### ISSUE TITLE
Failure to interact with bolt-remotion starter within bolt UI

### ISSUE THREAD

**Issue by chrismahoney** [stackblitz/bolt.new#10]
### Describe the bug

This could be due to browser configuration, but I don't believe so. Brave browser, latest public channel release

Reproduction:
1. Went to the bolt.new site, and clicked the 'Code a video with Remotion' starter button.
2. UI loads, AI chat displays 'Importing StackBlitz project (bolt-remotion)' and 'npm install && npm start' steps as expected.

Expected Behavior:
- The bolt-remotion project should properly display and be ready to interact with via the bolt UI.

Observed:
- Code and preview UIs are unpopulated. The console references five generic React minification errors #418 and #423.

Workaround (that didn't work unfortunately):
I figured I would try this, and what do you know... 🤣
- User Prompt: "Analyze the console for errors related to React minification"
  - Result: 
    - The user interface begins to generate the missing files realtime, AI response mentions adding ErrorBoundary.ts and some other remediation steps.
    - Opening the project in StackBlitz works and loads the Remotion project successfully.
    - **Encountered issue similar to those experienced in #6 and #9 where the generated code disappeared in bolt UI.**

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-remotion

### Steps to reproduce

See description

### Expected behavior

See description

### Platform

- OS: macOS Sequoia 15.0
- Browser: Brave
- Version: Latest release channel

**Comment by chrismahoney** [comment]
FYI, Brave comes with its own tracker blockers on by default, these steps were attempted with those default blockers enabled, and also completely turned off for bolt.new and stackblitz domains. This is probably a dupe of #9

**Comment by KwintenP** [comment]
I just tested in on latest Brave and it does seem to load now.

We did fix some bugs in between you testing it and now so maybe that was fixed as well.

Would you mind retrying?

**Comment by samdenty** [comment]
oops forgot to close this issue too, this was fixed

> This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back
