### ISSUE TITLE
After refreshing the page rollback disappears 

### ISSUE THREAD

**Issue by sisoalbert** [stackblitz/bolt.new#1001]
### Describe the bug

After the page refreshes the 
📍 Checkpoints!
🗨️ On every message!
🖱️ Roll back to in 1 click!

Disappears

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vanilla-vite-ycupbj

### Steps to reproduce

1. Make changes to any bolt.new
2. Refresh project
3. The rollback functionality disappears

### Expected behavior

1. Make changes to any bolt.new
2. Refresh project
3. The rollback functionality is still there

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
A fix for this is shipping today in #1104

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.
