### ISSUE TITLE
chat history 

### ISSUE THREAD

**Issue by fancreator** [stackblitz/bolt.new#1006]
### Describe the bug

if im developing with bolt and i refresh the page or exit and came back I loose the chat and the access to rollback points

### Link to the Bolt URL that caused the error

https://stackblitz.com/edit/sb1-we3ko5?file=index.html

### Steps to reproduce

if im developing with bolt and i refresh the page or exit and came back I loose the chat and the access to rollback points

### Expected behavior

if im developing with bolt and i refresh the page or exit and came back I loose the chat and the access to rollback points

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@fancreator progress on long term chat persistence (and instructions on how to continue work on your existing projects) can be found in issue #39

We will also be persisting rollbacks when the updates land!
