### ISSUE TITLE
My chat history disappeared

### ISSUE THREAD

**Issue by gitlevo** [stackblitz/bolt.new#1007]
### Describe the bug

Signed in with other device, my chat and tool is not available anymore - thats very disappointing as I invested 2 days in developing the thin with your tool and spent 16M tokens on it. Please restore my conversation.

<img width="434" alt="Bildschirmfoto 2024-10-27 um 17 05 00" src="https://github.com/user-attachments/assets/a3d96f1b-39f0-469f-9b8c-23f552c5a3f0">

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1 Sign on with github on my girlfriends device
2 dont see any chats or history....
3 everything is gone including 16M credits.

### Expected behavior

See my chat, continue working on it

### Platform

Google Chrome Browser

**Comment by ranrahav** [comment]
I got the same issue

**Comment by ayalpani** [comment]
I believe the history is only saved on your client. So if you switch to another client or delete you chrome caches, you have to restore your projects one by one by going into your stackblitz account and open them through "Collections":
 
<img width="651" alt="image" src="https://github.com/user-attachments/assets/d02af9a3-ba1c-42ab-bd9a-67a0afaf23a7">
