### ISSUE TITLE
 vTag- Problem - This message didn't complete its response.

### ISSUE THREAD

**Issue by sametburaksari** [stackblitz/bolt.new#1017]
### Describe the bug

This message didn't complete its response.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2kywmy

### Steps to reproduce

Hello, below is the working method using instructions in the form of no code. This message didn't complete its response.

### Expected behavior

To take my work to a better place than where I brought it

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93503024,
  "usedJSHeapSize": 86124464,
  "jsHeapSizeLimit": 2160066560
}
Username = sametburaksari
Chat ID = ce8d8ae67362
```

**Comment by kc0tlh** [comment]
@sametburaksari this is being tracked in #1073
