### ISSUE TITLE
se corta

### ISSUE THREAD

**Issue by barnamaq** [stackblitz/bolt.new#1019]
### Describe the bug

mientras empieza a trabajar se corta y sale pantalle en rojo y cuando vulves as de iniciar desde cero

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-w2x55m

### Steps to reproduce

solo sale un aviso de error ,quieres solucionarlo  , picas que si y se corta 

### Expected behavior

NotFoundError: No se pudo ejecutar 'insertBefore' en 'Nodo': el nodo antes del cual se insertará el nuevo nodo no es un hijo de este nodo.
    en ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    en je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Screen Recording / Screenshot

NotFoundError: No se pudo ejecutar 'insertBefore' en 'Nodo': el nodo antes del cual se insertará el nuevo nodo no es un hijo de este nodo.
    en ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    en je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89368595,
  "usedJSHeapSize": 74294739,
  "jsHeapSizeLimit": 2172649472
}
Username = barnamaq
Chat ID = dd68a6684b85
```

**Comment by barnamaq** [comment]
NotFoundError: No se pudo ejecutar 'removeChild' en 'Node': El nodo que se va a eliminar no es un hijo de este nodo.
    en Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:25974)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27253)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:30436)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:30436)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

**Comment by AriPerkkio** [comment]
Hey @barnamaq, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
