### ISSUE TITLE
// ... (keep existing code),   // ... (keep existing state),   // ... (keep existing functions) 

### ISSUE THREAD

**Issue by mateimmm** [stackblitz/bolt.new#102]
### Describe the bug

Those // ... (keep existing code),   // ... (keep existing state),   // ... (keep existing functions)  are ruining the entire app. 

Implementing the replace function it's a must have feature to not burn out tokens to write again and again the code

### Link to the Bolt URL that caused the error

for every project

### Steps to reproduce

ask to update an code with more than 100 -200 lines and will happen for sure...

### Expected behavior

To not replace the entire code

### Screen Recording / Screenshot

no

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Shabinder** [comment]
+1, This is irritating.

**Comment by alakaii** [comment]
agreed, this has caused me on several occasions to rebuild pages because it decided to throw out everything else.

**Comment by samdenty** [comment]
You can follow #124 to get notified when we've resolved this issue.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.

**Comment by mateimmm** [comment]
> **🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.

What will happen with the tokens which were already consumed becuse of the bug?  I'm already out of tokens because of its.
