### ISSUE TITLE
 This message didn't complete its response.

### ISSUE THREAD

**Issue by alteonn** [stackblitz/bolt.new#1020]
### Describe the bug

![image](https://github.com/user-attachments/assets/f876d283-456f-4394-8376-23a25dc0e0a6)
Get this messsage all the time or that the promt is to long when its 10 wordss

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vb7ypj

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e02ecbbc-2eb7-4433-a431-1fb329c772e6)

### Expected behavior

![image](https://github.com/user-attachments/assets/86f0976f-b59b-4dd5-bb46-7932e6050a33)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@alteonn this is being tracked in #1073
