### ISSUE TITLE
Prompt To Long on a simple sentence draining tokens

### ISSUE THREAD

**Issue by CISOMarketplace** [stackblitz/bolt.new#1025]
### Describe the bug

I am typing a simple error fix as it's stuck in some kind of loop where it starts to fix a file but then half way through it just stops and errors out. 

Now i'm just getting prompt is too long: 200223 tokens > 199999 maximum error time and it's draining me 200,000 tokens at a clip. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vvsn9f

### Steps to reproduce

All i'm doing is typing a prompt to fix the error that it go itself in from some kind of error looping then it just says my prompt is to long when all i'm doing is telling to fix the error code or sometime adding screenshot to help diagnose

### Expected behavior

It should be finishing editing as it edits the entire code within a file. instead of stopping half way through to error out fixing the half way written code

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91695379,
  "usedJSHeapSize": 81675999,
  "jsHeapSizeLimit": 2172649472
}
Username = cisomarketplace
Chat ID = e9d8051c88d0
```

**Comment by CISOMarketplace** [comment]
wow I want a couple million tokens in refund because now i'm just getting: Deploy Application Button to prompt is too long: 200765 tokens > 199999 maximum

**Comment by CISOMarketplace** [comment]
wow I want a couple million tokens in refund because now i'm just getting: Deploy Application Button to prompt is too long: 200765 tokens > 199999 maximum

**Comment by kevinnkansah** [comment]
Bolt is using a fake mechanism to consume tokens, its synthetic not real like Cline, greedy bastards

https://www.youtube.com/watch?v=rOwSQWFHqsI&lc=UgzdB85HeFH7getNB7F4AaABAg

**Comment by kc0tlh** [comment]
@CISOMarketplace thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!

Please reach out to hello@stackblitz.com with a specific request around credit!
