### ISSUE TITLE
Bolt.newPreview doesn't work, scren is blank

### ISSUE THREAD

**Issue by Zeno1234** [stackblitz/bolt.new#1026]
### Describe the bug

 can not resolve after many attempts as to why the Preview is not functioning. It has worked well for sometime,but can not solve the issue now.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jx4mau

### Steps to reproduce

ask it to as to why there is no Preview as I have done in many different ways

### Expected behavior

I expect the Preview to display the Ui and the Ui to work

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = Zeno1234
Chat ID = 8447df9f7bd8
```

**Comment by Zeno1234** [comment]
It gets like in a Doom Loop and keeps try the same solutions over and over

**Comment by Zeno1234** [comment]
It always says something is empty or missing a dependency. You would think that this would be easier to solve?

**Comment by Zeno1234** [comment]
This is like the Blue Screen of Death. So what I did was close it out and restart the program. Kind of like dealing with Microsoft Windows. Hahaha!

**Comment by endocytosis** [comment]
Hi @Zeno1234, 

We are aware of this issue and are tracking it here: #1791.
