### ISSUE TITLE
Bolt New -- all credits used on debugging something that was working

### ISSUE THREAD

**Issue by KemotRuns** [stackblitz/bolt.new#1032]
### Describe the bug

I built a website application, it looked perfect in preview, i tried to deploy and it errored out every time. When I tried to view it in preview again and asked to view it in preview it never could go back to the perfectly working website. No I still can't see it in preview and I feel like I wasted all of my tokens trying to fix an error. Spent over 3 million tokens trying to fix the error - the website app was alredy working in preview. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lbfcti

### Steps to reproduce

I just ask it to try and show me the application in preview -- which it used to show, but nothing happens 

### Expected behavior

I would like to see my working web application - it was working well. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64575189,
  "usedJSHeapSize": 59419837,
  "jsHeapSizeLimit": 2160066560
}
Username = KemotRuns
Chat ID = 82bae634861c
```

### Additional context

It feels like the error fixing mechanism could not do anything, just use my tokens. The problem is that my website applicaiton was working as I wanted earlier - then it broke when i tried to deploy it and then it was never even viewable in preview.

**Comment by kc0tlh** [comment]
Apologies for the frustration. There are many tips in #678 (including using Rollbacks) that will allow you to avoid this issue in the future!
