### ISSUE TITLE
netlift rate bit

### ISSUE THREAD

**Issue by Gumrukdoktoru** [stackblitz/bolt.new#1033]
### Describe the bug

netlift rate bit

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ooscyh

### Steps to reproduce

netlift rate bit

### Expected behavior

netlift rate bit

### Screen Recording / Screenshot

netlift rate bit

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 163909528,
  "usedJSHeapSize": 151490268,
  "jsHeapSizeLimit": 4294705152
}
Username = gumrukdoktoru
Chat ID = e39fea9aaa38
```netlift rate bit

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
@Akshay115 this issue is being tracked in #1037
