### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by 0phl** [stackblitz/bolt.new#1034]
### Describe the bug

Why all of the sudden my chat history is gone, i have an ongoing experimental project that im creating and now i cannot see it on my chat history, i didn't even delete my chat history.

![image](https://github.com/user-attachments/assets/ebd1b721-f210-4485-bc58-c0df553247e3)

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

chat history missing

### Expected behavior

its not suppose to delete my chat history

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/8056e3a7-f5b1-4c6a-bb90-e8ed15c9385d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@0phl progress on long term chat persistence (and instructions on how to continue work on your existing projects) can be found in issue #39
