### ISSUE TITLE
Unable to deploy the application.

### ISSUE THREAD

**Issue by Akshay115** [stackblitz/bolt.new#1035]
### Describe the bug

Unable to deploy the application.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yatawa

### Steps to reproduce

Unable to deploy the application.

### Expected behavior

It must deploy the website to Netlify.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66536581,
  "usedJSHeapSize": 58513293,
  "jsHeapSizeLimit": 2172649472
}
Username = Akshay115
Chat ID = 8ed75a09d098
```

**Comment by kc0tlh** [comment]
@Akshay115 this issue is being tracked in #1022
