### ISSUE TITLE
 prompt is too long: 209062 tokens > 199999 maximum

### ISSUE THREAD

**Issue by aiwu66** [stackblitz/bolt.new#1036]
prompt is too long: 209062 tokens > 199999 maximum
我不知道这个问题怎么解决，我的项目还有吗完成

**Comment by CISOMarketplace** [comment]
Same with my project and it nuked millions of tokens before realizing, i have a ticket open from last night

**Comment by kc0tlh** [comment]
@aiwu66 @CISOMarketplace thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!
