### ISSUE TITLE
Deployment Error: We ran into a Netlify rate limit error, please try again in a bit

### ISSUE THREAD

**Issue by OluStayhired** [stackblitz/bolt.new#1037]
### Describe the bug

I'm currently using Bolt to build an application and trying to deploy the application. Everytime I try I run into the error below:

We ran into a Netlify rate limit error, please try again in a bit.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ru6s7c

### Steps to reproduce

1. Go to Bolt and open the project
2. Type in the AI chat area "Deploy This Application"
3. Deployment to Netlify resumes
4. But then the error is reported 
![image](https://github.com/user-attachments/assets/7f324a28-a574-4e2d-9236-d44b6ad4c095)

### Expected behavior

The Application should be deployed

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/453b2ac7-5b00-46b5-9c51-12456e9f2bfd)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 281574475,
  "usedJSHeapSize": 258543211,
  "jsHeapSizeLimit": 4294705152
}
Username = olu_vc
Chat ID = 46178ee01c2e
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
This has been escalated to engineering for review!

**Comment by kc0tlh** [comment]
This issue was due to us hitting Netlify deployment rate limits. We've reached out to them, and they have increased our rate limit, so **this issue should be resolved!** Please comment below if you are still experiencing the issue.
