### ISSUE TITLE
Reate limit issue on netlify

### ISSUE THREAD

**Issue by stevejford** [stackblitz/bolt.new#1038]
### Describe the bug

I tried to redeploy 3nd time today and got rate limited

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qwy7sm

### Steps to reproduce

Deploy

### Expected behavior

Deploy this application.

I'll help you deploy the application to Netlify.

Deploy to Netlify

netlify
Let me check the deployment status to get the live URL.

We ran into a Netlify rate limit error, please try again in a bit.

### Platform

```
Browser name = Chrome
Full version = 132.0.0.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 267966854,
  "usedJSHeapSize": 128862326,
  "jsHeapSizeLimit": 4294705152
}
Username = stevejford
Chat ID = 603c6175e2b5
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
@Akshay115 this issue is being tracked in #1037
