### ISSUE TITLE
cant deploy

### ISSUE THREAD

**Issue by djahlor** [stackblitz/bolt.new#1039]
### Describe the bug

deployment issue. i wanted to deploy a nextjs starter kit https://github.com/michaelshimeles/nextjs-starter-kit (forked) to be able to set up clerk auth since ngrok isnt a possiblility. not sure how to workaround. stuck. ✌️

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-tkxufn

### Steps to reproduce

-

### Expected behavior

-

### Screen Recording / Screenshot

-

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94988117,
  "usedJSHeapSize": 90141429,
  "jsHeapSizeLimit": 4294705152
}
Username = djahlor
Chat ID = 824b6c6637e9
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
@djahlor this issue is being tracked in #1037
