### ISSUE TITLE
Chats are gone

### ISSUE THREAD

**Issue by mrexodia** [stackblitz/bolt.new#1041]
### Describe the bug

My chats from a few days ago no longer show up in the user interface.

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

1. Create some chats
2. Wait a few days
3. The chats are gone

### Expected behavior

The chats should be preserved (I paid for premium)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@mrexodia progress on long term chat persistence (and instructions on how to continue work on your existing projects) can be found in issue #39
