### ISSUE TITLE
Probleme to deploy my project and get the code files 

### ISSUE THREAD

**Issue by Quentinup** [stackblitz/bolt.new#1043]
### Describe the bug

I can not export or deploy my project anywhere, even to share to my dev

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-x3iazw

### Steps to reproduce

I click on deploy only, thne it showing the error message.

### Expected behavior

I would like to get the files or find a way to share the acces to the code that bolt developp concerning my project to my dev to link the app with my actual dashboard.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 242137810,
  "usedJSHeapSize": 225188690,
  "jsHeapSizeLimit": 2160066560
}
Username = Quentup
Chat ID = 63f6c432c0d1
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
@Quentinup this issue is being tracked in #1037
