### ISSUE TITLE
Netlify deploy issue

### ISSUE THREAD

**Issue by shaundataninja** [stackblitz/bolt.new#1044]
### Describe the bug

I am trying to deploy my app and am getting this issue
We ran into a Netlify rate limit error, please try again in a bit.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pfj93m

### Steps to reproduce

I try deploy and it fails

### Expected behavior

I expect it to deploy

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57300404,
  "usedJSHeapSize": 48733968,
  "jsHeapSizeLimit": 4294705152
}
Username = shaundataninja
Chat ID = d82d095b2605
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
@shaundataninja this issue is being tracked in #1037
