### ISSUE TITLE
We ran into a Netlify rate limit error, please try again in a bit.

### ISSUE THREAD

**Issue by Gumrukdoktoru** [stackblitz/bolt.new#1046]
### Describe the bug

We ran into a Netlify rate limit error, please try again in a bit.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3gj6zd

### Steps to reproduce

We ran into a Netlify rate limit error, please try again in a bit.

### Expected behavior

We ran into a Netlify rate limit error, please try again in a bit.

### Screen Recording / Screenshot

We ran into a Netlify rate limit error, please try again in a bit.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 230107192,
  "usedJSHeapSize": 216574560,
  "jsHeapSizeLimit": 4294705152
}
Username = gumrukdoktoru
Chat ID = 0696edab05dd
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
@Gumrukdoktoru  this issue is being tracked in #1037
