### ISSUE TITLE
Bug: "prompt is too long: 210085 tokens > 199999 maximum" Error on Simple Operations

### ISSUE THREAD

**Issue by gboross** [stackblitz/bolt.new#1047]
### Describe the bug

I'm experiencing a persistent issue in the bolt.new project where the application consistently throws an error related to prompt length, even when performing simple tasks. This issue is occurring despite the project's large size, which previously did not present this problem.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ymebn1

### Steps to reproduce

Navigate to [specific section or feature] in the application.
Perform [specific action, e.g., "generate a simple translation" or "render a basic component"].
Observe the error message in the console or UI.

### Expected behavior

The operation should execute successfully without exceeding the prompt token limit.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83662710,
  "usedJSHeapSize": 65957618,
  "jsHeapSizeLimit": 4294705152
}
Username = gboros
Chat ID = effe9401173f
```

**Comment by rryati20** [comment]
Have the same issue after 3 days of working on my project.

**Comment by CISOMarketplace** [comment]
Same with my project and it nuked millions of tokens before realizing, i have a ticket open from last night
