### ISSUE TITLE
Not able to deploy

### ISSUE THREAD

**Issue by sergiomago** [stackblitz/bolt.new#1048]
### Describe the bug

When trying to deploy the chat gets frozen and nothing happens. I waited for a while and also tried to retry and then it says: "We ran into a Netifly rate limit error, please try again in a bit."

Even trying again it keeps on the same error and the chat is frozen. I cannot write anything there.

Also tried with different browsers and it happens the same. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ae7ewz

### Steps to reproduce

Ask to deploy

Wait for to be deployed or an answer

### Expected behavior

To deploy the app or at least to share what the status is and not have the chat box frozen

### Screen Recording / Screenshot

<img width="485" alt="Screenshot 2024-10-28 at 13 43 39" src="https://github.com/user-attachments/assets/ac75fa4d-327f-4b6e-88ae-6a116d7e85c3">

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = sergiomago
Chat ID = cde10d5fa0bd
```

**Comment by kc0tlh** [comment]
@sergiomago this issue is being tracked in #1037
