### ISSUE TITLE
Local Installer does not work

### ISSUE THREAD

**Issue by bamit99** [stackblitz/bolt.new#105]
Installed it locally. Followed the steps for both Windows and WSL separately and yet when I launch the browser, type a task and press enter, the cursor just moves to next line with nothing starting. No button to click or anything etc. I can give more logs if needed but checking if this is a new issue or just my machine.

![image](https://github.com/user-attachments/assets/759d77d4-d9bc-412a-9389-dc4020cd9950)

**Comment by Six6pounder** [comment]
you have to build and start, not using the dev one

`pnpm build` && `pnpm start`

then go to http://localhost:8788/

**Comment by kirjavascript** [comment]
> you have to build and start, not using the dev one
> 
> `pnpm build` && `pnpm start`
> 
> then go to http://localhost:8788/

thanks for answering!

@bamit99 can you confirm it's working after following those instructions?

**Comment by bamit99** [comment]
Getting the same error in both Windows and WSL but with a different verbiage. Error about Binding.sh etc.

![image](https://github.com/user-attachments/assets/3a5dd2e6-09ba-45cb-b9bf-cc4e972f9d31)

**Comment by samdenty** [comment]
https://github.com/stackblitz/bolt.new/pull/157
