### ISSUE TITLE
Can't access projects 

### ISSUE THREAD

**Issue by bradical1979** [stackblitz/bolt.new#1050]
### Describe the bug

It's saying no previous convresations, I can't access my current projects. Also the UI for even managing projects is super hard to see 

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

Just trying to go to a  project i'm working on

### Expected behavior

I expect to see my projects

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@bradical1979 progress on long term chat persistence (and instructions on how to continue work on your existing projects) can be found in issue #39
