### ISSUE TITLE
 We ran into a Netlify rate limit error, please try again in a bit.

### ISSUE THREAD

**Issue by quentintou** [stackblitz/bolt.new#1052]
### Describe the bug

We ran into a Netlify rate limit error, please try again in a bit.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pz2ceh

### Steps to reproduce

click on deploy

### Expected behavior

deploy

### Screen Recording / Screenshot

https://markuphero.com/share/BqYfdzyo8uJrrHJBf9As

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77439201,
  "usedJSHeapSize": 67502421,
  "jsHeapSizeLimit": 4294705152
}
Username = quentintou
Chat ID = 43b535cb9cac
```

### Additional context

Error:
```
We ran into a Netlify rate limit error, please try again in a bit.
```

**Comment by kc0tlh** [comment]
This has been resolved in #1037
