### ISSUE TITLE
Whole project deleted

### ISSUE THREAD

**Issue by AntonWir** [stackblitz/bolt.new#1055]
### Describe the bug

Hi, my whole project was deleted and there is no version I can access anymore. How can you support?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dfjsg9

### Steps to reproduce

see below

### Expected behavior

I want my old project back or at least new tokens to restart the project.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by rryati20** [comment]
Hey any luck with restoring your files..? My project is also deleted after 3 days of work.

**Comment by rryati20** [comment]
Update found a fix, instead of hitting roll back to checkpoint, if you still have your website up with some code left, hit "undo" instead. It restored my files from before.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.

**Comment by AntonWir** [comment]
Hello,

thank you. It's working.

Anton

Am Di., 29. Okt. 2024 um 23:01 Uhr schrieb Alexander Berger <
***@***.***>:
