### ISSUE TITLE
My project files are deleted

### ISSUE THREAD

**Issue by iwt-nihadalic** [stackblitz/bolt.new#1056]
### Describe the bug

I was working on an application and everything was working fine and all of a sudden my project src directory was deleted and gone!

Here is the application published - working link https://cozy-sable-e2ba09.netlify.app/

Can I get back my project files ? 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-shadcn-zhmdap

### Steps to reproduce

It happend without any reason and I don't know how to reproduce. 

### Expected behavior

Project files must never be deleted!

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63037164,
  "usedJSHeapSize": 60402596,
  "jsHeapSizeLimit": 4294705152
}
Username = dd-ghadmin
Chat ID = e7a2abd83bad
```

**Comment by rryati20** [comment]
Hey any luck with restoring your files..? My project is also deleted after 3 days of work.

**Comment by rryati20** [comment]
Update found a fix, instead of hitting roll back to checkpoint, if you still have your website up with some code left, hit "undo" instead. It restored my files from before.

**Comment by kc0tlh** [comment]
@iwt-nihadalic It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.

**Comment by rririanto** [comment]
Hi @kc0tlh could you help me restore my project: https://stackblitz.com/edit/sb1-vpdzsuqc I'm subscribing but accidentaly remove the project because I dont know bolt.ai connect with stackblitz. Please help, I spend many hours for that.
