### ISSUE TITLE
when rolling back to checkpoint, all folders are deleted

### ISSUE THREAD

**Issue by gitlevo** [stackblitz/bolt.new#1059]
### Describe the bug

All folders with src files etc were deleted when roling back to checkpoint

![Bildschirmfoto 2024-10-28 um 16 30 35](https://github.com/user-attachments/assets/fbabba92-402c-41da-8877-68adecfe5064)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7v7d6s

### Steps to reproduce

Rollback to checkpoint

### Expected behavior

restore the files as it where at that checkpoint

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75311411,
  "usedJSHeapSize": 71325123,
  "jsHeapSizeLimit": 4294705152
}
Username = gitlevo
Chat ID = 80353a582032
```

**Comment by yoran-bosch** [comment]
Same issue. All my progress, all code files are lost now. Is there any way to revert this and get it back to how it was?

**Comment by rryati20** [comment]
Hey any luck with restoring your files..? My project is also deleted after 3 days of work.

**Comment by rryati20** [comment]
Update found a fix, instead of hitting roll back to checkpoint, if you still have your website up with some code left, hit "undo" instead. It restored my files from before.

**Comment by dubtor** [comment]
same problem here

**Comment by kc0tlh** [comment]
@gitlevo, @yoran-bosch, @dubtor: It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.
