### ISSUE TITLE
Help i lost most of the folders of my proyect

### ISSUE THREAD

**Issue by AugustoPrz** [stackblitz/bolt.new#1060]
### Describe the bug

so after a bad deploy and then a refresh i lost most of the folder files of my proyect 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vtdezq

### Steps to reproduce

go to bolt, select https://bolt.new/~/sb1-vtdezq chat, then try to deploy, no code all lost

### Expected behavior

i should be able to see this folders
![image](https://github.com/user-attachments/assets/c74da0b1-d2c1-40ff-a6ca-a7003d8af5a4)

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/682574cb-f1ed-49f6-aa68-93c0232b1dc1)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55411247,
  "usedJSHeapSize": 52540619,
  "jsHeapSizeLimit": 2172649472
}
Username = AugustoPrz
Chat ID = 3e0f890bb464
```

**Comment by rryati20** [comment]
Hey any luck with restoring your files..? My project is also deleted after 3 days of work.

**Comment by kc0tlh** [comment]
@AugustoPrz It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.
