### ISSUE TITLE
All project files deleted.

### ISSUE THREAD

**Issue by rryati20** [stackblitz/bolt.new#1062]
### Describe the bug

Working on a project, it was going fine despite the amount of token consumption I am using for issues that should not be there. Have been working tirelessly on this for many hours and days. All files are now lost... really hope there is a fix to this as I have sunk over $200 a month plan into this project.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sf3kew

### Steps to reproduce

Type anything to have code deleted, I believe I rolled back to checkpoint and this is what happened. 

### Expected behavior

Have my files back hopefully 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ae36c1ed-d3b3-4feb-bcd1-a724168fd73a)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 196573304,
  "usedJSHeapSize": 188661356,
  "jsHeapSizeLimit": 4294705152
}
Username = rryati20
Chat ID = a9b60678c970
```

**Comment by kc0tlh** [comment]
@rryati20 It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Based on your comments on other folks issues on this topic, it sounds like you found a workaround via the undo button.

Apologies for the frustrating experience! Thanks for your patience, and feel free to reach out if there is anything else we can help you with!
