### ISSUE TITLE
All my work dissapeared ...

### ISSUE THREAD

**Issue by istefka** [stackblitz/bolt.new#1063]
### Describe the bug

seems like there was an error and from there it lost my whole app!!!

Kt says now that's setting up the project from scratch.... 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zwb2s3

### Steps to reproduce

... just go in the conversation!!!

### Expected behavior

It should be remebering the 50 million tokens I used!

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87128755,
  "usedJSHeapSize": 79637743,
  "jsHeapSizeLimit": 4294705152
}
Username = istefka
Chat ID = 738fdd3ff27a
```

**Comment by rryati20** [comment]
Hey any luck with restoring your files..? My project is also deleted after 3 days of work.

**Comment by rryati20** [comment]
Update found a fix, instead of hitting roll back to checkpoint, if you still have your website up with some code left, hit "undo" instead. It restored my files from before.

**Comment by kc0tlh** [comment]
@istefka It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.
