### ISSUE TITLE
Custom Netlify Domain

### ISSUE THREAD

**Issue by tymoking** [stackblitz/bolt.new#1066]
### Describe the bug

I'm trying to deploy my website with my custom domain that I setup in Netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mcvauj

### Steps to reproduce

Try to deploy the app.

It will say it's deploying to my custom domain but ends up deploying to a new random Netlify domain.

### Expected behavior

It should deploy to heyvictoria.ai

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72873438,
  "usedJSHeapSize": 67517302,
  "jsHeapSizeLimit": 4294705152
}
Username = tymoking
Chat ID = 016fa9ee400c
```

**Comment by endocytosis** [comment]
Hi @tymoking, 

The team is aware of this feature request which is being tracked [here](https://github.com/stackblitz/bolt.new/issues/49), along with some potential workarounds.
