### ISSUE TITLE
Chats in the side bar are missing.

### ISSUE THREAD

**Issue by Habartru** [stackblitz/bolt.new#1067]
### Describe the bug

Hi ! I had 2 projects - 2 side bar chats. The last time was on 10/28.24 at 17.30 I finished editing the project and logged in 3 hours later on another PC and I don't see my projects in the sidebar.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-duyvsq

### Steps to reproduce

I log in, enter the menu, I don't see the chats

### Expected behavior

well, I want to see my projects)

### Screen Recording / Screenshot

![2024-10-28_20-42-02](https://github.com/user-attachments/assets/4c31fef3-7e60-4353-85e1-72c86593e829)

### Platform

- OS: [Windows 10]
- Browser: [Chrome browser, Calibri, Yandex browser, Opera.  The result is the same everywhere.]

**Comment by kc0tlh** [comment]
@Habartru progress on long term chat persistence (and instructions on how to continue work on your existing projects) can be found in issue #39
