### ISSUE TITLE
Complaint Regarding Issues with Bolt.new Platform

### ISSUE THREAD

**Issue by fuadoglu** [stackblitz/bolt.new#1069]
### Describe the bug

Dear Bolt.new Team,

I am writing to share my concerns about some issues I’ve encountered while using your platform. I was genuinely excited to use Bolt.new for my projects, but unfortunately, the experience has not been as smooth as expected. Below are the key problems I’ve faced:

Projects disappearing
I’ve created two different projects, both of which took considerable time and effort. However, each time, my projects disappeared without being completed, forcing me to start from scratch. This has been very frustrating and has wasted a lot of my time.
Long dependency installation and app start issues
Whenever I try to move forward, the "Installing dependencies" step takes hours without finishing, and the "Start application" option never works. This has completely blocked my ability to complete my projects.
Wasted tokens and unhelpful support
Despite multiple attempts to get help, the issues remain unresolved, and my tokens are being consumed in the process. This has been a disappointing experience, both in terms of time and resources.
I would greatly appreciate it if you could address these issues promptly and provide compensation for the wasted tokens. I had high expectations for the platform, and I am still hopeful that these problems can be fixed soon.

However, if these issues continue, I may need to consider other alternatives, as it would be difficult to continue using Bolt.new under these circumstances.

Thank you for your time and attention. I look forward to hearing from you soon and seeing these issues resolved.

Best regards,
Rizvan

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xsycbj

### Steps to reproduce

The project I prepared is no longer available. First, it disappeared from the sidebar on the left. When I try to access it through the link, the code is missing.

### Expected behavior

Expected behavior:

The project name and details should appear in the sidebar on the left.
When accessing the project via the provided link, all code and files should be visible and available.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@fuadoglu first, please check to ensure that your project is not just stored in your StackBlitz account by following the [instructions here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671).

If your project cannot be found using the method linked above, then you have likely been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.
