### ISSUE TITLE
An error occured while trying to deplay

### ISSUE THREAD

**Issue by ViciousSquare** [stackblitz/bolt.new#1070]
### Describe the bug

I continue to get this error message and can't get around it : 

Deploy React Application to Netlify

npm run build
netlify
I've initiated the deployment process to Netlify. Let me check the deployment status to get the URL where your site will be accessible.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mmsdg2

### Steps to reproduce

It's stuck on this and can't get through. 

### Expected behavior

I expected it to deploy. 

### Screen Recording / Screenshot

<img width="1440" alt="Screenshot 2024-10-28 at 2 32 40 PM" src="https://github.com/user-attachments/assets/df2037f6-e1c9-46f6-a455-07827afc2447">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90084446,
  "usedJSHeapSize": 79112018,
  "jsHeapSizeLimit": 2160066560
}
Username = ViciousSquare
Chat ID = 6ce31b298b8b
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@ViciousSquare this issue is being tracked in #1022
