### ISSUE TITLE
Repeating Errors: "This message didn't complete its response." 

### ISSUE THREAD

**Issue by Meabo** [stackblitz/bolt.new#1072]
### Describe the bug

I keep having this issue during my generations

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-racrku

### Steps to reproduce

Prompt: "Now from that DESIGN_SYSTEM.md

1. Update shadcn-ui theme with design tokens 2. Remove AI Generate tab 3. Create fullscreen LinkedIn content editor: - Adapt video editor layout for text content - Ensure design system consistency 4. Audit and update components to match design system 5. Document any design system deviations
Please provide UI inspiration screenshots to proceed."

### Expected behavior

Update the UI

### Screen Recording / Screenshot

<img width="1722" alt="image" src="https://github.com/user-attachments/assets/b71c6735-0c4c-470e-853b-d491c2deb512">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60613515,
  "usedJSHeapSize": 53600699,
  "jsHeapSizeLimit": 4294705152
}
Username = Meabo
Chat ID = c8cc8da1c0a0
```

**Comment by kc0tlh** [comment]
Thanks for the report! This has been escalated to engineering, and resolution will be tracked in #1073

**Comment by Meabo** [comment]
Thanks however I have consumed a lot of tokens with these errors, is there anyway to get back tokens? @kc0tlh

**Comment by kc0tlh** [comment]
@Meabo Please reach out to hello@stackblitz.com with a specific request!
