### ISSUE TITLE
Chat Error: This Message Didn't Complete It's Response

### ISSUE THREAD

**Issue by mmpavao** [stackblitz/bolt.new#1073]
### Update From StackBlitz on 11/12/24
We have identified the core issue and are working on implementing a fix!

### Describe the bug

**Current Behavior:**
Responses frequently fail to complete
Each failed attempt consumes tokens
Retries often fail with the same error
Token balance depletes rapidly due to failed attempts
Additional Context:

<img width="1428" alt="Captura de Tela 2024-10-28 às 14 43 49" src="https://github.com/user-attachments/assets/0396af5d-8840-48ca-95c5-a75c1c90b862">

**Expected Behavior:**
Responses should complete successfully
Failed responses should not consume tokens
Retry mechanism should resolve incomplete responses
Token consumption should only occur for successful responses

### Link to the Bolt URL that caused the error
https://bolt.new/~/sb1-ah5uab

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 140633173,
  "usedJSHeapSize": 138524853,
  "jsHeapSizeLimit": 2160066560
}
Username = mmpavao
Chat ID = 90e70213a98e
```

**Comment by kc0tlh** [comment]
This issue has been escalated to engineering for investigation!

**Comment by mmpavao** [comment]
As you can see in the photos and you can also see here at remittz.com a project that was going very well... but I'm simply stopped because it's impossible to continue, I spent all the millions of tokens trying to solve it but the platform after these errors says that there aren't enough tokens in my prompts... even though they are 2 or 3 lines of words... and then it gives an error in the bolt interface and I lose the restore points... I practically lost the project! because I can no longer recover the version that was working.

**Comment by kc0tlh** [comment]
@mmpavao we are very focused on resolving this for you, and everyone else experiencing it! We are having a number of calls tomorrow AM to dig further into this.

**Comment by jmdelatorre** [comment]
Any updates to this? My project started responding this and nothing works now

**Comment by kc0tlh** [comment]
@jmdelatorre the team is chatting live about this as we speak!
![image](https://github.com/user-attachments/assets/6aff297e-a2e0-4ddb-a7fe-d8a7606d3e62)

We met with our external AI model provider this morning and gathered some information on where to dig deeper, but It has been a more difficult than expected to isolate the issue. This is one of our top prio issues at the moment and I will continue to provide updates here as we learn more! Appreciate everyone's patience during this beta period.

**Comment by katetrahan** [comment]
Hello! We recently covered how the bolt.new team is working to optimize performance and reduce token usage in our latest Office Hours session. You can watch the clip from our Office Hours session on the diff-based approach here: https://www.youtube.com/watch?v=YBZTXNFVxD0

Or check out the full bolt.new Office Hours session here: https://www.youtube.com/watch?v=Ktr9ER7Jgts

Also check out the Diffs preview URL: https://1f1a1008.bolt-cnr.pages.dev/

**Comment by Sushantshr** [comment]
Same issue cannot work with bolt

**Comment by kc0tlh** [comment]
**📣 Update:** We have identified the core issue and implemented what we believe to be the fix! Appreciate all the reports as patience as we worked this tricky issue!

_If you are still experiencing this error, please tag me, share a screenshot, your project URL, and a screenshot below!_

**Comment by cskiwi** [comment]
I still have it:
![image](https://github.com/user-attachments/assets/49d8b546-c250-4cef-967f-8160be888690)

https://bolt.new/~/github-59lgki

@kc0tlh

**Comment by aniketbankapur02** [comment]
![Screenshot 2024-11-13 105130](https://github.com/user-attachments/assets/cf39fc77-5815-415a-b002-1db2641aa86c)
https://bolt.new/~/sb1-15gu7w
@kc0tlh

**Comment by aniketbankapur02** [comment]
![Screenshot 2024-11-14 131505](https://github.com/user-attachments/assets/2efc2214-cc55-4d30-8c84-a5bf8e81c1e0)

chat disabled ? Now it will not work in free tier?:( 😢 
@kc0tlh

**Comment by fscheps** [comment]
I am having this same issue This message didnt complete its response. Any ideas?

**Comment by nnnext** [comment]
same here - somethimes its ok. most times are not.
![image](https://github.com/user-attachments/assets/e14fbd12-0e51-432d-9695-3d6f4db6f376)

**Comment by vanillabrand** [comment]
I still get this error message. Seems to be with larger projects. :(

**Comment by colindacity** [comment]
I get this frequently as well

**Comment by waqasaca** [comment]
i am still having this issue. i already have consumed a lot of tokens on it and its so frustrating to see this error again and again. can someone please tell me how to get this resolved ?
