### ISSUE TITLE
"It seems that my entire project has been deleted, and I see that it has happened to other people in the community as well."

### ISSUE THREAD

**Issue by rubenmarques-gijon** [stackblitz/bolt.new#1078]
### Discussed in https://github.com/stackblitz/bolt.new/discussions/1077

<div type='discussions-op-text'>

<sup>Originally posted by **rubenmarques-gijon** October 28, 2024</sup>
"A complete project of mine got deleted right at the end, just when I clicked to recover at a point in the conversation, as I've done many times before. At that moment, the folders appeared empty.

Do you know if there's any way to recover it? I had spent 12 million tokens."</div>

**Comment by rubenmarques-gijon** [comment]
https://[bolt.new/~/sb1-znpcnb](https://bolt.new/~/sb1-znpcnb)

**Comment by kc0tlh** [comment]
@rubenmarques-gijon It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.
