### ISSUE TITLE
Complete project got wiped out

### ISSUE THREAD

**Issue by Maanav-gambit** [stackblitz/bolt.new#1079]
### Describe the bug

Hello! 
I was building a chess platform since many days on bolt using stackblitz. Today i logged in to continue working on it. After giving one prompt that didnt give me the desired results, i clicked on the rollback to checkpoint option before the prompt. It rolled back but ended up encountering some errors and showing a blank white screen instead of the platform in the preview section. When i prompted it to fix this issue, it ended up completely wiping out my project and resetting it.
I request you to please restore my project if possible to the version it was before all this mishap. For reference, please restore it to what it was before Tuesday 12am Indian Standard Time. I had put in a lot of effort and time into making the project. Please help me.
Best regards,
Maanav Sharma

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zqwpgy

### Steps to reproduce

the entire project components have been wiped out. the project has been reset to scratch. the preview section is now displaying Node.js project starter.

### Expected behavior

I expected it to undo my last prompt and rollback to checkpoint. I didnt expect it to wipe out my entire project.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58762219,
  "usedJSHeapSize": 54455771,
  "jsHeapSizeLimit": 4294705152
}
Username = Maanav-gambit
Chat ID = fb356cfc4f44
```

**Comment by kc0tlh** [comment]
@Maanav-gambit It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.

**Comment by Maanav-gambit** [comment]
The new backups feature didn't help. The oldest backup is still after the project files got deleted. The target timestamp is around 2 hours before the oldest backup. I'll be needing some personal help if possible. I have reached out on #1104 and emailed the required details on help@stackblitz.com. Really appreciate you guys trying to help out. Thanks in advance!
