### ISSUE TITLE
When revisiting projects, I'd like to read my conversation logs

### ISSUE THREAD

**Issue by MarcusHSmith** [stackblitz/bolt.new#1080]
**Is your feature request related to a problem? Please describe:**

I would like to read (and learn from) previous conversations while building an app.

I think I had a bug in Bolt and wanted to read the conversations and code written to understand if there was a bug learn more about bolt.

**Describe the solution you'd like:**

I'd like to read my conversation log and see what code was written/changed. 
![Screenshot 2024-10-28 at 12 59 42](https://github.com/user-attachments/assets/753a8322-d0d6-408d-8a5a-aed39172acbd)

**Describe alternatives you've considered:**

It could be provided anywhere, just need to go back

**Additional context:**

**Comment by kc0tlh** [comment]
This is coming soon! Updates will be posted in #39
