### ISSUE TITLE
Entire work wiped out

### ISSUE THREAD

**Issue by neha0072026** [stackblitz/bolt.new#1083]
### Describe the bug

the entire project components have been wiped out. the project has been reset to scratch. the preview section is now displaying Node.js project starter.
Wasted all token. Please fix it asap.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8cczut

### Steps to reproduce

the entire project components have been wiped out. the project has been reset to scratch. the preview section is now displaying Node.js project starter.
Wasted all token. Please fix it asap.

### Expected behavior

please recover last work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62790917,
  "usedJSHeapSize": 45242461,
  "jsHeapSizeLimit": 4294705152
}
Username = neha0072026
Chat ID = 304c9d392335
```

**Comment by kc0tlh** [comment]
@neha0072026 & @TLWPS  It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.

**Comment by FreeStylr** [comment]
what's never affected, though, is how quickly those tokens are being wiped out. Stripe is working perfectly too... :(
