### ISSUE TITLE
This is unusable at this point

### ISSUE THREAD

**Issue by JKdreaming** [stackblitz/bolt.new#1084]
### Describe the bug

I was working pretty good for a while, creating a slider in Shopify with this app, but now it starts creating things that I didn't tell it to and on top of that instead of working on the code that I threw inside the prompt ignore it completely and none of my chats have been saved. What's going on here? This is kind of a nightmare, and the worst thing is none of this started happening until I paid lol also, I can't give you a URL in the area below because your software doesn't save the chats so far.

### Link to the Bolt URL that caused the error

No links available no saving chats so far

### Steps to reproduce

All I'm trying to do is make a liquid JS file and I put in a prompt like this below…

I'd like you to think like a liquid JS Shopify expert please analyze the code below and help me make changes:

{% schema %}
{
  "name": "Two Column Slider",
  "settings": [
    {
      "type": "color",
      "id": "section_bg",
      "label": "Section Background",
      "default": "transparent"
    },
    {
      "type": "header",
      "content": "Slider Settings"
    },
    {
      "type": "checkbox",
      "id": "autoplay",
      "label": "Auto-rotate slides",
      "default": true
    },
    {
      "type": "range",
      "id": "autoplay_speed",
      "min": 3,
      "max": 10,
      "step": 1,
      "unit": "s",
      "label": "Change slides every",
      "default": 5
    },
    {
      "type": "select",
      "id": "transition_type",
      "label": "Transition Effect",
      "options": [
        {
          "value": "slide",
          "label": "Slide"
        },
        {
          "value": "fade",
          "label": "Fade"
        }
      ],
      "default": "slide"
    }
  ],
  "blocks": [
    {
      "type": "slide",
      "name": "Slide",
      "settings": [
        {
          "type": "header",
          "content": "Left Column Settings"
        },
        {
          "type": "image_picker",
          "id": "image",
          "label": "Content Image"
        },
        {
          "type": "range",
          "id": "image_width",
          "min": 50,
          "max": 100,
          "step": 5,
          "unit": "%",
          "label": "Content Image Width",
          "default": 100
        },
        {
          "type": "color",
          "id": "left_bg_color",
          "label": "Background Color",
          "default": "transparent"
        },
        {
          "type": "image_picker",
          "id": "left_bg_image",
          "label": "Background Image"
        },
        {
          "type": "range",
          "id": "left_padding",
          "min": 0,
          "max": 100,
          "step": 5,
          "unit": "px",
          "label": "Padding",
          "default": 30
        },
        {
          "type": "header",
          "content": "Right Column Settings"
        },
        {
          "type": "text",
          "id": "heading",
          "label": "Heading",
          "default": "Slide Heading"
        },
        {
          "type": "range",
          "id": "heading_size",
          "min": 16,
          "max": 60,
          "step": 2,
          "unit": "px",
          "label": "Heading Size (Desktop)",
          "default": 32
        },
        {
          "type": "range",
          "id": "heading_size_mobile",
          "min": 14,
          "max": 40,
          "step": 1,
          "unit": "px",
          "label": "Heading Size (Mobile)",
          "default": 24
        },
        {
          "type": "richtext",
          "id": "text",
          "label": "Text Content",
          "default": "<p>Add your content here</p>"
        },
        {
          "type": "range",
          "id": "text_size",
          "min": 12,
          "max": 24,
          "step": 1,
          "unit": "px",
          "label": "Text Size (Desktop)",
          "default": 16
        },
        {
          "type": "range",
          "id": "text_size_mobile",
          "min": 12,
          "max": 20,
          "step": 1,
          "unit": "px",
          "label": "Text Size (Mobile)",
          "default": 14
        },
        {
          "type": "color",
          "id": "heading_color",
          "label": "Heading Color",
          "default": "#000000"
        },
        {
          "type": "color",
          "id": "text_color",
          "label": "Text Color",
          "default": "#333333"
        },
        {
          "type": "color",
          "id": "right_bg_color",
          "label": "Background Color",
          "default": "transparent"
        },
        {
          "type": "range",
          "id": "right_padding",
          "min": 0,
          "max": 100,
          "step": 5,
          "unit": "px",
          "label": "Padding",
          "default": 30
        },
        {
          "type": "header",
          "content": "Button Settings"
        },
        {
          "type": "text",
          "id": "button_label",
          "label": "Button Label"
        },
        {
          "type": "url",
          "id": "button_link",
          "label": "Button Link"
        },
        {
          "type": "select",
          "id": "button_style",
          "label": "Button Style",
          "options": [
            {
              "value": "primary",
              "label": "Primary"
            },
            {
              "value": "secondary",
              "label": "Secondary"
            }
          ],
          "default": "primary"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "Two Column Slider",
      "blocks": [
        {
          "type": "slide"
        }
      ]
    }
  ]
}
{% endschema %}

<div class="tcsl-section-wrapper" style="background-color: {{ section.settings.section_bg }}; padding: 80px 20px;">
  <div class="tcsl-two-column-slider">
    {%- for block in section.blocks -%}
      {%- if block.type == 'slide' -%}
        <div class="tcsl-slide" {{ block.shopify_attributes }}>
          <div class="tcsl-page-width">
            <div class="tcsl-grid">
              {%- assign bg_image = block.settings.left_bg_image -%}
              <div class="tcsl-grid__item tcsl-slide-column tcsl-slide-column--left" 
                   style="background-color: {{ block.settings.left_bg_color }}; 
                          padding: {{ block.settings.left_padding }}px;
                          {%- if bg_image -%}background-image: url('{{ bg_image | img_url: '2000x' }}');{%- endif -%}">
                <div class="tcsl-slide-image-wrapper">
                  {%- if block.settings.image -%}
                    <img src="{{ block.settings.image | img_url: 'master' }}" 
                         alt="{{ block.settings.image.alt | escape }}"
                         style="width: {{ block.settings.image_width }}%;"
                         loading="lazy"
                         width="{{ block.settings.image.width }}"
                         height="{{ block.settings.image.height }}">
                  {%- endif -%}
                </div>
              </div>
              <div class="tcsl-grid__item tcsl-slide-column" 
                   style="background-color: {{ block.settings.right_bg_color }}; 
                          padding: {{ block.settings.right_padding }}px;">
                <div class="tcsl-slide-content">
                  {%- if block.settings.heading != blank -%}
                    <h2 class="tcsl-slide-heading">{{ block.settings.heading }}</h2>
                  {%- endif -%}
                  {%- if block.settings.text != blank -%}
                    <div class="tcsl-slide-text">{{ block.settings.text }}</div>
                  {%- endif -%}
                  {%- if block.settings.button_label != blank -%}
                    <a href="{{ block.settings.button_link }}" 
                       class="tcsl-button{% if block.settings.button_style == 'secondary' %} tcsl-button--secondary{% endif %}">
                      {{ block.settings.button_label }}
                    </a>
                  {%- endif -%}
                </div>
              </div>
            </div>
          </div>
        </div>
      {%- endif -%}
    {%- endfor -%}
  </div>
</div>

{%- style -%}
.tcsl-section-wrapper {
  width: 100%;
  margin: 0 auto;
}

.tcsl-two-column-slider {
  opacity: 0;
  transition: opacity 0.3s ease;
  position: relative;
}

.tcsl-two-column-slider.slick-initialized {
  opacity: 1;
}

.tcsl-page-width {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0;
}

.tcsl-grid {
  display: flex;
  flex-wrap: wrap;
  margin: -10px;
  padding: 0;
  list-style: none;
}

.tcsl-grid__item {
  width: calc(50% - 20px);
  margin: 10px;
  padding: 0;
}

.tcsl-slide-column {
  display: flex;
  align-items: center;
  min-height: 400px;
  position: relative;
  border-radius: 10px;
  overflow: hidden;
}

.tcsl-slide-column--left {
  background-position: center;
  background-size: cover;
  background-repeat: no-repeat;
}

.tcsl-slide-image-wrapper {
  position: relative;
  z-index: 2;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.tcsl-slide-image-wrapper img {
  max-width: 100%;
  height: auto;
  display: block;
  transition: transform 0.3s ease;
}

.tcsl-slide-content {
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  gap: 20px;
}

.tcsl-slide-heading {
  margin: 0 0 15px;
  line-height: 1.2;
  font-size: var(--heading-size, 32px);
  color: var(--heading-color, {{ block.settings.heading_color }});
}

.tcsl-slide-text {
  margin: 0;
  font-size: var(--text-size, 16px);
  color: var(--text-color, {{ block.settings.text_color }});
}

.tcsl-button {
  display: inline-block;
  padding: 12px 24px;
  text-decoration: none;
  border-radius: 5px;
  transition: all 0.3s ease;
  margin-top: 20px;
}

/* Slick Slider Custom Styles */
.tcsl-two-column-slider .slick-dots {
  bottom: -30px;
  padding: 10px 0;
}

.tcsl-two-column-slider .slick-dots li button:before {
  font-size: 12px;
}

.tcsl-two-column-slider .slick-prev,
.tcsl-two-column-slider .slick-next {
  z-index: 1;
  width: 40px;
  height: 40px;
}

.tcsl-two-column-slider .slick-prev {
  left: 15px;
}

.tcsl-two-column-slider .slick-next {
  right: 15px;
}

@media screen and (max-width: 749px) {
  .tcsl-grid {
    margin: 0;
  }

  .tcsl-grid__item {
    width: 100%;
    margin: 10px 0;
  }

  .tcsl-slide-column {
    min-height: 300px;
  }

  .tcsl-slide-heading {
    font-size: var(--heading-size-mobile, 24px);
  }

  .tcsl-slide-text {
    font-size: var(--text-size-mobile, 14px);
  }

  .tcsl-two-column-slider .slick-prev,
  .tcsl-two-column-slider .slick-next {
    display: none !important;
  }
}
{%- endstyle -%}

<script>
(function() {
  class TwoColumnSlider {
    constructor(element) {
      this.slider = element;
      this.init();
    }

    init() {
      $(this.slider).slick({
        dots: true,
        arrows: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1,
        adaptiveHeight: true,
        autoplay: {% if section.settings.autoplay %}true{% else %}false{% endif %},
        autoplaySpeed: {{ section.settings.autoplay_speed | times: 1000 }},
        fade: {% if section.settings.transition_type contains 'fade' %}true{% else %}false{% endif %},
        pauseOnHover: true,
        responsive: [
          {
            breakpoint: 749,
            settings: {
              arrows: false,
              dots: true
            }
          }
        ]
      });

      // Set CSS variables for text styling
      this.updateTextStyles();
    }

    updateTextStyles() {
      const slides = this.slider.querySelectorAll('.tcsl-slide');
      slides.forEach(slide => {
        const heading = slide.querySelector('.tcsl-slide-heading');
        const text = slide.querySelector('.tcsl-slide-text');
        
        if (heading) {
          heading.style.setProperty('--heading-size', `${slide.dataset.headingSize || '32'}px`);
          heading.style.setProperty('--heading-color', slide.dataset.headingColor || '#000000');
        }
        
        if (text) {
          text.style.setProperty('--text-size', `${slide.dataset.textSize || '16'}px`);
          text.style.setProperty('--text-color', slide.dataset.textColor || '#333333');
        }
      });
    }

    refresh() {
      $(this.slider).slick('refresh');
      this.updateTextStyles();
    }

    destroy() {
      if (this.slider) {
        $(this.slider).slick('unslick');
      }
    }
  }

  // Initialize slider
  document.addEventListener('DOMContentLoaded', function() {
    const sliderElements = document.querySelectorAll('.tcsl-two-column-slider');
    const sliders = new Map();

    sliderElements.forEach((element, index) => {
      sliders.set(`slider-${index}`, new TwoColumnSlider(element));
    });

    // Handle Shopify theme editor
    if (Shopify.designMode) {
      document.addEventListener('shopify:section:load', function(event) {
        const newSlider = event.target.querySelector('.tcsl-two-column-slider');
        if (newSlider) {
          sliders.set(`slider-${sliders.size}`, new TwoColumnSlider(newSlider));
        }
      });

      document.addEventListener('shopify:section:unload', function(event) {
        const unloadedSlider = event.target.querySelector('.tcsl-two-column-slider');
        if (unloadedSlider) {
          sliders.forEach((slider, key) => {
            if (slider.slider === unloadedSlider) {
              slider.destroy();
              sliders.delete(key);
            }
          });
        }
      });

      document.addEventListener('shopify:block:select', function(event) {
        const slider = event.target.closest('.tcsl-two-column-slider');
        if (slider) {
          const slideIndex = Array.from(slider.children).indexOf(event.target);
          $(slider).slick('slickGoTo', slideIndex);
        }
      });
    }
  });
})();
</script>

### Expected behavior

I expected it to analyze the code and just say great let's get working. Instead, what it does is it builds a new app and starts downloading all kinds of crap from NPM. On top of that, it hasn't saved a single one of my sessions so I can't go back.

### Screen Recording / Screenshot

https://komododecks.com/recordings/Vf4dKOYC6iQ8LL8yYkw7?uploadId=13rIYh7EF7kwqZI2qm1w

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

This is entirely too buggy right now to be charging for I feel. I don't know what's going on, but will this become more stable eventually?

**Comment by kc0tlh** [comment]
@JKdreaming please read #39 and #678 for info on both of the important topics you raise here!

**Comment by JKdreaming** [comment]
How do I get a refund?

**Comment by JKdreaming** [comment]
It's either a refund or a chargeback. Do you have a refund process?

**Comment by kc0tlh** [comment]
@JKdreaming happy to issue a refund at hello@stackblitz.com

**Comment by JKdreaming** [comment]
Thank you much appreciated
