### ISSUE TITLE
Bolt constant errors and timeouts

### ISSUE THREAD

**Issue by laurenburley** [stackblitz/bolt.new#1085]
### Describe the bug

Im constantly getting This message didn't complete its response whenever I try to ask Bolt to do something and its burned through MILLIONS of tokens to the point I cant finish my project.

Secondly, Im getting constant prompt is too long: 200006 tokens > 199999 maximum, for the simplest of requests like restarting the dev environment.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4goklk

### Steps to reproduce

On my project, its just giving the above errors for every request I make

### Expected behavior

It was working fine a few days ago and is now basically unusable.

### Screen Recording / Screenshot

![Screenshot 2024-10-29 at 8 55 27 AM](https://github.com/user-attachments/assets/80ced912-bbed-47af-a84f-d9244b8b2aa8)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77920514,
  "usedJSHeapSize": 72670258,
  "jsHeapSizeLimit": 4294705152
}
Username = laurenburley
Chat ID = 2150201e619a
```

**Comment by rryati20** [comment]
I've been getting so many errors as well, got a new one now of: 

too many total text bytes: 9759159 > 9000000

**Comment by kc0tlh** [comment]
Thanks for the report! This has been escalated to engineering, and resolution will be tracked in #1073

**Comment by idaltu-1** [comment]
bolt doesnt show submit button in prompt window anymore
