### ISSUE TITLE
Preview never shows

### ISSUE THREAD

**Issue by AImpactEvents** [stackblitz/bolt.new#1086]
### Describe the bug

The preview screen never showed anything other than a white blank screen. The tool could not resolve it after multiple attempts. A red X showed next to "Start Application"

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-twyxbq

### Steps to reproduce

This was the prompt I gave it: I want to create an interactive webpage that shows covers of books on a shelf as if it is a virtual bookshelf. I want the books to be clickable with a cool animation of the book being taken from the shelf and opening up in a pop-up page with book title, summary, author, publish date, and links to buy the book on Amazon

### Expected behavior

I was hoping to preview the code but I could never get the preview to appear

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = hwilsonia
Chat ID = 71806fdeffac
```

### Additional context

![Screenshot 2024-10-28 at 6 10 29 PM](https://github.com/user-attachments/assets/76025d3c-daf1-4ab9-8829-4daad768ac2a)
![Screenshot 2024-10-28 at 6 10 16 PM](https://github.com/user-attachments/assets/4c81f4e4-829e-4d56-bba3-0b0f9a3d7020)

**Comment by spifft** [comment]
i have the same problem, consistently. I don't think this app actually works yet.

**Comment by leosdad** [comment]
I also see blank screens because I also use the Dark theme. You'll probably find the "No preview available" message using your browser's DevTools. It's in white text over a white background (!!!). It happens with Dark theme only. If you switch themes or disable .bg-white's background-color, it will appear.

![image](https://github.com/user-attachments/assets/94f8b84d-46c1-4509-b095-022e33da180c)

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
