### ISSUE TITLE
History Chats Disappeared 

### ISSUE THREAD

**Issue by VantaGroups** [stackblitz/bolt.new#1087]
### Describe the bug

After 10M tokens to build an app. Chat was deleted automatically 

### Link to the Bolt URL that caused the error

no idea 

### Steps to reproduce

Check history 

### Expected behavior

Gone

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
Your project as not deleted. For more info on our comming UI improvements (and how to re-open your project) check out issue #39
