### ISSUE TITLE
Project wiped out

### ISSUE THREAD

**Issue by Frankg40** [stackblitz/bolt.new#1088]
### Describe the bug

My project is wiped out. Spent 15M TOkens on it, and now it just doesnt have all the files when I tried to roll back to a few minutes prior

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jhdosm

### Steps to reproduce

My project has been wiped twice. 

There needs to be a save feature, because the autosave is not good.

### Expected behavior

Where is my whole project?

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109454130,
  "usedJSHeapSize": 90200930,
  "jsHeapSizeLimit": 4294705152
}
Username = Targi
Chat ID = a11b99103353
```

**Comment by kc0tlh** [comment]
@Frankg40 It sounds like you’ve been affected by a bug we identified and fixed earlier today in the rollback feature. Apologies for the frustrating experience! Please follow the instructions in #1104 to reach out, and we’ll work with you to attempt restoring your project. Thanks for your patience as we get this sorted out for you.

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know in #1104 if you have any issues using this brand new feature.

**Comment by Frankg40** [comment]
Thanks. I am using the app pretty heavily. Currently going through about 10M tokens a day. (My wife is enjoying that)

------------

1. One I can think of off the bat is having the option for a prompt just like creating new GPTs, A set of instructions that the AI always takes into consideration FIRST before looking at what you just wrote.

For example, I am building a 4 step order process web page, and I want to add or modify options to one of the pages. AI likes to recreate the entire document, and more times than not when its finished, the entire design, layout, styling has completely changed.

I would put in a prompt (Only change whats necessary and leave all layout, options, styling) etc the same. I find myself telling it this every time before I tell it to do something, which usually works so that’s good. You could have checkboxes or radio button options that gives the prompt how you want to implement the change. Or hardcode it into the AI. I cant imagine a scenario where someone wants to make a modification to the project that does not involve styling or layout, and would ever want the AI to completely recreate the entire project or page. (I understand sometimes a change you implement maybe so big it actually requires a large change like that, but not sure styling should be affected.)

2. A second problem I see happening a lot, is when adding a new option or modifying anything, it has a habit to rewrite the file and only add the code of the change you made, and leave ALLLLLL the rest of the code of the entire file out. Which obviously results in an error since the file is now missing every critical part that made it work.
------------

With that’s said, I just wanted to say I really appreciate what you guys have created here. I understand its in Beta and its far from perfect but I am rather enjoying the heck out of it. Do you have a beta testing crowd that has any openings? I have some pretty good feedback based on using it a ton.

I am a designer and developer but my dev skills are mid. Im not a master by any means and I do not know a lot of the big frameworks. Im mostly html CSS Bootstrap etc… however I can read code pretty efficiently no matter what language and have a pretty good understanding of what its doing. Ive been able to look at the code myself, then ask the AI if this might be the problem, and it ends up agreeing and fixing it.

I do have experience designing, layout, structure, and rules for SAAS that I have directed the build on in my own tenured Marketing Agency business. Which makes this tool pretty much perfect for someone like me.

Frank Genovese
CEO | Paramount Direct Marketing
800-732-5478
Paramountlists.com

**Comment by Frankg40** [comment]
Hi,

Ive spent about 8 straight hours and 10M tokens trying to fix image upload. I connected firebase. Its uploading all other data except images. This took me down a 7 hour CORS rabbit hole that had chatgpt walking me through every conceivable fix.

My question is simple. Is building the app in bolt.new just not going to allow me to achieve this in the bolt app preview pane? Is Firebase just not going to allow me to upload images from bolt?

Or is this still a cors problem? Im about ready to give up.



Frank Genovese
CEO | Paramount Direct Marketing
800-732-5478
Paramountlists.com

**Comment by kc0tlh** [comment]
@Frankg40 image uploads are a known issue that many are experiencing. When this improvement lands, we will announce it on twitter and via email.

**Comment by Frankg40** [comment]
Thank you for the response. I have been using it about 8 hours a day.

I am coming across a lot of problems interacting with the database. I am able to save regular data and pull regular data. Images are an issue, but there are also regular permission denied from the database errors that happen quite often. Especially when trying to create new fields.

Are you having other database interaction issues other than just image upload? The reason I am asking is I don’t want to spend 10M tokens trying to get Bolt to fix something it cant fix right now, I can just move on to other functionality that I can get it to do.

Thanks!

Frank Genovese
CEO | Paramount Direct Marketing
800-732-5478
Paramountlists.com
