### ISSUE TITLE
Ability to go back to previous versions or save them 

### ISSUE THREAD

**Issue by samweist** [stackblitz/bolt.new#109]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, it would be great to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by samdenty** [comment]
@pkeller3 Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
