### ISSUE TITLE
Non-stop error messages for the past 2 days. 

### ISSUE THREAD

**Issue by rryati20** [stackblitz/bolt.new#1091]
### Describe the bug

I have not been able to work on my project for the past 2 days for more than 1 hour straight without persisting issues allowing me to work.

I have also had token errors popup, and more but I just forgot what they said. This has been very frustrating and I probably am down a total of 50 million tokens just from errors if not more. 

### Link to the Bolt URL that caused the error

Whenever I prompt something

### Steps to reproduce

Work on your project until you can't anymore because of a random error.

### Expected behavior

For me to use the platform.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/75c11c43-fb27-4b34-9e68-23041675198c)

![image](https://github.com/user-attachments/assets/4fd0061d-6b55-4f28-b1e8-6aba960b21b0)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by laurenburley** [comment]
Ive reported the same thing here https://github.com/stackblitz/bolt.new/issues/1085

**Comment by kc0tlh** [comment]
Thanks for the report! This has been escalated to engineering, and resolution will be tracked in #1073
