### ISSUE TITLE
disappointed by everything - no version saving available 

### ISSUE THREAD

**Issue by pranav682** [stackblitz/bolt.new#1093]
### Describe the bug

i keep losing my work and keep paying with my token to create the same i had created. badly designed and waste of money and time. i am back to 0 every time something goes wrong. hate this app. return my money.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bn3pbp

### Steps to reproduce

any step will reproduce this . 

### Expected behavior

expected for it to develop my webapp but it keeps ruining everywork tht has been done and you guys think you can have people on your platform and keep paying.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 125275403,
  "usedJSHeapSize": 107279371,
  "jsHeapSizeLimit": 4294705152
}
Username = pranav682
Chat ID = 193f7a37122d
```

**Comment by kc0tlh** [comment]
@pranav682 chat persistence (& rollback persistence across sessions) is coming next week and tracked in #39.

Happy to issue a refund tho via hello@stackblitz.com if the product is not the right fit for you during the beta!

**Comment by pranav682** [comment]
Hi Alexander!

Sorry I got really frustrated. I do like the product but it is not working
for me for the reason I shared. If you can just provide my spent tokens so
I can use it after chat persistence and rollback across session is active
so that I can save my work as a check post and be able to work on top of
it. It would be something that will create value for me . That’s a request.
Let me know if you can do that for me. My intention is to use a platform
like this for my multiple continued projects that I want to build and ship
.


Thanks,
Pranav

**Comment by pranav682** [comment]
Hello Alexander!,

Do you have any updates? we are waiting for the upgrade and reissue of the
wasted tokens so we could proceed building.

Thanks

**Comment by pranav682** [comment]
Hello,

I am reaching back again to follow up on this request. I don’t have enough
token and I have wasted all my token because of the aforementioned issue.
Within a day of getting this monthly token: please kindly address the
issue as soon as possible.

**Comment by pranav682** [comment]
Hello,

I am again following up on this issue. i am literally left with 2m tokens .
please can i have my tokens and if it doesnt work for you then please
refund me. i may have to think about some other alternative. I have not got
any response from you. please respond.

Thanks.

**Comment by pranav682** [comment]
I have been reaching out many times. I got charged for next month also but
please return my last month money or else token .

Thanks
