### ISSUE TITLE
Message didn't complete it's response

### ISSUE THREAD

**Issue by TunaUskudar** [stackblitz/bolt.new#1095]
### Describe the bug

Message didn't complete it's response

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ai7wqk

### Steps to reproduce

Just type in something in bolt and it produces it.

### Expected behavior

Complete the response and make the necessary changes

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 200790545,
  "usedJSHeapSize": 194918609,
  "jsHeapSizeLimit": 2172649472
}
Username = tunauskudar
Chat ID = 14cd89393a21
```

**Comment by kc0tlh** [comment]
Thanks for the report! This has been escalated to engineering, and resolution will be tracked in #1073
