### ISSUE TITLE
Deploy is not working properly

### ISSUE THREAD

**Issue by AashishThakuri** [stackblitz/bolt.new#1096]
### Describe the bug

I gave bolt.new make a clone google classroom but with better version and add extra it works but when said it to deploy in netlify, it just shows error

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ycekeu

### Steps to reproduce

1 create anything 2 say it to deploy app, application or website in netlify 4 error

### Expected behavior

I expected that it will directly open netlify and the all code will be deploy in it.

### Platform

```
Browser name = Safari
Full version = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/130.0.6723.37 Mobile/15E148 Safari/604.1
performance.memory = undefined
Username = AashishThakuri
Chat ID = 13dcfd4f07a7
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@AashishThakuri this issue is being tracked in #1022
