### ISSUE TITLE
Python broke

### ISSUE THREAD

**Issue by ajmssc** [stackblitz/bolt.new#11]
### Describe the bug

after asking to replace Flask with FastAPI, python stopped working. Any command with python crashed.

```
❯ python3
RustPython 3.11.0
Type "help", "copyright", "credits" or "license" for more information.
>>>>> import venv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv", line 10, in <module>
  File "subprocess", line 49, in <module>
  File "signal", line 1, in <module>
ModuleNotFoundError: No module named '_signal'
```

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-d9fwyd

### Steps to reproduce

1. ask to create a react frontend + python backend
2. ask to replace flask with fastapi
3. python got corrupted

### Expected behavior

python works and I can continue working

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by KwintenP** [comment]
At this point in time, we only support vanilla Python and that is still in an experimental alpha mode. 

So what you are trying is not supposed to work. Thanks for testing!
