### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by ubeffiong** [stackblitz/bolt.new#1102]
### Describe the bug

there is a serious bug, I can give bolt command to build more feature. Error "This message didn't complete its response."

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lyttc6

### Steps to reproduce

Ask a question to add new feature

### Expected behavior

I have options to roll back and retry but they are not working none serving the problem

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 247730002,
  "usedJSHeapSize": 241689226,
  "jsHeapSizeLimit": 4294705152
}
Username = ubeffiong
Chat ID = f5af6c44d0db
```

**Comment by kc0tlh** [comment]
Thanks for the report! This has been escalated to engineering, and resolution will be tracked in #1073
