### ISSUE TITLE
BUG: Using Rollback Feature Resulted in Improper File Removal (Fixed)

### ISSUE THREAD

**Issue by kc0tlh** [stackblitz/bolt.new#1104]
We recently identified and fixed a bug in the rollback feature implementation that, in some cases, caused files to be removed improperly when utilizing rollbacks. We understand this caused frustration, and we’re grateful to everyone who reported the issue, helping us pinpoint the root cause. Bolt.new has been updated to prevent this issue from occurring again in the future.

For those who experienced this bug, we believe it’s likely that we can help restore your projects to their intended state. However, this process may depend on specific factors, and we appreciate your patience as we work with you individually on these recoveries.

**What to Do if an Important Project Was Affected**
1. Pause Edits: Please stop editing any affected project(s) to preserve data that may aid restoration.
2. Reach Out: Contact us at hello@stackblitz.com and provide as many of the following details as possible:
- Affected Project URL(s): Links to the project(s) you need help with
- Target Timestamp: The approximate date and time you'd like us to restore to (if known)
- Bolt.new Username or Associated Email 
- Contact Details: A phone number and your time zone to get additional info/ensure the right version is restored, if needed

We’ll address each report individually. Thank you for helping us improve Bolt.new and for your understanding as we work on recoveries.

**Comment by kc0tlh** [comment]
**📣 Update:** we decided to ship a "backups" feature that will allow you to manually restore your projects to the desired timestamp. This will be shipping later today. Stay tuned here for instructions when it goes live!

**Comment by kc0tlh** [comment]
**📣 Update:** we decided to ship a "backups" feature that will allow you to manually restore your projects to the desired timestamp. This will be shipping later today. Stay tuned here for instructions when it goes live!

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Please let us know below if you're having trouble using this feature.

**Comment by iwt-nihadalic** [comment]
Thank you VERY much, it works! This is really a nice option.

**Comment by antonio59** [comment]
Do I use the backup feature over contacting you as stated above? I'm afraid to lose more changes in my project which is near production ready.

**Comment by KwintenP** [comment]
If you fear you might lose your changes you can create a manual back right now by:
- clicking 'open in stackblitz'
- click on 'fork'
- go to the dashboard (https://stackblitz.com/) 
- you should see a complete copy

You can then play around with the original project in bolt. If it screws up, you still have your copy.

**Comment by SamVerschueren** [comment]
Also do note that clicking `Load` for the backup automatically creates a new StackBlitz project, it will not affect the current project.

**Comment by Habartru** [comment]
Can I ask here? I created the project on another PC, after 2 hours I opened the bolt on another (home PC) and there is no project. The last backup in the system shows the time more than 6 hours ago, that is, my project did not enter it, but I need to work. What should I do?

**Comment by kc0tlh** [comment]
@Habartru that is a different issue. Your solution is in #39

**Comment by kc0tlh** [comment]
**🎉 Backups Have Landed on Production!**
Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

**Comment by Habartru** [comment]
Unfortunately, I don't have backups in this environment.  Can you see what's the matter?

> **🎉 Backups Have Landed on Production!** Open your affected project and in the lower left hand corner of the screen navigate to Settings > Backups to restore your project to any previous state!

Unfortunately, I don't have backups in this environment.  Can you see what's the matter?
![Screenshot - 2024-11-14T225609 955](https://github.com/user-attachments/assets/7924d692-571a-4e5a-b8b3-2bd18d2a0475)

**Comment by rririanto** [comment]
Hi @kc0tlh could you help me restore my project: https://stackblitz.com/edit/sb1-vpdzsuqc I'm subscribing but accidentaly remove the project because I dont know bolt.ai connect with stackblitz. Please help, I spend many hours for that.
