### ISSUE TITLE
Not working properly 

### ISSUE THREAD

**Issue by abhixx69** [stackblitz/bolt.new#1105]
### Describe the bug

Again and again i am writing the issue and showing me same results...damm sick of it...is this the way to forcefully upgrade your plan? my all tokens are expired.
![Screenshot 2024-10-29 105906](https://github.com/user-attachments/assets/4acbe633-11d6-4f76-8f14-3d5a9d1c6de4)
![Screenshot 2024-10-29 105917](https://github.com/user-attachments/assets/2f787440-7cd3-4202-8db6-50d3cf304d28)
![Screenshot 2024-10-29 105927](https://github.com/user-attachments/assets/4af031d5-67cb-48d6-a063-bfa63d667f6e)
![Screenshot 2024-10-29 110000](https://github.com/user-attachments/assets/765d55f0-cc76-47dd-9509-54734aee3db7)
 *

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lttvar

### Steps to reproduce

1. look at my screenshots
2. you will find the error

### Expected behavior

not solving the problem...damm i am sick of it,  all tokens are expired what am i suppose to do.

### Screen Recording / Screenshot

![Screenshot 2024-10-29 105906](https://github.com/user-attachments/assets/49437963-e4b6-4f01-98da-4aed30d31dbc)
![Screenshot 2024-10-29 105917](https://github.com/user-attachments/assets/8c44a359-ede6-442b-b86a-5799f9156f75)
![Screenshot 2024-10-29 105927](https://github.com/user-attachments/assets/534b9850-78b2-4c9f-9cf9-63679fc6de9b)
![Screenshot 2024-10-29 110000](https://github.com/user-attachments/assets/32b41c13-a165-4764-a850-36c112de319f)

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0
performance.memory = {
  "totalJSHeapSize": 53667860,
  "usedJSHeapSize": 49376204,
  "jsHeapSizeLimit": 2172649472
}
Username = abhixx69
Chat ID = 8d99a6670bb7
```

### Additional context

fix this...or give me a free plan

**Comment by kc0tlh** [comment]
Please checkout the tips in #678
