### ISSUE TITLE
prewiev not work

### ISSUE THREAD

**Issue by LexProfi** [stackblitz/bolt.new#1106]
### Describe the bug

prewiev show only blank page

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rwxmw4

### Steps to reproduce

1. Open page
2. Click prewiev

### Expected behavior

prewiev show only blank page

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56222690,
  "usedJSHeapSize": 53844822,
  "jsHeapSizeLimit": 4294705152
}
Username = LexProfi
Chat ID = 61b7ee4edf28
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1791.
