### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by Exodo0** [stackblitz/bolt.new#1111]
![{AD5A09BE-64D0-4A24-972B-5BB9A9232D88}](https://github.com/user-attachments/assets/cb20b032-a76e-41a5-826b-92e461546b25)
I wanted to buy the 9USD Plan, the Pro Plan, but now that I reviewed it, I changed the price to 20USD. When will it return or is it a mistake?

**Comment by kc0tlh** [comment]
@Exodo0 we needed to raise prices to keep up with demand. More info here: https://x.com/ericsimons40/status/1844551246658798079
