### ISSUE TITLE
Where is my project ?!! All my chat have disapear !

### ISSUE THREAD

**Issue by anthony40460** [stackblitz/bolt.new#1114]
### Describe the bug

No data in history chat !! Where is my project ?

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

?

### Expected behavior

Backup please

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by koblakai** [comment]
same here bro. Why is this happening? I can see my projects in stack blitz but cannot edit them in bolt new. Am I going to have to restart using cursor?

**Comment by kc0tlh** [comment]
@anthony40460 @koblakai the workaround for this can be found in issue #39. A full fix is coming soon.
