### ISSUE TITLE
My App Disappeared- Please help

### ISSUE THREAD

**Issue by supurrapp** [stackblitz/bolt.new#1116]
I spent 50m credits creating an app on bolt.new, and bolt suddenly forgot it. 

I have the latest netifly link, which is the version i want but i haven't saved the code. 
https://charming-parfait-1db237.netlify.app/
Could you help to revert to this version please? 

Bolt Project Link: https://bolt.new/~/sb1-d5z7k5
Stackblitz username: v****h

**Comment by kc0tlh** [comment]
@supurrapp this is a known issue with a fix coming later today in #1104
