### ISSUE TITLE
Project Disappeared

### ISSUE THREAD

**Issue by payday-apps** [stackblitz/bolt.new#1118]
### Describe the bug

Hi, 

My project disappeared in the middle of working on it, spending a bunch of tokens. 

Link:
https://bolt.new/~/sb1-ew8b5e

Stackblitz project legacy link (not appearing in dash, outdated)
https://stackblitz.com/edit/sb1-ew8b5e?file=index.html

Please help.

### Link to the blitz that caused the error

https://stackblitz.com/edit/sb1-ew8b5e?file=index.html

### Steps to reproduce

Link does not load

### Expected behavior

Would like to get it working again

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79381181,
  "usedJSHeapSize": 77114805,
  "jsHeapSizeLimit": 4294705152
}
Hash = 34c588ed
```

**Comment by kc0tlh** [comment]
@payday-apps this is a known issue with a fix coming later today in #1104
