### ISSUE TITLE
Where the heck is my project?

### ISSUE THREAD

**Issue by weixelbaumer** [stackblitz/bolt.new#1122]
### Describe the bug

Bolt.new project suddenly wasn't able to chat anymore - chat is gone in history on a paid account. I WANT MY MONEY BACK _ DO YOU FN HEAR ME?

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/weixelbaumer/team-roster

### Steps to reproduce

Try to open the bolt.new chat - it's effin vanished

### Expected behavior

Continue working on bolt ffs

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 3b0b7194bc6b567c2eaf4c96a5759098469dcf59
WebContainer = 134daa3c

Browser name  = Chrome
Full version  = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94830059,
  "usedJSHeapSize": 91450099,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by kc0tlh** [comment]
@weixelbaumer if you have not already, you can get a refund by email hello@stackblitz.com

Alternatively, you can reload your project using the instructions in #39
