### ISSUE TITLE
Project files disappear after I created them

### ISSUE THREAD

**Issue by ozgursarikamis** [stackblitz/bolt.new#1123]
### Describe the bug

Project files disappeared after I created them. I've used Bolt to create an Angular component with a few prompts. It was working perfectly fine but somehow the project files disappeared even though I could use the 'View on StackBlitz' button. project files disappeared even though I could use the

### Link to the blitz that caused the error

https://stackblitz.com/edit/sb1-dqqkkp

### Steps to reproduce

Create an angular app with a few AI prompts
Customize it
Hit the button 'View on StackBlitz'

### Expected behavior

Create an angular app with a few AI prompts
Customize it
Hit the button 'View on StackBlitz'
View the project on StackBlitz or Bolt.new

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101191607,
  "usedJSHeapSize": 90055471,
  "jsHeapSizeLimit": 2172649472
}
Hash = 134daa3c
```

**Comment by kc0tlh** [comment]
@ozgursarikamis instructions on reloading your project can be found in #39
