### ISSUE TITLE
npm next build running instead of npm vite build everyu

### ISSUE THREAD

**Issue by thedelph** [stackblitz/bolt.new#1127]
### Describe the bug

I've built an application that I've switched over from running Next.JS to running Vite, but everytime I deploy it still runs npm next build instead of npm vite build

"you should be running "npx vite build" instead of "npx next build"

You're absolutely right - this is a Vite project and I see the build has already completed successfully with vite build. Let me deploy this to Netlify now.

Deploy to Netlify

**npx next build**
netlify"

I've wasted millions of tokens trying to get this working and it just won't do what I want.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3gsmvx

### Steps to reproduce

I click on Deploy this application, and it runs "npm next build" prior to trying to deploy to netlify.

### Expected behavior

it should run **npm vite build** for a vite application.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/11738838-d76a-4fcf-9ee9-026e1570b508)
![image](https://github.com/user-attachments/assets/b892b1d0-e24a-4ed5-8f23-70d61670cb17)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 265862026,
  "usedJSHeapSize": 246867418,
  "jsHeapSizeLimit": 4294705152
}
Username = thedelph
Chat ID = cbda190bc8c5
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@thedelph thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
