### ISSUE TITLE
REFUND REQUEST as i dont get answers to fixing the previous bug reports. Millions of tokes wasted

### ISSUE THREAD

**Issue by RANKXSEO** [stackblitz/bolt.new#1131]
### Describe the bug

I've built an application that I've switched over from running Next.JS to running Vite, but everytime I deploy it still runs npm next build instead of npm vite build

Also the Building application always fails. I´m not happy with the product and hereby request the full refund.

Deploy to Netlify and anything else never worked.

My username is: RANKX

Please issue refund as this leads nowhere and support takes too long.

### Link to the Bolt URL that caused the error

issue refund please

### Steps to reproduce

have mentioned it many times

### Expected behavior

not doing what i want at all.

Issue refund please

### Screen Recording / Screenshot

refund

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

refund

**Comment by kc0tlh** [comment]
Apologies for the frustration! Refund requests will be handled via hello@stackblitz.com

**Comment by RANKXSEO** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Dear Support,
as mentioned in the github process already I hreby request a full refund as Bolt is too buggy and non performing.whenever the platform is ready for proper usage i´m happy to come back.BestDaniel

Daniel MansfieldCEO / Co-Founder
RANKX LIMITED 20 Harcourt StreetDublin 2, D02 H364T: +49 179 2431876Skype: rankxseoW: www.rankx.co

Alexander Berger wrote on 29.10.2024 19:39 (GMT +01:00):

Apologies for the frustration! Refund requests will be handled via ***@***.***

**Comment by RANKXSEO** [comment]
Hi Daniel, 


Thanks for reaching out. I've processed a refund for you. Please note, it can take 5-10 business days to appear on your account. In the meantime, I've attached a screenshot of the refund here. 


Thanks, 

— 
Hyllarie Colyer

--- original message ---
On October 29, 2024 at 1:08 PM PDT ***@***.*** wrote:



Dear Support,


as mentioned in the github process already I hreby request a full refund as Bolt is too buggy and non performing.


whenever the platform is ready for proper usage i´m happy to come back.


Best


Daniel

Daniel Mansfield

CEO / Co-Founder



RANKX LIMITED 

20 Harcourt Street

Dublin 2, D02 H364


T: +49 179 2431876

Skype: rankxseo

W: www.rankx.co


Alexander Berger wrote on 29.10.2024 19:39 (GMT +01:00):

> Apologies for the frustration! Refund requests will be handled via ***@***.***

> —

> Reply to this email directly, view it on GitHub, or unsubscribe.

> You are receiving this because you authored the thread.Message ID: ***@***.***>
--- end of original message ---
