### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by krisgnyc** [stackblitz/bolt.new#1132]
### Describe the bug

link should work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5yu82y

### Steps to reproduce

link should work

### Expected behavior

Link should work

### Screen Recording / Screenshot

Link should work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77080376,
  "usedJSHeapSize": 70457064,
  "jsHeapSizeLimit": 4294705152
}
Username = krisgnyc
Chat ID = 9bba5163d742
```link should work

### Additional context

Error:
```
An error occured while streaming this message.
```Upper East Side

**Comment by kc0tlh** [comment]
@krisgnyc thanks for the report! Tracking this in #1022
