### ISSUE TITLE
Uploaded image files get corrupted cannot use Astro

### ISSUE THREAD

**Issue by 138n4379** [stackblitz/bolt.new#1133]
### Describe the bug

Second site I have used bolt to build an astro site, both cannot take any uploaded images they just don't work, webp, png, jpg, avif. external image links are fine. For the first site when I was done with bolt I just downloaded it and fixed it in VS code.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-dfwbea

### Steps to reproduce

1. upload any image.
2. npm run build
3. build will fail, because of no "metadata" in the image or it says the image is corrupted. 

### Expected behavior

1. That image uploads would work.
2. That your company invests in a real ticketing system.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85689804,
  "usedJSHeapSize": 64875464,
  "jsHeapSizeLimit": 4294705152
}
Username = 138n4379
Chat ID = efa52a307425
```

### Additional context

Seems like stackblitz knows about this issue, This is the image upload issue from 2018; https://github.com/stackblitz/core/issues/538 

_No response_

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1809.
