### ISSUE TITLE
Keep getting error This message didn't complete its response.

### ISSUE THREAD

**Issue by stevejford** [stackblitz/bolt.new#1135]
### Describe the bug

Siply asked it to please reupdate app/trades/[slug]/page.tsx

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-k93ynf

### Steps to reproduce

Normal use just asked to create a small change it had to update 3 files and it errors. Seems to be fine until 2:30 AEST then I have been getting errors. Maybe more users online

### Expected behavior

Complete updating the files

### Screen Recording / Screenshot

![Screenshot 2024-10-30 023947](https://github.com/user-attachments/assets/9151317f-d4d3-459e-af6d-b3c9908b8bbc)

### Platform

```
Browser name = Chrome
Full version = 132.0.0.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 168091117,
  "usedJSHeapSize": 144811353,
  "jsHeapSizeLimit": 4294705152
}
Username = stevejford
Chat ID = 5044e5db5d7d
```

**Comment by kc0tlh** [comment]
@stevejford thanks for the report! Tracking this in #1073
