### ISSUE TITLE
Previous projects not showing up

### ISSUE THREAD

**Issue by IntownNFT** [stackblitz/bolt.new#1139]
### Describe the bug

I cant see any of my previous projects that i was working on this is very frustrating!!!!

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

i clicked login
then went to the projects sidebar 
and nothing shows up

### Expected behavior

my previous projects should show up

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by verbitski** [comment]
same here

**Comment by kc0tlh** [comment]
@IntownNFT the workaround for this can be found in issue #39 as @verbitski mentioned. A full fix is coming soon.
