### ISSUE TITLE
The "enhance prompt" button result is always appended by `[object Object][object Object]`

### ISSUE THREAD

**Issue by Mearman** [stackblitz/bolt.new#114]
### Describe the bug

The "enhance prompt" button result is always appended by `[object Object][object Object]`

### Link to the Bolt URL that caused the error

n/a

### Steps to reproduce

- Write a prompt.
- Click `enhance prompt`

### Expected behavior

The enhanced prompt should not have `[object Object][object Object]`
 appended.
 ![CleanShot 2024-10-06 at 20 14 18](https://github.com/user-attachments/assets/4eae0b5d-9769-4d65-a99f-dafef672b9a5)

### Screen Recording / Screenshot

![CleanShot 2024-10-06 at 20 12 51](https://github.com/user-attachments/assets/bbc37337-5ff5-4d44-8461-07e01ef97294)
![CleanShot 2024-10-06 at 20 13 04](https://github.com/user-attachments/assets/8efbe2e8-6da9-4260-8ab3-84c02f6dc08e)

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

A fix for this has now been deployed to production!
