### ISSUE TITLE
Cannot deploy to Netlify for any of my bolt projects. 

### ISSUE THREAD

**Issue by louisdhon** [stackblitz/bolt.new#1142]
### Describe the bug

Every time i type "Deploy this application."

It says this: 

"I'll help you deploy the application to Netlify. First, let's make sure we have the correct build configuration and then deploy it.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to ensure everything is working correctly.

An error occured while streaming this message."

No bueno!

### Link to the Bolt URL that caused the error

Ask me later

### Steps to reproduce

Just click Deploy button and pressed enter

### Expected behavior

for the app to deploy

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 160299304,
  "usedJSHeapSize": 154111236,
  "jsHeapSizeLimit": 4294705152
}
Username = louisdhon
Chat ID = 69a72caef4c3
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@louisdhon we're tracking this issue in #1022.
