### ISSUE TITLE
Bolt.New subscription missing

### ISSUE THREAD

**Issue by dsudduth** [stackblitz/bolt.new#1145]
### Describe the bug

I've already sent a direct message to the team, but have not received a response. My subscription is missing from bolt.new and I can no longer use my credits. It's now been this way for two days. I'm all for giving room to fix, but it would be great to obtain help as a paying customer. This is in addition to history loss as reported by other users.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-c5dnrd

### Steps to reproduce

1. Go to bolt.new.
2. Sign In.
3. Go to My Subscription.

My tokens are missing, so I can no longer generate new content. History is not working and the subscription is missing entirely from the management page.

### Expected behavior

I should be on the Pro 50 plan.

### Platform

- OS: macOS
- Browser: Chrome

**Comment by kc0tlh** [comment]
@dsudduth just reached out via email!
