### ISSUE TITLE
Lost chats

### ISSUE THREAD

**Issue by harielxavier** [stackblitz/bolt.new#1146]
I bought 200M worth of credits I have 34M left. All my work is missing. How do I get that back or get my credits back?

**Comment by davidldennison** [comment]
Yeah this actually just happened to me as well. I Were you getting CORS issues as well?

**Comment by kc0tlh** [comment]
@harielxavier @davidldennison it appears something just broke on the app and I am escalating to engineering immediately! Please pause usage while we investigate. Please post any additional details about what you were doing and links to projects in #1148! We will track this in issue #1148.
