### ISSUE TITLE
Bug: Chats Cleared & Lots of Tokens Consumed

### ISSUE THREAD

**Issue by shivanagendrak** [stackblitz/bolt.new#1148]
### Describe the bug

i'm making my portfolio website  i just used two prompts its utilized 5 M tokens , Then after i'm getting some errors then i just tap fix issues two time, i dont understand after 2 prompts literally all tokens finished now i getting message like You have hit the rate limit. You can continue to code for free in the editor.
<img width="1259" alt="Screenshot 2024-10-29 at 3 49 24 PM" src="https://github.com/user-attachments/assets/f69608d9-8e23-4b2a-b34e-89909627f0f0">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nfzzaq

### Steps to reproduce

my all chats are cleared automattically i can't able to show 

### Expected behavior

previous i gave so many prompts tokens are utlized like so less but now tokens are utlized like for single prompt millions tokens 

### Platform

- OS: macOS
- Browser: Chrome

**Comment by kc0tlh** [comment]
@shivanagendrak it appears something just broke on the app and I am escalating to engineering immediately! Please pause usage while we investigate. 

For other users experiencing this, please post any additional details about what you were doing and links to projects below.

**Comment by shivanagendrak** [comment]
I'm can't able to use bolt.new because today i use very less prompts not more than 7 but my tokens are utilized from  9.5 M to zero , Please help me out

**Comment by kc0tlh** [comment]
@shivanagendrak in order to help, I need to collect the information I requested above:
> Please check StackBlitz.com > Collections > Bolt and let us know if your projects are still stored there

**Comment by jcunio06** [comment]
I am having this same issue. It looks like my project is in Stackblitz.com > Collection > Bolt. However, I too consumed way too many tokens for what I did (a simple text change as about 1M tokens). Also, all of my chat history in Bolt is gone.

**Comment by kc0tlh** [comment]
@jcunio06 the projects will appear in the Bolt chat sidebar again after you open them in StackBlitz & then use the "Open in BOlt" button to pull them back into Bolt

**Comment by f12defilippis** [comment]
> Also, all of my chat history in Bolt is gone

Unfortunately I had the same experience. 1M token of work and code is gone after an error on the platform. I'd like to recover it or have the tokens back

**Comment by shivanagendrak** [comment]
I got this Bug resolved

**Comment by blanco1er** [comment]
I used nearly 100 million tokens, but unfortunately, it only resulted in errors. I hope the Bolt team can restore my account, as these issues seem to stem from their technical problems. I want to emphasize that I was unable to achieve anything with these tokens, which were consumed within just a few days.
![IMG_2666](https://github.com/user-attachments/assets/821a05d8-f0be-4604-bd22-4d6b939b8a3b)
