### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by COOLWINDFRESH** [stackblitz/bolt.new#1149]
### Describe the bug

Deploying issue

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jkx6s6?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

See error

### Expected behavior

A completed task

### Platform

```
Browser name = Safari
Full version = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPad; CPU OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/130.0.6723.37 Mobile/15E148 Safari/604.1
performance.memory = undefined
Username = COOLWINDFRESH
Chat ID = 602e62fb62b9
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@COOLWINDFRESH thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
