### ISSUE TITLE
this message didn't complete its response

### ISSUE THREAD

**Issue by TunaUskudar** [stackblitz/bolt.new#1150]
### Describe the bug

this message didn't complete its response

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ai7wqk

### Steps to reproduce

Just type in anything to the AI

### Expected behavior

Complete the response and make changes

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79457029,
  "usedJSHeapSize": 75311373,
  "jsHeapSizeLimit": 2172649472
}
Username = tunauskudar
Chat ID = fb2bc215211e
```

**Comment by kc0tlh** [comment]
@TunaUskudar this is being tracked in #1073
