### ISSUE TITLE
'll help you deploy this Next.js application to Netlify. 

### ISSUE THREAD

**Issue by krisgnyc** [stackblitz/bolt.new#1156]
### Describe the bug

'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

Report Issue

Rollback to Checkpoint

Retry
Deploy this application.

I'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5yu82y

### Steps to reproduce

'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

Report Issue

Rollback to Checkpoint

Retry
Deploy this application.

I'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

### Expected behavior

Should deploy

### Screen Recording / Screenshot

'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

Report Issue

Rollback to Checkpoint

Retry
Deploy this application.

I'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53759953,
  "usedJSHeapSize": 51230049,
  "jsHeapSizeLimit": 4294705152
}
Username = krisgnyc
Chat ID = 3e3759b1c090
```

### Additional context

Error:'ll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.

Report Issue

Rollback to Checkpoint

Retry
Deploy this application.

I'll help you deploy this Next.js application to Netlify.

Deploy to Netlify

npx next build
netlify
Let me check the deployment status to get the live URL for you.

An error occured while streaming this message.
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@krisgnyc thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
