### ISSUE TITLE
unable to install dependencies or take too long

### ISSUE THREAD

**Issue by cyrilimpulse** [stackblitz/bolt.new#1158]
### Describe the bug

I spend 2 hours at night and a lot of credit for almost nothing as the server had some difficulties to install basic dependencies (failed after 10 min or take 15 minutes to install one package. 
Project sb1-6hd15s

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6hd15s

### Steps to reproduce

The project showed a blank page, and the AI attempted to reinstall the package to minimize the project's footprint, but was unsuccessful in installing the required dependencies.

### Expected behavior

Dependencies are installed within a reasonable timeframe.

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = CGuillem
Chat ID = 3d5d085e857f
```

### Additional context

N/A

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
