### ISSUE TITLE
Cannot deploy

### ISSUE THREAD

**Issue by aruthaa** [stackblitz/bolt.new#1165]
### Describe the bug

Cannot deploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4a1auc

### Steps to reproduce

https://bolt.new/~/sb1-4a1auc
click on deploy

### Expected behavior

Deployin application.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 119602538,
  "usedJSHeapSize": 115204842,
  "jsHeapSizeLimit": 4294705152
}
Username = aruthaa
Chat ID = 2b09dd8d4ab1
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@aruthaa thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
