### ISSUE TITLE
Nothings working

### ISSUE THREAD

**Issue by Jattardian** [stackblitz/bolt.new#1168]
### Describe the bug

nothings working... Nothing. I cant even run my code. I uploaded a project and i cant even run it. I want my money back. 

"what bugs do i have

prompt is too long: 216061 tokens > 200000 maximum"

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-obackr

### Steps to reproduce

1 bold. 2 type anything and it does not work

### Expected behavior

I expect bolt to give me answers to my questions or try to run my app that i already 60% built

### Screen Recording / Screenshot

![1](https://github.com/user-attachments/assets/2d81ac67-c43b-4762-b826-06acbb38fb67)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66321288,
  "usedJSHeapSize": 62287228,
  "jsHeapSizeLimit": 4294705152
}
Username = jattardian
Chat ID = 9e45cba683e2
```

### Additional context

I want my money back.

**Comment by kc0tlh** [comment]
@Jattardian thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!
