### ISSUE TITLE
prompt is too long: 200263 tokens > 200000 maximum

### ISSUE THREAD

**Issue by grupodixis** [stackblitz/bolt.new#1177]
### Describe the bug

I prompt: resetear sqlite

prompt is too long: 200263 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pavrfd

### Steps to reproduce

any prompt you do

### Expected behavior

execute the prompt

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55333558,
  "usedJSHeapSize": 50714910,
  "jsHeapSizeLimit": 4294705152
}
Username = grupodixis
Chat ID = acb0da7a7096
```

**Comment by Albix81** [comment]
i am having the same identical issue since yesterday and i lost a lot of token because of it. I tried several times to restart the question but it get stuck again but at the same time it consumed me a lot of tokens for nothing. I am quite upset to be honest...

**Comment by Welexon** [comment]
Same issue with my project, runs out of context tokens.

**Comment by kc0tlh** [comment]
@grupodixis @Albix81 @Welexon thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!
