### ISSUE TITLE
app not deployed

### ISSUE THREAD

**Issue by ANSHUKR123** [stackblitz/bolt.new#1179]
### Describe the bug

I asked the ai to deploy the LPP solver and it too long just to show an error, kindly fix this

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2pq2yx

### Steps to reproduce

just the deployment part

### Expected behavior

it should have given a deployed webapp with all the features working

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e838df14-400f-48e2-8f62-464f8294c4ea)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50164828,
  "usedJSHeapSize": 44870980,
  "jsHeapSizeLimit": 2160066560
}
Username = ANSHUKR123
Chat ID = a6842520b2d2
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by Albix81** [comment]
i had the same issue and i tried several times to restart the installation of a library but it get stuck again. At the same time i lost a lot of tokens for nothing each time that i tried to restart the same question...

**Comment by ANSHUKR123** [comment]
What is the problem Exactly?

**Comment by kc0tlh** [comment]
@ANSHUKR123 @jerminor thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!

**Comment by ANSHUKR123** [comment]
The package.json file contains mostly deprecated versions of packages
