### ISSUE TITLE
please make a feature so that we can go back to previous versions of wwebsite

### ISSUE THREAD

**Issue by srinjoydutta** [stackblitz/bolt.new#118]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, it would be great to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by FastTrackAudio** [comment]
+1, cmd + z is easy enough when your working on a single component, but when a major change happens and the AI overwrites 5-6 files and it ends up breaking, it can be hard to get back to where you were, even asking the AI to revert all of their changes sometimes you end up with a different UI

Maybe a short term solution would just be able to have a revert feature, where you can revert it to the state before your last prompt. Not perfect, but would be super helpful so you can decide what problems to fix.

Like if you ran a prompt and it came back with an error. Instead you could revert it back, specifically include in your prompt again to keep that error from happening, and then try again without losing your project history.

But versioning would be the best end goal!

**Comment by samdenty** [comment]
@pkeller3 Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
