### ISSUE TITLE
REFUNDDDDDDD

### ISSUE THREAD

**Issue by poegun** [stackblitz/bolt.new#1180]
### Describe the bug

My money went down the drain. I want my money. 10m tokens went down the drain before I could say a word.

### Link to the Bolt URL that caused the error

https://bolt.new/~/secret-python-6gogkb

### Steps to reproduce

Trash

### Expected behavior

BOOO

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 161102927,
  "usedJSHeapSize": 142014679,
  "jsHeapSizeLimit": 4294705152
}
Username = Poegun
Chat ID = 75ac6ffc120c
```

**Comment by kc0tlh** [comment]
@poegun please reach out to hello@stackblitz.com and we will get you taken care of!
