### ISSUE TITLE
Netlify deployments

### ISSUE THREAD

**Issue by JohnCarter09** [stackblitz/bolt.new#119]
**Is your feature request related to a problem? Please describe:**

I am running into a bunch of issues when trying to deploy to netlify. I cross reference my netlify dashboard and do not see this project in there (i am also not sure why i would?) I was never asked to sign into netlify or anything so that is weird.

**Describe the solution you'd like:**
Some kind of netlify integration with my Bolt account and netlify so they can talk to eachother. Espically when trying to publish to production.

**Describe alternatives you've considered:**

None at the moment, I am stuck on trying to deploy.

**Additional context:**
The chat often references a "netlify CLI" but i would not have known that unless I aksed.

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

You can publish to netlify anonymously, so you are still provided with a deployment URL. 

There's also a URL that allows you to 'claim' the page - which will allow you to manage it directly through your Netlify account.

Are you able to see these URLs when deploying?

**Comment by wforbes** [comment]
In my case, I had to remind the LLM that it is able to deploy the project for me anonymously as you suggest @kirjavascript... using this prompt:
"The maintainers of bolt.new have commented in github issues that you should be able to deploy this project anonymously to netlify for me. Could you please try to do that? I am almost out of tokens for our session (29k left), so please limit text conversation with me as much as you can."
After that it successfully deployed and provided the URL as demonstrated in ViteConf.

Before that it was encouraging me to search my Stackblitz account for integration settings with my Netlify account, but also described how I'd manually deploy it through github/netlify.
Sidenote: This was the first time I could deploy an app through bolt.new with no extra features before running out of free-tier tokens, so I'd say you guys are making great progress 👍

**Comment by kc0tlh** [comment]
This should now be resolved, thanks!
