### ISSUE TITLE
error in building 

### ISSUE THREAD

**Issue by NeiMaldaner** [stackblitz/bolt.new#1194]
### Describe the bug

when building 
An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hfv1jk

### Steps to reproduce

An error occured while streaming this message.

### Expected behavior

building 

### Screen Recording / Screenshot

npm install
src/types/index.ts
src/App.tsx
src/components/Layout.tsx
src/pages/Dashboard.tsx

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 66262285,
  "usedJSHeapSize": 61790793,
  "jsHeapSizeLimit": 2160066560
}
Username = NeiMaldaner
Chat ID = b0a0c1d06500
```

### Additional context

An error occured while streaming this message.

**Comment by kc0tlh** [comment]
@NeiMaldaner thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
