### ISSUE TITLE
ate my project when i upgraded

### ISSUE THREAD

**Issue by KMM24** [stackblitz/bolt.new#1197]
### Describe the bug

created a project for a course with adaptive quizzes. Hit my limit. Was asked to upgrade. I upgraded. Now that project--for which i upgraded--is gone. That is not a good ux. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-empwbv

### Steps to reproduce

1. create a project
2. attempt to upgrade your account in order to access more credits.

### Expected behavior

I expected to be returned to my project or at least find it in my dashboard. It appears to be completely gone. Nothing was saved.

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = KMM
Chat ID = b4ceb8929c51
```

**Comment by endocytosis** [comment]
Hi @KMM24, 

Are you able to find your project by following the instructions here: #39? Go to StackBlitz.com (same account as Bolt.new) --> Collections Tab (left-hand side) --> Open Bolt Collection.

**Comment by KMM24** [comment]
No, it was not in collections. I’ve already rebuilt, no need to follow up on this thread. Was mostly warning stackblitz that they had a bug.

On Nov 7, 2024, at 7:02 PM, Brian ***@***.***> wrote:


Hi @KMM24,
Are you able to find your project by following the instructions here: #39? Go to stackblitz.com (same account as Bolt.new) --> Collections Tab (left-hand side) --> Open Bolt Collection.
