### ISSUE TITLE
Wont let me deploy anymore, dont know why

### ISSUE THREAD

**Issue by fscheps** [stackblitz/bolt.new#1199]
### Describe the bug

The app fails to deploy.
<img width="515" alt="2024-10-30_20-53-56" src="https://github.com/user-attachments/assets/e5786739-4d3b-4212-b728-fa0f12495e7a">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-epfgzz

### Steps to reproduce

Just hitting the deploy button or asking it to deploy.

### Expected behavior

That the app is deployed (on the same place it was initially deployed)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 159558181,
  "usedJSHeapSize": 141837949,
  "jsHeapSizeLimit": 4294705152
}
Username = fertech
Chat ID = e1d81476b4cd
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@fscheps thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
