### ISSUE TITLE
bolt-remotion `npm run build` attempt fails, perhaps on TLS handshake during Headless Chrome attempt

### ISSUE THREAD

**Issue by chrismahoney** [stackblitz/bolt.new#12]
### Describe the bug

I know this is related to StackBlitz UI instead of Bolt, but I thought it may be relevant for the issues seen with failure to generate starter projects.

Upon attempting to generate the `bolt-remotion` starter project within bolt.new, moving to the StackBlitz UI provides usable Remotion functionality. However, within the project it is implied that `npm run build` should be possible in order to render out an MP4; I'm not trying to actually do that, but it did surface an issue with an attempt to use Chrome headless that appears to be related to a TLS handshake.

Running `npm run build` in a StackBlitz UI terminal fails with the following, perhaps there are some cert issues that are failing the codegen process in Bolt?

```
~/projects/bolt-remotion 3s
❯ npm run build

> template-helloworld@1.0.0 build
> remotion render HelloWorld out/video.mp4

Downloading Chrome Headless Shell https://www.remotion.dev/chrome-headless-shell

Error: socket hang up
    at connResetException (https://boltremotion-w3hy.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:9365)
    at TLSSocket.socketOnEnd (https://boltremotion-w3hy.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:3:5895)
    at TLSSocket.emit (https://boltremotion-w3hy.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:30:11015)
    at endReadableNT (https://boltremotion-w3hy.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:225:8116)
    at processTicksAndRejections (https://boltremotion-w3hy.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:192:1067)
    at https://boltremotion-w3hy.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:199092
    at _0x5c6f37 (https://boltremotion-w3hy.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:199173)
    at _0x43b57e (https://boltremotion-w3hy.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:507065)
    at https://boltremotion-w3hy.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:506819
    at Array.forEach (<anonymous>)
```

### Link to the Bolt URL that caused the error

https://stackblitz.com/edit/bolt-remotion

### Steps to reproduce

1. Go to https://bolt.new
2. Click on 'Code a video with Remotion' button below the input field.
3. Forwarded to https://bolt.new/~/bolt-remotion - code UI is empty
4. Click 'Open in StackBlitz' upper-right button
5. Terminal in SB UI works as expected, runs npm install and start commands, loads preview successfully.
6. Ctrl/Cmd+C the open terminal, and run `npm run build`

### Expected behavior

Expected: An MP4 render

Observed:
Whether or not this is related to remotion specifically, README.md implies `npm run build` is usable in context. While trying to execute, the error in the description is thrown in the SB UI Console. This issue is being opened to surface helpful information related to cert handshake that may be impacting the Bolt UI's ability to render and operate successfully.

### Platform

- OS: macOS 15.0 Sequoia
- Browser: Brave latest, public release channel

**Comment by KwintenP** [comment]
Unfortunately remotion uses uses headless Chrome under the hood during a build which is currently not supported in WebContainers (our tech to run nodejs apps in the browser env).

There could be a way of getting this working with this rust based renderer (https://github.com/clearlysid/rustymotion) if we could port that to wasm. 
Unfortunately, this is out of scope for now.
