### ISSUE TITLE
Unable to view "Preview"

### ISSUE THREAD

**Issue by mmapp23** [stackblitz/bolt.new#1200]
### Describe the bug

Unable to see preview on bolt.new website using a MacBook Air. There is only a QR code displayed and when I download NativeScript on my Android phone and scan the QR code on my project, it's just a white screen. Same as when I tried downloading NS app on my iPad and scanning the QR. I would like assistance in figuring this out before I purchase a subscription.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-k3ikg2

### Steps to reproduce

Literally just request bolt.new to show a preview of the project.

### Expected behavior

I expected to see a preview of my project creation in the preview panel.

### Platform

- OS: macOS
- Browser: Chrome
- Version: macOS 12.7.6 and Chrome 128.0.6613.138

**Comment by tfm64** [comment]
I do have the same issue on a Macbook air m2

**Comment by agamenmon** [comment]
I have on macbook pro 2017 and still has the same issue with chrome

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
