### ISSUE TITLE
Won't build or deploy the application 

### ISSUE THREAD

**Issue by MattWride** [stackblitz/bolt.new#1203]
### Describe the bug

I'll help you deploy the StressMelt application to Netlify.

Deploy StressMelt to Netlify

npx vite build
netlify
Let me check the deployment status.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jdfts5

### Steps to reproduce

click deploy

### Expected behavior

to know what the error is and what to do next given this error

### Screen Recording / Screenshot

![Screen Shot 2024-10-30 at 3 18 02 PM](https://github.com/user-attachments/assets/e23e11ce-973a-4fee-a731-427c3cc543af)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59091038,
  "usedJSHeapSize": 54200534,
  "jsHeapSizeLimit": 4294705152
}
Username = Wride
Chat ID = 5aa8a90804bf
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@MattWride thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!

**Comment by Idreesofficial** [comment]
i am also facing same issue

**Comment by Chakuchanya** [comment]
has this matter been resolved?
