### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by dice-troubles** [stackblitz/bolt.new#1206]
### Describe the bug

when deploying the project to Netlify - it causes an error. It cannot carry out the npx vite build.
![Screenshot 2024-10-30 at 22 39 03](https://github.com/user-attachments/assets/65e47e7b-8d25-4e82-ac81-d9a279de5a70)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gkszhg

### Steps to reproduce

1. click the deploy button.

### Expected behavior

I expect it not to fail.

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 154128822,
  "usedJSHeapSize": 131005186,
  "jsHeapSizeLimit": 2172649472
}
Username = dice_troubles
Chat ID = 24e8e4f2a537
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@dice-troubles thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
