### ISSUE TITLE
Critical Integration Failure: Netlify Deployment Flow

### ISSUE THREAD

**Issue by halliday-andy** [stackblitz/bolt.new#1207]
### Describe the bug

Critical Integration Failure: Netlify Deployment Flow

Issue Description:
The Netlify deployment integration in bolt.new is failing to provide essential functionality:

**Claim URL Not Exposed**

Users cannot claim their Netlify deployments
No way to access Netlify dashboard to configure environment variables
Critical for setting OpenAI API keys and Assistant IDs

Current Deployment Process:

Build succeeds
Site deploys successfully
Site is accessible at generated URL
But no way to manage the deployment

Business Impact:
Blocks users from completing OpenAI integrations
Wastes user resources with failed deployment attempts
Undermines bolt.new's value proposition for seamless deployment

Recommendation:
Please escalate this to the platform team as a P0 issue. Users need:

Exposed claim URLs in deployment responses
Clear path to Netlify dashboard access
Documentation for environment variable configuration

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-spm9dm

### Steps to reproduce

Go to this repl, review the dialog between myself and the Agent to view the repeated failures to proceed to OpenAI API configuration of the application due to the gap in Netlify setup. 

### Expected behavior

When the Agent says that "build and deploy to Netlify"  will respond with website url and a "claim url" that will link this putative integration to an account with administrative functions that is awaiting my claim. Clicking on the "claim url" in the response window in bolt.new will open a tab with access to Netlify configuration screens and final registration of a Netlify account for this integration. 

### Screen Recording / Screenshot

I apologize for the multiple deployment attempts. You're absolutely right. Let me clarify the process:

When we deploy to Netlify through bolt.new, a claim URL should be provided in the deployment response. However, I notice that the claim URL is not being shown in the responses.

The proper sequence should be:

First successful build
Single deployment that provides both the site URL and claim URL
Claim the site in Netlify using the claim URL
Configure environment variables in Netlify:
OPENAI_API_KEY
OPENAI_ASSISTANT_ID
Redeploy after configuration
Since we're not getting the claim URL in the deployment response, we should:

Stop attempting deployments until we can ensure the claim URL will be visible
Verify the build process works locally first
Wait for confirmation that the deployment tool can properly expose the claim URL
Would you like me to focus on fixing any remaining build issues before we attempt another deployment?

Rollback to Checkpoint
I would like you to escalate this issue which is costing users money. Deployment to Netlify, which is a standardized integration between bolt.new and Netlify for the purpose of seamless deployment, is blocked by the lack of integration resilience.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 150677239,
  "usedJSHeapSize": 141144651,
  "jsHeapSizeLimit": 4294705152
}
Username = andyhalliday
Chat ID = 7b9fdac7f517
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020
