### ISSUE TITLE
My problem is that I'm getting the message `prompt is too long: 204548 tokens > 199999 maximum`. I only signed up for PRO today and I no longer have any tokens? Until when?

### ISSUE THREAD

**Issue by Filippo295** [stackblitz/bolt.new#122]
My problem is that I'm getting the message `prompt is too long: 204548 tokens > 199999 maximum`. I only signed up for PRO today and I no longer have any tokens? Until when?

_Originally posted by @vieirex10 in https://github.com/stackblitz/bolt.new/issues/99#issuecomment-2395603992_

**Comment by Filippo295** [comment]
what?! you got pro today and used all your 1M token?! there must be something wrong with the tokens, i mean this is the best coding ai i've seen, it is a pity
anyway if you know better ai tools for coding please tell me what they are

**Comment by FastTrackAudio** [comment]
Also somehow managed to use 10million tokens in a day, it seems every prompt used 125k tokens. Not sure when this daily limit refreshes.

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

The error you are seeing is due to trying to send too many tokens in a single request, unrelated to your monthly limit. We are also looking into how we can raise this limit.

If you create a new chat you should still be able to make requests.

Outside of this, we are going to add a way of buying more tokens ASAP.

**Comment by itebvgmbh** [comment]
@kirjavascript I went through 10M tokens in just a couple of hours. Was that the monthly limit? I know it’s mentioned in the subscription details, but I saw a message that seemed to talk about a daily limit instead

**Comment by adlereagle88** [comment]
i have the same issue

**Comment by kc0tlh** [comment]
The other issues mentioned in this thread by @dowdavid @adlereagle88 was a bug that has been resolved now.

**Comment by mihaiban1** [comment]
Dealing with the same error. Tried refreshing the page, but the same error. I think there's too much functionality for it to continue.

**Comment by nnikolov16** [comment]
i get the same error: prompt is too long: 200011 tokens > 199999 maximum. i have 19.9M tokens remaining.

**Comment by kc0tlh** [comment]
@ashiabbott @mihaiban1 @nnikolov16 @Filippo295, update on this: It is likely because the file system of the project is too large. More to come on this soon, but as a start, try to reduce the project size or break down the app into smaller components. This may be the best approach.
