### ISSUE TITLE
Website not starting

### ISSUE THREAD

**Issue by erkibe** [stackblitz/bolt.new#1223]
### Describe the bug

It is not previewing nor showing an error message. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8wm5e3

### Steps to reproduce

1. Press start application
2. It won't start you will see the error

### Expected behavior

I would love to see the website

### Screen Recording / Screenshot

![Screenshot 2024-10-31 104821](https://github.com/user-attachments/assets/8ad59938-00b5-44b2-ad65-9cb077252c9d)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 105644284,
  "usedJSHeapSize": 100033492,
  "jsHeapSizeLimit": 4294705152
}
Username = erkibe
Chat ID = 17f2b8388d90
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
