### ISSUE TITLE
Unable to deploy on Netlify

### ISSUE THREAD

**Issue by agnirudrasikdar** [stackblitz/bolt.new#1228]
### Describe the bug

The app stopped working and is not deploying on Netlify. In the preview section it's also not loading and only a white page is being shown. Prior to this issue, Bolt was trying to fix an user login management system with firebase. When I was trying to signup using google, it was redirecting to firebase url and showing invalid request. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dbpo1g

### Steps to reproduce

I selected deploy button on Bolt

### Expected behavior

Expected behaviour:
- I should be able to register through google signup
- Email validation was missing 
- Home screen was loading as blank (white) 
- Deployment was not working

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88398519,
  "usedJSHeapSize": 85733575,
  "jsHeapSizeLimit": 4294705152
}
Username = agnirudrasikdar
Chat ID = 9e7429c68790
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@agnirudrasikdar thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
