### ISSUE TITLE
Not possible to deploy html application - error message

### ISSUE THREAD

**Issue by Gomarketingch** [stackblitz/bolt.new#1229]
### Describe the bug

I tried several times to deploy a html application, but I keep getting an error message.
An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ipc92p

### Steps to reproduce

Click on "Deploy this application".

### Expected behavior

I expected to have a ready website.

### Screen Recording / Screenshot

Screenshot:
https://prnt.sc/DsaDgawMx-Qa

### Platform

```
Browser name = Safari
Full version = 18.0
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
performance.memory = undefined
Username = gomarketing
Chat ID = cfa9a1d0d721
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by Gomarketingch** [comment]
Refund my money.

**Comment by kc0tlh** [comment]
@Gomarketingch happy to do do so via hello@stackblitz.com!

Thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
