### ISSUE TITLE
Only white page is loading

### ISSUE THREAD

**Issue by agnirudrasikdar** [stackblitz/bolt.new#1230]
### Describe the bug

The app is not loading and I only see a white page

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dbpo1g

### Steps to reproduce

Click on preview to see how the app is loading

### Expected behavior

I am expecting it to load

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73161845,
  "usedJSHeapSize": 69692185,
  "jsHeapSizeLimit": 4294705152
}
Username = agnirudrasikdar
Chat ID = 01bba3e8d909
```

**Comment by endocytosis** [comment]
Hi @agnirudrasikdar, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
