### ISSUE TITLE
Bolt Chats Disappeared

### ISSUE THREAD

**Issue by jcunio06** [stackblitz/bolt.new#1234]
I wrote code in Bolt and it is gone. I paid for subscription, was developing code in Bolt, and now it is all gone. Please help me get it back.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
