### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by baadigi** [stackblitz/bolt.new#1237]
### Describe the bug

Won't deploy 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yeehbu

### Steps to reproduce

click deploy 

### Expected behavior

deploys 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51816613,
  "usedJSHeapSize": 48530189,
  "jsHeapSizeLimit": 4294705152
}
Username = BaaDigi
Chat ID = f084f355d50c
```

### Additional context

Checking validity of types ...Failed to compile.

./app/[city]/[service]/page.tsx:6:10
Type error: Module '"@/lib/cities"' has no exported member 'getCity'.

Error:
```
An error occured while streaming this message.
```

**Comment by baadigi** [comment]
> Build failed because of webpack errors
   Creating an optimized production build .

**Comment by baadigi** [comment]
I keep getting this error now

**Comment by kc0tlh** [comment]
@baadigi appreciate your patience as we track this high priority issue in #1073
