### ISSUE TITLE
Hanging on installing dependencies 

### ISSUE THREAD

**Issue by davidpreid** [stackblitz/bolt.new#1243]
### Describe the bug

App won't start as its hanging on installing dependencies 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-d1ywbh

### Steps to reproduce

npm install 

System sits there

### Expected behavior

Application should start 

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = davidpreid
Chat ID = ab2a04e52a4a
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
