### ISSUE TITLE
still take request charging fortokens and not completing the task 

### ISSUE THREAD

**Issue by chefbc2k** [stackblitz/bolt.new#1246]
### Describe the bug

still take request charging fortokens and not completing the task 

### Link to the Bolt URL that caused the error

https://bolt.new/~/nativescript-stackblitz-templates-lxghss

### Steps to reproduce

input command and it just describes how to implement in something with out doing so 

### Expected behavior

to follow my commands 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88068513,
  "usedJSHeapSize": 76487381,
  "jsHeapSizeLimit": 4294705152
}
Username = chefbc2k41
Chat ID = 01942ddd34e2
```

**Comment by kc0tlh** [comment]
@chefbc2k appreciate your patience as we track this high priority issue in #1073
