### ISSUE TITLE
I cannot deploy the app to netlify

### ISSUE THREAD

**Issue by jaimedevelop** [stackblitz/bolt.new#1248]
### Describe the bug

it is not specific, I have tried like five times and same error happens

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hswjk4

### Steps to reproduce

deploy button clicked.

### Expected behavior

deploy the app

### Screen Recording / Screenshot

click the button

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 121620997,
  "usedJSHeapSize": 115426249,
  "jsHeapSizeLimit": 2160066560
}
Username = jaimedevelop
Chat ID = 2249e89ce78a
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@jaimedevelop thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
