### ISSUE TITLE
Deploy to Netlify  npx vite build netlify I'll wait for the deployment to complete and then share the live URL with you. The deployment process will:  Build the application using Vite Deploy the static files to Netlify Provide you with a live URL to access your site Let me check the deployment status...  An error occured while streaming this message.   Report Issue  Undo  R

### ISSUE THREAD

**Issue by krisgnyc** [stackblitz/bolt.new#1252]
### Describe the bug

Deploy to Netlify

npx vite build
netlify
I'll wait for the deployment to complete and then share the live URL with you. The deployment process will:

Build the application using Vite
Deploy the static files to Netlify
Provide you with a live URL to access your site
Let me check the deployment status...

An error occured while streaming this message.

Report Issue

Undo

R

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yz7rjo

### Steps to reproduce

Deploy to Netlify

npx vite build
netlify
I'll wait for the deployment to complete and then share the live URL with you. The deployment process will:

Build the application using Vite
Deploy the static files to Netlify
Provide you with a live URL to access your site
Let me check the deployment status...

An error occured while streaming this message.

Report Issue

Undo

R

### Expected behavior

Deploy to Netlify

npx vite build
netlify
I'll wait for the deployment to complete and then share the live URL with you. The deployment process will:

Build the application using Vite
Deploy the static files to Netlify
Provide you with a live URL to access your site
Let me check the deployment status...

An error occured while streaming this message.

Report Issue

Undo

R

### Screen Recording / Screenshot

Deploy to Netlify

npx vite build
netlify
I'll wait for the deployment to complete and then share the live URL with you. The deployment process will:

Build the application using Vite
Deploy the static files to Netlify
Provide you with a live URL to access your site
Let me check the deployment status...

An error occured while streaming this message.

Report Issue

Undo

R

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68187734,
  "usedJSHeapSize": 60954290,
  "jsHeapSizeLimit": 4294705152
}
Username = krisgnyc
Chat ID = 10a0d0a794c1
```

### Additional context

Deploy to Netlify

npx vite build
netlify
I'll wait for the deployment to complete and then share the live URL with you. The deployment process will:

Build the application using Vite
Deploy the static files to Netlify
Provide you with a live URL to access your site
Let me check the deployment status...

An error occured while streaming this message.

Report Issue

Undo

R

**Comment by kc0tlh** [comment]
@krisgnyc thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
