### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by Snipersnippet** [stackblitz/bolt.new#1253]
### Describe the bug

When hitting deploy is just runs nothing but errors.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hjq1vv

### Steps to reproduce

Deploy app

### Expected behavior

Actually deploy the app

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46838168,
  "usedJSHeapSize": 43138612,
  "jsHeapSizeLimit": 1098907648
}
Username = Code_red
Chat ID = c67234b18798
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@Snipersnippet thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
