### ISSUE TITLE
White screen in preview 

### ISSUE THREAD

**Issue by agnirudrasikdar** [stackblitz/bolt.new#1257]
### Describe the bug

White screen in preview .  I am unable to see anything on the UI  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uuy2zz

### Steps to reproduce

White screen in preview 

### Expected behavior

I would like to see visuals . 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111012331,
  "usedJSHeapSize": 103631479,
  "jsHeapSizeLimit": 4294705152
}
Username = agnirudrasikdar
Chat ID = 93c689a99e03
```

**Comment by endocytosis** [comment]
Hi @agnirudrasikdar, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
