### ISSUE TITLE
Manually Refresh Tokens

### ISSUE THREAD

**Issue by FastTrackAudio** [stackblitz/bolt.new#126]
**Is your feature request related to a problem? Please describe:**

Paying for a monthly subscription has a daily limit, 100% understandable. 

**Describe the solution you'd like:**

I love coding this tool, and would love to be able to buy another daily quota for $1-$2, maybe you can buy packages where you buy 10 daily quote extensions for around $15. Sometimes Im able to spend awhile coding and fleshing out an app idea and I ran into that problem today. 

**Describe alternatives you've considered:**

It also doesn't tell me when my tokens refresh, so I don't know how long I wont be able to use the tool. 

**Additional context:**

no other context

**Comment by divparty** [comment]
This is urgently needed, we have run into the limit and there is no way to add more tokens?! allow us to give you money...
Also it would be good to easily see the usage somewhere so we know we are approaching a limit.

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, it would be great to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by patiljignesh** [comment]
Hi there, I support this request big time, I have reached 325K of 10M monthly tokens remaining, but no way to add more tokens.

**Comment by patiljignesh** [comment]
@FastTrackAudio @divparty @kirjavascript,I assume the workaround would be to create another account and relink to that account?

**Comment by FastTrackAudio** [comment]
@patiljignesh Im sure that could possibly work, but you can only have so many emails before it gets overwhelming. 

Its also unclear if this is a daily or monthly limit, as as im running out, the chat says that its a daily limit, but the subscription says the same number (10M) is a monthly limit. I've waited over a day and my tokens still haven't refreshed :/.

**Comment by patiljignesh** [comment]
@FastTrackAudio I guess as a temp solution, I mean there will be lots of users with the same issue. The Bolt Team has to push this one out as soon as possible. It's an opportunity to generate more revenue. 

My chat says this. It has been refreshing as I use it. I don't see any daily limits. 
![Screenshot 2024-10-07 at 15 30 28](https://github.com/user-attachments/assets/62743eda-0771-4c5b-ba97-e0943518b966)

**Comment by FastTrackAudio** [comment]
Hmm, maybe I was just blind and read it wrong, I thought it was daily for sure because I remember thinking that was weird. However, now it just says that I’ve used all my tokens so I can’t check, but I certainly hope I can use it before next month

**Comment by cosmicwork** [comment]
OMG - i thought it said 10m tokens daily...... I easily blew through my tokens in a 6hour session.
How can we improve this?
10m per month is almost worthless.
This needs to be fixed.
I was making amazing progress in a website design.
Now I feel stifled.
HELP

**Comment by FastTrackAudio** [comment]
@cosmicwork I went back on a different account, and I can confirm it says "Daily" when the token limit is about to be reached, I agree 10m is pretty tough for an entire month, especially with each request seemingly taking 125k. You get less than 100 prompts that way. I know the devs are working hard on a fix and a solution for us, excited for what it will bring.

**Comment by CrypticVariable** [comment]
+1

**Comment by verioussmith** [comment]
Running out of tokens in the middle of a coding session and you lose track is not good.  Please add this feature ASAP.  +1

**Comment by argenta1** [comment]
I ran out of tokens! Why dont you want to take my money? I need to finish my app! This will only create confusion and bad customer experience. Let us purchase extra tokens when we need to. Now i dont know when i will be able to finish my app was one prompt away from finish it, now i must wait a whole month??

**Comment by divparty** [comment]
@argenta1 they posted on X today that they are adding the ability to buy more credits in the next few days, so we won't have to wait long thankfully :)
Here's the post:
https://x.com/ericsimons40/status/1843345406576787496

**Comment by verioussmith** [comment]
> @argenta1 they posted on X today that they are adding the ability to buy more credits in the next few days, so we won't have to wait long thankfully :) Here's the post: https://x.com/ericsimons40/status/1843345406576787496

I read this post yesterday and saw that they said, _"In interim, we've enabled paid users to get 500k tokens for free per day until token reloading has landed- we hope this is enough to keep you rolling for the next few days!"_

This is not true because for 2 days I have gone to my premium account and refreshed my page but didn't see any new tokens added for the last couple of days.

I've exported my project to cursor now and probably wont bring it back into bolt.

**Comment by kc0tlh** [comment]
@FastTrackAudio thanks for the feedback! Token reloading and usage monitoring are now both live on production!

Reloading: https://x.com/stackblitz/status/1844138865508134999
Usage Monitoring: https://x.com/stackblitz/status/1844144363384996169 

Also, to clarify:
Free users have a daily limit of 150k, and a monthly limit of 1m
Pro users have a daily limit of 10m, and a monthly limit of 10m (so really, no daily limit)

**Comment by kc0tlh** [comment]
@verioussmith sorry for the rough initial experience. I think you may have been a victim of some issues we were having with inefficient token usage. I have reset your account to have the full 10m tokens available again for this month.

@argenta1 same for you my friend :)

If anyone else experienced rapid token usage, please email me (alex@stackblitz.com) and I will reset you as well :)

Appreciate the feedback on this early beta product and hope you will continue on this journey with us as we add features and stability!

**Comment by argenta1** [comment]
Thank you! Very much appreciated! Loving the software its so addicting !

**Comment by patiljignesh** [comment]
@argenta1 you asked for it, now it's gone from $10 to $20.

**Comment by argenta1** [comment]
$20 for basically having a dev ai agent that creates web apps? I will gladly pay $100 . I literally just build 2 web apps in less than 24hrs fully deployed and functional that are going to help my home service business that will pay for the service its self 100x

**Comment by divparty** [comment]
Is it just me or can we no longer buy credit top ups again?

**Comment by patiljignesh** [comment]
> Is it just me or can we no longer buy credit top ups again?

Yes, I can't seem to purchase either. But the button above the chat says Subscribe to Pro 2 and I don't see any pro 2.

**Comment by patiljignesh** [comment]
@argenta1 unfortunately, I am not at that level yet. Working on a very tight budget.

**Comment by argenta1** [comment]
@patiljignesh Use bolt.new to make web apps and then get customers to pay you for that web apps and then youll be profitable! Im just saying bolt is worth its value in the marketplace for people like me than dont know how to code. Now every idea i have i can quickly prototype but if theres usage limits it breaks the flow. I would rather just pay for extra tokens in case im moving forward with the web apps. Because im essentially paying for it to be build just how i would pay any other developer to finish the web apps

**Comment by patiljignesh** [comment]
@divparty 

An update for you and others. 

![Screenshot 2024-10-11 at 18 13 08](https://github.com/user-attachments/assets/cde6d4c5-85ab-4037-8488-cb0281ced6f9)
