### ISSUE TITLE
Fails! a lot and I pay tokens

### ISSUE THREAD

**Issue by grupodixis** [stackblitz/bolt.new#1260]
### Describe the bug

Fails! a lot and I pay tokens

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xdhufe

### Steps to reproduce

Fails! a lot and I pay tokens

### Expected behavior

Fails! a lot and I pay tokens

### Screen Recording / Screenshot

Fails! a lot and I pay tokens

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67374649,
  "usedJSHeapSize": 61385141,
  "jsHeapSizeLimit": 4294705152
}
Username = grupodixis
Chat ID = b0a20e18bd74
```

### Additional context

Fails! a lot and I pay tokens

**Comment by kc0tlh** [comment]
@grupodixis appreciate your patience as we track this high priority issue in #1073
