### ISSUE TITLE
issue with uploading images 

### ISSUE THREAD

**Issue by RuthvikManju** [stackblitz/bolt.new#1264]
### Describe the bug

I have been trying to add images to my portfolio and its using a lot if token but its failing to update the portfolio, and it encounters a lot of errors and it crashes 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nsnmer?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

please try to add images in the prompt section and and you will see it is unable to add the images 

### Expected behavior

I wanted my portfolio's "About" section to be uploaded along with the images I provided, but it hasn’t been able to do that. Instead, it randomly chooses an image from the web and attaches it. Many times, the preview screen crashes, and it doesn’t work at all. I feel like I am wasting my tokens for unnecessary reasons.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/b3dbfc16-e6c4-46b4-a66a-fb8913a99906)
![Screenshot 2024-10-31 181309](https://github.com/user-attachments/assets/2709ea52-afbb-48fc-8c21-5296cdcd53a1)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
iam using my windows machine I7 intel evo

### Additional context

I bought the pro version and I purchased the pro version and was completely dissatisfied with the bolt's performance. I feel it's a waste to invest 20 dollars in this. I was completely dissatisfied with the performance of the bolt. new and i think its waste to invest 20 dollars for this, please initiate the refund

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking the preview issue here: #1791. Improvements continue to be made. Regarding image uploads, we are aware of the issue and are tracking it here: #1809, along with potential workarounds. Refund requests are handled through hello@stackblitz.com.
