### ISSUE TITLE
Chat/Project lost and tokens lost

### ISSUE THREAD

**Issue by lewismcgui** [stackblitz/bolt.new#1268]
### Describe the bug

Was working on an App, and as it does randomly the preview freezes so I reloaded, and then it instantly reset the whole application, losing over 10m tokens and countless hours, I've went into collections and my project and it's all gone. This is awful, with no chat history or backups, I've essentially had my tokens deleted without pressing it. What can be done about this? can it be recovered, can we get some form of refund for the tokens?

URls are empty on search history.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s7p7at

### Steps to reproduce

NA

### Expected behavior

to be able to get my chat history back

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows chrome newest version

### Additional context

Is it possible to get these tokens credited? Because I lost the chat, just before the rollback feature

**Comment by kc0tlh** [comment]
@lewismcgui Apologies for this unfortunate experience! We are tracking a couple of other folks that seem to have had the same thing happen in #1148. 

Please reach out to hello@stackbooks.com for credits!
