### ISSUE TITLE
 Failed to save project. You can download your project by clicking this notification

### ISSUE THREAD

**Issue by stevejford** [stackblitz/bolt.new#1269]
### Describe the bug

Says this evrytime I load the project
Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

Failed to save project. You can download your project by clicking this notification

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ajrj2u

### Steps to reproduce

try to deploy to netlify

### Expected behavior

deploy

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by j4k0m** [comment]
Same here

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2762.
