### ISSUE TITLE
refund !!!!!use up token of bugs 

### ISSUE THREAD

**Issue by Abstractfocus** [stackblitz/bolt.new#1273]
the system throws up way to many errors and then uses up tokens to fix them but the fixes arent good . I would like a refund please

**Comment by agnirudrasikdar** [comment]
I am facing a similar issue as well and totally resonate with this thought

**Comment by kc0tlh** [comment]
@Abstractfocus @agnirudrasikdar Apologies for the frustrating experience! Refunds are being processed via hello@stackblitz.com. Thanks for your pateience.
