### ISSUE TITLE
I logon my Bolt on different PC. But it will show different Apps which created by myself. I would like to see all APPs when I logon different PC with same account.

### ISSUE THREAD

**Issue by FreemanLuo** [stackblitz/bolt.new#1276]
### Describe the bug

I logon my Bolt on different PC. But it will shows diffrent Apps which I created by myself. I would like to see all APPs when I logon different PC with same account.

### Link to the Bolt URL that caused the error

I logon my Bolt on different PC. But it will shows diffrent Apps which I created by myself. I would like to see all APPs when I logon different PC with same account.

### Steps to reproduce

I logon my Bolt on different PC. But it will shows diffrent Apps which I created by myself. I would like to see all APPs when I logon different PC with same account.

### Expected behavior

I logon my Bolt on different PC. But it will shows diffrent Apps which I created by myself. I would like to see all APPs when I logon different PC with same account.

### Screen Recording / Screenshot

I logon my Bolt on different PC. But it will shows diffrent Apps which I created by myself. I would like to see all APPs when I logon different PC with same account.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
This is tracked in #39
