### ISSUE TITLE
application failed to install dependencies and start

### ISSUE THREAD

**Issue by AstroSpeed** [stackblitz/bolt.new#1278]
### Describe the bug

application failed to install dependencies and start

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-im9uut

### Steps to reproduce

sorry but i have no idea

### Expected behavior

application was to install dependencies and start

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 178887679,
  "usedJSHeapSize": 172771791,
  "jsHeapSizeLimit": 4294705152
}
Username = AstroSpeed
Chat ID = a6d3e87780f3
```

### Additional context

application failed to install dependencies and start

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
