### ISSUE TITLE
I need to speak with someone NOW

### ISSUE THREAD

**Issue by wavemaker777** [stackblitz/bolt.new#1282]
Have been experiencing tremendous frustration with working with this platform I am behind when the deadline and as a result of my decision to go with this platform I I've been unable to produce a website with minimal functionality for my design specifications I need someone to contact me and this frustration has been put days and my efforts to reach out to someone have fruit fruitless it will support links goes to 40 fours or ticket submission.now meter utilize my email because it's not recognized as a work email I need assistance and I need it now

**Comment by kc0tlh** [comment]
@wavemaker777 apologies for the frustrating experience during our beta period. Customer support can be reached at hello@stackblitz.com.
