### ISSUE TITLE
 Build application failure

### ISSUE THREAD

**Issue by jalsmida321** [stackblitz/bolt.new#1284]
### Describe the bug

when i want to deplory, it can't Build application:An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-eurdat

### Steps to reproduce

Deploy this application.

### Expected behavior

I want to have a preview to my application，but it doesn't work.

### Screen Recording / Screenshot

![Uploading 微信截图_20241101173045.png…]()

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 91155952,
  "usedJSHeapSize": 86662256,
  "jsHeapSizeLimit": 4294705152
}
Username = jalsmida321
Chat ID = 2c7cfb7f9c68
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@jalsmida321 thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!

**Comment by JkevinFv** [comment]
Error de aplicación
NotFoundError: No se pudo ejecutar 'removeChild' en 'Node': El nodo que se va a eliminar no es un hijo de este nodo.
    en Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:25974)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27253)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

**Comment by JkevinFv** [comment]
![Captura de pantalla 2024-11-22 112408](https://github.com/user-attachments/assets/e7042307-b57b-42bd-83a2-5ad8c06d4dbd)

Application Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:25974)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27253)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
