### ISSUE TITLE
Old Chats Dissapper

### ISSUE THREAD

**Issue by anaximanrus** [stackblitz/bolt.new#1287]
### Describe the bug

When I login from a new device my old chats dissappear.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Login 
2. Check Siderbar for previous chats 

### Expected behavior

I shoudl be able to find my old chats.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@anaximanrus we are fixing this next week, but the workaround for now can be found in #39
