### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by abisong** [stackblitz/bolt.new#1290]
### Describe the bug

'll wait for the deployment to complete and provide you with the live URL. Once deployed, you'll be able to access your Drone Defense Control Dashboard online.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mmjmef

### Steps to reproduce

Click on Deploy this application.

### Expected behavior

Successful deployment to production

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 188729962,
  "usedJSHeapSize": 183254634,
  "jsHeapSizeLimit": 4294705152
}
Username = abisong
Chat ID = 7c481987f55e
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Tracking this in #1022
