### ISSUE TITLE
My whole project got removed

### ISSUE THREAD

**Issue by W-EXOTIC-W** [stackblitz/bolt.new#1293]
### Describe the bug

I was trying to create a website and all of a sudden i get an error and everything gets deleted and I paid for this.
![image](https://github.com/user-attachments/assets/fb8c69db-6beb-4a3b-9846-a4078642714f)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-j3zcyo

### Steps to reproduce

1.Login
2.Click on Chats
3. Click on most recent chat
4. It will say there is an error

### Expected behavior

It wouldn't load the project

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/f8855882-46c8-44bd-a6d7-aa2aa8d4b937)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57104134,
  "usedJSHeapSize": 39442210,
  "jsHeapSizeLimit": 4294705152
}
Username = W-EXOTIC-W
Chat ID = 45e1e1d1c356
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@W-EXOTIC-W please use [the instructions here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2445044619) to reload your project into Bolt
