### ISSUE TITLE
Failing to install dependencies and using bad url's burning through credits

### ISSUE THREAD

**Issue by backtog33k** [stackblitz/bolt.new#1294]
### Describe the bug

Attempting to use bad URLs, which break builds and report 'unknown errors,' should NEVER cost credits. This is a problem on the platform side. I must have burned through about 5 million credits yesterday trying to get this to build simply until it finally realised it was just using a bad URL.

I gave up on it yesterday and thought, whatever its the 1st of the month tomorrow my credits will reset, yet I only have 144k now ? I pay for 20 million per month.

I was testing this out for rapid prototyping to try and convince my team to adopt it but I have to say, its not a good start.

This issue only started after it found errors in its own code repeatedly and I let it fix them which put me in to  a death spiral of credit use.

❯ npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-draggable - Not found
npm ERR! 404 
npm ERR! 404  '@types/react-draggable@^3.3.3' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-01T11_38_38_390Z-debug-0.log

~/project 5s
❯ 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2g17je

### Steps to reproduce

Ask bolt.new to fix this error that it created itself:

[plugin:vite:import-analysis] Failed to resolve import "react-draggable" from "src/components/meetings/ParticipantGrid.tsx". Does the file exist?
/home/project/src/components/meetings/ParticipantGrid.tsx:2:22
17 |  var _s = $RefreshSig$();
18 |  import { useRef, useState, useEffect } from "react";
19 |  import Draggable from "react-draggable";
|                         ^
20 |  import { Maximize2, Minimize2, MicOff, VideoOff } from "lucide-react";
21 |  function VideoWindow({
at TransformPluginContext._formatError (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49304:41)
at TransformPluginContext.error (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49299:16)
at normalizeUrl (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64090:23)
at async eval (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64222:39)
at async TransformPluginContext.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64149:7)
at async PluginContainer.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49145:18)
at async loadAndTransform (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51978:27)
at async viteTransformMiddleware (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:61930:24
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.

Then watch it fail to install Add react-draggable dependency

### Expected behavior

It uses valid url's and does not burn through your credits repeatedly then report unknown errors

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86466715,
  "usedJSHeapSize": 78485411,
  "jsHeapSizeLimit": 4294705152
}
Username = backtogeek
Chat ID = 65804b9fdff7
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
