### ISSUE TITLE
Постоянна ошибка

### ISSUE THREAD

**Issue by BogateyDi** [stackblitz/bolt.new#1299]
### Describe the bug

NotFoundError: Не удалось выполнить «insertBefore» для «Node»: Узел, перед которым должен быть вставлен новый узел, не является дочерним по отношению к этому узлу.
    в ро (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:25478)
    в je (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:30669)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fhboxj

### Steps to reproduce

После попытки устранить ошибку или разместить сайт

### Expected behavior

Не возможность исправить или так
NotFoundError: Не удалось выполнить «insertBefore» для «Node»: Узел, перед которым должен быть вставлен новый узел, не является дочерним по отношению к этому узлу.
    в ро (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:25478)
    в je (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:30669)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)
    в кс (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    в Ne (https://bolt.new/assets/comComponents-B64jh5hJ.js:24:27401)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111265489,
  "usedJSHeapSize": 96891345,
  "jsHeapSizeLimit": 4294705152
}
Username = BogateyDi
Chat ID = 28ea38035895
```

**Comment by AriPerkkio** [comment]
Hey @BogateyDi, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
