### ISSUE TITLE
Slow locally compared to bolt.new

### ISSUE THREAD

**Issue by VersaceXcodes** [stackblitz/bolt.new#13]
### Describe the bug

I downloaded the code and its slow compared to the commercial one in bolt.new, how can i make it as fast as bolt.new?

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

clone, run prompt 'build todo'

### Expected behavior

should be fast like bolt.new

### Platform

- OS: [e.g. macOS ]

**Comment by KwintenP** [comment]
Unfortunately, there isn't much we can do about that. 

In bolt, it uses our node.js runtime called WebContainers. This however only runs in the browser.

**Comment by samdenty** [comment]
if you're cloning the local repo - that could be because the `ANTHROPIC_API_KEY` isn't on a paid plan. Antrophic can rate limit free tokens, to get the best experience I'd add funds to your Anthropic API console
