### ISSUE TITLE
Using up credits to fix problems but doesnt fix the problem

### ISSUE THREAD

**Issue by maverickcowboy** [stackblitz/bolt.new#1305]
### Describe the bug

It keeps saying it's updating the issues and using credits to solve it's own problems which are the same problems over and over. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m2yg93

### Steps to reproduce

i keep clicking fix problems and the same problems occur even though it says it fixes them.

### Expected behavior

it should at the very least fix the problem or some of the problems so there is progress. not going in a circle. also using credits when clicking fix problems is a big issue because it will take up a lot of credits being stuck in a loop

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62425665,
  "usedJSHeapSize": 53766925,
  "jsHeapSizeLimit": 4294705152
}
Username = MaverickCowboy
Chat ID = 1e1ed2f62366
```

**Comment by kc0tlh** [comment]
Please see #678 for tips and tricks on working through errors efficiently
