### ISSUE TITLE
 prompt is too long: 200452 tokens > 200000 maximum

### ISSUE THREAD

**Issue by melvinlim87** [stackblitz/bolt.new#1306]
### Describe the bug

https://github.com/user-attachments/assets/eb135105-7e54-4163-9caa-91d5dc47c07d
my prompt is not even 200k long. and it doesnt seems to be writing more than 200k characters too. but i face this problem. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nrfa3q

### Steps to reproduce

1) type the page About & Logs is blank due to bugs when i type step 2 then error occurs
2) type prompt is too long: 200430 tokens > 200000 maximum

### Expected behavior

please solve the 200k token issues, it seems like we are spending more tokens as compared to 2 weeks ago. There is definitely an increase in the tokens usage per prompt right now

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@melvinlim87 thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!

**Comment by So3093** [comment]
we are locked up now we cannot do anything any prompt is too long

**Comment by deandre233** [comment]
I JUST HAD THIS HAPPEN TO ME
