### ISSUE TITLE
Build error multiple times

### ISSUE THREAD

**Issue by plugmakr** [stackblitz/bolt.new#131]
### Describe the bug

Build failed because of webpack errors
   Creating an optimized production build .
   
   It was building without issues for a while then suddenly just stopped. I started another project that seems to be building just fine.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1uktfe

### Steps to reproduce

I click on Deploy

I've initiated the deployment process for the PCReview.co application. The build command npm run build will be executed, and the contents of the out directory will be deployed to Netlify.

Now, let's wait for the deployment to complete and retrieve the deployment status.

Failed building the project. Make sure the build command is correct and try again.

### Expected behavior

Should build and launch in netlify

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = plugmakr
Chat ID = f2c5964b9640
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report! 😃

We're tracking this issue internally and will let you know when we have a fix in place.

**Comment by samdenty** [comment]
this should be resolved. If not we're adding auto-fixes for deploy build errors which you can track in https://github.com/stackblitz/bolt.new/issues/46
