### ISSUE TITLE
 An error occured while streaming this message.

### ISSUE THREAD

**Issue by jeffersongarcia** [stackblitz/bolt.new#1314]
### Describe the bug

Error in npx vite build.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lfvzqx

### Steps to reproduce

1. Bolt.new application
2. Create the app
3. Error in deploy NPX VITE BUILD

### Expected behavior

![Screenshot 2024-11-01 155705](https://github.com/user-attachments/assets/a6d76353-02d6-4455-8969-bbbc0ead9598)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82808351,
  "usedJSHeapSize": 80165975,
  "jsHeapSizeLimit": 4294705152
}
Username = jeffersongarcia
Chat ID = 8373716a0731
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@jeffersongarcia thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
