### ISSUE TITLE
wont let me deploy

### ISSUE THREAD

**Issue by CheesyPoofs346** [stackblitz/bolt.new#1315]
### Describe the bug

IDK

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-l5sdud

### Steps to reproduce

skib

### Expected behavior

deploy the app

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/2ca17529-82ab-4f74-8f41-c8acdaf03be9)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 148933452,
  "usedJSHeapSize": 142677368,
  "jsHeapSizeLimit": 2003042304
}
Username = test165
Chat ID = dff1ce9c4a20
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@CheesyPoofs346 thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
