### ISSUE TITLE
Can't review flutter code.

### ISSUE THREAD

**Issue by mdmahib10** [stackblitz/bolt.new#1319]
### Describe the bug

Although flutter is not included in this ai. It should be added soon with preview support. The code generation worked fine. Just needed the preview support.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-auin5z

### Steps to reproduce

1. Tell the ai to create a flutter app
2. after generating code click on the preview option
3. it will not show any thing

### Expected behavior

it will show a white screen without anything rendering

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 59914193,
  "usedJSHeapSize": 54243825,
  "jsHeapSizeLimit": 4294705152
}
Username = mdmahib10
Chat ID = 762fe7ba11bd
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Currently, Bolt only supports web programming languages.

**Comment by CodePhyt** [comment]
is there an update about flutter bolt.new had an update but im not sure if it had any features like flutter, any suggestions on LLMs that can run flutter ?
