### ISSUE TITLE
picture upload

### ISSUE THREAD

**Issue by ailokemi** [stackblitz/bolt.new#1321]
### Describe the bug

every picture I try to upload when making a homepage, it turns out broken and not viewable, i have tried to uplode different file type pictures

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-prbvlh

### Steps to reproduce

1. click on the chain button 2. upload picture 3. make it use the picture.

### Expected behavior

upload a working picture

### Screen Recording / Screenshot

![image (2)](https://github.com/user-attachments/assets/7398b7c1-a233-46fe-9407-254a8c09d1b8)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57495893,
  "usedJSHeapSize": 51277369,
  "jsHeapSizeLimit": 2160066560
}
Username = ailokemi
Chat ID = 9b00ba35cbd8
```

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking it here: #1809.
