### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by welingtonoliveira** [stackblitz/bolt.new#1325]
### Describe the bug

On build application i have a great problem, because i cant build and the error are unknow.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hbaldz

### Steps to reproduce

when i try to deploy

### Expected behavior

deploy the system

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72586312,
  "usedJSHeapSize": 54470588,
  "jsHeapSizeLimit": 4294705152
}
Username = welingtonoliveira
Chat ID = 51dd118de3b3
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it and potential workarounds here: #2019
