### ISSUE TITLE
Broken image icon

### ISSUE THREAD

**Issue by pavle019** [stackblitz/bolt.new#1326]
### Describe the bug

The images on the website are not displaying properly and bolt can't figure it out. It's just showing the Broken image icon. 

I would love to get some help from you. Thanks! 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-e47miq

### Steps to reproduce

Tried multiple propmpts. 

### Expected behavior

Show the image in the preview.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57354953,
  "usedJSHeapSize": 55598865,
  "jsHeapSizeLimit": 2160066560
}
Username = pavle
Chat ID = 06e002528820
```

**Comment by endocytosis** [comment]
Hi @pavle019,

Appreciate the feedback. We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1809.
