### ISSUE TITLE
prompt is too long: 200156 tokens > 200000 maximum 

### ISSUE THREAD

**Issue by Habartru** [stackblitz/bolt.new#1330]
### Describe the bug

prompt is too long: 200156 tokens > 200000 maximum
![Скриншот 02-11-2024 041720](https://github.com/user-attachments/assets/ecc72dfb-a3ac-4207-9c0b-c6d3b25c48fe)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pesz3g

### Steps to reproduce

it just shows up in chat. I updated, rebooted, cleared the cache, nothing helps. It just stopped working and gives an error.

### Expected behavior

chat should work

### Platform

```
Browser name = Chrome
Full version = 132.0.0.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62230805,
  "usedJSHeapSize": 55071329,
  "jsHeapSizeLimit": 4294705152
}
Username = Habartru
Chat ID = f3cfb0336eba
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.

**Comment by Habartru** [comment]
I wrote earlier and I want to share my thoughts about exceeding the context window limit again.  my project went beyond the limits of what was possible in bolt at the stage when I had already spent $ 300 on it. moreover, he was already at the stage when there were little things left. but faced with the problem of the system's failure to continue working with the project files, I began to look for ways to fix it. for a week I wrote letters, created topics on github and received the same answers as everyone else. a week later, the developers recommended using the ignore file to exclude it from the context. but the thing is that this will only work if you assemble a modular project from different components that are minimally connected to each other, but if your project works as one system, then you are doomed to failure. The AI simply forgets about how the project should look as a whole, and begins to create code, disrupting performance and connections with already created parts of the project placed in ignore. while I was coming to this understanding, I spent another $200 creating forks, trying to get at least what was there. Now I have a reasonable question for the developers, of course with full respect for their work and understanding of the complexity of the pioneers, - tell me here and in other branches I have met people like myself who unknowingly, due to the lack of any warnings, started creating projects and stopped because of these problems, losing time and money and remaining in fact, with a one-on-one problem. is there any plan on your part to compensate for the loss of users, in terms of refunds, or accrual of tokens to the balance, or will you continue to ignore it? don't you think that at this stage you will get more negativity than a well-deserved HYPE? did you know about the limitation of the context window when launching bolt, and if you did, why didn't you warn users that it is not recommended to create sites that are more than banal landing pages?  someone in your team has obviously given up on this bolt. And returning to my problem, I want to ask another and main question, how do I complete my project, are you ready to help me with this, or do I have to experiment again, for my money, in some way that is still incomprehensible to me?  This is a post without negativity and some kind of commercialism, I just want to get answers to questions, like others here.  And as a possible piece of advice, maybe you should think about delineating projects from the inside? for example, you could keep a counter for a context window, and when you reach close to the limit, start a new window, but with the ability to transfer information about the project from the first one. that is, in fact, a multi-agent communicating system. this will not be necessary for everyone, but only for those who really do something voluminous, and bring you the most money. I hope you understand what I mean.  and another point, from the practice of observing the use of bolts. is it possible to prescribe a condition in the system script under which error messages from the user will be deleted from the context window, especially those that the bolt fixes on the machine? it seems that they are not required in the context at all, but they take up a very large amount of context.   I'm sorry that I write so much, and maybe not everything is on the case, but there are a lot of questions, but there are no answers yet, and I don't see the point in carrying money back into the bolt, having unfinished even one project.... Thanks for attention.
