### ISSUE TITLE
Deployment problem

### ISSUE THREAD

**Issue by zenacarbeni** [stackblitz/bolt.new#1332]
### Describe the bug

Unable to deploy app that was being coded by Bolt

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4wdzln

### Steps to reproduce

Click "deploy" button. 

### Expected behavior

Expected to deploy the app

### Platform

```
Browser name = Firefox
Full version = 130.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
performance.memory = undefined
Username = zenacarbeni
Chat ID = 3c43c621b3f0
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.

**Comment by zenacarbeni** [comment]
Hi Brian

Thanks for your reply.

Am I able to run the deployment again?

Because previously the remaining tokens were used up in the debug process.

Zena
