### ISSUE TITLE
issue in deploying

### ISSUE THREAD

**Issue by mahdi-nadir** [stackblitz/bolt.new#1335]
### Describe the bug

the deployment crashes, not possible to see the result of the website

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6zscdc

### Steps to reproduce

not applicable

### Expected behavior

redirecting to another widnow in order to see the result

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67477961,
  "usedJSHeapSize": 62999533,
  "jsHeapSizeLimit": 4294705152
}
Username = nipton71
Chat ID = 806d1af2f892
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
