### ISSUE TITLE
Impossible to deploy the app

### ISSUE THREAD

**Issue by Lelahel08** [stackblitz/bolt.new#1338]
### Describe the bug

Impossible to deploy the app

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vrepur

### Steps to reproduce

Just trying to deploy

### Expected behavior

Deployment of the app

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 300489548,
  "usedJSHeapSize": 295272960,
  "jsHeapSizeLimit": 4294705152
}
Username = Lelahel
Chat ID = a7812c6b9893
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
