### ISSUE TITLE
prompt is too long: 206640 tokens > 200000 maximum

### ISSUE THREAD

**Issue by leadmetrik** [stackblitz/bolt.new#1339]
### Describe the bug

I am getting this error: prompt is too long: 206640 tokens > 200000 maximum

### Steps to reproduce

I entered any prompt

### Expected behavior

execute prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
