### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by Ariefrse** [stackblitz/bolt.new#134]
### Describe the bug

i have subcribe pro plan, but whenever i prompt it show forbidden

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/a94c57f6-4cb6-4fda-982b-893ef7133594">
<img width="1216" alt="Screenshot 2024-10-07 at 10 39 19 AM" src="https://github.com/user-attachments/assets/cff10e09-0a2c-4394-969e-772190b27cdc">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fvvthj

### Steps to reproduce

1. go to bolt.new
2. prompt anything
3. get forbidden error

### Expected behavior

1. after prompt, it should generate an answer based on what i have prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by SamVerschueren** [comment]
Closing this in favour of #77.

**Comment by labelhigh** [comment]
![Image](https://github.com/user-attachments/assets/1e8f411b-54c3-4ede-b1d4-27c239feba2f)
I'm so mad!!! Why does this error occur!!
