### ISSUE TITLE
prompt is too long: 205673 tokens > 200000 maximum

### ISSUE THREAD

**Issue by amarieivey** [stackblitz/bolt.new#1345]
### Describe the bug

When trying to add information, I get this:  prompt is too long: 205673 tokens > 200000 maximum. And then it is hard for the program to stop sending this alert even when I make the prompt much shorter. It uses a lot of tokens 

### Link to the Bolt URL that caused the error

my site

### Steps to reproduce

I will add in information, it gives the prompt, I will make it shorter and it keeps giving the prompt. 

### Expected behavior

for the changes to be made

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @amarieivey, 

We are aware of this issue. We have current workarounds you can try and will be tracking future developments here: #1322.
