### ISSUE TITLE
Code Stuck

### ISSUE THREAD

**Issue by abuhasnatruhu** [stackblitz/bolt.new#135]
### Describe the bug

If you some codes are done generate properly its can't be delete or rewrite. Fix the issue.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ghpog9

### Steps to reproduce

If you run any program and frizz some where then the file can't be deleted or rewrite. If rewrite then go back to the last version. Its hard to explain for me.

### Expected behavior

Can't delete or rewrite or save file.

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = abuhasnatruhu
Chat ID = 594c0c8eadc8
```

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report! 😃

I think we need more information to diagnose this issue correctly. Which files are you trying to change, and how are you trying to change them?

**Comment by kc0tlh** [comment]
Closing for now due to inactivity. Please feel free to re-open if additional info on a bug is reported!
