### ISSUE TITLE
prompt is too long: 202507 tokens > 200000 maximum

### ISSUE THREAD

**Issue by Cy-S3c** [stackblitz/bolt.new#1350]
### Describe the bug

from yesterday onwards am getting errors like "prompt is too long: 202507 tokens > 200000 maximum" even though how small is the prompt is 
![error](https://github.com/user-attachments/assets/a8afd367-a926-4086-ba07-cd06d414fc1c)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ktfftw

### Steps to reproduce

got any chat type something if you are lucky you will successfully get an error

### Expected behavior

it should provide the reposes instead of prompt is too long: 202507 tokens > 200000 maximum

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e71871a5-fc8d-46a9-ba32-36e72aeae2f9)

### Platform

```
Browser name = Firefox
Full version = 128.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
performance.memory = undefined
Username = Cy-S3c
Chat ID = 2fa2224cf623
```

**Comment by yasinkocak** [comment]
https://github.com/stackblitz/bolt.new/issues/1322

**Comment by kc0tlh** [comment]
Thanks @yasinkocak! This is being tracked in #1322 and we are working hard on R&D to improve this!
