### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by abisong** [stackblitz/bolt.new#1354]
### Describe the bug

When I click on the deploy button then I get this message:
Let me help you deploy this React application to Netlify.

Deploy to Netlify

npm run build
netlify

The deployment is in progress. Let me check the status...

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mmjmef

### Steps to reproduce

When I click on the deploy button then I get this message:
Let me help you deploy this React application to Netlify.

Deploy to Netlify

npm run build
netlify

The deployment is in progress. Let me check the status...

An error occured while streaming this message.

### Expected behavior

Deploy the application to Netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 180804715,
  "usedJSHeapSize": 171694211,
  "jsHeapSizeLimit": 4294705152
}
Username = abisong
Chat ID = 9ca389ea20f7
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
