### ISSUE TITLE
Build always failing and the issue is never fixed

### ISSUE THREAD

**Issue by saridsa1** [stackblitz/bolt.new#1356]
### Describe the bug

npm run build always fails for my nextjs project

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hte1qv

### Steps to reproduce

try deploying the application

### Expected behavior

The build should complete successfully.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59904380,
  "usedJSHeapSize": 42322520,
  "jsHeapSizeLimit": 4294705152
}
Username = saridsa1
Chat ID = 169f791921a9
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it and potential workarounds here: #2019
