### ISSUE TITLE
Fails to Import Firebase Dependencies 

### ISSUE THREAD

**Issue by fabuka** [stackblitz/bolt.new#1361]
### Describe the bug

I have try to link the app to Firebase (Cloud Firestore) but the takes long to install the depencies and the system suddenly crashes.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-q7ykuz

### Steps to reproduce

1. I copy my config file from Fire Base and then use this in bolt.new but it is having problems installing the dependencies. 

### Expected behavior

I expected the dependencies to be easily installed

### Screen Recording / Screenshot

I have tried to link the app to Firebase (Cloud Firestore) but it takes too  and suddenly failed long to install the dependencies and the system suddenly crashed
<img width="635" alt="dependencies challenges" src="https://github.com/user-attachments/assets/49b35395-74cc-4ecb-b07f-49c7af896538">
<img width="598" alt="instal depencencies" src="https://github.com/user-attachments/assets/b8facab1-62b2-4133-90ad-6f36720ad39f">
.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 155538253,
  "usedJSHeapSize": 151006489,
  "jsHeapSizeLimit": 2160066560
}
Username = fabuka
Chat ID = c46322a2d646
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
