### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by amarieivey** [stackblitz/bolt.new#1362]
### Describe the bug

It almost doesn't even function now. I was considering buying new tokens, but this is very hard because im spending so much on trying to maintain previous data. When I am giving new prompts, barely any of them work- I will receive this: src/data/blogs.ts
This message didn't complete its response. then if I hit retry, I get this response: prompt is too long: 204838 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

I wrote it above

### Expected behavior

to provide the code and preview

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62133916,
  "usedJSHeapSize": 57784688,
  "jsHeapSizeLimit": 4294705152
}
Username = amarieivey
Chat ID = 88169efe0a43
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
