### ISSUE TITLE
blank pages oover and over

### ISSUE THREAD

**Issue by tdadelaja** [stackblitz/bolt.new#1363]
### Describe the bug

Not able to create sign-in authentication

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jsit27

### Steps to reproduce

not working

### Expected behavior

create sign-in authentication

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 148207956,
  "usedJSHeapSize": 140157156,
  "jsHeapSizeLimit": 4294705152
}
Username = tdadelaja
Chat ID = f3e1e3fe0218
```

**Comment by endocytosis** [comment]
Hi @tdadelaja, 

Some advice on efficient use of tokens when prompting Bolt can be found here: #678. Effective prompt engineering is an area of active development. More information can be found [here](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview).
