### ISSUE TITLE
Stuck on `npm install`

### ISSUE THREAD

**Issue by jalakoo** [stackblitz/bolt.new#1365]
### Describe the bug

Created Next.js app never runs. During 3rd attempt to fix, the system stalled on `npm install` in both the Bolt and Terminal sub-tabs

![image](https://github.com/user-attachments/assets/3f80260c-9104-4d24-88d3-083410cf8dce)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-md92bw

### Steps to reproduce

1. Go to Terminal tab
2. Enter `npm install`

### Expected behavior

Expected dependencies to finish loading then to run `npm run dev` and see a running application.

### Platform

```
Browser name = Safari
Full version = 17.4.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15
performance.memory = undefined
Username = jalakoo
Chat ID = 4515a9d2f2e2
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
