### ISSUE TITLE
Chat History Missing

### ISSUE THREAD

**Issue by JamesHarley** [stackblitz/bolt.new#1367]
### Describe the bug

When I test across different devices I have no chat history.

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

Test from one device / browser to another

### Expected behavior

Chat history should be across devices/browsers

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@JamesHarley the workaround for this & upcoming solution is tracked in #39
