### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by farhaan-stack** [stackblitz/bolt.new#1368]
### Describe the bug

When using bolt, it creates all the folders very well but when the user is needed to upload an image it doesn't have any option for that in the code files section.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ii5rev

### Steps to reproduce

![image](https://github.com/user-attachments/assets/b0e24030-8305-48ac-b95c-3b2bc85aad75)

### Expected behavior

it should have an option to upload a file/image

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49145091,
  "usedJSHeapSize": 46900723,
  "jsHeapSizeLimit": 2160066560
}
Username = farhaan-stack
Chat ID = 4390c905d969
```

**Comment by endocytosis** [comment]
Hi @farhaan-stack, 

Appreciate the feedback. We are aware of this issue and are tracking it here: #1809.
