### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by bouboure** [stackblitz/bolt.new#137]
### Describe the bug

I am getting Forbidden 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sdseum

### Steps to reproduce

all prompt result to a forbidden error

### Expected behavior

create a website as asked

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/9851b22c-444b-4b8d-8f13-a9e2a9730395)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Wangxs404** [comment]
me too

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by SamVerschueren** [comment]
Closing this in favour of #77.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
