### ISSUE TITLE
lost chat list

### ISSUE THREAD

**Issue by nicko913** [stackblitz/bolt.new#1370]
### Describe the bug

lost past chat(s) and backups

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

signed in. shows all tokens used, but no record of a past chat. all backups are also gone. 

### Expected behavior

chat and backups were available all day yesterday post-login. had to log back in throughout the day so not a session thing.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@nicko913 the workaround for this & upcoming solution is tracked in #39
