### ISSUE TITLE
Deploy to Netlify  npx next build netlify Let me check the deployment status.  An error occured while streaming this message.

### ISSUE THREAD

**Issue by krisgnyc** [stackblitz/bolt.new#1371]
### Describe the bug

Deploy to Netlify

npx next build
netlify
Let me check the deployment status.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5yu82y

### Steps to reproduce

Deploy to Netlify

npx next build
netlify
Let me check the deployment status.

An error occured while streaming this message.

### Expected behavior

Deploy to Netlify

npx next build
netlify
Let me check the deployment status.

An error occured while streaming this message.

### Screen Recording / Screenshot

Deploy to Netlify

npx next build
netlify
Let me check the deployment status.

An error occured while streaming this message.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59752562,
  "usedJSHeapSize": 57007218,
  "jsHeapSizeLimit": 4294705152
}
Username = krisgnyc
Chat ID = 94e48fd83ac6
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
