### ISSUE TITLE
Deploy application to Netlify

### ISSUE THREAD

**Issue by HolmBIM** [stackblitz/bolt.new#1372]
### Describe the bug

I'll help you deploy the application to Netlify.

Deploy application to Netlify

npx next build
netlify
I'll wait for the deployment to complete and provide you with the live URL once it's ready.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-prydky

### Steps to reproduce

Deploy application to Netlify

### Expected behavior

Deploy application to Netlify

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/1e68671f-6f9b-49ad-a2df-07653fb24b04)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68697770,
  "usedJSHeapSize": 63525506,
  "jsHeapSizeLimit": 4294705152
}
Username = thomasbim
Chat ID = ae17a9bceb81
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
