### ISSUE TITLE
Blank preview 

### ISSUE THREAD

**Issue by ezhulati** [stackblitz/bolt.new#1374]
### Describe the bug

preview is blank 50% of the time or more. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-stzd6r

### Steps to reproduce

start application to see 

### Expected behavior

a rendered site

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 209576200,
  "usedJSHeapSize": 201812828,
  "jsHeapSizeLimit": 4294705152
}
Username = ezhulati
Chat ID = 4272bf515fc1
```

**Comment by endocytosis** [comment]
Hi @ezhulati, 

Appreciate the feedback. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
