### ISSUE TITLE
 black screen error

### ISSUE THREAD

**Issue by GGBueno** [stackblitz/bolt.new#1377]
### Describe the bug

when trying to create a task or correct the problem, errors occur and a black screen occurs, tokens are spent and the request is lost, as the bolt does not skip the history of user requests, which ends up generating a problem, as we have to ask again to implement or correct the same request again because BOLT does not save requests when these errors occur and we have to spend double tokens, this should be reimbursed to users!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-csa235

### Steps to reproduce

black screen error: when trying to create a task or correct the problem, errors occur and a black screen occurs, the tokens are spent and the request is lost, as bolt does not skip the history of user requests, which ends up generating a problem, as we have to ask again to implement or correct the same request again because BOLT doesn't save requests when these errors occur and we have to spend double tokens, this should be reimbursed to users!

### Expected behavior

black screen error: when trying to create a task or correct the problem, errors occur and a black screen occurs, the tokens are spent and the request is lost, as bolt does not skip the history of user requests, which ends up generating a problem, as we have to ask again to implement or correct the same request again because BOLT doesn't save requests when these errors occur and we have to spend double tokens, this should be reimbursed to users!

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/4e9549e7-171e-41ac-b5b1-5a78b95d2ce5)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

black screen error: when trying to create a task or correct the problem, errors occur and a black screen occurs, the tokens are spent and the request is lost, as bolt does not skip the history of user requests, which ends up generating a problem, as we have to ask again to implement or correct the same request again because BOLT doesn't save requests when these errors occur and we have to spend double tokens, this should be reimbursed to users!

**Comment by AriPerkkio** [comment]
Hey @GGBueno, thanks for the report!

This issue is tracked on #2556.
