### ISSUE TITLE
Tokens problem

### ISSUE THREAD

**Issue by Spartacusklaus45** [stackblitz/bolt.new#1381]
### Describe the bug

when I try to launch the prompt, this is my problem that appears
prompt is too long: 201180 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-grg7pf

### Steps to reproduce

prompt is too long: 201180 tokens > 200000 maximum

### Expected behavior

resolve this problem

### Platform

chrome

**Comment by endocytosis** [comment]
Hi @Spartacusklaus45, 

We are aware of this issue. We have current workarounds you can try and will be tracking future developments here: #1322.
