### ISSUE TITLE
Max tokens

### ISSUE THREAD

**Issue by derickcaps** [stackblitz/bolt.new#1386]
### Describe the bug

put a lot of time into a project and now I can't finish it as it just says maximum tokens is 200000 this is 200853 so it won't fix any errors or anything anymore 

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-wvjagx

### Steps to reproduce

just talk and it will respond back with an error 

### Expected behavior

to fix the errors or respond properly 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61369230,
  "usedJSHeapSize": 49379378,
  "jsHeapSizeLimit": 4294705152
}
Username = derickcaps
Chat ID = 953c2ebdfca2
```

### Additional context

I can't finish the app I put all this money and time into?

**Comment by kc0tlh** [comment]
@derickcaps this is being tracked in #1322
