### ISSUE TITLE
New to Bolt.

### ISSUE THREAD

**Issue by MrSuperSharpie** [stackblitz/bolt.new#1397]
I have signed up to a free account and am extremely happy with the Bolt.new platform.. to be honest it is amazing! 

While I am working on a project can it remain confidential until completed? 

Thanks,
Edgar

**Comment by fcptech** [comment]
I'm having an issue. I've created a project, by default private, then I switched the visibility to secret (accesible by URL), and a few days after switch it back to private. But everyone (who access in the past and who doesn't) can still access the project with the URL. 
Is this a known issue?
