### ISSUE TITLE
Unable to send messages to bolt.new

### ISSUE THREAD

**Issue by Titanium-ctrl** [stackblitz/bolt.new#1398]
### Describe the bug

When loading a previous bolt.new project, and preparing to make some tweaks, the project is first loaded in and setup (dependencies need to be installed etc.). This seems to happen successfully, as I can see my project's sign in page appear on the right.

However, when I try to send a prompt to bolt.new and hit enter, the prompt I've typed in disappears, and a message saying "
This message didn't complete its response." appears on the previous message (which is the one where bolt installs dependencies and starts the app).

In attempts to reload the page and see if it fixes anything, Bolt.new has somehow managed to take ~145k tokens in the process, so I think it is receiving my prompts, but isn't showing me what it's done. When I try to open the specific pages to see if it's done anything, I'm shown a white screen - so I can't tell what's happened.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vez9lh

### Steps to reproduce

1. Load bolt.new project
2. Wait for it to be fully set up
3. Provide a prompt
4. Observe error

### Expected behavior

The prompt should not disappear once I've hit sent - it should appear as a chat bubble and I should be able to see Bolt's response

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ac52d14a-7d5b-4ad6-92bb-c2d0a01ace0f)

https://github.com/user-attachments/assets/ed72d330-598e-4a7e-b422-56234005e665

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 58814690,
  "usedJSHeapSize": 54210914,
  "jsHeapSizeLimit": 2160066560
}
Username = Titanium-ctrl
Chat ID = 4119ac5f0551
```

**Comment by kc0tlh** [comment]
@Titanium-ctrl thanks for the report! Tracking this in #1073
