### ISSUE TITLE
No css assets loading on landing page

### ISSUE THREAD

**Issue by guilleF225** [stackblitz/bolt.new#14]
### Describe the bug

when navigating to https://bolt.new/ no asset is being loaded. I can see on the console that it is because of 'too many redirects'
On incognito it worked as expected. Tried disabling adblock but nothing changed.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

navigate to bolt.new

### Expected behavior

Styles being loaded

### Screenshots

<img width="1440" alt="Screen Shot 2024-10-03 at 17 45 57" src="https://github.com/user-attachments/assets/2dd81756-c46b-40c6-87b0-97ba7de2827f">
<img width="1434" alt="Screen Shot 2024-10-03 at 17 46 34" src="https://github.com/user-attachments/assets/8986306b-324e-425c-b2b3-1f9856a2b812">

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [latest]

**Comment by yilmazdurmaz** [comment]
``net::ERR_TOO_MANY_REDIRECTS``

I wonder if it is the site or your network! Do you have any VPS or similar settings between you and the internet? or maybe a temporary problem that you fell into while the site was being updated.

by the way, please fill in the OS and Browser details.

**Comment by guilleF225** [comment]
> `net::ERR_TOO_MANY_REDIRECTS`
> 
> I wonder if it is the site or your network! Do you have any VPS or similar settings between you and the internet? or maybe a temporary problem that you fell into while the site was being updated.
> 
> by the way, please fill in the OS and Browser details.

I had left the os and browser but did not look that it still said eg. I'm on macos and chrome.
Tried turning off zscaler but it didn't change anything, usually when I do have problems because of that it just doesn't let me into the website
It is still happening, as mentioned on incognito it loads as expected.

Will paste the assets that are failing

```
GET https://bolt.new/assets/ReactToastify-CYivYX3d.css net::ERR_TOO_MANY_REDIRECTS
bolt.new/:1 
       GET https://bolt.new/assets/root-DmUsxXQ9.css net::ERR_TOO_MANY_REDIRECTS
bolt.new/:1 
       GET https://bolt.new/assets/tailwind-compat-CC20SAMN.css net::ERR_TOO_MANY_REDIRECTS
bolt.new/:1 
       GET https://bolt.new/assets/index-CNBGx7uP.css net::ERR_TOO_MANY_REDIRECTS
bolt.new/:1 
       GET https://bolt.new/assets/xterm-lQO2bNqs.css net::ERR_TOO_MANY_REDIRECTS
bolt.new/
       GET https://bolt.new/assets/_index-DZ0tBKf4.css net::ERR_TOO_MANY_REDIRECTS
```

**Comment by yilmazdurmaz** [comment]
> I'm on macos and chrome. 

👍 

> as mentioned on incognito it loads as expected.

I missed that part. It then usually means some other extension interferes with the normal operation of the browser and the sites. 

Open extensions page (chrome://extensions) and try disabling them one by one and see if the page loads. Also If you can find the culprit that way, tell us here for reference.

**Comment by guilleF225** [comment]
Took out all of the extensions but that didn't work :\ it is most surely something on my end that I'm not finding.

I fixed it opening the assets that were failing in independent tabs.
When first opened it returned the same error, on reload they loaded. When I went back to the main page it loaded alright, I guess because it cached?

Not really sure what was happening, if I see anything else will comment

**Comment by samdenty** [comment]
This is an issue on our side - to workaround simply open devtools and check disable cache then reload then it should start loading. You can close devtools after that.

Our servers are responding with a permanent redirect that's getting persisted in the browsers disk network cache

**Comment by samdenty** [comment]
We've just shipped a fix, the issue was we didn't have Full strict enabled on cloudflare and so some bots were accessing the bolt.new urls over non-secure https, causing cloudflare to cache a permanent redirect to the same url. Hopefully this should be fixed now
