### ISSUE TITLE
Cross-Device Continuity

### ISSUE THREAD

**Issue by AppliedApplications** [stackblitz/bolt.new#140]
### Describe the bug

Previous chats / projects are not appearing on other device side menu's, only the device the conversation was started in.
Original device:
![thumbnail_image](https://github.com/user-attachments/assets/9d14afe2-464b-4b4d-8f5c-695621f38341)

New Device with project missing:
![image](https://github.com/user-attachments/assets/aa84aeb9-1dd2-423c-b654-0b41e2a39b2f)

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Login to my account from any other device 
2. Project not populating to list to select

### Expected behavior

Projects being accessible from any device with the same login credentials.

### Platform

Windows 10

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, it would be great to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by FMpoli** [comment]
Confirmed here
Macosx and linux

**Comment by samdenty** [comment]
Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #39!
