### ISSUE TITLE
Prompt too long Issue ongoing  x 250 , now ( at least )!

### ISSUE THREAD

**Issue by jaywakeford** [stackblitz/bolt.new#1401]
### Describe the bug

I was earlier some progress had been made.   However, after 3 successful prompt tasks the system is once again returning a Prompt too long error .     

 
example below :

"I do not see any changes in the Social Trading page

prompt is too long: 207374 tokens > 200000 maximum"   

I did roll back once and it worked well to rollback and start the next prompt actions.  But then a single line follow-up resulted in error above   

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wlgkaw

### Steps to reproduce

"I do not see any changes in the Social Trading page

prompt is too long: 207374 tokens > 200000 maximum "

### Expected behavior

I am expecting to be able to put a single line prompt or follow-up from a previous prompt without getting an error that is seemingly gaslighting the paying customers :

"I do not see any changes in the Social Trading page

prompt is too long: 207374 tokens > 200000 maximum"    

### Screen Recording / Screenshot

<img width="433" alt="Screenshot 2024-11-02 170433" src="https://github.com/user-attachments/assets/42a30b0f-25b6-4780-a24e-6f92ff05a6bf">
#

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76814871,
  "usedJSHeapSize": 73653623,
  "jsHeapSizeLimit": 4294705152
}
Username = jaywakeford
Chat ID = 34eb8564bc55
```

**Comment by Habartru** [comment]
hi. I get the same result and I can't work with my project for the second day. The support is silent! They don't care if you're a paid customer or not. They can make bolt.new, but prioritize customer support and the fastest possible interaction is not!

**Comment by behnod24** [comment]
Hello everyone,

This error isn’t related to the prompt size you input in Bolt; rather, it’s tied to the overall project size. As the project becomes more complex, this issue tends to appear. I hope the Bolt.new team will address this soon.

Thank you.

**Comment by kc0tlh** [comment]
This issue and the workarounds are being tracked in #1322
