### ISSUE TITLE
Existing frameworks changing to node.js 

### ISSUE THREAD

**Issue by wsxcvbnmlp** [stackblitz/bolt.new#1405]
it was making .exe files, window applications, but now it is changing everything to node.js? it was working phenomenal.

**Comment by endocytosis** [comment]
Hi @wsxcvbnmlp, 

While the AI language model model powering Bolt is able to generate code in multiple languages, Bolt itself relies on [WebContainers](https://webcontainers.io/) to provide full-stack web application development, and as such does not support non-web languages.
