### ISSUE TITLE
Unable to import Wasp

### ISSUE THREAD

**Issue by louisdhon** [stackblitz/bolt.new#1407]
### Describe the bug

wasp-lang/wasp
Cannot destructure property 'appFiles' of 'project' as it is null.
An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/wasp-lang/wasp

### Steps to reproduce

Go to https://bolt.new/~/github.com/wasp-lang/wasp
Receive import error

### Expected behavior

Imported Wasp Project

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 310042175,
  "usedJSHeapSize": 281432831,
  "jsHeapSizeLimit": 4294705152
}
Username = louisdhon
Chat ID = fe1e0b39bce0
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1812.

**Comment by louisdhon** [comment]
Thank you! Also, is it possible build a PHP app with this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
