### ISSUE TITLE
Unable to Preview Code or Deploy

### ISSUE THREAD

**Issue by PoopHacker** [stackblitz/bolt.new#141]
### Describe the bug

Seems that I lost the ability to preview the code as well as deploy it sadly. Otherwise a really great app that will certainly help me and others when it comes to building a full-fledged website. Would love to see this minor issue fixed. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-86ybwe

### Steps to reproduce

Image attached of error. 

### Expected behavior

I just want to be able to preview the code and changes made as well as deploy them to Netify. 

### Screen Recording / Screenshot

<img width="1710" alt="Screenshot 2024-10-07 at 10 22 19 AM" src="https://github.com/user-attachments/assets/8f6b6c80-bf7d-4f0a-8691-dea9c989b996">

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72993168,
  "usedJSHeapSize": 68825628,
  "jsHeapSizeLimit": 2172649472
}
Username = PoopHacker
Chat ID = 7df080660451
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report! 😃

We're tracking this issue internally and will let you know when we have a fix in place.

**Comment by PoopHacker** [comment]
No problem, my pleasure. Great product!

Kind regards,
JB

**Comment by samdenty** [comment]
i've just opened a pr to add auto-fixes for build errors encountered inside deployment build commands

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/46

**Comment by PoopHacker** [comment]
Thanks Sam!

Kind regards,
JB
