### ISSUE TITLE
Enhanced Token Usage Tracking in Subscription Tab for Bolt.new

### ISSUE THREAD

**Issue by Riakon1** [stackblitz/bolt.new#142]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, this would be a really nice feature! We're tracking this internally. We'll keep you posted ✨

**Comment by samdenty** [comment]
we've shipped this in the settings tab! 🎊

**Comment by Riakon1** [comment]
🔥🔥🔥🔥🔥🔥
