### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by yasboyman** [stackblitz/bolt.new#143]
### Describe the bug

Your site seems to be broken I suspect its perhaps asset issue or redirect issue as logs show 'too many redirects'

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Go to site, you will see the page layout is broken along with console erros
<img width="1153" alt="Screenshot 2024-10-07 at 10 27 51" src="https://github.com/user-attachments/assets/b48c4766-8aad-4041-91e9-3f6e776dc407">

### Expected behavior

Homepage should be rendering correctly

### Screen Recording / Screenshot

<img width="1153" alt="Screenshot 2024-10-07 at 10 27 51" src="https://github.com/user-attachments/assets/8
<img width="420" alt="Screenshot 2024-10-07 at 10 30 41" src="https://github.com/user-attachments/assets/10a34efe-9fa1-4cb1-9fe0-1c180e08ce82">
6b8de2c-691b-4366-ba47-54f2eefd29ce">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report! 😃

We're tracking this issue internally and will let you know when we have a fix in place.

**Comment by itsrn** [comment]
The site looks broken for me too. I'm using Firefox.

**Comment by samdenty** [comment]
we've fixed this issue
