### ISSUE TITLE
error want money bacj 

### ISSUE THREAD

**Issue by serko-ko** [stackblitz/bolt.new#1434]
### Describe the bug

https://disk.yandex.com/i/5LC388tIh8NKLA

### Link to the Bolt URL that caused the error

https://disk.yandex.com/i/5LC388tIh8NKLA

### Steps to reproduce

https://disk.yandex.com/i/5LC388tIh8NKLA

### Expected behavior

https://disk.yandex.com/i/5LC388tIh8NKLA

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Refund requests are handled through hello@stackblitz.com.
