### ISSUE TITLE
code in chat

### ISSUE THREAD

**Issue by fede-barba** [stackblitz/bolt.new#144]
### Describe the bug

code into the chat 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-p6x4s1

### Steps to reproduce

in this part of chat : Certainly! I'll improve the app focusing on the key areas you've mentioned. Let's start by enhancing the core functionalities and improving the overall structure of the application.

Improved Simplify App

 V update app/page.tsx
 V create hooks/useLocalStorage.ts
 V update components/Dashboard.tsx
 V update components/Folders.tsx
 V update components/Notes.tsx
 V update components/MindMaps.tsx
 X update components/MemoryPalaces.tsx

MemoryPoint {
id: string;
content: string;
position: { x: number; y: number };
}

// Define the structure of a memory palace
interface MemoryPalace {
id: string;
name: string;
points: MemoryPoint[];
}

const MemoryPalaces: React.FC = () => {
// Use local storage to persist memory palaces
const [palaces, setPalaces] = useLocalStorage<MemoryPalace[]>('memoryPalaces', []);
const [newPalaceName, setNewPalaceName] = useState('');
const [selectedPalace, setSelectedPalace] = useState<MemoryPalace | null>(null);
const [newPointContent, setNewPointContent] = useState('');
const [draggedPoint, setDraggedPoint] = useState<MemoryPoint | null>(null);
const palaceRef = useRef(null);

// Function to add a new memory palace
const addPalace = () => {
if (newPalaceName) {
const newPalace: MemoryPalace = {
id: Date.now().toString(),
name: newPalaceName,
points: [],
};
setPalaces([...palaces, newPalace]);
setNewPalaceName('');
}
};

// Function to add a new memory point
const addPoint = (event: React.MouseEvent) => {
if (selectedPalace && newPointContent && palaceRef.current) {
const rect = palaceRef.current.getBoundingClientRect();
const x = event.clientX - rect.left;
const y = event.clientY - rect.top;
const newPoint: MemoryPoint = {
id: Date.now().toString(),
content: newPointContent,
position: { x, y },
};
const updatedPalace = {
...selectedPalace,
points: [...selectedPalace.points, newPoint],
};
setPalaces(palaces.map(p => p.id === selectedPalace.id ? updatedPalace : p));
setSelectedPalace(updatedPalace);
setNewPointContent('');
}
};

// Functions for drag and drop functionality
const handleDragStart = (event: React.DragEvent, point: MemoryPoint) => {
setDraggedPoint(point);
};

const handleDragOver = (event: React.DragEvent) => {
event.preventDefault();
};

const handleDrop = (event: React.DragEvent) => {
event.preventDefault();
if (draggedPoint && selectedPalace && palaceRef.current) {
const rect = palaceRef.current.getBoundingClientRect();
const x = event.clientX - rect.left;
const y = event.clientY - rect.top;
const updatedPoints = selectedPalace.points.map(p =>
p.id === draggedPoint.id ? { ...p, position: { x, y } } : p
);
const updatedPalace = { ...selectedPalace, points: updatedPoints };
setPalaces(palaces.map(p => p.id === selectedPalace.id ? updatedPalace : p));
setSelectedPalace(updatedPalace);
setDraggedPoint(null);
}
};

// Function to delete a memory point
const deletePoint = (pointId: string) => {
if (selectedPalace) {
const updatedPoints = selectedPalace.points.filter(p => p.id !== pointId);
const updatedPalace = { ...selectedPalace, points: updatedPoints };
setPalaces(palaces.map(p => p.id === selectedPalace.id ? updatedPalace : p));
setSelectedPalace(updatedPalace);
}
};

return (

Memory Palaces
<Input placeholder="Memory palace name" value={newPalaceName} onChange={(e) => setNewPalaceName(e.target.value)} className="mb-2" /> Create Memory Palace
{palaces.map(palace => ( <Card key={palace.id} onClick={() => setSelectedPalace(palace)} className="cursor-pointer"> {palace.name}
{palace.points.length} memory points

))}
{selectedPalace && (
{selectedPalace.name}
<Input placeholder="Memory point content" value={newPointContent} onChange={(e) => setNewPointContent(e.target.value)} className="mb-2" />
{selectedPalace.points.map(point => ( <div key={point.id} className="absolute w-4 h-4 bg-blue-500 rounded-full cursor-move" style={{ left: ${point.position.x}px, top: ${point.position.y}px }} draggable onDragStart={(e) => handleDragStart(e, point)} onClick={(e) => e.stopPropagation()} >
Memory Point
{point.content}

<Button onClick={() => deletePoint(point.id)}>Delete Point
))}
)} ); };
export default MemoryPalaces;

import type { Metadata } from 'next' import { Inter } from 'next/font/google' import './globals.css'  .  I stopped it here. 

### Expected behavior

no code in the chat but in the right side of the screen when he create code. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 99454915,
  "usedJSHeapSize": 82064431,
  "jsHeapSizeLimit": 4294705152
}
Username = fede-barba
Chat ID = 3d5d2a1ad9d1
```

**Comment by kirjavascript** [comment]
Hey! Thanks for creating this issue!

We're tracking this internally. You can follow https://github.com/stackblitz/bolt.new/issues/26 to be notified of progress on this issue.
