### ISSUE TITLE
An unknown error occured while running an action.

### ISSUE THREAD

**Issue by PvPcococo** [stackblitz/bolt.new#1441]
### Describe the bug

An unknown error occured while running an action. they want to deploy my app

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hysf81

### Steps to reproduce

Étapes pour reproduire le comportement :

Accéder à l'interface de Bolt.new : Ouvrir un navigateur et se rendre sur le site de Bolt.new.

Connexion : Se connecter à mon compte utilisateur avec des identifiants valides.

Sélectionner le projet : Accéder à la section "Mes Projets" ou "Déploiement" dans le tableau de bord.

Initier le déploiement : Cliquer sur le bouton pour déployer le site (par exemple, "Déployer" ou "Publier").

Observer le message d'erreur : Attendre que le processus de déploiement commence et prendre note du message d'erreur qui s'affiche : "An unknown error occurred while running an action."

Vérifier les détails : Si disponible, vérifier la console du navigateur pour tout message d'erreur supplémentaire ou information contextuelle.

### Expected behavior

Comportement attendu :

Je m'attendais à ce que l'action que j'ai tentée d'exécuter sur le site se déroule sans erreur, permettant ainsi de [décrivez l'action précise, par exemple : "publier le contenu", "déployer le site", "enregistrer les modifications", etc.]. Le système devrait [indiquer ce que le système devrait faire, par exemple : "afficher un message de confirmation", "rediriger vers la page d'accueil", "enregistrer les données avec succès", etc.].

Au lieu de cela, j'ai reçu un message d'erreur indiquant "Une erreur inconnue est survenue lors de l'exécution d'une action", ce qui empêche la progression et nécessite une résolution pour que l'action puisse être exécutée correctement.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 101420901,
  "usedJSHeapSize": 84758137,
  "jsHeapSizeLimit": 2160066560
}
Username = PvPcococo
Chat ID = a8a23982e820
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Hi @PvPcococo, 

Appreciate the feedback! The team is aware of this issue and tracking it here: #499.
