### ISSUE TITLE
Stuck loading

### ISSUE THREAD

**Issue by EatRiteAi** [stackblitz/bolt.new#1444]
### Describe the bug

I had to reload  page after the ai builder getting stuck.  Now the app won't load

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-c2k46f

### Steps to reproduce

go to open the app

### Expected behavior

stuck installing dependencies 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111110477,
  "usedJSHeapSize": 105634905,
  "jsHeapSizeLimit": 4294705152
}
Username = EatRiteAi
Chat ID = 355517b5b9fe
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
