### ISSUE TITLE
Won't deploy to Netlify

### ISSUE THREAD

**Issue by adamhyde57** [stackblitz/bolt.new#1445]
### Describe the bug

From Bolt when I try to deploy to netlify it doen't work.  There is an error.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vue-tuticp

### Steps to reproduce

deploy and it fails.

### Expected behavior

show on netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73324943,
  "usedJSHeapSize": 64053575,
  "jsHeapSizeLimit": 4294705152
}
Username = adamhyde57
Chat ID = 70a509276595
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
