### ISSUE TITLE
prompt is too long issue

### ISSUE THREAD

**Issue by SymonBee** [stackblitz/bolt.new#1447]
### Describe the bug

I can't continue to develop my app, I have this message "prompt is too long: 200849 tokens > 200000 maximum"
Can it possible to override dans continue to develop? 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-y2deiz

### Steps to reproduce

I think when the game is finished

### Expected behavior

Continue to prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @SymonBee, 

We are aware of this issue. We have current workarounds you can try and will be tracking future developments here: #1322.
