### ISSUE TITLE
All my chats were cleared

### ISSUE THREAD

**Issue by kevinnkansah** [stackblitz/bolt.new#145]
### Describe the bug

I came back the next day, and my chat history was gone

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

no steps, my chats just got wiped for no reason

### Expected behavior

my chat history should only be deleted when I delete it myself

### Platform

- Windows
- Edge
- Version 129.0.2792.79 (Official build) (64-bit)

**Comment by mauriciorubio2** [comment]
OMG, I have the same issue: https://github.com/stackblitz/bolt.new/issues/160
Which I consider a major issue and problem with Bolt right now. They shouldn't be working on anything else until they fix this, it's basically a showstopper.

**Comment by kirjavascript** [comment]
Hey, thanks for reporting this issue!

We're already tracking this issue in https://github.com/stackblitz/bolt.new/issues/39 so I'm going to close this issue. Feel free to subscribe to those to track our progress on this!

**Comment by kevinnkansah** [comment]
Okay and the history comes back after my credits refresh, but they go when its finished
