### ISSUE TITLE
White pages blank

### ISSUE THREAD

**Issue by smartusercoder** [stackblitz/bolt.new#1459]
### Describe the bug

Why am i getting white bblank pages when I try to preview or errors when I try to deploy the app

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7cuhpi

### Steps to reproduce

Go to deploy or preview

### Expected behavior

Error with deployment or blank white preview screen

### Platform

Macos

**Comment by endocytosis** [comment]
Hi @smartusercoder, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
