### ISSUE TITLE
I'm encountering a "Forbidden" error while using bolt.new.

### ISSUE THREAD

**Issue by wilber1980** [stackblitz/bolt.new#146]
![Uploading 截屏2024-10-07 17.52.36.png…]()
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by yilmazdurmaz** [comment]
the pic you attached is broken. try attaching it along with filling written details, please.

**Comment by kirjavascript** [comment]
Hey! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
