### ISSUE TITLE
 prompt is too long: 200034 tokens > 200000 maximum

### ISSUE THREAD

**Issue by nder228** [stackblitz/bolt.new#1465]
### Describe the bug

prompt is too long: 200034 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wwzgzs

### Steps to reproduce

prompt is too long: 200034 tokens > 200000 maximum

### Expected behavior

prompt is too long: 200034 tokens > 200000 maximum  

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49534484,
  "usedJSHeapSize": 45708656,
  "jsHeapSizeLimit": 4294705152
}
Username = nd123
Chat ID = 613f9392c8e8
```

**Comment by nder228** [comment]
@kc0tlh  j'ai vue que vous êtes entrain de trouver une solution avez-vous une mise a jour ?

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
