### ISSUE TITLE
npm error every time i log into my account

### ISSUE THREAD

**Issue by mrbasson** [stackblitz/bolt.new#1469]
### Describe the bug

npm error every time i log into my account it starts the install npm command but then it fails and i cannot see the preview of my application. this happens every and I don't get a chance to deploy what i have build.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4yhfiy

### Steps to reproduce

i would like to log in and not have to get npm install errors every time. 

### Expected behavior

i would like to log in and not have to get npm install errors every time. 

### Screen Recording / Screenshot

![bolt-new-sb1-4yhfiy](https://github.com/user-attachments/assets/e050644c-d48d-4c8a-8bce-a22de5215605)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
