### ISSUE TITLE
Import Error: Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by naokihash** [stackblitz/bolt.new#1471]
### Describe the bug

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-hykfmz
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

![スクリーンショット 2024-11-04 20 03 35](https://github.com/user-attachments/assets/dc134059-4db5-48c5-9539-025e97e992e0)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hykfmz

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 36754314,
  "usedJSHeapSize": 35457030,
  "jsHeapSizeLimit": 4294705152
}
Username = naokihash
Chat ID = 2c514e50d96c
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
**Here is how to restore your project:**

1. Manually re-import your project from StackBlitz as described in #39
2. Re-open the project in Bolt using the button in the upper left corner of the StackBlitz editor.
3. If this is not the right version of your app, and go to Settings > Backups to find a more current version of your app.

_Thanks for the report and apologies for the frustrating experience!_
