### ISSUE TITLE
can not deploy in netlify... 

### ISSUE THREAD

**Issue by bjules19** [stackblitz/bolt.new#1472]
### Describe the bug

when i deploy the app it says :"
An unknown error occurred when deploying your project."

![image](https://github.com/user-attachments/assets/da43a530-5bdd-45f0-a1a2-0c9236561a75)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jzqhu1

### Steps to reproduce

just click on deploy button

### Expected behavior

i wish to have an url to deploy my app ... 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/cca8b529-671a-45dc-8e45-6f28b8bcb0b4)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 58584780,
  "usedJSHeapSize": 47917632,
  "jsHeapSizeLimit": 4294705152
}
Username = Jules Boisseau
Chat ID = 9a1214c9d3d5
```

### Additional context

Error:
```
An unknown error occurred when deploying your project.
```

**Comment by kc0tlh** [comment]
@bjules19 this is being tracked in #1499. Please follow there for updates!
