### ISSUE TITLE
Importing Stackblitz Project

### ISSUE THREAD

**Issue by MellensR** [stackblitz/bolt.new#1476]
### Describe the bug

sb1-vrppuf
Unexpected token 'U', "Unexpected"... is not valid JSON

Project is not returned on refresh

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vrppuf

### Steps to reproduce

Go to project 
Error returned

### Expected behavior

Project should be returned 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80909887,
  "usedJSHeapSize": 73390983,
  "jsHeapSizeLimit": 1098907648
}
Username = MellensR
Chat ID = fca0a83f0e78
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@MellensR Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
