### ISSUE TITLE
Json issue

### ISSUE THREAD

**Issue by xinetex** [stackblitz/bolt.new#1478]
### Describe the bug

Project wont start

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ugvjxf

### Steps to reproduce

Just try and open the project.

### Expected behavior

app wont start

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88195153,
  "usedJSHeapSize": 72010293,
  "jsHeapSizeLimit": 4294705152
}
Username = xinetex
Chat ID = 000090c63eec
```

### Additional context

sb1-ugvjxf
Unexpected token 'U', "Unexpected"... is not valid JSON

**Comment by kc0tlh** [comment]
@xinetex Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
