### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by SergeyMaa** [stackblitz/bolt.new#1481]
### Describe the bug

Hi!

I see this error "An error occured while streaming this message." when press "Deploy".

This project: https://bolt.new/~/sb1-b5ooec

<img width="586" alt="image" src="https://github.com/user-attachments/assets/f7181628-7dc2-47a9-a928-f41b2eeac290">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-b5ooec

### Steps to reproduce

1. Click "Deploy"
2. I see this error "An error occured while streaming this message."

### Expected behavior

it should Deploy and load https://netlify.app/

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57521036,
  "usedJSHeapSize": 54970904,
  "jsHeapSizeLimit": 2160066560
}
Username = SergeyMaa
Chat ID = 526264b6bd31
```

**Comment by kc0tlh** [comment]
@SergeyMaa this is being tracked in #1022. Please follow there for updates!
