### ISSUE TITLE
Token reload didn't work

### ISSUE THREAD

**Issue by justfinleygold** [stackblitz/bolt.new#1484]
### Describe the bug

I ran out of tokens and performed a token reload. I see the invoice and receipt in my StackBlitz page, but bolt.new doesn't acknowledge the purpose.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2ztvyr

### Steps to reproduce

You have hit the rate limit. You can continue to code for free in the editor.

### Expected behavior

It should show 10M tokens available

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45453062,
  "usedJSHeapSize": 41878886,
  "jsHeapSizeLimit": 4294705152
}
Username = justfinleygold
Chat ID = 688210a3647c
```

**Comment by endocytosis** [comment]
Hi @justfinleygold, 

Sorry to hear that you are having an issue with token reloading. Could you please reach out to hello@stackblitz.com with your account and invoice information so we can look into this further? Thanks.
