### ISSUE TITLE
Deploy Error: Something went wrong while creating your site on Netlify

### ISSUE THREAD

**Issue by alexandru-dumitru-dev** [stackblitz/bolt.new#1485]
### Describe the bug

Cannot deploy to Netlify and receive the error: **Something went wrong while creating your site on Netlify.**

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bzcqga

### Steps to reproduce

Click on deploy button.

### Expected behavior

Should deploy to Netlify.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c4be6285-67fe-4aa1-ab2e-4258e8ce8ad5)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50743514,
  "usedJSHeapSize": 46954662,
  "jsHeapSizeLimit": 1098907648
}
Username = alexandru-dumitru-dev
Chat ID = 2c94b1238d94
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@alexandru-dumitru-dev thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Thanks everyone for the reports! It seems like something is up with our Netlify endpoint right now. **I have escalated to engineering** and updates will come in this issue.

**Comment by Alm0stEthical** [comment]
> Thanks everyone for the reports! It seems like something is up with our Netlify endpoint right now. **I have escalated to engineering** and updates will come in this issue.

Poor man haha, these issues thing has been exploding!! And any update yet?

**Comment by kc0tlh** [comment]
**📣Update: This is now RESOLVED**
Thanks for the timely reports! We identified the core issue and fixed it. Happy coding!
