### ISSUE TITLE
cant preview, npm and dependencies install fail

### ISSUE THREAD

**Issue by Cobra-Fx** [stackblitz/bolt.new#1487]
### Describe the bug

the code is there but npm install is empty and preview page too

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jjvpel

### Steps to reproduce

click on preview , it will show nothing, but chat says it should

### Expected behavior

it should have shown the dashboard i was creating

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 43960838,
  "usedJSHeapSize": 42033314,
  "jsHeapSizeLimit": 2172649472
}
Username = Cobra-Fx
Chat ID = 4a1c0bb829a6
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
