### ISSUE TITLE
Unable to Build app and Deploy to netlify

### ISSUE THREAD

**Issue by Narmik88** [stackblitz/bolt.new#1490]
### Describe the bug

When I deploy the app in netlify, it gives the following error.
Something went wrong while creating your site on Netlify.
Bolt is unable to build the application and deploy it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ux4dqj

### Steps to reproduce

Click on Deploy button. You'll reproduce the error.

### Expected behavior

Bolt should be able to build the app and deploy it in netlify

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e8007ae3-24d9-44d1-b11f-6ea930c467e1)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92331818,
  "usedJSHeapSize": 86747166,
  "jsHeapSizeLimit": 4294705152
}
Username = Narmik88
Chat ID = cab3d018c7ae
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@Narmik88 thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
