### ISSUE TITLE
Something went wrong while creating your site on Netlify.

### ISSUE THREAD

**Issue by kish4pm** [stackblitz/bolt.new#1492]
### Describe the bug

Application deployment to LIVE is not happening within your platform. Please fix this bug ASAP though I ran out my credits tried regorously multiple times but no use. Please help here

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ndrlap

### Steps to reproduce

1. application preview done. 2. upon clicking deploy it is not responsive

### Expected behavior

complete deployment

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53559878,
  "usedJSHeapSize": 48871498,
  "jsHeapSizeLimit": 2160066560
}
Username = kish4pm
Chat ID = 2a7ff0eb7e91
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!

**Comment by kish4pm** [comment]
deployment is not working, but my tokens are kept burning for no reason. Please fix the issue asap and refund my tokens too. thanks in adv. 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/b4b4fe50-75c7-43c5-98e2-040176ebdb51">
<img width="956" alt="app1" src="https://github.com/user-attachments/assets/845dd7c4-d14f-490d-833c-8fba43b842e2">
