### ISSUE TITLE
Something went wrong while creating your site on Netlify.

### ISSUE THREAD

**Issue by salmanbareesh039** [stackblitz/bolt.new#1493]
### Describe the bug

When I try to deploy the script it throws me an error in deploying.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tntcmb

### Steps to reproduce

![Screenshot 2024-11-04 222539](https://github.com/user-attachments/assets/d54ac7de-d28c-477f-81d7-8f785e0d9b14)

### Expected behavior

When I try to deploy the script it throws me an error in deploying.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 134315954,
  "usedJSHeapSize": 129731398,
  "jsHeapSizeLimit": 4294705152
}
Username = salmanbareesh039
Chat ID = 29e6a4bba14c
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@salmanbareesh039 thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!

**Comment by salmanbareesh039** [comment]
Now getting another error

An unknown error occured while running an action.


![Screenshot 2024-11-05 095734](https://github.com/user-attachments/assets/9c07f829-a8f6-46a9-b367-8ee6f1a4a456)
