### ISSUE TITLE
App deployment fails

### ISSUE THREAD

**Issue by biliz** [stackblitz/bolt.new#1494]
### Describe the bug

When I click the "Deploy" button, I get a message that says "Something went wrong while creating your site on Netlify.".  I've closed the browser and reloaded the app to try the deployment again, but it still fails.  Iv'e only been able to successfully deploy one of three test apps.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2trggu

### Steps to reproduce

1. Click on "Deploy"
2. Deployment fails

### Expected behavior

Site is successfully deployed to Netlify.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85099363,
  "usedJSHeapSize": 81399807,
  "jsHeapSizeLimit": 4294705152
}
Username = biliz
Chat ID = efa187766cb0
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@biliz thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
