### ISSUE TITLE
Issue when trying to deploy to Netlify. Getting the message " Something went wrong while creating your site on Netlify."

### ISSUE THREAD

**Issue by Fastenup** [stackblitz/bolt.new#1495]
### Describe the bug

Getting the message " Something went wrong while creating your site on Netlify."

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gtykkm

### Steps to reproduce

1. Click Deploy

### Expected behavior

Getting the message " Something went wrong while creating your site on Netlify."

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/0f4eeeee-80d6-411f-8452-ec130303ce8f

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112074091,
  "usedJSHeapSize": 102174935,
  "jsHeapSizeLimit": 2160066560
}
Username = Fastenup
Chat ID = 39c26e3139fa
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@Fastenup thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
