### ISSUE TITLE
Refund tokens when netlify deploy fails

### ISSUE THREAD

**Issue by meretrix** [stackblitz/bolt.new#1497]
### Describe the bug

title. I don't think its fair to continue burning tokens trying to deploy to Netlify when the dpeloy doesn't work because they are rate limiting bolt or whatever else is happening

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zdib6k

### Steps to reproduce

Click deploy or tell deploy

### Expected behavior

Site deploys - URL is updated

### Screen Recording / Screenshot

<img width="544" alt="image" src="https://github.com/user-attachments/assets/14f86d53-e53e-44f2-85c9-c7fcb5a70f7d">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88088643,
  "usedJSHeapSize": 83600651,
  "jsHeapSizeLimit": 4294705152
}
Username = meretrix
Chat ID = c8ca26da07b1
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@meretrix thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

Refund/credits are handled via hello@stackblitz.com

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
