### ISSUE TITLE
can not deploy

### ISSUE THREAD

**Issue by oak8513** [stackblitz/bolt.new#1499]
### Describe the bug

Something went wrong while creating your site on Netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uold8b

### Steps to reproduce

deploy application, then you get Something went wrong while creating your site on Netlify.

### Expected behavior

Something went wrong while creating your site on Netlify.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55780507,
  "usedJSHeapSize": 52304523,
  "jsHeapSizeLimit": 4294705152
}
Username = help@yorkcomputer.net
Chat ID = 7f1e30692e8d
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@oak8513 thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
