### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by LeonlogicStudio** [stackblitz/bolt.new#15]
### Describe the bug

When I click on the preview it is blank. I have tried different browsers.

![image](https://github.com/user-attachments/assets/02d73c9a-7c25-4c89-9026-6f3cf1b06aa6)

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-shadcn-gtnnvm

### Steps to reproduce

Clicking on preview

### Expected behavior

I should see the preview

### Platform

```
Browser name = Safari
Full version = 18.0
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
performance.memory = undefined
Username = LeonlogicStudio
Chat ID = 0f934a3c990d
```

### Additional context

Message:
```
I've successfully imported your project. I'm ready to assist you with analyzing and improving your code.
      <div class="__boltArtifact__" data-artifact-id="2:bolt-dev-server" data-running-actions="true"></div>
```

**Comment by yilmazdurmaz** [comment]
Check all the generated files by the AI, they might be empty. I had such an issue that clears the content of generated files other than the last one opened, and you may need open them and undo by Ctrl+Z (or Cmd+Z). 

If this does not work, it means this is not the same as my issue, then check the developer console and try to give an error log.

**Comment by samdenty** [comment]
This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back

**Comment by LeonlogicStudio** [comment]
Works now!

**Comment by LeonlogicStudio** [comment]
@samdenty https://bolt.new/~/sb1-jlbws2 the preview is not working. Is it a browser issue I am using Safari

**Comment by yilmazdurmaz** [comment]
@LeonlogicStudio  that project loaded on my browser, but after a little waiting. I guess files had never been fetched to your browser before, and your network might be slow at the moment. give it some time. open developer tools and watch network if browser is active for the page.
