### ISSUE TITLE
Not Allowing Deployment to Netify

### ISSUE THREAD

**Issue by cmhenry23** [stackblitz/bolt.new#1500]
### Describe the bug

When I try to deploy to Netify, it fails each time - no reason why is provided.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-escpcd

### Steps to reproduce

Click 'Deploy' butoon

### Expected behavior

It gets deployed

### Platform

Browser is Firefox

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@cmhenry23 thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
