### ISSUE TITLE
It is not letting me deploy, it is giving an error every time

### ISSUE THREAD

**Issue by SanPlayground** [stackblitz/bolt.new#1501]
### Describe the bug

I am not sure what is giving the error, this is what it is shown in the prompt area:

![image](https://github.com/user-attachments/assets/d61c562e-9d0b-4541-80a4-394cc5f0ac11)

The development server is running, and you can now test the new features in the Alerts tab.

Rollback to Checkpoint
Deploy this application.

I'll help you deploy the application to Netlify.

Deploy to Netlify

netlify
The application is being deployed to Netlify. Let me check the deployment status.

Something went wrong while creating your site on Netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fdawdj

### Steps to reproduce

![image](https://github.com/user-attachments/assets/bf58509b-3672-4399-bf9a-2e9a486f041f)

### Expected behavior

I expected it to deploy, allow me to claim and view 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/844ce5a6-a238-4999-8210-26558c7d187f)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50335817,
  "usedJSHeapSize": 46617305,
  "jsHeapSizeLimit": 4294705152
}
Username = SantiagoH
Chat ID = a2ec0ead3f3f
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@SanPlayground thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1483

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
