### ISSUE TITLE
CAN'T FIND MY PROJECT

### ISSUE THREAD

**Issue by Dullaaahh** [stackblitz/bolt.new#1503]
### Describe the bug

I can't find my project named point of sale after working on it for a long time. Please recover this project ASAP

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

I have no idea where it dissapeared to

### Expected behavior

When I logged back in it had just disappeared

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Juni-crypto** [comment]
Hey Just try to find them under Collections of Stackblitz.com

**Comment by endocytosis** [comment]
Yes, @Juni-crypto is correct. @Dullaaahh, you should be able to find your project by navigating to stackblitz.com, logging in (same login as bolt.new), clicking "Collections" on the left-hand side of the page, and then opening "Bolt Collection".

With regards to chat persistence, the team is aware of this issue which is being tracked here: #39.
