### ISSUE TITLE
Cannot deploy the application

### ISSUE THREAD

**Issue by netmsglog** [stackblitz/bolt.new#1504]
### Describe the bug

After I input the prompt: "Deploy this application."
The answer shows:

I'll help you deploy the application to Netlify.

Deploy to Netlify

netlify
Let me check the deployment status to provide you with the live URL.

Something went wrong while creating your site on Netlify.

No detailed error information, and don't know what happens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-le8izp

### Steps to reproduce

Just click "deploy" button

### Expected behavior

The application should be deployed, and I will get a URL to access it.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 68774255,
  "usedJSHeapSize": 64870051,
  "jsHeapSizeLimit": 4294705152
}
Username = netmsglog
Chat ID = b75c708c2a2a
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@netmsglog thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1485, so please subscribe there!

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
