### ISSUE TITLE
Something went wrong while creating your site on Netlify.

### ISSUE THREAD

**Issue by JennBot22** [stackblitz/bolt.new#1505]
### Describe the bug

Trying to deploy my app to Netlify, and an error occurred with no description

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-czwvzs

### Steps to reproduce

Deploy 

### Expected behavior

Deploy

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 139268410,
  "usedJSHeapSize": 129866614,
  "jsHeapSizeLimit": 4294705152
}
Username = JennBot22
Chat ID = ecef87934f6c
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@JennBot22 thanks for the report, seems like something is up with our Netlify endpoint! I have escalated to engineering and updates will come in issue #1485, so please subscribe there!

**Comment by kc0tlh** [comment]
Update: We have identified the core issue and fixed it. Happy coding!
