### ISSUE TITLE
Something went wrong while creating your site on Netlify.

### ISSUE THREAD

**Issue by ahmetarslan** [stackblitz/bolt.new#1510]
### Describe the bug

Something went wrong while creating your site on Netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jbplrg

### Steps to reproduce

i cant deploy.

### Expected behavior

it should deploy the app

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 60684508,
  "usedJSHeapSize": 57075720,
  "jsHeapSizeLimit": 2172649472
}
Username = ahmetarslan
Chat ID = e421e142e5c7
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@ahmetarslan thanks for the timely report! We identified the core issue and fixed it. Happy coding! #1485
