### ISSUE TITLE
Unable to deploy on to a netlify url

### ISSUE THREAD

**Issue by rayyanai** [stackblitz/bolt.new#1512]
### Describe the bug

I am not able to deploy the app on to the netlify url.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-peqeuj

### Steps to reproduce

1. Gave a prompt to create a tool
2. Added more feilds to the tool to customize it
3. Deployment failed

### Expected behavior

Should be deployed on the URL

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108829833,
  "usedJSHeapSize": 103616513,
  "jsHeapSizeLimit": 2160066560
}
Username = rayyanai
Chat ID = fe0247727d63
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@rayyanai thanks for the timely report! We identified the core issue and fixed it. Happy coding! #1485
