### ISSUE TITLE
Unable to deploy the app

### ISSUE THREAD

**Issue by Virtuel21** [stackblitz/bolt.new#1513]
### Describe the bug

Hello, I'm unable to publish my app on Netlify. I'm receiving an error message saying, 'Something went wrong while creating your site.' Could you help me resolve this issue?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yrrpwt

### Steps to reproduce

just hit deploy button

### Expected behavior

it should be published

### Screen Recording / Screenshot

![Capture d’écran 2024-11-04 200540](https://github.com/user-attachments/assets/131bd55f-4f08-4d70-bf77-e7bc4353c697)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 158411578,
  "usedJSHeapSize": 147976486,
  "jsHeapSizeLimit": 4294705152
}
Username = Virtuel21
Chat ID = 15fd425d70d4
```

### Additional context

Error:
```
Something went wrong while creating your site on Netlify.
```

**Comment by kc0tlh** [comment]
@Virtuel21 thanks for the timely report! We identified the core issue and fixed it. Happy coding! #1485
