### ISSUE TITLE
Severe Import Issue

### ISSUE THREAD

**Issue by jacobnorgord** [stackblitz/bolt.new#1515]
### Describe the bug

<img width="485" alt="Screenshot 2024-11-04 at 1 09 46 PM" src="https://github.com/user-attachments/assets/a4bcb31a-34f4-4af2-ab5f-c5b1a6c9d69f">
I am unable to load my project, chat to debug, or access backups of my project. Last time I was on it said there was issues downloading the changes so it was trying to create a zip of the project and failing. When I restarted this happened.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ihyxqm

### Steps to reproduce

1. Encountered issue with saving project.
2. Refreshed.
3. Received this error.
4. Unable to restore backup, chat, see or edit code files, etc.

### Expected behavior

Restore backup, chat, see or edit code files, etc.

### Screen Recording / Screenshot

<img width="485" alt="Screenshot 2024-11-04 at 1 09 46 PM" src="https://github.com/user-attachments/assets/a4bcb31a-34f4-4af2-ab5f-c5b1a6c9d69f">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83584047,
  "usedJSHeapSize": 65504275,
  "jsHeapSizeLimit": 2160066560
}
Username = jacobnorgord
Chat ID = 39cd1431922d
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by arjunw7** [comment]
Facing the same issue on my app. Can't launch the project or see backups.

**Comment by jacobnorgord** [comment]
Now none of my files are showing when I open the project. Hoping that they can be restored.

**Comment by jacobnorgord** [comment]
Hey Alexander,

I am now able to see the backups whereas I couldn't yesterday.

Thanks for your help!

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=bm9yZ29yZGphY29iQGdtYWlsLmNvbQ==>
