### ISSUE TITLE
Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by userness** [stackblitz/bolt.new#1520]
### Describe the bug

Unexpected token 'U', "Unexpected"... is not valid JSON

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-htv327

### Steps to reproduce

1.Visit the url
2. Read the response.
![Screenshot](https://github.com/user-attachments/assets/113f40d4-b2bf-4ba7-885d-d09df4bade41)

### Expected behavior

It working

### Screen Recording / Screenshot

![Screenshot](https://github.com/user-attachments/assets/113f40d4-b2bf-4ba7-885d-d09df4bade41)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46221563,
  "usedJSHeapSize": 42167431,
  "jsHeapSizeLimit": 2172649472
}
Username = userness
Chat ID = f371002f2bc1
```

### Additional context

Error:
```
An unknown error occured while running an action..
```

**Comment by amp23** [comment]
Same problem

**Comment by Juni-crypto** [comment]
Same here too

**Comment by richardrguez** [comment]
same problem

**Comment by userness** [comment]
It might be an issue with their severs because it was glitchy before too

**Comment by userness** [comment]
They fixed it.
