### ISSUE TITLE
Project Dissapeared

### ISSUE THREAD

**Issue by Alm0stEthical** [stackblitz/bolt.new#1521]
### Describe the bug

I spent around 3 hours and 3 MILLION tokens on the project and it just disappeared? Can you guys look into this issue?

### Link to the Bolt URL that caused the error

/

### Steps to reproduce

/

### Expected behavior

Not being deleted

### Screen Recording / Screenshot

/

### Platform

- OS: Windows 10
- Browser: Chrome
- Version: 22H2

**Comment by Juni-crypto** [comment]
Please check under StackBlitz Collections @Alm0stEthical

**Comment by Alm0stEthical** [comment]
> Please check under StackBlitz Collections @Alm0stEthical 
It disappeared there too, but I have the deployed URL though, and it also isn't at the "My Repositories" Section
