### ISSUE TITLE
Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by ViciousSquare** [stackblitz/bolt.new#1522]
### Describe the bug

Unexpected token 'U', "Unexpected"... is not valid JSON
No preview or code loading

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mmsdg2

### Steps to reproduce

just trying to start / load 

### Expected behavior

deploy and preview the existing website that is working

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90290881,
  "usedJSHeapSize": 87603969,
  "jsHeapSizeLimit": 2160066560
}
Username = ViciousSquare
Chat ID = 2f36c0e150b2
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@ViciousSquare Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
