### ISSUE TITLE
error occurred.

### ISSUE THREAD

**Issue by LorenzoTrionfi** [stackblitz/bolt.new#1524]
### Describe the bug

i made a page called "make a sowiso like platform" and it says an unknown errror while importing the project from stackblitz. this is what it says me:sb1-kee1ih Unexpected token 'U', "Unexpected"... is not valid JSON An unknown error occured while running an action

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kee1ih

### Steps to reproduce

i don't know

### Expected behavior

i'm expecting my project's preview to appear

### Screen Recording / Screenshot

![Schermata 2024-11-04 alle 8 22 58 PM](https://github.com/user-attachments/assets/a344a05f-1e3f-4477-bce4-4ae9fbb8e9c8)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65811292,
  "usedJSHeapSize": 58427396,
  "jsHeapSizeLimit": 2160066560
}
Username = Lorenzo Trionfi
Chat ID = a6cdac7ad406
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@LorenzoTrionfi Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
