### ISSUE TITLE
Unable to import my project

### ISSUE THREAD

**Issue by harshhustle** [stackblitz/bolt.new#1525]
### Describe the bug

Unable to import my project

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wwupai

### Steps to reproduce

Just navigate to https://bolt.new/~/sb1-wwupai, import is failing with error "Unexpected token 'U', "Unexpected"... is not valid JSON"

### Expected behavior

Should be able to import

### Screen Recording / Screenshot

![Capture](https://github.com/user-attachments/assets/d55e0619-e188-4e9c-90ec-cbeb56994594)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 140235832,
  "usedJSHeapSize": 127064276,
  "jsHeapSizeLimit": 4294705152
}
Username = harshhustle
Chat ID = 4c5b9ef44e16
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@harshhustle Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
