### ISSUE TITLE
Project won't load anymore

### ISSUE THREAD

**Issue by dlarmitage** [stackblitz/bolt.new#1526]
### Describe the bug

Importing Stackblitz Project

sb1-mtco7t
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mtco7t

### Steps to reproduce

Load project into Bolt.  It will load and run just fine in Stackblitz.  

### Expected behavior

All of a sudden I cannot load this project anymore!  

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68594032,
  "usedJSHeapSize": 66552436,
  "jsHeapSizeLimit": 4294705152
}
Username = dlarmitage
Chat ID = d61a93ccf5e8
```

**Comment by kc0tlh** [comment]
@dlarmitage Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
