### ISSUE TITLE
Getting an error message when login in   Importing Stackblitz Project  sb1-5vs1ju

### ISSUE THREAD

**Issue by Tribute-montage** [stackblitz/bolt.new#1528]
### Describe the bug

Getting an error message when login in 

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-5vs1ju
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5vs1ju

### Steps to reproduce

I'm experiencing issues when I log in. I have been working on a project for four days and have made little progress, resulting in a total expense of $200. Can you assist me?

### Expected behavior

would like to continue working on it

### Screen Recording / Screenshot

no

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141698250,
  "usedJSHeapSize": 128496070,
  "jsHeapSizeLimit": 4294705152
}
Username = tribute_montage
Chat ID = 9ddcca4e3b82
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@Tribute-montage Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
