### ISSUE TITLE
Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by IzaacSB** [stackblitz/bolt.new#1532]
### Describe the bug

Receiving this error while trying to import project from SB to Bolt

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-me6y5b

### Steps to reproduce

Click on the URL

### Expected behavior

Should properly import the project.

### Screen Recording / Screenshot

![448c0055348e9fa2e9498ea468bfcd61](https://github.com/user-attachments/assets/5127c57b-e57a-4b1b-971a-1cde22f45c2f)

### Platform

- OS: MacOS
- Browser: Brave
- Version: [Version 1.71.114]

**Comment by kc0tlh** [comment]
@IzaacSB Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
