### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by ManiAhmeti** [stackblitz/bolt.new#1538]
### Describe the bug

The application is already built - I can see the /out directory with all the static files generated by Next.js. The build was successful and generated all the necessary files for deployment.

Now we can proceed with deploying to Netlify:

Deploy portfolio to Netlify

netlify
Let me check the deployment status to get the live URL.

An unknown error occurred when deploying your project.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-6y7ymg

### Steps to reproduce

1. click deploy 

### Expected behavior

Deploy the project to Netlify , or show a manual way to do that. 

### Screen Recording / Screenshot

![Capture](https://github.com/user-attachments/assets/4934f9a5-8699-4106-8b84-8dfc31755dcb)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54664546,
  "usedJSHeapSize": 52245246,
  "jsHeapSizeLimit": 4294705152
}
Username = Monnni
Chat ID = 1ef70516b606
```

### Additional context

Error:
```

An unknown error occurred when deploying your project.
```

**Comment by kc0tlh** [comment]
@ManiAhmeti thanks for the report! We are tracking this in #499
