### ISSUE TITLE
can not deploy !!! 

### ISSUE THREAD

**Issue by bjules19** [stackblitz/bolt.new#1539]
### Describe the bug

lorsque je demande le déploiement de mon app il ne veut jamais treminer.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jzqhu1

### Steps to reproduce

1/ clique sur déploiement
2/erreur"Une erreur inconnue s'est produite lors du déploiement de votre projet"

### Expected behavior

1/ cliquer sur déploiement
2/ obtenir l url pour le publier 

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = Jules Boisseau
Chat ID = 42e8cd0fee1d
```

### Additional context

Error:
```
An unknown error occurred when deploying your project.
```

**Comment by kc0tlh** [comment]
@bjules19 thanks for the report! We are tracking this in #499

**Comment by LCDA26** [comment]
Hi, I have the same problem when deploying, and I also spent millions of Tokens! Has anyone found the solution? Thanks in advance
