### ISSUE TITLE
sb1-1syj6x Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by ogoudge** [stackblitz/bolt.new#1540]
### Describe the bug

Been working on a project with no issues and when I came back to update it I got the error: sb1-1syj6x
The unexpected token 'U', "Unexpected"... is not valid JSON when it tries to load it. It loads fine in stack blitz, but when importing, I get the error. 

Can you fix this or direct me on how to do it? I want to finish this project.

Thanks

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1syj6x

### Steps to reproduce

Import into bolt.net

### Expected behavior

Load the project

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49260793,
  "usedJSHeapSize": 42346961,
  "jsHeapSizeLimit": 2160066560
}
Username = ogoudge
Chat ID = 2eadc98c4a3a
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@ogoudge Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
