### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by patinas** [stackblitz/bolt.new#1544]
### Describe the bug

Cannot import my project into bolt again

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-djxlhl

### Steps to reproduce

Open in bolt when on the stackblitz editor

### Expected behavior

The import works

### Screen Recording / Screenshot

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-djxlhl
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68933827,
  "usedJSHeapSize": 60646379,
  "jsHeapSizeLimit": 2160066560
}
Username = patinas
Chat ID = 06abf40d06f2
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@patinas Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
