### ISSUE TITLE
Importing Stackblitz Project - Keeps failing

### ISSUE THREAD

**Issue by smartguyio** [stackblitz/bolt.new#1545]
### Describe the bug

Importing Stackblitz Project

sb1-fvmzho
Unexpected token 'U', "Unexpected"... is not valid JSON

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fvmzho

### Steps to reproduce

Access the link and bolt.new is trying to import the project from stackblitz, but it keeps failing.

### Expected behavior

It should be imported.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 123132584,
  "usedJSHeapSize": 109590044,
  "jsHeapSizeLimit": 4294705152
}
Username = smartguyio
Chat ID = 1dc0b3d8fa2c
```

### Additional context

Importing Stackblitz Project

sb1-fvmzho
Unexpected token 'U', "Unexpected"... is not valid JSON

**Comment by kc0tlh** [comment]
@smartguyio Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
