### ISSUE TITLE
From different computers, different projects visible

### ISSUE THREAD

**Issue by TheTiGuR** [stackblitz/bolt.new#155]
### Describe the bug

From different computers, different chat sessions are visible. In particular this link bolt is from my work computer and it only has the 1 session I started with, but I have 3 or 4 more that I did from home and none of those are visible.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hate63

### Steps to reproduce

Create bolt sessions on different computers, it appears that only those created on a given machine are visible on that machine. Feels like if I did a browser cache clear that I would lose it all, which doesn't seem like a good behavior.

### Expected behavior

All sessions visible anywhere I log in.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62120801,
  "usedJSHeapSize": 44311933,
  "jsHeapSizeLimit": 4294705152
}
Username = TheTiGuR
Chat ID = 8235708dd9f6
```

**Comment by kirjavascript** [comment]
Hey! Sorry for this issue, this is something we hope to land soon!

We're tracking this issue in #140. We will let you know when we have a solution in place.
