### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by CAPTKirk1967** [stackblitz/bolt.new#1550]
### Describe the bug

![bolt-new-sb1-nkuy1q-11-04-2024_02_08_PM](https://github.com/user-attachments/assets/1c1b13a2-3308-4e5f-a788-f798eebfc15a)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nkuy1q

### Steps to reproduce

1. Deploy
2. Error message

### Expected behavior

Please advise

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 164899664,
  "usedJSHeapSize": 158542136,
  "jsHeapSizeLimit": 4294705152
}
Username = CAPTKirk
Chat ID = 3d83873f2f38
```

### Additional context

Error:
```
An unknown error occurred when deploying your project.
```

**Comment by kc0tlh** [comment]
@CAPTKirk1967 thanks for the report! We identified the core issue and fixed it. Happy coding! #1485

**Comment by kc0tlh** [comment]
@CAPTKirk1967 we are tracking this in #499. Thanks for the report!
