### ISSUE TITLE
sb1-ba39go

### ISSUE THREAD

**Issue by extra330ffefz** [stackblitz/bolt.new#1552]
### Describe the bug

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-ba39go
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

i try to backup with save , now i lost my project

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ba39go

### Steps to reproduce

sb1-ba39go
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

### Expected behavior

sb1-ba39go
Unexpected token 'U', "Unexpected"... is not valid JSON
An unknown error occured while running an action.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53512828,
  "usedJSHeapSize": 48836156,
  "jsHeapSizeLimit": 2160066560
}
Username = Extra330
Chat ID = 2a032cd71e02
```

bolt.new

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@extra330ffefz Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
