### ISSUE TITLE
Importing Stackblitz Project  sb1-fueafh Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by TNieva64** [stackblitz/bolt.new#1554]
### Describe the bug

 sb1-fueafh Unexpected token 'U', "Unexpected"... is not valid JSON

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fueafh

### Steps to reproduce

log in 
go to https://[bolt.new/~/sb1-fueafh](https://bolt.new/~/sb1-fueafh)

### Expected behavior

load my project files ( wheelchair charity donation campaign

### Screen Recording / Screenshot

![Capture d’écran 2024-11-04 211533](https://github.com/user-attachments/assets/0f589ff1-1fdf-4bc7-8420-3e0c6eb8330d)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 48755813,
  "usedJSHeapSize": 46388977,
  "jsHeapSizeLimit": 4294705152
}
Username = thb264
Chat ID = 879707ef0fc6
```

### Additional context

i asket bolt chat to make sure there was not deprecated or obsolete libraries and packages befor deploying for production . it updated and tried to restart my project, never restarted.

**Comment by kc0tlh** [comment]
@TNieva64 Thanks for the report and apologies for the frustrating experience! The fix is explained in #1471
