### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by Bil124** [stackblitz/bolt.new#1556]
### Describe the bug

Subject: Urgent Resolution Required: Repeated Errors and Token Consumption

Dears , 

I am writing to express my deep frustration with the challenges I've encountered while using bolt. Despite my efforts to create a straightforward application, I’ve faced continuous errors and unresponsive, blank UI screens that have made development nearly impossible.

Throughout this process, I’ve exhausted approximately 2 million tokens, most of which were spent on attempts to resolve these repeated issues rather than advancing the project. This situation is extremely disappointing, given the time and resources invested without achieving a functional application.

I kindly request that you:

Review my usage history to verify the volume of tokens consumed in error resolution.
Provide a solution or guidance for the recurring issues that disrupt the development flow.
Reimburse the 2 million tokens spent on unsuccessful error handling and troubleshooting due to these unresolved platform issues.
I hope to see a prompt response and a solution that allows me to complete my project without further hindrance.

Thank you for your attention to this matter.

Best regards,

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n9bxtz

### Steps to reproduce

Subject: Urgent Resolution Required: Repeated Errors and Token Consumption

Dears , 

I am writing to express my deep frustration with the challenges I've encountered while using bolt. Despite my efforts to create a straightforward application, I’ve faced continuous errors and unresponsive, blank UI screens that have made development nearly impossible.

Throughout this process, I’ve exhausted approximately 2 million tokens, most of which were spent on attempts to resolve these repeated issues rather than advancing the project. This situation is extremely disappointing, given the time and resources invested without achieving a functional application.

I kindly request that you:

Review my usage history to verify the volume of tokens consumed in error resolution.
Provide a solution or guidance for the recurring issues that disrupt the development flow.
Reimburse the 2 million tokens spent on unsuccessful error handling and troubleshooting due to these unresolved platform issues.
I hope to see a prompt response and a solution that allows me to complete my project without further hindrance.

Thank you for your attention to this matter.

Best regards,

### Expected behavior

Subject: Urgent Resolution Required: Repeated Errors and Token Consumption

Dears , 

I am writing to express my deep frustration with the challenges I've encountered while using bolt. Despite my efforts to create a straightforward application, I’ve faced continuous errors and unresponsive, blank UI screens that have made development nearly impossible.

Throughout this process, I’ve exhausted approximately 2 million tokens, most of which were spent on attempts to resolve these repeated issues rather than advancing the project. This situation is extremely disappointing, given the time and resources invested without achieving a functional application.

I kindly request that you:

Review my usage history to verify the volume of tokens consumed in error resolution.
Provide a solution or guidance for the recurring issues that disrupt the development flow.
Reimburse the 2 million tokens spent on unsuccessful error handling and troubleshooting due to these unresolved platform issues.
I hope to see a prompt response and a solution that allows me to complete my project without further hindrance.

Thank you for your attention to this matter.

Best regards,

### Screen Recording / Screenshot

Subject: Urgent Resolution Required: Repeated Errors and Token Consumption

Dears , 

I am writing to express my deep frustration with the challenges I've encountered while using bolt. Despite my efforts to create a straightforward application, I’ve faced continuous errors and unresponsive, blank UI screens that have made development nearly impossible.

Throughout this process, I’ve exhausted approximately 2 million tokens, most of which were spent on attempts to resolve these repeated issues rather than advancing the project. This situation is extremely disappointing, given the time and resources invested without achieving a functional application.

I kindly request that you:

Review my usage history to verify the volume of tokens consumed in error resolution.
Provide a solution or guidance for the recurring issues that disrupt the development flow.
Reimburse the 2 million tokens spent on unsuccessful error handling and troubleshooting due to these unresolved platform issues.
I hope to see a prompt response and a solution that allows me to complete my project without further hindrance.

Thank you for your attention to this matter.

Best regards,

### Additional context

Subject: Urgent Resolution Required: Repeated Errors and Token Consumption

Dears , 

I am writing to express my deep frustration with the challenges I've encountered while using bolt. Despite my efforts to create a straightforward application, I’ve faced continuous errors and unresponsive, blank UI screens that have made development nearly impossible.

Throughout this process, I’ve exhausted approximately 2 million tokens, most of which were spent on attempts to resolve these repeated issues rather than advancing the project. This situation is extremely disappointing, given the time and resources invested without achieving a functional application.

I kindly request that you:

Review my usage history to verify the volume of tokens consumed in error resolution.
Provide a solution or guidance for the recurring issues that disrupt the development flow.
Reimburse the 2 million tokens spent on unsuccessful error handling and troubleshooting due to these unresolved platform issues.
I hope to see a prompt response and a solution that allows me to complete my project without further hindrance.

Thank you for your attention to this matter.

Best regards,

**Comment by endocytosis** [comment]
Appreciate the feedback! A blank preview window is a known issue and is being tracked here: #1791. Additionally, this page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights into using Bolt most effectively while maximizing token efficiency. Refund requests are handled through hello@stackblitz.com.
