### ISSUE TITLE
Stuck on white screen

### ISSUE THREAD

**Issue by buligAi** [stackblitz/bolt.new#1557]
### Describe the bug

I've consumed a million tokens just to fix the white screen but still an issue.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-etczth

### Steps to reproduce

i need a refund

### Expected behavior

it should show up the app in the previewer

### Screen Recording / Screenshot

...

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112862026,
  "usedJSHeapSize": 91600182,
  "jsHeapSizeLimit": 4294705152
}
Username = buligAi
Chat ID = cdc8e8fb75cc
```

**Comment by endocytosis** [comment]
Hi @buligAi,

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates.
