### ISSUE TITLE
How can I use the bolt.new ai in stackblitz?

### ISSUE THREAD

**Issue by innocentdavid** [stackblitz/bolt.new#156]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, it would be great to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by samdenty** [comment]
there's now an open in bolt button on all stackblitz projects

**Comment by innocentdavid** [comment]
I still can't open an existing repository in bolt.new only project created
in stackblitz
Why?
