### ISSUE TITLE
I NEED MY MONEY BACK

### ISSUE THREAD

**Issue by jagal101** [stackblitz/bolt.new#1561]
### Describe the bug

I sent many emails regarding the errors I am facing and received no reply. When I enter a basic prompt like change the color of the text, it gives me this error "prompt is too long: 201053 tokens > 200000 maximum"

I tried contacting the support, no reply. I need my money back. This is just a scam company!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hbaxpy

### Steps to reproduce

Type anything and it will say "prompt is too long: 201053 tokens > 200000 maximum"

### Expected behavior

Not this "prompt is too long: 201053 tokens > 200000 maximum"

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@jagal101 we will 100% get you a refund. We are not a scam company. What email address did you reach out from so I can get it prioritized for you?

Also tagging to #1322 where this error is being tracked

**Comment by jagal101** [comment]
My email address that I used is ***@***.***

Error: #1322

**Comment by kc0tlh** [comment]
@jagal101 what email? This is all I see:
![image](https://github.com/user-attachments/assets/2e42b860-80da-4c12-b43f-443eed879e46)

**Comment by jagal101** [comment]
Github is covering it. Can you see this? malik.kash.habib at g m ai l

**Comment by jagal101** [comment]
I haven't received my money or any response from you again.

**Comment by SM-Aether** [comment]
My Stackblitz account has been hacked, the hacker spent 50 USD and also tried a charge of 2100 USD. I need help to recover my account please, is very urgent.

**Comment by saudinccam** [comment]
Hello -  

Can you please refund my money? Bolt is encountering frequent issues and not able to fix the simple problems. I have cancelled my subscription within an hour. please refund my money.
