### ISSUE TITLE
Stuck and Installing Dependencies

### ISSUE THREAD

**Issue by sirioberati** [stackblitz/bolt.new#1563]
### Describe the bug

I am stuck at installing dependencies. And when it does, if it does, all I see is blank. Nothing being built.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lzzwov

### Steps to reproduce

I am building a web-based UI that collects business data and outputs AI-generated social media strategies, including content calendars, mission and vision statements, and content pillars. Can you help me create a detailed plan to design and implement this? Provide an overview of the architecture and user flow.

### Expected behavior

It does nothing. Just says intsalling dependencies.
<img width="2025" alt="Screenshot 2024-11-04 at 8 07 20 PM 1" src="https://github.com/user-attachments/assets/440a1ebb-eda0-450e-8cba-ce04810eed48">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
