### ISSUE TITLE
cant see preview. all blank/white screen. how to fix it??????????

### ISSUE THREAD

**Issue by geafreitas** [stackblitz/bolt.new#1570]
### Describe the bug

cant see preview. all blank/white screen. how to fix it?????????? eating all the tokens

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-g1sfpj

### Steps to reproduce

it codes. but does not show preview.

### Expected behavior

show preview

### Screen Recording / Screenshot

![issue](https://github.com/user-attachments/assets/f107ffad-30f8-49ee-b5ef-05b3859045ab)

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = giftyfund
Chat ID = 489241508f93
```

**Comment by endocytosis** [comment]
Hi @geafreitas, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates.
