### ISSUE TITLE
otp not received to the mobile number

### ISSUE THREAD

**Issue by hitboyrohith** [stackblitz/bolt.new#1573]
### Describe the bug

after entering the number the number haven't received the otp's please resolve it

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2e224u

### Steps to reproduce

i want to generate otp request to the given phone number

### Expected behavior

i want to generate otp request to the given phone number

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 44861142,
  "usedJSHeapSize": 43396618,
  "jsHeapSizeLimit": 2172649472
}
Username = hitboyrohith
Chat ID = c4c827fbaa75
```

**Comment by endocytosis** [comment]
Hi @hitboyrohith,

While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects.

There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform.
