### ISSUE TITLE
It is not installing dependancies. I have wasted a lot of tokens as well. i have subcribed to the pro 100 pack. please help solve this issue. i tried logging in from another acount and it's working. it is specific to my account. it seems like you are limiting an account

### ISSUE THREAD

**Issue by ricketyrickyrick** [stackblitz/bolt.new#1574]
### Describe the bug

![Screenshot 2024-11-05 113321](https://github.com/user-attachments/assets/609423d3-66f4-4dc2-9a00-4ec428fdac53)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gmd3xh

### Steps to reproduce

load the project

### Expected behavior

install dependencies and load the project

### Screen Recording / Screenshot

![Screenshot 2024-11-05 113321](https://github.com/user-attachments/assets/a959c988-c6df-4cb5-b223-2c0dc55c61ee)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56822103,
  "usedJSHeapSize": 54774447,
  "jsHeapSizeLimit": 4294705152
}
Username = ricketyrick
Chat ID = c62ce898f8c6
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
