### ISSUE TITLE
the preview is not showing

### ISSUE THREAD

**Issue by TarekRef3at1971** [stackblitz/bolt.new#1575]
### Describe the bug

the preview is not showing

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dqm9zq

### Steps to reproduce

refresh preview to see the result

### Expected behavior

preview of the result

### Screen Recording / Screenshot

![Screen Shot 2024-11-05 at 8 30 43 AM](https://github.com/user-attachments/assets/4b485ab1-ef9b-47ef-bd8b-326f6d7d1725)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50506869,
  "usedJSHeapSize": 47493837,
  "jsHeapSizeLimit": 4294705152
}
Username = TarekRef3at1971
Chat ID = 82123768c668
```

**Comment by endocytosis** [comment]
Appreciate the feedback here. We are tracking this issue: [#1791](https://github.com/stackblitz/bolt.new/issues/1791). You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
