### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by Jkiwele** [stackblitz/bolt.new#1576]
### Describe the bug

Bolt is not able to deploy my application to Netlify, I need your assistance, cause this is causing my tokens being consumed.
I urgently need your assistance

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aaoksw

### Steps to reproduce

1. Go to "Deploy"

### Expected behavior

Live URL sent and application deployed.

### Screen Recording / Screenshot

<img width="950" alt="Screenshot bolt 05112024" src="https://github.com/user-attachments/assets/c26cbbab-e870-4bf0-8ed0-b46360210f60">

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53490996,
  "usedJSHeapSize": 48516460,
  "jsHeapSizeLimit": 4294705152
}
Username = jkiwele
Chat ID = 2e52da8ef918
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by aelbore** [comment]
Same issue here

**Comment by Jkiwele** [comment]
Help me fix it

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback! We are aware of this issue and are tracking it here: #1022.
