### ISSUE TITLE
And what should I do about it??

### ISSUE THREAD

**Issue by Habartru** [stackblitz/bolt.new#1577]
### Describe the bug

I have been creating a project for a long time and spent tens of millions of tokens on it. Now, when I try to write anything, I get an error about a long prompt (prompt is too long: 200072 tokens > 200000 maximum) and I can't work on my project. I did not find a solution.  The creators of BOLT, maybe it's time to think about it? Do you think I should forget that I spent 5 days and $120 on this project, and now I don't have access to edit it, is that okay in your opinion?  Can someone answer specifically without sending to some other branches where there are no answers either ?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pesz3g

### Steps to reproduce

the chat is blocked for any message.

### Expected behavior

the normal operation of the chat and the project

### Platform

```
Browser name = Chrome
Full version = 132.0.0.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49722508,
  "usedJSHeapSize": 46700876,
  "jsHeapSizeLimit": 4294705152
}
Username = Habartru
Chat ID = 49fde7ce9c09
```

**Comment by smartguyio** [comment]
Same

**Comment by yasinkocak** [comment]
https://github.com/stackblitz/bolt.new/issues/1322

**Comment by kc0tlh** [comment]
As @yasinkocak mentions, this issue, and the workarounds are being tracked in #1322. Please head over there @smartguyio @heliusmaximus08 🙏🏻
