### ISSUE TITLE
prompt is too long: 200800 tokens > 200000 maximum

### ISSUE THREAD

**Issue by heliusmaximus08** [stackblitz/bolt.new#1579]
### Describe the bug

I can no longer work on my project even though I have more than 19 million tokens. Even if I enter just one word and press enter, this message pops up: 200800 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fmiguq

### Steps to reproduce

dont know

### Expected behavior

that i can work again on my project without this failure. (Prompt is too long) I mean i have the 100Dollar subscription, this is too expensive as it doesnt work for

### Screen Recording / Screenshot

![Screenshot 2024-11-05 093226](https://github.com/user-attachments/assets/2b0d1042-e1d9-45b7-9888-60fa8e9aedf2)

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = heliusmaximus08
Chat ID = 674aed7a4f3d
```

### Additional context

it also have taken me a lot of tokens for no solutions. this is unfair and inacceptable

**Comment by endocytosis** [comment]
Hi @heliusmaximus08,

We are aware of this issue. We have current workarounds you can try and will be tracking future developments here: #1322.
