### ISSUE TITLE
Working on Different Devices, no History

### ISSUE THREAD

**Issue by patricecolucci** [stackblitz/bolt.new#1580]
### Describe the bug

I cant see the history of my projects when working on a different device.

### Link to the Bolt URL that caused the error

ww

### Steps to reproduce

Open bolt.new on a diffrent device and going to chats.

### Expected behavior

..

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @patricecolucci, temporary workarounds and future improvements for this are being tracked here #39.
