### ISSUE TITLE
Prompt is too long

### ISSUE THREAD

**Issue by smartguyio** [stackblitz/bolt.new#1583]
### Describe the bug

Whatever i write i get prompt is too long.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fvmzho

### Steps to reproduce

1. Access the project
2. Apps starts
3. Enters a prompt to edit any of the code
4. Receives "prompt is too long: 204566 tokens > 200000 maximum"

### Expected behavior

To edit based on the prompt.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi, 

We are aware of this issue and tracking it here: #1332, which includes some potential approaches for resolution. Thanks for the report!
