### ISSUE TITLE
cant deploy

### ISSUE THREAD

**Issue by ahmetarslan** [stackblitz/bolt.new#1586]
### Describe the bug

hi - i can't deploy it again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gm2gqd

### Steps to reproduce

tried to deploy to netlify. 

### Expected behavior

it should deploy to the netlify. 

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 77489417,
  "usedJSHeapSize": 73933149,
  "jsHeapSizeLimit": 2172649472
}
Username = ahmetarslan
Chat ID = 299d2246ddf2
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @ahmetarslan, 

Appreciate the feedback. We are aware of this issue and are tracking it here: #1022.
