### ISSUE TITLE
Deploy to Netlify not working

### ISSUE THREAD

**Issue by ahmedelseoudy** [stackblitz/bolt.new#1588]
### Describe the bug

![Error by deploying](https://github.com/user-attachments/assets/86d912af-a7a6-4f2d-ab7c-f0a71ea625b6)

I get this error every time I try to deplay. This issue is only with this project and for many days.

### Link to the Bolt URL that caused the error

https://bolt.new/~/withastro-astro-rqiunt

### Steps to reproduce

I just click deploy
I always get the same error
![Error by deploying](https://github.com/user-attachments/assets/bf5c8e01-9a39-41b2-86d2-009cbbc838be)

### Expected behavior

Should be deplayed and give me a link to be able to check the application live

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60191698,
  "usedJSHeapSize": 56819518,
  "jsHeapSizeLimit": 4294705152
}
Username = AhmedeGentic
Chat ID = a6d45c1a4f31
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
