### ISSUE TITLE
I lost my previous chat after subscription

### ISSUE THREAD

**Issue by osman-koc** [stackblitz/bolt.new#1593]
### Describe the bug

I had started a chat and when I created a subscription and went back because the token ran out, I couldn't see anything from the past. The previous messages are gone and in the existing chat there is only a reply with an import error, I can't enter a new prompt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1acumb

### Steps to reproduce

1. Start a new chat
2. Generate a project with ai
3. Go to subscription for new plan
4. Back to chat
5. Error

### Expected behavior

Resuming the chat.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60833312,
  "usedJSHeapSize": 38882132,
  "jsHeapSizeLimit": 4294705152
}
Username = osman-koc
Chat ID = 7d1772e09cc9
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@osman-koc please follow the instructions in #39 to reload your chats!
