### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by daniellannon** [stackblitz/bolt.new#1598]
### Describe the bug

Trying to test the product and getting an error everytime it hits the build stage npx vite build

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dhduwk

### Steps to reproduce

1. Click deploy

### Expected behavior

I expect it to be deployed with a preview link

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114569206,
  "usedJSHeapSize": 105440166,
  "jsHeapSizeLimit": 4294705152
}
Username = daniellannon
Chat ID = 7835e9d32c27
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @daniellannon, 

We are aware of this issue and are tracking it here: #1022.
