### ISSUE TITLE
prompt to long

### ISSUE THREAD

**Issue by REBEL33Soul** [stackblitz/bolt.new#1599]
### Describe the bug

prompt is too long: 200153 tokens > 200000 maximum error needs to fixed can't update the work.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-agumc6

### Steps to reproduce

Asked Botl.new to Perform a comprehensive system verification including unit tests, integration tests, and end-to-end tests. Check for code coverage, performance bottlenecks, security vulnerabilities, and accessibility compliance. Provide actionable recommendations for improvements, prioritized by severity and impact.

prompt is too long: 200153 tokens > 200000 maximum. Two words, one word, nothing works. I even bought more tokens, and refreshed the browser and cleared the history.

### Expected behavior

return to normal chat.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 149904306,
  "usedJSHeapSize": 108511978,
  "jsHeapSizeLimit": 4294705152
}
Username = REBEL33Soul
Chat ID = 3d5c681ebb63
```

### Additional context

Perform a comprehensive system verification including unit tests, integration tests, and end-to-end tests. Check for code coverage, performance bottlenecks, security vulnerabilities, and accessibility compliance. Provide actionable recommendations for improvements, prioritized by severity and impact.

prompt is too long: 200153 tokens > 200000 maximum. Two words, one word, nothing works. I even bought more tokens, and refreshed the browser and cleared the history.

**Comment by yasinkocak** [comment]
https://github.com/stackblitz/bolt.new/issues/1322

**Comment by kc0tlh** [comment]
@REBEL33Soul As @yasinkocak says, we are tracking this issue and the workarounds in #1322 so please head over there for more info!
