### ISSUE TITLE
No preview given

### ISSUE THREAD

**Issue by 911Vinny** [stackblitz/bolt.new#1602]
### Describe the bug

The minute I've ask for a modification, I lost the preview feature

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-guxjwe

### Steps to reproduce

I just ask to switch the company name

### Expected behavior

I wanted the site to update with a diffrent name

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 320541757,
  "usedJSHeapSize": 312195969,
  "jsHeapSizeLimit": 4294705152
}
Username = 911Vinny
Chat ID = 1370329a2ec9
```

**Comment by endocytosis** [comment]
We appreciate the feedback and are aware of this issue which is being tracked here: #1791.
