### ISSUE TITLE
"The dependencies needed to run the server did not install correctly, and I was unable to see the result in the preview tab."

### ISSUE THREAD

**Issue by daniemen2388** [stackblitz/bolt.new#1608]
### Describe the bug

"The dependencies needed to run the server did not install correctly, and I was unable to see the result in the preview tab."

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-k4n6pz

### Steps to reproduce

1. I opened the new project in bolt.new.
2. I installed the necessary dependencies according to the instructions.
3. I attempted to run the server from the development environment.
4. I accessed the "Preview" tab to see the result, but it did not load correctly.

### Expected behavior

I expected the dependencies to install correctly and the server to run smoothly, allowing me to view the project output in the 'Preview' tab without issues

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101810587,
  "usedJSHeapSize": 82618239,
  "jsHeapSizeLimit": 4294705152
}
Username = daniemen2388
Chat ID = f653283b2c79
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
