### ISSUE TITLE
can't deploy or run the server

### ISSUE THREAD

**Issue by aaaalabs** [stackblitz/bolt.new#1609]
### Describe the bug

I can't run bolt.new or deploy. also not on stackblitz.

feels very unstable right now..

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-npoqao

### Steps to reproduce

try to deploy or run 

### Expected behavior

stable system

### Screen Recording / Screenshot

<img width="431" alt="Screenshot 2024-11-05 at 18 09 26" src="https://github.com/user-attachments/assets/678eae85-d715-4db6-978b-4f7157364289">
<img width="240" alt="Screenshot 2024-11-05 at 18 09 14" src="https://github.com/user-attachments/assets/6eee3c62-c83d-4399-b8a7-67ece2497304">
<img width="448" alt="Screenshot 2024-11-05 at 18 07 06" src="https://github.com/user-attachments/assets/2794c43a-d13f-4a9e-a9e0-b9d0044c4eae">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 182046853,
  "usedJSHeapSize": 171161617,
  "jsHeapSizeLimit": 4294705152
}
Username = aaaalabs
Chat ID = 4b144db87de8
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
