### ISSUE TITLE
trying to deploy to netlify

### ISSUE THREAD

**Issue by ahmetarslan** [stackblitz/bolt.new#1615]
### Describe the bug

An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-za9du6

### Steps to reproduce

i just need to publish my webapp on netlify but keep giving error

### Expected behavior

i just need to publish my webapp on netlify but keep giving error

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 81768609,
  "usedJSHeapSize": 62362797,
  "jsHeapSizeLimit": 2172649472
}
Username = ahmetarslan
Chat ID = 61d396bb5393
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Hi @ahmetarslan, 

Appreciate the feedback. We are aware of this issue and are tracking it here: #499.
