### ISSUE TITLE
Env variables

### ISSUE THREAD

**Issue by trascastefan** [stackblitz/bolt.new#1617]
**Is your feature request related to a problem? Please describe:**

Spent a lot of time and tokens and pressing the fix button on a topic that now seems to have been without solution. Specifically I tried connecting to airtable api via .env file. I tried using it again and again without succes. I now find within stackblitz that I can specify .env variables, but would have appreciated this info before I spent about 2M tokens and 6 hours.

**Describe the solution you'd like:**
As soon as .env is mentioned or such variables, make the LLM not try to update the code, but rather instruct the user to answer with stackblitz best practices in how to handle that , with a step by step. 

Don't try to refactor code around .env just offer guidelines in how to achieve the setup.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
Hi @trascastefan, 

Appreciate the feedback. The team is hard at work improving token usage efficiency, more of which can be found here: #678. Also, you can right-click a file in the Bolt file system and click "Lock file" to prevent AI changes to that file.
