### ISSUE TITLE
Almost always hangs on "Install Dependencies"

### ISSUE THREAD

**Issue by khzou** [stackblitz/bolt.new#1626]
### Describe the bug

Takes long time on "Install Dependencies"
npm install

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-t2oktb

### Steps to reproduce

Almost any prompt will trigger it

### Expected behavior

npm install is normal

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
npm install times vary based on the size of the npm dependency tree. If npm install hangs, refreshing the page often resolves the issue (but be aware that you will lose your current chat history with a page refresh). Hope this helps!
