### ISSUE TITLE
Everything I have created yesterday is gone

### ISSUE THREAD

**Issue by karimhyahia** [stackblitz/bolt.new#163]
### Describe the bug

Hi, I have creaeted a few things yesterday, and I cannot see it in my account anymore

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-glc8wu

### Steps to reproduce

Go to my Dashboard

### Expected behavior

It is all gone

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
Hey, thanks for reporting this issue!

We're already tracking this issue in https://github.com/stackblitz/bolt.new/issues/39 so I'm going to close this issue. Feel free to subscribe to those to track our progress on this!
