### ISSUE TITLE
i'm already having 37M credits but still showing error prompt is too big even it is a single line 

### ISSUE THREAD

**Issue by asgharishkumar** [stackblitz/bolt.new#1636]
### Describe the bug

prompt is too long: 201845 tokens > 200000 maximum

i'm geeting this error when i'm working on the one project and because of this error i have worked from begining 2 times. i have subcribed to the plan 2 times and my credits have wasted and i'm able to finish the project 

![WhatsApp Image 2024-11-06 at 11 19 07](https://github.com/user-attachments/assets/df4c6331-9232-4cc1-a835-3758737283c2)

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vanilla-vite-8y7q4y

### Steps to reproduce

as the Boat to work on next module or give any prompt. it will show error of prompt is too long: 201845 tokens > 200000 maximum. also you can try small prompts also , even i'm not able to deploy 
![WhatsApp Image 2024-11-06 at 11 19 07](https://github.com/user-attachments/assets/50a778ba-e384-4d8f-8469-a5044b5943bf)

### Expected behavior

the bolt should respond to the prompt 

### Screen Recording / Screenshot

![WhatsApp Image 2024-11-06 at 11 19 07](https://github.com/user-attachments/assets/846dec27-2268-4968-a37d-06c572e1c57d)

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: 130.0.6723.92 (Official Build) (arm64)

### Additional context

KINDLY RESOLVE THIS ISSUE . I NEED TO COMPLETE MY PROJECT

**Comment by melvinlim87** [comment]
I encountered the same issue even though i bought 2 120m tokens account n fork it to another account. I hope the devs can fixed this as it is quite urgent on my side too

**Comment by ayalpani** [comment]
The limit of 200k tokens (per each request!) can probably not get liftet right now, no matter how much tokens you buy. it's what the LLM limits bolt to.

**Comment by endocytosis** [comment]
Hi all, 

Yes, we are aware of this issue. We have current workarounds you can try and will be tracking future developments here: #1322.

**Comment by asgharishkumar** [comment]
now when i refresh, project is not available 
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/0fcb5f89-026d-46bd-9fa9-0d5be6baefe0">

**Comment by kc0tlh** [comment]
@asgharishkumar you can re-load your project using the instructions in #39

**Comment by asgharishkumar** [comment]
Kindly let me know the status of my issue "prompt is too long: 201845 tokens > 200000 maximum" i need to complete my project and i have subcribed 3 times for your plan. @kc0tlh  kc0tlh
