### ISSUE TITLE
project just disappeared and wont load again  

### ISSUE THREAD

**Issue by Michaedis** [stackblitz/bolt.new#1638]
### Describe the bug

was work on project and out of a sudden bolt stopped an wont respond or open project.  I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-txsw2p
Project not found
An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-txsw2p

### Steps to reproduce

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-txsw2p
Project not found
An unknown error occured while running an action.

### Expected behavior

to open project and respond accordingly 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 95478034,
  "usedJSHeapSize": 58243382,
  "jsHeapSizeLimit": 4294705152
}
Username = Unique
Chat ID = dfd9075dc020
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by Manthan1907** [comment]
I am having the same problem

**Comment by kc0tlh** [comment]
@Michaedis @Manthan1907 please try the instructions in #39 to reload your project directly from StackBlitz and let us know if that does not work!

**Comment by Michaedis** [comment]
Ok I will do soMichaedis AOn Nov 8, 2024, at 10:57 AM, Alexander Berger ***@***.***> wrote:﻿
@Michaedis @Manthan1907 please try the instructions in #39 to reload your project directly from StackBlitz and let us know if that does not work!
