### ISSUE TITLE
Cannot the deploy the application

### ISSUE THREAD

**Issue by INXPRNCD** [stackblitz/bolt.new#1642]
### Describe the bug

I'll help you deploy the application to Netlify.

Deploy to Netlify

npx astro build
netlify
Let me check the deployment status to get the URL where your application is available.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xo6sdk

### Steps to reproduce

Click 'Deploy' for the Project 'CNC Industry Website with Advanced SEO' and you will see the deployment problem

### Expected behavior

I expected to deploy the application to see it live

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92018142,
  "usedJSHeapSize": 70598730,
  "jsHeapSizeLimit": 4294705152
}
Username = IXPRNCD
Chat ID = bd3d2f7b54a2
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this message and are tracking it here: #1022.
