### ISSUE TITLE
bolt.new product seems to have no option to cancel subscription

### ISSUE THREAD

**Issue by infrachris** [stackblitz/bolt.new#1644]
Please cancel my recurring subscription.  I'd suggest not requiring a github issue in order to perform run of the mill customer service or subscription changes.  It may be a common ecommerce belief that not having any form of downgrade or cancellation option somehow increases revenue, however I don't think that's the case it just increases manual labor by support which increaes expenses.

Thank you

**Comment by snakeplisskenai** [comment]
Click manage current plan from your subscriptions then cancel from there, it worked fine for me

**Comment by infrachris** [comment]
Thanks, that link did the trick
