### ISSUE TITLE
I lost my work

### ISSUE THREAD

**Issue by gershomcharig** [stackblitz/bolt.new#1649]
### Describe the bug

I entirely lost my work after opening it on Stackblitz! Costed me quite a lot of tokens and now it's gone!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ui67xg

### Steps to reproduce

1. Do a project on Bolt.new
2. Open it on stackblitz
3. Close stackblitz
4. When i reopen bolt.new, the project is gone

### Expected behavior

I should not lose my project! And my tokens

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73109456,
  "usedJSHeapSize": 49177964,
  "jsHeapSizeLimit": 4294705152
}
Username = gershomcharig
Chat ID = b7988da60beb
```

**Comment by endocytosis** [comment]
Hi @gershomcharig, 

Sorry to hear about this! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: [#39]. Appreciate your patience as improvements continue to be made!
