### ISSUE TITLE
My files on bolt have been cancelled from yesterday, i don't see an archive on bolt

### ISSUE THREAD

**Issue by Boras72** [stackblitz/bolt.new#1651]
### Describe the bug

Je ne retrouve pas mes fichiers dont j'avais fait une sauvegarde au fromat .zip

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. https://bolt.new/
2. My account is empty

### Expected behavior

<img width="175" alt="bolt" src="https://github.com/user-attachments/assets/8eba0e8a-3807-46e1-8b9e-888f78d1b219">

### Platform

- Windows 11
- Chrome
- Version: ?

### Additional context

J'avais travaillé la veille sur mon fichier qui avait été sauvegardé par Bolt, mais aujourd'hui plus rien !

**Comment by endocytosis** [comment]
Hi @Boras72, 

Apologies for any frustration here! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. Appreciate your patience as improvements continue to be made!
