### ISSUE TITLE
Interface issue after hitting the limit

### ISSUE THREAD

**Issue by kengeorge2** [stackblitz/bolt.new#166]
### Describe the bug

You have hit the rate limit. Please <a class="__boltUpgradePlan__">Upgrade</a> to keep chatting, or you can continue coding for free in the editor.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kzhv7m

### Steps to reproduce

this interface format error is seen after hitting the limit

### Expected behavior

You have hit the rate limit. Please Upgrade to keep chatting, or you can continue coding for free in the editor.

### Screen Recording / Screenshot

![ISSUE AFTER HITTING THE LIMIT](https://github.com/user-attachments/assets/1fa54544-42ad-4cd1-9865-abdf93c56218)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 223643022,
  "usedJSHeapSize": 213255906,
  "jsHeapSizeLimit": 2172649472
}
Username = kengeorge2
Chat ID = 5ec630e2a0ce
```

**Comment by d3lm** [comment]
Hey there! Do you still see this if you reload / hard reload the page?

**Comment by kc0tlh** [comment]
This should be resolved. Let us know if the issue persists!
