### ISSUE TITLE
Chat history is not visible

### ISSUE THREAD

**Issue by vijaymarch** [stackblitz/bolt.new#1663]
### Describe the bug

while generating the code, as a developer, I chat a lot with the product but the chat history is not retained

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3acmn1

### Steps to reproduce

while generating the code, as a developer, I chat a lot with the product but the chat history is not retained

### Expected behavior

chat  history should be retained

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @vijaymarch, 

Appreciate the feedback here! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. Appreciate your patience as improvements continue to be made.
