### ISSUE TITLE
Preview displays white ALOT!

### ISSUE THREAD

**Issue by frice8** [stackblitz/bolt.new#1664]
### Describe the bug

The prompt will write code and begin the preview and it has been white 80%-90% of the time. Yet, if I open it in StackBlitz, it's loads and I  can verify the changes. Again, this happens so much. Then, I have to use many of my credits to ask the prompt what's the issue. Please resolve this.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rzdcpn

### Steps to reproduce

1. Request and update, 2. go to preview tab and it will never load and be white with no errors. 3. open in stackblitz to review changes.

### Expected behavior

I expect the preview to work.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45542490,
  "usedJSHeapSize": 43584794,
  "jsHeapSizeLimit": 4294705152
}
Username = frice8
Chat ID = bc466ab15b26
```All broswers tested, Brave, Microsoft Edge and Google Chrome

### Additional context

Sorry, I'm just tired of using credits on resoving something that shouldn't happen. Thank you

**Comment by endocytosis** [comment]
Hi @frice8, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates.
