### ISSUE TITLE
Prompt Too Long

### ISSUE THREAD

**Issue by alirazazain** [stackblitz/bolt.new#1667]
### Describe the bug

No matter what I write in prompt, it has started giving me Prompt too long error.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-z254bx

### Steps to reproduce

When I write instructions whether few words or many, it give me this error every now and then. It started today.

https://github.com/user-attachments/assets/aa7fd0bb-73ce-4134-970e-9bd94fbba31a

### Expected behavior

It should give instructions.

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/aa7fd0bb-73ce-4134-970e-9bd94fbba31a

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63157931,
  "usedJSHeapSize": 61099191,
  "jsHeapSizeLimit": 4294705152
}
Username = alirazazain
Chat ID = e69374047358
```

**Comment by endocytosis** [comment]
Hi @alirazazain, 

We are aware of this issue. We have current workarounds you can try and will be tracking future developments here: #1322
