### ISSUE TITLE
Account Based Bolts

### ISSUE THREAD

**Issue by ExperienceCompany** [stackblitz/bolt.new#167]
**Is your feature request related to a problem? Please describe:**

When working on different computers, using the bolt chat, each computer has a different bolt history. I am afraid that they will override each other because i'm not seeing all of my bolts all in one account.

I believe the github connection overrides the original bolt username and that is what separated it. I think usernames should be different than the github usernames. Like a connected socials page or something.

**Describe the solution you'd like:**

I believe all bolts made for that account should appear for that account no matter the browser.  I also feel that in the Stackblitz editor, there should be a button/way to pull open the bolt for that specific project and keep the history for it and continue prompting for that project.

**Describe alternatives you've considered:**

I've been going to the computer i started on and not closing the window.
As for projects, ive been forking the projects to the account but still cant seem to access the bolts from the stackblitz project

**Additional context:**

N/A

**Comment by kirjavascript** [comment]
Hey! Sorry for this issue, this is something we hope to land soon!

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/140. We will let you know when we have a solution in place.
