### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by F-ai-rest** [stackblitz/bolt.new#1671]
### Describe the bug

[
![FireShot Capture 142 - bolt new - bolt new](https://github.com/user-attachments/assets/ea9ff87b-2a68-4eae-8fd9-b4dd1d4bacad)
](url)
package.json
npm install
tailwind.config.js
src/components/ApiKeySelector.tsx
src/components/TextInput.tsx
npm run build
netlify

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kri63t

### Steps to reproduce

package.json
npm install
tailwind.config.js
src/components/ApiKeySelector.tsx
src/components/TextInput.tsx
npm run build
netlify

### Expected behavior

An unknown error occured while running an action

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86146753,
  "usedJSHeapSize": 78804977,
  "jsHeapSizeLimit": 2160066560
}
Username = johnfairest
Chat ID = d910d2aeae52
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it and potential workarounds here: #2019

**Comment by F-ai-rest** [comment]
![FireShot Capture 251 - Twilio Console - console twilio com](https://github.com/user-attachments/assets/fcec1c97-4b2d-4535-b028-e2146d95a314)
![FireShot Capture 250 - bolt new - bolt new](https://github.com/user-attachments/assets/196fd9d0-3781-4e34-a522-6f258ba408b1)
![FireShot Capture 247 - bolt new - bolt new (1)](https://github.com/user-attachments/assets/78400d72-f423-4254-b5bc-c91cd6ddcc7c)
![FireShot Capture 247 - bolt new - bolt new](https://github.com/user-attachments/assets/274de141-b45a-4031-96d0-6bafe8584685)
Have emailed this over but no responce
