### ISSUE TITLE
Chat history - Previous Conversation is missing when two Machines are used

### ISSUE THREAD

**Issue by navamara55** [stackblitz/bolt.new#1675]
### Describe the bug

I used two different machines with the same github email ID which I used to purchase subscription.
Chat history is not synchronized correctly. Chats made in one machine is not available in the other machine. 

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1.Register and subscribe using github ID
2. Use computer A and create a chat and deploy it.
3. Logout in computer A
4. Sign in in computer B using the github ID used previosly
5. Expand left panel and notice the chat history is missing

### Expected behavior

Chat history should be persisted and usable across different machines for the same user id.

### Screen Recording / Screenshot

N/A

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

N/A

**Comment by endocytosis** [comment]
Hi @navamara55, 

Appreciate the feedback. We are aware of this issue and are tracking current workarounds plus ongoing developments here: #39
