### ISSUE TITLE
“Bolt not working with private repositories

### ISSUE THREAD

**Issue by rsnullptr** [stackblitz/bolt.new#1676]
### Describe the bug

Hey,

I tried opening my repo in bolt and it gave me a "You don't have access to the repository" error.
My repo works fine in stackblitz. its a private repo but I do have this connected to my Teams account on stackblitz.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/Pixie-sh/metsis-microservices

### Steps to reproduce

Go to stackblitz and allow the private organization repository from the github to stackblitz.
Open the repo in stackblitz and confirm its all working correctly.
Open https://bolt.new/~/GITHUB_URL
Error.

### Expected behavior

It should have access

### Screen Recording / Screenshot

<img width="558" alt="Screenshot 2024-11-06 at 18 07 30" src="https://github.com/user-attachments/assets/5a7e6133-0154-4ee7-a804-cb94191e488c">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 155509163,
  "usedJSHeapSize": 150987687,
  "jsHeapSizeLimit": 4294705152
}
Username = rsnullptr
Chat ID = d037332e4195
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Hi @rsnullptr, 

Appreciate the feedback here! Currently, private GitHub repositories are not supported but this is in development.

**Comment by rsnullptr** [comment]
In that case can I request a refund please? Honestly I was trying out Stackblitz because it said it would include Bolt Pro and manage Private repositories;

Bolt without private repositories has no use for me at this time. Thanks
