### ISSUE TITLE
UNABLE TO DEPLOY TO NETLIFY

### ISSUE THREAD

**Issue by samora254** [stackblitz/bolt.new#1677]
### Describe the bug

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-969yan

### Steps to reproduce

To deploy to netlify. I have tried uploading the Github repository directly it doesnt allow as well

### Expected behavior

To deploy to netlify. I have tried uploading the Github repository directly it doesnt allow as well

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/66973f74-cd8e-477a-a219-974ecc84d57d)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 115885761,
  "usedJSHeapSize": 111944665,
  "jsHeapSizeLimit": 4294705152
}
Username = samora254
Chat ID = 0bf25668fd68
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @samora254, 

We are aware of this issue and are tracking it here: #1022.
