### ISSUE TITLE
I would like a refund

### ISSUE THREAD

**Issue by jackcskates** [stackblitz/bolt.new#1678]
### Describe the bug

I spent all of my tokens, watching bolt repeat the same mistakes over and over again. I couldn't even get it to reference a simple backgorund image and logo placement. I spent an hour trying to get it to do that simple thing. If your product can't do something that basic, I shouldn't have to pay for that because I built an entire app with it before, and now I can't get past a single screen.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-eju9zy

### Steps to reproduce

1. I asked it to create a react app with some basic standard mobile app features. It ignored all of that, and just tried to create the landing pre-sign in page
2. I asked it to create a background image and a logo. That went on for over 45 minutes and I got no where... It kept trying to write code to recreate images into folders and then tried creating multiple image folders and re-naming the images and changing the file extensions.

### Expected behavior

To figure out how to reference an image in less than 45 minutes of failing
!

### Screen Recording / Screenshot

[Screenshot 2024-11-06 at 11 50 00 AM](https://github.com/user-attachments/assets/b26b20b4-5a80-4391-a55a-bea716a7b55c)

### Platform

- OS: macOS]
- Browser: Chrome]
- Version: latest

### Additional context

I need to know if you're going to charge me for something that's clearly not working, I need to know so I can cancel my subscription since I'm not going to pay for software that can't do basic things.

**Comment by endocytosis** [comment]
Hi @jackcskates, 

If you are looking for a refund, please reach out to hello@stackblitz.com as we process all refund requests there!
