### ISSUE TITLE
Ability to "go back" 

### ISSUE THREAD

**Issue by steveninge** [stackblitz/bolt.new#168]
The only thing keeping me from using this 100% over v0 is the ability to go back to old code. It's fairly often that a change it made that messes up something else unintentionally, and sometimes it's very hard to get it back to how it was when it was working properly.

**Comment by kirjavascript** [comment]
Hey! Thanks for raising this issue!

We're tracking this internally, and #35 is a similar feature request. I'm going to close this issue, feel free to subscribe for updates in the other issue! We'll keep you posted 🙌
