### ISSUE TITLE
prompt is too long: 202352 tokens > 200000 maximum

### ISSUE THREAD

**Issue by Chaitanyaprabu8** [stackblitz/bolt.new#1680]
Hi, currently i am waiting on one project in bolt.new, the project is almost completed, however there are still some errors. When I am trying to further request on resolving errors, it is showing as "prompt is too long: 202352 tokens > 200000 maximum". Can you please assist on addressing this issue please

**Comment by endocytosis** [comment]
Hi @Chaitanyaprabu8, 

We are aware of this issue and have current workarounds you can try and will be tracking future developments here: #1322.
