### ISSUE TITLE
Millions of tokens wasted

### ISSUE THREAD

**Issue by vassadi** [stackblitz/bolt.new#1681]
### Describe the bug

i was asking about a task and it is generated code. But it has some issues. Asked it to fix, which cause another. This happened as a cyclic process. Almost i lost 2M coins in that small applictaion. You can check the history of the application, how the tokens are gone in vain. Also, it is taking so many attempts to fix one issue. And it is missing imports and taking that as a separate error.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-g1vvkw

### Steps to reproduce

Just follow through the history. I lost millions of tokens.

### Expected behavior

It should properly address the issues, without wasting any tokens.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by agustinm20** [comment]
Same history here, bolt enter in some loop and waste million of tokens, debugging the code I see he generate a lot of repetitive code

**Comment by endocytosis** [comment]
Appreciate the feedback! This page [here](https://github.com/stackblitz/bolt.new/issues/678) contains a number of insights into maximizing token efficiency. Sometimes there are programming challenges that are too complex for the AI to solve, and as such manual intervention is required to prevent excessive token usage. Appreciate your patience as improvements continue to be made!
