### ISSUE TITLE
Project is gone

### ISSUE THREAD

**Issue by agustinm20** [stackblitz/bolt.new#1682]
### Describe the bug

Working on this project but suddenly dissaper. Now I have the same on github, can export to use it in bolt?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-i6f1ga

### Steps to reproduce

Project is gone

### Expected behavior

Project is gone

### Screen Recording / Screenshot

Project is gone

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = agustinm20
Chat ID = d7956e0a4253
```

### Additional context

Project is gone

**Comment by endocytosis** [comment]
Hi @agustinm20, 

Appreciate the feedback here. Regarding chat persistence, the team is aware of this issue and tracking it here: #39. Support for private GitHub repositories is currently in development. A potential workaround at this time is as follows: 

Download your GitHub repo, create an empty StackBlitz project, drag and drop your GitHub project files into the StackBlitz file system, save, and then use the “Open in Bolt” button to work on the project in Bolt. It is important to be aware that Bolt cannot support very large codebases, so this is only recommended for small projects at this time.
