### ISSUE TITLE
Won't install dependencies

### ISSUE THREAD

**Issue by JoshuaJohn94** [stackblitz/bolt.new#1683]
### Describe the bug

J
![Screenshot 2024-11-06 at 2 15 32 PM](https://github.com/user-attachments/assets/35b68d06-bd4f-4f35-bea5-2a416ca04adc)
It won't install dependencies continuously spins, and will not deploy, unfortunately 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dgcguy

### Steps to reproduce

Anything I am trying to build or deploy is not working

### Expected behavior

Installs dependencies or deploys to netifly

### Screen Recording / Screenshot

[
![Screenshot 2024-11-06 at 2 15 32 PM](https://github.com/user-attachments/assets/8912921f-8c65-4e6f-83d3-ad78a8b9e280)
](url)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68883688,
  "usedJSHeapSize": 62568752,
  "jsHeapSizeLimit": 4294705152
}
Username = JoshJohn
Chat ID = d0e20ddc68e0
```

**Comment by endocytosis** [comment]
Hi @JoshuaJohn94, 

Appreciate the feedback here! I was just able to open your project. Could you try again on your end? Often refreshing the page can resolve an issue if the system hangs on npm install.

**Comment by JoshuaJohn94** [comment]
Thank you! It started working a few hours later.Sent from my iPhoneOn Nov 7, 2024, at 3:41 PM, Brian ***@***.***> wrote:﻿
Hi @JoshuaJohn94,
Appreciate the feedback here! I was just able to open your project. Could you try again on your end? Often refreshing the page can resolve an issue if the system hangs on npm install.

**Comment by endocytosis** [comment]
Great, glad to hear it!
