### ISSUE TITLE
Page does not display from code

### ISSUE THREAD

**Issue by kismetaz** [stackblitz/bolt.new#1684]
### Describe the bug

I have run the code twice requesting the display and have used tokens to do so and still there is no display of a simple regsitration page for a download.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-je43qe

### Steps to reproduce

Display the landing page

### Expected behavior

Display the landing page to register for the download

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/373b9511-961e-4afa-b2fc-6d20700cb16b)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 611582157,
  "usedJSHeapSize": 590611701,
  "jsHeapSizeLimit": 4294705152
}
Username = kismetaz
Chat ID = e8072ea770a8
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is known issue and is being tracked here: #1791.
