### ISSUE TITLE
drag-drop and state management are not working properly 

### ISSUE THREAD

**Issue by bizwhitaker** [stackblitz/bolt.new#1688]
### Describe the bug

drag-drop of a Resource card on a work order does not change resource card to "Active" and the work order card state LABOR state button does not turn green

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jssl2g

### Steps to reproduce

drag-drop a Resource Card on a Work Order.  The Work Order State should now be Labor and the Resource card state should be  Active.  

### Expected behavior

The Work Order State should now be Labor  with the Labor button green with white text, and the Resource card state should be  Active. with the Active icon seen on the resource card

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 152884651,
  "usedJSHeapSize": 144486583,
  "jsHeapSizeLimit": 4294705152
}
Username = britt
Chat ID = 8af3849fbac9
```

**Comment by endocytosis** [comment]
Hi @bizwhitaker, 

Unfortunately we don't have the capacity to investigate issues with the programmatic logic of individual applications. There are programming challenges that AI can not solve automatically, and sometimes manual intervention is required. More information can be found here: https://github.com/stackblitz/bolt.new/issues/678. The [StackBlitz Discord](https://discord.gg/stackblitz) also has some threads where users share helpful insights into programming problems. Hope this helps!
