### ISSUE TITLE
Limit Token Usage Especially When Caught in Loop

### ISSUE THREAD

**Issue by natelasko528** [stackblitz/bolt.new#1689]
### Describe the bug

I really like your product, but the tokens got used up super fast and the ai was stuck in a loop trying to fix the same thing over and over again with the same methods, even though I was telling it what to do, it kept just using and reverting back to old code that we had already decided wasn't good anymore, so I don't know if I want to refund or just some credit just to try to fix it and maybe work with 1 of the developers to show you what's happening because I went through all the 10 million tokens like a day and II mean I got some progress, but I mean that's a lot to not have something have to pay another $30 when I could just use an open source.. Speaking of which, can we connect to open source LLMS like rock or whatever or use our tokens on other LMS? We already have subscriptions too and are paying for the API accents. Thank you.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zxy1ss

### Steps to reproduce

You can just look back through my most recent conversation history and see that even though I gave it the complete open AI real time API instructions, copy and paste it right from their page and the link for it to go itself is still kept using old code that wasn't referenced anywhere in the API guide. So I was really confused. Let's probably use the error and not knowing how to interact with it, but to use up ten million tokens that quickly and not solve anything and repeating the same stuff is kind of crazy

### Expected behavior

To just fix the code, because I gave it the sample code to use. It was actually, it did a lot of things. There were a lot harder versus just changing the template api code to match my settings. It was kind of weird

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! Agreed, when the LLM is stuck in a loop token usage can be excessive. Sometimes there are programming problems that are too complex for the AI to solve and manual intervention is required. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on ways to use tokens most efficiently. We appreciate your patience as improvements continue to be made!
