### ISSUE TITLE
Code is broken and no matter what I do the AI keeps adding back the same broken code

### ISSUE THREAD

**Issue by fizex** [stackblitz/bolt.new#1690]
### Describe the bug

Code is broken and no matter what I do the AI keeps adding back the same broken code. I've described the issue 50 times and it keeps creating the same broken code, I have also made it create a new file add the correct code there but then on the next run it deletes this and adds back the old version.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hfe3ug

### Steps to reproduce

I keep asking it to fix app.tsx and it keeps looping adding the same broken code.
<img width="1440" alt="Screenshot 2024-11-07 at 10 50 23 AM" src="https://github.com/user-attachments/assets/18dbc382-55bf-4369-bfd1-a729877fa2bf">

### Expected behavior

Functioning code

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126745115,
  "usedJSHeapSize": 103910727,
  "jsHeapSizeLimit": 2160066560
}
Username = fizex
Chat ID = 1b6d8f7b4ba9
```

### Additional context

Ok I managed to fix it by refreshing the browser window. It might have run out of memory or something?

_No response_

**Comment by endocytosis** [comment]
Glad to hear refreshing the window resolved the issue! A number of insights into efficient token usage and using Bolt most effectively can be found [here](https://github.com/stackblitz/bolt.new/issues/678), which are important to consider to avoid excessive token usage when encountering an error. Something else that can help is that in the Bolt file system if you right-click a file and click "Lock file" this will prevent the AI from making changes to that file. Hope this helps!
