### ISSUE TITLE
Deployment status 

### ISSUE THREAD

**Issue by JessePimenta** [stackblitz/bolt.new#1691]
### Describe the bug

No matter how many prompts i use or times i press the deploy button, i cannot deploy my app. I had it deployed earlier, but the link suddenly stopped working. I now am unable to deploy anything and get no response from the chat. It simply says "checking deployment status" does that for about 20 seconds, and provides no further response.
I have tried refreshing the page completely. it loads the project, but refuses to deploy it.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-ds9z6m

### Steps to reproduce

go to https://bolt.new/~/bolt-nextjs-shadcn-ds9z6m
try to deploy

### Expected behavior

the app successfully would deploy to netlify

### Screen Recording / Screenshot
![Screen Shot 2024-11-06 at 6 54 56 PM](https://github.com/user-attachments/assets/0b61299e-4c36-4bcd-9da4-37b0e32a719a)

_No response_

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108387377,
  "usedJSHeapSize": 103116869,
  "jsHeapSizeLimit": 4294705152
}
Username = JessePimenta
Chat ID = 522d11aa3399
```

**Comment by endocytosis** [comment]
Hi @JessePimenta, 

Appreciate the feedback. The team is aware of this issue and tracking it here: #1022. In the interim, you could try accessing your Bolt project by going to stackblitz.com and navigating to the Collections tab on the left-hand side and then opening the Bolt Collection. From there, you can open the project of interest in StackBlitz, click the download icon in the file explorer, and then upload the project files to Netlify using their service [here](https://app.netlify.com/drop).
