### ISSUE TITLE
teste 2

### ISSUE THREAD

**Issue by nunoluanova** [stackblitz/bolt.new#1694]
### Describe the bug

asasasasdasdasdsadsadasd

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-shadcn-wj8bka

### Steps to reproduce

asdasd

### Expected behavior

asdasda

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77720743,
  "usedJSHeapSize": 67886043,
  "jsHeapSizeLimit": 4294705152
}
Username = luiznova
Chat ID = dc4b460485ba
```

**Comment by AriPerkkio** [comment]
This issue does not have enough information. Please file a new one if you run into any issues.
