### ISSUE TITLE
Broken code loop

### ISSUE THREAD

**Issue by SadMachine777** [stackblitz/bolt.new#1695]
### Describe the bug

The code creates an error, the AI 'corrects' the error and it errors again and again...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nhiu5d

### Steps to reproduce

1. using ai run troubleshooting command and correction
2. test corrected app code
3. code produces error
4. try in stackblitz, produces error
5. repeat

### Expected behavior

The app has a simple chore creation window. I'm attempting to have icons associated with each chore. For example a cat for feeding the cat, toothbrush for brushing teeth, etc.

### Screen Recording / Screenshot

[plugin:vite:esbuild] Transform failed with 1 error:
/home/project/src/types.ts:62:54: ERROR: Unexpected "/"
/home/project/src/types.ts:62:54
Unexpected "/"
60 |  } as const;
61 |  
62 |  export type ChoreIconType = keyof typeof CHORE_ICONS;</content>
   |                                                        ^
    at failureErrorWithLog (/home/project/node_modules/esbuild/lib/main.js:1462:15)
    at eval (/home/project/node_modules/esbuild/lib/main.js:745:50)
    at responseCallbacks.<computed> (/home/project/node_modules/esbuild/lib/main.js:612:9)
    at handleIncomingPacket (/home/project/node_modules/esbuild/lib/main.js:667:12)
    at Socket.readFromStdout (/home/project/node_modules/esbuild/lib/main.js:590:7)
    at Socket.emit (node:events:30:10899)
    at addChunk (node:internal/streams/readable:225:3685)
    at readableAddChunk (node:internal/streams/readable:225:3393)
    at Readable.push (node:internal/streams/readable:225:4971)
    at _0x23d939.onStreamRead (node:internal/stream_base_commons:211:2596
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.

### Platform

```
Browser name = Chrome
Full version = 127.0.0.0
Major version = 127
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 OPR/113.0.0.0 (Edition std-1)
performance.memory = {
  "totalJSHeapSize": 86311652,
  "usedJSHeapSize": 79809472,
  "jsHeapSizeLimit": 4294705152
}
Username = SadMachine777
Chat ID = 0e7438179375
```

### Additional context

Code worked up until adding icons for chores.

**Comment by endocytosis** [comment]
Appreciate the feedback! There are some programming problems that are too complex for the LLM to solve. In such cases, manual intervention is necessary to prevent excessive token usage from repeated unsuccessful attempts by the AI to fix the problem. More insights into efficient token usage and using Bolt most effectively can be found [here](https://github.com/stackblitz/bolt.new/issues/678).
