### ISSUE TITLE
Chats Do Not Populate on Other Devices

### ISSUE THREAD

**Issue by Mhinolv** [stackblitz/bolt.new#1699]
### Describe the bug

I created two chats using bolt.new on my PC. When I logged in with my laptop however, I noticed that my chats were not available, and I was unable to continue work.
<img width="1503" alt="Bolt New" src="https://github.com/user-attachments/assets/6a3d941b-fde5-40d2-b57d-4f17488f900c">

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

1. Used Chrome and Safari private browsing to log into Bolt.new
2. Checked chat history on both browsers
3. Ensured was using correct account on both instances

### Expected behavior

I was expected my chat history to appear as I have seen on other tools of similar nature.

### Platform

- OS: [MacOS]
- Browser: [e.g. Chrome, Safari]

**Comment by endocytosis** [comment]
Hi @Mhinolv, 

Appreciate the feedback. We are aware of this issue and are tracking current workarounds plus ongoing developments here: #39
