### ISSUE TITLE
Missing both chat history and edit old prompts

### ISSUE THREAD

**Issue by choephix** [stackblitz/bolt.new#17]
Losing my chat history after refreshing the page, as well as not being able to edit previous prompts (effectively branching the chat into a tree) make this unusable for anything meaningful/important. The AI is prone to messing up or deleting important code, especially with comments like "// ... the rest of your code remains unchanged ..." replacing it in files. This is expected from LLMs of course, but having no way to undo this after refresh is insane.

Other than that, I'm in love :)

**Comment by KwintenP** [comment]
Keeping chat history is indeed an important feature. We have made some initial decisions in order to get to MVP asap and still save the amount of tokens it would cost to do things.

This is on our roadmap and will be addressed soon though.

**Comment by mauriciorubio2** [comment]
This is probably the Number 1 Issue with Bolt right now. Who wants to lose hours of work? Or login to see their builds/app disappear? It's a major problem: https://github.com/stackblitz/bolt.new/issues/160

The sad thing about this is I had built one of my apps to the state where I was actually happy with what I was seeing. Something Replit, Cursor and v0 failed to do.

**Comment by kc0tlh** [comment]
@choephix Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #39!
