### ISSUE TITLE
Throughout generation, bolt suddenly didn't include the previous output anymore

### ISSUE THREAD

**Issue by hybridherbst** [stackblitz/bolt.new#170]
### Describe the bug

The first few generations went really well, but then at some point the page stayed white.
The cause seems to have been that the code included something like
```
/* all the previous App.tsx stays the same */
```
instead of the actual content of the App.tsx.

After that, on the next generation, bolt seems to have lost all context of how the app looked – suddenly it had a new design and the functionality was broken.

(I ran out of tokens then, so couldn't test if it would "recover")

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n12fxh

### Steps to reproduce

See above

### Expected behavior

Not losing context in the middle of a session

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100081714,
  "usedJSHeapSize": 93696642,
  "jsHeapSizeLimit": 4294705152
}
Username = hybridherbst
Chat ID = 2d3d5ce7997b
```

**Comment by kirjavascript** [comment]
Hey! Sorry for this issue, this is something we hope to land soon!

We're tracking this internally. You can follow https://github.com/stackblitz/bolt.new/issues/124 to get notified when we've resolved this issue.

**Comment by pk-pathkraft** [comment]
i am also facing the same issue, i am building a WordPress plugin 

initial prompts went find till a few versions, i was slowly prompting and adding more features, but after a while bolt started loosing the context , after inspection of the code i found that the main files the code were missing after a point of time and i was seeing this

// ... (rest of the code remains the same)

Which explains why there were errors and functionality loss, i tried various prompts to evade this loop
but not very successful , tried with prompts " rewrite the complete code " but the its going out of context and desired code output is not there.

i am a paid user, i Lost a of lot of tokens and time trying to come over this issue, for the time being i have halted this particular plugin development work , till i find a solution

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
