### ISSUE TITLE
All my chats are gone 

### ISSUE THREAD

**Issue by HolmBIM** [stackblitz/bolt.new#1709]
### Describe the bug

All my chats are gone!!!

### Link to the Bolt URL that caused the error

All my chats are gone!!!

### Steps to reproduce

All my chats are gone!!!

### Expected behavior

All my chats are gone!!!

### Screen Recording / Screenshot

All my chats are gone!!!

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

All my chats are gone!!!

**Comment by endocytosis** [comment]
Hi @HolmBIM, 

Current workarounds and upcoming solutions are being tracked here: #39.
