### ISSUE TITLE
Netlify deployment issue

### ISSUE THREAD

**Issue by fizex** [stackblitz/bolt.new#1710]
### Describe the bug

I claimed the Netlify site but now Bolt keeps deploying to a new (wrong Netlify site) and there doesn't seem to be a way to update it's deployment settings.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hfe3ug

### Steps to reproduce

Deploy a site
Claim the site
Deploy the site again (will deploy a totally new site rather than linking to the claimed one)
Try to get Bolt to fix this (it will not be able to change it)

### Expected behavior

I should be able to get it to deploy to the site that I claimed.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pure6777** [comment]
it is refusing to deploy

**Comment by pure6777** [comment]
help me

**Comment by endocytosis** [comment]
Hi @fizex, 

Appreciate the feedback. The team is aware of this feature request and it is being tracked [here](https://github.com/stackblitz/bolt.new/issues/49) along with some potential workarounds.
