### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by yschaub** [stackblitz/bolt.new#1713]
### Describe the bug

this is like the 100th time that after creating a new bolt, the screen is just blank. i tell it ot fix it but nothing ever works

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uxahch

### Steps to reproduce

a

### Expected behavior

a

### Screen Recording / Screenshot

a

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87233011,
  "usedJSHeapSize": 79628107,
  "jsHeapSizeLimit": 4294705152
}
Username = yschaub
Chat ID = 868be74f5ea2
```

### Additional context

a

**Comment by endocytosis** [comment]
Hi @yschaub, 

Appreciate the feedback. We are tracking this issue regarding a white preview screen after code changes here: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
