### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by monnyahmeti** [stackblitz/bolt.new#1717]
### Describe the bug

npx next build error showing after I clicked Deploy button.
Building error.
An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4ojvdc

### Steps to reproduce

Click Deploy , 
Fix building error
Deploy to netlify

### Expected behavior

Bulding the project and deploy in Netlify

### Screen Recording / Screenshot

![Capture](https://github.com/user-attachments/assets/19db21f4-f53c-41fe-a7a3-23441ce4f937)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67321317,
  "usedJSHeapSize": 63692445,
  "jsHeapSizeLimit": 4294705152
}
Username = moniahmeti
Chat ID = 64a48bb7f6cd
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @monnyahmeti, 

Appreciate the feedback! We are aware of this issue and tracking it here: #1022.
