### ISSUE TITLE
bolt.new and git

### ISSUE THREAD

**Issue by davidmoshal** [stackblitz/bolt.new#172]
<img width="551" alt="Screenshot 2024-10-07 at 1 49 09 PM" src="https://github.com/user-attachments/assets/270cfecd-a5b1-4725-847e-a54cd5ca2ebd">
### Describe the bug

Hi, I'm trying to connect bolt.new with git.
Here is what I tried:
- exported the project from bolt.new as a zip
- created a github repository and pushed that unzipped project to github
- imported the project in stackblitz
- asked bolt.new what I should do:
- it advised me to replace the stackblitz.com in the url with bolt.new 
- but I was told I don't have access to that repo

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/davidmoshal/au2410-bolt-1?file=package.json

### Steps to reproduce

not applicable

### Expected behavior

firstly I expected to be able to connect bolt.new with github.    
failing that: I expected to be able to open a stackblitz project with bolt.new.  
particularly and this was a project exported from bolt.new, pushed to github, and imported into stackblitz

### Screen Recording / Screenshot

not applicable

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52901466,
  "usedJSHeapSize": 43805986,
  "jsHeapSizeLimit": 4294705152
}
Username = davidmoshal_4vzu
Chat ID = 76d54b8d08a1
```

### Additional context

not applicable
<img width="551" alt="Screenshot 2024-10-07 at 1 49 09 PM" src="https://github.com/user-attachments/assets/cdf9a92c-ffd1-464c-9065-63f273494c8a">

**Comment by boudewijndanser** [comment]
Is your repo public? Think it needs to be for import.

**Comment by kirjavascript** [comment]
The project at https://github.com/davidmoshal/au2410-bolt-1 doesn't seem accessible.

Could you make it public and try again?

**Comment by davidmoshal** [comment]
it's public now
when I open in stackblitz there is no option to open in bolt.
so: this project started on bolt, was exported to stackblitz and then to github, but now can't be opened in bolt again!

**Comment by kc0tlh** [comment]
Clicking the link your provided now results in a successful import of the repo to Bolt as shown below. Marking this issue resolved.

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/9ca9a0e4-7579-40c7-9074-5c01d5da7b46">

**Comment by christhomas** [comment]
you would need to create a key in your github repo and then update bolt to support setting this parameter in a way that git is allowed to access the repository. I think right now this is not possible.

**Comment by kc0tlh** [comment]
@u007 private repos are not currently supported in Bolt

**Comment by Veeeetzzzz** [comment]
> @u007 private repos are not currently supported in Bolt

![image](https://github.com/user-attachments/assets/f414ca13-7c4e-4717-9618-9065c89b9bb8)

This seems to suggest otherwise but I understand this is being looked at under https://github.com/stackblitz/bolt.new/issues/95

I just tested this with a public repo and it worked fine whereas it had trouble importing a private repo - so looks like if you want to import into Bolt, fork your private repo and work from there or make your original repo public.
