### ISSUE TITLE
ALL CHAT HISTORY GONE 

### ISSUE THREAD

**Issue by iamabroor** [stackblitz/bolt.new#1720]
### Describe the bug

all my chat history is gone when i upgraded my plan. from all chats. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-e5bcbh

### Steps to reproduce

just upgraded to a paid plan

### Expected behavior

chat history to be saved

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/b642544c-9551-4746-b598-671e1fec4684)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @iamabroor, 

Current workarounds and upcoming solutions are being tracked here: #39.
