### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by oak8513** [stackblitz/bolt.new#1722]
### Describe the bug

I have deployed my "task tracker game foundation" to netlify.app and a custom domain at thegoalcrusher.com. However when I make a change to the code with bolt.new and deploy it does not update on the custom domain. I have instructed bolt to use site id 5d1b027a-c35b-408a-a1e8-a40ef15a83f2. But still no luck. Am I missing something?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aavpbj

### Steps to reproduce

deploy site
wait for custom domain to update

### Expected behavior

deployed changes appear at custom domain thegoalcrusher.com

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93627111,
  "usedJSHeapSize": 86834559,
  "jsHeapSizeLimit": 4294705152
}
Username = help@yorkcomputer.net
Chat ID = 472dee3ec159
```

**Comment by endocytosis** [comment]
Hi @oak8513, 

Appreciate the feedback here! The team is aware of the issue which is currently being tracked here along with potential workarounds: #49.
