### ISSUE TITLE
Bug: Bolt changes not reflected in StackBlitz

### ISSUE THREAD

**Issue by MattVOLTA** [stackblitz/bolt.new#1726]
### Describe the bug

All changes being lost when I open a bolt project in stackblitz

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vite-react-wiqhe5

### Steps to reproduce

Please watch video

### Expected behavior

No changes in bolt are being carried over to stackblitz

### Screen Recording / Screenshot

https://us06web.zoom.us/clips/share/IBMT4aRMaqEKHT1CSirlyq9AAjw0XhJfqGpwUcU1LYMlYOHPGZtkHxyzvH3xmCNtfr-qBREg-p6SVXQSONDoP0tl.qQTdA-vOsuRWwLaZ

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 104496601,
  "usedJSHeapSize": 84566929,
  "jsHeapSizeLimit": 4294705152
}
Username = MattVOLTA
Chat ID = 1bb32c832e9e
```

**Comment by kc0tlh** [comment]
@MattVOLTA thanks for the report! Currently we are not seeing this behavior for other users, but your bolt changes absolutely SHOULD be syncing to StackBlitz, so this is strange. Some troubleshooting questions:
- Are you experiencing this with other projects ro just this one?
- What about in Chrome incognito?

Thanks for the support as we work to stabilize the platform!

**Comment by endocytosis** [comment]
Going to merge this with issue #1954 as multiple users have observed this behavior.
