### ISSUE TITLE
Unable to Add Anthropic API Key

### ISSUE THREAD

**Issue by frice8** [stackblitz/bolt.new#1731]
### Describe the bug

The platform is unable to successfully add the api key for anthropic. I am have the same issue on multiple applications. it just tries over and over and just wastes credits, IMO.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xsbjjw

### Steps to reproduce

Juat ask to add your API key and provide it.

### Expected behavior

it work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89359851,
  "usedJSHeapSize": 70877795,
  "jsHeapSizeLimit": 4294705152
}
Username = frice8
Chat ID = 9d7fced762e1
```

### Additional context

I don't have any, just want to see the api key get implemented successfully. All I'm trying to get it to do is add an AI chat bot, it seems to add everything for it to function but never works with the api key

**Comment by endocytosis** [comment]
Hi @frice8, 

Advice on increasing token usage efficiency can be found here: #678, which can be especially crucial if the LLM is repeatedly unsuccessful at generating particular code. Another option would be to open the Bolt project in StackBlitz (click Open In StackBlitz in the top right) and continue development there, following these [instructions](https://support.anthropic.com/en/articles/9767949-api-key-best-practices-keeping-your-keys-safe-and-secure) from Anthropic.
