### ISSUE TITLE
Couldn't import my github repo

### ISSUE THREAD

**Issue by zilla-hue** [stackblitz/bolt.new#1733]
### Describe the bug

Got the following message when i tried to import my github repo on bolt.new ```You don't have access to the repository```

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/zilla-hue/nis

### Steps to reproduce

1. Go to where you type in url and type bolt.new/~/github.com/zilla-hue/nis

### Expected behavior

I expected bolt.new to load my repo

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 134905306,
  "usedJSHeapSize": 126001682,
  "jsHeapSizeLimit": 2160066560
}
Username = zilla-hue
Chat ID = 1de36d0234b6
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by zilla-hue** [comment]
The repository was set to private

**Comment by endocytosis** [comment]
Hi @zilla-hue, 

Is this a private repository? Currently, Bolt does not support importing private repositories, but this feature is in development. However, private StackBlitz projects are supported.
