### ISSUE TITLE
Charging me for issues that never get resolved

### ISSUE THREAD

**Issue by fmehlinger** [stackblitz/bolt.new#1734]
### Describe the bug

Whenever it doesn't complete a task and I have to submit my prompt again, it keeps charging me for those tasks, which isn't fair. It's done this to me at least 20 times in the last 2 days and I've had to buy more because it kept asking me to redo things. That's not fair to end users at all. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-onfesr

### Steps to reproduce

Not sure what this means, I was entering in a prompt to fix my code and it paused for nearly 5 minutes and then asked me to do the prompt again and is charging me each time

### Expected behavior

I shouldn't be charged for tasks that aren't performed. That's unfair to us end users. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 246897469,
  "usedJSHeapSize": 217966421,
  "jsHeapSizeLimit": 4294705152
}
Username = fmehlinger
Chat ID = 1a85e95c4498
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by krischulz** [comment]
I totally agree, spent 16,000,000 tokens on fixing the same set of errors and they weren't fixed.

**Comment by massacretv** [comment]
Same here I get tired of having to fix things 10 times and then im down 7 mill

**Comment by endocytosis** [comment]
Hi all, 

We appreciate your patience as improvements continue to be made, especially regarding token efficiency. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has useful insights on ways to maximize token usage efficiency while we continue to work on improvements.
