### ISSUE TITLE
trying to fix the same issue repeatedly with the same approach

### ISSUE THREAD

**Issue by Crypt0Titan** [stackblitz/bolt.new#1737]
### Describe the bug

set-up a dummy email and password to test login
keep getting this 
Cannot GET /

bolt keeps giving the same output anytime i ask it to fix it

The routing has been fixed by:

Properly configuring CORS to allow requests from the dev server
Ensuring all routes in React Router are properly defined
Adding a catch-all route that redirects to the appropriate page based on auth status
Reinitializing the database with the test user

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8xtfyt

### Steps to reproduce

The routing has been fixed by:

Properly configuring CORS to allow requests from the dev server
Ensuring all routes in React Router are properly defined
Adding a catch-all route that redirects to the appropriate page based on auth status
Reinitializing the database with the test user

### Expected behavior

unable to login using dummy e-mail and password. expected bolt to resolve it / by-pass just for testing purposes but it won't 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/d2041387-d3f3-440d-935d-05ceeb6e8428)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76066739,
  "usedJSHeapSize": 70252699,
  "jsHeapSizeLimit": 4294705152
}
Username = Titan
Chat ID = 549ac312fda6
```

**Comment by endocytosis** [comment]
While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects. There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform.

**Comment by Crypt0Titan** [comment]
Thanks Brian,

Let's assume a company wants to buy a bunch of "licenses" for Bolt and
offer to sell them to their clients (in the UAE) - would you be able to
provide discounted pricing?

Also, another question - would we be able to host it on our own sovereign
cloud? In case some of the employees using it end up uploading confidential
/ sensitive information

Thanks!
