### ISSUE TITLE
No way to undo last change and get back to exact state of files.

### ISSUE THREAD

**Issue by waleedzeb** [stackblitz/bolt.new#174]
### Describe the bug

I asked in chat to undo last change/prompt, it recreated the whole app with different styling and also did not remove files created in last step. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rucefp

### Steps to reproduce

1.  Create a preact app with tailwind styling, 
2. make some form with loading state.
3. ask it to deploy this for non preact project
4. ask it revert previous state.

### Expected behavior

It should have remembered exactly the state of files after 2nd last prompt rather than recreating it with new changed behavior. Asked it to undo last prompt and it recreated a new app with different behaviour.

### Screen Recording / Screenshot

OLD <img width="605" alt="Screenshot 2024-10-08 at 2 05 24 AM" src="https://github.com/user-attachments/assets/feb13b78-9001-43e0-8b9a-79899011af8e"> 

New
<img width="515" alt="Screenshot 2024-10-08 at 2 06 25 AM" src="https://github.com/user-attachments/assets/5b0bc201-69fb-409e-b8f2-dd1d98f7c7bc">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 138223380,
  "usedJSHeapSize": 134458940,
  "jsHeapSizeLimit": 4294705152
}
Username = waleedzeb@gmail.com
Chat ID = f9f78347d7e1
```

**Comment by kirjavascript** [comment]
Hey! Thanks for raising this issue!

We're tracking this internally, and #35 is a similar feature request. I'm going to close this issue, feel free to subscribe for updates in the other issue! We'll keep you posted 🙌
