### ISSUE TITLE
An unknown error occured while running an action

### ISSUE THREAD

**Issue by mitchiem** [stackblitz/bolt.new#1740]
### Describe the bug

IIt wont give me live URL for me to test. It has been working fine until now. Please help

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dws88z

### Steps to reproduce

Juast ask it to fix error and privide link to test and it will gicve you this output "An unknown error occured while running an action"

and not give you the link 

### Expected behavior

It supposed to give me a url/link to the app im trying to buold it wont even do that

### Screen Recording / Screenshot

Video of the error here https://www.awesomescreenshot.com/video/33377538?key=f30ee22cedd6053fd9bdc162dd443915

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110083928,
  "usedJSHeapSize": 97955088,
  "jsHeapSizeLimit": 4294705152
}
Username = mitchiem
Chat ID = 2daeb553c904
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #499.
