### ISSUE TITLE
Prisma

### ISSUE THREAD

**Issue by Ahmed3techcampus** [stackblitz/bolt.new#1741]
### Describe the bug

it have problem working with prisma . steps for install ,migration ,....
my app was next js . i ask him for use prisma . 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rv6x6l

### Steps to reproduce

just review prisma documentation 

### Expected behavior

just he know how work with prisma

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! A potential issue is that https://github.com/prisma/prisma/discussions/18428, which would be necessary for compatibility with Bolt. If you are open to using another database we have instructions on using Firebase [here](https://www.youtube.com/watch?v=1GfqnOAKr9M).
