### ISSUE TITLE
No 'Claim project' URL generated during Deploy

### ISSUE THREAD

**Issue by awelcing-alm** [stackblitz/bolt.new#1742]
### Describe the bug

When deploying to Netlify, sometimes the URL that allows you to claim the project does not get provided. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-shadcn-lettft

### Steps to reproduce

1. Click Deploy
2. Sometimes, the claim URL is not generated.

### Expected behavior

On a Deploy, the claim project URL should always be provided.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141835223,
  "usedJSHeapSize": 119962927,
  "jsHeapSizeLimit": 4294705152
}
Username = awelcing-alm
Chat ID = 26be597ad983
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are trakcing it here: #2020
