### ISSUE TITLE
Save chat history

### ISSUE THREAD

**Issue by neil-h** [stackblitz/bolt.new#1743]
If I go to bolt.new, and select my project from under "Your Chats", it doesn't actually load the former chat. It simply says:

> I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

I can't see anywhere to access my actual chat history. There also didn't appear to be anywhere to download it while I was using it initially. I had actually considered using the browser dev tools to download it so I could show it to my coworkers, but I assumed it would be there for them if I shared the project link.

The context is important.

**Describe the solution you'd like:**

I'd like chat to be saved and loaded with the project every time it's opened.

If that would be an issue for how the AI functions, it would be acceptable to have the chat saved elsewhere so it was viewable by the user.

**Describe alternatives you've considered:**

I considered using my web browser's dev tools to copy the sidebar's HTML element. You can imagine this isn't exactly convenient.

**Comment by endocytosis** [comment]
Hi @neil-h, 

Appreciate the feedback here! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39.
