### ISSUE TITLE
prisma

### ISSUE THREAD

**Issue by Ahmed3techcampus** [stackblitz/bolt.new#1744]
### Describe the bug

prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/605197351a3c8bdd595af2d2a9bc3025bca48ea2/debian-openssl-1.1.x/libquery_engine.so.node.gz.sha256 failed, reason: socket hang up

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rv6x6l

### Steps to reproduce

this error happened when 
npx prisma generate

### Expected behavior

execute without error

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67073155,
  "usedJSHeapSize": 60316107,
  "jsHeapSizeLimit": 2197815296
}
Username = Ahmed3techcampus
Chat ID = 387ceadedb31
```

**Comment by endocytosis** [comment]
Appreciate the feedback! A potential issue is that [Prisma does not currently compile to Wasm](https://github.com/prisma/prisma/discussions/18428), which would be necessary for compatability with Bolt. If you are open to using another database we have instructions on using Firebase [here](https://www.youtube.com/watch?v=1GfqnOAKr9M).
