### ISSUE TITLE
Netlify delployment error

### ISSUE THREAD

**Issue by jhillbht** [stackblitz/bolt.new#1747]
### Describe the bug

I haven't been able to create the Netlify preview link this week. I have previously used it successfully but at some point last week it stopped working.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sdm8kn

### Steps to reproduce

Creat preview with Netlify

### Expected behavior

A link similar to 
https://relaxed-blancmange-91b99d.netlify.app/

### Screen Recording / Screenshot

<img width="540" alt="Screenshot 2024-11-07 at 1 50 04 PM" src="https://github.com/user-attachments/assets/169eab7c-5131-45fd-9180-9da8f5bd9146">

### Platform

```
Browser name = Chrome
Full version = 124.0.0.0
Major version = 124
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 104808268,
  "usedJSHeapSize": 97322364,
  "jsHeapSizeLimit": 4294705152
}
Username = jhillbht
Chat ID = 5e5ca95950f7
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Hi @jhillbht, 

Appreciate the feedback! The team is aware of this issue and tracking it here: #499.
