### ISSUE TITLE
 prompt is too long: 202128 tokens > 200000 maximum

### ISSUE THREAD

**Issue by davidpreid** [stackblitz/bolt.new#1748]
### Describe the bug

One line Prompt gives this error and I'm loosing tokens!
prompt is too long: 202128 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-y86rgx

### Steps to reproduce

Type any prompt and it gives the error

### Expected behavior

The AI to work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67400484,
  "usedJSHeapSize": 54493868,
  "jsHeapSizeLimit": 4294705152
}
Username = davidpreid
Chat ID = 760029901509
```

### Additional context

Tried Edge and Chrome same result

**Comment by Trisfidel** [comment]
@davidpreid: Please refer to this thread to find explanations (NOT ANSWERS!) for this issue.

**Comment by kc0tlh** [comment]
@davidpreid as @Trisfidel mentions, this issue, and some workarounds, are being tracked in #1322. Closing this issue as duplicate.
