### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by REPYYC** [stackblitz/bolt.new#1754]
### Describe the bug

I can't seem to build this one out

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-giryxh

### Steps to reproduce

just try to deploy

### Expected behavior

deployed site

### Screen Recording / Screenshot

n/a 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 227021366,
  "usedJSHeapSize": 220947246,
  "jsHeapSizeLimit": 4294705152
}
Username = REPYYC
Chat ID = c12377b6bc99
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #499.
