### ISSUE TITLE
preview page is blank

### ISSUE THREAD

**Issue by oliviajiang1989** [stackblitz/bolt.new#1755]
### Describe the bug

the preview page is blank with no show

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ddxsc2?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=sidebar

### Steps to reproduce

after chating to bolt and created a website , the preview page is blank with no show

### Expected behavior

the preview page is blank with no show

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @oliviajiang1989, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
