### ISSUE TITLE
Cannot Deploy

### ISSUE THREAD

**Issue by jasontaken1** [stackblitz/bolt.new#1757]
### Describe the bug

I'm unable to deploy this project. Please assist.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qamggg

### Steps to reproduce

try to deploy the app

### Expected behavior

deploy

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69436754,
  "usedJSHeapSize": 66379794,
  "jsHeapSizeLimit": 4294705152
}
Username = jasontaken
Chat ID = d8183ba6cf77
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @jasontaken1, 

The team is aware of this issue with deployment and it is being tracked here: #1022.
