### ISSUE TITLE
MY CHAT PROJECTS WERE DELETED!!!! MY PROJECT ITS LOST!

### ISSUE THREAD

**Issue by sitatel** [stackblitz/bolt.new#1758]
### Describe the bug

mY CHAT PROJECTS WERE DELETED!!!! MY PROJECT ITS LOST!

### Link to the Bolt URL that caused the error

CHECK MY ACCOUNT

### Steps to reproduce

I DONT SEE MY CHATS

### Expected behavior

I DONT SEE MY CHATS

### Platform

- OS: [e.g. macOS, Windows, Linux] IM USING WINDOWS
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ShahbazBaloch515** [comment]
same

**Comment by endocytosis** [comment]
Hi all, 

The team is aware of this issue with persistence. You should be able to find your project by following the workaround outlined here: #39. Navigate to StackBlitz (stackblitz.com), login with the same credentials as bolt.new, click Collections on the left-hand side of the page, then click Bolt Collection.
