### ISSUE TITLE
Bolt Replacing files and not completing coding

### ISSUE THREAD

**Issue by PattayaCreativeCode** [stackblitz/bolt.new#1759]
### Describe the bug

Bolt is using // Rest of code stays the same 
And by doing that destroying original design as later on he does not know how to put it back as it was.

### Link to the Bolt URL that caused the error

Does not matter it does it everywhere

### Steps to reproduce

In the beginning all good, but making big projects it does the same Claude.AI does 

### Expected behavior

You guys need to fix that.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! Improvements continue to be made to improve AI model performance. Issue #678 has some excellent insights into prompting Bolt most effectively. Additionally, if you right-click a file in the Bolt code editor and select "Lock file", this will prevent the AI from making additional changes to that file.
