### ISSUE TITLE
Not able to Deploy.

### ISSUE THREAD

**Issue by Sai-Prashanth-Banda** [stackblitz/bolt.new#1761]
### Describe the bug

It's not deploying my application.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hic6cp

### Steps to reproduce

It's not deploying my application.

### Expected behavior

It's not deploying my application.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/08488ed7-ff4b-42aa-9b02-08c1509c7856)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 119150389,
  "usedJSHeapSize": 110605325,
  "jsHeapSizeLimit": 4294705152
}
Username = saiprashanthbanda
Chat ID = b52d36800d6c
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @Sai-Prashanth-Banda, 

Appreciate the feedback. The team is aware of this issue with deployment which is being tracked here: #1022.
