### ISSUE TITLE
</content> being randomly added at the end of code

### ISSUE THREAD

**Issue by steroman** [stackblitz/bolt.new#1763]
### Describe the bug

When the app is updating a piece of code, it sometimes appends `</content>` at the end, causing the app to break.

![Screenshot 2024-11-08 at 08 18 31](https://github.com/user-attachments/assets/a92c8378-e776-4be3-be26-1b67991789b1)
![Screenshot 2024-11-08 at 08 18 22](https://github.com/user-attachments/assets/688d0fe1-5540-47a5-95d3-914ddf552e86)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xklueg

### Steps to reproduce

1. Ask for an update
2. Let the app work
3. Look at the new code added

The new code ends with `</content>`

### Expected behavior

1. Ask for an update
2. Let the app work
3. Look at the new code added

The new code doesn't end with `</content>`

### Platform

- OS: [MacOS]
- Browser: [Chrome]
- Version: [Version 130.0.6723.70 (Official Build) (x86_64)]

**Comment by steroman** [comment]
I also asked this:

>  Also, moving forward, could you please stop randomly appending  at the end of the updated code?

But it keeps doing it.

**Comment by endocytosis** [comment]
When the AI makes repeated errors it is best to intervene manually, as repeated requests to fix the error can result in excessive token consumption. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on ways to work most effectively with the LLM. Hope this helps!
