### ISSUE TITLE
not able to fix my issue

### ISSUE THREAD

**Issue by thedbadmin** [stackblitz/bolt.new#1766]
### Describe the bug

Bolt has build my app but its not able to fix this issue from long time. after giving all possible details

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qfkezn

### Steps to reproduce

just give this prompt "Failed to generate data. The operation exceeded system limits. Please reduce the number of records or fields in your request. Additionally, review the application logic for potential issues in data handling and processing."

### Expected behavior

it should generate mock data

### Screen Recording / Screenshot

![Screenshot 2024-11-08 141149](https://github.com/user-attachments/assets/72437def-fcf9-4008-85a2-69ac07ff8efd)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106371588,
  "usedJSHeapSize": 82272464,
  "jsHeapSizeLimit": 4294705152
}
Username = thedbadmin
Chat ID = a10f22cd7913
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve and manual intervention is required. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency.
