### ISSUE TITLE
Application won't deploy and the error message doesn't tell me why

### ISSUE THREAD

**Issue by rundm73** [stackblitz/bolt.new#1767]
### Describe the bug

I have built a simple app and everytime try and deploy it I get the attached message which doesn't tell me what the error is so I can't fix it. 
<img width="369" alt="image" src="https://github.com/user-attachments/assets/4e036642-3716-40b6-a1f1-c3d4a1d5fb18">
<img width="369" alt="Screenshot 2024-11-08 090923 Bolt error" src="https://github.com/user-attachments/assets/5dfe6815-bf9e-4164-8ca0-4e6ba21c6caa">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dusxzx

### Steps to reproduce

1. build any app 
2. fix errors
3. try to deploy using the default Netlify

### Expected behavior

I expected to be presented with the netlify URL for the app 

### Screen Recording / Screenshot

<img width="369" alt="Screenshot 2024-11-08 090923 Bolt error" src="https://github.com/user-attachments/assets/a08d067a-f73c-4e55-b7d8-f47e9110e9bf">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80217633,
  "usedJSHeapSize": 71952209,
  "jsHeapSizeLimit": 2160066560
}
Username = rundm73
Chat ID = f68e2b562c4c
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1022.
