### ISSUE TITLE
Previous projects

### ISSUE THREAD

**Issue by realmattross** [stackblitz/bolt.new#1768]
Previous projects I can't find projects that I was working on yesterday-help!

**Comment by Obax2050** [comment]
i lost my project olso

**Comment by endocytosis** [comment]
Hi all, 

The team is aware of this issue and tracking it here: #39. Are you able to find your projects by following the instructions there?

**Comment by realmattross** [comment]
Yes! Thanks

Matt Ross
07379333526

**Comment by endocytosis** [comment]
@realmattross, you're welcome!
