### ISSUE TITLE
problem bolt.new 

### ISSUE THREAD

**Issue by un9er** [stackblitz/bolt.new#1772]
after the bugs were removed, all projects with other work 
at the same time, 3.2 million tokens and a lot of time were spent
please elaborate on the problem

**Comment by Obax2050** [comment]
I lost my project so

**Comment by Obax2050** [comment]
you can find your project back if you go to `Collections > Bolt collection` on [http://stackblitz.com]

**Comment by endocytosis** [comment]
Yes, issues with chat persistence are being tracked here: #39. Projects can be found by logging into StackBlitz with the same credentials as Bolt, navigating to Collections on the left-hand side of the page, and then clicking Bolt Collection.
