### ISSUE TITLE
Missing Application History and Disappearing Project

### ISSUE THREAD

**Issue by hsnpai** [stackblitz/bolt.new#1774]
### Describe the bug

Dear Bolt.New Support Team,

I am writing to report an issue I encountered with the platform.

Issue Description:
Registration and Application Creation: I successfully registered on Bolt.New and created an application using the AI.
Token Subscription: I subscribed with 26M tokens and spent approximately 6 hours and 1,200,000 tokens building my project.
Problem Encountered: When I returned the following day to complete my work, I discovered the following:
The application history and backup records were missing.
The project has disappeared entirely from my conversation with the AI, and I am unable to locate it anywhere in my account.
This has resulted in a significant loss of time and resources, and I would greatly appreciate any assistance you can provide in recovering the project or identifying the root cause of this issue.

Thank you for your attention to this issue.

Best regards,

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Steps to Reproduce:
Register and create an application with the AI.
Subscribe with tokens and spend a substantial amount of time and tokens building the application.
Return after several hours to find the application history and project missing.
Additional Information:
Subscription Amount: 26M tokens
Tokens Spent: 1,200,000 tokens oSubscription Amount: 26M tokens

### Expected behavior

The application history and backup records should be available, and the project should remain accessible in my conversation with the AI.

### Screen Recording / Screenshot

N/A

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Tokens Spent: 1,200,000 tokensver 6 hours
I look forward to your prompt resolution of this matter, as the work and tokens spent are critical to my ongoing efforts.

**Comment by rizvinewed** [comment]
ya same haapend just now with me

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback here and apologies for the frustration this has caused. The team is aware of this issue with chat persistence. Temporary workarounds and updates can be found here: [#39].  As described there, you should be able to locate your Bolt projects in your StackBlitz account by navigating to Collections (left-hand side of the page at stackblitz.com, same login as bolt.new), then Bolt Collection. 

Appreciate your patience as improvements continue to be made.
