### ISSUE TITLE
all chat gone

### ISSUE THREAD

**Issue by rizvinewed** [stackblitz/bolt.new#1775]
i purchased an plan pro 50 and used almost all credits and working on the application, and all chat gone, and please give teh credit back and posisble chat back

**Comment by dubtor** [comment]
my chat (i.e. my projects) also disappeared right now. i hope it comes back. i am already on the paid plan

**Comment by dubtor** [comment]
@EricSimons I hope you guys can restore my projects, already invested a substantial amount of time. Thanks a lot!

**Comment by endocytosis** [comment]
Hi all, 

We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. Appreciate your patience as improvements continue to be made.

**Comment by rizvinewed** [comment]
it's worked i had chats and i got throught stackblitz ,

**Comment by endocytosis** [comment]
Great, glad to hear it!
