### ISSUE TITLE
Progress lost after page refresh

### ISSUE THREAD

**Issue by eyichan** [stackblitz/bolt.new#1776]
### Describe the bug

After refreshing the interface, you cannot return to previously modified nodes and can only debug again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uyimjr

### Steps to reproduce

After refreshing the interface, you cannot return to previously modified nodes and can only debug again.

### Expected behavior

After refreshing the interface, you cannot return to previously modified nodes and can only debug again.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110388449,
  "usedJSHeapSize": 88089621,
  "jsHeapSizeLimit": 4294705152
}
Username = eyichan
Chat ID = 7ab86b5489f3
```

**Comment by Obax2050** [comment]
you can find your project back if you go to `Collections > Bolt collection` on [http://stackblitz.com]

**Comment by endocytosis** [comment]
We are tracking this persistence issue here: #39.
