### ISSUE TITLE
My Bolt project is not saving

### ISSUE THREAD

**Issue by ogoudge** [stackblitz/bolt.new#1778]
### Describe the bug

I had a project shared with me I made lots of changes and realized it was not updating on stackblitz. In the meantime the site went down. I am still able to edit as long as I don't close my browser I tried to open the project with the URL in another browser and it cant find it.

I did manage to get my project downloaded and on git and imported into Stackblitz but not sure how to get it back into bolt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-maj64w

### Steps to reproduce

Gone into stack verified its not updating removed it since its old and it still not saving.

### Expected behavior

Save my changes. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 54297918,
  "usedJSHeapSize": 51773102,
  "jsHeapSizeLimit": 4294705152
}
Username = ogoudge
Chat ID = aaaf59f36c87
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Hi @ogoudge, 

Appreciate the feedback. Chat persistence is a known issue and is being tracked here: #39. You should be able to find your Bolt projects by navigating to stackblitz.com, clicking Collections on the left-hand side, and then opening the Bolt Collection.

Additionally, full GitHub integration is an area of ongoing development and only public GitHub repositories are currently supported. A potential workaround is creating a private StackBlitz native project as follows:

- Download your GitHub repo 
- Create an empty StackBlitz project
- Drag and drop your GitHub project files into the StackBlitz filesystem, save, and then use the “Open in Bolt” button to work on the project in Bolt

It is important to be aware that Bolt cannot support very large codebases, so this is only recommended for small projects.
