### ISSUE TITLE
Deployment of application is showing error

### ISSUE THREAD

**Issue by AntonWir** [stackblitz/bolt.new#1781]
### Describe the bug

Tried to deploy the project many times, used a lot of tokens:

Error message: 
An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kkbjzb

### Steps to reproduce

1. go to "deploy"
2. after processing...An error occured while streaming this message.

### Expected behavior

deployment of application

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77140606,
  "usedJSHeapSize": 71435538,
  "jsHeapSizeLimit": 2182610944
}
Username = AntonW
Chat ID = c6129a79dcfe
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by endocytosis** [comment]
Hi @AntonWir, 

We are aware of this issue that occurs during deployment and are tracking it here: #1022.
