### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by amsartawi3** [stackblitz/bolt.new#1783]
### Describe the bug

It happened twice, meaning i am losing tokens

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qf4995

### Steps to reproduce

just from my first prompt it was stuck halfway of creating the website

### Expected behavior

complete generating code until all components finished

### Screen Recording / Screenshot

<img width="2240" alt="Screenshot 2024-11-08 at 22 13 46" src="https://github.com/user-attachments/assets/0e56b40a-6ec6-4016-99bf-3a5bea9b34d9">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110593509,
  "usedJSHeapSize": 103887281,
  "jsHeapSizeLimit": 4294705152
}
Username = amsartawi3
Chat ID = f4e7bab1e63b
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.
