### ISSUE TITLE
‌‌The price is too expensive, can we start the Black Friday activity?

### ISSUE THREAD

**Issue by kankanai** [stackblitz/bolt.new#1784]
‌‌‌A single conversation consumes 50,000 tokens, hoping it can be more cost-effective, so that I can consider purchasing more token packages.

**Comment by endocytosis** [comment]
Hi @kankanai, 

The team continues to make improvements to improve token efficiency. The issue being tracked [here](https://github.com/stackblitz/bolt.new/issues/1322) describes progress on this as well as tips to improve token efficiency.
