### ISSUE TITLE
Stuck at Npm install

### ISSUE THREAD

**Issue by GeekAp09** [stackblitz/bolt.new#1786]
![Screenshot (636)](https://github.com/user-attachments/assets/100b5270-3a6f-4d4f-bfa9-68000a9a6b2c)
### Describe the bug

- the chat is stuck at at `npm install` and the installing isn't progressing .
- No resolving even after refreshing

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bemnfw

### Steps to reproduce

Just Started an app and made a simple prompt

```
make a modern leetcode like code editor where there is one side problem desc and editor on the other side and below is the output of the code and also make buttons like run code ,test code and should be a transition and effect rich app with modern color and the code editor should be using monaco editor and the styling should be in plain css and the theme should be minimalistic and the borders should be realistic
```

### Expected behavior

The package should have installed and the app must have a preview

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52108869,
  "usedJSHeapSize": 48026557,
  "jsHeapSizeLimit": 4294705152
}
Username = GeekAp09
Chat ID = e6873511ea63
```

**Comment by endocytosis** [comment]
Appreciate the feedback here! Here are some things to consider regarding npm load times:

- **Initial Load Times:** npm load times are correlated with overall dependency tree size. The greatest load time is usually during initial project generation as npm modules are installed. Performance improvements continue to be made to reduce load times.
- **Browser Refresh:** If npm continues to hang, refreshing the page usually fixes the problem. However, be aware that doing so will result in losing your current chat history.
- **Browser Compatibility:** Bolt, which [relies on WebContainers](https://webcontainers.io/guides/browser-support#:~:text=WebContainers%20are%20fully%20supported%20in,working%20out%20of%20the%20box.), currently has the greatest support for Chrome and most Chromium-based browsers. Developing in Chrome will likely result in improved performance. We expect support for other browsers to continue to improve.
- **Available System Memory:** As a Bolt project size increases so do local memory (RAM) demands. Ensuring your browser has sufficient memory by closing unnecessary tabs can increase performance.
- **Manual Intervention:** Improved the out of LLMs is an area of active research. As such, the model may not always find the correct or compatible npm module, requiring manual intervention. The terminal window is a good place to look for such errors if Bolt does not automatically detect and offer to resolve them. As working with LLMs is a fluid and evolving process, this page [[here](https://github.com/stackblitz/bolt.new/issues/678)](https://github.com/stackblitz/bolt.new/issues/678) contains numerous insights on leveraging Bolt most effectively while maximizing token usage.

Hope this helps!
