### ISSUE TITLE
Chat history 

### ISSUE THREAD

**Issue by esaghapour** [stackblitz/bolt.new#1787]
### Describe the bug

When I log in from another computer and want to use it, the chat section doesn't show my previous chats on the new computer

### Link to the Bolt URL that caused the error

na

### Steps to reproduce

When I log in from another computer and want to use it, the chat section doesn't show my previous chats on the new computer

### Expected behavior

When I log in from another computer and want to use it, the chat section doesn't show my previous chats on the new computer

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ilyatbn** [comment]
+1 I tried switching browsers and everything disappeared. at the minimum, I'd like to be a be export and import it, or keep the history in a github repo or something.

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback here! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. Appreciate your patience as improvements continue to be made.
