### ISSUE TITLE
Prompt Maxing out at 200K 

### ISSUE THREAD

**Issue by CVO-TreeAi** [stackblitz/bolt.new#1788]
### Describe the bug

Here's a description of the bug with prompt limits:

---

### Description of the Prompt Limit Bug in Bolt

**Summary**:  
When trying to submit prompts in Bolt, we receive an error message stating that the prompt has exceeded the 200k token limit. However, the prompts we are submitting are far shorter—often just a few hundred characters or words. This issue is preventing us from sending even basic instructions to Bolt.

**Details**:  
1. **Error Message**:
   - The error message reads: `"prompt is too long: 200164 tokens > 200000 maximum"`.
   - This message suggests that the prompt exceeds the 200,000 token limit, but in reality, the prompt length is much shorter than that.

2. **Prompt Content**:
   - We are not submitting large or complex prompts. Most prompts are straightforward instructions or queries, typically containing fewer than 500 words.
   - We verified that there are no hidden characters or unusual formatting that could artificially inflate the token count.

3. **Impact**:
   - This bug is severely limiting our ability to use Bolt effectively, as we are unable to submit necessary prompts for project guidance, debugging, and feature enhancements.
   - Breaking down the prompts into smaller chunks only partially mitigates the issue, as even simple prompts are intermittently rejected with the same error message.
   - The issue persists even after clearing cache, restarting sessions, and attempting prompts with minimal text.

4. **Suspected Causes**:
   - This may be a server-side misinterpretation of prompt size or a bug in Bolt’s token-counting algorithm.
   - Another possibility is that the system is mistakenly concatenating previous prompts or metadata into the current prompt, causing the token count to artificially inflate.

5. **Steps to Reproduce**:
   - Open Bolt and enter a simple prompt, e.g., "Install dependencies using `npm install`."
   - Attempt to submit the prompt.
   - Observe that even short prompts are sometimes rejected with the token limit error.

6. **Temporary Workarounds**:
   - We attempted simplifying and shortening prompts further, but this only partially alleviates the issue.
   - No permanent workaround has been identified, as the error persists unpredictably.

---

**Request**:  
Please investigate the token-counting mechanism on Bolt’s server to identify if there’s an error in how prompt sizes are calculated. Additionally, it would help if you could provide more detailed error logs or token count information to aid in debugging. 

Let us know if further information is needed to assist with this report.
<img width="406" alt="Screenshot 2024-11-08 at 9 36 55 AM" src="https://github.com/user-attachments/assets/f38a86bf-0746-4216-a4fa-395fd3895b4a">

### Steps to reproduce

this is cmd A for all the text on the chat 

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-3hu8iy
I've successfully imported your project. I'm ready to assist you with analyzing and improving your code.

Your project has been previously deployed to https://tranquil-conkies-047dd0.netlify.app/.

Initial CRM Project Setup

npm install
npm run dev

Report Issue

Rollback to Checkpoint
how many tokens are availble for this prompt

prompt is too long: 200132 tokens > 200000 maximum

Expected behavior

id expect to be able to input prompts to effect change. 

### Platform

macOS on Chrome. latest versions

Additional context

love the service. thanks

**Comment by kmlacr** [comment]
Its happening me too now i cant build its suck really i bought 200 dolar package and cant use now

**Comment by So3093** [comment]
it general we have to wait it seems

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback. The team is aware of this issue which is being tracked here: #1322. That page includes updates in addition to approaches you can try to improve token efficiency.
