### ISSUE TITLE
Nothing visible in the preview.

### ISSUE THREAD

**Issue by RonakAjwani** [stackblitz/bolt.new#1789]
### Describe the bug

I tried and wasted many tokens and still I cannot see anything in the preview section and also it is complied error free meaning there is no error but still nothing in the preview it's blank. After 1 hour I am getting server error and when I click on the fix the error it is again starting and still no change in preview.
![image](https://github.com/user-attachments/assets/cd6f2621-b133-469b-8db3-2e9b0c9084b1)
And now I am out of token and still cannot see anything. Please look into the matter and also let me know what will happen to my wasted tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5znnxv

### Steps to reproduce

1. Go to the offical website.
2. Then paste this prompt "I am working on a project "Cyber Threat Hunting using LLM". And I want to make a dashboard for this project. Make a proper and detailed dark themed dashboard react or next.js"
3. Then error appears
4. Then I click on the fix the error. It starts updating.
5. Then again same error.
6. I repeated this for atleast 3 to 4 times. Still no response.

### Expected behavior

I except to get my tokens back and also make it smoother and solve the errors shown in the terminal and then run again so that user still has tokens for iterations/modification and is not stuck in the first prompt only.

### Screen Recording / Screenshot

-

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55791682,
  "usedJSHeapSize": 53319822,
  "jsHeapSizeLimit": 2160066560
}
Username = ronakajwani
Chat ID = 8fa37cd739e7
```

### Additional context

-

**Comment by endocytosis** [comment]
Hi @RonakAjwani, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
