### ISSUE TITLE
Expo Project

### ISSUE THREAD

**Issue by codercatdev** [stackblitz/bolt.new#179]
### Describe the bug

I tried converting a bunch of components running in the standard Vite React to Expo and running the project.

I received this back `FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: socket hang up`

```
> expo start

Starting project at /home/project

TypeScript: A tsconfig.json has been auto-generated

Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: socket hang up
```

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jfrps9

### Steps to reproduce

Create an application then convert to expo and run start

### Expected behavior

Expected to be able to run successfully.

### Platform

- OS: macOS
- Browser: Brave
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
Hey @codercatdev!

Ah, I think this is because it's running into a CORS issue. It would work if [https://v0.dev/chat/b/<id>](https://api.expo.dev) was served with Access-Control-Allow-Origin set to * or if returned the origin which sent the request, returning something like https://<unique>.w-credentialless-staticblitz.com/.

We do have a CORS proxy on StackBlitz, but I believe it hasn't been ported over the WebContainer API / Bolt yet. I've added this to our internal issue tracker.

**Comment by jirojirocirociro** [comment]
> Hey @codercatdev!
> 
> Ah, I think this is because it's running into a CORS issue. It would work if https://api.expo.dev was served with Access-Control-Allow-Origin set to * or if returned the origin which sent the request, returning something like https://.w-credentialless-staticblitz.com/.
> 
> We do have a CORS proxy on StackBlitz, but I believe it hasn't been ported over the WebContainer API / Bolt yet. I've added this to our internal issue tracker.

please fix.

**Comment by asssmidt** [comment]
> Hey @codercatdev!
> 
> Ah, I think this is because it's running into a CORS issue. It would work if https://api.expo.dev was served with Access-Control-Allow-Origin set to * or if returned the origin which sent the request, returning something like https://.w-credentialless-staticblitz.com/.
> 
> We do have a CORS proxy on StackBlitz, but I believe it hasn't been ported over the WebContainer API / Bolt yet. I've added this to our internal issue tracker.

Any update on this?

Trying to get around Cors issue with Bolt.new. Seems impossible?

**Comment by VortexxJS** [comment]
yeah getting this issue too when installing prisma.

**Comment by osheenchavhan** [comment]
@kirjavascript , any update on this ?
I am trying to build mobile app using react native and expo not working is ruining the whole thing and I am not able to move forward.
Do you have a workaround for this ?

**Comment by kirjavascript** [comment]
Merging into https://github.com/stackblitz/bolt.new/issues/3164 which has more detail.

**Comment by davidoort** [comment]
Hey @kirjavascript any updates on the timeline for adding this to Webcontainer API? I see in the issue you linked that it's been added to Bolt.new but we're having issues with this in our webcontainers.

**Comment by kirjavascript** [comment]
> Hey [@kirjavascript](https://github.com/kirjavascript) any updates on the timeline for adding this to Webcontainer API? I see in the issue you linked that it's been added to Bolt.new but we're having issues with this in our webcontainers.

I'm afraid there's no decision on when CORS proxy access is going to be added to the WebContainer API yet.

We'll definitely make an announcement when it's available!

**Comment by davidoort** [comment]
Ah okay, thanks for letting me know - for full transparency (and to hopefully bump the urgency on this), this is a blocker preventing us from using Webcontainer API right now and having to go for a Cloud VM approach. We need to be able to use things like `localtunnel` to expose our expo app to devices and run things like `npx convex dev` from the Webcontainer which are both blocked by CORS...

**Comment by kenstack-ltd** [comment]
> Hey [@codercatdev](https://github.com/codercatdev)!
> 
> Ah, I think this is because it's running into a CORS issue. It would work if https://api.expo.dev was served with Access-Control-Allow-Origin set to * or if returned the origin which sent the request, returning something like https://.w-credentialless-staticblitz.com/.
> 
> We do have a CORS proxy on StackBlitz, but I believe it hasn't been ported over the WebContainer API / Bolt yet. I've added this to our internal issue tracker.

Great helps. It works for me.
Thanks a lot @kirjavascript
