### ISSUE TITLE
Bolt again! Five times I have built this app! 

### ISSUE THREAD

**Issue by REBEL33Soul** [stackblitz/bolt.new#1790]
### Describe the bug

Bolt again! Five times I have built this app in the last few weeks! "prompt is too long: 211063 tokens > 200000 maximum". You screwed around with me all day, fixing the same issue over and over for hours! Wasting tokens. I am trying to deploy and you won't let me. The minute I get to that point, I get the error! This is ridiculous! Fix! The! Token! Cap!  Fix, unmistakable lunacy that to you can't go from one chat to another without it being able to link to your work! Fix the agonizingly stupid issue with it lying and saying it can't do something when it already has done it! Fix the issue with the issue with it reloading and not remembering where it was in the process! Fix the issue with no one there to help with issues! Fix the issue with it not doing what you ask and only answering what it wants and doing what it wants! Fix the issue with it following complete instructions! Fix the issue with it eating up tokens for no reason! Fix the issue with it not letting you connect with a GitHub repository to start or resume, working! How many more issues have to occur before you do something! How many people have to complain about the same things before you fix them! Clearly none of you are "Joe on the Street," because you may think your system is easy and perfect, but it's far from it! I am angry, but having said that and waste da lot of money on your system, you still have a great one. Just listen to your users and fix the baloney in the system! Please!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dfc4ry

### Steps to reproduce

Bolt again! Five times I have built this app in the last few weeks! "prompt is too long: 211063 tokens > 200000 maximum". You screwed around with me all day, fixing the same issue over and over for hours! Wasting tokens. I am trying to deploy and you won't let me. The minute I get to that point, I get the error! This is ridiculous! Fix! The! Token! Cap!  Fix, unmistakable lunacy that to you can't go from one chat to another without it being able to link to your work! Fix the agonizingly stupid issue with it lying and saying it can't do something when it already has done it! Fix the issue with the issue with it reloading and not remembering where it was in the process! Fix the issue with no one there to help with issues! Fix the issue with it not doing what you ask and only answering what it wants and doing what it wants! Fix the issue with it following complete instructions! Fix the issue with it eating up tokens for no reason! Fix the issue with it not letting you connect with a GitHub repository to start or resume, working! How many more issues have to occur before you do something! How many people have to complain about the same things before you fix them! Clearly none of you are "Joe on the Street," because you may think your system is easy and perfect, but it's far from it! I am angry, but having said that and waste da lot of money on your system, you still have a great one. Just listen to your users and fix the baloney in the system! Please!

### Expected behavior

To simply work correctly. Not lie. Not eat up tokens. Not hit a very low token cap. Let you connect directly to github to start or resume a project. Do exactly what the user asks and do it completely not just what it wants to do. Remember where you where when it refreshes. Have someone there to help and answer questions.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @REBEL33Soul, 

Appreciate the feedback. We understand that these context window limitations can be frustrating. The team is aware of this issue and is actively working on solutions. Information on this can be found [here](https://github.com/stackblitz/bolt.new/issues/1322) and approaches to improve token usage efficiency can be found [here](https://github.com/stackblitz/bolt.new/issues/678).
