### ISSUE TITLE
a lot of my tokens goes for bad changes that i need to revert 

### ISSUE THREAD

**Issue by Matan693** [stackblitz/bolt.new#1792]
### Describe the bug

a lot of my tokens goes for bad changes that i need to revert 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-phwrca

### Steps to reproduce

123 vdfbdfbdfbdfbdbfbg wdg sd

### Expected behavior

not to take token for rollback code 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96762443,
  "usedJSHeapSize": 87994279,
  "jsHeapSizeLimit": 4294705152
}
Username = Matan693
Chat ID = db8099d782fe
```

**Comment by endocytosis** [comment]
There are some excellent resources in #678 that can help in maximizing token efficiency. The team is hard at work making improvements in model efficiency. We appreciate your patience as improvements are made!
