### ISSUE TITLE
Build Failure During Deployment

### ISSUE THREAD

**Issue by Idrissyau** [stackblitz/bolt.new#1793]
### Describe the bug

# Complaint: Build Failure During Deployment

**Issue:**  
While attempting to deploy the application, I encountered a recurring issue with the build process. The deployment log shows the following error message:

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mfek4a

### Steps to reproduce

# Complaint: Build Failure During Deployment

**Issue:**  
While attempting to deploy the application, I encountered a recurring issue with the build process. The deployment log shows the following error message:

### Expected behavior

I cannot preview or deploy the created app. this is the error I'm receiving: "Failed building the project. Make sure the build command is correct and try again."

### Screen Recording / Screenshot

![deploy](https://github.com/user-attachments/assets/c029dcf3-5c15-414e-8066-9811ec1624e8)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88559710,
  "usedJSHeapSize": 84915498,
  "jsHeapSizeLimit": 2108162048
}
Username = Idrissyau
Chat ID = 02c7737a6f06
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
