### ISSUE TITLE
Failed to deploy Astro project

### ISSUE THREAD

**Issue by 4islam** [stackblitz/bolt.new#1794]
### Describe the bug

Prompt: "need a website blog in Astro with some pages with Next.js and others with Svelte 5. The collections for blog pages will be from md files"

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zmnnrw?gad_source=1&gclid=Cj0KCQiAire5BhCNARIsAM53K1jwltVavVmuvJkpdT2dWLQNl81w9XOWw3jz5VSSycp3UCbHr9CyH5caAldbEALw_wcB

### Steps to reproduce

Write this in prompt: "need a website blog in Astro with some pages with Next.js and others with Svelte 5. The collections for blog pages will be from md files"

### Expected behavior

Create a project with no errors

### Screen Recording / Screenshot

Errors after **npx astro build** command:
11:08:23 AM [vite] Pre-transform error: Failed to load url astro/config (resolved id: astro/config) in /home/project/astro.config.mjs. Does the file exist?
11:08:23 AM [vite] Pre-transform error: Failed to load url @astrojs/next (resolved id: @astrojs/next) in /home/project/astro.config.mjs. Does the file exist?
11:08:23 AM [vite] Pre-transform error: Failed to load url @astrojs/svelte (resolved id: @astrojs/svelte) in /home/project/astro.config.mjs. Does the file exist?
[astro] Unable to load your Astro config

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73057207,
  "usedJSHeapSize": 70035927,
  "jsHeapSizeLimit": 4294705152
}
Username = 4islam
Chat ID = ee18b181cab9
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
