### ISSUE TITLE
20 fixes the take a lot of time and tokens 

### ISSUE THREAD

**Issue by Matan693** [stackblitz/bolt.new#1795]
### Describe the bug

small change that take a lot of fixes and at the end i roll everything back

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-phwrca

### Steps to reproduce

123 4

### Expected behavior

dont write rest of code here, just keep it there

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110929908,
  "usedJSHeapSize": 102275384,
  "jsHeapSizeLimit": 4294705152
}
Username = Matan693
Chat ID = db8099d782fe
```

**Comment by endocytosis** [comment]
Hi @Matan693, 

Appreciate the feedback. Something that might help is that in the Bolt file system you can right-click a file and click "Target file" to have the AI make changes only to that file, or click "Lock file" to prevent a single or multiple (as you can perform this action repeatedly) files from being modified by the AI. Additionally, this page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using the model and tokens most effectively. Hope this helps!
