### ISSUE TITLE
Deploying the changes, should never throw the error : prompt is too long: 203789 tokens > 200000 maximum

### ISSUE THREAD

**Issue by hackertrust** [stackblitz/bolt.new#1798]
### Describe the bug

If the context window is at capacity, it makes sense that Bolt would prevent any additional chats. However, this limitation doesn’t prevent the application from being deployed.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-y8b8ze

### Steps to reproduce

1. When the context window in full.

2. Try to do a final deployment.

3. You will still notice the token issue

### Expected behavior

Deployments should be work even if the window of the AI has reached it's limit

**Comment by endocytosis** [comment]
Hi @hackertrust, 

Appreciate the feedback. The team is aware of this context window issue and it is being tracked here: #1322. That issue page also includes advice on improving token efficiency. When the application is deployed, the LLM performs additional logic to initiate the deployment, which is not possible when the context window is full. A possible solution would be to download the project files (Download button at top of the page next to the title) and build the project locally which can then be deployed.
