### ISSUE TITLE
Deploy doesn't work

### ISSUE THREAD

**Issue by jes** [stackblitz/bolt.new#18]
### Describe the bug

I clicked the "Deploy" button and it ran "npx vite build" successfully but then got a JSON parsing error when trying to deploy to netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wqdoxy

### Steps to reproduce

1. Click "Deploy"
2. Watch the chat
3. See that it builds the application successfully.
4. See the JSON error message on trying to deploy to netlify.

`JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Expected behavior

I expected it to deploy the application somewhere.

### Screen Recording / Screenshot

[Screencast from 2024-10-03 22-42-11.webm](https://github.com/user-attachments/assets/dabbcd65-b67e-4322-93a4-2be9d5f8d91b)

### Platform

```
Browser name = Firefox
Full version = 130.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
performance.memory = undefined
Username = jes
Chat ID = c3ccb6316ccc
```

### Additional context

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Message:
```
Certainly! I'll deploy the Time Tracker application for you using Netlify, which is one of our supported deployment providers.

<div class="__boltArtifact__" data-artifact-id="5:deploy-time-tracker" data-running-actions="true"></div>

I've initiated the deployment process for your Time Tracker application to Netlify. The build and deployment process is now underway. Let's wait for the deployment to complete and retrieve the status.
```

**Comment by samdenty** [comment]
netlify increased our rate limit so this should be solved
