### ISSUE TITLE
is my project saved somewhere?

### ISSUE THREAD

**Issue by CRW888-byte** [stackblitz/bolt.new#180]
I've been working on a website for 2 days and had to restart my computer and when logging in to bolt.new - my project is gone?

**Comment by FeiArt-Ai** [comment]
I have the same problem! Where is my project? I spent a whole day testing it yesterday, and I even published this webpage. But when I logged in again today, I found that my project is gone!!!!!!

**Comment by ClausGS** [comment]
similar problem here, I made a project on my work computer and now when i log in to my account on my home computer the project is not in bolt.new,,, but still on my work computer ???

**Comment by kirjavascript** [comment]
Hey! Chat is not persisted at the moment.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/39. Feel free to subscribe to that issue if you want to be informed when this will be added!

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
