### ISSUE TITLE
bus and bugs

### ISSUE THREAD

**Issue by xpdeal** [stackblitz/bolt.new#1801]
### Describe the bug

Many bugs and debit credits in loop, because rewrite bugs many times

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a56wca

### Steps to reproduce

.

### Expected behavior

.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65314237,
  "usedJSHeapSize": 62148549,
  "jsHeapSizeLimit": 4294705152
}
Username = xpdeal
Chat ID = ad866c63b8ec
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Hi @xpdeal, 

Sorry to hear about these challenges! There are complex programming issues that the AI can not solve and at times require manual intervention. Insights on efficient token usage and methods to use Bolt most effectively can be found [here](https://github.com/stackblitz/bolt.new/issues/678). Hope this helps!
