### ISSUE TITLE
Project Was Not Saved

### ISSUE THREAD

**Issue by appcontentbiz** [stackblitz/bolt.new#1803]
### Describe the bug

Hello:

I was using the free bolt system and had gotten to about the end of my project, but ran out of tokens and hit the link to select the number of tokens desired to continue this first project.  After payment, I was taken to a new screen and the project I was working on was no longer there and the menu shows as no projects for today.  How is this possible when I worked hard on the first part of the app with now, nothing to show for it except a blank slate and more tokens?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bstiss?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

I do not have anything to provide.

### Expected behavior

Just not sure why I no longer have the project?

### Screen Recording / Screenshot

Did not have time to take a snapshot nor a link shot.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46759193,
  "usedJSHeapSize": 37204509,
  "jsHeapSizeLimit": 2160066560
}
Username = appcontentbiz
Chat ID = a9ba89029583
```

### Additional context

n/a

**Comment by endocytosis** [comment]
Hi @appcontentbiz, 

Can you check the workaround (go to stackblitz.com, open Collections on the left-hand side, then open Bolt Collection) described here: #39 and see if that works? Thanks.

**Comment by appcontentbiz** [comment]
Hello endocytosis:

Thank you very much as I am new here, it is good to know that the community/support answers so quickly.  The Collection tab did work!  Again, thank you. It is appreciated.

**Comment by endocytosis** [comment]
@appcontentbiz, 

Great, glad to help!

**Comment by appcontentbiz** [comment]
Hello Brian:

I started a new education app project and have been working on it now for
almost three days and am still having trouble
working out bolt's problem with locating the appropriate "working" video
player for the project.  Every video player it
suggests has an error. I have been asking for a solution for days now and
we still end-up with the exact same problem, it
does not know what video player to use in order for the preview to work and
the video player to work.  Plus, I am using
way too many tokens and getting no where.

I really need help with this, if possible.

Thank you very much in advance for any assistance.

**Comment by endocytosis** [comment]
Hi, could you please email hello@stackblitz.com with reference to this thread and we can take a closer look? Thanks!
