### ISSUE TITLE
Hosting on another hosting server

### ISSUE THREAD

**Issue by Compdave** [stackblitz/bolt.new#1805]
I would like to build the web app with bolt.net and then, when done. Either deploy to, or copy and upload to, my domain on the hosting site I'm already using (Bluehost, for now).

**Describe alternatives you've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
Hi @Compdave, 

When you have completed your Bolt project you can download the files (download button at the top of the page next to the project title) which you can then deploy to a hosting provider of your choosing.
