### ISSUE TITLE
Wasting tokens on Bolt breaking more than he is fixing

### ISSUE THREAD

**Issue by visiontek-official** [stackblitz/bolt.new#1806]
### Describe the bug

2 days ago Bolt was still working okay and yesterday it started breaking code and doing the most weirdest ting. I will tell him to change a file and then he breaks an entire different side of my project that has noting to day with the change i have. today i lost an entire day of code because Bolt couldnt save my work.
I even tried to deploy the netlify which says i need to wait for the url, but nothing happens.

I have waisted over 40min of tokens in the past 2 days just trying to get Bolt to do the basic stuff.

I NEED HELP or Bolt needs to go.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-chmrvy

### Steps to reproduce

2 days ago Bolt was still working okay and yesterday it started breaking code and doing the most weirdest ting. I will tell him to change a file and then he breaks an entire different side of my project that has noting to day with the change i have. today i lost an entire day of code because Bolt couldnt save my work.
I even tried to deploy the netlify which says i need to wait for the url, but nothing happens.

I have waisted over 40min of tokens in the past 2 days just trying to get Bolt to do the basic stuff.

I NEED HELP or Bolt needs to go.

### Expected behavior

to work like it was working 2 days ago with ALOT less issues.
2 days ago Bolt was still working okay and yesterday it started breaking code and doing the most weirdest ting. I will tell him to change a file and then he breaks an entire different side of my project that has noting to day with the change i have. today i lost an entire day of code because Bolt couldnt save my work.
I even tried to deploy the netlify which says i need to wait for the url, but nothing happens.

I have waisted over 40min of tokens in the past 2 days just trying to get Bolt to do the basic stuff.

I NEED HELP or Bolt needs to go.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @visiontek-official, 

Appreciate the feedback. In the Bolt code window you can right-click a file and then click "Lock file", which will prevent the AI from making changes to that file. The page [here](https://github.com/stackblitz/bolt.new/issues/1806) has some advice for improving token efficiency that might be helpful.

**Comment by visiontek-official** [comment]
im not sure you understanding the issue - it doesnt save my work, cant even deploy to netlify anymore and for the past 2 days, its making huge mistakes and alot of them.

**Comment by visiontek-official** [comment]
and by the looks as the issues in the past 2 days, i not the only one
