### ISSUE TITLE
Feature Request: Upload image files to Bolt

### ISSUE THREAD

**Issue by endocytosis** [stackblitz/bolt.new#1809]
Currently, image files cannot be uploaded to Bolt. A solution is in progress. In the interim, you can:

- Open your Bolt project in StackBlitz (click "Open in StackBlitz" at the top right of the page)
- Upload the image to the StackBlitz file system
- Specify the correct image path

**Comment by endocytosis** [comment]
To upload an image to the StackBlitz file system:

1) Login to [stackblitz.com](https://stackblitz.com/) (same credentials as Bolt) and open your project.
2) This page [here](https://developer.stackblitz.com/guides/user-guide/ide-whats-on-your-screen#frontmatter-title) describes the UI of the StackBlitz IDE.
3) Drag the image files into the Project Sidebar.
4) Make sure the location of the image within the file directory matches the image file path in your code and adjust either of these as necessary.

**Comment by buger** [comment]
It actually did not worked for me. 
When app gets build and rendered inside the StackBlitz, it all renders well. 
When I get back to bold, it does not render those images.
When you try to open this image in Bolt editor, it actually just a text file containing URL like https://stackblitz.com/storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJB.....
Same when you download the project. 

So at the moment I do not see a way how to have custom image in bolt 🤔

**Comment by endocytosis** [comment]
**Update:** You can now upload images to the Bolt file system.

**Comment by mkeserci** [comment]
![Image](https://github.com/user-attachments/assets/d1d2ffd9-b450-433a-a923-fb28717eed07)

same problem hier ?
