### ISSUE TITLE
Unexpected token 'U', "Unexpected"... is not valid JSON

### ISSUE THREAD

**Issue by kantconcentr8** [stackblitz/bolt.new#181]
### Describe the bug

was trying to to a test deployment and got the error
![bolt-deployment error](https://github.com/user-attachments/assets/1203ae80-3984-48fb-aef6-13c0e16521f8)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ucakt1

### Steps to reproduce

![bolt-deployment error](https://github.com/user-attachments/assets/3daa5175-9d53-41a3-8846-c08bdbff7420)

### Expected behavior

I wanted to test the website on a live environment

### Screen Recording / Screenshot

![bolt-deployment error](https://github.com/user-attachments/assets/46f92921-fc00-4970-b19f-30966f073d17)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45722503,
  "usedJSHeapSize": 43587351,
  "jsHeapSizeLimit": 4294705152
}
Username = kantconcentr8
Chat ID = 01abafc5eaa6
```

### Additional context

Error:
```
Unexpected token 'U', "Unexpected"... is not valid JSON
```

**Comment by boudewijndanser** [comment]
Have the same issue.

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

We're tracking this issue internally and will let you know when we have a resolution.

**Comment by samdenty** [comment]
we've just fixed this and made the error messages better

**Comment by oliroro1968** [comment]
Hello I have this error: "Unexpected token (194:22)" I cannot use it anymore, it always end up blocked, can you help?
