### ISSUE TITLE
Base template for building NativeStript Starter JavaScript Fails before any changes.

### ISSUE THREAD

**Issue by seagalli** [stackblitz/bolt.new#1810]
### Describe the bug

The base template for building NativeStript Starter JavaScript doesnt seem to start properly. the error is below: setup-nativescript-stackblitz && ns preview
Setting up NativeScript aliases: ns, nsc, tns and nativescript...
Installing @nativescript/preview-cli@latest
Installing @nativescript/stackblitz@latest
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-08T22_10_51_550Z-debug-0.log
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-08T22_10_51_574Z-debug-0.log

 ERROR  callSite.getFileName is not a function. (In 'callSite.getFileName()', 'callSite.getFileName' is undefined)
┃
┃  depd@
┃  ../../node_modules/body-parser/index.js@
┃  __require@
┃  ../../node_modules/express/lib/express.js@
┃  __require@
┃  ../../node_modules/express/index.js@
┃  __require@
┃  @
┃  _0x39bbea@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/blitz.f565b097.js:40:799734
┃  @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14247
┃  @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14863
┃  @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
┃  @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10277
┃  executeUserEntryPoint@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:1646
┃  internal/main/run_main_module@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/builtins.ddb8d84d.js:138:405
┃  _0x17065f@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/blitz.f565b097.js:40:1435197
┃  @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/blitz.f565b097.js:40:897016
┃  @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-vqe93rgk.w-corp-staticblitz.com/blitz.f565b097.js:40:1465224
┗━

~/project 1m 10s
❯ 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nativescript-js

### Steps to reproduce

1. Start by clicking the button NativeStript Starter JavaScript on the main page.
2. Wait for the initialization and you see the error while building

### Expected behavior

I would expect it to start so you can start working on a project.

### Screen Recording / Screenshot

None 

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Chat ID = 6bd201b08b1e
```

**Comment by endocytosis** [comment]
Hi @seagalli, 

Appreciate the feedback! The issue likely stems from Safari. [WebContainers](https://webcontainers.io/), a fundamental technology powering Bolt, are fully supported in Chrome and most Chromium based browsers. You can read more about browser support [here](https://webcontainers.io/guides/browser-support). You should have success opening the NativeScript starter in Chrome. Hope this helps!
