### ISSUE TITLE
Auto Save Control Version 

### ISSUE THREAD

**Issue by panchito05** [stackblitz/bolt.new#1811]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by panchito05** [comment]
They need to implement version control I just lost all my work version control and I have no way to recover it

**Comment by endocytosis** [comment]
Hi @panchito05, 

Sorry to hear about this! Chat persistence and better GitHub integration are ongoing areas of development. The chat persistence issue is being tracked here: #39. You can try going to stackblitz.com, logging in (same credentials as Bolt), clicking Collections on the left-hand side, and then clicking Bolt Collection to see if your project is there. Appreciate your patience as the team continues to make improvements!
