### ISSUE TITLE
I asked it to create a contact form and display the phone and email from my settings in my admin and it started erasing all my code. 

### ISSUE THREAD

**Issue by jeremysteam** [stackblitz/bolt.new#1813]
### Describe the bug

I asked it to create a contact form and use some of the settings from my admin area for the contact page to display my saved phone number and email and it went in my admin area and started editing all my admin pages. 

It wouldn't be a problem usually, but this time it left notes in the code like {The rest of your JSX*/} and {Rest of Content} 

And it completely broke my page. 

Then I went to revert the pages back with undo, and theres nothing. 

All the old code is gone. Theres no backup. I can't find it. 

So all the tokens I just used to build out my admin area are now wasted...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-oleqmq

### Steps to reproduce

Just a bug 

Made a prompt and it went crazy editing the code for files that aren't even necessary. Now when I do undo theres no  code to undo or revert.

### Expected behavior

Was only supposed to edit my contact us page. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 198807619,
  "usedJSHeapSize": 177498071,
  "jsHeapSizeLimit": 4294705152
}
Username = jeremysteam
Chat ID = 5b0df203e684
```

**Comment by endocytosis** [comment]
Hi @jeremysteam, 

In the Bolt file system, you can right-click a file and click "Lock file" to prevent the AI from making changes to that file. Regarding chat persistence, we are aware of the issue. Temporary workarounds and updates can be found here: #39. You can check to see if your project is located in your Bolt Collection by navigating to stackblitz.com, logging in (same credentials as Bolt), click Collections on the left-hand side of the page, and then clicking Bolt Collection.
