### ISSUE TITLE
When making adjustments, Bolt screws up other parts

### ISSUE THREAD

**Issue by orca-m** [stackblitz/bolt.new#1818]
### Describe the bug

I provide a concise, one step adjustment to be made, and Bolt fixes that but then screws up the UI on another unrelated part of the preview. It seems to be happening more and more now.  I even tried giving it explicit instructions of "Please keep all current code UNCHANGED except for this ONE adjustment:" but it still is messing up other parts. I feel like I'm playing whackamole and it is wasting an excessive number of credits!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nxbkb1

### Steps to reproduce

Ask it to adjust the photo placement (if it is not responding/working) and see what it changes that wasn't changed previously and was not related to the change you had asked for.

### Expected behavior

I expect it to only change the code of that one element to make the adjustment

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 142291159,
  "usedJSHeapSize": 135012447,
  "jsHeapSizeLimit": 4294705152
}
Username = orcamarketology
Chat ID = c1a86aa1569e
```

### Additional context

It seems that the further I have gotten into this project, the erroneous errors seem to be increasing.

**Comment by clee100** [comment]
ditto. Smooth sailing at first but now I've hit a wall. Can't make any progress because it creates more bugs than it fixes now -even in unrelated code. My project has less than 2000 lines of code. Refactoring to make more components seemed to have made it worse. It will often update multiple locations when it should only update one location.

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback! If you right-click a file in the Bolt code editor and select "Lock-file", this will prevent the AI from making further changes to that file. This can be done for multiple files. Conversely, if you want the AI to just focus on modifying one file, right-click that file and select "Target file". 

This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on leveraging Bolt most effectively while maximizing token efficiency. Appreciate your patience as improvements continue to be made!
