### ISSUE TITLE
PLEASE HELP... NO CHAT FOUND 

### ISSUE THREAD

**Issue by nedwolp1** [stackblitz/bolt.new#1819]
So I've spent about $300 worth of tokens on bolt chat for my company and I do not see it on my end.... 
 I would never delete it as it's my TOP project right now. I do have the netlify link and luckily sent a zip of my project to my developer but now I can not edit it in bolt! PLEASE HELP RESOLVE OR refund me the tokens spent on that project at disappeared

**Comment by endocytosis** [comment]
Hi @nedwolp1, 

Sorry to hear you are having this issue. Are you able to find your project by as follows: Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection?
