### ISSUE TITLE
Is it possible to attach a svg file?

### ISSUE THREAD

**Issue by raqphixken** [stackblitz/bolt.new#182]
Please help. How can I attach a svg file?
![Screenshot 2024-10-07 at 4 25 14 PM](https://github.com/user-attachments/assets/d8f47346-1f62-45da-a28d-c0ad34683e7d)

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the issue!

We're tracking this issue internally and will let you know when we have a resolution.

**Comment by kirjavascript** [comment]
This should be fixed now!

Feel free to open another issue if you are still having problems with anything.
