### ISSUE TITLE
I asked for a animated globe and a picture of the milky way galaxy. It did not add both the website. 

### ISSUE THREAD

**Issue by shettigarvivek** [stackblitz/bolt.new#1821]
### Describe the bug

I asked for a animated globe and a picture of the milky way galaxy. It did not add both the website. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-frvzik?ref=futuretools.io

### Steps to reproduce

just repeat my  inputs and you see see the results. 

### Expected behavior

It should have show me an animted globe and when i press get started it should have shown me a picture of the milky way galaxy

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54161967,
  "usedJSHeapSize": 48163711,
  "jsHeapSizeLimit": 4294705152
}
Username = shettigarvivek
Chat ID = 7fa7ff2d7410
```

**Comment by endocytosis** [comment]
While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects. There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform, including prompting the AI most effectively. Hope this helps!
