### ISSUE TITLE
White Preview Screen

### ISSUE THREAD

**Issue by WhitePine2024** [stackblitz/bolt.new#1822]
### Describe the bug

Every Browser I use I keep running into a white preview screen have not been able to see any previews? Trying to create a 3D CPQ 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vgzces

### Steps to reproduce

Prompt
-Create 3D CPQ for a Pool

Says it does it and i can see preview and I cant see preview

### Expected behavior

I expect to see a preview I only see a white screen

### Screen Recording / Screenshot

![bolt](https://github.com/user-attachments/assets/3bf686d7-ea59-497f-ac01-44083079de92)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46673062,
  "usedJSHeapSize": 44473982,
  "jsHeapSizeLimit": 4294705152
}
Username = WhitePine2024
Chat ID = 8c112a7c366b
```

### Additional context

Have used: Shift, Edge, & Chrome

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking is here: #1791.
