### ISSUE TITLE
Setup google Oauth in the application and testing on webcontainer

### ISSUE THREAD

**Issue by ta1bbty** [stackblitz/bolt.new#1823]
### Describe the bug

How do we setup google oauth in the application ?

### Link to the Bolt URL that caused the error

http://bolt.new/~/na

### Steps to reproduce

1. How to setup Google Oauth app in bolt.new ?

### Expected behavior

should be able to login using google oauth and get values from there.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @ta1bbty, 

This video [here](https://www.youtube.com/watch?v=eE6m0MmLpDU) describes adding auth with Firebase.

**Comment by ta1bbty** [comment]
Hey @endocytosis 👋
Thanks for reverting back on this. However the video that you sent ( which I had checked before posting here ), is about adding email and password through firebase.

Oauth login gets complicated because of `redirect URIs` and `authorised URLs` . In the web container I am not sure what those values would be ?

Thanks. Regards.
