### ISSUE TITLE
Redoing full page

### ISSUE THREAD

**Issue by asargeant88** [stackblitz/bolt.new#1825]
### Describe the bug

this program rewirtes full pages over and over to use up max amount of tokens as quickly as possible using 200k tokens per rewrite why

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qchflh

### Steps to reproduce

none

### Expected behavior

create a login

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = asargeant88
Chat ID = 482010b38f8c
```

**Comment by endocytosis** [comment]
Appreciate the feedback! The team is hard at work implementing improvements to address this. If you no longer want the AI to modify a file, you can right-click that file in the Bolt code editor and select “Lock file” to prevent the AI from making further changes. This can be done for multiple files. Additionally, this page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt most effectively while maximizing token efficiency. Hope this helps!
