### ISSUE TITLE
 prompt is too long: 202918 tokens > 200000 maximum

### ISSUE THREAD

**Issue by eventstubsol** [stackblitz/bolt.new#1828]
### Describe the bug

This message randomly appeared. Not sure what I did but now it would not get me past that. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-oq7qhd

### Steps to reproduce

This message randomly appeared. Not sure what I did but now it would not get me past that. 

### Expected behavior

This message randomly appeared. Not sure what I did but now it would not get me past that. 

### Screen Recording / Screenshot

![Bug](https://github.com/user-attachments/assets/b3912453-07bd-4d47-8576-3b562f83d3ee)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Unique/97.7.6833.65
performance.memory = {
  "totalJSHeapSize": 117058422,
  "usedJSHeapSize": 106686766,
  "jsHeapSizeLimit": 4294705152
}
Username = eventstubsol
Chat ID = 7040cdac10d8
```

### Additional context

Refreshing the page seems to have fixed this issue

**Comment by Frankg40** [comment]
1. Refresh Web Browser
2. Ask Bolt if there are any files or code that is deprecated or unused or duplicated that can be removed from your project.
ADD THE WORDS: "ANSWER ONLY DO NOT DO ANYTHING ELSE"
3. https://github.com/stackblitz/bolt.new/issues/1322 - Last 2 posts

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue and is being tracked [here](https://github.com/stackblitz/bolt.new/issues/1322), which has additional context along with ways to maximize token efficiency. Appreciate your patience as improvements continue to be made!
