### ISSUE TITLE
 Missing Project Chat

### ISSUE THREAD

**Issue by kirullos** [stackblitz/bolt.new#1829]
I am reaching out regarding an issue with my project chat on your platform. I recently noticed that my project chat, which relates to a fitness initiative, has disappeared unexpectedly. I did not delete this chat, and I am unsure why it is no longer accessible.
Please find attached a screenshot showing that I currently have no backups available for this project. This is concerning, as I was under the impression that backups would be retained automatically, especially given that I have utilized 807,000 tokens this month.
Could you please advise on how I might be able to restore my project chat? Unfortunately, I did not save the latest version of this project independently, so it is crucial for me to retrieve it if possible. Any guidance or assistance in recovering this data would be greatly appreciated.
Thank you for your attention to this matter. I look forward to your prompt response.
![image](https://github.com/user-attachments/assets/f6f11aca-a5bc-4be8-8cf8-d27af02ac7fd)
![image](https://github.com/user-attachments/assets/8a3e7a08-c403-448c-8d31-35a38e5f53eb)

**Comment by endocytosis** [comment]
We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made!
