### ISSUE TITLE
This message didn't complete its response!!!!

### ISSUE THREAD

**Issue by visiontek-official** [stackblitz/bolt.new#1830]
### Describe the bug

Each time im giving Bolt a prompt, it starts changing the code then randomly says "This message didn't complete its response." and stops, which also breaks the code each time. This is really wasting my tokens and breaking my entire project each time which i have to revert.
Also when reverting, its making alot of app changes that a person did even have or requested.
Im not sure what was done to Bolt in the last couple of days but please revert it back to how Bolt was. This new Bolt is TERRIBLE!!!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-osytzx

### Steps to reproduce

Each time im giving Bolt a prompt, it starts changing the code then randomly says "This message didn't complete its response." and stops, which also breaks the code each time. This is really wasting my tokens and breaking my entire project each time which i have to revert.
Also when reverting, its making alot of app changes that a person did even have or requested.
Im not sure what was done to Bolt in the last couple of days but please revert it back to how Bolt was. This new Bolt is TERRIBLE!!!

### Expected behavior

To work how it is supposed to work and how it worked in the past.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/05c546d7-adcb-4907-8277-5090e0d2e64b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows - Chrome and tried, firefox and Edge.

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracker here: #1073.
