### ISSUE TITLE
After 8 attempts I cannot download the full code

### ISSUE THREAD

**Issue by andaydvice** [stackblitz/bolt.new#1832]
### Describe the bug

After 8 attempts I cannot download the full code

It is a much smaller file size than it should be

The code needs to be added to a seperate Wordpress page to update the existing tool, built with a different. application.

https://globaldocumentsolutions.com.au/printer_lease_quote.html?cvfd=sdf

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dc952t

### Steps to reproduce

Clicking on the download button ion the bottom right hand corner as the tool suggests

### Expected behavior

Receive all files of around 4-5mb according to the system replies.

### Screen Recording / Screenshot

Video of the download size

https://app.screencast.com/hddCPbbXdPesQ

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 122374341,
  "usedJSHeapSize": 99780337,
  "jsHeapSizeLimit": 4294705152
}
Username = andaydvice
Chat ID = 1381419f5032
```

**Comment by endocytosis** [comment]
Hi @andaydvice, 

You could try clicking the Download button at the top of the Bolt page. The code is downloaded as a ZIP file which is compressed. If you double-click those files to unzip them, you should see the full code. Regarding the functionality of applications created with Bolt, we unfortunately don't have the capacity to troubleshoot the code for individual user's projects.
