### ISSUE TITLE
Nothing shows up in the preview no matter how many times the code is updated

### ISSUE THREAD

**Issue by rockysingh3** [stackblitz/bolt.new#1833]
### Describe the bug

exactly what the title says. It keeps updating all the files and rerunning the sever but nothing happens

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vws9rw

### Steps to reproduce

Nothing shows up

### Expected behavior

a basic UI

### Platform

```
Browser name = Chrome
Full version = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 156977355,
  "usedJSHeapSize": 138580519,
  "jsHeapSizeLimit": 4294705152
}
Username = rockysingh3
Chat ID = 0f416a6b2d4f
```

**Comment by Nishantbhagat57** [comment]
Same here. Even I have subscription

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue and is being tracked here: #1791.
