### ISSUE TITLE
Again the same issue 

### ISSUE THREAD

**Issue by rockysingh3** [stackblitz/bolt.new#1834]
### Describe the bug

I just get a blink white screen and no errors.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vws9rw

### Steps to reproduce

Nothing shows up

### Expected behavior

UI that displays the functionlity 

### Platform

```
Browser name = Chrome
Full version = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 145011982,
  "usedJSHeapSize": 134704058,
  "jsHeapSizeLimit": 4294705152
}
Username = rockysingh3
Chat ID = 0f416a6b2d4f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: https://github.com/stackblitz/bolt.new/issues/1791.
