### ISSUE TITLE
cannot send my chat request

### ISSUE THREAD

**Issue by KentBrian054** [stackblitz/bolt.new#1837]
### Describe the bug

![image](https://github.com/user-attachments/assets/80b9598b-9faf-403b-b04a-360b66de5e18)

### Link to the Bolt URL that caused the error

https://bolt.new/~/monitoring-system-thqsrw-nyfnkw

### Steps to reproduce

i want to analyze my request

### Expected behavior

i want to analyze my request

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.
