### ISSUE TITLE
Option to save chat/instruction

### ISSUE THREAD

**Issue by ps-Code-01** [stackblitz/bolt.new#184]
A way to copy the instructions or the entire chat session.  Possibly to add it as a Markdown / Instruction file.

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the issue!

It would be nice to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by samdenty** [comment]
We do not persist the chat history for now, but we will add support for this. You can track this in https://github.com/stackblitz/bolt.new/issues/39. I'll close this issue for now but feel free to create a new one if you ever run into any other issues 😃
