### ISSUE TITLE
app wont load 

### ISSUE THREAD

**Issue by blutrich** [stackblitz/bolt.new#1841]
### Describe the bug

the preview wont load 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rexrwu

### Steps to reproduce

sign up page 

### Expected behavior

app load 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49687059,
  "usedJSHeapSize": 48204635,
  "jsHeapSizeLimit": 2160066560
}
Username = blutrich
Chat ID = d145a108d34e
```

**Comment by uri100** [comment]
I have the same problem

**Comment by endocytosis** [comment]
Appreciate the feedback!  This is a known issue that is being tracked here: #1791. We appreciate your patience as Bolt continues to improve!
