### ISSUE TITLE
npm load infinite and other file doesn’t generate

### ISSUE THREAD

**Issue by lilyaan444** [stackblitz/bolt.new#1842]
### Describe the bug

when i ask for feature bolt try to install npm but it’s load infinitly and the other file doesn’t generate 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gueswh

### Steps to reproduce

1. ask a feature 
2. wait infinitly

### Expected behavior

maybe a button to stop manually npm installation or something like that’s so i can at least get the code writting and doesn’t lost token for nothing 

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = lilyaan444
Chat ID = 96d4158045a7
```

**Comment by endocytosis** [comment]
Hi @lilyaan444, 

A few things to try here if npm hangs: 

- npm load times are correlated with overall dependency tree size. The greatest load time is usually during initial project generation as npm modules are installed. Performance improvements continue to be made to reduce load times.
- If npm continues to hang, refreshing the page usually fixes the problem. However, be aware that doing so will result in losing your current chat history.
- Bolt, which [relies on WebContainers](https://webcontainers.io/guides/browser-support#:~:text=WebContainers%20are%20fully%20supported%20in,working%20out%20of%20the%20box.), currently has the greatest support for Chrome and most Chromium-based browsers. Developing in Chrome will likely result in improved performance. We expect support for other browsers to continue to improve.
- As a Bolt project size increases so do local memory (RAM) demands. Ensuring your browser has sufficient memory by closing unnecessary tabs can increase performance.
