### ISSUE TITLE
Import failing 

### ISSUE THREAD

**Issue by sanjabh11** [stackblitz/bolt.new#1844]
### why import is failing on bolt.new?
https://bolt.new/~/github.com/sanjabh11/RecordNow
I'm importing your repository into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Github Repository

import failed- sanjabh11/RecordNow
Cannot destructure property 'appFiles' of 'project' as it is null.
An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/sanjabh11/RecordNow

### Steps to reproduce

https://bolt.new/~/github.com/sanjabh11/RecordNow

### Expected behavior

https://bolt.new/~/github.com/sanjabh11/RecordNow

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 43728604,
  "usedJSHeapSize": 39496640,
  "jsHeapSizeLimit": 2160066560
}
Username = Renu
Chat ID = 22ad334105bb
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This issue is being tracked here: #1812.
