### ISSUE TITLE
 Saving issue

### ISSUE THREAD

**Issue by vdeguere** [stackblitz/bolt.new#1845]
### Describe the bug

When I am working on a single project across multiple machines (sometimes on my laptop, sometimes on desktop), I cannot seem to save the progress that updates the right files. We need an easier way in bolt to save the progress. I am finding one version of work on one machine and another version of my work on another. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3wx8xj

### Steps to reproduce

 w

### Expected behavior

I would like to have a much better file saving system. For example saving to stackblitz and loading from stackblitz no matter which machine I'm using. 

### Screen Recording / Screenshot

wd

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65170213,
  "usedJSHeapSize": 61550217,
  "jsHeapSizeLimit": 4294705152
}
Username = vdeguere
Chat ID = 24db9b06794b
```

### Additional context

 sd

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made!
