### ISSUE TITLE
Please add git

### ISSUE THREAD

**Issue by tarto-bianco** [stackblitz/bolt.new#1847]
add something like git, i had the app like 99% working to how I wanted it. But went back to change something, and it basically destroyed the whole app. git would usually fix this for me.

**Comment by endocytosis** [comment]
Appreciate the feedback! The team continues to work to improve GitHub integration. Temporary workarounds and updates can be found here: #39. (To look for projects, you can try the following: Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). 

Additionally, this page [here](https://github.com/stackblitz/bolt.new/issues/678) outlines a number of techniques to use Bolt most effectively, such as the Rollback feature (at the of a previous prompt click "Rollback to Checkpoint" to revert your project to a previous state), which might be helpful.
