### ISSUE TITLE
not connecting with external database

### ISSUE THREAD

**Issue by azlanstratafy** [stackblitz/bolt.new#1849]
### Describe the bug

not connecting with external database

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-beaxxv

### Steps to reproduce

not connecting with external database

### Expected behavior

not connecting with external database

### Screen Recording / Screenshot

not connecting with external database

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59438597,
  "usedJSHeapSize": 53689229,
  "jsHeapSizeLimit": 2160066560
}
Username = azlanstratafy
Chat ID = 8655b3e7e721
```

**Comment by endocytosis** [comment]
Unfortunately we don't have the capacity to troubleshoot code issues with individual projects. However, there are some community resources that may be helpful! This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on working with Bolt most effectively. The [StackBlitz Discord](https://discord.gg/stackblitz) has some threads where users share knowledge on projects. Also, this video [here](https://www.youtube.com/watch?v=1GfqnOAKr9M) shows how to add a Firebase database. Hope this helps!
