### ISSUE TITLE
many many issues with this AI

### ISSUE THREAD

**Issue by savas1605** [stackblitz/bolt.new#1850]
### Describe the bug

around 60%-70% of the work is regenerated multiple times fixing one errOR and creating 20, useless regenerating while consuming  all the tokens, sometimes you ask the bot to go right, he goes left. Adding new feature and removing 10 others,then you need to go to a saved checkpoint. Contacted the support and still waiting for their reply.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wmrmdg

### Steps to reproduce

scroll down

### Expected behavior

Verifying the log, and refill all the unnecessaries credits used by the bot. Fixing the deployment issues. Enhancing the bot to fully remember do not ignore all the tasks done before under the same project. .... many many things needs to be improved. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 265321428,
  "usedJSHeapSize": 204547164,
  "jsHeapSizeLimit": 2248146944
}
Username = Savas2030
Chat ID = 9c6c21124564
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
This page [here](https://github.com/stackblitz/bolt.new/issues/678) contains a number of insights into using Bolt most effectively and maximizing token usage efficiency. We appreciate your patience as improvements continue to be made!
