### ISSUE TITLE
I lost credits because bolt gave an error and I couldn't recover them

### ISSUE THREAD

**Issue by plataformaconcreta** [stackblitz/bolt.new#1851]
### Describe the bug

After almost two hours of producing the bolt, there was an error and I lost everything. The point that had balance was much earlier.

I lost more than 10M credits! And I had to do it all again

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-ari7fm-aq4cmm

### Steps to reproduce

After almost two hours of producing the bolt, there was an error and I lost everything. The point that had balance was much earlier.

I lost more than 10M credits! And I had to do it all again

### Expected behavior

After almost two hours of producing the bolt, there was an error and I lost everything. The point that had balance was much earlier.

I lost more than 10M credits! And I had to do it all again

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Sorry to hear about this! Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, then clicking Bolt Collection? Chat persistence is a known issue that is being tracked here: #39.

**Comment by plataformaconcreta** [comment]
Again. lots 13M credits 
![Uploading Screenshot at Nov 10 11-28-09.png…]()
