### ISSUE TITLE
The site keeps crashing

### ISSUE THREAD

**Issue by pluckhired** [stackblitz/bolt.new#1853]
### Describe the bug

I paid for pro subscription ..but I am never able to complete my task .. it always crashes and refreshes midway. Either give me subscription back or pls fix it.

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

dadasd

### Expected behavior

ddd

### Screen Recording / Screenshot

dd

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

dd

**Comment by plataformaconcreta** [comment]
me too

**Comment by endocytosis** [comment]
Hi all, 

Appreciate your patience as the team continues to make improvements. In #678 we have collected many best practices on error resolution and prompting strategies for efficient token usage. If you are looking for a refund, please reach out to hello@stackblitz.com as we process all refund requests there!
