### ISSUE TITLE
Enable GitHub Repository Integration for Direct Project Loading in bolt.new

### ISSUE THREAD

**Issue by tautiz** [stackblitz/bolt.new#1854]
**Is your feature request related to a problem? Please describe:**

I'm often frustrated when I want to load projects directly from a GitHub repository into bolt.new for streamlined development. Currently, I have to manually transfer files or set up projects outside of bolt.new, which disrupts the workflow and reduces efficiency, especially when collaborating or testing specific codebases.

**Describe the solution you'd like:**

I'd like the ability to load projects directly from a GitHub repository within bolt.new. This feature would allow users to connect to their GitHub accounts, select a repository, and import the project seamlessly into bolt.new. This integration would enable direct access to the project files and the ability to work on them immediately using bolt.new's AI-powered tools.

**Describe alternatives you've considered:**

I considered manually downloading project files from GitHub and uploading them to bolt.new, but this approach is time-consuming and does not support continuous updates. Another alternative is using other platforms that offer GitHub integration, but they lack the unique AI functionalities of bolt.new, making it less appealing for AI-enhanced workflows.

**Additional context:**

This feature could also allow for automatic syncing with GitHub repositories, ensuring that any updates made in bolt.new could be committed back to GitHub, supporting version control and collaboration. This would be especially beneficial for developers working on teams or frequently updating code.

**Comment by endocytosis** [comment]
Appreciate the feedback here! You are correct - currently, we only support public GitHub repositories. The team is hard at work continuing to improve GitHub functionality and integration. The [StackBlitz X](x.com/stackblitz) account is a great place to keep abreast of continued updates. 

We do support private StackBlitz native projects. To utilize this workaround you will need to download your GitHub repo, create an empty StackBlitz project, drag and drop your GitHub project files into the StackBlitz filesystem, save, and then use the “Open in Bolt” button to work on the project in Bolt. It is important to be aware that Bolt cannot support very large codebases, so this is only recommended for small projects. Appreciate your patience at the team continues to improve this functionality!

**Comment by Labhk** [comment]
Hey, I've build this web tool for just this issue, previously using script on local now its a website much easy, enjoy
https://boltsync.mystify.tech/
https://www.youtube.com/watch?v=IneFM6ViV8s
