### ISSUE TITLE
Lose your job when you use another computer. 

### ISSUE THREAD

**Issue by julianmartineza** [stackblitz/bolt.new#1856]
### Describe the bug

When I log into my account from another computer, I don't find the work that I've been doing or the chat windows I used on the other one. This has made me lose several times the work I've done. Even if I close my browser, I'll lose the work I've been doing on the bolt.new platform. I don't even see it on StarBlitz. 

### Link to the Bolt URL that caused the error

i have no error

### Steps to reproduce

just open your account in another computer

### Expected behavior

I would hope to see my work from any computer i access to my account

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback here! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to stackblitz.com, login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made!
