### ISSUE TITLE
Token limit!!

### ISSUE THREAD

**Issue by QRUMN** [stackblitz/bolt.new#1857]
### Describe the bug

Why does this continue to happen when I pay for the most expensive plan?
Error msg: prompt is too long: 203897 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-l1yxmt

### Steps to reproduce

Not sure but I need help so i can continue to build.

### Expected behavior

any time i try to input a new prompt that error message pops up.

### Screen Recording / Screenshot

![Screenshot 2024-11-09 at 11 03 02 AM](https://github.com/user-attachments/assets/27fdfa8c-3f13-43e3-bce7-924a6b02f6dd)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76462409,
  "usedJSHeapSize": 69861937,
  "jsHeapSizeLimit": 4294705152
}
Username = QRUMN
Chat ID = ebfce228c5cc
```

**Comment by endocytosis** [comment]
Appreciate the feedback. This is a known issue related to context window size that we are tracking here: #1322. That page also includes some insights on improving token efficiency.
