### ISSUE TITLE
LOST ALL WORK LIKE OTHERS! Unrecoverable errors; all forked contains lost on StackBlitz. UNACCETABLE FOR COMMERCIAL PRODUCT!

### ISSUE THREAD

**Issue by lcapece** [stackblitz/bolt.new#1865]
Like many other people here I have lost all my work, for example about 8 hours of work today from early this morning is gone, when the server crashes it will also wipe out yourstackblitz.com container in collections. I have burned through close to 50,000 tokens and have 0 progress done towards completion of this four different projects I have started because of the repeated crashes there needs to be some mechanism to checkpoint the container itself because the container is extremely unstable

**Comment by endocytosis** [comment]
We understand that this is frustrating. Persistence is a known issue and is being tracked here: #39. The team is hard at work continuing to improve GitHub integration as well. We appreciate your patience as improvements continue to be made!
