### ISSUE TITLE
Deploy fail

### ISSUE THREAD

**Issue by Bookern** [stackblitz/bolt.new#1866]
### Describe the bug

Just trying to deploy this site but it errors on trying to deploy.

I'll check the deployment status to get the URL for you.

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nm5sws

### Steps to reproduce

Well, I think just click the Deploy button

### Expected behavior

Expected it to deploy the page

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 170002707,
  "usedJSHeapSize": 148440511,
  "jsHeapSizeLimit": 4294705152
}
Username = Bookern
Chat ID = 8415cd27116e
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
