### ISSUE TITLE
Failed building the project. Make sure the build command is correct and try again.

### ISSUE THREAD

**Issue by CooldudeGeldrop** [stackblitz/bolt.new#1867]
### Describe the bug

![image](https://github.com/user-attachments/assets/d3b172fb-0d61-4d97-8224-ebce8c55c32b)
npx shadcn-ui@latest init --yes && npx shadcn-ui@latest add table dialog button dropdown-menu

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-p2nuhd

### Steps to reproduce

got to build
see the error
and see npx shadcn-ui@latest init --yes && npx shadcn-ui@latest add table dialog button dropdown-menu

### Expected behavior

normal build process now in a loop somehow
npx shadcn-ui@latest init --yes && npx shadcn-ui@latest add table dialog button dropdown-menu
I guess this is going wrong

### Screen Recording / Screenshot

npx shadcn-ui@latest init --yes && npx shadcn-ui@latest add table dialog button dropdown-menu

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 188500999,
  "usedJSHeapSize": 153107695,
  "jsHeapSizeLimit": 4294705152
}
Username = Cooldudeams
Chat ID = e15b344e7162
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
