### ISSUE TITLE
Cannot Deploy App

### ISSUE THREAD

**Issue by waldo8888** [stackblitz/bolt.new#1868]
### Describe the bug

I hit the deploy button and it says it can
<img width="519" alt="Screenshot 2024-11-09 at 1 19 51 PM" src="https://github.com/user-attachments/assets/1d15eed6-9d70-45cb-abd3-482991c1f2b4">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m9fqez

### Steps to reproduce

1. go to bolt.new
2. spend hours and most of your credits building a website
3. hit deploy
4. get error

### Expected behavior

To deploy website

### Screen Recording / Screenshot

<img width="519" alt="Screenshot 2024-11-09 at 1 19 51 PM" src="https://github.com/user-attachments/assets/592bb274-9e4c-462f-9420-5c9512eaca95">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53252916,
  "usedJSHeapSize": 48366688,
  "jsHeapSizeLimit": 4294705152
}
Username = waldo8888
Chat ID = 32c1418e81f1
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
