### ISSUE TITLE
Puts code in chat instead of editor

### ISSUE THREAD

**Issue by lassecapel** [stackblitz/bolt.new#1869]
### Describe the bug

once in a while when generating code the bot continues in chat instead of implementing the actual code

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-htid5y

### Steps to reproduce

visit: https://bolt.new/~/sb1-htid5y
start generating code.
it's not always updating code

### Expected behavior

When the ai is generating code i expect the ai to update the files in the editor and not prompt out the ocde in the chat window

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = lassecapel
Chat ID = 6b885a983a21
```

**Comment by orca-m** [comment]
This was happening to me yesterday too

**Comment by endocytosis** [comment]
Appreciate the feedback! Prompting LLMs to achieve the desired behavior is an [area of active research](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview). Some helpful insights on how to use Bolt most effectively while maximizing token efficiency can be found [here](https://github.com/stackblitz/bolt.new/issues/678). At times, the model does not fully understand the request and manual intervention may be required. Something else that might help is if you select a block of text in a file in the Bolt code editor and then click "Ask Bolt" the AI's focus will be directed to that specific section of code. We appreciate your patience as improvements to continue to be made towards consistently achieving desired model behavior!
