### ISSUE TITLE
Unwanted Bug& and Error in Deployment.

### ISSUE THREAD

**Issue by KIRATH25** [stackblitz/bolt.new#1870]
### Describe the bug

Unable to deploy and fix the bug.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-auvnzg

### Steps to reproduce

I don;t sure about this.

### Expected behavior

Deploy the project

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e90a3532-cff8-457b-b37e-01e745e897bc)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116538676,
  "usedJSHeapSize": 94546652,
  "jsHeapSizeLimit": 4294705152
}
Username = KIRATH25
Chat ID = 0e9e2ca8a92a
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
