### ISSUE TITLE
All prompts generate this error: "prompt is too long: 200002 tokens > 200000 maximum"

### ISSUE THREAD

**Issue by uri100** [stackblitz/bolt.new#1871]
### Describe the bug

No matter what I write I get this error (even if I write "hi").  Tried refreshing the page since this solved this frequent  problem on previous ocassions, however this time around the problem persists. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jg9zcw

### Steps to reproduce

write any prompt

### Expected behavior

a response

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1322. It is likely the project is too large for the AI model's context window. That page contains some possible workarounds. Appreciate your patience as improvements continue to be made!
