### ISSUE TITLE
No characters being decoded

### ISSUE THREAD

**Issue by Sparks72** [stackblitz/bolt.new#1873]
### Describe the bug

No characters displayed / Decoded

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6vz8cr

### Steps to reproduce

click on "Start"
Allow Microphone

### Expected behavior

Decoded morse characters

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57105933,
  "usedJSHeapSize": 52931669,
  "jsHeapSizeLimit": 4294705152
}
Username = Sparks72
Chat ID = 423da74c398c
```

**Comment by endocytosis** [comment]
While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects.There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform.
