### ISSUE TITLE
Token limit has stopped the project

### ISSUE THREAD

**Issue by Grayjack64** [stackblitz/bolt.new#1874]
### Describe the bug

I cannot send any prompts without hitting the 200K token limit and do not see a way to get the token amount down.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-akendw

### Steps to reproduce

Attempt to write any prompt

### Expected behavior

A response

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/154e881e-8e28-4101-85a2-06543a55579b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows
Firefox

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1322), which provides additional context and also has a number of insights for using tokens most effectively.
