### ISSUE TITLE
Hours of work disappeared after the app got stuck

### ISSUE THREAD

**Issue by Bogatinovski** [stackblitz/bolt.new#1875]
### Describe the bug

I had worked for 4 hours and had a lot of generated code . Suddenly the app wouldn't launch even though there were no build errors  so I refreshed the browser. When I did, the whole conversation was gone! I lost a very valuable progress and I have to start from scratch now. I don't know if I will be able to instruct the AI to produce the same output again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vite-react-1sp6qu

### Steps to reproduce

1. Create new React Vite project from the started templates
2. Add 50+ prompts
3. Suddenly the react app won't launch within the editor
4. Refresh the browser
5. Your whole conversation is gone

### Expected behavior

1. Create new React Vite project from the started templates
2. Add 50+ prompts
3. Suddenly the react app won't launch within the editor
4. Refresh the browser
5. Continue where you left off with the existing conversation

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 39367456,
  "usedJSHeapSize": 38487244,
  "jsHeapSizeLimit": 4294705152
}
Username = bogatinovski
Chat ID = 18d791b039c6
```

**Comment by endocytosis** [comment]
Hi @Bogatinovski, 

Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in with the same credential as Bolt, clicking Collections on the left-hand side of the page, and then clicking Bolt Collection?

**Comment by Bogatinovski** [comment]
> Hi @Bogatinovski,
> 
> Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in with the same credential as Bolt, clicking Collections on the left-hand side of the page, and then clicking Bolt Collection?

Unfortunately no, I just checked and this collection is not there.

**Comment by Bogatinovski** [comment]
Actually, I think the project does appear in the Collections list **but** it only contains the default boilerplate code from the starter template I had selected. So it didn't actually save any of my code which was generated by bolt.new. Doesn't it auto-save? I am surprised that even now I created new project from scratch and when I checked in the Collections, the project there again doesn't contain my code.

**Comment by endocytosis** [comment]
Hi @Bogatinovski, 

Appreciate you sharing this information, it is helpful. If you are able, one more quick questions that will help the team further investigate this issue: 

1) Are you experiencing this with other Bolt projects or just this one? Have you created other Bolt projects where you have made changes to the code in Bolt but only see default starter template code in Collections?

Appreciate it!

**Comment by Bogatinovski** [comment]
I can confirm I have discovered the following scenarios:

**1. Create project through bolt.new** (Doesn't work)
- I go to bolt.new and from there create a new project by choosing the React template
- I generate some code with the AI
- I close the page and the go to [stackblitz.com](https://stackblitz.com/) and check the Collections menu
- I do see the collection but when I load it, it shows me the default template project and my code is missing
- I go back to bolt.new, open my project and here also I only see the template code

**2. Create project through [stackblitz.com](https://stackblitz.com/)** (Works)
- I go to [stackblitz.com](https://stackblitz.com/) and from there create a new project by clicking on + Create Project
- I select the React template and after init I click on "Open in bolt.new"
- The project loads in bolt and I write new code
- Then I close bolt and go back to stackblitz to reopen the project. Here I see my own code changes.
- When I go to Collections I don't see the project there but I do see it under Projects. I believe this may be expected.
- I go back to bolt.new, refresh my page and I still see my own changes.

I hope you'll be able to reproduce and fix this. It's too bad I lost 4 hours of work, 4M credits which I have to recharge now and most importantly an amazing outcome! 
But I fell in love with this product so it's all forgiven :) Keep up the amazing work.

Oh and one more glitch I noticed: On the projects created directly through bolt.new I am not able to edit the project name by double-clicking on it. Even if I open it through stackblitz collections I am still not able to edit it.

**Comment by endocytosis** [comment]
Hi @Bogatinovski, 

Really appreciate your detailed response here, this is extremely helpful! I will pass this along to the team so we can continue to make improvements. Thanks again!

**Comment by endocytosis** [comment]
Just re-opening this here to merge with #1954 where we are now tracking this issue. Again, thank you very much for the excellent feedback!
