### ISSUE TITLE
page loading

### ISSUE THREAD

**Issue by Stayfitapp** [stackblitz/bolt.new#1876]
### Describe the bug

When prompting bolt to make a landing page, it creates the code, but when I go to Preview it, nothing shows up. I've prompted to fix itself and restart npm run dev and nothing happens. I'm not a developer so I'm not sure what could be the issue. 
The code seems to be fine. There is no noted issue. I am just not able to preview the page like if something is wrong with the local host because I have tried opening it up in a different browser and is giving me a fail connect to server page. I haven't been able to see what it created and I've used all my tokens so I am not able to do anything else.
http://localhost:5173/

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gpy8yo

### Steps to reproduce

 I've prompted bolt to fix itself and restart npm run dev

### Expected behavior

load the preview page

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = Stayfitapp
Chat ID = 28b4b027f8de
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1791.

**Comment by Stayfitapp** [comment]
do you have any suggestions or what can I do to get it working. 
I was thinking about subscribing but I haven't been able to get it to work for the last couple days.
