### ISSUE TITLE
Cant deploy my project

### ISSUE THREAD

**Issue by scofieldd27** [stackblitz/bolt.new#1877]
### Describe the bug

Tried to deploy my project but its stucked in Build application for 3 hours now

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6hv2jb

### Steps to reproduce

Just try to deploy 

### Expected behavior

Nothing happend

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 324055977,
  "usedJSHeapSize": 316192373,
  "jsHeapSizeLimit": 4294705152
}
Username = scofieldd27
Chat ID = 8f8fa5f7ae8d
```

**Comment by kc0tlh** [comment]
@Really appreciate the detailed feedback here! We are tracking the build failure issue here: #2019
