### ISSUE TITLE
Nothing shows up in the Preview window.

### ISSUE THREAD

**Issue by seoninja13** [stackblitz/bolt.new#1878]
### Describe the bug

I ma seeing a blanks creen on the Preview window.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fdftvv

### Steps to reproduce

Preview window is blank.

### Expected behavior

I am expected to see the website display in the Preview window. I am getting a Blank screen.

### Screen Recording / Screenshot

blank screen

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61694476,
  "usedJSHeapSize": 54562624,
  "jsHeapSizeLimit": 4294705152
}
Username = seoninja13
Chat ID = 49917c59cac5
```

### Additional context

blank screen

**Comment by endocytosis** [comment]
Appreciate the feedback. This is a known issue and is being tracked here: #1791.
