### ISSUE TITLE
"Forbidden" error message

### ISSUE THREAD

**Issue by thaq1f** [stackblitz/bolt.new#188]
### Describe the bug

Hi there, I am not able to submit a prompt into the system. I would get a "forbidden" error message in my first prompt into the system. Initially thought it was because I had hit a limit in my request, but have subscribed to the pro plan and it still returns the same error message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n1wsau

### Steps to reproduce

1. Go to bolt.new
2. Write prompt and submit
3. Get "Forbidden" error message. 
4. Open a new chat - get the same error. 

### Expected behavior

The AI would start building based on the prompt. 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ba2017da-530d-48e8-92e5-6d2e684f1047)

### Platform

- OS: macOS 15.0.1 
- Browser: Arc 1.63.0

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77

**Comment by Nemikolh** [comment]
Hey @thaq1f! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by thaq1f** [comment]
Thanks Jòan! Very promising tech you guys are working on! ⚡️

**Comment by paulaboratory** [comment]
Same thing happen to me too!

![Uploading Screenshot 2024-10-08 232720.png…]()

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!

**Comment by shahidyousuf2023** [comment]
when i write a prompt in bolt.new then i face this error. there is any solution ??? 
{
"error": {
"type": "forbidden",
"message": "Request not allowed"
}
}

**Comment by talhary-dot** [comment]
```

{
"error": {
"type": "forbidden",
"message": "Request not allowed"
}
} 
``` 
getting same problem.

**Comment by khalidmaquilang** [comment]
> when i write a prompt in bolt.new then i face this error. there is any solution ??? { "error": { "type": "forbidden", "message": "Request not allowed" } }

Same.. im encountering this issue

**Comment by khalidmaquilang** [comment]
> ```
> 
> {
> "error": {
> "type": "forbidden",
> "message": "Request not allowed"
> }
> } 
> ```
> 
> getting same problem.

i didn't expect we posted at the same time haha i guess this is really their issue

**Comment by talhary-dot** [comment]
> > ```
> > 
> > {
> > "error": {
> > "type": "forbidden",
> > "message": "Request not allowed"
> > }
> > } 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > getting same problem.
> 
> i didn't expect we posted at the same time haha i guess this is really their issue

yup. we need to wait. I guess

**Comment by khalidmaquilang** [comment]
waiting...

**Comment by reyjun1992** [comment]
still an issue from my end

**Comment by kscheung1228** [comment]
same issues starting today !

**Comment by duongpro01** [comment]
same problem

**Comment by teDdyMucho** [comment]
Same here

**Comment by SteveAnh787** [comment]
:vvv same problem. Damm, I love this tool, and hope it will be fixed soon.

**Comment by reyjun1992** [comment]
same still issue! refund!

**Comment by mkrz-x** [comment]
Same, I want to continue fixing my project and can’t prompt anything; it just tells a forbidden error message.

**Comment by waqasaca** [comment]
i am facing this issue right now, what's going on ?

**Comment by dalerka** [comment]
Same here, just signed up and every prompt returns this error.

**Comment by teressawang** [comment]
Forbidden  too=== i Paid for your service.

**Comment by Cordalys** [comment]
I am running Bolt.new on Windows 11 Chrome and I receive the same forbidden message. Is there a solution to this problem. I have shut off and shut down everything including antiviruses to figure something out but nothing yet.

![Image](https://github.com/user-attachments/assets/40de0b15-adaf-4436-85f7-a5a918ba2e5d)

**Comment by tnlong311** [comment]
Same issue please fix, i paid for the premium version and cannot use for my work!

Tried to clear site data, sign up with a different account, create new project, connect to supabase,... none of these fixed the problem

![Image](https://github.com/user-attachments/assets/2e714d88-f6e2-4c91-b24f-776f57ffec38)

![Image](https://github.com/user-attachments/assets/17c44d7a-2dc3-428b-ac62-c6ed6fba0de3)

**Comment by gcyte** [comment]
![Image](https://github.com/user-attachments/assets/6e4ad5d7-fa90-4aab-9593-9603c9a9b591)

**Comment by reeve718** [comment]
![Image](https://github.com/user-attachments/assets/a1c74b2f-2924-42f6-ad0a-a6bf5480d7f2)

The app was good, but it is meaningless if can't use. GG for bolt.new

**Comment by abearxiong** [comment]
<img width="484" alt="Image" src="https://github.com/user-attachments/assets/8bf45018-939f-4709-a740-6c4ba20998c3" />
same ....

**Comment by Local911** [comment]
Same here

**Comment by labelhigh** [comment]
![Image](https://github.com/user-attachments/assets/799eb652-c7b6-41ff-be20-f23cb672db46)WHY!!!!    I'm so mad!!! Why does this error occur!!

**Comment by kscheung1228** [comment]
Just ask for refund like I did

**Comment by rafeeqkp** [comment]
is this issue resolved? I too facing the issue

**Comment by khalidmaquilang** [comment]
not yet

**Comment by abearxiong** [comment]
> is this issue resolved? I too facing the issue

也许是vpn导致的这个问题。我去掉就好了，日常使用地址切换了，他就报错了

**Comment by tnlong311** [comment]
it's been 3 days and the issue is not resolved yet
