### ISSUE TITLE
Half of the file is deleted after responding

### ISSUE THREAD

**Issue by sruthik27** [stackblitz/bolt.new#1880]
### Describe the bug

<img width="779" alt="image" src="https://github.com/user-attachments/assets/1f7737ba-e9e3-44fc-b17c-e5934861577a">
It gave the full file, but then upon finishing half of file is not there anymore

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1epidi

### Steps to reproduce

Just see the RoomForm.jsx 

### Expected behavior

Should always give and retain full code 

### Screen Recording / Screenshot

https://bolt.new/~/sb1-1epidi

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 81702115,
  "usedJSHeapSize": 62591931,
  "jsHeapSizeLimit": 4294705152
}
Username = sruthik27
Chat ID = cae39a313dea
```

**Comment by endocytosis** [comment]
Appreciate the feedback. Achieving desired output with AI is an area of [active research](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview). This issue [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on leveraging Bolt most effectively and maximizing token efficiency. At times the AI does not fully generate code and manual intervention is required. Hope this helps!
