### ISSUE TITLE
First time attempt: simply doesn't work.  Very disappointed

### ISSUE THREAD

**Issue by kbdguy** [stackblitz/bolt.new#1881]
### Describe the bug

I asked for something that I thought it would be able to do relatively easily: a simple CRUD application using angular.  It looked like it was doing useful work!  But in the end, I could never the the running app to display anything except a totally blank screen.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zxwbmi?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=sidebar

### Steps to reproduce

angular crud for {id:string,name:string,bday:Date}

### Expected behavior

a basic working CRUD application

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61322011,
  "usedJSHeapSize": 58464251,
  "jsHeapSizeLimit": 4294705152
}
Username = hangbouquet
Chat ID = 35c0aee39c30
```

### Additional context

It failed at first, saying there was an error with "ng serve"  It offered to "fix" it, and seemed to be happy with itself.  However, the running app displays absolutely nothing.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
