### ISSUE TITLE
Failed to Deploy

### ISSUE THREAD

**Issue by ezhulati** [stackblitz/bolt.new#1882]
### Describe the bug

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s6cb95

### Steps to reproduce

Try to deploy it. Im unable to. 

### Expected behavior

Should deploy to Netlify 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 240587482,
  "usedJSHeapSize": 229740538,
  "jsHeapSizeLimit": 4294705152
}
Username = ezhulati
Chat ID = 870a4719f930
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by ifeeltech** [comment]
I burned trough 5m tokens trying to deploy my app, going crazy right now

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
