### ISSUE TITLE
String to lonlg error

### ISSUE THREAD

**Issue by cp5337** [stackblitz/bolt.new#1889]
### Describe the bug

I keep getting the string to long error even with small commands.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-snwqto

### Steps to reproduce

Try to ask a question 

### Expected behavior

Command is carried out 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 135135696,
  "usedJSHeapSize": 120238772,
  "jsHeapSizeLimit": 4294705152
}
Username = cp5337
Chat ID = 1c181b859d9f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
