### ISSUE TITLE
NO output or creation 

### ISSUE THREAD

**Issue by kfrrst** [stackblitz/bolt.new#1891]
### Describe the bug

Nothing executed

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hn6n3l

### Steps to reproduce

When I creat a chat nothing happens 

### Expected behavior

The app to execute and write script

### Platform

```
Browser name = Safari
Full version = 17.3
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15
performance.memory = undefined
Username = kfrrst
Chat ID = 6d9ff3a53e67
```

**Comment by endocytosis** [comment]
At times there are programming challenges that are too complex for the AI to solve and manual intervention is required. Sometimes pasting any errors messages from the terminal into the chat is successful in resolving issues. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
