### ISSUE TITLE
No build logs present upon error in deployment

### ISSUE THREAD

**Issue by ahmad1702** [stackblitz/bolt.new#1895]
### Describe the bug

<img width="398" alt="Screenshot 2024-11-09 at 9 45 20 PM" src="https://github.com/user-attachments/assets/85432bff-d2b7-491d-b98e-c7c81618abcf">

I clicked on the "Deploy" button for a next app and it errored. but I didn't get any visibility behind why the build error happenned. This deploy button seems pretty misleading. Its deploying to netlify but it didn't ask me to setup a netlify account? Because of this i don't have access to neither the deployment nor any visibility from the bolt platform on why it failed deployment

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-g5pbwv

### Steps to reproduce

1. Create a next app
2. Make a change that might cause a deploy/build error
3. Hit deploy and initiate it

### Expected behavior

Would like to either get logs or have an option to link to a netlify account so i can go there and see the logs.

### Screen Recording / Screenshot

<img width="398" alt="Screenshot 2024-11-09 at 9 45 20 PM" src="https://github.com/user-attachments/assets/67149f26-8234-4f7c-b1e7-18623caafba5">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79344031,
  "usedJSHeapSize": 71746583,
  "jsHeapSizeLimit": 4294705152
}
Username = ahmad1702
Chat ID = 98f872f8a988
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
