### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [stackblitz/bolt.new#19]
### Describe the bug

It seemed to stream some code first while its first reponse is coming, but when it finishes the streaming, nothing, all empty, tried refereshing the page, still nothing
![image](https://github.com/user-attachments/assets/e3a4e85d-d1a4-4120-a5e9-05786f6023bf)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sdg8tr

### Steps to reproduce

just make it do any todo app, and maybe multiple-file app.

### Expected behavior

the code should just show and remain there

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by yilmazdurmaz** [comment]
Was there any files/folders, or nothing at all?

And please fill in the OS and browser details, as they seem to be very important details for this app.

**Comment by Ebrahim-Ramadan** [comment]
> Was there any files/folders, or nothing at all?
> 
> And please fill in the OS and browser details, as they seem to be very important details for this app.

there were 2 folders ig, and a bunch of files in them, I saw them progressing the stream as it went all fine, once finished, got nothing ( I MEAN NOTHING).

Windows 11, google chrome

**Comment by Ebrahim-Ramadan** [comment]
> Was there any files/folders, or nothing at all?
> 
> And please fill in the OS and browser details, as they seem to be very important details for this app.

there were 2 folders ig, and a bunch of files in them, I saw them all progressing thr streaming, once finished, I got nothing (I MEAN NOTHING).
win11, google chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by Elite** [comment]
Same issue here, it created a blank project and then when asked to create the file structure it stuck on the second file. Using Google Chrome (Version 129.0.6668.72 (Official Build) (arm64)) on MacOS 15.0

**Comment by madmaxbr5** [comment]
Same exact issue here. See code get written but then nothing is stored once the generation finishes. Chrome/OSX.

**Comment by madmaxbr5** [comment]
OK, it's definitely a chrome issue. It works in safari.

**Comment by mrmachine** [comment]
Same problem here in Edge, Chrome and Safari on macOS 14.

**Comment by samdenty** [comment]
This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back

**Comment by Ebrahim-Ramadan** [comment]
> This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back

this damn thing again

**Comment by Ebrahim-Ramadan** [comment]
> This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back

which commit did resolve this issue tho? I wanna dig in some more

**Comment by samdenty** [comment]
https://github.com/stackblitz/bolt.new/commit/6a9cb78fd64ffe30ac9546f59b0ae1063e7aa8ae
