### ISSUE TITLE
Bolt.new not previewing

### ISSUE THREAD

**Issue by videoplane** [stackblitz/bolt.new#1903]
### Describe the bug

Keeps giving me syntax error of one kind or a another.

SyntaxError: The requested module '/src/pages/auth/signup.tsx' does not provide an export named 'SignUpPage'

and its doing this again and again

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vvtflu

### Steps to reproduce

1. goto preview
2. see the error show up

### Expected behavior

just not previewing

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61931139,
  "usedJSHeapSize": 59527087,
  "jsHeapSizeLimit": 4294705152
}
Username = beatviral
Chat ID = bd293957c017
```

### Additional context

Im not a coder so dont know

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any errors messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!

**Comment by videoplane** [comment]
Thanks for that.
You tell a non coder that manual intervention is required and he won't
touch this app with a 10 foot pole.
I keep trying to build and it forgets and i have to go back over and over
again. Then there are errors that it fixes over and over again. Each time
eating tokens.
So is that ok? Hmm. I let it keep eating my tokens for fixing and breaking
then fixing again cos i am excited about the power i get as a non coder and
for what i am trying to accomplish, i dont mind it eating my tokens like
this but it still feels like im getting screwed but that's ok, the end will
justify the means. But the real issue is the time that i am spending,
that's my real cost.
I am ok to keep at it till a better platform comes around then i will never
look at this one again. Do you understand what I mean?
Today u got everyone to ride around in this broken system but what about
tomorrow?
I suggest you implement a 'refund token system' where at the end of the
build it calculates how many times it has screwed up and chewed the tokens
unfairly and refunds them. And for the time lost it could offer a perk.
This way you show the users you care and are aware of the difficulty and
you would create great loyalty and future proof the app.
This is just feedback and I really appreciate your work and I hope you get
it all running 100% soon in the future. And thanks for your hard work.
