### ISSUE TITLE
The prompt or the messages are too long

### ISSUE THREAD

**Issue by prensgold** [stackblitz/bolt.new#1904]
### Describe the bug

I deleted and reloaded the project, I could not overcome the error below even though I reopened the prompt. I want it to analyze an error from a very small .tsx file. I have never encountered such a problem before. I tried with chrome and firefox and got a similar error.

The prompt or the messages are too long

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-x2mdu5

### Steps to reproduce

![2024-11-10_12h57_21](https://github.com/user-attachments/assets/50f96971-d3d4-4057-9240-b5e35cf962a7)

### Expected behavior

I have never encountered such a problem before.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72400463,
  "usedJSHeapSize": 61630427,
  "jsHeapSizeLimit": 2197815296
}
Username = prensgold
Chat ID = f0f5f860fe06
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue related to the AI model's context window that we are tracking here: #1322.
