### ISSUE TITLE
Open in StackBlitz and Chat History also does not reflect the updated code.

### ISSUE THREAD

**Issue by donvito** [stackblitz/bolt.new#1908]
### Describe the bug

i lost the code in bolt for the workplace project https://bolt.new/~/bolt-shadcn-qucmqh. i noticed this when I opened in stackblitz and it didn't reflect the current source code

chat history does not reflect the source code too

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-shadcn-qucmqh

### Steps to reproduce

1. Created app using shadcn
2. Prompted to add features.
3. Open in StackBlitz
4. Code doesn't reflect the updated UI in preview
5. Refresh the page
6. Chat for this bolt does not reflect the current source code

### Expected behavior

This is the preview of the updated code
<img width="1714" alt="Screenshot 2024-11-10 at 8 04 17 PM" src="https://github.com/user-attachments/assets/f965887c-c328-4ab2-b2de-7ccc1465b646">

### Screen Recording / Screenshot

This is the code when opened in StackBlitz and from the chat history

<img width="1390" alt="Screenshot 2024-11-10 at 8 02 37 PM" src="https://github.com/user-attachments/assets/99998e50-7531-4fae-a8c4-56bae75cc8bc">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 137983896,
  "usedJSHeapSize": 111911948,
  "jsHeapSizeLimit": 4294705152
}
Username = donvito
Chat ID = fe938c15c7c3
```

### Additional context

Error:
```

```

**Comment by endocytosis** [comment]
Hi @donvito, 

Appreciate the feedback! We are tracking this issue here: #1954.
