### ISSUE TITLE
forbidden 

### ISSUE THREAD

**Issue by paradox626** [stackblitz/bolt.new#191]
### Describe the bug

the Bolt Chat interface is giving me an forbidden message 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2dkjdh

### Steps to reproduce

the Bolt Chat interface is giving me an forbidden message 

### Expected behavior

the Bolt Chat interface is giving me an forbidden message 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 159660012,
  "usedJSHeapSize": 134631496,
  "jsHeapSizeLimit": 2172649472
}
Username = paradox626
Chat ID = cf1336589aeb
```

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by Nemikolh** [comment]
Hey @paradox626! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
