### ISSUE TITLE
Application is Broken

### ISSUE THREAD

**Issue by cp5337** [stackblitz/bolt.new#1910]
### Describe the bug

Unable to prompt the application with any size string without receiving the string is too long message. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-snwqto

### Steps to reproduce

1. Run application until environment displays the main dashboard of the application. 2. enter a prompt of any size. 3. You will receive a string is too long. 

### Expected behavior

The AI agent should execute my request. 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/945a9649-42aa-4b1c-b512-5b50e20bc207)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 137531741,
  "usedJSHeapSize": 117762905,
  "jsHeapSizeLimit": 4294705152
}
Username = cp5337
Chat ID = e36914b1251c
```

### Additional context

I have rebooted the application and looked for solutions on the web.

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue related to the AI model's context window that we are tracking here: #1322.
