### ISSUE TITLE
Bolt AI stalls with a continuous loading circle on any task

### ISSUE THREAD

**Issue by Swelo-ui** [stackblitz/bolt.new#1911]
### Describe the bug

Whenever I attempt to perform any task in Bolt AI (like modifying, running, or deploying my app), it gets stuck with a continuous blue loading circle, and the task never completes. This issue is not specific to my app or any dependency installation—it's a general problem in Bolt AI’s processing. Please investigate the cause of the loading stall as it prevents me from completing any action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-p8pxb6

### Steps to reproduce

1 open bolt ai any previous project that are in forked 
2 then you say any prompt to bolt ai to modify the app.
3 so the bolt ai update is start the script is updated one by one
4 then you see the first script update is stuck in loading not completed and other script also struck then also bolt ai do all the work
5 but in app no changes come by this
6 even i open in stackblitz there also no changes in app because it stuck the loading on first script changes that seen in images which loading i say.

### Expected behavior

Please solve this as fast as because i not able to done my project if this happens then why i buy the premium plan 

### Screen Recording / Screenshot

![Screenshot_2024-11-04-19-30-21-46_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/3536cff0-d04c-4014-8084-cb2e12ab6de4)
![IMG_20241104_193044](https://github.com/user-attachments/assets/ea153b56-1f5d-4ded-97dc-36920a471cbf)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50943273,
  "usedJSHeapSize": 44296733,
  "jsHeapSizeLimit": 1275068416
}
Username = Laxmi222
Chat ID = 8f415d70b822
```

### Additional context

Just solve this

**Comment by endocytosis** [comment]
Hi @Swelo-ui, 

Bolt is most compatible with desktop based Chrome and Chromium browsers at this time, as opposed to mobile browsers. I would try continued development there. Hope this helps!

**Comment by Swelo-ui** [comment]
@endocytosis I used desktop chrome that's problem come in desktop, and i try in android by on the desktop mode in it , then also get this problem
