### ISSUE TITLE
prompt is too long: 202082 tokens > 200000 maximum

### ISSUE THREAD

**Issue by nullsoft8411** [stackblitz/bolt.new#1913]
### Describe the bug

i dont know if  that's a bug but i cant continue to work  on me projekt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3etkwa

### Steps to reproduce

implement another component on the projekt

### Expected behavior

he is implemententing a component on our projekt

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = nullsoft8411
Chat ID = 7a473df24499
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue related to the capacity of the AI model's context window that we are tracking here: #1322.
