### ISSUE TITLE
what happened to my previous chats?

### ISSUE THREAD

**Issue by searchursoul** [stackblitz/bolt.new#1914]
I created some chats and now they are gone. How can I get them back?

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
