### ISSUE TITLE
Chat history issue

### ISSUE THREAD

**Issue by johnarossman** [stackblitz/bolt.new#1918]
### Describe the bug

Chat history not saving on different computers using the same login. E.g. my phone doesn't show my chat history that's on my desktop.

### Link to the Bolt URL that caused the error

Bolt.new

### Steps to reproduce

Create a chat on your phone im using android 

Then login on a different device and the phone history is not there.

### Expected behavior

Chat history should be the same between devices.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @johnarossman, 

Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
