### ISSUE TITLE
Deploy this application.  prompt is too long: 203468 tokens > 200000 maximum

### ISSUE THREAD

**Issue by plataformaconcreta** [stackblitz/bolt.new#1919]
### Describe the bug

Deploy this application.

prompt is too long: 203468 tokens > 200000 maximum
<img width="569" alt="Screenshot at Nov 10 15-05-01" src="https://github.com/user-attachments/assets/d5b3eb33-c4a9-412e-b610-7c9e34452095">

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-d25wtv-yly29s

### Steps to reproduce

Deploy this application.

prompt is too long: 203468 tokens > 200000 maximum

### Expected behavior

Deploy this application.

prompt is too long: 203468 tokens > 200000 maximum

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109490444,
  "usedJSHeapSize": 106449356,
  "jsHeapSizeLimit": 2160066560
}
Username = plataformaconcreta
Chat ID = 81d91a1c0b0d
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1322.
