### ISSUE TITLE
no preview available

### ISSUE THREAD

**Issue by paulgosnell** [stackblitz/bolt.new#192]
### Describe the bug

no preview available
not sure if anything is working
bolt can't fix and recommended I contact stackblitz

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-akhj1n

### Steps to reproduce

1. open project
2. nothing happens
3. ask bolt 10+ times to fix and it can't 

### Expected behavior

preview pane to show application

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103390149,
  "usedJSHeapSize": 78756685,
  "jsHeapSizeLimit": 2172649472
}
Username = paulgosnell
Chat ID = 6c2774f14864
```

**Comment by fixfounder** [comment]
@paulgosnell When I'm using 'Vite', I type 'vite preview' in the terminal, and it has helped.

**Comment by Jimmy-Jim-J** [comment]
I am experiencing the same issue, where the preview doesn't preview.
Have been an issue since using  and paying subscription 

Any advice would be appreciated.

**Comment by DSchallenberg** [comment]
I have the same issue since I subscribed. Even in projects created after subscribing

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback. We are aware of this issue and are tracking it here: #1791.

**Comment by karenlin813** [comment]
I have the same issue no preview available Even in projects created after subscribing

**Comment by ngchi** [comment]
I have the same issue

**Comment by Appsorwebs** [comment]
Please any fix to this No preview available problem on Bolt.diy?

**Comment by Recreabox** [comment]
Same issue on Bolt.diy

**Comment by Hey-Okay** [comment]
Same issue!
