### ISSUE TITLE
I keep getting this error after a project grows big

### ISSUE THREAD

**Issue by Mapalo2023** [stackblitz/bolt.new#1920]
### Describe the bug

I keep getting this annoying error: 
prompt is too long: 202764 tokens > 200000 maximum

each time a project grows large. and its hard to move on from here, despite any prompt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n4xars

### Steps to reproduce

while building an app, if it grows large enough, you stat getting this error, at almost every request

### Expected behavior

I expect it to work well 

### Screen Recording / Screenshot

![Screenshot 2024-11-10 101611](https://github.com/user-attachments/assets/d52cf21b-1e8f-4eae-ae9d-12d11e0c024f)

### Platform

- OS: [Windows]
- Browser: Chrome
- Version: [e.g. 91.1]

### Additional context

.

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it here: #1322. Appreciate your patience as Bolt continues to improve!
