### ISSUE TITLE
missing texts

### ISSUE THREAD

**Issue by sarr43** [stackblitz/bolt.new#1921]
### Describe the bug

my texts are missing

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7qghu6

### Steps to reproduce

show and translate all texts

### Expected behavior

show and translate all texts

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109130527,
  "usedJSHeapSize": 98643751,
  "jsHeapSizeLimit": 4294705152
}
Username = aliyunsaar
Chat ID = 254e0a3e5f1a
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
