### ISSUE TITLE
App will not deploy on Netlify

### ISSUE THREAD

**Issue by ezhulati** [stackblitz/bolt.new#1924]
### Describe the bug

An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s6cb95

### Steps to reproduce

Deploy

### Expected behavior

Should have deployed to Netlify 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 305788166,
  "usedJSHeapSize": 297086958,
  "jsHeapSizeLimit": 4294705152
}
Username = ezhulati
Chat ID = 870a4719f930
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #499.
