### ISSUE TITLE
bug1

### ISSUE THREAD

**Issue by Nag-786** [stackblitz/bolt.new#1925]
### Describe the bug

[plugin:vite:react-babel] /home/project/src/components/Experience.tsx: Unexpected token, expected "," (12:52)
  15 |         'Maintain and improve the website by developing new user-facing and mobile-based features.',

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tdwf27

### Steps to reproduce

[plugin:vite:react-babel] /home/project/src/components/Experience.tsx: Unexpected token, expected "," (12:52)
  15 |         'Maintain and improve the website by developing new user-facing and mobile-based features.',

### Expected behavior

preview should be shown

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66847866,
  "usedJSHeapSize": 56251966,
  "jsHeapSizeLimit": 2089549824
}
Username = Nag-786
Chat ID = f10a55acf676
```

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking it here: #1791.
