### ISSUE TITLE
Cancellation

### ISSUE THREAD

**Issue by pacers3** [stackblitz/bolt.new#1928]
### Describe the bug

Please cancel the plan associated with oryanhs@gmail.com effective immediately. 

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

Please cancel the plan associated with oryanhs@gmail.com effective immediately. 

### Expected behavior

Please cancel the plan associated with oryanhs@gmail.com effective immediately. 

### Screen Recording / Screenshot

Please cancel the plan associated with oryanhs@gmail.com effective immediately. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Please cancel the plan associated with oryanhs@gmail.com effective immediately.

**Comment by endocytosis** [comment]
Hi @pacers3,

From the homepage of bolt.new hover over the left-hand side. A menu will appear. Click "My Subscription", the click "Manage current plan". From here, you will be brought to the StackBlitz Billing Portal where you can update or cancel your subscription. If you need further assistance, please reach out to hello@stackblitz.com.
