### ISSUE TITLE
failing to deploy

### ISSUE THREAD

**Issue by CreatestudioAI** [stackblitz/bolt.new#1929]
### Describe the bug

failing to deploy. only message  is this - Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-y6snup

### Steps to reproduce

?

### Expected behavior

n/a

### Screen Recording / Screenshot

n/a

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92408458,
  "usedJSHeapSize": 84240642,
  "jsHeapSizeLimit": 4294705152
}
Username = CreatestudioAI
Chat ID = 07f7cb1dc038
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by jpeguero** [comment]
Can't deploy

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
