### ISSUE TITLE
Preview not loading

### ISSUE THREAD

**Issue by The-Alcademy** [stackblitz/bolt.new#1930]
### Describe the bug

I can't get the preview to work. Bolt keeps telling me that it has fixed the problem, but the same messages keep appearing in the developer console.
![image](https://github.com/user-attachments/assets/2b02a356-ce10-4dec-b889-aa590c875a95)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mphscn

### Steps to reproduce

When I click on the preview tab, I expect the preview to open.

### Expected behavior

The preview should open.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e538fb13-cb66-477a-a8c6-e98d6b79d1a8)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74269402,
  "usedJSHeapSize": 66670542,
  "jsHeapSizeLimit": 4294705152
}
Username = othersyde
Chat ID = cafe5aa49298
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing "npm run dev" in the Bolt console to see if this resolves the issue. Appreciate your patience as improvements continue to be made!
