### ISSUE TITLE
"npm run dev:all" returns an error each time it is called

### ISSUE THREAD

**Issue by clee100** [stackblitz/bolt.new#1932]
### Describe the bug

<img width="294" alt="image" src="https://github.com/user-attachments/assets/1a1f0e79-4597-4bfe-adeb-d90d003030f9">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-23sqvg

### Steps to reproduce

Software is amazing btw. My project uses express server and saves data to json files so Bolt wants to use the this "npm run dev:all" command to start the frontend and backend at the same time but it always returns an error. I've asked it to stop using this command but it will not change it's behavior. I'm able to work around it by prompting it to "run app" but I thought you should know.

### Expected behavior

use "npm run dev:all" without returning an error

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@clee100 perhaps adjusting the scripts in package.json would resolve this.
