### ISSUE TITLE
Bolt.new - Losing session 

### ISSUE THREAD

**Issue by sunilrw** [stackblitz/bolt.new#1933]
### Describe the bug

- Each time I refresh the page, my session ends, which is quite frustrating.  
- Additionally, I encountered difficulty in locating the project I’m currently working on; I only managed to find it after some effort through the link provided at https://stackblitz.com/.  
- Furthermore, when I attempt to reload my work, the source code does not display in its entirety, making it challenging to review or continue my project.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tdxxvu

### Steps to reproduce

Steps to Recreate the Bug:

1. Open Google Chrome on your Windows 11 computer.

2. Create a New Account:
   - Go to the website where you want to create an account.
   - Follow the prompts to sign up for a new account.

3. Log In to Your Account:
   - Enter your credentials to log in.

4. Create a New Project:
   - Navigate to the section of the site where you can create a project.
   - Follow the on-screen instructions to set up a new project.

5. Refresh the Page:
   - Once your project is created, click the refresh button or press F5 on your keyboard to refresh the page.

After completing these steps, you will lose the session 

### Expected behavior

It should keep my old session 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52972153,
  "usedJSHeapSize": 46770745,
  "jsHeapSizeLimit": 4294705152
}
Username = sunilrw
Chat ID = a0ae31280988
```

**Comment by jackccrawford** [comment]
Same problem here.  Rather important for Bolt to make savepoints after each prompt, or keep logs.  Logs are the most faithful method to restore to point in time.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
