### ISSUE TITLE
Feature Request: Increase Context Limit to Support Larger Projects

### ISSUE THREAD

**Issue by websitefox** [stackblitz/bolt.new#1934]
**Is your feature request related to a problem? Please describe:**

Our AI product is incredibly useful, but the current context limit of 200,000 characters is restrictive for larger projects. This limitation impacts the scale and functionality of projects, which affects the user experience.

**Describe the solution you'd like:**

Ideally, increasing the context limit or providing a method to bypass this restriction would allow the product to handle more extensive data, enhancing its capabilities.

**Describe alternatives you've considered:**

I've considered processing data in smaller batches or breaking down tasks, but this approach is complex and reduces efficiency. A more straightforward solution to the capacity limitation would be preferable.

**Additional context:**

Increasing the context limit would greatly expand the product’s applicability and improve the user experience.

**Comment by endocytosis** [comment]
Agreed and appreciate the feedback! Challenges with context window size is being tracked here: #1322. That page contains some helpful insights on ways to maximize token efficiency.
