### ISSUE TITLE
Image Upload / CORS to Firebase is Undefeated

### ISSUE THREAD

**Issue by Frankg40** [stackblitz/bolt.new#1939]
### Describe the bug

I cannot get images to upload to Firebase.

I've done every single suggestion by Bolt and chatGPT. Ive updated cors via firebase and Googles CLI. I've done every single suggestion.

I'm starting to think that it's because the web container URL is dynamic?

However a buddy started a new project and put his firebase database into dev mode and he can upload images.

So I just dont know what to do to fix it. I've probably got 10 hours+ on it.

Anybody?

### Link to the Bolt URL that caused the error

bole.new

### Steps to reproduce

Upload on profile page

### Expected behavior

Images should upload

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately we aren't able to offer support of individual coding projects. However, the [Firebase Documentation](https://firebase.google.com/docs/storage/web/upload-files) might be helpful. Additionally, the [StackBlitz Discord](https://stackblitz.gg/discord) has some threads where individuals offer insights on programming projects. Hope this helps!
