### ISSUE TITLE
Allow opening from a git (or already imported stackblitz) repo

### ISSUE THREAD

**Issue by Mearman** [stackblitz/bolt.new#194]

**Comment by kc0tlh** [comment]
@Mearman thanks for the great feedback. Both of these are now live on production:

Importing repos from github: https://x.com/stackblitz/status/1843668731681267801

Import projects from StackBlitz:
![image](https://github.com/user-attachments/assets/6461a8b7-5712-4a21-93e6-cea60e1441e8)

**Comment by Mearman** [comment]
thank you as a stopgap I made a bookmarklet
```javascript
javascript: (function () {
	var url = window.location.href;
	var match = url.match(/github\.com\/([^\/]+\/[^\/]+)/);
	if (match) {
		var repo = match[1];
		var newUrl = "https://bolt.new/~/github.com/" + repo;
		window.open(newUrl, "_blank");
	} else {
		alert("Not a valid GitHub repository URL.");
	}
})();
```

**Comment by kc0tlh** [comment]
@Mearman yep, that should continue to work!
