### ISSUE TITLE
preview too long to display

### ISSUE THREAD

**Issue by LaurentBarbareau** [stackblitz/bolt.new#1940]
### Describe the bug

It takes too long to display the content of the interface of my app in the preview tab.
I thought there was an error into my app then I said it multiple times to bolt so my free tokens are out now for today...

maybe this can help
![image](https://github.com/user-attachments/assets/ca502d48-2d0e-4cd9-abe7-c24b4df188d0)

I deactivated my AdBlocker but same problem.

Same problem also with Chrome : 24s to display the content 
![image](https://github.com/user-attachments/assets/29240d37-2970-4e0b-8a8c-4493741bbdbe)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cofqby

### Steps to reproduce

I just entered my initial prompt

### Expected behavior

running faster

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = LaurentBarbareau
Chat ID = d24503858366
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing "npm run dev" in the Bolt console to see if that resolves the issue. Appreciate your patience and improvements continue to be made!
