### ISSUE TITLE
my project chat desapear

### ISSUE THREAD

**Issue by nomadestudio067** [stackblitz/bolt.new#1941]
### Describe the bug

I paid for tokens and used 400k of them. My project was practically done... but when I reconnected to finish, it disappeared.

### Link to the Bolt URL that caused the error

I only have my account url

### Steps to reproduce

I dont know? maybe logout and log in

### Expected behavior

Can I take back my project? or tokkens?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi all, 

We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made!
