### ISSUE TITLE
preview not showing 

### ISSUE THREAD

**Issue by saisolomon** [stackblitz/bolt.new#1942]
### Describe the bug

When bolt finishes coding it says the app is ready in preview but nothing is there.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-61k78g

### Steps to reproduce

1. Create a prompt
2. wait for bolt to code
3. click preview

### Expected behavior

When the code is finished I expected to see what I created in the preview 

### Platform

```
Browser name = Safari
Full version = 17.5
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
performance.memory = undefined
Username = saisolomon
Chat ID = bf15378084e7
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is known issue and we are tracking it here: #1791.
