### ISSUE TITLE
prompt is too long: 200011 tokens > 200000 maximum

### ISSUE THREAD

**Issue by theteam123** [stackblitz/bolt.new#1943]
### Describe the bug

Bug Report: Receiving "Prompt too long" error despite single paragraph input

I am encountering an error message indicating the prompt is too long, however the prompt I'm attempting to use consists of only one paragraph. This appears to be unexpected behavior since such a short input should be within normal length limits.

The issue initially occurred when using a particularly long prompt, but appears to have caused a persistent system lock-up. Now every prompt, regardless of length, triggers the same error message.

"Let's temporarily disable all user authentication and permissions to allow unrestricted access throughout the application. We can implement the proper authentication and permission systems later - for now I just need to focus on building out the core app functionality."

### Link to the Bolt URL that caused the error

https://bolt.new/~/the-team-app-r1-4-rvgyrp

### Steps to reproduce

"Let's temporarily disable all user authentication and permissions to allow unrestricted access throughout the application. We can implement the proper authentication and permission systems later - for now I just need to focus on building out the core app functionality."

### Expected behavior

My prompts should work :)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76189047,
  "usedJSHeapSize": 71579847,
  "jsHeapSizeLimit": 4294705152
}
Username = theteam123
Chat ID = 171e505cbe39
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is known issue with the AI model's context window which is being tracker here: #1322.
