### ISSUE TITLE
Improvement Suggestion:

### ISSUE THREAD

**Issue by Progggggggg** [stackblitz/bolt.new#1944]
First of all, I would like to thank you for the development of the platform, which has been essential in my daily work and has optimized my workflow. However, I am encountering a limitation when developing applications that need to be integrated with existing ones. Currently, when uploading files, the platform allows a maximum of 5 files at a time, which complicates the integration of larger projects.

I suggest two possible improvements to optimize this process:

GitHub Integration: Allow me to directly link a GitHub repository. This would facilitate complete project imports and simplify version and code update management.

Increase File Upload Limit: Expanding the upload limit to more than 5 files, or enabling bulk uploads (by folder), would significantly help in integrating and modifying complex applications.

These improvements would make the development process more agile, especially when working with applications that require multiple dependencies or components.

Congratulations to the team on the excellent work! The platform has been an incredible asset to my development.

**Comment by endocytosis** [comment]
Hi @Progggggggg, 

Appreciate the feedback! The team is hard at work improving GitHub integration (currently, you can open public repositories by prepending bolt.new in front of the repository URL as follows: https://bolt.new/[REPOSITORY URL]). Regarding increasing file upload limit, will pass this along to the team. Glad to hear Bolt has been working well for you!
