### ISSUE TITLE
Is the Token Limit in Plans Applied Monthly or Daily?

### ISSUE THREAD

**Issue by Progggggggg** [stackblitz/bolt.new#1945]
Hello, everyone! I have a question regarding the token limits in the plans offered by the platform. Does the token limit apply to monthly usage or is it reset daily? Any clarification would be greatly appreciated. Thank you!

**Comment by Annawoody** [comment]
The token limit usually depends on the specific platform or service you're using. For some services, token limits might reset monthly, while others might reset daily. It’s best to check the specific terms and conditions of the platform you’re referring to. If you have more details about the platform, I can try to help you find more precise information!
@Progggggggg

**Comment by adamfils** [comment]
Monthly @Progggggggg

**Comment by endocytosis** [comment]
Hi all, 

Here is the token information: 

**Free Accounts: ** 150,000 token daily limit and 1,000,000 token monthly limit 
**Paid Accounts: ** There are no daily token limits. However, unused tokens for monthly plans do NOT roll over to the subsequent month.
