### ISSUE TITLE
I can't reach the project

### ISSUE THREAD

**Issue by umut1993** [stackblitz/bolt.new#1946]
### Describe the bug

While I was developing a project, I looked at the payment plans and it redirected me to a different page and I cannot access that project.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-unjncx

### Steps to reproduce

...vsfgsdf

### Expected behavior

help me achieve the project

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
