### ISSUE TITLE
I just see a blank screen after the code is complete

### ISSUE THREAD

**Issue by ianb0688** [stackblitz/bolt.new#1947]
### Describe the bug

Hello, I have signed up to a paid account tonight and I am trying to get an MVP ready on my first project. I only see a blank white screen in the preview window. It did show a version one time but when I asked to change the UI colours, bolt said it was complete but again, only a white screen.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-axwbuu

### Steps to reproduce

Prompt bolt for my app

### Expected behavior

To see the front end of the web app

### Screen Recording / Screenshot

<img width="2056" alt="Screenshot 2024-11-10 at 22 56 24" src="https://github.com/user-attachments/assets/2063e076-6cf6-4ac1-b32c-af36e54200e4">
<img width="2056" alt="Screenshot 2024-11-10 at 22 56 32" src="https://github.com/user-attachments/assets/35fd17fe-d503-4386-9616-b4587af72512">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking it here: #1791.
