### ISSUE TITLE
chat history

### ISSUE THREAD

**Issue by MSIMHI** [stackblitz/bolt.new#1948]
**Is your feature request related to a problem? Please describe:**

Why i don't see my chat history and the prompt i submitted?
**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
