### ISSUE TITLE
In Progress Project disappeared.

### ISSUE THREAD

**Issue by Raspin247** [stackblitz/bolt.new#1949]
### Describe the bug

The projects I spent my first months tokens working on have all disappeared from the chat menu. Please let me know how to recover them, see the attached image showing the menu bar empty.
![image](https://github.com/user-attachments/assets/32299311-7c93-436d-b593-891fe9e12730)

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Open my account

### Expected behavior

I expect my project to be visible in the menu.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/7a44ca8d-feb9-4e55-b820-05184ada15f3)

### Platform

- OS: Windows
- Browser: Chrome
- Version 128.0.6613.113 (Official Build) (64-bit)

**Comment by Annawoody** [comment]
can you give more details about it ?
@Raspin247

**Comment by Raspin247** [comment]
Hi Anna

I had two or three projects in my menu bar, I had spent a lot of time on
the one at the following link:
https://rococo-hamster-0807b9.netlify.app/uniformat/a/a10/lod100

I had not coded in Bolt.new for the last week or so but came back to log in
today and I don't see any of my projects.

The one redlined below was created when I tried to chat to Bolt to recover
my projects.

Is this enough, please recover my project if possible.

Cheers
Rick
[image: image.png]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.

**Comment by Raspin247** [comment]
Appreciate the speedy feedback!

I'm back into it, thank you all good :-)

Cheers
Rick

**Comment by Raspin247** [comment]
Hello I placed this Issue below a good while ago without any response. Are
you able to provide me an update as it seems strange because the team
responded so quickly with my first issue.

https://github.com/stackblitz/webcontainer-core/issues/1619

Cheers
Rick
