### ISSUE TITLE
bro. this app does not listen.. and runs in circles..... Burning tokens on doing nothing...

### ISSUE THREAD

**Issue by CitizenCapet** [stackblitz/bolt.new#1950]
### Describe the bug

No matter what i ask . it just re-writes the code base and does nothing. different .. fucking annoying. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/xuv5pg

### Steps to reproduce

Im tired of typing

### Expected behavior

Im tired of typing

### Screen Recording / Screenshot

Im tired of typing

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 354802082,
  "usedJSHeapSize": 321297986,
  "jsHeapSizeLimit": 4294705152
}
Username = CitizenCapet
Chat ID = 2edb7376b03f
```

### Additional context

Im tired of typing

**Comment by endocytosis** [comment]
Appreciate the feedback. Achieving desired output with AI is an area of [active research](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview). This issue [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on leveraging Bolt most effectively and maximizing token efficiency. Additionally, you can right-click a file in the Bolt code editor and select  "Lock file" to prevent the AI from making further changes to that file. You are able to do this with multiple files. Hope this helps!
