### ISSUE TITLE
i upgraded my subscription and my chat history is gone 

### ISSUE THREAD

**Issue by rookie7312** [stackblitz/bolt.new#1952]
### Describe the bug

i upgraded my subscription and my chat history is gone 

### Link to the Bolt URL that caused the error

i upgraded my subscription and my chat history is gone 

### Steps to reproduce

i upgraded my subscription and my chat history is gone 

### Expected behavior

i upgraded my subscription and my chat history is gone 

### Screen Recording / Screenshot

i upgraded my subscription and my chat history is gone 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

i upgraded my subscription and my chat history is gone

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
