### ISSUE TITLE
Bolt project in StackBlitz just boilerplate template, does not reflect file changes

### ISSUE THREAD

**Issue by endocytosis** [stackblitz/bolt.new#1954]
**Issue**: The user creates a project in Bolt and prompts the AI to make some changes, which are then reflected in the application files and preview window. The user then opens the project in StackBlitz, but the files do not reflect the changes made, and instead exist as the initial, boilerplate template. Often the project is present in the Bolt Collection on StackBlitz, but the files do not reflect the changes made, and instead also exist as the initial, boilerplate template.

[Video Repro Here](https://us06web.zoom.us/clips/share/IBMT4aRMaqEKHT1CSirlyq9AAjw0XhJfqGpwUcU1LYMlYOHPGZtkHxyzvH3xmCNtfr-qBREg-p6SVXQSONDoP0tl.qQTdA-vOsuRWwLaZ) & [Detailed Repro Instructions Here](https://github.com/stackblitz/bolt.new/issues/1875#issuecomment-2466456966) & [Report from @donvito here](https://github.com/stackblitz/bolt.new/issues/1908#issue-2647174686)

Possibly related to general issues with persistence tracked in: #39, but definitely a distinct issue

**Comment by Arcade1080** [comment]
Will it be fixed soon and will the lost work be available again? If not, could I get a refund on the used tokens?

**Comment by endocytosis** [comment]
**Update:** Hi all, this issue should now be resolved. Changes made in Bolt should be reflected in the associated project on StackBlitz. For existing projects, you can look for a backup in Bolt by going to Settings > Backups to load a project from previous state.
