### ISSUE TITLE
forbidden issue

### ISSUE THREAD

**Issue by rhino-acoustic** [stackblitz/bolt.new#196]
### Describe the bug

forbidden issue

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ffgz2n

### Steps to reproduce

after prompt, it should generate an answer based on what i have prompt

### Expected behavior

after prompt, it should generate an answer based on what i have prompt

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 84477270,
  "usedJSHeapSize": 78939046,
  "jsHeapSizeLimit": 4294705152
}
Username = rhino-acoustic
Chat ID = 1951f632e556
```

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by Nemikolh** [comment]
Hey @rhino-acoustic! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
