### ISSUE TITLE
prompt is too long: 200XXX tokens > 200000 maximum

### ISSUE THREAD

**Issue by tokieda0610** [stackblitz/bolt.new#1960]
### Describe the bug

頻繁に起こるエラーです。
ページリロードすると直る時はありますが、一度起こるとそのプロジェクトでは毎回起こり使えなくなります。
対策として、StackBlitzの方で保存と fork を使ってバックアップを取っています。
このエラーが起こると、バックアップで前のバージョンからやり直すと続けることができることがあります。
ただし、前のバージョンなので再度同じ更新をしないといけないため、更新分のトークンが無駄になります。
大きめのプロジェクトになりつつあるので、プロジェクトの大きさ（ファイル数やメモリ使用量など）がエラーが出る原因でしょうか。
これまで多くの課金をして作成したプロジェクトなので使えなくなるのは非常に困ります。早く直ってほしいです。

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cgzdnr

### Steps to reproduce

...

### Expected behavior

...

### Platform

- OS: macOS
- Browser: Chrome
- Version: 最新

**Comment by adamfils** [comment]
Open the project in StackBlitz and create an ignore file in .bolt directory
.bolt/ignore

Then specify the files you want bolt to ignore so you don't exceed the prompt limit
Example

src/context/*
src/styles/*
src/components/Splash/*
src/utils/TokenManager.ts
src/components/Dashboard/BottomNav/*

Hope this helps

**Comment by tokieda0610** [comment]
@adamfils 

Thank you very much for your response to my issue !
Your detailed explanation and guidance helped me solve the problem. 
I really appreciate your time and support. 
It was a great help !
