### ISSUE TITLE
Won't Move Buttons When Requested

### ISSUE THREAD

**Issue by mel895** [stackblitz/bolt.new#1961]
### Describe the bug

I'm continually telling the AI to move the category buttons and it won't.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uryp4i

### Steps to reproduce

I don't understand.

### Expected behavior

The category buttons are supposed to be moved, and the AI cannot move them to the appropriate place.

I've requested about 25 times and the buttons have not shifted.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ef783d94-08e5-4ff5-b544-7c266ac20250)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 192585735,
  "usedJSHeapSize": 164622223,
  "jsHeapSizeLimit": 2160066560
}
Username = mel895
Chat ID = 1333465ca865
```

### Additional context

Why am I paying when nothing happens?

**Comment by endocytosis** [comment]
While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects.

There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform.

At times, there are programming problems that are too complex for the AI to solve and require manual intervention.
