### ISSUE TITLE
npm dependicies 

### ISSUE THREAD

**Issue by SYasJ** [stackblitz/bolt.new#1962]
### Describe the bug

When bot run the package.js and then npm dependencies "npm install"it keep going in circle and when error show and ask to fix it it goes thru updating the code again and try to run npm dependencies to install. 
Error "~/project
❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-11T04_19_30_595Z-debug-0.log"

and second time 

"/project 1s
❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-11T04_25_46_196Z-debug-0.log"
3rd time 
/project 5s
❯ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: kr8iv-agency@0.0.0
npm WARN Found: eslint@9.12.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^8.45.0" from the root project
npm WARN   4 more (@eslint-community/eslint-utils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@">=7" from eslint-plugin-react-refresh@0.4.12
npm WARN node_modules/eslint-plugin-react-refresh
npm WARN   dev eslint-plugin-react-refresh@"^0.4.3" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: kr8iv-agency@0.0.0
npm WARN Found: vite@5.4.8
npm WARN node_modules/vite
npm WARN   dev vite@"^4.4.5" from the root project
npm WARN   1 more (@vitejs/plugin-react)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vite@"^4.2.0 || ^5.0.0" from @vitejs/plugin-react@4.3.2
npm WARN node_modules/@vitejs/plugin-react
npm WARN   dev @vitejs/plugin-react@"^4.1.0" from the root project
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-11T04_28_49_040Z-debug-0.log

~/project 12m 24s
❯ npm run dev

> kr8iv-agency@0.0.0 dev
> vite

jsh: command not found: vite

~/project
❯ 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a3sucs

### Steps to reproduce

Prompt
Agree on the changes
Deployment process
Error

### Expected behavior

it suppose to show me a landing page for a website

### Screen Recording / Screenshot

<img width="486" alt="Screen Shot 2024-11-10 at 9 30 38 PM" src="https://github.com/user-attachments/assets/78302220-f3de-41ae-9aa9-5fb11204e130">
<img width="898" alt="Screen Shot 2024-11-10 at 9 37 28 PM" src="https://github.com/user-attachments/assets/9d6dd4f5-87bc-4a3a-8e1d-71650df90357">
<img width="523" alt="Screen Shot 2024-11-10 at 9 30 53 PM" src="https://github.com/user-attachments/assets/8ca65ea5-e89c-45e7-a951-9a028adce681">

<img width="951" alt="Screen Shot 2024-11-10 at 9 41 46 PM" src="https://github.com/user-attachments/assets/8d8bb12c-0128-47b9-93bf-d1bd0ade7853">
<img width="1624" alt="Screen Shot 2024-11-10 at 9 45 40 PM" src="https://github.com/user-attachments/assets/af6da74e-ca1b-48ef-addb-b11ece3bbe54">

### Platform

Safari and Chrome on Mac

### Additional context

This is not acceptable when paying $50/monthly and not even able to get single product worked. when I used a free it has no issue. Got this subscription so don't have to worry running on my system

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021

**Comment by endocytosis** [comment]
Hi @SYasJ, 

Would you be able to set your project permission to "Private (accessible by URL)" by clicking the lock icon next to the project title so we can take a closer look? Refund requests are handled through hello@stackblitz.com. Thanks!
