### ISSUE TITLE
 An unknown error occured while running an action.

### ISSUE THREAD

**Issue by lorisd5** [stackblitz/bolt.new#1963]
### Describe the bug

The app was created and I clicked the deploy button and I got an error message. So I tried again and got this message: 
You have hit the rate limit. Please Upgrade to keep chatting, or you can continue coding for free in the editor. I don't need to chat I just want to launch it.How many tokens does it take to launch once it's created? 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ffyg7z

### Steps to reproduce

1 Deploy this application.  
2 build application npx vite build
3 deploy to netlify

### Expected behavior

I expected it to launch the app

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84097634,
  "usedJSHeapSize": 73576134,
  "jsHeapSizeLimit": 2061238272
}
Username = lorisd5
Chat ID = f2de63870aa3
```

### Additional context

Error:
```
You have hit the rate limit. Please <a class="__boltUpgradePlan__">Upgrade</a> to keep chatting, or you can continue coding for free in the editor.
```

**Comment by endocytosis** [comment]
Hi @lorisd5, 

The amount of tokens required to launch a project would depend on the nature and size of the project. More information on using Bolt most effectively and maximizing token efficiency can be found here: #678. Hope this helps!
