### ISSUE TITLE
I lost everything. This is unacceptable.

### ISSUE THREAD

**Issue by pjasak** [stackblitz/bolt.new#1964]
### Describe the bug

I subscribed to the $20 package. I worked for a few hours on the project and after refreshing the browser with F5, I lost everything. This is unacceptable.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-baixr6

### Steps to reproduce

1. Click to F5

### Expected behavior

Back to my previous version.

### Platform

- Windows
- Firefox 132.0.1

**Comment by pjasak** [comment]
I started again from the beginning, however after just half an hour, Bolt deleted half of my functions. It completely lost track.

Before putting Bolt.new online, you should have tested it.

The solution is excellent and very useful. If it worked properly, every dollar paid would be worth it. This way you will lose many clients.

**Comment by dukuo** [comment]
bro is really saying unacceptable on an OSS project 💀

**Comment by pjasak** [comment]
I tried for the third time from scratch.

Bolt doesn't follow the code from the beginning, but generates it anew each time, so parts of the application that were finished get completely changed or deleted and something entirely different is offered instead. It even changes or deletes user interface elements. Very frustrating.

Please fix all these bugs as soon as possible, because the idea is excellent and revolutionary.

**Comment by jackccrawford** [comment]
> I tried for the third time from scratch.
> 
> Bolt doesn't follow the code from the beginning, but generates it anew each time, so parts of the application that were finished get completely changed or deleted and something entirely different is offered instead. It even changes or deletes user interface elements. Very frustrating.
> 
> Please fix all these bugs as soon as possible, because the idea is excellent and revolutionary.

This is exactly what is happening for me. One of the culprits is the tendency for LLMs to put placeholders in code they edit, such as "The rest remains unchanged ..." or something similar.  To overcome this, I include instructions to always write complete working code, and not leave anything out. I imagine this can be fixed by tuning the instructions in Bolt.new

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback and your patience as improvements continue to be made! Regarding chat persistence, temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). 

Additionally, if there is a file you do not want Bolt to modify, right-click the file in the editor and select "Lock file." This will prevent the AI from making further changes to that file. This action can be applied to multiple files.

This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on using Bolt most effectively while maximizing token efficiency. Hope this helps!
