### ISSUE TITLE
its stuck on npm install many times

### ISSUE THREAD

**Issue by prakhar840** [stackblitz/bolt.new#1965]
### Describe the bug

<img width="1440" alt="Screenshot 2024-11-11 at 11 39 50 AM" src="https://github.com/user-attachments/assets/5093983c-068d-4a63-9930-f26a42889cee">
its stuck on installing npm module i think some issue on server

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nv2mu5

### Steps to reproduce

Write prompt
just after that npm install stel it will stuck

### Expected behavior

should be continue

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51747939,
  "usedJSHeapSize": 49619203,
  "jsHeapSizeLimit": 4294705152
}
Username = prakhar840
Chat ID = fddc05d0f4c5
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Here are a number of things you can try regarding npm hanging: 

- **Initial Load Times:** npm load times are correlated with overall dependency tree size. The greatest load time is usually during initial project generation as npm modules are installed. Performance improvements continue to be made to reduce load times.
- **Browser Refresh:** If npm continues to hang, refreshing the page usually fixes the problem. However, be aware that doing so will result in losing your current chat history.
- **Browser Compatibility:** Bolt, which [relies on WebContainers](https://webcontainers.io/guides/browser-support#:~:text=WebContainers%20are%20fully%20supported%20in,working%20out%20of%20the%20box.), currently has the greatest support for Chrome and most Chromium-based browsers. Developing in Chrome will likely result in improved performance. We expect support for other browsers to continue to improve.
- **Available System Memory:** As a Bolt project size increases so do local memory (RAM) demands. Ensuring your browser has sufficient memory by closing unnecessary tabs can increase performance.
- **Manual Intervention:** Improving the output of LLMs is an area of active research. As such, the model may not always find the correct or compatible npm module, requiring manual intervention. The terminal is a good place to look for such errors if Bolt does not automatically detect and offer to resolve them. Working with LLMs is a fluid and evolving process. This [[page](https://github.com/stackblitz/bolt.new/issues/678)](https://github.com/stackblitz/bolt.new/issues/678) contains numerous insights on leveraging Bolt most effectively while maximizing token usage.
