### ISSUE TITLE
Does not load preview after initial prompt

### ISSUE THREAD

**Issue by donvito** [stackblitz/bolt.new#1967]
### Describe the bug

After an initial prompt, the preview does not load. this is the error in the terminal

```(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.```

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fnvftm

### Steps to reproduce

make a new project

### Expected behavior

Show the preview

### Screen Recording / Screenshot

![Screenshot 2024-11-11 at 3 55 52 PM](https://github.com/user-attachments/assets/eb45c35e-7a2e-4ace-bab9-48552440fc54)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84749925,
  "usedJSHeapSize": 80761141,
  "jsHeapSizeLimit": 4294705152
}
Username = donvito
Chat ID = ebb6af2fb879
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this issue with the preview not loading here: #1791.
