### ISSUE TITLE
App not loading the preview and just went crazy and created Node APIs

### ISSUE THREAD

**Issue by donvito** [stackblitz/bolt.new#1968]
### Describe the bug

App not loading the preview and just went crazy and created Node APIs
![Screenshot 2024-11-11 at 4 09 39 PM](https://github.com/user-attachments/assets/4d4875cc-5741-43e2-9ec4-ddc38b0fd790)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6tbbrt

### Steps to reproduce

Create a fresh bolt project

### Expected behavior

Show the preview

### Screen Recording / Screenshot

![Screenshot 2024-11-11 at 4 06 46 PM](https://github.com/user-attachments/assets/921c49c7-f559-4903-98f6-d3abf2ec87d7)
![Screenshot 2024-11-11 at 4 09 39 PM](https://github.com/user-attachments/assets/328a078a-b23a-4a9b-b474-e77cbef3a590)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114960281,
  "usedJSHeapSize": 92231261,
  "jsHeapSizeLimit": 4294705152
}
Username = donvito
Chat ID = 857dee0d7c27
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791.
