### ISSUE TITLE
Comments in the code for the previous code written

### ISSUE THREAD

**Issue by PradeepPatil10** [stackblitz/bolt.new#197]
### Describe the bug

When asked to modify code with any new features it write the comments in the code to keep the previous code, which breaks down the complete functionality and layout and everything else.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-amvirw

### Steps to reproduce

Look at the link provided and the logs and also the code generated you will get it.

### Expected behavior

Should write only modified code and untouched with existing functionalaties

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samdenty** [comment]
We're tracking this internally. You can follow #124 to get notified when we've resolved this issue.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.

**Comment by PradeepPatil10** [comment]
What was the fix not able to see in the repo PRs. Could you help me locate the same.
