### ISSUE TITLE
Daily tokens on top of maximum amount for Pro Plan

### ISSUE THREAD

**Issue by mateimmm** [stackblitz/bolt.new#1971]
**Is your feature request related to a problem? Please describe:**

Daily tokens are available only for free plan as free tokens but I would say that should be part of Pro Plan as well. We are paying to have additional tokens /month but in this time the free plan options are not included. Pro should include the Free plan not to be as separate plan. 

**Describe the solution you'd like:**

I would like to see above the "Per month" in Settings/Usage tab an row with "Free per day" with the same amount of tokens as Free plan and when that ones are used to start to burn from Pro plan  tokens. 

**Describe alternatives you've considered:**

An alternative my be when Bolt goes in like a loop and is consuming tokens unnecessary to show an pop up message as a warning for User that same job is attempting to be performed.

**Additional:**
For Pro plan I have the feeling that tokens burned after prompting are increased in number compared to reality - could someone check it ? 

**Thank you!**

**Comment by endocytosis** [comment]
Hi @mateimmm, 

Appreciate the feedback! The free plan has a limit of 150,000 tokens/day and 1,000,000 tokens total per month. After 1,000,000 tokens are consumed in the free plan, no more are available until the next month. Thus, the Pro Plan does contain more available tokens overall. 

Regarding using Bolt most effectively and maximizing token efficiency, this thread [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights. Hope this helps!

**Comment by arnesssr** [comment]
I feel like the Pro Plan token consumption is way too unrealistic. It would be much better if users were given a daily token quota—something like 333,333 tokens per day (for a 10M token plan)—to make usage more predictable and manageable. . I might be terribly mistaken, but a light instruction like "change the color of the button to red" should definitely not consume over 100k tokens in just one instance regardless of the size of project.
