### ISSUE TITLE
Cannot connect to service - Blank white page

### ISSUE THREAD

**Issue by RongWroom** [stackblitz/bolt.new#1972]
### Describe the bug

All I've been getting for the last 12 tries is a blank white page. I've tried the self heal but again, it will say it's fixed everything and nothing has changed.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mb9ypa

### Steps to reproduce

Create a project / fix a project.

### Expected behavior

Create a project.

### Screen Recording / Screenshot

<img width="758" alt="Screenshot 2024-11-11 at 08 42 38" src="https://github.com/user-attachments/assets/cff1ad19-16ee-4296-9b41-5bec02a0241b">

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = WrongRoom
Chat ID = 6d65bb82ff30
```

### Additional context

I'd love this to work but it's all of a sudden started to fail on every project I try.

**Comment by RongWroom** [comment]
Okay, I asked cursor to try and fix the issue and it changed these bits and the fix works.
<img width="391" alt="Screenshot 2024-11-11 at 13 40 41" src="https://github.com/user-attachments/assets/25b61741-f30a-46e9-9c6b-a89d915ad068">
<img width="472" alt="Screenshot 2024-11-11 at 13 41 49" src="https://github.com/user-attachments/assets/d9b99f53-8839-4499-b9e4-b728fb209056">

I hope that helps you permanently fix that blank white screen issue.

**Comment by RongWroom** [comment]
I refreshed Bolt with the old code just now. I realised it's your preview window in Bolt that isn't showing anything. The website now seems to work.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue regarding the preview window and are tracking it here: #1791. We appreciate your patience as the team continues to make improvements!

**Comment by RongWroom** [comment]
Sorry, I thought it was working but it's because my cursor localhost open too.

Closing that and trying again with Bolt gives me the same issue. Sorry to faff. It's all new to me.

**Comment by endocytosis** [comment]
@RongWroom, no worries! Appreciate the follow-up here.
