### ISSUE TITLE
Deploying the App via Bolt.New Error

### ISSUE THREAD

**Issue by jennyjanetech** [stackblitz/bolt.new#1975]
### Describe the bug

I am a newbie. The app is working fine in the Preview and Webcontainer.io however, when i click Deploy in bolt.new i am getting the following error:
Failed building the project. Make sure the build command is correct and try again.
When i click RETRY i got another error "Let me check the deployment status to get the URL where your site is live.

An unknown error occured while running an action."

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-hxioco

### Steps to reproduce

Goto Bol.NEw
Select Project - CyberV1

### Expected behavior

The app should be deployed without issues in Netlify

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = abrahamsurf
Chat ID = b853a23fef01
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by jennyjanetech** [comment]
up

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
