### ISSUE TITLE
Blank White Screen

### ISSUE THREAD

**Issue by Skhi-Bridges** [stackblitz/bolt.new#1977]
### Describe the bug

I tried for 4 hours, lost stuff when i refreshed the screen and then for over 2 hours it wont say there is an error, but the localhost wont connect.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ekqju4

### Steps to reproduce

1 click go to localhost:3000 2 or 8080 - good luck

### Expected behavior

to open up the app

### Screen Recording / Screenshot

zs

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 136353900,
  "usedJSHeapSize": 118760208,
  "jsHeapSizeLimit": 2160066560
}
Username = Skhi-Bridges
Chat ID = a4a7220cdf1c
```

### Additional context

It sure looks nice and i like to see it go but.
..my aching lifestyle,, please look into it~

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

Regarding chat persistence and past projects, temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.

**Comment by Skhi-Bridges** [comment]
Thanks. I am going to have to ask for a refund. It has been less that 24
hours and I havent accomplished anything but burning tokens like at a las
vegas slot machine. and then it forgets what the project is and changes
everything all the time and just breaks stuff and then fixes it and then
the same error comes up again. It is a nice interface, but it needs a
memory or something. I only have so much time and money. Thanks anyway --
maybe in the next few months the glitches will be resolved. Appreciations~



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by endocytosis** [comment]
Hi @Skhi-Bridges, 

The team is hard at work continuing to resolve issues! Refund requests are handled through hello@stackblitz.com.
