### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by annepuravida** [stackblitz/bolt.new#1979]
### Describe the bug

Despite several attempts, the application previews don't work. All I get are white or black pages instead of the application preview.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-htyaqg

### Steps to reproduce

every time I try to build an app with the IA, the preview doesn't work

### Expected behavior

that ITS WORK

### Screen Recording / Screenshot

![iScreen Shoter - Safari - 241111105635](https://github.com/user-attachments/assets/acff6854-df9b-4cdc-94d0-f076b3f5abda)

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = anne.puravida
Chat ID = bd2aa1ad479d
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
