### ISSUE TITLE
Forbidden messages

### ISSUE THREAD

**Issue by yoran-bosch** [stackblitz/bolt.new#198]
### Describe the bug

I keep getting the error 'Forbidden' when I submitted messages. Is this some type of rate limit I've ran into? I also can't check how many tokens I've used already in my subscription.

### Link to the Bolt URL that caused the error

Private

### Steps to reproduce

All my chats have the same issue.

### Expected behavior

Normal replies to my prompts by the system.

### Screen Recording / Screenshot

<img width="513" alt="Screenshot 2024-10-08 at 14 37 11" src="https://github.com/user-attachments/assets/c8383e6f-5423-4e52-90ef-c2d034172b74">

### Platform

- OS: macOS
- Browser: Chrome

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by Nemikolh** [comment]
Hey @yoran-bosch! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
