### ISSUE TITLE
Your app  keeps making coding mistakes with error after error 

### ISSUE THREAD

**Issue by Matjay007** [stackblitz/bolt.new#1981]
why are you usijng up my tokens if  your app is the one that keeps writing bad code with error after error.  Its annoying.  I am not happy with your app.  Its sucking peoples money without doing what its supposed to do properly.

**Comment by endocytosis** [comment]
There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform. Work continues to improve performance and token efficiency. At times, there are programming challenges that the AI model can not solve, and manual intervention is required. This is especially important when asking the AI to fix an error. If it is unsuccessful, copying and pasting relevant errors messages from the terminal into the chat can be helpful. If it remains unsuccessful, manual intervention is required to prevent excessive token usage.

**Comment by Matjay007** [comment]
yes but seriously  in three hours used up 20 usd of tokens that is criminal
