### ISSUE TITLE
I need Feature Change DNS Domain .netlify.app Please 

### ISSUE THREAD

**Issue by tetipong2542** [stackblitz/bolt.new#1982]
**Is your feature request related to a problem? Please describe:**
I need Feature Change DNS Domain .netlify.app Please 

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
After clicking Deploy, click "Claim URL" in chat to move the deployed site into your own Netlify account. Further [DNS configuration](https://docs.netlify.com/domains-https/netlify-dns/) can be managed in your Netlify account.
