### ISSUE TITLE
Projects/Chats not showing

### ISSUE THREAD

**Issue by Storbaek** [stackblitz/bolt.new#1985]
### Describe the bug

I worked on multiple computers - but from same subscription. I don't see those chats I have on one computer one another.

I have wasted enourmous amounts of tokens, as I had to recreate complete applications. Super irritating - and expensive, experience which should NOT have been needed.

Am I doing something wrong here? Please tell me what I am doing wrong.

Dan

### Link to the Bolt URL that caused the error

@storbaek subscription

### Steps to reproduce

1. Create a chat. Post and pay.
2. Go to a different computer. 
3. Login to subscription.
4. Open chat window - and it's not there

### Expected behavior

Nlank

### Screen Recording / Screenshot

-

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

-

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
