### ISSUE TITLE
deployment problems 

### ISSUE THREAD

**Issue by blutrich** [stackblitz/bolt.new#1989]
### Describe the bug

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-houyzw

### Steps to reproduce

Failed building the project. Make sure the build command is correct and try again.

### Expected behavior

deploy to netlify 

### Screen Recording / Screenshot

Failed building the project. Make sure the build command is correct and try again.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64308134,
  "usedJSHeapSize": 62094658,
  "jsHeapSizeLimit": 4294705152
}
Username = blutrich
Chat ID = e4b2639f3a79
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
