### ISSUE TITLE
Gettying "Forbidden" Error

### ISSUE THREAD

**Issue by mohammeddyousuf** [stackblitz/bolt.new#199]
### Describe the bug

Hi, Am not able to submit the prompt and getting "Forbidden" Error. Its not giving any more infor about it. What should i assume ?.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aeqwar?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=sidebar

### Steps to reproduce

Not able to submit the prompt.

### Expected behavior

Should work as prompted.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/079026a5-0599-4eda-89b2-02e5c05a3871)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50803155,
  "usedJSHeapSize": 48725515,
  "jsHeapSizeLimit": 4294705152
}
Username = mohammeddyousuf
Chat ID = a7cf9054d5d7
```

### Additional context

Pleae resolve the issue.

**Comment by Nemikolh** [comment]
Hey @mohammeddyousuf! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!

**Comment by mohammeddyousuf** [comment]
Its working fine now, if faced with the same will report. thanks.
