### ISSUE TITLE
cant deploy

### ISSUE THREAD

**Issue by blutrich** [stackblitz/bolt.new#1990]
### Describe the bug

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-houyzw

### Steps to reproduce

deploy 

### Expected behavior

error

### Screen Recording / Screenshot

<img width="521" alt="Screenshot 2024-11-11 at 15 10 17" src="https://github.com/user-attachments/assets/899d84a2-705d-4f67-bb5a-6943347e234d">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69529439,
  "usedJSHeapSize": 64233727,
  "jsHeapSizeLimit": 4294705152
}
Username = blutrich
Chat ID = e4b2639f3a79
```

### Additional context

can you refund me 
i tried to fix this so many time 
days from 20K to 12k tokens

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
