### ISSUE TITLE
Repeated unresolved errors 

### ISSUE THREAD

**Issue by MeheretNeg** [stackblitz/bolt.new#1992]
### Describe the bug

Experiencing repeated unresolved errors and when clicking on fix problem each time it reduces our token so this is not fair or efficient for users please look into this. Thanks.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8mqiae

### Steps to reproduce

.

### Expected behavior

Fix the problem the first time or second? But same error keeps coming back

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
At times there are coding problems that are too complex for the AI to solve and manual intervention is required to avoid excessive token usage. Issue #678 contains a number of insights on error resolution and maximizing token efficiency. Hope this helps!

**Comment by MeheretNeg** [comment]
Thanks for getting back Brian.

However it's quite frustrating and feel like it's unfair how I spent almost
50% of my tokens on trying to fix errors in recurring loop. I upgraded my
tokens today but I'm afraid this will be my last unless there are some
major changes.

M

**Comment by endocytosis** [comment]
Hi @MeheretNeg, 

Totally understand that reoccurring errors are frustrating! This is something that one can expect to become less of an issue as AI models improve. Unfortunately, at the time, when AI models become stuck in this state manual intervention is often necessary. The team is hard at work improving Bolt performance and token efficiency. 

Something that may help is if you get a certain file to a state where it is working fully, you can right click that file in the Bolt code editor and select "Lock file", which will prevent the AI from making further changes to the file.

We greatly appreciate your patience as improvements continue to be made!
