### ISSUE TITLE
Failed building the project. Make sure the build command is correct and try again.

### ISSUE THREAD

**Issue by Autifill** [stackblitz/bolt.new#1996]
### Describe the bug

I can't deploy my project I keep getting this error

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cppefu

### Steps to reproduce

Failed building the project. Make sure the build command is correct and try again.

### Expected behavior

Failed building the project. Make sure the build command is correct and try again.

### Screen Recording / Screenshot

Failed building the project. Make sure the build command is correct and try again.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83693946,
  "usedJSHeapSize": 71962218,
  "jsHeapSizeLimit": 1990459392
}
Username = pie
Chat ID = 9d34d5d99457
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by jennyjanetech** [comment]
same issue i have now

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
