### ISSUE TITLE
Chat history available across multiple devices

### ISSUE THREAD

**Issue by AncientRow2816** [stackblitz/bolt.new#2005]
**Is your feature request related to a problem? Please describe:** 

The problem is using bolt.new across multiple devices.
The chat history created from one device is not available in another's chat history - quite a shame given you can spend hours on creating one app and not accessible from another device sucks.

**Describe the solution you'd like:**

Make all chats history available across devices

**Describe alternatives you've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
