### ISSUE TITLE
blank

### ISSUE THREAD

**Issue by klepi21** [stackblitz/bolt.new#2006]
### Describe the bug

i try to access a huge web app from guthub but never loads always blank screen with no reason an i cannot chat 

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-cw398j

### Steps to reproduce

just build it

### Expected behavior

nothing to see

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78956353,
  "usedJSHeapSize": 77495661,
  "jsHeapSizeLimit": 4294705152
}
Username = klepi21
Chat ID = 643dc041c98d
```

**Comment by endocytosis** [comment]
Currently, Bolt works best for small to medium sized projects based on limitations of the AI model's context window. You can read more about this here: #1322. Insights on leveraging Bolt most effectively while maximizing token usage can be found here: #678. Hope this helps!

**Comment by klepi21** [comment]
So can we wait for something that work on large scale soon ?
