### ISSUE TITLE
Allow opening from a git (or already imported stackblitz) repo

### ISSUE THREAD

**Issue by PradeepPatil10** [stackblitz/bolt.new#201]
### Describe the bug

Allow opening from a git (or already imported stackblitz) repo

### Link to the Bolt URL that caused the error

Allow opening from a git (or already imported stackblitz) repo

### Steps to reproduce

Allow opening from a git (or already imported stackblitz) repo

### Expected behavior

Allow opening from a git (or already imported stackblitz) repo

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by boudewijndanser** [comment]
You can by using the url like this: https://bolt.new/~/github.com/[username/public-repo-name

**Comment by kc0tlh** [comment]
@boudewijndanser thanks for the provided resolution! 

More info on this feature here:
https://x.com/stackblitz/status/1843668731681267801
