### ISSUE TITLE
bugs bugs and bug

### ISSUE THREAD

**Issue by Matjay007** [stackblitz/bolt.new#2011]
### Describe the bug

again and again your app keeps having issues and yet you are using my tokens i will not tolerate that and to me its like you are scamming me.  I paid for an app that should be able to code properly but keeps having issue after issue error after erro.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-oskxwa

### Steps to reproduce

i ask it over and over to fix the errors but it does not 

### Expected behavior

for the app to work not error after error after error 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/aab01a5b-efd1-498c-8bd2-78015026ed06)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 185878619,
  "usedJSHeapSize": 159215095,
  "jsHeapSizeLimit": 4294705152
}
Username = matjay1111
Chat ID = dd16fccff205
```

### Additional context

i want my tokens back i have wasted more time asking it to fix errors than anything else.

**Comment by endocytosis** [comment]
Often times pasting the error message into the chat can help resolve the problem. The team is hard at work continuing to make performance improvements. There are times where the AI is unable to solve complex coding problems and manual intervention is required. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on maximizing token efficiency. Refund requests are handled through hello@stackblitz.com.

**Comment by Matjay007** [comment]
i do not care this is not right i think their algorithm is corrupt and sucking up our money
