### ISSUE TITLE
Can't see previous chats?

### ISSUE THREAD

**Issue by Cassiniuk** [stackblitz/bolt.new#2012]
### Describe the bug

Hi I've logged in on a different computer but can't see previous chats/apps? It is blank.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

See screenshot

### Expected behavior

I have logged in via my MacBook Pro on Brave (previously logged in on Windows/Google Chrome) exepecting to see my previous chats so I could continue but there is nothing there

### Screen Recording / Screenshot

<img width="1718" alt="Screenshot 2024-11-11 at 18 18 03" src="https://github.com/user-attachments/assets/a744c9ad-2673-4075-8b99-022fa1cbeae6">

### Platform

MacOS (latest version) on Brave Broswer

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
