### ISSUE TITLE
Chat History is blank

### ISSUE THREAD

**Issue by dipaksaraf** [stackblitz/bolt.new#2013]
### Describe the bug

The chat history which I was working on has vanished! Yesterday there were 2 project where I had chat history, but it has vanished suddenly! Though I can see them in stackblitz's collection >> bolt collection

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

When I sign-in to bolt.new 

### Expected behavior

Chat history should be visible!

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/0e90c8f6-8f25-4982-9afc-e19fba67102a)

### Platform

- OS: Windows 10
- Browser: Firefox
- Version: 132.0.1 (64-bit

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
