### ISSUE TITLE
not showing or deploying

### ISSUE THREAD

**Issue by jkay007** [stackblitz/bolt.new#2015]
### Describe the bug

ive tried many times to see preview or deploy and says failed building the project. Make sure the build command is correct and try again. ive wasted millions of tokens and nothing has been produced 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-huprc2

### Steps to reproduce

open the project

### Expected behavior

the preview and deployment of the project 

### Screen Recording / Screenshot

![Screenshot 2024-11-11 8 31 57 PM](https://github.com/user-attachments/assets/c9b7626b-757f-4f97-820c-f39e2d628aef)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51653093,
  "usedJSHeapSize": 48642437,
  "jsHeapSizeLimit": 2006188032
}
Username = Trad1
Chat ID = 173c17f83d88
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
