### ISSUE TITLE
missing my project

### ISSUE THREAD

**Issue by danishmbutt** [stackblitz/bolt.new#2016]
I created a calculator over the weekened. Now that i log into bolt. i cannot see it in my chats. please help. i spent quite a bit of time creating it.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
