### ISSUE TITLE
Bolt.new Chat is output Forbidden Messages... Again and again...

### ISSUE THREAD

**Issue by Jay-PoetryFlow** [stackblitz/bolt.new#202]
### Describe the bug

When I Input Prompt Message, Blot Chat is No Response and Showing Forbidden Messages...

![image](https://github.com/user-attachments/assets/321ed577-7654-4966-b4a2-cc7c7b3c3ce7)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cgmzdn

### Steps to reproduce

Just not working bolt.new

### Expected behavior

https://[bolt.new/~/sb1-cgmzdn](https://bolt.new/~/sb1-cgmzdn)

![image](https://github.com/user-attachments/assets/321ed577-7654-4966-b4a2-cc7c7b3c3ce7)

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/321ed577-7654-4966-b4a2-cc7c7b3c3ce7)

### Platform

- OS: Windows 11 Pro (beta)
- Browser: MS edge
- Version: Microsoft Edge, Version 130.0.2849.27 (Official Build) stable app, beta  (64bit)

### Additional context

Today is not working day for "npm install & npm start". Maybe, They are enjoy holiday! haha!

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by Nemikolh** [comment]
Hey @Jay-PoetryFlow! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
