### ISSUE TITLE
Dependency conflicts using latest version of angular 

### ISSUE THREAD

**Issue by kjlavallee** [stackblitz/bolt.new#2022]
### Describe the bug

Run into dependency error loop when building app with new angular.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kqzjyb

### Steps to reproduce

Click fix issue

### Expected behavior

Issue is fixed

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! If the AI is referencing an incorrect dependency and is unable to correct it, manual intervention is often required. Sometimes copying and pasting the error from the terminal into the chat can help resolves the problem. The teams continues to work to make improvements regarding this and we appreciate your patience!
