### ISSUE TITLE
Just logged in an my projects are GONE. No previous chats.... :( 

### ISSUE THREAD

**Issue by seansafholm** [stackblitz/bolt.new#2024]
### Describe the bug

I just logged in from another computer to my account. and my chats are gone. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sk4fkh

### Steps to reproduce

no clue

### Expected behavior

show my chat history>.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made!
