### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by ascendus28** [stackblitz/bolt.new#2025]
### Describe the bug

No matter what i do the preview only shows a plain white screen with no possibility to do anything 
![Capture d'écran 2024-11-11 213526](https://github.com/user-attachments/assets/5279dcfc-3f46-49e8-b0cc-aaa7e76a5fde)
![Capture d'écran 2024-11-11 213402](https://github.com/user-attachments/assets/8b6d917e-a72a-4b9d-9d81-69a24d4c5773)
![Capture d'écran 2024-11-11 213246](https://github.com/user-attachments/assets/67df824d-8f61-4477-8e02-76177ad43aeb)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nveh5r

### Steps to reproduce

i wanted a UI like ChatGPT and ended up with a white screen

### Expected behavior

i wanted a UI like ChatGPT and ended up with a white screen

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82331385,
  "usedJSHeapSize": 58265937,
  "jsHeapSizeLimit": 4294705152
}
Username = ascendus28
Chat ID = e642eff0c522
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
