### ISSUE TITLE
Your tool is not working

### ISSUE THREAD

**Issue by Dudi-marketing** [stackblitz/bolt.new#2028]
### Describe the bug

Hi Guys,
I have try your tool today and spent few hours.
Sadly I got into situation where II got white screen with nothing on it and the agent explain that everything setup.
I explained to the agent 3 times that the frontend is white screen white nothing on it include screenshot . Th answer was it was fixed but still I have white screen and it is not the app I wanted to biuld.

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-4jc29l

### Steps to reproduce

go to my project and you can see I have asked it to fix 3 time the white screen :(

### Expected behavior

I expected to see something in the frontend 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

**Comment by endocytosis** [comment]
Hi @Dudi-marketing, 

Unfortunately "npm run dev" works in some but not all cases for this issue. The team is hard at work continuing to ship improvements to resolve this issue. Refund requests are handled through hello@stackblitz.com.

**Comment by Dudi-marketing** [comment]
Hi Brian,

Your answer is not clear.

I need to understand if I need to start again or what you suggest is that
your tool can't develop what I'm asking for?

Please advise?

FYI - I saw a youtube video with your CEO explaining what should be the
prompt. but please guide me so I will make the best use of my time and
money.

Thank you,
Dudi
