### ISSUE TITLE
Better way to save and restore progress in the bolt.new interface.

### ISSUE THREAD

**Issue by koenjah** [stackblitz/bolt.new#203]
Is your feature request related to a problem? Please describe:

I'm always frustrated when my progress is lost after closing the bolt.new interface. There's no clear way to save my work, which leads to repeated efforts and wasted time.

Describe the solution you'd like:

I'd like an automatic save feature that regularly backs up my progress. Additionally, a manual save option would be helpful, allowing users to save specific versions of their work and restore them as needed.

Describe alternatives you've considered:

I've considered using third-party tools to capture my progress, such as screenshots or external note-taking apps, but these are cumbersome and not integrated into the workflow.

Additional context:

A save and restore feature would greatly enhance productivity and user satisfaction. It would be beneficial to have an intuitive interface for accessing saved versions, perhaps with a version history sidebar.

**Comment by kirjavascript** [comment]
Hey! Thanks for raising this issue!

We're tracking this internally, and #35 is a similar feature request. I'm going to close this issue, feel free to subscribe for updates in the other issue! We'll keep you posted 🙌

**Comment by Brettk80** [comment]
Just lost a day of work. Seems really trash if you pay and lose your work.

**Comment by echerrypick** [comment]
I have the same issue.  Need to be able to snapshot code and restore to a snapshot so can go back to a point where the app was working well and then can try adding functionality again
