### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by okitoki92** [stackblitz/bolt.new#2030]
### Describe the bug

depuis plus 1heure je n'arrive pas à intégré les bonnes photos

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1l24uj

### Steps to reproduce

demandez une photo

### Expected behavior

pas bonne photo

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60377024,
  "usedJSHeapSize": 54855128,
  "jsHeapSizeLimit": 2112618496
}
Username = okitoki92
Chat ID = b8be35aa3971
```

**Comment by endocytosis** [comment]
Appreciate the feedback! The team is aware of this issue and is being tracked here: #1809.
