### ISSUE TITLE
Exceeding token count in the prompt box (false count)

### ISSUE THREAD

**Issue by ChakrawartiJeet** [stackblitz/bolt.new#2031]
### Describe the bug

<img width="425" alt="image" src="https://github.com/user-attachments/assets/9149fe9a-d8dd-43b9-97e0-d69c7f4c8051">

### Steps to reproduce

Open the project, type in any prompt, even 1 word or letter

### Expected behavior

Doesn't allow to give any prompt

### Screen Recording / Screenshot

<img width="425" alt="image" src="https://github.com/user-attachments/assets/b2367a20-1512-4924-82bc-515c768e9950">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56150943,
  "usedJSHeapSize": 50707683,
  "jsHeapSizeLimit": 4294705152
}
Username = ChakrawartiJeet
Chat ID = 1c2c53a2a066
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
