### ISSUE TITLE
not getting my whole projects after deploying in

### ISSUE THREAD

**Issue by ashish9731** [stackblitz/bolt.new#2037]
### Describe the bug

HiTeam, I have created a project and deployed it. and again I wanted to add some more features in it and ran the program but it failed and the deployed link got disconnected this is strange please help me to get the last deployed workable project. I am fed up with this behaviour in this app. It automatically changes UI and codes though mentioning always do not change current UI or code. Please help me to get back my last deployed project.

Project link which was deployed:

https://idyllic-dragon-ff30d1.netlify.app/

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-axlhvc

### Steps to reproduce

I do not know the steps as i am unable to see anything to reproduce last version. 

### Expected behavior

Once I deployed that should be different part and afterwards whatever I do in bolt should not effect deployed app. but this is not happening. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52535659,
  "usedJSHeapSize": 50658315,
  "jsHeapSizeLimit": 2160066560
}
Username = ashish9731
Chat ID = 5a3daa9aa7d8
```

**Comment by endocytosis** [comment]
Hi @ashish9731, 

Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
