### ISSUE TITLE
Application code wiped by the AI

### ISSUE THREAD

**Issue by rikro** [stackblitz/bolt.new#2038]
### Describe the bug

After burning through MILLIONS of tokens, more than half trying many times to get the ai to successfully do what it said it had done, but clearly hadn't, I finally got to an app state I considered complete phase 1. I got frustrated with the ai as it again kept saying it had completed the requested changes, but no changes were visible. After about 10 attempts, I told it that 'it was fired' ... and it proceeded to 'reset' the application. I told it to restore the code, but it's not been able to successfully do so. I was originally thrilled with Bolt, but now I just can't trust it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-np1lly

### Steps to reproduce

See above description.

### Expected behavior

See above description.

### Screen Recording / Screenshot

Can't capture a recording or screenshot that's useful.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87995092,
  "usedJSHeapSize": 66969888,
  "jsHeapSizeLimit": 4294705152
}
Username = rikro
Chat ID = fb33d52f6885
```

**Comment by rikro** [comment]
I should add that the last version of the code deployed to stacktrace was solid. The last instructions I gave to Bolt were simple instructions to remove a line of text on the screen and move another line of text.

**Comment by rikro** [comment]
I've been able to recreate the app to a point with ongoing prompting, but I'm having to rebuild/reinstantiate much of the interface and I'm not back to where we were prior to the incident. I've deployed the current state and pausing now.

**Comment by endocytosis** [comment]
Hi @rikro, 

Sorry to hear about this! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
