### ISSUE TITLE
Inquiry About Project Recovery in Bolt Pro Mode

### ISSUE THREAD

**Issue by machavarro** [stackblitz/bolt.new#2039]
### Describe the bug

Hello, Bolt Support Team,

I’ve been using Bolt in Pro mode for a few days and created a project in the platform. However, when I recently logged back into my account, it says there are no previous conversations, and I can’t find the project I previously created.

Could you please guide me on how to recover my project and regain access to previous conversations? I appreciate your assistance in resolving this issue.

Thank you in advance for your attention.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Your Chats

### Expected behavior

Could you please guide me on how to recover my project and regain access to previous conversations?

### Platform

- OS:  Windows
- Browser: Chrome
- Version: 130.0.6723.117 (Build oficial) (64 bits)

**Comment by endocytosis** [comment]
Hi @machavarro, 

Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
