### ISSUE TITLE
Can't publish app to netifly. 

### ISSUE THREAD

**Issue by supurrapp** [stackblitz/bolt.new#2040]
### Describe the bug

App works fine on preview but it encounters an error when publishing to netifly. 

error msg: 
Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jk2ixq

### Steps to reproduce

Go to twitter growth analytics dashboard and try to publish the project to netifly

### Expected behavior

It will say 
Failed building the project. Make sure the build command is correct and try again.

### Screen Recording / Screenshot

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/dcfca3b1-d163-4c5c-a107-2a50c98fec84">
<img width="1427" alt="Screenshot 2024-11-12 at 8 13 21 AM" src="https://github.com/user-attachments/assets/e5b0475c-4d46-412b-b269-7a8c01a034ba">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83165155,
  "usedJSHeapSize": 78550419,
  "jsHeapSizeLimit": 2172649472
}
Username = vinish
Chat ID = 09fce05a646a
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue are are tracking it here: #2019.
