### ISSUE TITLE
Stuck in a Loop

### ISSUE THREAD

**Issue by ifemuyiwaojo** [stackblitz/bolt.new#2041]
### Describe the bug

The program is stuck in a loop. By the way, I made major progress yesterday and your system just crashed and lost it all! @ days of work, $50 worth.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-d2q4ds

### Steps to reproduce

No specific steps rreally. It just happens

### Expected behavior

System recovers and restores state instead of losing it all

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 198868244,
  "usedJSHeapSize": 187582872,
  "jsHeapSizeLimit": 4294705152
}
Username = ifemuyiwaojo
Chat ID = edb63499ecc3
```

**Comment by endocytosis** [comment]
Hi @ifemuyiwaojo, 

Are you able to find your past projects by going to [stackblitz.com](stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then clicking Bolt Collection?

**Comment by ifemuyiwaojo** [comment]
Yes I'm able to, but it took me back to a very early state. It seems the
system crashed around 6:45 pm yesterday and erased every progress I had
made for  2 straight days after I used up all my regular and extra tokens
to build it. I had to pay another $50 to get new tokens. It was very
frustrating but I love the product. You guys are the best! It would be nice
to have an interval backup system or git backup.

For the loop issue I had today, I had to restart the container (a few
times) and I lost history each time.

Best Regards,
Ife.

**Comment by endocytosis** [comment]
Totally understandable that this is frustrating but glad to hear that overall you are enjoying the product! The team is hard at work improving chat persistence and Git integration, which is being tracked here: #39. We really appreciate your patience as improvements continue to be made!

**Comment by ifemuyiwaojo** [comment]
Thanks. Is there work being done about this persistent failure we are doing, though? Theresa new error about token size exceeding 200000 that forces us to refresh our container and lose a chunk of progress. I just had one. It's very frustrating to just lose all your work like that. 

⁣
