### ISSUE TITLE
Cannot GET

### ISSUE THREAD

**Issue by mel895** [stackblitz/bolt.new#2042]
### Describe the bug

Every prompt returns Cannot GET every time for the last 20 prompts

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ztoisb

### Steps to reproduce

prompt and click generate.

### Expected behavior

I wanted a microphone icon to appear, but instead only a blank screen continues to appear.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/f4621334-d33e-447c-ad8d-27ff6406b0dc)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 139529882,
  "usedJSHeapSize": 107919930,
  "jsHeapSizeLimit": 2160066560
}
Username = mel895
Chat ID = 508e213680f0
```

### Additional context

Cannot GET is all bolt.new returns.

**Comment by endocytosis** [comment]
At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Hope this helps!
