### ISSUE TITLE
Ask for One and Leave with None

### ISSUE THREAD

**Issue by davidnightmusic** [stackblitz/bolt.new#2043]
### Describe the bug

When i asked for one prompt, it would hit a wall, and from that point on it would just delete massive parts of the code, and then be forced to rewrite. Even with specific criteria to not change anything but, or Rule: Only change x within y, but still it would make some irrational deletions of huge parts of code.

It's as if it hits a wall mentally, and then almost starts spiraling downward and you can't get over.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-haybpi

### Steps to reproduce

It just happens routinely I don't think I'm doing anything other than a ton of prompting.

### Expected behavior

^^^Description of the Bug

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55980194,
  "usedJSHeapSize": 51815558,
  "jsHeapSizeLimit": 2160066560
}
Username = davidarnett01
Chat ID = a47ab6757f84
```

**Comment by davidnightmusic** [comment]
Hi Stackblitz,

Yes although I've seen and used the lock feature, it isn't a solve all,
because if you're trying to make changes that effect multiple files, there
are times where you are changing things within a really large file, but
only specific things must stay the same, for example

Let's say I have 5 buttons with different functionality, and I'm asking to
change the color of the buttons to match something else. I may lock the
functional elements to stop it from changing functional code, but I can't
lock the file that the UI lives in because it's needed. If you go deep
enough into the project you will hit a wall where Bolt will start to delete
and change random things you didn't ask for. In this example I asked to
change a button, and it changes the entire pages background color. Rolled
it back, same prompt, but added, do not change background color or anything
else. Re-ran it, same exact result, despite new prompt.

Then I go and lay out detailed rules for what it can and can't change, and
it starts destroying elements in order to fix a simple UI element.

I think the lock feature is cool, but the issue persists. Just wanted to
let you know in detail because I really care for and love this platform.

Thanks,
@davidnight_

**Comment by endocytosis** [comment]
Appreciate the additional info here!
