### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by AndersondaCampo** [stackblitz/bolt.new#2047]
### Describe the bug

A AI não consegue executar o comando de start na aplicação por dependecias no banco, o que não tem problema, mas a questão é que o ultimo arquivo alterado perder as modificações, ficando assim consumindo tokens que são perdidos

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7rxeue

### Steps to reproduce

Peça depedencias que não são possíveis executar no container, como arquivos docker

### Expected behavior

Mesmo com erro nas dependencias, as ultimas alterações  não se percam

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 66622246,
  "usedJSHeapSize": 60627490,
  "jsHeapSizeLimit": 4294705152
}
Username = AndersondaCampo
Chat ID = 4e96faeb9f7b
```

**Comment by endocytosis** [comment]
Appreciate the feedback! If you right-click a file in the Bolt code editor and select "Lock file" this will prevent the AI from making further changes to the file. This can be done to multiple files. This page [here](https://github.com/stackblitz/bolt.new/issues/678) contains insights on using Bolt most effectively while maximizing token efficiency. Hope this helps!
