### ISSUE TITLE
Firebase Authentication Services

### ISSUE THREAD

**Issue by pimpcaddy** [stackblitz/bolt.new#2048]
### Describe the bug

All build was amazing until i added firebase authentication.  Just burnt through tokens then and spent so much time trying to get it to work.  this should be real easy its too distracting

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

add log in features
add firebase auth

### Expected behavior

add in firebase auth
and it works 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback and sorry to hear about the challenges with Firebase authentication! This video [here](https://www.youtube.com/watch?v=1GfqnOAKr9M) has some helpful information on setting up authentication with Firebase. At times, there are programming challenges that are too challenging for the AI to solve, and as such manual intervention is required. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has some insights on using Bolt most effectively.
