### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by umojabuild** [stackblitz/bolt.new#2049]
### Describe the bug

While making changes to App.ts in a bolt-vite-react project there were repeated network failures. I have no way of knowing if the network errors were caused by my internet connection quality or if it was indeed an internal network error, that made it difficult to decide the way forwards, after 3 retries and 3 failures. I then ignored the failure and continued by the application was missing code. My guess is it was infact an internal network error or just a rate limiting or sync error.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vite-react-xfsnm7

### Steps to reproduce

difficult as it can not be reproduced exactly as it is a spurious problem

### Expected behavior

flawless code generation or continuation of the synthesis

### Screen Recording / Screenshot

sorry none yet

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 89170040,
  "usedJSHeapSize": 70862752,
  "jsHeapSizeLimit": 4294705152
}
Username = umojabuild
Chat ID = e1e4fe694291
```

### Additional context

Error:
```
network error
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
