### ISSUE TITLE
Forbidden error

### ISSUE THREAD

**Issue by nheelam** [stackblitz/bolt.new#205]
### Describe the bug

I can't use the app at all it is throwing Forbidden error for each message I prompt for the past hour. Worked fine around 17 hours ago. I tried logging in with a different account still the same. Also, my conversations history went missing.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Go to bolt.new
2. Sign in
3. Type a custom prompt

### Expected behavior

I wanted it to reply my prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by Nemikolh** [comment]
Hey @nheelam! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
