### ISSUE TITLE
"Build Application" not working 

### ISSUE THREAD

**Issue by Leiya02** [stackblitz/bolt.new#2053]
### Describe the bug

When it's time for Bolt new to "build application" theres a problem

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8l4jxx

### Steps to reproduce

Let me help fix the build and deployment issues. First, let's ensure our build configuration is correct.

Fix Build Configuration

package.json
npm install
vite.config.js
netlify.toml
npm run build
netlify
This configuration:

Properly sets up the build script in package.json
Configures Vite for optimal production builds
Adds Netlify configuration for proper routing
Sets up proper chunk splitting for better performance
Once the deployment is complete, you'll get a new URL where you can access the application.

Failed building the project. Make sure the build command is correct and try again.

### Expected behavior

"build application" starts working again 

### Screen Recording / Screenshot

<img width="1069" alt="Screenshot 2024-11-11 at 9 09 03 PM" src="https://github.com/user-attachments/assets/30a90049-f4ca-4a52-8d10-48ffa8607943">
<img width="1069" alt="Screenshot 2024-11-11 at 9 09 03 PM" src="https://github.com/user-attachments/assets/4baee3c3-a1b0-4641-858e-ec1f2c19220c">

### Platform

```
Browser name = Chrome
Full version = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 144375126,
  "usedJSHeapSize": 141420558,
  "jsHeapSizeLimit": 4294705152
}
Username = Leiya02
Chat ID = 7b8f7b75d382
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019.
