### ISSUE TITLE
cannot deploy

### ISSUE THREAD

**Issue by curiosityexplorer** [stackblitz/bolt.new#2054]
### Describe the bug

cannot deploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-r8gtsd

### Steps to reproduce

cannot deploy

### Expected behavior

cannot deploy

### Screen Recording / Screenshot

cannot deploy

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52451947,
  "usedJSHeapSize": 49379391,
  "jsHeapSizeLimit": 4294705152
}
Username = Vikki
Chat ID = ed52c08165ae
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019.
