### ISSUE TITLE
Token too long

### ISSUE THREAD

**Issue by ifemuyiwaojo** [stackblitz/bolt.new#2055]
### Describe the bug

Error: token tool long spontaneously shows up and necessitates a page/container referesh losing all recent progress (3 - hours worth)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-d2q4ds

### Steps to reproduce

refresh system, start to prompt for more than 10 minutes or so

### Expected behavior

No error message. No data lossx

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 212670692,
  "usedJSHeapSize": 181793932,
  "jsHeapSizeLimit": 4294705152
}
Username = ifemuyiwaojo
Chat ID = fbdf205ffbca
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
