### ISSUE TITLE
Solana connect wallet

### ISSUE THREAD

**Issue by Bibinoo** [stackblitz/bolt.new#2057]
### Describe the bug

The changes made to fix cross-browser wallet connection doesn't work with:

    Added proper wallet provider detection that works across browsers
    Added a check interval to wait for wallet injection
    Improved handling of both window.phantom.solana and window.solana providers
    Added better error handling for connection states

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-crwqs8

### Steps to reproduce

When attempting to connect the wallet via the wallet connect feature, the Phantom Solana wallet is not properly triggered.

### Expected behavior

Click on Connect Wallet, open the Phantom Wallet from the browser, enter the passowrd if required and connect the wallet, show th current wallet address

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = Bibinoo
Chat ID = 25c4e553d0f6
```

**Comment by endocytosis** [comment]
While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects. There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform.

The [Solana Documentation](https://solana.com/docs/intro/wallets) is likely a good resource as well. Hope this helps!
