### ISSUE TITLE
Its beem over an hour of jsut trying to get an API and OAuth call to work and I feel like I am going in circles

### ISSUE THREAD

**Issue by mgerasolo** [stackblitz/bolt.new#2059]
### Describe the bug

I am trying to make an app that pulls form ETrade APIs to get my account balance and a few other parameters from the account.  There is a User Settings page where I am supposed to put in the ETrade Sandbox API Key & Secret.  It made a nice looking interface with mock data, but it has been an endless process of about 50 attempts to get it to even try to even make the OAuth query but it keeps not wanting to actually save the API keys, and it keeps trying to do mock data instead of the actually anything functioning.  I have sent about 50 "fix the problem" attempts (or so it feels), and it has yet to save the data and have the data still be on the screen.  Let alone have anything functional happen when I hit the OAuth button.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yqhcjr

### Steps to reproduce

From the content it generated, hit the Settings option.  and try saving any value in the ETrade Sandbox API Key and Secret, and hit save.

### Expected behavior

It should have at least been able to do a database save of the API keys and pull those values back by now.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59496523,
  "usedJSHeapSize": 54402895,
  "jsHeapSizeLimit": 4294705152
}
Username = mgerasolo
Chat ID = e46f7bcbf014
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This is likely the case if the AI is repeatedly unable to resolve an error.

This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
