### ISSUE TITLE
Forbidden?

### ISSUE THREAD

**Issue by anandacdr** [stackblitz/bolt.new#206]
### Describe the bug

![image](https://github.com/user-attachments/assets/0b38dbfb-5cea-4993-bf32-29f9ff4642b6)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4k7ytc

### Steps to reproduce

Please fix,

### Expected behavior

I can't able to perform more chat

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/d8c09c12-89d6-4189-a0cf-527819a8c4cf)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105168846,
  "usedJSHeapSize": 99526922,
  "jsHeapSizeLimit": 4294705152
}
Username = ananda
Chat ID = 6b594534fbbc
```

**Comment by resetsix** [comment]
https://github.com/stackblitz/bolt.new/issues/77#issuecomment-2395503410

**Comment by Nemikolh** [comment]
Hey @anandacdr! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
