### ISSUE TITLE
Daily Token Allocation Not Refreshing in Bolt AI Model (1,50,000 Tokens Per Day)

### ISSUE THREAD

**Issue by VC067** [stackblitz/bolt.new#2061]
### Describe the bug

The daily token allocation of 1,50,000 tokens in the Bolt AI model has not been resetting as expected. Despite not using the model for the last 3-4 days, the token count remains depleted and is not refreshing back to 1,50,000/1,50,000 daily tokens left.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Use the daily token allocation (1,50,000 tokens) in Bolt's AI model.
2. Wait 24 hours for the daily token allocation to reset.
3. Check the remaining daily tokens in the Bolt dashboard after 24 hours and again over the following days.

### Expected behavior

The daily token allocation should reset to 1,50,000/1,50,000 tokens left every 24 hours, allowing a fresh token balance each day.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jennyjanetech** [comment]
I've noticed that the token is easily consumed. Example from 6.3 million tokens are few iteration to modify the code it goes down to 6M tokens

**Comment by endocytosis** [comment]
Hi all, 

If you have a specific question regarding the token balance in your account please reach out to hello@stackblitz.com. Note: free accounts have an daily limit of 150,000 tokens and monthly allowance of 1,000,000 tokens total.
