### ISSUE TITLE
chat is not getting saved, 

### ISSUE THREAD

**Issue by pradda-gotham** [stackblitz/bolt.new#2064]
Not able to access past chat. Could you please help me with that.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
