### ISSUE TITLE
Won't fix my issue after asking it to do so repeatedly

### ISSUE THREAD

**Issue by christospapageorgio** [stackblitz/bolt.new#2065]
### Describe the bug

I have a fairly simple request. When the user is signed in, replace the "sign up / sign in" buttons on the top right with "dashboard / log out" buttons. 

It will tell me the issue is resolved, tell me to try again, and nothing has changed. I've wasted plenty of tokens asking it to make this change, to no avail. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-q1a7bm

### Steps to reproduce

In preview, sign up, then go to sign in, return to the landing page, and it will still say sign in / sign up. It should say dashboard / log in. 

Then you can ask it to fix this issue, it will tell you it's fixed, when it's not. I've asked several times. 

### Expected behavior

I would expect it to fix the issue. I've had several issues where I'm wasting tokens over and over again asking it to fix things that it does nothing. 

### Screen Recording / Screenshot

Not applicable, I've already wasted enough tokens trying to fix the issue. I'm not recording it again for the sake of flagging it just to waste my tokens further. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109035615,
  "usedJSHeapSize": 99129599,
  "jsHeapSizeLimit": 2160066560
}
Username = christospapageorgio
Chat ID = 102d53bf35c6
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
