### ISSUE TITLE
how to add api

### ISSUE THREAD

**Issue by Darweshpak** [stackblitz/bolt.new#2066]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
Unfortunately we don't have the resources to answer specific programming questions for project. However, this page [here](https://github.com/stackblitz/bolt.new/issues/678) contains on a number of insights on using Bolt most effectively. Additionally, there are some threads in the [StackBlitz Discord](https:/discord.gg/stackblitz) where users share knowledge on a number of programming topics. Hope this helps!
