### ISSUE TITLE
Getting Forbidden Message 

### ISSUE THREAD

**Issue by Srivamshi-ai** [stackblitz/bolt.new#207]
### Describe the bug

![image](https://github.com/user-at
![Screenshot 2024-10-08 150307](https://github.com/user-attachments/assets/36559d0d-0f45-4e98-8bd7-75dec6ae4ac1)
tachments/assets/c3874593-e345-4e66-8496-1d0a19a7fc2d)

getting forbidden message tried everything like changing browser prompt , asking simple things but its showing same error 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bpwtyz

### Steps to reproduce

enter anything on how can i help you tab then hit submit 

### Expected behavior

now forbidden messege is appering and the app is not functioning at all

### Screen Recording / Screenshot

![Screenshot 2024-10-08 150307](https://github.com/user-attachments/assets/62a13ea8-4888-4d6f-8c90-878a1221edca)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 97559770,
  "usedJSHeapSize": 87193198,
  "jsHeapSizeLimit": 2172649472
}
Username = Srivamshi-ai
Chat ID = 3b4abb8b6fad
```

**Comment by Nemikolh** [comment]
Hey @Srivamshi-ai! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
