### ISSUE TITLE
Still Cannot Deploy

### ISSUE THREAD

**Issue by Overcomer7** [stackblitz/bolt.new#2071]
### Describe the bug

Continues to give the same error I reported earlier about Build Command. Failed. Have tried numerous options like switching to Yarn instead of npm but of no avail. And credits getting consumed anyway. This is llike being looted.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v1idza

### Steps to reproduce

click on deploy and you will get the same error message.

### Expected behavior

it should deploy and take the app live

### Screen Recording / Screenshot

![err3gthub](https://github.com/user-attachments/assets/ffdbda62-2cb4-4ac6-9722-4186ba300799)

### Platform

- OS:  Windows, 
- Browser: Chrome, 
- Version: 130.0.6723.117

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
