### ISSUE TITLE
Preview not loading.

### ISSUE THREAD

**Issue by keneur** [stackblitz/bolt.new#2073]
### Describe the bug

The preview load but I get nothing, just a blank white screen

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-krr3fn

### Steps to reproduce

1. Click on preview or reload the application

### Expected behavior

I expect to see a preview of the built application

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/365c2a0c-712f-4663-91ab-006a82377e61)

### Platform

- OS: Windows
- Browser: Firefox

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
