### ISSUE TITLE
The AI responds to the previous question instead of the current one.

### ISSUE THREAD

**Issue by TheBlueHouse75** [stackblitz/bolt.new#2075]
### Describe the bug

I requested the AI to provide me with the code to integrate a cookie banner into my footer file, but it responded with something unrelated from a previous conversation.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xuvyub

### Steps to reproduce

Hard to reproduce as the problem occur in the conversation flow

### Expected behavior

The AI should answer the question, not an old one

### Screen Recording / Screenshot

<img width="558" alt="Capture d’écran 2024-11-12 à 10 45 34" src="https://github.com/user-attachments/assets/009ac28b-08f4-4d05-9282-d7bdae8bd733">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 146654641,
  "usedJSHeapSize": 139053913,
  "jsHeapSizeLimit": 4294705152
}
Username = TheBlueHouse75
Chat ID = b850b99891b4
```

### Additional context

you can ask your AI to translate the screenshot for better understanding

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve and manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
