### ISSUE TITLE
well token renew stop woking 

### ISSUE THREAD

**Issue by 7054company** [stackblitz/bolt.new#2076]
### Describe the bug

yay token reset stop working it will like 0/150000 as we not expect
well i have idea create a status page to show what is working and functional and what not work 

### Link to the Bolt URL that caused the error

no one whole platform 

### Steps to reproduce

well you see 

### Expected behavior

well the token should reset 

### Screen Recording / Screenshot

nono

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! Regarding token limits:

**Free Account:** Free accounts have a limit of 150,000 tokens/day and 1,000,000 tokens per month. 
**Paid Accounts:** Paid accounts do not have a daily token limit. 

If you believe you have an issue with tokens you have purchased not being reflected in your account, please reach out to hello@stackblitz.com with your account information for assistance. Hope this helps!

**Comment by 7054company** [comment]
No thats not the matter every-day renew not work after 24 h thats why i
email  know that
