### ISSUE TITLE
Pro have 10 Million tokens is it for day or monthly 

### ISSUE THREAD

**Issue by Naveen-Sadhanala** [stackblitz/bolt.new#2077]
### Describe the bug

Pro have 10 Million tokens is it for day or monthly 

### Link to the Bolt URL that caused the error

Pro have 10 Million tokens is it for day or monthly 

### Steps to reproduce

Pro have 10 Million tokens is it for day or monthly 

### Expected behavior

Pro have 10 Million tokens is it for day or monthly 

### Screen Recording / Screenshot

Pro have 10 Million tokens is it for day or monthly 

### Platform

Pro have 10 Million tokens is it for day or monthly 

### Additional context

Pro have 10 Million tokens is it for day or monthly

**Comment by Bazz0r** [comment]
It's a month.
