### ISSUE TITLE
sb1-zid6oc Project not found

### ISSUE THREAD

**Issue by apmai** [stackblitz/bolt.new#208]
### Describe the bug

While working on the project, the daily tokens got exhausted yesterday, and it was trying to update the project, whic was saved earlier as an interim version of the same. It got stuck with the error Unable to import project. Screen shot attached, and am unable to see my code or do anything about it, including see the hisotry of the code base that was built / chat.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zid6oc

### Steps to reproduce

My history of what i worked yesterday is completely not accesible...there is no navigation to go to the previous step or retrieve my code..its stuck with the screen as shared in the image

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-zid6oc
Project not found

### Expected behavior

To be able to continue my project  and complete it

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/24676b7b-cf45-4657-b6de-29f255a771fa)
![bolt Issue](https://github.com/user-attachments/assets/d242d58b-9283-47bf-a18c-7a806e8c12e7)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 43119115,
  "usedJSHeapSize": 40865059,
  "jsHeapSizeLimit": 4294705152
}
Username = apmai
Chat ID = f160a794d57b
```

### Additional context

Please help resolve it

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/50

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
