### ISSUE TITLE
project not found. automatically signs out

### ISSUE THREAD

**Issue by TR808T** [stackblitz/bolt.new#2081]
### Describe the bug

instant log out on trying to open a recent project. on some browsers, all chats are missing completely.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vx3ydb

### Steps to reproduce

sign in. click on previous chats. hit any chat. says

"I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-vx3ydb
Project not found
An unknown error occured while running an action."

or logs you out. 

### Expected behavior

works. lol

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79129331,
  "usedJSHeapSize": 65384223,
  "jsHeapSizeLimit": 4294705152
}
Username = TR808T
Chat ID = 6b7b8dda0b42
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
