### ISSUE TITLE
Erreur d'application

### ISSUE THREAD

**Issue by yopellio** [stackblitz/bolt.new#2082]
### Describe the bug

NotFoundError : échec de l'exécution de « insertBefore » sur « Node » : le nœud avant lequel le nouveau nœud doit être inséré n'est pas un enfant de ce nœud.
    chez ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    chez moi (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1kbzkt

### Steps to reproduce

request to bolt for page creation and development

### Expected behavior

page design and development 

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [e.g. 91.1]

**Comment by AriPerkkio** [comment]
Hey @yopellio, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
