### ISSUE TITLE
Not ready for production use

### ISSUE THREAD

**Issue by mitchmenghi** [stackblitz/bolt.new#2083]
### Describe the bug

I am getting errors as shown on the screenshot when it tries to preview the website.
![2024-11-12_22h20_28](https://github.com/user-attachments/assets/6cbdc0b6-d448-4398-b23b-0a1f89035118)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nmb8wd

### Steps to reproduce

If you click on the link for the project and it tries to render the design the error will occur

### Expected behavior

It should obiously render the preview without any issues

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 63556885,
  "usedJSHeapSize": 56315033,
  "jsHeapSizeLimit": 4294705152
}
Username = mitchmenghi
Chat ID = c8f4480774ae
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
