### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by keneur** [stackblitz/bolt.new#2088]
### Describe the bug

Bolt keeps breaking the code as it fixes problems so I end up with more problems to fix and this I believe is quickly eating into my token count. Please see if it can remember previous actions so that it does not break one part of the code as it fixes other parts

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6gwtef

### Steps to reproduce

Fix problem then you have another problem on reload

### Expected behavior

To not break previously working code

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @keneur, 

If you right-click a file in the Bolt code editor and selection "Lock file" this will prevent the AI from making further changes to that file. This can be done to multiple files. A number of insights on using Bolt most effectively while maximizing token efficiency can be found [here](https://github.com/stackblitz/bolt.new/issues/678).
