### ISSUE TITLE
build is not getting generated

### ISSUE THREAD

**Issue by pradda-gotham** [stackblitz/bolt.new#2089]
### Describe the bug

build is not getting generated and getting this error. "Failed building the project. Make sure the build command is correct and try again"

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xdob3v

### Steps to reproduce

Go to project - > Click on Deploy Button at the top right 

### Expected behavior

Netlify build to get generated with url to access

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/d8f76f3e-d1c3-48ea-9cf9-1fe003392609)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58537511,
  "usedJSHeapSize": 53427163,
  "jsHeapSizeLimit": 2160066560
}
Username = pradda-gotham
Chat ID = 53353f18c764
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019.
