### ISSUE TITLE
Why does it all say“Forbidden”

### ISSUE THREAD

**Issue by ottopan** [stackblitz/bolt.new#209]
### Describe the bug

<img width="2560" alt="image" src="https://github.com/user-attachments/assets/7dbcfbd1-77c1-404f-9360-bbc858524e1e">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zfvcyr

### Steps to reproduce

Just a normal chat, only to find that it doesn't work

### Expected behavior

Hope it can be used normally

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 115771772,
  "usedJSHeapSize": 113703052,
  "jsHeapSizeLimit": 4294705152
}
Username = ottopan
Chat ID = da08c4067c0c
```

**Comment by rafiqulshopon** [comment]
Same here. Getting forbidden message

**Comment by Gaurav-Wankhede** [comment]
Same here I got Forbidden message.

**Comment by JunHaoZhou1** [comment]
Same here

**Comment by Nemikolh** [comment]
Hey everyone! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let us know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!

**Comment by rafiqulshopon** [comment]
@samdenty It's working now!
