### ISSUE TITLE
The preview breaks every time, and I need to reload the page again

### ISSUE THREAD

**Issue by jimjcranshaw** [stackblitz/bolt.new#2090]
### Describe the bug

The preview breaks every time, and I need to reload the page again

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bpgevw

### Steps to reproduce

make any changes whatsoever. 
![image](https://github.com/user-attachments/assets/47de9771-d770-436b-9126-63f2d0bca80c)

### Expected behavior

I expected the preview to make the edits that were made in the code.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 177145889,
  "usedJSHeapSize": 156999437,
  "jsHeapSizeLimit": 4294705152
}
Username = jimjcranshaw
Chat ID = 0ea43b1e9785
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

**Comment by jimjcranshaw** [comment]
Hi Brian,

Thanks for the quick response and the workaround suggestion. I'll give that
a try.

Cheers,
Jim



<https://www.linkedin.com/in/jim-cranshaw-b450b430/>

Jim Cranshaw

Consultant
[image: envelope]  ***@***.***
[image: phone] (0044) 7894085505
[image: linkedin] <https://www.linkedin.com/in/jim-cranshaw-b450b430/> [image:
telegram-plane] <https://www.flourishnonprofits.org/>
Book a call directly into my calendar
<https://tidycal.com/jimjcranshaw/60-min-meeting>
[image: Email Badge] <https://emailbadge.com/?utm_source=signature>
