### ISSUE TITLE
Redeploying to the same Netlify project issue!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Julienbase** [stackblitz/bolt.new#2091]
### Describe the bug

Bolt.new is not redeploying to the same Netlify project always is creating a new one after I claimed already the first app.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1xdybz

### Steps to reproduce

click on deploy

### Expected behavior

redeploy to the initial deployment. Stay consistent to the same deployed app.
this issue is causing a lot of troubles and Credit consumptions.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59308411,
  "usedJSHeapSize": 54448119,
  "jsHeapSizeLimit": 4294705152
}
Username = Julien_base
Chat ID = 52e299550755
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this request and are tracking it here: #49.
