### ISSUE TITLE
Version control / checkpoints

### ISSUE THREAD

**Issue by etheuer** [stackblitz/bolt.new#2092]
**Is your feature request related to a problem? Please describe:**

Yes. The agent is unable to revert to previous versions. After things got messy when I asked it to use Firebase, I could not revert back and all my work became waste.

**Describe the solution you'd like:**

Proactively create checkpoint (see Replit) or allow user to do so.

**Describe alternatives you've considered:**

Asking the agent to revert to version prior to me asking to implement Firebase.

**Additional context:**

**Comment by AlAhmedElHamed** [comment]
I'm facing the same issue after i refreshed the page, the chat doesn't contain history

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [[stackblitz.com](http://stackblitz.com/)](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
