### ISSUE TITLE
bolt agent deleted all what i have been working on since yesterday.

### ISSUE THREAD

**Issue by creatorsam1** [stackblitz/bolt.new#2093]
### Describe the bug

bolt agent deleted all what i have been working on since yesterday. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zgjz4m

### Steps to reproduce

i just wasted 10milion tokens because the agent deleted all my work. this has  cuase me too much time and its sad. 

### Expected behavior

i don't know where to start maybe this is not for me.

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = Farmerbrownj
Chat ID = 80daac9b6367
```

**Comment by endocytosis** [comment]
Hi @creatorsam1, 

Sorry to hear this! Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection?

**Comment by creatorsam1** [comment]
Thank you so much @endocytosis

**Comment by endocytosis** [comment]
@creatorsam1,

You're welcome and glad to hear this helped! We appreciate your patience as the team continues to make improvements!
