### ISSUE TITLE
 This message didn't complete its response.

### ISSUE THREAD

**Issue by ElMaxito** [stackblitz/bolt.new#2095]
### Describe the bug

This message didn't complete its response. Then loading spinner keeps going forever.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wvrfqg

### Steps to reproduce

Enter a prompt to build a website.

### Expected behavior

Starts writing files and doenst crash half way.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73601943,
  "usedJSHeapSize": 69800923,
  "jsHeapSizeLimit": 4294705152
}
Username = ElMaxito
Chat ID = c387fdf0aef0
```

**Comment by kc0tlh** [comment]
@ElMaxito tracking this in #1073
