### ISSUE TITLE
Token Consumption Policy During Bug Fixes by AI

### ISSUE THREAD

**Issue by Evirgen88** [stackblitz/bolt.new#2096]
### Describe the bug

Dear Development Team/Support Team,

I hope this message finds you well.

I am a regular user of your AI coding service, and I greatly appreciate the powerful capabilities and the efficiency it offers in generating code. However, I would like to bring to your attention a concern related to the token consumption policy.

Currently, it appears that tokens are deducted from my account not only when the AI successfully generates a code snippet but also when it identifies and fixes bugs in the code during the generation process. While I understand the necessity of resource usage for code generation, I believe it is not fair for token consumption to occur in cases where the AI is simply correcting its own mistakes.

Could you please consider adjusting the policy so that token usage is not deducted for bug fixes performed by the AI, or at least offer a separate model for billing that acknowledges this distinction? I believe this change could lead to a more fair and transparent experience for all users.

Thank you for taking the time to consider this matter. I look forward to your response and any potential updates on this issue.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-c5dytl

### Steps to reproduce

Go to the AI coding interface.
Enter a prompt for generating code.
Observe the token deduction as the AI starts generating the code.
Notice that even when the AI finds a bug in its generated code and then fixes it, tokens are still deducted.

### Expected behavior

Tokens should only be deducted for successful code generation, not when the AI uses resources to correct its own errors. Ideally, the token consumption policy should be adjusted to avoid penalizing users for bug fixes.

### Platform

Chrome web browser

### Additional context

This issue affects the overall user experience and transparency of token usage. A clearer policy on token consumption during self-corrective bug fixes by the AI could enhance user satisfaction.

**Comment by endocytosis** [comment]
Hi @Evirgen88, 

Appreciate the feedback! AI model compute is required for both code generation and error resolution. We expect the efficiency of these processes to improve as AI models improve. 

The team is hard at work maximizing token efficiency, especially with regards to error resolution logic. This thread [here](https://github.com/stackblitz/bolt.new/issues/678) contains information on using Bolt most effectively as well as updates on ways the team is making error resolution more efficient. We appreciate your patience as improvements continue to be made!
