### ISSUE TITLE
Not able to see my previous chat

### ISSUE THREAD

**Issue by blbacelar** [stackblitz/bolt.new#2098]
### Describe the bug

When I open bolt.new and open the side menu I can't see my previous chat.  I had a full app that I was almost finishing it and now I can't find it. 

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

As you can see I don't see any project here in this screenshot
![Screenshot 2024-11-12 at 7 22 29 AM](https://github.com/user-attachments/assets/140e574f-0003-4b98-94bb-e7e663c97eb0)

But if I open https://stackblitz.com/ I can see my previous project, only the ones that I created a repo. But unfortunately the project that I was working on I didn't create the repo and I don't see how can I recover it. 
![Screenshot 2024-11-12 at 7 23 28 AM](https://github.com/user-attachments/assets/6a0a5bb9-7ab5-4c6b-b921-02b7c03e8064)

### Expected behavior

I should be able to see all my projects. 

### Platform

- OS:  macOS
- Browser: Chrome
- Version: Version 130.0.6723.117 (Official Build) (arm64)

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
