### ISSUE TITLE
Bolt Now Space Invaders

### ISSUE THREAD

**Issue by MVC73** [stackblitz/bolt.new#2099]
### Describe the bug

I asked bolt.now to create a space invader. It did it at the first try but then I could not destroy the invaders. I then asked it to fix it and then multiple errors happened and then while I had to prompt it 5 times to fix the errors my token limits ran out. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mzi4kw

### Steps to reproduce

1. request to create a space invader game
2. Once built, the requested it to be able to shoot the invaders
3. Still not fixed, then no invaders came
4. request again to fix, then ship moved left to right but the firing stayed in the middle
5. Request to fix again - then bug error reported: SyntaxError: The requested module '/src/components/GameHUD.tsx' does not provide an export named 'GameHUD'
6. Request to fix - ran out of token limits. 
7. Game over. 

### Expected behavior

I expected a simple game like space invader to work perfectly. 

### Platform

- OS: Mac Os Apple M2 
- Browser: Chrome
- Version: Version 130.0.6723.117 (Official Build)

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Unfortunately we are unable to provide code assistance for individual projects at this time.

Appreciate your patience as the team continues to make improvements!
