### ISSUE TITLE
Forbidden Issue

### ISSUE THREAD

**Issue by Gaurav-Wankhede** [stackblitz/bolt.new#210]
### Describe the bug

When I am Prompting to build a website it is showing forbidden. it is not generating anything. Can you please find out the issue.

I wrote a Prompt like this below

Create a Educational Website like having information about UPSC.

I want to have my Private Dashboard from there I can Upload the Content related to UPSC Prelims, Mains, Interview, Blog. Depending upon the Category it will automatically Settle down. Also It can be filtered by the Date and Categories. Additionally use Technologies like NEXTJS14, TypeScript, Shadcn for Dark and Light Theme, Use Hamburger for Mobile friendly, Theme primary color will be #daa520. And From Dashboard the Information can be Stored into the JSON Format, Use Appropriate method for Data Retrieval System. These Data can be Stored at specific Private Folder which can be Access by only the Admin. From Dashboard Admin can Add/Update/Delete the Information.

Inside Dashboard Admin can have a option for Text Editor Hence Admin can Write the content according to his requirement, and those content will be showed on the Client Side as a normal User. 

UPSC Categories will follow as following Syllabus Copy:

<Prelims>
UPSC Syllabus for GS Paper (Prelims Paper I)
Current events of national and international importance.
History of India and Indian National Movement.
Indian and World Geography-Physical, Social, Economic Geography of India and the World.
Indian Polity and Governance – Constitution, Political System, Panchayati Raj, Public Policy, Rights Issues, etc.
Economic and Social Development – Sustainable Development, Poverty, Inclusion, Demographics, Social Sector initiatives, etc.
General issues on Environmental Ecology, Biodiversity, and Climate Change – that do not require subject specialisation.
General Science

UPSC Syllabus for CSAT Paper (Prelims Paper-II)
Comprehension
Interpersonal skills including communication skills
Logical reasoning and analytical ability
Decision-making and problem solving
General mental ability
Basic numeracy (numbers and their relations, orders of magnitude, etc.) (Class X level), Data interpretation (charts, graphs, tables, data sufficiency, etc. – Class X level)
</Prelims>

<Mains>
IAS Syllabus for UPSC Mains GS-I
General Studies‐I is also called Paper-II of UPSC Mains. It covers –  Indian Heritage and Culture, History and Geography of the World and Society. The detailed UPSC Syllabus for this paper is given below:

Indian culture will cover the salient aspects of Art Forms, literature and Architecture from ancient to modern times.
Modern Indian history from about the middle of the eighteenth century until the present – significant events, personalities, issues.
The Freedom Struggle — its various stages and important contributors/contributions from different parts of the country.
Post-independence consolidation and reorganization within the country.
History of the world will include events from 18th century such as industrial revolution, world wars, redrawal of national boundaries, colonization, decolonization, political philosophies like communism, capitalism, socialism etc.— their forms and effect on the society.
Salient features of Indian Society, Diversity of India.
Role of women and women’s organization, population and associated issues, poverty and developmental issues, urbanization, their problems and their remedies.
Effects of globalization on Indian society.
Social empowerment, communalism, regionalism & secularism.
Salient features of world’s physical geography.
Distribution of key natural resources across the world (including South Asia and the Indian sub-continent); factors responsible for the location of primary, secondary, and tertiary sector industries in various parts of the world (including India).
Important Geophysical phenomena such as earthquakes, Tsunami, Volcanic activity, cyclone. etc., geographical features and their location-changes in critical geographical features (including water-bodies and ice-caps) and in flora and fauna and the effects of such changes. 
Get the UPSC Mains GS Paper 1 Strategy in the linked article.

IAS Syllabus for Mains GS-II
General Studies-II is also called Paper-III of UPSC Mains. It majorly covers Governance, Constitution, Polity, Social Justice and International relations. The detailed UPSC syllabus for this paper is given below:

Constitution of India —historical underpinnings, evolution, features, amendments, significant provisions and basic structure.
Functions and responsibilities of the Union and the States, issues and challenges pertaining to the federal structure, devolution of powers and finances up to local levels and challenges therein.
Separation of powers between various organs dispute redressal mechanisms and institutions.
Comparison of the Indian constitutional scheme with that of other countries.
Parliament and State legislatures—structure, functioning, conduct of business, powers & privileges and issues arising out of these.
Structure, organization and functioning of the Executive and the Judiciary—Ministries and Departments of the Government; pressure groups and formal/informal associations and their role in the Polity.
Salient features of the Representation of People’s Act.
Appointment to various Constitutional posts, powers, functions and responsibilities of various Constitutional Bodies.
Statutory, regulatory and various quasi-judicial bodies.
Government policies and interventions for development in various sectors and issues arising out of their design and implementation.
Development processes and the development industry —the role of NGOs, SHGs, various groups and associations, donors, charities, institutional and other stakeholders.
Welfare schemes for vulnerable sections of the population by the Centre and States and the performance of these schemes; mechanisms, laws, institutions and Bodies constituted for the protection and betterment of these vulnerable sections.
Issues relating to development and management of Social Sector/Services relating to Health, Education, Human Resources.
Issues relating to poverty and hunger.
Important aspects of governance, transparency and accountability, e-governance applications, models, successes, limitations, and potential; citizens charters, transparency & accountability and institutional and other measures. 
Role of civil services in a democracy.
India and its neighbourhood- relations.
Bilateral, regional and global groupings and agreements involving India and/or affecting  India’s interests.
Effect of policies and politics of developed and developing countries on India’s interests, Indian diaspora.
Important International institutions, agencies and fora- their structure, mandate. 
Get the UPSC Mains GS Paper 2 Strategy in the linked article.

IAS Syllabus for Mains GS-III
General Studies-III is also called Paper-IV of the UPSC Mains. The major topics covered are Technology, Economic Development, Biodiversity, Environment, Security and Disaster Management. The detailed UPSC syllabus for this paper is given below:

Indian Economy and issues relating to planning, mobilization, of resources, growth, development and employment.
Inclusive growth and issues arising from it.
Government Budgeting.
Major crops-cropping patterns in various parts of the country, – different types of irrigation and irrigation systems storage, transport and marketing of agricultural produce and issues and related constraints; e-technology in the aid of farmers.
Issues related to direct and indirect farm subsidies and minimum support prices; Public Distribution System- objectives, functioning, limitations, revamping; issues of buffer stocks and food security; Technology missions; economics of animal-rearing.
Food processing and related industries in India- scope’ and significance, location, upstream and downstream requirements, supply chain management.
Land reforms in India.
Effects of liberalization on the economy, changes in industrial policy and their effects on industrial growth. 
Infrastructure: Energy, Ports, Roads, Airports, Railways etc.
Investment models.
Science and Technology- developments and their applications and effects in everyday life.
Achievements of Indians in science & technology; indigenization of technology and developing new technology.
Awareness in the fields of IT, Space, Computers, robotics, nano-technology, bio-technology and issues relating to intellectual property rights.
Conservation, environmental pollution and degradation, environmental impact assessment.
Disaster and disaster management.
Linkages between development and spread of extremism.
Role of external state and non-state actors in creating challenges to internal security.
Challenges to internal security through communication networks, role of media and social networking sites in internal security challenges, basics of cyber security; money-laundering and its prevention. 
Security challenges and their management in border areas – linkages of organized crime with terrorism.
Various Security forces and agencies and their mandate. 
Get the UPSC Mains GS Paper 3 Strategy in the linked article.

IAS Syllabus for Mains GS-IV
General Studies Paper-IV is also called Paper-V of UPSC Mains. The major topics covered under it are Ethics, Integrity and Aptitude. This paper will include questions to test the candidates’ attitude and approach to issues relating to integrity, probity in public life and his problem-solving approach to various issues and conflicts faced by him in dealing with society. Questions may utilize the case study approach to determine these aspects. The following broad areas will be covered:

Ethics and Human Interface: Essence, determinants and consequences of Ethics in-human actions; dimensions of ethics; ethics – in private and public relationships. Human Values – lessons from the lives and teachings of great leaders, reformers and administrators; role of family society and educational institutions in inculcating values.
Attitude: content, structure, function; its influence and relation with thought and behaviour; moral and political attitudes; social influence and persuasion.
Aptitude and foundational values for Civil Service, integrity, impartiality and non-partisanship, objectivity, dedication to public service, empathy, tolerance and compassion towards the weaker sections.
Emotional intelligence-concepts, and their utilities and application in administration and governance.
Contributions of moral thinkers and philosophers from India and the world.
Public/Civil service values and Ethics in Public administration: Status and problems; ethical concerns and dilemmas in government and private institutions; laws, rules, regulations and conscience as sources of ethical guidance; accountability and ethical governance; strengthening of ethical and moral values in governance; ethical issues in international relations and funding; corporate governance.
Probity in Governance: Concept of public service; Philosophical basis of governance and probity; Information sharing and transparency in government, Right to Information, Codes of Ethics, Codes of Conduct, Citizen’s Charters, Work culture, Quality of service delivery, Utilization of public funds, challenges of corruption.
Case Studies on the above issues. 
</Mains>

<Interview>
Known as Personality Test, UPSC Interview is the last stage of the examination. There is no defined UPSC syllabus for the interview. Questions are asked from wide-ranging issues.

Candidates who qualify the UPSC Mains Exam will be called for the ‘Personality Test/Interview’. These candidates will be interviewed by a Board appointed by the UPSC.
The objective of the interview is to assess the personal suitability of the candidate for a career in civil services by a board of competent and unbiased observers.
The interview is more of a purposive conversation intended to explore the mental qualities and analytical ability of the candidate.
The Interview test will be 275 marks and the total marks for the written examination is 1750. This sums up to a Grand Total of 2025 Marks, based on which the final merit list will be prepared.
Candidates should note that there are no changes in UPSC Syllabus 2023 in comparison to UPSC Syllabus 2022 and UPSC Syllabus 2021.
</Interview>

According to the given Syllabus Split the Categories and Sub Categories. Those Categories will be Asked to the Admin while Posting his Content.

Make a Comprehensive Full Stack Educational Website with Header having Navigation Menu like (Favicon, Prelims, Mains, Interview, Blog, About, Contact)

In the Home Page there will be Brief about the Website. 

Some Quotes by Reputed Authors that will Randomly generated every day which are related to the UPSC Point of view.

Then 3 Recent Blogs in the Grid like structure. 3 Most Recent Post from Prelims. 3 Most recent Posts from Mains. 3 Most recent Posts from Interview.

Footer with Short Description, Useful Links in the form of List, Contact Details in the form of List, Copyright details.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xu5c8v

### Steps to reproduce

1. Go to bolt.new website
2. Write a prompt
3. Check weather it is processing for long prompt or not.

### Expected behavior

It should generate  the Code, however it gave me forbidden error.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/154fe901-ed06-40b5-b928-82f9bff1ccaa)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Nemikolh** [comment]
Hey @Gaurav-Wankhede! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in #77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
