### ISSUE TITLE
payment plan

### ISSUE THREAD

**Issue by jpstones** [stackblitz/bolt.new#2100]
Hi, first offlove the bolt app.nice work

I seem to be stcuk on the 50 plan when i want to downgrade to the 20. Please fix
also I've added a few coupons for 30% off that were valid but did not seem to be applied, which sucks.

JP

**Comment by endocytosis** [comment]
Hi @jpstones,

Please reach out to hello@stackblitz.com with your account information for assistance with downgrading your plan.
