### ISSUE TITLE
Deploy to existing netlify instance

### ISSUE THREAD

**Issue by mattyJmoss** [stackblitz/bolt.new#2101]
**Is your feature request related to a problem? Please describe:**

It would be nice if the app would deploy to the netfliy site it first deployed to instead of creating new sites each time.
**Describe the solution you'd like:**

Not sure if it already does this - but I couldn't figure it out.

**Additional context:**

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this request and are tracking it here: #49.
