### ISSUE TITLE
not following instuctions 

### ISSUE THREAD

**Issue by AdamMonkey10** [stackblitz/bolt.new#2102]
### Describe the bug

time and again you get a component correct only for it to get changed when you are working on something else. most of my tokens are wasted put things back to how we had them.  constantly have to tell it not to change anything else but still it does.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-taz6ai

### Steps to reproduce

time and again i change one thing only to see we have lost something else

### Expected behavior

just to not break things unless asked to look at them 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi all, 

Appreciate your patience as the team continues to make improvements! Something else you can try is if you don't want a file to be change by the AI right click that file in the Bolt code editor and select "Lock file", which will prevent the AI from making further changes. This can be done for multiple files.
