### ISSUE TITLE
no able use ai nd pre view is not working in ai but its working on stackblitz project

### ISSUE THREAD

**Issue by rahul74165** [stackblitz/bolt.new#2105]
### Describe the bug

preview not working

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-iqyskr

### Steps to reproduce

after compelete cod epreview is not working

### Expected behavior

preview should once npm run dev after this command

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 48954063,
  "usedJSHeapSize": 44340179,
  "jsHeapSizeLimit": 4294705152
}
Username = loke
Chat ID = 169932753ae2
```

### Additional context

pre view not working

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
