### ISSUE TITLE
Failed building the project. Make sure the build command is correct and try again

### ISSUE THREAD

**Issue by bradical1979** [stackblitz/bolt.new#2107]
### Describe the bug

I've spent hours building what seems like a great project, it works fine in preview (somtimes) but it will not build and deploy. "
"Failed building the project. Make sure the build command is correct and try again."  So I tell that to Bolt, it tries again and same thing. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zkr3w6

### Steps to reproduce

Click Deploy

### Expected behavior

Deploy correctly to a live environment. The Bolt app seems to really struggle with figuring out how to correct errors, kinda doing the same thing over and over.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 293482351,
  "usedJSHeapSize": 244613243,
  "jsHeapSizeLimit": 2160066560
}
Username = bradical1979
Chat ID = 7435145884ce
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019

**Comment by bradical1979** [comment]
It’s really not fair to charge credits when there are bugs costing the credits! Sent from my iPhoneOn Nov 12, 2024, at 9:36 AM, Brian ***@***.***> wrote:﻿
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
