### ISSUE TITLE
 Failed building the project

### ISSUE THREAD

**Issue by yopellio** [stackblitz/bolt.new#2108]
### Describe the bug

I had this problem when i deploy the project.
Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1kbzkt

### Steps to reproduce

Click on deploy

### Expected behavior

Deploy the site on netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52105331,
  "usedJSHeapSize": 50018067,
  "jsHeapSizeLimit": 4294705152
}
Username = yopellio
Chat ID = 989a47cba133
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
