### ISSUE TITLE
NOTHING EVEN IN THE PAID SECTION

### ISSUE THREAD

**Issue by Sreenivas1323** [stackblitz/bolt.new#211]
### Describe the bug

Hey, I just wanted to try out all of the paid version i.e, $9 dollar thing, and have not been able to atleast try out something new via prompt. Im just getting the "forbidden" error via the panel. please fix this.

![Screenshot 2024-10-08 at 15 39 59](https://github.com/user-attachments/assets/b9edafd1-04b7-4c9f-9176-7a5fd49fd794)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v2pn6z

### Steps to reproduce

1. Go to the bolt.new
2. Login
3. Buy the $9 tier
4. enter a prompt other than the suggested, 
5. Boom! you can't get anything in return/ or just fixed with this error as the screenshot.

### Expected behavior

Get the code and everything that it meant to do

### Platform

- OS: [MAC]
- Browser: [Chromium/ARC]

**Comment by lazuee** [comment]
#77

**Comment by kirjavascript** [comment]
Hey @Sreenivas1323! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
