### ISSUE TITLE
Throwing Errors in code

### ISSUE THREAD

**Issue by AliZaidBabar** [stackblitz/bolt.new#2110]
### Describe the bug

[plugin:vite:css] [postcss] /home/project/src/index.css:1:1: The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.
/home/project/src/index.css:1:0
1  |  @tailwind base;
   |  ^
2  |  @tailwind components;
3  |  @tailwind utilities;

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wo3hns

### Steps to reproduce

[plugin:vite:css] [postcss] /home/project/src/index.css:1:1: The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.
/home/project/src/index.css:1:0
1  |  @tailwind base;
   |  ^
2  |  @tailwind components;
3  |  @tailwind utilities;

### Expected behavior

correct code which respond correctly. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50420537,
  "usedJSHeapSize": 44780301,
  "jsHeapSizeLimit": 2160066560
}
Username = Ali Zaid Babar
Chat ID = 7b0e82522387
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
