### ISSUE TITLE
images can't be displayed for some reason

### ISSUE THREAD

**Issue by Mr777xx** [stackblitz/bolt.new#2114]
### Describe the bug

I've uploaded images to stack blitz of Aztec to put them in as placeholders and it just can't seem to do it it keeps updating the path I've been at it nearly an hour it's not a good way of working

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-emxcry

### Steps to reproduce

We'll ask it to you know put the image in In the image

### Expected behavior

I expected to be able to display a simple png image of a product in the product section

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/0c5e7e68-7ed4-46d5-b1f7-2ddb5a16ca69)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112922999,
  "usedJSHeapSize": 105162311,
  "jsHeapSizeLimit": 4294705152
}
Username = Mr777xx
Chat ID = 56825d99ecad
```

### Additional context

Very frustrating very simple thing to do you know create a path between a directory image and where you want it displayed and it just can't seem to do it

**Comment by endocytosis** [comment]
Hi @Mr777xx, 

Are you able to post a link to the StackBlitz project with permissions set to public so we can take a look?

**Comment by Mr777xx** [comment]
Hi,

I've set the link to public https://bolt.new/~/sb1-emxcry

Regards

**Comment by endocytosis** [comment]
Hi @Mr777xx, 

It looks like the image being referenced on the products.ts page has an invalid path. The ability to upload images is a known issue and is being tracked here: #1809. 

In the interim, if you go to your products.ts page and directly specify the image path, this should resolve the issue. In other words: 

image: 'IMAGE PATH'

We appreciate your patience as improvements continue to be made!
