### ISSUE TITLE
Bolt wont use GPT 4o mini

### ISSUE THREAD

**Issue by dilzilla** [stackblitz/bolt.new#2115]
### Describe the bug

I tried to get bolt to use GPT 4o mini and it won't do it. It says it's not a real model and therefore it won't do it even when I change the code and then says there's an error and it won't execute.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ua4tz9

### Steps to reproduce

I was having it use open AI API in my app and it tried using GPT 4 turbo I told her I wanted to use the newer model and it said that it didn't exist and it's not a valid model and cannot move forward until I choose a valid model.

### Expected behavior

I would expect it to have a modern knowledge of what models are available to use and even if it doesn't know, it should allow me to change it to what I want, but unfortunately, it doesn't work.

### Screen Recording / Screenshot

<img width="1312" alt="Screenshot 2024-11-12 at 11 27 02 AM" src="https://github.com/user-attachments/assets/4241dac4-4cee-4290-829c-08f66fd7786e">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72127758,
  "usedJSHeapSize": 66061550,
  "jsHeapSizeLimit": 4294705152
}
Username = Dilzilla
Chat ID = 6dfa1623c524
```

**Comment by endocytosis** [comment]
Hi @dilzilla, 

Appreciate the feedback! Currently, Bolt uses Anthropic models for inference. However, Bolt is open source many individuals have had success forking the project to use with different models. Hope this helps!
