### ISSUE TITLE
Bolt appends text to the end of JS files

### ISSUE THREAD

**Issue by chadananda** [stackblitz/bolt.new#2117]
### Describe the bug

the generated code is not always parsed out correctly and the code file gets text appended like:

```
</content></file>
</boltArtifact>

Key improvements:

1. Secure file permissions:
   - Config file is created with `0o600` permissions (readable/writable only by owner)
   - Stored in user's home directory (`~/.sifter/config.json`)
   ...
```
Something then goes wrong and this file becomes possibly locked. Any further changes or manual fixes are automatically reverted to this errored state. I have to reload the project to continue working.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jbh5mr

### Steps to reproduce

Very intermittent issue. After several hours of work, it happened twice.

### Expected behavior

Generated code should not have appended non-code text

### Screen Recording / Screenshot

<img width="772" alt="image" src="https://github.com/user-attachments/assets/2c34cce6-2059-4153-b758-25546663b552">

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79321553,
  "usedJSHeapSize": 74251433,
  "jsHeapSizeLimit": 4294705152
}
Username = chadananda
Chat ID = 1a441d18bf96
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2119
