### ISSUE TITLE
Netlify Claim URL After Deploy Not Provided

### ISSUE THREAD

**Issue by drssr-coding** [stackblitz/bolt.new#2118]
### Describe the bug

Don't know if it's normal or not but at the beginning Bolt always gave me the claim URL after the deploy on Netlifyand now it stopped... Thank you!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rohgxl

### Steps to reproduce

1. Ask for a deploy
2. If the claim URL is not provided ask for it
3. Ask it again and again (looping)

### Expected behavior

I would expect for the claim URL for Netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 163116187,
  "usedJSHeapSize": 156302947,
  "jsHeapSizeLimit": 2160066560
}
Username = drssr-coding
Chat ID = 666aa3994339
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020.
