### ISSUE TITLE
Preview Not Rendering

### ISSUE THREAD

**Issue by LesterAIMaster** [stackblitz/bolt.new#2122]
### Describe the bug

Unable to view a preview. Showing a blank white screen.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-slidev-kah5ap

### Steps to reproduce

Preview shows blank white screen and not the rendered code.

### Expected behavior

To show a preview of the rendered code.

### Platform

```
Browser name = Safari
Full version = 17.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
performance.memory = undefined
Username = LesterAIMaster
Chat ID = 9d8ca5428e22
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
