### ISSUE TITLE
local images not working properly when added to code

### ISSUE THREAD

**Issue by brianmkogut** [stackblitz/bolt.new#2123]
### Describe the bug

I'm uploading an image to use on a site build and it says its putting it in place but it is not.  Web linked images work but local upload does not

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-c5f7mk

### Steps to reproduce

Request to use an image you have uploaded

### Expected behavior

place image on site

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73137334,
  "usedJSHeapSize": 53148002,
  "jsHeapSizeLimit": 4294705152
}
Username = briank
Chat ID = afedfc853921
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1809
