### ISSUE TITLE
Had Long Converstion , Used enhace prompt for a promt - After that Bolt got crashed - All history related to that conversation gone

### ISSUE THREAD

**Issue by dineshc77** [stackblitz/bolt.new#2127]
### Describe the bug

After long conversation i used AI Enhancement button for prompt - On that submit bolt got crashed and all history related to that conversation deleted

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-anc16u

### Steps to reproduce

1. start conversation
2. After a while whle creating prompt use ai enhancer
3.sumbit

### Expected behavior

Should have given better rsult

### Platform

- OS: [Windows]
- Browser: [Edge]
- Version: [130.0.2849.80]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
