### ISSUE TITLE
Deployment of APP in Netlify in my own account or deploy with claim URL?

### ISSUE THREAD

**Issue by dipaksaraf** [stackblitz/bolt.new#2128]
### Describe the bug

I am trying to deploy the site to netlify with claim URL, so that I can add the deployed app in my netlify URL. Tried this 4 times today but it is just deploying the app without any claim URL. Deployed here >> https://sweet-stardust-b70ee1.netlify.app/

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-abfgnx

### Steps to reproduce

Deploy the site with claim URL

### Expected behavior

Should provide the claim URL once it has been deployed

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = dipaksaraf
Chat ID = 97b8da26a7cb
```

**Comment by dipaksaraf** [comment]
It is just burning my token without any claim URL tried 3 times and it deducted 100K token each time

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020
