### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Hk13-dev** [stackblitz/bolt.new#2130]
### Describe the bug

NotFoundError : échec de l'exécution de « insertBefore » sur « Node » : le nœud avant lequel le nouveau nœud doit être inséré n'est pas un enfant de ce nœud.
    chez ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    chez moi (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m7zg6r

### Steps to reproduce

erreur a chaque execution code

### Expected behavior

la premiere etape tombe en erreur

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 123367436,
  "usedJSHeapSize": 109000272,
  "jsHeapSizeLimit": 4294705152
}
Username = Hk13-dev
Chat ID = a683960aa1b4
```

**Comment by AriPerkkio** [comment]
Hey @Hk13-dev, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
