### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by mumiix1** [stackblitz/bolt.new#2131]
### Describe the bug

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nativescript-community%2fui-document-scanner - Not found
npm ERR! 404 
npm ERR! 404  '@nativescript-community/ui-document-scanner@^1.2.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-12T20_04_34_910Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kgwpts

### Steps to reproduce

while creating the project i give this issues. 

### Expected behavior

it should install the npm

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ed99ab32-0db8-4f84-b3ca-461ba80528a3)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90438053,
  "usedJSHeapSize": 63336985,
  "jsHeapSizeLimit": 4294705152
}
Username = mumiix
Chat ID = 241cc526d34b
```

**Comment by kc0tlh** [comment]
@mumiix1 Please subscribe to #2021 for updates as we are investigating causes of this error there!
