### ISSUE TITLE
I can't see my history anymore. Somehow the page crashe

### ISSUE THREAD

**Issue by DaChillexx** [stackblitz/bolt.new#2135]
### Describe the bug

I can't see my history anymore. I want to go back to a checkpoint, because there was everything still working - now it doesn't. Please help me.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-blvbxk

### Steps to reproduce

Write a prompt.
While he is working, go to "my subscription" to check how many tokens left. Go back and then it crashed.

### Expected behavior

Show me my history again. Full history.

### Platform

```
Browser name = Safari
Full version = 16.6.1
Major version = 16
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6.1 Safari/605.1.15
performance.memory = undefined
Username = DaChillexx
Chat ID = 05b72395a745
```

**Comment by endocytosis** [comment]
Hi @DaChillexx,

Sorry to hear that! Are you able to access your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection?

**Comment by endocytosis** [comment]
We are tracking chat persistence here: #39. An update was recently released for chat persistence so you should see your chat history going forward.
