### ISSUE TITLE
cant see and there isnt anything coming up on preview on anything I prompt. Have i just wasted my tokens???

### ISSUE THREAD

**Issue by rama4343** [stackblitz/bolt.new#2138]
### Describe the bug

cant see and there isnt anything coming up on preview on anything I prompt. Have i just wasted my tokens???
And theres warning coming up.

~/project
❯ npm install
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead

added 353 packages in 5s

76 packages are looking for funding
  run `npm fund` for details

~/project 5s
❯ npm run dev

> etsy-research-app@0.1.0 dev
> vite

  VITE v5.4.11  ready in 764 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-d9ddxj

### Steps to reproduce

dont know you tell me.cant see and there isnt anything coming up on preview on anything I prompt. Have i just wasted my tokens???

### Expected behavior

<img width="1439" alt="Screenshot 2024-11-12 at 2 37 06 PM" src="https://github.com/user-attachments/assets/0f8f2a49-819c-4855-97f6-7808e34688b9">

### Screen Recording / Screenshot

<img width="1439" alt="Screenshot 2024-11-12 at 2 37 06 PM" src="https://github.com/user-attachments/assets/92a09b38-fcbc-4176-9464-74bbe7ef285d">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65865046,
  "usedJSHeapSize": 59940434,
  "jsHeapSizeLimit": 2160066560
}
Username = rama@
Chat ID = defb53b6a4bf
```

### Additional context

~/project
❯ npm install
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead

added 353 packages in 5s

76 packages are looking for funding
  run `npm fund` for details

~/project 5s
❯ npm run dev

> etsy-research-app@0.1.0 dev
> vite

  VITE v5.4.11  ready in 764 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

**Comment by rama4343** [comment]
Hi Brain,

Does that mean I wasted my tokens??
And do I get this back if it has wasted?

On 13 Nov 2024, at 2:04 pm, Brian ***@***.***> wrote:

﻿

Closed #2138<https://github.com/stackblitz/bolt.new/issues/2138> as completed.

**Comment by rama4343** [comment]
Nothing is working and have tried what you said. [image0.jpeg]
Sent from my iPhone

On 13 Nov 2024, at 2:04 pm, Brian ***@***.***> wrote:

﻿

Appreciate the feedback! We are aware of this issue and are tracking it here: #1791<https://github.com/stackblitz/bolt.new/issues/1791>. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

**Comment by endocytosis** [comment]
Hi, 

While manually running "npm run dev" works in some cases, it unfortunately does not resolve all cases. The team is hard at work continuing to improve performance. Refund requests are handled through hello@stackblitz.com. 

We appreciate your patience as improvements continue to be made!
