### ISSUE TITLE
bolt.new - Project not show up 

### ISSUE THREAD

**Issue by ClausGS** [stackblitz/bolt.new#214]
### Describe the bug

I have created a project in bolt.new on my work computer.
Now i log into my account on my home computer and the project / chat i have on my work computer is not in the side bar...
I use same account and same GitHub account
What's the problem here ???? 

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

log into my account and then can not find earler project 

### Expected behavior

my earlier project should be avaliabl 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samdenty** [comment]
Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #39!
