### ISSUE TITLE
Dont have credits.

### ISSUE THREAD

**Issue by harielxavier** [stackblitz/bolt.new#2140]
### Describe the bug

Everytime i am nearing a project i get this, then i start a new one. this is my 4th time building my photography website. I am spending tons of money here and i have NO results I am really getting discouraged here.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sfumht

### Steps to reproduce

No Need, just log on, it says i don't have tokens i an using 214300 of 20000 but all i do is say fix or a simple command and nothing works

### Expected behavior

The shit to work, expect for me to actually finish something so i can publish the website instead of spending time and money.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/664cf7b3-d104-49e1-bad5-44b379c33c43)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 123542606,
  "usedJSHeapSize": 114851106,
  "jsHeapSizeLimit": 4294705152
}
Username = harielxavier
Chat ID = 2f1f5ba818ac
```

### Additional context

I really need a refund on credits here. Please look at how many unfinished projects I have. Half of them is because i can no longer continue. the other half i didn't knew you had an upgrade so i redid existing projects. I have ZERO ROI from all the money i am spending

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322. Refund requests are handled through hello@stackblitz.com.

**Comment by harielxavier** [comment]
Hi,
So what does this mean? I am stuck with all these unfinished projects ? I am pushing a deadline.


From: Brian ***@***.***>
Date: Tuesday, November 12, 2024 at 8:55 PM
To: stackblitz/bolt.new ***@***.***>
Cc: harielxavier ***@***.***>, Author ***@***.***>
Subject: Re: [stackblitz/bolt.new] Dont have credits. (Issue #2140)


Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322<https://github.com/stackblitz/bolt.new/issues/1322>. Refund requests are handled through ***@***.******@***.***>.

**Comment by harielxavier** [comment]
Hello can i get a response?

**Comment by endocytosis** [comment]
Hi @harielxavier, 

Apologies for the frustration. At this point if the model is unable to resolve those errors then manual intervention is required. Something that might help is pasting those error messages into an LLM outside of Bolt and asking for a specific explanation on how to resolve the error. Perplexity is a good tool for this as well as it will link to reference sites which often have additional information. From there, you could try to manually resolve the error. 

Refund requests are handled through hello@stackblitz.com.

**Comment by harielxavier** [comment]
Brian can you help with this? As I wrote to them and I’ve gotten no response.


From: Brian ***@***.***>
Date: Wednesday, November 13, 2024 at 11:01 PM
To: stackblitz/bolt.new ***@***.***>
Cc: harielxavier ***@***.***>, Mention ***@***.***>
Subject: Re: [stackblitz/bolt.new] Dont have credits. (Issue #2140)


Hi @harielxavier<https://github.com/harielxavier>,

Apologies for the frustration. At this point if the model is unable to resolve those errors then manual intervention is required. Something that might help is pasting those error messages into an LLM outside of Bolt and asking for a specific explanation on how to resolve the error. Perplexity is a good tool for this as well as it will link to reference sites which often have additional information. From there, you could try to manually resolve the error.

Refund requests are handled through ***@***.******@***.***>.
