### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by sirking1991** [stackblitz/bolt.new#2142]
### Describe the bug

When generating an image, the AI just infinitely writes `A`

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yageo4

### Steps to reproduce

As AI to generate an image

### Expected behavior

It should stop when the image is complete.

### Screen Recording / Screenshot

<img width="1140" alt="Screenshot 2024-11-13 at 7 20 54 am" src="https://github.com/user-attachments/assets/42434a94-ace7-41c7-9b88-cd48c5580b8f">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109961385,
  "usedJSHeapSize": 95043433,
  "jsHeapSizeLimit": 2160066560
}
Username = sirking1991
Chat ID = 0158bc916e18
```

### Additional context

Error:
```
You cancelled this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve, or the AI produces undesired output, in which case manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!

**Comment by sirking1991** [comment]
Cool!

I'm really liking #boltnew!

I hope I can have these as a plugin for VC.

Thanks,
*Sherwin de Jesus*
Mobile:+63 920.475.9976
------------------------------------------------------------------------------------------------------------
Life is not measured by the number of breaths we take, but by the moments
that take our breath away.
------------------------------------------------------------------------------------------------------------

**Comment by endocytosis** [comment]
Hi @sirking1991, 

Glad you are liking Bolt! We appreciate your patience as the team continues to make improvements!
