### ISSUE TITLE
the application is giving me a forbidden feature 

### ISSUE THREAD

**Issue by paradox626** [stackblitz/bolt.new#215]
### Describe the bug

![image](https://github.com/user-attachments/assets/e9a3a776-ecc2-4ed5-b018-cb0a40d0f099)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2dkjdh

### Steps to reproduce

go to the chat UI click on anything and it will give a forbidden message

### Expected behavior

supposed to work normally 
![image](https://github.com/user-attachments/assets/1e68f7d3-51af-4787-9ae9-1f94f1772dc5)

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/6c7e031f-e095-4aeb-a7ce-653b4329321e)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by vc-min** [comment]
Me too bro. Why?

**Comment by kirjavascript** [comment]
Hey! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/77. We will let you know when we have a good solution in place.

**Comment by paradox626** [comment]
Hello

I apologize but why this issue is being seen on the platform I would like
to learn

**Comment by paradox626** [comment]
I would like to know what makes the issue that the bolt chat functions
don’t work it goes straight to forbidden some said is that the geographic
location of my residence.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
