### ISSUE TITLE
The same problem every time I try to deploy

### ISSUE THREAD

**Issue by Crispoloko** [stackblitz/bolt.new#2150]
### Describe the bug

I'll start the deployment process. The application will be built and deployed to Netlify. Let me check the deployment status and provide you with the live URL once it's ready.

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cyq6id

### Steps to reproduce

1. deploy
2. ask to fix
3. doesn`t work
4. waste my precious time

### Expected behavior

fix the problem

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49611440,
  "usedJSHeapSize": 44772812,
  "jsHeapSizeLimit": 2160066560
}
Username = Crispo
Chat ID = 829fbe6e911a
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019.
