### ISSUE TITLE
Previous conversation erased

### ISSUE THREAD

**Issue by fred039** [stackblitz/bolt.new#2151]
### Describe the bug

I was testing bolt and when I ran out of tokens I clicked on the "Open with Stackblitz" button. When I navigated back to bolt the previous conversation was erased and there were some messages referring to bolt importing the stackblitz project into bolt, even though I started the project in Bolt. One of the messages said this "I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code." 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dcrkt3

### Steps to reproduce

1. While on the free trial, ask Bolt to create something and prompt it until it runs out of tokens.
2. Open the project on Stackblitz 
3. Navigate back to Bolt
4. Refresh the page

### Expected behavior

I expected the whole conversation to remain when navigating back to Bolt after opening the project on Stackblitz. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 39582215,
  "usedJSHeapSize": 37897911,
  "jsHeapSizeLimit": 4294705152
}
Username = fred039
Chat ID = 8c5858223f3f
```

**Comment by endocytosis** [comment]
Hi @fred039,

Sorry to hear this! Are you able to access your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt, clicking Collections on the left-hand side of the page, then opening Bolt Collection?

**Comment by fred039** [comment]
It takes me to the code in stackblitz, but I still can't see the previous
conversation.

**Comment by endocytosis** [comment]
Appreciate the feedback! Chat persistence is a known issues and is being tracked here: #39.
