### ISSUE TITLE
Prod site on netlify is not updated. I tried whole day to work with oyur service and still getting no progress. 

### ISSUE THREAD

**Issue by alpsla** [stackblitz/bolt.new#2152]
### Describe the bug

I tried whole day to work with your service and still getting no progress. Everything looks very nice for me and would like to continue, but we stack :( 
The development environment works correctly with all translations and content
Production deployment is not reflecting changes despite successful deployments
We've already tried:
Forcing a clean cache build with a cache-buster plugin
Setting no-cache headers
Adding a build-time variable to force new builds
Clearing browser cache.
Please advise,
regards, Rostislav

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yn7aou

### Steps to reproduce

Made changes to the codebase (removed language switcher, updated translations)
Changes work correctly in development environment
Deployed to production using Netlify
Production site (familycentral.io) remains unchanged:
Still shows language switcher
Missing feature card titles and content
Shows placeholder text like "features.title" instead of actual content

### Expected behavior

Production site should match development environment:
Language switcher should be removed
Feature cards should display proper titles and descriptions
All translations should be properly rendered
No placeholder text should be visible

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90628194,
  "usedJSHeapSize": 84455702,
  "jsHeapSizeLimit": 4294705152
}
Username = alpsla
Chat ID = ff7732ad13c7
```

### Additional context

Build Configuration:

Using Vite for building
TypeScript compilation is enabled
Build command: npm run build
Output directory: dist
Environment Details:

Node.js version: 20
Production URL: https://familycentral.io/
Preview URL: https://jocular-quokka-b1e951.netlify.app/
Recent Changes:

Updated netlify.toml with proper cache headers
Added environment variables for production/preview contexts
Modified build command to include TypeScript compilation
Removed language switcher component
Updated i18n configuration
Deployment Status:

Last successful deployment: Today at 3:35 PM
Build logs show successful completion
No visible errors in Netlify deployment logs
Cache headers are set correctly in netlify.toml
Troubleshooting Steps Attempted:

Cleared browser cache
Tested in incognito mode
Verified build output locally
Checked Netlify deployment settings
Added force=true to redirects
Set Cache-Control headers to prevent caching

**Comment by endocytosis** [comment]
Hi @alpsla,

Appreciate the feedback! We are aware of this feature request and are tracking it here: #49. Currently, once a domain in claimed for a project in Netlify updates to the site associated with that domain must be performed outside of Bolt. However, you can expect more seamless integration as described in #49 in the near future. We appreciate your patience as the team continues to make improvements!

**Comment by alpsla** [comment]
Thanks for the clarification, Brian. It gives me at least an understanding of available options and stops trying to troubleshoot of the issue.
I hope you can make a better solution for integration with Netlify.
Regards,
Rostislav
________________________________
