### ISSUE TITLE
The claim URL is a 404 URL

### ISSUE THREAD

**Issue by BenLMT** [stackblitz/bolt.new#2155]
### Describe the bug

The claim URL is a 404 URL

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zhfmrh

### Steps to reproduce

Deploy the project

### Expected behavior

Get a URL to claim the site thanks to netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72241700,
  "usedJSHeapSize": 66739440,
  "jsHeapSizeLimit": 2160066560
}
Username = Crackito
Chat ID = 99917f90141e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020
