### ISSUE TITLE
Bolt.new is down ;(

### ISSUE THREAD

**Issue by SecteurA** [stackblitz/bolt.new#2158]
### Describe the bug

i think that Bolt.new is down !
<img width="1140" alt="Capture d’écran 2024-11-13 à 04 20 35" src="https://github.com/user-attachments/assets/70b874be-de66-4a85-9c70-5102ca3a36c9">

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Just enter the main url it's not working !

### Expected behavior

it should work

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @SecteurA, 

Given the high demand we have been seeing the team was making some database upgrades but everything should be good to go now! We will work to communicate this more clearly in the future. Appreciate your patience as improvements continue to be made!

**Comment by caughtonline** [comment]
Der Bolt.new, i'm currently experiencing the exact same problem, is Bolt.new currently down?

**Comment by julavision** [comment]
Still Down

**Comment by Papa-b-Ndiaye** [comment]
today on 12/19 at 11:59pm
