### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by eventstubsol** [stackblitz/bolt.new#2159]
### Describe the bug

Got an server error while working and after refreshing the page getting application error

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-oq7qhd

### Steps to reproduce

Appeared suddenly, while working

### Expected behavior

Should have worked fine after pressing retry below the prompt box

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e85b386f-a59c-4166-851d-92e578d19518)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by nrgyapp** [comment]
the system has shat itself

**Comment by eventstubsol** [comment]
It is back working again. Wondering what might have been the issue.
