### ISSUE TITLE
forbidden message 

### ISSUE THREAD

**Issue by paradox626** [stackblitz/bolt.new#216]
### Describe the bug

we are still having the issue that is being forbidden 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2dkjdh

### Steps to reproduce

click on the bolt UI it will say forbidden 

### Expected behavior

I would like to have bolt fully functional

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61678560,
  "usedJSHeapSize": 58844360,
  "jsHeapSizeLimit": 2172649472
}
Username = paradox626
Chat ID = b62f5782de9e
```

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
