### ISSUE TITLE
its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site 

### ISSUE THREAD

**Issue by rookie7312** [stackblitz/bolt.new#2164]
### Describe the bug

its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xljwkf

### Steps to reproduce

its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site 

### Expected behavior

its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site 

### Screen Recording / Screenshot

its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56231743,
  "usedJSHeapSize": 53422099,
  "jsHeapSizeLimit": 4294705152
}
Username = rookie7312
Chat ID = 8cdf847d9195
```its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site 

### Additional context

its not working, i make a prompt and there is code there but its showing nothing on the preview window hopeless site

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
