### ISSUE TITLE
Getting the error: Failed to save project. repeatedly 

### ISSUE THREAD

**Issue by richlow** [stackblitz/bolt.new#2166]
### Describe the bug

Seems buggy today. I am getting a repeated message about not being able save my project. Then I get three zipped copies of the source. Not sure what is going on.
![image](https://github.com/user-attachments/assets/011e848a-6e6a-44f9-b58f-4dc49dee84e2)

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-ab1hnb

### Steps to reproduce

Just hang out on the page for a minute and the bugs start poppin' 🐛 🐛 🐛 

### Expected behavior

Errrr expected behaviour is that the file saves quietly and I am not spammed with error messages

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/8c00999d-a1eb-4743-a395-01f7f4fd6426)

### Platform

- OS: macOS
- Browser: Chrome - 
- Version 130.0.6723.117 (Official Build) (arm64)

### Additional context

Bolt.new is great but just not so much today.

**Comment by endocytosis** [comment]
Hi @richlow, 

Are you able to download project files now? There was a recent database upgrade performed to handle increased demand so it may have been related to this.

**Comment by richlow** [comment]
All seems to stable again. I am not getting the error message and forced download of files.

**Comment by endocytosis** [comment]
Glad to hear it!

**Comment by YousefSaeed668** [comment]
i have the same problem any change i apply it gives me same notification why is that

**Comment by ImLunaHey** [comment]
same issue here its been like this for a few hours now.

**Comment by harrysonm** [comment]
Getting this same persistent errors. They are so many they even hide the page header buttons
![Uploading Failed to save errors.png…]()

**Comment by endocytosis** [comment]
Hi @harrysonm, 

Appreciate the additional feedback! We are tracking this issue here: #2762. 

If you are able, could you go to [stackblitz.com](https://stackblitz.com), login (same credentials as Bolt), click Collections on the left-hand side of the page, and then open Bolt Collection to see if any version of your project exists there? In other words, are you able to find any saved version of your project (just so we can confirm the validity of this error message). 

Also, if you click the notification, are you able to successfully download your project?

We appreciate the additional feedback as this is extremely helpful for us to continue to improve Bolt. Thanks!

**Comment by harrysonm** [comment]
Hi,
*In other words, are you able to find any saved version of your project
(just so we can confirm the validity of this error message) *Yes, I can see
my projects in collections. But any edits I make don't persist after login
out and in to bolt. This has been happening for the last few hours.

*Also, if you click the notification, are you able to successfully download
your project?*
Yes, I'm able to.

**Comment by endocytosis** [comment]
@harrysonm, 

Thanks! Really appreciate the additional feedback here!

**Comment by chrisdeweese** [comment]
I'm also getting this issue consistently for the last few hours

**Comment by bug-breeder** [comment]
Same with me

**Comment by rlalire** [comment]
Same with me!

**Comment by Glordbzh** [comment]
hi have the same issue ...

**Comment by Omhsoni** [comment]
hello, I am facing this same issue for the past 2 months. Can anyone help me solve this bug ??

**Comment by ysy523** [comment]
hello , until now also can fix this issues

**Comment by CultkAI** [comment]
Hi,  I have been facing same issue as well. since yesterday. My project exists in stackblitz (collections) but bolt is not able to save any changes to the project.

**Comment by AlfAli117** [comment]
it is hapening to me since yesterday any change that i make the same small window pops out
