### ISSUE TITLE
Blank white page in preview

### ISSUE THREAD

**Issue by jococo** [stackblitz/bolt.new#2168]
### Describe the bug

Tried to create a simple App and the preview just shows a blank white page. Repeated attempts to "fix" the app result in the same blank view.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5ps86n?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

Ask Bolt to create an application

### Expected behavior

The code is written, server started and the preview shows something

### Platform

```
Browser name = Safari
Full version = 17.5
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
performance.memory = undefined
Username = jocphone
Chat ID = 7ff7ac690772
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
