### ISSUE TITLE
Bolt fails to create pwa icon

### ISSUE THREAD

**Issue by stephenlai2021** [stackblitz/bolt.new#2174]
### Describe the bug

Bolt cannot generate pwa icon, i.e. public/pwa-192x192.png, it took so long and got stuck. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m6mj43

### Steps to reproduce

1. Make this app installable and work offline

### Expected behavior

The app should be able to be installabled, and work offline with proper caching strategy especially working with firebase

### Screen Recording / Screenshot

![ScreenShot Tool -20241113161333](https://github.com/user-attachments/assets/f722717d-f8eb-4e89-b5d3-56d5f0772999)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69614415,
  "usedJSHeapSize": 65147691,
  "jsHeapSizeLimit": 4294705152
}
Username = stephenlai2021
Chat ID = 16a3a0cc9044
```

**Comment by endocytosis** [comment]
Hi @stephenlai2021, 

Bolt currently does not have the ability to store images in its file directory or generate images directly. We are aware of this issue and are tracking it here: #1809. You could try generating an image with an AI image generation tool outside of Bolt and then follow the steps in #1809 to continue working with this image. Hope this helps!
