### ISSUE TITLE
Excessive Token Wastage

### ISSUE THREAD

**Issue by creativewp24** [stackblitz/bolt.new#218]
### Describe the bug

Lets start that I LOVE the platform, but Im disappointed with the amount of token wastage in regenerating the same code over and over again. in the last 24 hours ive used over 10 million tokens? Whilst I know im developing something complex, most of this has been used on issue like:

1. The ai starts randomly generating code in the chat and not the files leaving files half completed and forcing a regeneration.
2. When the ai is told about such issues, it doesnt regenerate the files it messed up, it starts from the start again, causing token wastage.
3. The platform seems to break quite a bit when building and deploying. This again leads to regenerated tokens for no reason.

As i said at the start of this. I really LOVE this platform. Its awesome. Truly! I just cant believe ive been able to use up the code tokens of your highest plan in less than 24 hours.

Please can we discuss this further as I would happily pay more and would like more tokens. Can you assist there?

### Link to the Bolt URL that caused the error

https://merry-chebakia-634b1c.netlify.app/login

### Steps to reproduce

Its in the code generation platform, just look at my chat history and you will see the frustration of chats that go wrong and when they do the excessive token regeneration on files that didnt go wrong.

### Expected behavior

Token usage should not be counted when there are issues with the platform its not fair on a paid account. 
Or, a way to request tokens back for poor generations.
Or, a subscription package that accomodates the excessive token useage so that a developer can use this for more than 1 day

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by MamunHoque** [comment]
I am agree with you also need to add option to get additional token , now I am stack with my code.

**Comment by creativewp24** [comment]
> I am agree with you also need to add option to get additional token , now I am stack with my code.

I just spent 800k tokens on a npm build issue. Yay!

**Comment by codenomnom** [comment]
I also agree. I'm quite happy with the platform, but from my experience, it sometimes regenerates an entire long file (a few hundred lines), just to add tailwind styles for example.

Does the pricing work on updated parts of the file only, or it considers the entire file regeneration? For example if in 100 lines of code it needs to update only one, is the rewriting of the other 99 lines paid for?

I also agree it'll be nice to be able to buy token packages. Right now it can feel you're stuck and all you can do is wait for the next day. Token usage could be better adjusted to the packages you offer.

Good luck!

**Comment by EricSimons** [comment]
Hey all- apologies on the issues here, just FYI we've got fixes in flight for this and will be landing within the next 24-48 hours, more details & timeline here: https://x.com/ericsimons40/status/1843345406576787496

For the time being, for those of y'all that paid, shoot me an email at eric@stackblitz.com with your stackblitz username and/or email and I'll reload your tokens back to 10m until we get this landed 🙇

**Comment by YDX64** [comment]
just a scam 9usd do you really need to take my 9usd and time ?

**Comment by creativewp24** [comment]
> just a scam 9usd do you really need to take my 9usd and time ?

Its no scam. I created an entire working UI for a complex CRM in less than a day. The platforms awesome already, it just needs some fine tuning which Eric and the team are doing already i can see and As the originator of this thread, Eric has already been in touch to address my concerns. Great product, Fast support. Cant ask for more. I wouldnt moan about your 9USD.

**Comment by YDX64** [comment]
my account shown to them already where is my daily 500k tokens nope here isnt any tokens and my purchased tokens already gone also and i cant continue with my project! This is the issue!

**Comment by kc0tlh** [comment]
Update: we have now shipped an update that will make token usage more efficient going forward! As @EricSimons stated above, if you were affected by inefficient token usage and want your tokens reset, please reach out via email to him directly or to me directly and we will get you reset back to full health!

**Comment by kc0tlh** [comment]
>@YDX64 my purchased tokens already gone also and i cant continue with my project! This is the issue!

@YDX64 on my end I can see you used 1,161,407 tokens today and you still have additional tokens remaining. I want to make sure you have a great experience with Bolt.new so I have gone ahead and reset you back to full 10M token health so you should have even more room to experiment this month!

**Comment by plugmakr** [comment]
I though an additional 10mil tokens was going to be $10. I just checked and it's double. Twice the price of the subscription is not cool. 10 million is already not enough for anything serious but this is very frustrating to see. You want twice the price of the subscription to refill tokens?
