### ISSUE TITLE
Persistent error with npm run dev

### ISSUE THREAD

**Issue by sjobergfredrik** [stackblitz/bolt.new#2182]
### Describe the bug

Tried to let LLM fix error without luck. Each fix creates new errors.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tp78zd

### Steps to reproduce

Just used the button Fix problem

### Expected behavior

Solve the error with npm run dev****

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109514974,
  "usedJSHeapSize": 78481954,
  "jsHeapSizeLimit": 4294705152
}
Username = sjobergfredrik
Chat ID = 9ed075304e9d
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
