### ISSUE TITLE
Cant upload images

### ISSUE THREAD

**Issue by edarroch90** [stackblitz/bolt.new#2183]
### Describe the bug

i tried uplaoding images into the website, but they arent rendering. i have tried multiple types (JPG / WEBP etc)
![Screenshot 2024-11-13 165632](https://github.com/user-attachments/assets/e9fabfbe-8336-4dd8-ba75-d0e388fc9933)
![Screenshot 2024-11-13 165625](https://github.com/user-attachments/assets/a834997f-790c-454e-ad9c-ed916153c3c3)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a1tsfb

### Steps to reproduce

upload image in chat, then prompt to use image in website, then look at the preview.

### Expected behavior

i expext the image to render correctly 

### Screen Recording / Screenshot

![Screenshot 2024-11-13 165632](https://github.com/user-attachments/assets/eaa61dbc-144b-4269-a44f-7f0a6c40fe64)
![Screenshot 2024-11-13 165625](https://github.com/user-attachments/assets/dbd7dd2a-20d8-44ce-9f52-6cd70074cc91)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77467648,
  "usedJSHeapSize": 67867796,
  "jsHeapSizeLimit": 4294705152
}
Username = Expandmyfans
Chat ID = 6917eb9f5067
```

**Comment by PacomeLeRouge** [comment]
Sometimes to see the preview you have to open it on slackbitz

**Comment by edarroch90** [comment]
https://papaya-medovik-1ddd1b.netlify.app/#contact  - i tried opening it in a variety of places but none of my pictures are rendering still.

**Comment by PacomeLeRouge** [comment]
What you can do is to open your bolt project on slackbitz and manually drag and drop your image in the src/public folder. Click on the image you should see a preview. You can then create a GitHub repository and host on netlify. I know it's not ideal but it worked for me. They may come with some changes to fix the issue.

**Comment by endocytosis** [comment]
Yes, the above method should work! The team is hard at work adding the ability to upload images. We are tracking this issue here: #1809. We appreciate your feedback as improvements continue to be made!
