### ISSUE TITLE
Token error 

### ISSUE THREAD

**Issue by Okleeqo** [stackblitz/bolt.new#2187]
### Describe the bug

prompt is too long: 205106 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u4r2jw

### Steps to reproduce

<img width="448" alt="Screenshot 2024-11-13 at 12 17 21" src="https://github.com/user-attachments/assets/56b8243d-84fd-400a-9c9d-f5fc1d66f178">

### Expected behavior

It seems i can't write any further instruction

### Screen Recording / Screenshot

<img width="448" alt="Screenshot 2024-11-13 at 12 17 21" src="https://github.com/user-attachments/assets/79fe8f84-ebd0-4010-ad52-8b34a8ca0190">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
