### ISSUE TITLE
L'application ne fonctionne plus comme il faut elle ne crée plus les applications que je lui demande de créer il m'affiche toujours un message d'erreur

### ISSUE THREAD

**Issue by Alex723-bit** [stackblitz/bolt.new#2188]
### Describe the bug

Aucune application n'est possible à créer pourtant j'ai payé pour toute l'année et j'aimerais bien profiter de mon achat s'il vous plaît.
![Screenshot_20241113-111307](https://github.com/user-attachments/assets/77d40f00-deb8-44b9-b502-def60172894e)
![Screenshot_20241113-111303](https://github.com/user-attachments/assets/625757b2-6ccd-45fd-9239-155f979b9d55)
![Screenshot_20241113-111049](https://github.com/user-attachments/assets/9b6a02ea-186b-42f1-beb8-5bf859b93493)
![Screenshot_20241113-111042](https://github.com/user-attachments/assets/e557db24-874c-4b96-bd5f-877fca92284e)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-31g9fs

### Steps to reproduce

Demander simplement à l'application Bolt de créer une application et là elle se plante
![Screenshot_20241113-111307](https://github.com/user-attachments/assets/74b8afff-d5e5-4279-b990-69b03a34948c)
![Screenshot_20241113-111303](https://github.com/user-attachments/assets/b3b2ae35-ba1a-43fd-8f98-85f71dcf5f7e)
![Screenshot_20241113-111049](https://github.com/user-attachments/assets/5f6a8562-46e3-4c90-b39d-3ac7e731ad23)
![Screenshot_20241113-111042](https://github.com/user-attachments/assets/90d1c58d-2255-408b-9f84-1789ae7af9bd)

### Expected behavior

L'application ne fonctionne pas comme prévu. Je m'attends à ce qu'elle soit stable, même pour les tâches les plus basiques. Par exemple, lorsque je tente de créer une application web simple pour convertir des unités, elle plante en cours d'exécution, alors qu'elle démarre correctement. Ces erreurs sont frustrantes et rendent l'application inutilisable.
![Screenshot_20241113-111307](https://github.com/user-attachments/assets/a8095dc3-f2ea-4d8c-a801-d5dcaf485bc2)
![Screenshot_20241113-111303](https://github.com/user-attachments/assets/ddbcd57a-41a7-4da7-b73d-4642b6cb6940)
![Screenshot_20241113-111049](https://github.com/user-attachments/assets/57138932-e374-485c-92b5-e6cda2877718)
![Screenshot_20241113-111042](https://github.com/user-attachments/assets/7129e9a8-6fb3-44b6-88f2-b078a212fa3d)

### Screen Recording / Screenshot

![Screenshot_20241113-111307](https://github.com/user-attachments/assets/477ea69e-2682-4488-9a94-7e284df27fbc)
![Screenshot_20241113-111303](https://github.com/user-attachments/assets/13dabd59-b310-4713-9ce1-6e45df4ec657)
![Screenshot_20241113-111049](https://github.com/user-attachments/assets/4313541e-c297-42fd-8f67-0578f84f9238)
![Screenshot_20241113-111042](https://github.com/user-attachments/assets/8fe6c8f6-d4b2-4f42-9b5f-87329b4d86e8)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76588497,
  "usedJSHeapSize": 47838181,
  "jsHeapSizeLimit": 1009516544
}
Username = Bouesso
Chat ID = 0fef797a2a22
```

### Additional context

J'ai rencontré plusieurs problèmes lors de la création d'applications sur votre plateforme. Malgré une génération apparente des applications (musique, cuisine, langues), les fichiers multimédias associés (audio, vidéo) ne sont pas accessibles. Ce problème se répète systématiquement, rendant les applications inutilisables. Étant donné l'investissement financier que représente cet abonnement, je sollicite votre aide pour résoudre ces problèmes et pouvoir utiliser votre service de manière optimale.

**Comment by Alex723-bit** [comment]
J'attends une répartition !

**Comment by sasa-92** [comment]
Ca me fait pareil.

**Comment by AriPerkkio** [comment]
Hey @Alex723-bit, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
