### ISSUE TITLE
I keep getting forbidden error

### ISSUE THREAD

**Issue by inxgodmode** [stackblitz/bolt.new#219]
### Describe the bug

I keep getting a forbidden error, no matter what i type in the prompt.
![Screenshot 2024-10-08 at 9 06 37 PM](https://github.com/user-attachments/assets/3724bd83-c338-429f-9325-10f5b377b0f2)

### Link to the Bolt URL that caused the error

prompt and submit

### Steps to reproduce

1. Go to homepage
2. Enter any prompt
3. submit

### Expected behavior

it should generate the code.

### Screen Recording / Screenshot

![Screenshot 2024-10-08 at 9 07 55 PM](https://github.com/user-attachments/assets/aac8e495-d374-4709-9376-44883109e915)

### Platform

-Mac OS/Chrome

**Comment by kirjavascript** [comment]
Hey @inxgodmode! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
