### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by TradingWithSL** [stackblitz/bolt.new#2192]
### Describe the bug

This message didn't complete its response.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jjxgqi

### Steps to reproduce

![Screenshot 2024-11-13 165320](https://github.com/user-attachments/assets/f1421266-3c43-4dc0-9db0-33a88251b278)

### Expected behavior

This message didn't complete its response.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75777941,
  "usedJSHeapSize": 70318985,
  "jsHeapSizeLimit": 4294705152
}
Username = TradingWithSL
Chat ID = 2cf73b966e4f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.

**Comment by TradingWithSL** [comment]
How can i solve yhis error
