### ISSUE TITLE
Je ne comprend pas l'Erreur d'application ,quelqu'un peux m'aider svp merci

### ISSUE THREAD

**Issue by sasa-92** [stackblitz/bolt.new#2193]
### Describe the bug

a chaque fois que je demande a bolt quelque chose ca me met NotFoundError : échec de l'exécution de « removeChild » sur « Node » : le nœud à supprimer n'est pas un enfant de ce nœud.
    chez Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:25956)
    à et (https://bolt.new/assets/components-B64jh5hJ.js:24:25667)
    chez Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:26187)
    à et (https://bolt.new/assets/components-B64jh5hJ.js:24:25667)
    chez Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:26404)
    à et (https://bolt.new/assets/components-B64jh5hJ.js:24:25667)
    chez Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:25859)
    à et (https://bolt.new/assets/components-B64jh5hJ.js:24:25667)
    chez Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:26404)
    à et (https://bolt.new/assets/components-B64jh5hJ.js:24:25667)

Et aprés je perd des crédit car ca ne répond pas à la question et tous les anciens messages disparaissent
![Capture d'écran 2024-11-13 122025](https://github.com/user-attachments/assets/e3ee5a81-2ee6-4ade-b366-d416a59a16fc)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sf6ho5

### Steps to reproduce

1) envoyer un message  et sa apparait erreur d'aplication

### Expected behavior

Qu'il n'y est plus se probléme

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 43232219,
  "usedJSHeapSize": 40729683,
  "jsHeapSizeLimit": 4294705152
}
Username = abdz_92
Chat ID = 6537e1030e1b
```

**Comment by AriPerkkio** [comment]
Hey @sasa-92, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
