### ISSUE TITLE
Lost my work

### ISSUE THREAD

**Issue by ivlop** [stackblitz/bolt.new#2196]
### Describe the bug

I closed the tab and when i open again I losted all my promts, my job and my tokens from my recent chat

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-astro-blog

### Steps to reproduce

1.  Create an astro blog
2. Run prompts
3. Close the tab
4. Reopen the tab

### Expected behavior

I should have recovered my work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 117930329,
  "usedJSHeapSize": 88558881,
  "jsHeapSizeLimit": 4294705152
}
Username = ivlop
Chat ID = 7fcf195e261d
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
