### ISSUE TITLE
Unable to delete my account

### ISSUE THREAD

**Issue by mukiralad** [stackblitz/bolt.new#22]
### Describe the bug

I don't find an option to delete my account permanently from your database. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mzgaw4

### Steps to reproduce

I don't find it in the settings or on my profile after selecting the bottom left pane

### Expected behavior

I am expected to offload from your platform if I wish to

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116879464,
  "usedJSHeapSize": 94099648,
  "jsHeapSizeLimit": 2172649472
}
Username = mukiralad
Chat ID = 094d49f7926f
```

### Additional context

Message:
```
I've successfully imported your project. I'm ready to assist you with analyzing and improving your code.
```

**Comment by KwintenP** [comment]
Hi, 

Sorry to hear you want to leave us.

You can do that by going to 
1. stackblitz.com
2. Click on your profile icon in the top right
3. Your settings
4. Select Profile tab
5. Scroll down to 'account deletion'

If there is anything we can do to keep you a StackBlitz user, let us know.
