### ISSUE TITLE
Issues when attaching images in the chat

### ISSUE THREAD

**Issue by mrcego** [stackblitz/bolt.new#220]
### Describe the bug

I'm not allowed to attach images. Immediately I add the file, Bolt shows error when attaching them.

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

Just press attach file icon and select your file. Maybe because need to sign-in?

### Expected behavior

File is uploaded and attached to chat.

### Screen Recording / Screenshot

![Captura de pantalla 2024-10-08 a la(s) 8 10 38 a m](https://github.com/user-attachments/assets/9f0a16e4-057c-468b-81c2-50c6c4fed12a)

https://github.com/user-attachments/assets/90135cd5-3d01-4c00-9819-2abd37a2f862

### Platform

- OS: MacOS / Windows / Android Mobile
- Browser: Microsoft Edge
- Version: Web: 129.0.2792.79, Android: 129.0.2792.65

**Comment by InitPatch** [comment]
as far as I know, Bolt doesn't support vision. Just send it a "can I upload an image here?" prompt, and you'll have your answer :)

**Comment by InitPatch** [comment]
I meant vision capabilities, which means that the model would be able to take in images and answer questions about them

**Comment by InitPatch** [comment]
Actually, that's odd .... now it works ... yesterday I was brainstorming with Bolt (first time use), and asked if i could upload images; and the response was that I wasn't able to do so ¯\_(ツ)_/¯ 
 ... but I just tried and it took the picture and he described it after I asked "what do you see" ... that's interesting ... 
<img width="454" alt="CleanShot 2024-10-08 at 12 24 20@2x" src="https://github.com/user-attachments/assets/d6848f40-3e92-46ae-92bb-ee97e7fb4d1c">

**Comment by samdenty** [comment]
i've just opened a pr to fix this!
