### ISSUE TITLE
unable to fix problems

### ISSUE THREAD

**Issue by Kiks9** [stackblitz/bolt.new#2201]
### Describe the bug

While trying to create a simple tasks mgt app, I've spent 6m tokens and hours of my time trying to get rid of this fetch issue. I am really disappointed by the value provided after hours spent and most of my credit consumed without satisfaction on simple tasks. Kindly let me know how to fix this
<img width="1687" alt="image" src="https://github.com/user-attachments/assets/2eb335d4-5c9b-403a-913e-7ed3e509e8ad">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-leklqz

### Steps to reproduce

just run the draft app as is

### Expected behavior

you will get errors notification

### Screen Recording / Screenshot

<img width="1687" alt="image" src="https://github.com/user-attachments/assets/79a5a4fb-8c9f-4aa5-ab96-7cbb846fda4c">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
