### ISSUE TITLE
Paid for Premium 20 and my project disappeared after payment :cry: 

### ISSUE THREAD

**Issue by tomaytotomato** [stackblitz/bolt.new#2205]
### Describe the bug

Used free trial to make a very nice Vue and Vite starter project

Got prompted that I ran out of tokens and to upgrade.

Upgraded and was redirected to a Stripe payment page.

When I paid and came back my project was gone, tried looking in stackblitz.com but it isn't there either.

Very dissapointing after just giving $20

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vue-irjepv

### Steps to reproduce

1. Use up free tokens
2. Pay for subscription
3. Get redirect to Stripe
4. Pay stripe
5. Redirected back to bolt.new page
6. Project is gone

### Expected behavior

My project I was just working on is still persisted

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = tomaytotomato
Chat ID = e64a4b0c81ce
```

**Comment by endocytosis** [comment]
Hi @tomaytotomato,

Sorry to hear this! Did you check in the following location for your project in StackBlitz? Go to [stackblitz.com](https://stackblitz.com), login (same credentials as Bolt), click Collections on the left-hand side of the page, click Bolt Collection.

**Comment by tomaytotomato** [comment]
Unfortunately nothing is there when trying  Stackblitz (Authentication with Github SSO)

![image](https://github.com/user-attachments/assets/cb48225e-91e9-4bf8-8e1f-2d6439a50cd3)


Just a new project I have now started from scratch with

**Comment by 7054company** [comment]
hey team you need auto save button give to user

**Comment by endocytosis** [comment]
Hi all, 

The team is hard at working making improvements to chat persistence and state management. We are tracking this issue here: #2209.

Appreciate your patience as improvements continue to be made!
