### ISSUE TITLE
Chat history does not show when I login from another computer.

### ISSUE THREAD

**Issue by sirking1991** [stackblitz/bolt.new#2207]
### Describe the bug

Chat history does not show when I login from another computer.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

After you've chatted from one computer, open bolt.new on another computer and login with the same credentials.
It will not show the chat history

### Expected behavior

It should display the chat history.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
