### ISSUE TITLE
Error of png picture uploading and adding to the code

### ISSUE THREAD

**Issue by davson007** [stackblitz/bolt.new#2211]
### Describe the bug

I tried to insert just normal png picture and the bolt started somehow converting to its own png and messed with the code.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uisajf

### Steps to reproduce

Insert the picture and ask to place the picture to some place on the page.

### Expected behavior

I expect normal picture display.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/5170b3ae-f136-4dff-b6c4-9e50d4df74a6)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 74497087,
  "usedJSHeapSize": 68575847,
  "jsHeapSizeLimit": 4294705152
}
Username = davson007
Chat ID = 73ae873b470a
```

### Additional context

Error:
```
You cancelled this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1809
