### ISSUE TITLE
prompt is too long: 201335 tokens > 200000 maximum

### ISSUE THREAD

**Issue by smartguyio** [stackblitz/bolt.new#2217]
### Describe the bug

prompt is too long: 201335 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2k4hfj

### Steps to reproduce

1. Start
2. prompt is too long: 201335 tokens > 200000 maximum
3. prompt is too long: 201335 tokens > 200000 maximum
4. prompt is too long: 201335 tokens > 200000 maximum
5. prompt is too long: 201335 tokens > 200000 maximum
6. prompt is too long: 201335 tokens > 200000 maximum
7. prompt is too long: 201335 tokens > 200000 maximum
8. prompt is too long: 201335 tokens > 200000 maximum
9. prompt is too long: 201335 tokens > 200000 maximum
10. prompt is too long: 201335 tokens > 200000 maximum
11. prompt is too long: 201335 tokens > 200000 maximum
12. prompt is too long: 201335 tokens > 200000 maximum

### Expected behavior

To work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 95852930,
  "usedJSHeapSize": 90601890,
  "jsHeapSizeLimit": 4294705152
}
Username = smartguyio
Chat ID = 05529ff094a5
```

### Additional context

prompt is too long: 201335 tokens > 200000 maximum
prompt is too long: 201335 tokens > 200000 maximum
prompt is too long: 201335 tokens > 200000 maximum
prompt is too long: 201335 tokens > 200000 maximum
prompt is too long: 201335 tokens > 200000 maximum
prompt is too long: 201335 tokens > 200000 maximum
prompt is too long: 201335 tokens > 200000 maximum

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
