### ISSUE TITLE
Google OAuth Error 

### ISSUE THREAD

**Issue by revup64** [stackblitz/bolt.new#2219]
### Describe the bug

I'm trying to connect the app to a Google Merchant Centre to pull in product information, however I'm having issues with the Google OAuth. Here is the error I get: 

"[GSI_LOGGER]: Failed to open popup window on url: https://accounts.google.com/o/oauth2/v2/auth?gsiwebsdk=3&client_id=801666740916-rconbghu7jnbshsq54g44ietejbum618.apps.googleusercontent.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontent&redirect_uri=storagerelay%3A%2F%2Fhttps%2Fzp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--f565b097.local-credentialless.webcontainer-api.io%3Fid%3Dauth397621&prompt=select_account&response_type=token&include_granted_scopes=true&enable_granular_consent=true. Maybe blocked by the browser?"
   at _.C (https://accounts.google.com/gsi/client:71:273)
   at _.Gj (https://accounts.google.com/gsi/client:240:158)
   at Us.requestAccessToken (https://accounts.google.com/gsi/client:358:215)
   at /node_modules/.vite/deps/@react-oauth_google.js?v=968284e8:165:77
   at handleLogin (/src/components/GoogleAuthButton.tsx:177:7)
   at HTMLUnknownElement.callCallback2 (/node_modules/.vite/deps/chunk-M324AGAM.js?v=968284e8:3672:22)
   at Object.invokeGuardedCallbackDev (/node_modules/.vite/deps/chunk-M324AGAM.js?v=968284e8:3697:24)
   at invokeGuardedCallback (/node_modules/.vite/deps/chunk-M324AGAM.js?v=968284e8:37

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-19ryjb

### Steps to reproduce

Click connect and login using my email but straight away I get this error, 

### Expected behavior

Click connect and login using my email, then to be able to select which Merchant Center account I want to use. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120036276,
  "usedJSHeapSize": 111503424,
  "jsHeapSizeLimit": 2160066560
}
Username = Caldev
Chat ID = 805effa10b7c
```

**Comment by endocytosis** [comment]
Unfortunately we don't have the resources to provide one-on-one engineering support for individual projects. At times, there are programming challenges that are too complex for the AI to solve an manual intervention is required. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on using Bolt most effectively while maximizing token efficiency. 

The [Google Authorization Docs](https://developers.google.com/identity/authorization) may also be helpful.
