### ISSUE TITLE
Amazing tool, HORRIBLE release

### ISSUE THREAD

**Issue by CurtisCowgill** [stackblitz/bolt.new#222]
### Describe the bug

As many have already reported, the fact that the chats aren't saved and that there was no warning to new users that chats would not be saved is a significant issue that makes bolt.new essentially unusable, except for the smallest of projects. I, like many, have spent hours working on a project only to discover that it is NOT saved. Selling a product with such a glaringly obvious bug isn't a good look.

I really like using the app, but until this issue is resolved, I wouldn't recommend anyone use it unless they are fully aware their work will NOT be saved.

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

sign in, start a chat, close the browser, open it, go to bolt.new, be dissapointed

### Expected behavior

I expect a product I'm paying for to save my work!

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
Hey! Chat is not persisted at the moment.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/39. Feel free to subscribe to that issue if you want to be informed when this will be added!
