### ISSUE TITLE
Histories for the chat are not saving

### ISSUE THREAD

**Issue by AdityaBadve** [stackblitz/bolt.new#2221]
### Describe the bug

I keep using the bolt chat, but everytime I leave and come back to an old chat, none of the original code and history of the chat is saved. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6ln8fn

### Steps to reproduce

1. Create a chat
2. Leave chat
3. Come back

### Expected behavior

History is saved

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 382761087,
  "usedJSHeapSize": 364233979,
  "jsHeapSizeLimit": 4294705152
}
Username = AdityaBadve
Chat ID = c79f08d2143f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
