### ISSUE TITLE
System is having to many issues

### ISSUE THREAD

**Issue by globalvoice** [stackblitz/bolt.new#2223]
### Describe the bug

Error Fetching User Role

Review the function responsible for fetching the user role. Ensure that the API or function call is correctly authenticated and has the necessary permissions to retrieve user roles.
If {} is the response, check for potential authorization issues or incorrect endpoint configurations.
Verify that the request includes necessary headers or tokens if required by the API.
Syntax Error: Unexpected Token 'b', "business" is not valid JSON

Locate where the "business" object or string is being parsed or stringified. This error suggests that there may be improperly formatted JSON in your code.
Check that any data being sent as JSON is correctly structured. Ensure double quotes around keys and values (e.g., {"business": "value"} instead of {business: 'value'}).
Use JSON.stringify() when converting JavaScript objects to JSON format before sending them in requests, and use JSON.parse() when receiving JSON responses.
Error Fetching Bookings: Firebase Error (Resource Exhausted)

The “resource-exhausted” error often indicates that you’ve reached a quota limit in Firebase. This could be due to excessive reads/writes or reaching a storage limit.
Check Firebase console for usage metrics to identify if quotas have been exceeded.
If limits are reached, consider optimizing the data reads/writes in your code, such as implementing caching mechanisms, limiting query scope, or upgrading your Firebase plan if necessary.
General Debugging Tips

Implement try-catch blocks around API calls and data-fetching functions to catch and log more detailed error messages.
Enable Firebase logging to monitor and troubleshoot data access patterns. This will help pinpoint areas that might be triggering the quota exhaustion.
Test each fix individually and verify it resolves the specific error before moving on to the next.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-evy7x4

### Steps to reproduce

i havent been able to deploy the page that the system fixed earlier 
the same issues come back all the time and is eating the tokens 

### Expected behavior

is shoult allow me to create users, login, pay with Paypal or stripe and access the customer portal 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/a56de3d0-39c0-4c1f-bbfa-66cc020b1c2a)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 236064397,
  "usedJSHeapSize": 226817465,
  "jsHeapSizeLimit": 2160066560
}
Username = globalvoice
Chat ID = c0a2f840d57f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
