### ISSUE TITLE
navigation still does not work

### ISSUE THREAD

**Issue by krissistrunk** [stackblitz/bolt.new#2226]
### Describe the bug

I have tried to fix the navigation many time and I am burning up tokens doing it.  It will not work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-juaw3e

### Steps to reproduce

try to login with demo info.  (user: demo) (pass: password123)

### Expected behavior

it should go to the dashboard screen but it gets stuck

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82012625,
  "usedJSHeapSize": 73057461,
  "jsHeapSizeLimit": 2160066560
}
Username = krissistrunk
Chat ID = a0891879a782
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
