### ISSUE TITLE
Images Not Displaying on Bolt Webpage Despite Correct Directory Placement

### ISSUE THREAD

**Issue by MDSoftware-DE** [stackblitz/bolt.new#2227]
### Describe the bug

've encountered an issue where images, specifically a logo (md-logo.svg) and a personal photo (michael-dudenko.jpg), do not display on my webpage built using Bolt. I followed the given instructions to place these files in the /public/images/ directory and ensured the component paths are correct, as outlined in the documentation, but they still don’t render on the site.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-j5urnm

### Steps to reproduce

Save the logo as md-logo.svg in the /public/images directory.
Save the personal photo as michael-dudenko.jpg in the /public/images directory.
Confirm that the images are located at:
/public/images/md-logo.svg
/public/images/michael-dudenko.jpg
Open the webpage and inspect the areas where the images should appear.

### Expected behavior

Expected Behavior:
The logo and photo should be displayed on the webpage as specified in the components. The components are set up to use these exact image paths, and the images should load automatically via Vite.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57640830,
  "usedJSHeapSize": 54188994,
  "jsHeapSizeLimit": 4294705152
}
Username = MDSoftware
Chat ID = e987239e9867
```

### Additional context

Actual Behavior:
The images do not display on the webpage. I have attempted multiple solutions, including rechecking the directory paths, reviewing component settings, and trying alternate paths, but without success. Despite following instructions closely, the images remain invisible on the site.

Troubleshooting Steps Taken:

Verified that md-logo.svg and michael-dudenko.jpg are indeed in the /public/images/ directory.
Checked Vite's configuration to ensure it is serving static files correctly.
Verified image paths in component code.
Cleared browser cache and reloaded the page.
Restarted the development server multiple times.
Environment:

Framework: Bolt
File Structure: Standard Bolt project structure
Image File Paths: /public/images/md-logo.svg, /public/images/michael-dudenko.jpg
Additional Context:
This issue has been persistent, despite multiple attempts to resolve it. It's currently blocking the display of important visual elements on my webpage, and assistance would be appreciated to identify any overlooked configuration or caching steps.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1809
