### ISSUE TITLE
Simple Angular site generates blank preview

### ISSUE THREAD

**Issue by scotthankinsonToptal** [stackblitz/bolt.new#2229]
### Describe the bug

My prompt was:
Build an Angular frontend Admin site with basic login, accessing resources from a SQLServer backend.

It generated code, and then displayed a Preview that was a blank white screen. I told it so, twice, and it regenerated a blank Preview each time.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xfc4j3

### Steps to reproduce

1. Prompt: 
Build an Angular frontend Admin site with basic login, accessing resources from a SQLServer backend.
2. Observe error condition

### Expected behavior

1. Prompt:
Build an Angular frontend Admin site with basic login, accessing resources from a SQLServer backend.
2. Observe login screen

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66610716,
  "usedJSHeapSize": 60672340,
  "jsHeapSizeLimit": 4294705152
}
Username = scotthankinsonToptal
Chat ID = e81185a8e0f4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
