### ISSUE TITLE
Forbidden?

### ISSUE THREAD

**Issue by jirojirocirociro** [stackblitz/bolt.new#223]
### Describe the bug

Why is it forbidden? Im paid user. Thanks 

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

1. Pasting my desciption 
2. Forbidden error

### Expected behavior

I expected it to work as usual

### Screen Recording / Screenshot

<img width="1440" alt="Tangkapan Skrin 2024-10-08 pada 10 41 50 PTG" src="https://github.com/user-attachments/assets/0399c556-52c1-4ca5-a556-bc3a58ff35f1">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
Hey @jirojirocirociro ! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
