### ISSUE TITLE
Stuck with not fixing the overlay issue

### ISSUE THREAD

**Issue by cryptokoh** [stackblitz/bolt.new#2231]
### Describe the bug

The right column is still overlaying a popup
![image](https://github.com/user-attachments/assets/e5bd471c-a0bb-44d6-9824-bfd612530ef8)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-spwa5l

### Steps to reproduce

Ask it to fix and ask it to fix again. I feel I'm wasting tokens and should find a better prompt

### Expected behavior

fix the  overlay issue on the website

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58635175,
  "usedJSHeapSize": 56084031,
  "jsHeapSizeLimit": 4294705152
}
Username = hand
Chat ID = 05679937a64d
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!
