### ISSUE TITLE
Unable to deploy Site

### ISSUE THREAD

**Issue by hirisk93** [stackblitz/bolt.new#2239]
### Describe the bug

I try to deploy and i get this error : I'll help deploy the application to Netlify. First, let me fix the error in the code and then proceed with the deployment.

Fix errors and deploy to Netlify

src/App.tsx
npm run build
netlify
Let me check the deployment status and provide you with the live URL once it's ready. The application will be deployed with all the latest features including:

Modern dark theme with teal/blue accents
Animated LeadFlow logo
Full lead management functionality
Archive system
Drag-and-drop lead status updates
Responsive design
Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a1kf2x

### Steps to reproduce

Click on deploy

### Expected behavior

The app should deploy and have a link to access it

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 107800423,
  "usedJSHeapSize": 93763391,
  "jsHeapSizeLimit": 4294705152
}
Username = hirisk93
Chat ID = 9b28a56ac3e3
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019, along with some possible workarounds.
