### ISSUE TITLE
History keeps getting deleted??

### ISSUE THREAD

**Issue by gocygo** [stackblitz/bolt.new#2244]
### Describe the bug

The history will not stay, it's there but as soon as I log in the next day it's all gone.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Here are the steps to reproduce the bug:

1. Use bolt.new.
2. Log in the next day.
3. Your browsing history will be gone, which may indicate the bug.

### Expected behavior

The expected behavior is that the chat history should be retained even after logging in the next day. The bug occurs when the chat history is unexpectedly cleared.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). 

The team has recently released updates to chat persistence so this should be resolved soon!
