### ISSUE TITLE
my chats'/software disappeardd - I have worked a=on 2 and both are gone - 1 was almost ready for deployment

### ISSUE THREAD

**Issue by robingithub-ai** [stackblitz/bolt.new#2247]
### Describe the bug

Please can someone contact me? I have been working hard and my chats / software disappeared - thank you

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

my chats/software is gone!!!!! please help

### Expected behavior

Please contact me to restore my work - it started looping last night and downoaded a zip without me asking and now its gone
<img width="1728" alt="Screenshot 2024-11-13 at 12 31 51 PM" src="https://github.com/user-attachments/assets/a7c0175d-aca6-4aac-b6da-7ef9fa96d083">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). 

The team has recently released updates regarding chat persistence so this should be resolved soon! We appreciate your patience as improvements are made!
