### ISSUE TITLE
You have hit the rate limit. Please-upgrade link doesn't work

### ISSUE THREAD

**Issue by Seanmclem** [stackblitz/bolt.new#2248]
### Describe the bug

it has a link when you hit the rate limit in the response. you can click "upgrade". It did nothing for me. I am now less likely to upgrade

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-w78vx7

### Steps to reproduce

hit the rate limit, try and click the link. doesn't work... It's because it's just an anchor with no href.

### Expected behavior

it should be clickable.

### Screen Recording / Screenshot

<img width="1123" alt="Screenshot 2024-11-13 at 3 46 12 PM" src="https://github.com/user-attachments/assets/d7a59ee5-6095-4bba-a1c7-e510e1a34d5a">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 63736699,
  "usedJSHeapSize": 59994279,
  "jsHeapSizeLimit": 4294705152
}
Username = Seanmclem
Chat ID = 36c776a99be3
```

### Additional context

Error:
```
You have hit the rate limit. Please <a class="__boltUpgradePlan__">Upgrade</a> to keep chatting, or you can continue coding for free in the editor.
```

**Comment by endocytosis** [comment]
Hi @Seanmclem, 

Appreciate the feedback! I have relayed this to the team and they are investigating - will follow-up here.

**Comment by kc0tlh** [comment]
@Seanmclem this has been resolved! Thanks for the report 🙏🏻
