### ISSUE TITLE
Project Missing from History

### ISSUE THREAD

**Issue by cbalaur91** [stackblitz/bolt.new#2251]
### Describe the bug

I have been working on an app for couple of hours yesterday 11/12/2024 and I am not sure if it got deleted or I just don`t have visibility to that, but I feel like I have lost all that time and tokens. App is called Closing Process Manager. Can you please help me get that back into bolt.new so I can continue working on it? I am not sure if this is the right url but I will provide it. I am not sure if I have been improving on this one or build a new one from scratch but there are only 2 projects in chat history

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nenqvp

### Steps to reproduce

-

### Expected behavior

-

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by cbalaur91** [comment]
It is not just the chat persistence, is the project that I have been working on as well. So If I can not find my project in the collections, that means I have lost all the progress? It seems that it did not saved couple of hours of work. Please confirm

**Comment by endocytosis** [comment]
Hi @cbalaur91, 

Here is something else to try. If you have the chat associated with your project open:

1) Hover over the left-hand side of the page in Bolt to bring up the menu system.
2) Click Settings. 
3) Click Backups.
4) Find a recent Backup, open, and click Create fork to open the project at that state.

**Comment by cbalaur91** [comment]
I was able to find it under Backups. Thank you so much!
