### ISSUE TITLE
Impossible to work with replicate api because of CORS issue in the local preview

### ISSUE THREAD

**Issue by BenLMT** [stackblitz/bolt.new#2254]
### Describe the bug

Impossible to work with replicate api because of CORS issue in the local preview, is it a bug or is it me that are dumb guys :'(

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zcect1

### Steps to reproduce

Create a proxy server to avoid the CORS problem

### Expected behavior

Successfuly send the POST & GET 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55914205,
  "usedJSHeapSize": 49629049,
  "jsHeapSizeLimit": 2160066560
}
Username = Crackito
Chat ID = ebd59b3b918e
```

**Comment by endocytosis** [comment]
Hi @BenLMT, 

Appreciate the feedback! If you are willing, could you set the visibility of your Bolt project to secret (accessible by URL) so we can take a look?
