### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by harofastlife** [stackblitz/bolt.new#2258]
### Describe the bug

I created an admin panel backend for a website using firebase.  The admin panel only works in bolt.new.  when it is deployed it doesn't load. 

When I tell bolt.new that it isn't working it tries to fix it then crashed with ther error attached

### Link to the Bolt URL that caused the error

bolt.new chat

### Steps to reproduce

asked bolt.new "The admin panel is not loading on deployed site"

### Expected behavior

expected it to fix the problem.
![bolt_new___sb1-rkqumc](https://github.com/user-attachments/assets/51132767-b1cf-471d-86b7-68391dd75460)

### Screen Recording / Screenshot

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
![bolt_new___sb1-rkqumc](https://github.com/user-attachments/assets/c4fa0a28-fede-483b-9342-f3a78b4530ff)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lkorba** [comment]
same thing happened to at least me twice already, losing some of my progress and tokens

**Comment by lkorba** [comment]
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Le (https://bolt.new/assets/components-B64jh5hJ.js:22:17522)
    at Object.ec [as useCallback] (https://bolt.new/assets/components-B64jh5hJ.js:22:21045)
    at O.useCallback (https://bolt.new/assets/index-fw5NnR3n.js:9:5633)
    at I (https://bolt.new/assets/stripIndent-YObSZ0C4.js:1:206)
    at OP (https://bolt.new/assets/_index-BdrECYhd.js:66:4112)
    at https://bolt.new/assets/_index-BdrECYhd.js:66:4053
    at Array.flatMap (<anonymous>)
    at https://bolt.new/assets/_index-BdrECYhd.js:66:4007
    at Vo (https://bolt.new/assets/components-B64jh5hJ.js:22:16948)
    at Ji (https://bolt.new/assets/components-B64jh5hJ.js:24:3134)

these are happening very often, making my tokens burn every time

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2348).

**Comment by xerudro** [comment]
Yes, but how about our burned tokens we use until the fix really works ? I lost almost 5M tokens building a computer repair platform... who will give me those credits back, to continue to the latest save ... ? This platform of yours is a BIG SCAM.
