### ISSUE TITLE
keeps getting "Forbidden"

### ISSUE THREAD

**Issue by paulaboratory** [stackblitz/bolt.new#228]
### Describe the bug

keeps getting "Forbidden"

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-astro-blog-meufge

### Steps to reproduce

I get "Forbidden" whenever I send message in chat

### Expected behavior

Forbidden

### Screen Recording / Screenshot

<img width="409" alt="image" src="https://github.com/user-attachments/assets/2535ac23-2253-4c21-bade-080472c16eb1">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100992807,
  "usedJSHeapSize": 88074567,
  "jsHeapSizeLimit": 2172649472
}
Username = paulaboratory
Chat ID = 9f593b175a4c
```

**Comment by kirjavascript** [comment]
Hey @[paulaboratory](https://github.com/paulaboratory) ! Sorry for this issue, we're actively investigating this to find a resolution soon.

We're tracking this issue in https://github.com/stackblitz/bolt.new/issues/77. We will let you know when we have a good solution in place.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
