### ISSUE TITLE
prompt is too long: 201928 tokens > 200000 maximum

### ISSUE THREAD

**Issue by jerekel87** [stackblitz/bolt.new#2282]
### Describe the bug

prompt is too long: 201928 tokens > 200000 maximum

I can't even type to this thing and this is all I keep getting. It's getting out of hand now and I cannot even use this app anymore as this is all I keep receiving everytime I ask it to do so

<img width="608" alt="Screenshot 2024-11-14 at 4 12 33 PM" src="https://github.com/user-attachments/assets/3f19dc1d-bfb3-4cc2-b809-4466dec63ee2">

### Steps to reproduce

Go to the project, type something in and receive error. It's really bad today I can't do anything anymore

### Expected behavior

I expect the Ai to build the app when I give it a prompt, it's not a difficult prompt either.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I don't know if this is an overload on the server that's why this error keeps happening but it's really bad today

**Comment by jerekel87** [comment]
When I refresh the page, I enter the text prompt in again and I still get this error.

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
