### ISSUE TITLE
the preview is empthy

### ISSUE THREAD

**Issue by Hidayat0507** [stackblitz/bolt.new#2286]
### Describe the bug

using next js shadcn. the preview is empty. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-i2ejdb

### Steps to reproduce

please fix the preview problem. i already paid for it. 

### Expected behavior

please fix the preview problem. 

### Platform

```
Browser name = Safari
Full version = 18.2
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15
performance.memory = undefined
Username = Hidayat0507
Chat ID = 85e6cfd85f80
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
