### ISSUE TITLE
Page disappears into a React error log

### ISSUE THREAD

**Issue by AuroMun** [stackblitz/bolt.new#2304]
### Describe the bug

During iterations of a project, bolt randomly goes into an error state, as seen in the screenshot attached. This leads to a waste of tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ihkwdd

### Steps to reproduce

No exact reproduction, this happens intermittently. Working on a React app where I suggest successive modifications.

### Expected behavior

No disappearing into an error page

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ec56086b-9a7a-47de-bba4-f177ae171987)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 130.0

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this issue [here](https://github.com/stackblitz/bolt.new/issues/2348) and engineering recently released a fix so it should be resolved if you refresh the page.
