### ISSUE TITLE
Black and red screen bug

### ISSUE THREAD

**Issue by InfoRubix** [stackblitz/bolt.new#2305]
### Describe the bug

When bolt ai want to fix the bug, it jumps into red black screen

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-l3i86k

### Steps to reproduce

try to fix the deploy problem, changing to static and then it crash

### Expected behavior

I expected it to fix the problem and be able to deploy

### Screen Recording / Screenshot

![Screenshot 2024-11-14 175556](https://github.com/user-attachments/assets/9daa4f56-7e9a-4794-b02b-52eb9a47f84e)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47566354,
  "usedJSHeapSize": 44553546,
  "jsHeapSizeLimit": 4294705152
}
Username = InfoRubix
Chat ID = 6fd4cee24bea
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this error here: #2348.
