### ISSUE TITLE
Completely failed making a portfolio website

### ISSUE THREAD

**Issue by InitPatch** [stackblitz/bolt.new#231]
### Describe the bug

It's not really a bug, but more like a global functionality issue, as it just failed on me. 
I wanted to test Bolt as I heard about it recently. I've asked to build a website, but after it did write some code files, all I did was to click on "fix errors" until I couldn't anymore because it spent all the 150k tokens doing so...  At this point, although I'm still curious to see it working and see what it would suggest to me, so I can decide whether or not I jump deep with it and redo my current website using that tech, I don't know if I can trust it after what happened.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cka4nd

### Steps to reproduce

So I started chatting and asked it to build a portfolio website for a video game music composer, which would need music and videos players, a blog , a news section, and a bio/credits.
It started creating the code files (see first screenshot below), and I guess tried to run it, but the preview wouldn't show nothing but a white page.
After a few "fix problem", the page changed to dark gray, then with the Next.js logo page
a few "fix problem" later, it ended up with:
Build Error
Failed to compile
Conflicting app and page file was found,
please remove the conflicting files to
continue:
"src/pages/index.tsx"-"src/app/page.tsx"

There was still lots of errors, but it spent the whole 150k tokens I was allowed to use in like 10 minutes or, trying to fix them, so I couldn't chat/fix anymore.
Today I went back to it to copy/paste the full chat so I can share it here, but I can't see it, only the 2 last messages, which was related to the errors. Which means, even though I can see the chat recorded in "My Chats" in the main menu, there's no history of it actually. When I click on the chat, it just show what's in the second screenshot below, but nothing from our last conversation.

### Expected behavior

Expected behavior? Well, let's say I was expecting it to work, at least enough so I can test it out properly, give it feedback after a first iteration, etc... and not spending 150k tokens in 10 minutes for nothing :) 

### Screen Recording / Screenshot

![CleanShot 2024-10-08 at 10 14 47@2x](https://github.com/user-attachments/assets/7b58f96c-cc7e-4879-b967-48cbb660080b)
<img width="513" alt="CleanShot 2024-10-08 at 10 26 15@2x" src="https://github.com/user-attachments/assets/69a534a9-e6c7-485e-b388-8092df2bfa9f">

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61481732,
  "usedJSHeapSize": 60157556,
  "jsHeapSizeLimit": 4294705152
}
Username = InitPatch
Chat ID = 078b902dd6e0
```

**Comment by superresistant** [comment]
When you get the same error 2 times, do not retry. Ask google/perplexity/claude/chatgpt about the specifics of that error and how you should prompt differently back into bolt.new

I fix all my errors like this. Works every time.

**Comment by InitPatch** [comment]
Ok, I'll give it another chance. Deleting the file from Stackblitz, and reload the Bolt page seamed to at least unlock it from that loop and it finally managed to run it. I'm not impressed by the result at first glance, none of links are working, it looks terrible, etc... even though my prompt was relatively detailled; I guess I'll play a bit with it, see if it can improve; my only problem is that it doesn't remember (or even display) the conversation in the chat the next time I come back to it. So I can't even see what my original prompt was

**Comment by superresistant** [comment]
Sure, I consider that there are is no history at all. I always pre-prompt and discuss everything with claude so claude will have some of the history. 
What I found is that long detailed prompt isn't always better. If I'm stuck, I sometimes restart from scratch with totally different prompt. In some case it works.

**Comment by Nemikolh** [comment]
Hey @InitPatch, thanks a lot for sharing your experience, this is truly insightful :heart_hands: 

I think an aspect to keep in mind is that Bolt makes mistakes and it does not always succeed at fixing the issues it created. I often find that it works best when I investigate a bit to provide some context before asking it to fix the issue.

Our auto-fix tries to do that by providing the errors as context to bolt but sometimes the root cause is a bit more complex.

We want to make that easier and smoother so we will add smarter and easier solution in the future that don't impact your token usage. Stay tuned :eyes: 

Regarding the chat history we're tracking this in #39. You can track that issue to be informed when it lands as we'll post an update there.

**Comment by InitPatch** [comment]
Thank you @Nemikolh !
Yeah, after that fix was finally done, I started over, and it did something, but oh my god, that was ugly and clearly not what I asked for :) ... So, I'll stay tuned and watch the chat history bug, but for now, I'm not gonna embrace this new tech until it gets a bit better and will stay with my Wix website for now ;) 
Cheers!

**Comment by Nemikolh** [comment]
All good! :raised_hands: 

And thanks again for spending the time to share your experience, having the perspective of our users is extremely useful to help us shape bolt into something truly delightful! It has some pain points but we've only just started :smiley:
