### ISSUE TITLE
deployement not working with 

### ISSUE THREAD

**Issue by waelausy** [stackblitz/bolt.new#2317]
### Describe the bug

i tried deploying this app but takes time but never works

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rkzipv

### Steps to reproduce

deploy to netlify blocked

### Expected behavior

deployement

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58133357,
  "usedJSHeapSize": 54419149,
  "jsHeapSizeLimit": 4294705152
}
Username = waelausy
Chat ID = 021791b497df
```

### Additional context

Error:
```
You cancelled this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! You can manually deploy to Netlify as follows: 

1. Run the build command (usually ”npm run build”)
2. Download the project (click the Download button in the upper-right corner)
3.  Follow the Netlify manual deploy instructions [[here](https://www.youtube.com/watch?v=etZ9HSUoTPU)](https://www.youtube.com/watch?v=etZ9HSUoTPU)
