### ISSUE TITLE
github import is broken

### ISSUE THREAD

**Issue by mrezzzy** [stackblitz/bolt.new#2320]
### Describe the bug

I can't import the project from github, I get an error "Cannot destructure property 'appFiles' of 'project' as it is null."

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/mrezzzy/api-1

### Steps to reproduce

just try importing the project

### Expected behavior

I expected that as before, my project would be imported and I would be able to work on it

### Screen Recording / Screenshot

![bolt_problem_git](https://github.com/user-attachments/assets/773e8a8b-de5a-41c0-87a1-6578fbad7dbe)

### Platform

- OS: Windows
- Browser: Chrome
- Version: [ 130.0.6723.117]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1812.

**Comment by mrezzzy** [comment]
>Appreciate the feedback! We are aware of this issue and are tracking it here #1812.

Can you tell me how else I can continue working on the project? It is important to return the product to its original state. It was created inside Bolt, but it stopped working. I have already spent $30 million tokens on this project and I don't want to start from scratch again. Thank you for your help.
