### ISSUE TITLE
Error Failed to resolve import "./pages/Create" from "src/App.tsx".

### ISSUE THREAD

**Issue by lucasmolusco** [stackblitz/bolt.new#2326]
### Describe the bug

[plugin:vite:import-analysis] Failed to resolve import "./pages/Create" from "src/App.tsx". Does the file exist?

I tried to create a app with that prompt and it stoped in the error above.

The prompt was:

Create a system for proposing, reviewing, and signing popular initiatives (publicly-suggested legislation drafts). In this system, a user can suggest an idea for a popular initiative law (PIL), which is then transformed into a preliminary draft by the AI. The AI also suggests a tentative title for the PIL based on the user’s initial idea, which the user can edit as needed.

Once a draft is generated, it proceeds to a three-stage review by AI "commissions" that provide a score and critical feedback on specific criteria:

Constitutional Compatibility: Ensures the PIL aligns with the constitution.
Budget Compatibility: Verifies if the PIL fits within the designated budgetary constraints.
Sector-Specific Legal Compatibility: Checks for compliance with existing laws related to the PIL’s sector.
Each commission provides a score and constructive critique for the PIL.

After receiving feedback, the user can choose to publish the PIL in a public area for digital signatures. The public section includes filters for users to view PILs by thematic category and geographic region. Users interested in supporting a PIL can sign it digitally. The system should provide an option for each PIL to be shared via a unique link on WhatsApp to encourage sign-ups.

If a PIL gathers enough signatures for the target municipality, it becomes eligible for legislative consideration in the local government houses.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-p5tkj7

### Steps to reproduce

Go to: Initial page, insert the prompt  and the error was [plugin:vite:import-analysis] Failed to resolve import "./pages/Create" from "src/App.tsx". Does the file exist?

### Expected behavior

Create the system without error
![Captura de Tela (57)](https://github.com/user-attachments/assets/ddf32d56-327c-4caf-8e7d-b044ab43079d)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45753628,
  "usedJSHeapSize": 42934584,
  "jsHeapSizeLimit": 2160066560
}
Username = lucasmolusco
Chat ID = 8aff97bff4a8
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This page [here](https://github.com/stackblitz/bolt.new/issues/2310) has as number of insights on continuing to develop your application. Hope this helps!
