### ISSUE TITLE
problems making landing pages

### ISSUE THREAD

**Issue by aaronseal** [stackblitz/bolt.new#2332]
### Describe the bug

It's not really a bug, it's just that I got really excited paying my $20 to use your website, and whenever I want to make a landing page of my affiliate marketing stuff, it keeps giving me a message of "unethical type websites" and that's not the actual message,I was wondering if there is like a god mode version of this of ChatGPT, but I can go past that and just make a simple landing page. The Landing page of mine leads to an affiliate marketing offer for people who are looking for a.  I was wondering if there is like a god mode version of this of ChatGPT, but I can go past that and just make a simple winding page. Landing page of mine leads to an affiliate marketing offer for people who are looking for quick loans. I also have other offers for making money online as well. Seems to be I might have wasted my $20 for nothing. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-icom5o

### Steps to reproduce

Can you build me a landing page Wordpress website about loans that are easy to get in case you need cash for an emergency. The website needs to be a wordpress based website that solves the problem of people getting loans to help pay for bills

### Expected behavior

create a landing page with wordpress

### Screen Recording / Screenshot

![Screenshot 2024-11-14 101541](https://github.com/user-attachments/assets/de0cc631-16df-4fc4-8427-1558e24c9153)
![Screenshot 2024-11-14 101541](https://github.com/user-attachments/assets/421ebd19-9bbf-4a37-8d37-e31f8337516e)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! Bolt is powered by [WebContainers](https://webcontainers.io/) and as such only supports languages that are supported by WebContainers. If you need to develop a WordPress project, another platform may be best for your needs at this time.

**Comment by aaronseal** [comment]
So can I get a refund cause obviously this is something that I need. I just
bought it today already canceled it.

**Comment by endocytosis** [comment]
Refund requests are handled through hello@stackblitz.com.
