### ISSUE TITLE
Error Loop

### ISSUE THREAD

**Issue by MD-TopGun** [stackblitz/bolt.new#2334]
### Describe the bug

I am in a loop with error in migration code. 
Although I have tested myself that I can connect via the command line but the system is unable to update code to handle it. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zugqsf

### Steps to reproduce

Just try to run it. 

### Expected behavior

connect to database and create db and tables. 

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = MD-TopGun
Chat ID = 1dab963aa4b4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times the LLM is unable to resolve programming challenges and further steps are required, more of which you can read about [here](https://github.com/stackblitz/bolt.new/issues/2310).
