### ISSUE TITLE
app is not using the image i've uploaded for the logo

### ISSUE THREAD

**Issue by jjfrey** [stackblitz/bolt.new#2336]
### Describe the bug

I've uploaded my logo on two different occasions and asked the app to use it in the design but the app seems to be using a logo that the app generated. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-j3ulku

### Steps to reproduce

go to prompt, click on 'upload file', choose file and enter 'Use this attached logo in place of the existing logo'

### Expected behavior

The logo that is displayed should be the same as the file that I'd uploaded

### Screen Recording / Screenshot

![Screenshot 2024-11-14 at 11 31 17 AM](https://github.com/user-attachments/assets/4ab2f4ef-2418-40d3-a75d-1de6a67df9c5)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85758594,
  "usedJSHeapSize": 79886246,
  "jsHeapSizeLimit": 4294705152
}
Username = jjfrey
Chat ID = f87f9713512a
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1809
