### ISSUE TITLE
 Forbidden

### ISSUE THREAD

**Issue by YashSodaye** [stackblitz/bolt.new#234]
### Describe the bug

Forbidden

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ubudqr

### Steps to reproduce

while giving input it giving error

### Expected behavior

Forbidden error 

### Screen Recording / Screenshot

![error](https://github.com/user-attachments/assets/adb0b874-a6cd-489c-998d-3d626ed12764)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 39855348,
  "usedJSHeapSize": 36986292,
  "jsHeapSizeLimit": 4294705152
}
Username = YashSodaye
Chat ID = 39926bc69020
```

**Comment by samdenty** [comment]
see https://github.com/stackblitz/bolt.new/issues/77

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
