### ISSUE TITLE
Failed to save project. You can download your project by clicking this notification

### ISSUE THREAD

**Issue by kcedx111** [stackblitz/bolt.new#2340]
### Describe the bug

When using bolt.new, some times, it just can't save the files. 

```
Request URL:
https://stackblitz.com/api/projects/bolt-nextjs-XXXX
Request Method:
PATCH
Status Code:
413 Payload Too Large
Referrer Policy:
strict-origin-when-cross-origin
```

And keep popping up the following notifications.
```
Failed to save project. You can download your project by clicking this notification
```

Please fix it. Thanks.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-XXXXX

### Steps to reproduce

1. Enter prompt
2.  Wait for result
3.  Save automatically

### Expected behavior

Able to save automatically without intervention.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/cb860d1a-4334-4cdc-bd0e-5c8433803ed2)
![image](https://github.com/user-attachments/assets/4916493f-b72f-454a-aab0-1beceba2af00)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2762.
