### ISSUE TITLE
Nothing is working and I've spent over 20M tokens to get a white screen!!!

### ISSUE THREAD

**Issue by fmehlinger** [stackblitz/bolt.new#2346]
### Describe the bug

I had my app working. The the bot decided to hallucinate and then messed everything up and now all I see is a white screen. No matter what I do, all it does is return error codes and give me a white screen. 20M tokens down the drain and nothing to show for it except frustration and being pissed off that I had to waste that many tokens to have nothing work at all. LAME.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nativescript-js-vg81a1

### Steps to reproduce

who knows...the whole bot hallucinated and messed up my whole app. 

### Expected behavior

at least find the problem and help me solve it and not say everything is fixed only to find the page doesn't load at all. Total waste of money and not happy with the result at all. Would not recommend using Bolt until they fix these hallucinations. It's going to cost users hundreds of dollars just to see something work properly. I could've hired someone and spent less money and got better results. This isn't fair to users at all. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 1114845928,
  "usedJSHeapSize": 1069825424,
  "jsHeapSizeLimit": 4294705152
}
Username = fmehlinger
Chat ID = 3b44f23760f6
```

### Additional context

The cost for the tokens is becoming outrageous especially when problems aren't corrected or they aren't fixed. Not happy with how much I've had to spend to see absolutely nothing.

**Comment by endocytosis** [comment]
Sorry to hear about this! If you have the chat open, you can mouseover the left-hand side of the screen to open the options menu, click Settings, then click Backups, then click the relevant chat to revert to that state. 

Additionally, you can look for past versions of your project by going to [stackblitz.com](stackblitz.com), opening Collections on the left-hand side of the page, and then opening Bolt Collection.

Finally, while you are interacting with Bolt, you can click "Rollback to Checkpoint" at the bottom-right of a previous message to revert your project to that state. Additionally, clicking "Undo" at the bottom right of a message will undo those changes. 

Hope this helps! Additional information on using Bolt most effectively can be found [here](https://github.com/stackblitz/bolt.new/issues/678).
