### ISSUE TITLE
total loss of my file in development

### ISSUE THREAD

**Issue by vieuxgrizou** [stackblitz/bolt.new#2347]
### Describe the bug

unable to recover my file https://bolt.new/p/33307081

### Link to the Bolt URL that caused the error

https://bolt.new/p/33307081

### Steps to reproduce

launch the project

### Expected behavior

in pre-production and it's empty the page no longer loads so the project no longer loads.

I lost thousands of credits tried to restart it with github on bolt...

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by vieuxgrizou** [comment]
I lost millions of credit to relaunch the project, I hope you will make a gesture because we are not the only ones from what I see

**Comment by elogicuk** [comment]
I was also working tonight and my work and messages just vanished and they are no where to be seen

what the hell is going on i am very angry right now

and im a brand new user that signed up tonight

**Comment by endocytosis** [comment]
Hi all, 

Apologies for the issues with chat history. Two things to try: 

1) Navigate to [stackblitz.com](stackblitz.com), login (same credential as Bolt), click Collections on the left-hand side of the page, and then open Bolt Collection. See if your past project is there.

2) If you have a current chat open in Bolt, mouseover the left-hand side of the screen to bring up the options menu, click Settings, then click Backups and open the relevant chat to revert to that state.

**Comment by elogicuk** [comment]
restoring a backup did nothing, my work is still lost i want to cry so much lost.

**Comment by endocytosis** [comment]
Sorry to hear this! I'm merging this issue [here](https://github.com/stackblitz/bolt.new/issues/39) so we can continue to investigate with other issues related to chat persistence. We appreciate your patience as improvements continue to be made!

**Comment by vieuxgrizou** [comment]
and for all the lost credits you will make a gesture because I had to pay again to continue and relaunch the whole project from a new bolt + github I lost half a day there
