### ISSUE TITLE
Bolt crashes on minified React error #310

### ISSUE THREAD

**Issue by endocytosis** [stackblitz/bolt.new#2348]
**Issue:** User encounters Minified React error 310 which results in application crashing. Collecting similar incidents here to investigate further.

**Comment by nicolas-geysse** [comment]
Same issue here
 https://github.com/stackblitz/bolt.new/issues/2365

**Comment by endocytosis** [comment]
Hi all,

Engineering recently released a fix for this issue so it should be resolved shortly on your end. Thanks again for bringing this to our attention.

**Comment by InfoRubix** [comment]
thank you

**Comment by xerudro** [comment]
Yes, but how about our burned tokens we use until the fix really works ? I lost almost 5M tokens building a computer repair platform... who will give me those credits back, to continue to the latest save ... ? This platform of yours is a BIG SCAM.
