### ISSUE TITLE
Netlify Deployment - Claim URL Not Listed 

### ISSUE THREAD

**Issue by fixfounder** [stackblitz/bolt.new#235]
### Describe the bug

When Bolt deploys to Netlify it often doesn't offer a Claim URL.

![image](https://github.com/user-attachments/assets/89a53720-750b-45cb-af98-470dbe9ab1d2)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n8pchx

### Steps to reproduce

1. Make changes to code.
2. Deploy using Netlify
3. URL is provided but no Claim URL
4. Ask for Claim URL
5. Bolt will *usually* generate another site and provide the Claim URL but it can take multiple attempts.

### Expected behavior

Bolt should deploy to a site and provide the Claim URL.

_(Ideally, we control the dest site via config so it stops randomly generating, referenced in another issue or it uses the same site instead spinning up entirely new ones on each deploy)_

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/482abc66-6c22-4a50-9c76-6ce8327ade5e)

### Platform

Windows/Edge

**Comment by fixfounder** [comment]
When I claimed the latest deployment, the last 2-3 suddenly appeared. It might be detecting my Netlify account, but I'm not sure. Before claiming, they didn't show up, even after refreshing.

**Comment by Nemikolh** [comment]
Hey @fixfounder ! Thanks for the report!

We're tracking this issue internally, we'll let you know when we have a fix! 

Like you said retrying typically helps but this is not ideal.

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
