### ISSUE TITLE
Utter Frustration

### ISSUE THREAD

**Issue by StartWithWonder** [stackblitz/bolt.new#2356]
Bolt should have not been released a paid subscritipn option without fixing your developmental issues; this is bad relationship building. charging someone for a product that does not proplery do what it is sold to do. 

1. I wasted hours of my time with bolt making mistakes and fixing things I din't tell it to fix. 
2. It doens't follow instructins and usies it's libert to chagne things that don't need to be changed. 
3. it lies tell you it does stuff that it ddin't and puts you in a loop sayign it's makeing changes that it is reallly not then confess to it that it hasn't been making the changes when it's been saying it's been makeing the changes. THIS IS A PROBELME It show the capacity to tlie. 
<img width="480" alt="Screenshot 2024-11-14 at 1 43 52 PM" src="https://github.com/user-attachments/assets/0596c7d8-b2d2-4a5f-aa19-c0e4d6df3965">

You realease a demo that's capable of missleading people on a paid version. 

to rememdy this. 

I would like to a) Refund my money for this glithcy paid verion I have.  b) make it clear that this released product key fundemtnatl issues so people don't waste there time thinking bolt is going to imporve if you just tell it what to do. c) if you cant give me a refund at least provide a credit and work to rebuild my trust. 

As of Now I WILL TELL EVERYONE TO RUN FROM BOLT TILL YOU FIX YOUR ISSUES  NOT BECUAE IT"S NOT. HELL OF A PRODUCT BUT BECUSE IT WASTE PEOPLES TIMES AND THE INTELLIGENCE NEEDS WORK> AND PEOPLE CANT WASTE THERE TIME LIKE THIS> 

I TRUSTED YOU GUYS AND I DON"T ANYMORE

**Comment by endocytosis** [comment]
Apologies for the frustration! Refund requests are handled through hello@stackblitz.com.
