### ISSUE TITLE
Issue connecting with mongodb

### ISSUE THREAD

**Issue by optimwalls** [stackblitz/bolt.new#2357]
### Describe the bug

~/project 2m 7s
❯ npm run dev

> node-starter@1.0.0 dev
> node --watch src/index.js

(node:399) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"info","message":"Attempting to connect to MongoDB...","timestamp":"2024-11-14T18:38:24.792Z"}
Completed running 'src/index.js'

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8rsc2r

### Steps to reproduce

~/project 6m 6s
❯ npm run dev

~/project 6m 6s
❯ ^E^Unode src/test-mongodb-connection.js

> node-starter@1.0.0 dev
> node --watch src/index.js

(node:403) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"info","message":"Attempting to connect to MongoDB...","timestamp":"2024-11-14T18:44:31.435Z"}
Completed running 'src/index.js'
^C

~/project 1s
❯ npm run dev

> node-starter@1.0.0 dev
> node --watch src/index.js

(node:407) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"info","message":"Attempting to connect to MongoDB...","timestamp":"2024-11-14T18:44:33.176Z"}
Completed running 'src/index.js'

### Expected behavior

connection in mongodb compass is happening, but bolt is not able to connect, i have shared the error message above.
please advise on the resolution

### Screen Recording / Screenshot

its repeating the same process again and again, the string is correct as it connects through mongodb compass, credentials are right, ip addresses are active and whitelisted in mongodb, not sure how to solve this.   Please advise

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105163611,
  "usedJSHeapSize": 91056183,
  "jsHeapSizeLimit": 2160066560
}
Username = Syed Nizamuddin
Chat ID = 95514f6b4421
```

### Additional context

<img width="1440" alt="Screenshot 2024-11-15 at 12 07 29 AM" src="https://github.com/user-attachments/assets/5d7978e6-f569-4af7-a08e-6bce424a9c0a">

**Comment by endocytosis** [comment]
Hi @optimwalls 
Appreciate the feedback! This page [here](#2310) has a number of insights on moving your project forwards. Hope this helps!

**Comment by eturan** [comment]
I’m experiencing the same issue as others have reported. When I download the source code and run it locally, my application successfully connects to my MongoDB cluster hosted on Atlas, which is currently set to accept connections from any IP for testing purposes. However, when I deploy the exact same code on Bolt, it fails to connect to MongoDB Atlas.

I reached out to Bolt’s AI assistant for guidance, and it suggested that network restrictions within the WebContainer environment might be preventing connections to external databases like MongoDB Atlas.

Any advice or workaround for resolving this connectivity issue would be greatly appreciated!

**Comment by boris0237** [comment]
Hi have same issue like @eturan

**Comment by rohitpandey77** [comment]
same issue - connection from compass works but not from bolt's editor

**Comment by gregos** [comment]
from the web container , it's like only ipv6 address is used . on atlas we can only define ipv4 .

**Comment by bigorniax** [comment]
men ..no body from Bolt team cares about fixing this ? 
Sorry I'm a little frustated spending 50M on tokens trying to make this works.

Sad from Bolt side

**Comment by arshx86** [comment]
still same. Cant make a project without it
