### ISSUE TITLE
THIS IS A PROBLEM

### ISSUE THREAD

**Issue by StartWithWonder** [stackblitz/bolt.new#2358]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

 Please read the chat window, I just want credits or a refund for me canceling my subscriptio. I worked with bolt and wasted two days of my time. I can trust this product. 

**Describe alternatives yo
<img width="1791" alt="Screenshot 2024-11-14 at 1 56 44 PM" src="https://github.com/user-attachments/assets/5d47015a-6255-4ee9-89a2-4593d7463e94">
u've considered:**

**Additional context:**

**Comment by endocytosis** [comment]
Apologies for the frustration! There are some programming challenges that are too complex for LLMs to solve. Advice on interacting with Bolt most effectively can be found [here](https://github.com/stackblitz/bolt.new/issues/678). Refund requests are handled through hello@stackblitz.com.

**Comment by StartWithWonder** [comment]
This lousy customerService Sent from my iPhoneOn Nov 14, 2024, at 2:50 PM, Brian ***@***.***> wrote:﻿
Apologies for the frustration! There are some programming challenges that are too complex for LLMs to solve. Advice on interacting with Bolt most effectively can be found here. Refund requests are handled through ***@***.***
