### ISSUE TITLE
prompt is too long: 200272 tokens > 200000 maximum

### ISSUE THREAD

**Issue by nativebrands** [stackblitz/bolt.new#2364]
### Describe the bug

First, I must say great AI tool so far.

I often encounter this error even after providing proper contexts in my prompts
At some points I was able to make headways, but I think I'm currently hitting a snag because nothing works anymote

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dukwmc

### Steps to reproduce

1. The project is an application for a creative community
2. From the onboarding step, the user is expected to complete the onboarding processes, but just in case the user skips all the steps, I want to display a notice on the homepage for the incomplete steps
3. I've already created the homepage, next step was to create the notice component, and here's my prompt
4. Create a notice component above the Story section to show if the user's profile is incomplete from the onboarding pages. This notice should also be dismissable

### Expected behavior

I expected the prompt to run correctly and display the notice component, but I got an error of "prompt is too long: 200272 tokens > 200000 maximum"

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/5d9ad240-5bf6-48a6-a3d5-c6a4ca61f5d9)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 150847706,
  "usedJSHeapSize": 145505906,
  "jsHeapSizeLimit": 4294705152
}
Username = nativebrands
Chat ID = a85eb742be81
```

### Additional context

I've also experienced this on previous prompts and had to undo several changes in most cases.

**Comment by endocytosis** [comment]
Appreciate the feedback here and glad to know you are enjoying using Bolt! This is a known issues regarding the AI model's context window size and is being tracked here: #1322.
