### ISSUE TITLE
Preview is blank 

### ISSUE THREAD

**Issue by magnum6actual** [stackblitz/bolt.new#2368]
### Describe the bug

The last two days - everything I try to do with Bolt has a blank preview. Then it consumes tons of tokens trying to figure out the issue.  Negative value proposition at this point. Perhaps related to a recent update?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2usuup

### Steps to reproduce

Ask Bolt to make pretty much anything 

### Expected behavior

Preview is not blank

### Screen Recording / Screenshot

<img width="1675" alt="Screenshot 2024-11-14 at 14 04 30" src="https://github.com/user-attachments/assets/da528813-ec94-426d-b1d7-d1cb51f95f99">

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = magnum6actual
Chat ID = d3245b7ffdf7
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
