### ISSUE TITLE
Bolt.new chat history gone

### ISSUE THREAD

**Issue by Bigmayn** [stackblitz/bolt.new#237]
### Describe the bug

I was working on a project in bolt.new over the course of the last few days, but now that I get back to it the page had crashed and my project is not in my chat history. I'm able to go back to it through the same link, but it would be better to have it show up in my history. Maybe add a save button or something? 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-shcptu

### Steps to reproduce

1. Leave browser open
2. Chat once in a while
3. Either wait for crash or close browser
4. Check for history

### Expected behavior

Saving my chat in the chat history

### Platform

- OS: Windows
- Browser: Chrome
- Version: 126.0.6478.254

**Comment by swcrazyfan** [comment]
I had the same problem! I spent a few hours on a project, and now it's suddenly gone. Just gone. I even paid for the month. I'm a bit upset, to be honest.

**Comment by Nemikolh** [comment]
Hey everyone! Sorry for the inconvenience, projects are persisted at the moment but not chats.

We're tracking this in #39, you can subscribe to it to be notified when they are.
