### ISSUE TITLE
Daily token count does not reset

### ISSUE THREAD

**Issue by CentillionJinx** [stackblitz/bolt.new#2370]
### Describe the bug

The daily token count is seemingly not being reset. it has been more than 24h, and there is not reset to 0, for the daily token count.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fvnemd

### Steps to reproduce

1. Use some of the token to generate templates
2. wait 24h
3. The daily token count is still unchanged

### Expected behavior

A reset of daily token count.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/6642980a-2770-4469-9314-b278dd931ea2)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

Linux - Chrome - 130.0.6723.116

**Comment by endocytosis** [comment]
Hi @CentillionJinx, 

Are you still seeing this issue? What time zone are you in?

**Comment by CentillionJinx** [comment]
![Screenshot_20241115-123544](https://github.com/user-attachments/assets/1aad90b2-b3db-47ad-bd4a-9fafbc998b2f)

The issue seems to be resolved. I am at AEDT.

**Comment by MorrisMuuoMulitu** [comment]
It's the same issue for me. Has been more than 48 hours. The daily token count is still O.
I am in the EAT time zone.
