### ISSUE TITLE
Can't get Vimeo or YouTube videos to work

### ISSUE THREAD

**Issue by Larry4547** [stackblitz/bolt.new#2374]
### Describe the bug

I spent more than an hour trying to get my Vimeo video to play on a page in my project. The video was always broken and unable to play. I then tried with a video link from YouTube and got the same result.

What is the dependable way to get video to play in my Bolt SaaS project?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dxw6lh

### Steps to reproduce

1. Login for the following credentials; Email: advisor.tier3.1@learntgymoney.com Pw: Hello23.4
2. Select Tools from the main menu
3. Select Open Tool in Business Valuation
4. See the broken video player at the top of the page.

### Expected behavior

The video should be playable on the page.

### Screen Recording / Screenshot

![CAP-MockVideoPlayer-01-111424-C](https://github.com/user-attachments/assets/51ed431c-27ff-4206-a07a-27f7f12ed83d)

### Platform

- OS: [Windows 10]
- Browser: [Chrome]

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately we don't have the resources to offer programming assistance for individual projects but this page [here](https://github.com/stackblitz/bolt.new/issues/2310) may be helpful for next steps you can take.
