### ISSUE TITLE
Lost all my tokens all of a sudden

### ISSUE THREAD

**Issue by igorfel** [stackblitz/bolt.new#2376]
### Describe the bug

Well, I was working on a project since yesterday, (had 24 million tokens left) and today after some hours in it i've paused working on it and did checked the remaining tokens on my account it was close to 19 million but after some time (a few minutes) when /I tried to continue working on the project it simply said that i have 0 tokens left.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-517avw

### Steps to reproduce

do not apply

### Expected behavior

do not apply

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/94177036-1a4a-4229-91f5-803a1b9c5792)

**Comment by endocytosis** [comment]
Hi @igorfel,

Sorry to hear this! Can you reach out to hello@stackblitz.com with your account information so we can look into this further. Thanks.
