### ISSUE TITLE
Lost millions of tokens

### ISSUE THREAD

**Issue by Hazier007** [stackblitz/bolt.new#2378]
### Describe the bug

Hi, I was working on a project and spent millions of tokens untill I had a white screen. Now I can't find back the project. Where is it? And how to avoid losing my tokens? 

### Link to the Bolt URL that caused the error

I lost the project

### Steps to reproduce

Was working untill whitescreen

### Expected behavior

Wanted to keep working on the site. It was almost done :(

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @Hazier007, 

Appreciate the feedback and sorry to hear about the issues. Are you able to see if you project is in the following location: go to [stackblitz.com](https://stackblitz.com), login (same credentials as Bolt), click Collections on the left-hand side of the page, open Bolt Collection. 

Additionally, if you are on Bolt and mouseover the left-hand side of the page to open the settings menu, you can open Settings and then click Backups to look up previous versions of your chat and revert to that state.

Regarding utilizing Bolt most effectively while maximizing token efficiency, this page [here](https://github.com/stackblitz/bolt.new/issues/678) has some insights. Hope this helps!
