### ISSUE TITLE
Chat History is always empty.

### ISSUE THREAD

**Issue by p2horst** [stackblitz/bolt.new#238]
### Describe the bug

I chated with bold, but the Chat history is empty.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. chat with bold
2. refresh bold.new
3. chat history is empty

### Expected behavior

Old bolt chats exists.

### Platform

- OS: [Windows 11]
- Browser: [MS Edge]
- Version: [129.0.2792.79 (Official build) (64-bit)]

**Comment by Nemikolh** [comment]
Hey @p2horst! Sorry for the inconvenience, chats are not persisted at the moment but your project is.

We're tracking this in #39, you can subscribe to it to be notified when we land the feature.
