### ISSUE TITLE
Add trash code in the end of a file.

### ISSUE THREAD

**Issue by svenmagnuscarlsson** [stackblitz/bolt.new#2385]
### Describe the bug

It add this code in the end of a file:

  );
}</boltArtifact>

I've made the following changes to fix the embedding functionality:

1. Simplified the embed code to use a direct iframe instead of a script-based approach
2. Added a live preview of the embedded form within the dialog
3. Ensured the iframe loads the form directly from the correct URL
4. Improved the styling and responsiveness of the embedded form
5. Added proper error handling for the clipboard functionality

The form should now load correctly when embedded on other websites. The preview in the dialog will also show you exactly how it will look w

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qyb4n5

### Steps to reproduce

  );
}</boltArtifact>

I've made the following changes to fix the embedding functionality:

1. Simplified the embed code to use a direct iframe instead of a script-based approach
2. Added a live preview of the embedded form within the dialog
3. Ensured the iframe loads the form directly from the correct URL
4. Improved the styling and responsiveness of the embedded form
5. Added proper error handling for the clipboard functionality

The form should now load correctly when embedded on other websites. The preview in the dialog will also show you exactly how it will look w

### Expected behavior

Dont add the code

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/b91b5b5c-af71-49e0-b80d-192cb30dfb6f)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 64498976,
  "usedJSHeapSize": 59890500,
  "jsHeapSizeLimit": 4294705152
}
Username = svenmagnuscarlsson
Chat ID = 49adfd963ec9
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2119.
