### ISSUE TITLE
My chats dissappeared

### ISSUE THREAD

**Issue by srijan816** [stackblitz/bolt.new#239]
### Describe the bug

My chat with my projects dissappeared randomly. basically after i logged out and then logged in. fix that please

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

No idea

### Expected behavior

The projects show up on dashboard

### Platform

- macOS
- Chrome

**Comment by Nemikolh** [comment]
Hey @srijan816 ! Sorry for the inconvenience, chats are not persisted at the moment but your projects are.

We're tracking this in #39, you can subscribe to it to be notified when we land the feature.

**Comment by srijan816** [comment]
Hi,
My account was running out of tokens and I got this notification that said:
"Subscribe to Pro 2 for 3X more usage but I don't see a Pro 2 option among
my subscriptions." Alternatively, just yesterday, I had an option to buy an
additional 10M tokens which are not viewable anymore.

Is there a way for me to purchase tokens?

Thanks
