### ISSUE TITLE
Blank page in preview, no matter what kind of prompt.

### ISSUE THREAD

**Issue by Eagleprojectz** [stackblitz/bolt.new#2390]
### Describe the bug

It does not matter, how complicated or easy the prompt is, the preview is always a blank page. 
After asking to resolve the issues there is no change in the preview.
It is happening in different browsers, on different devices and on different chats.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-c3zu92

### Steps to reproduce

1. Create prompt
2. Wait for bolt to deploy and create the project
3. Wait for preview to load
4. See blank screen appear

### Expected behavior

I expected to see the created application in the preview just as the bolt ai described it as a reaction to my prompt.

### Platform

- OS: macOS
- Browser: Safari / Firefox
- Version: 18.0.1 / 132.0.2

**Comment by siyant** [comment]
I faced the same error too in both Firefox 132.0.2 and Safari 17.6 on macOS, with a super basic React Vite project. The same project worked in Chrome.

In Firefox, I can see that there is a <div id="root"></div> in the preview window, but it is empty.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791). 

Bolt is most compatible with Chrome and Chromium browsers.

Try selectively disabling browser extensions such as ad blockers and refresh the page to see if this resolves the problem. Additionally, you can try typing "npm run dev" in the Bolt console.
