### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by mitunami** [stackblitz/bolt.new#2393]
### Describe the bug

An application error has occurred. The following message was displayed on bolt.net and the process ended.

NotFoundError: Could not perform 'removeChild' on 'Node': The node being removed is not a child of this node.
    Ec で (https://bolt.new/assets/components-B64jh5hJ.js:24:25974)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27253)
    kc にて (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    kc にて (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    kc にて (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    kc にて (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-z1sday

### Steps to reproduce

It is unknown how to reproduce it.
This occurred after an instruction was given in chat.

### Expected behavior

Avoid application errors.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72195587,
  "usedJSHeapSize": 67893415,
  "jsHeapSizeLimit": 4294705152
}
Username = mitunami
Chat ID = ffe7bac17b4c
```

**Comment by AriPerkkio** [comment]
Hey @mitunami, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
