### ISSUE TITLE
Cant get URL to test on mobile

### ISSUE THREAD

**Issue by fscheps** [stackblitz/bolt.new#2398]
### Describe the bug

I am trying to get Bolt to give me the URL I should use to test the app I am developing on my mobile, but I am stuck in a loop (again), where bolt doesnt help and repeats over and over the same.

The message "it" gives me is: 

Once the server starts, you'll see a URL in the terminal that looks like:
https://[unique-id].local-credentialless.webcontainer.io

You can open this URL on your mobile device or any other device on your network to test the application.

I go to Terminal and I see nothing just a blinking cursor, I go to preview and I see the app started so not sure what the problem is.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qzwh1q

### Steps to reproduce

Trying to get the URL of the app so I can test it.

It would be nice if we would always see the URL of the app to test it on an incognito window or our mobile device. We just need that this has a complex URL not referenced anywhere else (like for example a support ticket) to ensure only we have access temporarily to that URL and test our app.

### Expected behavior

Explained above. Thank you!

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Chrome
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96727145,
  "usedJSHeapSize": 75009141,
  "jsHeapSizeLimit": 4294705152
}
Username = fertech
Chat ID = eedd73b2062f
```

**Comment by endocytosis** [comment]
If you click "Deploy" at the top-right of the page in Bolt you will receive a Netlify link that you can then access from any device, including your phone. Hope this helps!
