### ISSUE TITLE
LLM Response Added to Code Files

### ISSUE THREAD

**Issue by dpmishler** [stackblitz/bolt.new#24]
### Describe the bug

In multiple files, the LLM response was added to the end of whatever file it starts working on first. See the screenshot for a representation, but this happened across almost every file in the repo.
![image](https://github.com/user-attachments/assets/37f481f1-93a7-40b3-b944-61661666bf55)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-im584d

### Steps to reproduce

1. Ask for a complicated app that will result in many files
2. Examine the end of each created file

### Expected behavior

You will find the LLM Response at the bottom of the file. I had to delete them manually from each file.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67335897,
  "usedJSHeapSize": 52234557,
  "jsHeapSizeLimit": 4294705152
}
Username = dpmishler
Chat ID = 66ad2df9ed12
```

**Comment by chrismahoney** [comment]
I’m familiar with React Flow, do you have details about the prompt resulting in this?

**Comment by Nemikolh** [comment]
Hey @dpmishler ! :wave: Thanks for opening this issue!

We're aware of this and working on making sure this error does not happen. AFAIK, this is not related to the prompt provided to Bolt, it just happens from time to time.

We'll keep you posted!

**Comment by kc0tlh** [comment]
This should be resolved, as we've upgraded to a new Sonnet 3.5 model under the hood and not seen any more reports of this. Going to close this for now, but feel free to comment below if you experience this again with the new model!

**Comment by ImLunaHey** [comment]
im getting the same issue with astro. should i open a new issue? 🤔

**Comment by copostic** [comment]
Still have the error with Claude 3.7 Thinking.
I have duplicate tags on my Nuxt project, one of them with boltAction tags inside.
Any idea how to solve it ?
