### ISSUE TITLE
Agent cannot solve blank Home Screen issue

### ISSUE THREAD

**Issue by etheuer** [stackblitz/bolt.new#2402]
### Describe the bug

The agent is running in circles. Almost 10 prompt asking it to fix what it broke and I cannot get my app back to the state when it was working.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v45wwm

### Steps to reproduce

go to the agent chat, tell it the preview is loading a blank screen instead of the app home.

### Expected behavior

Shoe the Home Screen.

### Screen Recording / Screenshot

<img width="1302" alt="Screenshot 2024-11-14 at 21 15 09" src="https://github.com/user-attachments/assets/a7271c8b-6c98-4885-aaca-70f528f76be8">

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = stoic-mouse
Chat ID = f8a223cce565
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it https://github.com/stackblitz/bolt.new/issues/1791.

Bolt is most compatible with Chrome and Chromium browsers.

Try selectively disabling browser extensions such as ad blockers and refresh the page to see if this resolves the problem. Additionally, you can try typing "npm run dev" in the Bolt console.

**Comment by kc0tlh** [comment]
@etheuer additionally, Settings > Backups should help you revert to prior states
