### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by mitunami** [stackblitz/bolt.new#2405]
### Describe the bug

After sending the instructions to the chat, the application error occurred again.
The error message below appears on the screen, and you cannot recover unless you open bolt.net anew from your browser.
Your previous work will be lost.

NotFoundError: Could not perform 'removeChild' on 'Node': The node being removed is not a child of this node.
In Ec (https://bolt.new/assets/components-B64jh5hJ.js:24:25974)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27253)
    At kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    At kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    At kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    At kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-z1sday

### Steps to reproduce

Not reproducible. This happens suddenly when I am giving instructions via chat.

### Expected behavior

Please improve the application so that errors do not occur.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53678286,
  "usedJSHeapSize": 50911066,
  "jsHeapSizeLimit": 4294705152
}
Username = mitunami
Chat ID = 87eeac24471f
```

**Comment by AriPerkkio** [comment]
Hey @mitunami, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
