### ISSUE TITLE
Why do have no version controll?

### ISSUE THREAD

**Issue by brie77** [stackblitz/bolt.new#243]
### Describe the bug

Why is there no version controll to go a few steps backwards? This ist totally useless!!! I worked for hours on a layout and with one change it destroyed all our work and it just can't set it back to where everything was good. This is a waste of time!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aqwpus

### Steps to reproduce

...

### Expected behavior

...

### Screen Recording / Screenshot

...

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80670433,
  "usedJSHeapSize": 56944077,
  "jsHeapSizeLimit": 4294705152
}
Username = brie77
Chat ID = 20bea7b1f75d
```

### Additional context

...

**Comment by superresistant** [comment]
Why not using github for version control? It's fully compatible and it's how professional or amateur do. You can also download your files.

**Comment by kc0tlh** [comment]
@brie77 Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
