### ISSUE TITLE
Unable to upgrade to Pro version due to payment authentication issue

### ISSUE THREAD

**Issue by davmdk13** [stackblitz/bolt.new#2432]
### Describe the bug

I have been trying to upgrade to the Pro version of the application for the past three days, but I am unable to complete the payment. After entering my card details and passing the CAPTCHA (via Stripe), I receive the following error message:
'We are unable to authenticate your payment method. Please choose another payment method and try again.'
I have tried using multiple cards, but the issue persists.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7aa21s?showPricing=true

### Steps to reproduce

Go to the billing or upgrade page.
Select the Pro version and proceed to the payment process.
Enter card details and complete the CAPTCHA.
Observe the error message after authentication attempt.

### Expected behavior

The payment should be processed successfully, and I should be able to upgrade to the Pro version without issues.

### Platform

MAC OS
Chrome browser

### Additional context

This issue only occurs when attempting to upgrade to the Pro version. The free version of the application works without any problems. I have tried using different cards and networks, but the problem persists.

**Comment by endocytosis** [comment]
Hi @davmdk13, 

Could you please reach out to hello@stackblitz.com with your account information so that they can look into this further? Thanks!
