### ISSUE TITLE
Past chats not available

### ISSUE THREAD

**Issue by Arcade1080** [stackblitz/bolt.new#2435]
### Describe the bug

I cannot see my last project in the "Your chats" section anymore and all my progress and work is gone. This is really bad since I am on premium and spent a lot of tokens for this. How to recover my past project?

### Link to the Bolt URL that caused the error

Not there anymore and that is the problem

### Steps to reproduce

1. Use the editor
2. Past project is not in the "Your chats" section

### Expected behavior

 Past project is not in the "Your chats" section

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi @Arcade1080, 

Sorry to hear about this! Two things to try: 

1) Can you go to [stackblitz.com](https://stackblitz.com), login (same credentials as Bolt), click Collections on the left-hand side of the page, then open Bolt Collection and see if your project is there?

2) Could you try logging out of Bolt, clearing your browser cache, and logging back in to see if this resolves the issue?

**Comment by Arcade1080** [comment]
Hey @endocytosis,

1. It is there but with the initial boilerplate. My progress is gone.
2. Does not resolve. 

Any more ideas?

**Comment by endocytosis** [comment]
Hi @Arcade1080, 

Unfortunately it looks like this is a bug which we are tracking [here](https://github.com/stackblitz/bolt.new/issues/1954). We appreciate your patience as the team continues to make improvements!
