### ISSUE TITLE
Importing Github repo fails

### ISSUE THREAD

**Issue by manulykebe** [stackblitz/bolt.new#2442]
### Describe the bug

trying to import: https://bolt.new/~/github.com/manulykebe/editor

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/manulykebe/editor

### Steps to reproduce

1. go to the above url: https://bolt.new/~/github.com/manulykebe/editor
2. takes a while ('We are still retrieving the repository, hang tight'), then error pops up:
x Import manulykebe/editor
Cannot destructure property 'appFiles' of 'project' as it is null.

### Expected behavior

succesful import of project

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/cf9fceb5-2bf6-493f-a7aa-6538350b3e1d)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54828175,
  "usedJSHeapSize": 37695547,
  "jsHeapSizeLimit": 4294705152
}
Chat ID = 1604d222ed67
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1812).
