### ISSUE TITLE
preview Bug 

### ISSUE THREAD

**Issue by Elspecko** [stackblitz/bolt.new#2446]
### Describe the bug

I'm currently having a problem where the preview of the projects isn't loading; it's always the loading screen.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aavpci

### Steps to reproduce

As soon as I give it instructions, it writes the code and then starts the project with npm run dev and opens the preview.

### Expected behavior

Quick fix, can't work any further at the moment, the problem exists in all projects.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/975865c9-a4a9-4b1f-8fc7-ab162840271a)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

**Comment by Elspecko** [comment]
Found the error the browser extension in chrome Urban VPN generates this error
