### ISSUE TITLE
Why is there no place to send mail or form to ask for refund?

### ISSUE THREAD

**Issue by code-pumpkin** [stackblitz/bolt.new#2448]
Last month, I subscribed to your $20 plan. While the service worked fine initially, I noticed that it consumed tokens very quickly and often did not provide solutions as comprehensive as those I experienced with other platforms like Claude.ai.

I understand that this is part of a beta testing phase, and I appreciate the effort being put into refining the platform. However, I don’t feel that the current experience justifies the cost for me personally.

Today, my subscription renewed automatically for another month. Since I do not wish to continue at this time, I kindly request a refund for the renewal. I’m happy to reconsider subscribing in the future when the platform has improved further.

Thank you for your understanding, and I look forward to hearing from you.
Please reply to this request with your mail or some form where i could request for the same.

**Comment by endocytosis** [comment]
Hi @code-pumpkin 

Refund requests are handled through hello@stackblitz.com. Please reach out there with your account information.
