### ISSUE TITLE
prompt to long

### ISSUE THREAD

**Issue by CooldudeGeldrop** [stackblitz/bolt.new#2449]
### Describe the bug

prompt is too long: 202095 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-p2nuhd

### Steps to reproduce

creates this error somehow

### Expected behavior

Just divide in 2 pieces and complete the task

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/161f690d-82d6-4474-93c2-41f299998ff7)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 157891807,
  "usedJSHeapSize": 151705795,
  "jsHeapSizeLimit": 4294705152
}
Username = Cooldudeams
Chat ID = 7a6861a79f53
```

### Additional context

you would expect prompt length calculation function in the core module also the code becomes more sloppy waisting loads of tokens

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
