### ISSUE TITLE
Bolt regenerates abbreviated versions of files

### ISSUE THREAD

**Issue by arghhhhh** [stackblitz/bolt.new#245]
### Describe the bug

When instructing Bolt to fix an issue, it seems to regenerate code for an entire file whenever modifications to parts of that file's code are necessary. Multiple times over the course of testing, Bolt simply erased important parts of my app's code and replaced them with comments, similar to how other LLMs abbreviate long outputs. 

See below photo for example
<img width="436" alt="{02C6BC9F-67EA-4466-9C9B-124A8B0978BA}" src="https://github.com/user-attachments/assets/61fd74c8-3c93-41bf-bc3d-26e61e6477d8">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bkhvvk

### Steps to reproduce

1. Go to url.
2. Inspect contents of /src/App.tsx

### Expected behavior

Do not replace functional code with comments. 

### Platform

- OS: [Windows,]
- Browser: [Edge, Firefox]

**Comment by samdenty** [comment]
We're tracking this internally. You can follow #124 to get notified when we've resolved this issue.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
