### ISSUE TITLE
Error Deploy

### ISSUE THREAD

**Issue by faqimifauzi** [stackblitz/bolt.new#2455]
### Describe the bug

It always says

Failed building the project. Make sure the build command is correct and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-68hh6w

### Steps to reproduce

When click deploy to netlify

### Expected behavior

Always loss token with this problem.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 125180819,
  "usedJSHeapSize": 119860815,
  "jsHeapSizeLimit": 4294705152
}
Username = faqimifauzi
Chat ID = 5260ed8c2b22
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
