### ISSUE TITLE
Cannot create website

### ISSUE THREAD

**Issue by Polarisman1964** [stackblitz/bolt.new#2458]
### Describe the bug

I give Bolt clear instructions but it is unable to even create a demo site.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ah24hx

### Steps to reproduce

I give it instructions and it fails

### Expected behavior

A working website

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60174533,
  "usedJSHeapSize": 57429861,
  "jsHeapSizeLimit": 4294705152
}
Username = Polarisman1964
Chat ID = bf974750cb4f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on using Bolt most effectively while maximizing token efficiency.
