### ISSUE TITLE
Preview of not showing

### ISSUE THREAD

**Issue by fconteh** [stackblitz/bolt.new#2459]
### Describe the bug

After generating the project, one can see the code, but can't preview.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zw9yxa

### Steps to reproduce

N/A

### Expected behavior

I wanted to generate a presentation about screenplay.

### Screen Recording / Screenshot

N/A

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64749090,
  "usedJSHeapSize": 61201002,
  "jsHeapSizeLimit": 4294705152
}
Username = fconteh
Chat ID = 72c103deed43
```

### Additional context

Preview is not working

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it https://github.com/stackblitz/bolt.new/issues/1791.

Bolt is most compatible with Chrome and Chromium browsers.

Try selectively disabling browser extensions such as ad blockers and refresh the page to see if this resolves the problem. Additionally, you can try typing "npm run dev" in the Bolt console.
