### ISSUE TITLE
got the following error when trying to access my repo on github

### ISSUE THREAD

**Issue by d-vlasov** [stackblitz/bolt.new#246]
### Describe the bug

Tried to access: https://bolt.new/github/d-vlasov/cv-optimizer-genie, received application error:

Application Error
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fe (https://bolt.new/assets/components-g8_Fbz61.js:24:33638)
    at np (https://bolt.new/assets/components-g8_Fbz61.js:22:22233)
    at rB (https://bolt.new/assets/_index-BZGIVHL1.js:3:685)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:754
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:743
    at rB (https://bolt.new/assets/_index-BZGIVHL1.js:3:685)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:754
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:743

### Link to the Bolt URL that caused the error

https://bolt.new/github/d-vlasov/cv-optimizer-genie

### Steps to reproduce

Just tried to open https://bolt.new/github/d-vlasov/cv-optimizer-genie

### Expected behavior

Expected my project from github to be imported

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samdenty** [comment]
Hey everyone! Sorry for the inconvenience, we're going to track this in https://github.com/stackblitz/bolt.new/issues/260
