### ISSUE TITLE
I need to get access to my bolt.new project 

### ISSUE THREAD

**Issue by bencium** [stackblitz/bolt.new#2462]
### Describe the bug

I need to get access to my bolt.new project after switching to stackblitz,  linking to a repo and deploying to netlify as promised

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/bencium/sb1-jjb5fj

### Steps to reproduce

1. create site in bolt.new
2. open in stackblitz
3. link to repo on GH
4. deployed to netlify
5. reopened in stackblitz and edited manually successfully - auto deploy worked BUT

when I load bolt.new/GHusername/reponame I get an error message

### Expected behavior

open in bolt.new for continuous edit and deployment (and not only in stackblitz
<img width="494" alt="Screenshot 2024-11-15 at 14 26 21" src="https://github.com/user-attachments/assets/f55fe129-abeb-42d4-83a9-ec8eadd6eb1f">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108399874,
  "usedJSHeapSize": 98646942,
  "jsHeapSizeLimit": 4294705152
}
Username = bencium
Chat ID = bd06adb333d8
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Hi @bencium, 

Appreciate the feedback! The team is hard at work continuing to make improvements to the git workflow, which we are tracking [here](https://github.com/stackblitz/bolt.new/issues/2367). 

Also, Bolt does not support private GitHub repositories at this time.

**Comment by Labhk** [comment]
Hey, I have build this web tool for just this, previously using script on local now its a website much easy, enjoy
https://boltsync.mystify.tech/
https://www.youtube.com/watch?v=IneFM6ViV8s
