### ISSUE TITLE
big appa

### ISSUE THREAD

**Issue by MyAiLaptop** [stackblitz/bolt.new#2466]
I am building a big app but as its fixing one issue another appears. Now I am just burning tokens trying to fix something that was right before the something that was wrong before. Going in circle's  I am on the 200 per month plan but don't think I will ever finish. we need to stop changing pages that was right to fix something that was wrong. think I must wait a few months before logging in again maybe the product will get better. that said this is the best thing since sliced bread.

**Comment by endocytosis** [comment]
Hi @MyAiLaptop, 

Glad to hear you are liking Bolt! A few things you can try: 

- If you right-click a file in the Bolt code editor and select "Lock file" this will prevent the AI from making further changes to that file. This can be done to multiple files. 
- This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt most effectively while maximizing token efficiency.
- As your application becomes more complex you may run into programming challenges that require additional research and intervention, which you can read more about [here](https://github.com/stackblitz/bolt.new/issues/2310). 

Hope this helps!
