### ISSUE TITLE
prompt is too long issue

### ISSUE THREAD

**Issue by Johnprogg** [stackblitz/bolt.new#2467]
### Describe the bug

prompt is too long: 200186 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

prompt is too long: 200186 tokens > 200000 maximum

### Expected behavior

prompt is too long: 200186 tokens > 200000 maximum

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Larry4547** [comment]
I experienced this issue as well yesterday.

**Comment by endocytosis** [comment]
Hi all, 

This is a known issue with the AI model’s context window size and is being tracked here: #1322. The top comment on that page has a preview link that you can try to support larger projects.

**Comment by Larry4547** [comment]
Thank you. 
Does mean that for now, projects with this error can’t be developed further? I’m making a prototype for a client. So I need to know what to tell them. 


Sent from Yahoo Mail for iPad


On Friday, November 15, 2024, 12:10 PM, Brian ***@***.***> wrote:




Closed #2467 as completed.
