### ISSUE TITLE
Bolt deploys to a different link on netlify everytime browser refreshes or new session is started. 

### ISSUE THREAD

**Issue by alan313313** [stackblitz/bolt.new#2469]
### Describe the bug

Hey,

Complete noob here.

I deployed my app, to Netlify, then added a custom domain.
As long as I try to redeploy or rather update the already deployed version during the same session, it works. But it seems that if I refresh by browser or open it the next day make changes and try to update the app, it just creates a new deploy link every time forgetting that it's already deployed.

When I try to upload the project manually it fails due to typescript errors. So I'm stuck... Every time I want to update testers I have to claim new link, change DNS records on my domain etc.

What am I doing wrong? How to fix this?

### Steps to reproduce

press deploy button on a new session or ask it to redeploy or update and it's going to just create a new deploy link.

### Expected behavior

I'd like to push updates to the same link consistently.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110693192,
  "usedJSHeapSize": 106754184,
  "jsHeapSizeLimit": 2160066560
}
Username = alan313313
Chat ID = 2a2f31f9b4fe
```

**Comment by daletkc** [comment]
I think this is expected to deploy a unique URL.

**Comment by alan313313** [comment]
Like I said, it know how to update the current deploy but only in the same session. 

That's fine with me but I need to understand how to have a permanent site I can update consistently.

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback. Yes, this is the intended behavior at this time. We are aware of the request for the ability to continue to update the site associated with a custom domain and are tracking it here: #49.

In the meantime, you can open the project in StackBlitz (click "Open in StackBlitz") at the top-right of the Bolt page and continue development there with git integration. Hope this helps!
