### ISSUE TITLE
Go back in hstory missing

### ISSUE THREAD

**Issue by ilkkanisula** [stackblitz/bolt.new#247]
### Describe the bug

When prompting a change and AI messes up you should have simple way to return to previous version.
I prompted for 20 minutes for implementation, then in single prompt it wiped the created content and there was no way to restore it back. As a rescue attempt I reloaded window which made the whole history disappear.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-acmizv

### Steps to reproduce

Just prompt something compex like animation and as it to return to previous version that worked...

### Expected behavior

It should return to some previous version and not invent a new version.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 95295206,
  "usedJSHeapSize": 73773166,
  "jsHeapSizeLimit": 2172649472
}
Username = ilkkanisula
Chat ID = b6804f227401
```

### Additional context

I was doing svelte 4 component with canvas animation and mouse pointer interaction.

**Comment by ilkkanisula** [comment]
Some kind of generation tree could also be possibly used to handle each change as a patch. You could also generate multiple alternative branches and perhaps switch between them. Similarly like in image generators you create 2-4 images per prompt. And since each node in tree would be a patch, it could be reused later if wanted. For web outputs you could store a screenshot thumbnail for each snapshot.

**Comment by dragsbruh** [comment]
#35 is a similar issue. This is a heavily requested feature lmao

**Comment by kc0tlh** [comment]
@ilkkanisula Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #17!

**Comment by kc0tlh** [comment]
@ilkkanisula Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
