### ISSUE TITLE
wont fix the problem

### ISSUE THREAD

**Issue by Blueoctopusdigital** [stackblitz/bolt.new#2472]
### Describe the bug

its been well over 20 attempts and crunched through nearly 5m credits to fix an issue it literally keeps saying is fixed and its not. the blog editor is supposed to be showing a SEO score, suggestions and keywords along with image generator and no matter what prompt i write i cant see what it says its fixed. As i say ive crunched through 5m credits on this one issue 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ygh5qf

### Steps to reproduce

i want the view to follow the script. In the Blog editor i should have the AI button, SEO score and SEO suggestions as well as AI image generator, and on the social media side, i should have the ability to use AI to create posts, and also the blog editor should have an option to create a social meida post on this which will then appear in the schedule 

### Expected behavior

correct the view of what should be on there. I keep suggesting to refresh the entire code for the site but the same issue keeps appearing 

### Screen Recording / Screenshot

i cant show what its not showing 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92841048,
  "usedJSHeapSize": 84890964,
  "jsHeapSizeLimit": 4294705152
}
Username = Blueoctopusdigital
Chat ID = b6fda8a7d100
```

### Additional context

none but i want credit back for 5m credits as ive wasted this trying to fix the issue

**Comment by endocytosis** [comment]
Appreciate the feedback! Oftentimes more detailed next steps are necessary to continue with more complicated application development, which you can read more about [here](https://github.com/stackblitz/bolt.new/issues/2310). Hope this helps!

**Comment by endocytosis** [comment]
Additionally, refund requests are handled through hello@stackblitz.com.

**Comment by Blueoctopusdigital** [comment]
its not a refund its giving me back 5m credits as i burnt through those in 45 mins for this one issue
