### ISSUE TITLE
Can't open a StackBlitz project in Bolt

### ISSUE THREAD

**Issue by caxaria** [stackblitz/bolt.new#2474]
### Describe the bug

Imported a public project from github into StackBlitz and then opened it (https://bolt.new/~/xoriwybwzp.github). It opened an empty project.

### Link to the Bolt URL that caused the error

https://bolt.new/~/xoriwybwzp.github

### Steps to reproduce

1. Go to https://stackblitz.com/
2. Click repositories
3. Open a public repo
4. Replace https://stackblitz.com/~/github.com/.... for https://stackblitz.com/github/...
5. Click button "Open in bolt.new"

### Expected behavior

Open the repo

### Screen Recording / Screenshot

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b7f5d596-16ee-466b-83f2-01e2424286a6">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/82d6bf46-e308-4988-bb45-5f7c2d07feae">

### Platform

- OS: MacOS
- Browser:Chrome

**Comment by endocytosis** [comment]
Hi @caxaria, 

To open a public repository in Bolt, enter bolt.new[PUBLIC GITHUB URL]. For the public project you reference, this would be: 

[https://bolt.new/github.com/caxaria/joao-caxaria-com](https://bolt.new/github.com/caxaria/joao-caxaria-com)

Does this work successfully on your end?

**Comment by caxaria** [comment]
It does! Thank you <3

**Comment by endocytosis** [comment]
Glad to hear it, you're welcome!
