### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by optimwalls** [stackblitz/bolt.new#2475]
### Describe the bug

An unknown error occured while processing the servers response
<img width="1440" alt="Screenshot 2024-11-15 at 11 03 18 PM" src="https://github.com/user-attachments/assets/2d168b0f-fb39-4080-a525-f220acb064d1">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uztwjy

### Steps to reproduce

see error

### Expected behavior

its stopping, see error in image shared

### Screen Recording / Screenshot

<img width="1440" alt="Screenshot 2024-11-15 at 11 03 18 PM" src="https://github.com/user-attachments/assets/bb66bf0e-9b7f-4623-8147-213fdf91ed62">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 121429563,
  "usedJSHeapSize": 112086379,
  "jsHeapSizeLimit": 2160066560
}
Username = Syed Nizamuddin
Chat ID = 83b3f87c99ec
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.
