### ISSUE TITLE
Prompts don't work in a HTML5 project for me.

### ISSUE THREAD

**Issue by aleaming** [stackblitz/bolt.new#2476]
### Describe the bug

prompt is too long: 214319 tokens > 200000 maximum
<img width="1285" alt="Screenshot 2024-11-15 at 10 43 24 AM" src="https://github.com/user-attachments/assets/5f3e2280-9afc-4695-a975-ab213b913c89">

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-mgze9u

### Steps to reproduce

Import an HTML website project and try to enter any prompt.
https://stackblitz.com/edit/stackblitz-starters-mgze9u?file=package.json

### Expected behavior

I should be able to enter a prompt and have Bolt help me edits to my HTML5 project. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 131522188,
  "usedJSHeapSize": 126911532,
  "jsHeapSizeLimit": 4294705152
}
Username = aleaming
Chat ID = 2850e6006aec
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
