### ISSUE TITLE
Can not render a US map

### ISSUE THREAD

**Issue by CDECK2019** [stackblitz/bolt.new#2478]
### Describe the bug

Ive asked bolt in many different ways to create a US map and it is unable to do so. This is pretty staightforward I thought...

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Can you create the most modern and beautiful dashboard in darkmode with a dynamic map of the united states as its central image? This map should have the capacity to highlight states whose data points fed into the dashboard.
2. The most important part of this mission is to determine whether you can create this dynamic US-map. Please ensure that it is visible on the preview pane

### Expected behavior

Can you create the most modern and beautiful dashboard in darkmode with a dynamic map of the united states as its central image? This map should have the capacity to highlight states whose data points fed into the dashboard.

The most important part of this mission is to determine whether you can create this dynamic US-map. Please ensure that it is visible on the preview pane

### Screen Recording / Screenshot

<img width="739" alt="Screenshot 2024-11-15 at 1 29 38 PM" src="https://github.com/user-attachments/assets/76d75eb3-aaa9-47e4-9d8c-866d3121f91b">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110293915,
  "usedJSHeapSize": 103841375,
  "jsHeapSizeLimit": 2160066560
}
Username = CDECK2019
Chat ID = 5ff871a37072
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Something that can help is prompting the AI to use specific libraries. If there is a specific open-source map library you have in mind, explicitly tell Bolt to use that. This page [here](https://github.com/stackblitz/bolt.new/issues/2310) has a number of insights on advancing your project. Hope this helps!
