### ISSUE TITLE
I have this error when trying to send a new message in the chat.

### ISSUE THREAD

**Issue by thxare** [stackblitz/bolt.new#248]
### Describe the bug

Application Error
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fe (https://bolt.new/assets/components-g8_Fbz61.js:24:33638)
    at np (https://bolt.new/assets/components-g8_Fbz61.js:22:22233)
    at rB (https://bolt.new/assets/_index-BZGIVHL1.js:3:685)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:754
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:743
    at rB (https://bolt.new/assets/_index-BZGIVHL1.js:3:685)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:754
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BZGIVHL1.js:3:743

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lbgmkz

### Steps to reproduce

1. Request or ask for something.
2. Wait until the process completes.
3. Attempt to send a new message in the chat.
4. Encounter the error.

### Expected behavior

I expect to send a message in the chat 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/4f425ddc-f195-42e1-9c48-ca01b9231610)

### Platform

- OS:  macOS
- Browser: Chrome

**Comment by chalovega** [comment]
same for me, both tries: https://bolt.new/~/sb1-fsamf8 and https://bolt.new/~/sb1-veanky

**Comment by samdenty** [comment]
Hey everyone! Sorry for the inconvenience, we're going to track this in https://github.com/stackblitz/bolt.new/issues/260
