### ISSUE TITLE
impossible de fini un projet peut importe le quel 

### ISSUE THREAD

**Issue by roockle** [stackblitz/bolt.new#2480]
### Describe the bug

NotFoundError : échec de l'exécution de « insertBefore » sur « Node » : le nœud avant lequel le nouveau nœud doit être inséré n'est pas un enfant de ce nœud.
    chez ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    chez moi (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-9bxqq4

### Steps to reproduce

Prompt :

"Je souhaite créer un site web moderne de comptabilité nommé ComptaSmartAI avec les fonctionnalités suivantes :

Système d'abonnement avec options flexibles :

Niveau gratuit (Freemium) avec accès aux fonctionnalités de base.
Abonnement mensuel à 9,99 €/mois pour un accès complet.
Abonnement annuel à 49,99 €/an avec une réduction pour un accès complet.
Différents niveaux d'automatisation pour la comptabilité avec un plafond maximum de 9,99 €/mois pour l'IA :
0% (manuel) - Pas d'IA : gratuit.
50% automatisé - Assistance partielle par l'IA à 4,99 €/mois.
75% automatisé - Assistance poussée par l'IA à 7,99 €/mois.
100% automatisé - Automatisation complète par l'IA à 9,99 €/mois.
Fonctionnalités à inclure :

Formulaire d'inscription et de connexion sécurisé.
Tableau de bord interactif pour gérer les revenus, dépenses, et factures.
Génération automatique de rapports financiers (bilan, compte de résultat).
Notifications pour les paiements en retard et déclarations fiscales.
Animation de confettis pour célébrer les inscriptions réussies et les abonnements.
Technologies à utiliser :

Front-end avec Next.js et Tailwind CSS pour un design moderne et réactif.
Back-end avec Node.js et API REST pour gérer l'authentification et les paiements.
Intégration avec Stripe pour gérer les abonnements payants.
Sauvegarde des données sur Amazon S3 avec chiffrement AES-256.

### Expected behavior

un resulta sans black screen de la mort un geste commercial serait aprecier sa fait 2 jours que je casse les dent sur 3 projet ou j'ai depenser mes point

### Screen Recording / Screenshot

![téléchargement](https://github.com/user-attachments/assets/1ee89594-e036-4501-b7d0-51f38b8240d0)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

en tout cas merci c'est quant même énorme pour un pure débutant comme moi vous pouvait me prendre en t'en que testeur si vous voulait au moins les script serons réaliste prompt par apport a des professionnelles

**Comment by Phineas17** [comment]
en tout cas tu n'est pas le seul avec cette erreur de noeuf :
