### ISSUE TITLE
NotFoundError

### ISSUE THREAD

**Issue by jst15** [stackblitz/bolt.new#2484]
### Describe the bug

[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[..................] - preloadMetadata: timing ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] / idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[######............] - idealTree:project: sill ideal[############......] | idealTree:css: sill placeDep ROOT source-map@0.7.4 OK for: @nativescript/webpack@[############......] | idealTree:css: sill placeDep ROOT source-map@0.7.4 OK for: @nativescript/webpack@[##########........] | idealTree:webpack-chain: sill placeDep ROOT deepmerge@4.3.1 OK for: fork-ts-check[##########........] | idealTree:webpack-chain: sill placeDep ROOT deepmerge@4.3.1 OK for: fork-ts-check[##########........] - idealTree:reduce-css-calc: timing idealTree:node_modules/reduce-css-calc Complete[##########........] - idealTree:reduce-css-calc: timing idealTree:node_modules/reduce-css-calc Complete[############......] / idealTree:schema-utils: timing idealTree:node_modules/raw-loader/node_modules/sch[############......] / idealTree:schema-utils: timing idealTree:node_modules/raw-loader/node_modules/sch
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nativescript/firebase@^13.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-15T20_05_14_140Z-debug-0.log

NotFoundError : échec de l'exécution de « insertBefore » sur « Node » : le nœud avant lequel le nouveau nœud doit être inséré n'est pas un enfant de ce nœud.
    chez ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    chez moi (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mrouni

### Steps to reproduce

.

### Expected behavior

.

### Screen Recording / Screenshot

.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60631911,
  "usedJSHeapSize": 51838859,
  "jsHeapSizeLimit": 4294705152
}
Username = Jst
Chat ID = b626befc96ce
```

**Comment by AriPerkkio** [comment]
Hey @jst15, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
