### ISSUE TITLE
prompt is too long: 200241 tokens > 200000 maximum.

### ISSUE THREAD

**Issue by allinwondee** [stackblitz/bolt.new#2485]
### Describe the bug

When using bolt.new, I encounter an error message that says:
prompt is too long: 200241 tokens > 200000 maximum.

This issue arises even when the prompt being sent is very short, consisting of fewer than two sentences. It seems the error is related to the overall project size or context being processed, rather than the actual input length.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-67acgj

### Steps to reproduce

type prompt. 

### Expected behavior

I expected the short prompt to be processed successfully without exceeding the token limit, as the input size itself is well below the maximum limit

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79301438,
  "usedJSHeapSize": 73234358,
  "jsHeapSizeLimit": 2160066560
}
Username = allinwondee
Chat ID = 5f48b8dce9e7
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
