### ISSUE TITLE
always just plane white preview

### ISSUE THREAD

**Issue by Smilerich2** [stackblitz/bolt.new#2487]
### Describe the bug

I have tried using bolt.new with a few different prompts and frameworks. However, I mostly get a plain white preview page with no error message

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-faxnej

### Steps to reproduce

try any prompt

### Expected behavior

i would like to see any Preview. I payed for bold premium..!

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = Smilerich2
Chat ID = 540e82bd1734
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
