### ISSUE TITLE
Cant deploy..

### ISSUE THREAD

**Issue by Experimentusprime** [stackblitz/bolt.new#249]
### Describe the bug

unable to deploy project "sb1-h4ywta" to nelify. 
![Bildschirmfoto 2024-10-08 um 22 59 44](https://github.com/user-attachments/assets/b7d8f7c9-f4b6-4a72-8fe7-1c42316982bd)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-h4ywta

### Steps to reproduce

.

### Expected behavior

.

### Screen Recording / Screenshot

.

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114946057,
  "usedJSHeapSize": 108734209,
  "jsHeapSizeLimit": 4294705152
}
Username = toymail@gmx.ch
Chat ID = 716d270dc4f7
```

### Additional context

Error:
```
Unexpected token 'U', "Unexpected"... is not valid JSON
```

**Comment by samdenty** [comment]
we've just fixed this and made the error messages better
