### ISSUE TITLE
Stuck on Install dependencies and no Preview

### ISSUE THREAD

**Issue by MJDCH09** [stackblitz/bolt.new#2491]
### Describe the bug

I have tried to develop a web application for a vacation itinerary planner and it keeps getting stuck on "Install dependencies". Or it will say it needs to restart and that it's done and now I can see this and this. But I can't. The preview pane stays blank white. I got one itinerary planner to work out great until I added a new feature and then it was like the above. All the others have never been able to even preview anything. Help please? (I wish you guys had a help section somewhere.) Bolt describes this amazing and beautiful planner and then ..... nada. Excited to see and interact with!

### Link to the Bolt URL that caused the error

https://bolt.new/~/nativescript-stackblitz-templates-mu13ga

### Steps to reproduce

Just try to see anything in the preview pane?

### Expected behavior

Everything is noted above in my bug report

### Screen Recording / Screenshot

![tempImageNnUpDp](https://github.com/user-attachments/assets/6ca1afec-cad1-4de7-a28e-e5287c1f73c9)

### Platform

```
Browser name = Safari
Full version = 17.0
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
performance.memory = undefined
Username = MJH09
Chat ID = 4db78a29f684
```

### Additional context

I'm so excited to see this work for me. I have no coding knowledge but a lot of creativity and this seems a match. Just want to see it work because I paid for Pro today. Thanks!!

**Comment by WillCKyle** [comment]
I just got the same exact issue.

Link:
https://bolt.new/~/sb1-5b4zj9

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = WillCKyle
Chat ID = 07548a831f34
```

**Comment by kc0tlh** [comment]
@MJDCH09 @WillCKyle Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!
