### ISSUE TITLE
An unknown error occured while processing the servers response.

### ISSUE THREAD

**Issue by nicolas-geysse** [stackblitz/bolt.new#2496]
### Describe the bug

While playing a lot with it, it explodes...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dp56xv

### Steps to reproduce

Push it to the limit.

### Expected behavior

Not to explode.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 272649775,
  "usedJSHeapSize": 260405835,
  "jsHeapSizeLimit": 4294705152
}
Username = Niko
Chat ID = 7c0a0ed9bdec
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
