### ISSUE TITLE
png file generation not completing

### ISSUE THREAD

**Issue by bvjebin** [stackblitz/bolt.new#250]
### Describe the bug

When scaffolding chrome extensions, it is attempting to generate png files and it is not able to complete it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ph1zy2?ck_subscriber_id=1725833361

### Steps to reproduce

Ask prompt "Create a chrome extension which can read the content of the pages I visit. With the help of openai api, it can convert the contents to simple interactible visual aid using svg, js, css, html and runs it for the user in a popup when the extension is invoked. The svg can be downloaded as a simple self-contained html file"

### Expected behavior

Either skip generating png or complete it or atleast move on to next code generation

### Screen Recording / Screenshot

![Screenshot 2024-10-08 at 2 29 02 PM](https://github.com/user-attachments/assets/3aca67c0-64d8-4f86-ae2e-307a538276f6)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 42939068,
  "usedJSHeapSize": 41708704,
  "jsHeapSizeLimit": 4294705152
}
Username = bvjebin
Chat ID = 8953e238ee76
```

**Comment by endocytosis** [comment]
While we’re committed the success of our users, unfortunately we aren’t equipped to offer one-on-one engineering support for individual coding projects. There are some excellent resources in #678 that others have found helpful in advancing their skills and building complex applications on the platform.
