### ISSUE TITLE
Used Car Stock feed issue 

### ISSUE THREAD

**Issue by LukeInMyEyes** [stackblitz/bolt.new#2500]
### Describe the bug

I'm new to this so I might call things by the wrong name - 

I've been trying to use this stock feed: https://www.easyquote-dcs.co.za/ver6/admin/eqwcfServiceCal/EasyQuoteStockFeed.ashx?Username=EQTESTFEED&Password=1b07c8ef-3d7b-4721-bc82-742ca8618322 

But I keep getting this: DataCloneError: Failed to execute 'postMessage' on 'MessagePort': Symbol() could not be cloned.
   at /.localservice@runtime.d3acb9e1.js:1:16407
   at new Promise (<anonymous>)
   at _0x50fcc3 (/.localservice@runtime.d3acb9e1.js:1:15593)
   at Object.apply (/.localservice@runtime.d3acb9e1.js:1:13545)
   at _0x45ce41 (/.localservice@runtime.d3acb9e1.js:26:34770)
   at _0x3cfe65 (/.localservice@runtime.d3acb9e1.js:26:35484)
   at console.error (/.localservice@runtime.d3acb9e1.js:26:34216)
   at fetchVehicles (/src/components/VehicleInventory.tsx:71:17)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ybelej

### Steps to reproduce

I keep clicking "Fix Problem" 

### Expected behavior

Import the list of used vehicle from the stock feed 

### Platform

Chrome

**Comment by endocytosis** [comment]
Appreciate the feedback! At times, there are programming challenges that are too complex for the LLM to solve and manual intervention is required. Pasting the error message directly into the chat can help at times. You may need to consulting the official documentation for the service you are trying to use. Additionally, this page [here](https://github.com/stackblitz/bolt.new/issues/678) contains a number of insights on using Bolt most effectively. Hope this helps!
