### ISSUE TITLE
getting html embeded instead of error message

### ISSUE THREAD

**Issue by ngsanthosh** [stackblitz/bolt.new#2501]
### Describe the bug

![image](https://github.com/user-attachments/assets/9f42336b-eed4-4199-bb3a-e22cce1668f0)

Should throw error, when tokens are expired, rather it is embedding html

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-edgi7e

### Steps to reproduce

1. Drain your tokens 2. try to enhance the prompt

### Expected behavior

error message directly. or not allowing to enhance prompt, if no tokens are left

### Platform

- OS: , Windows
- Browser:Chrome
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this issue here: #2529.
