### ISSUE TITLE
Issue with importing code from a different branch besides the main branch of a given repository

### ISSUE THREAD

**Issue by Temicruise007** [stackblitz/bolt.new#2502]
### Describe the bug

unable to import code from a different branch of a given public repository. can only import the main branch

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/Temicruise007/milton-frontend/tree/milton-update-2.0?file=src/index.js

### Steps to reproduce

not sure on what to write here

### Expected behavior

my expectation was that every thing would work fine and i would be able to import codes in a different branch of a given public repository into stackblitz and then i should also be able to work with it on bolt.new

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69153041,
  "usedJSHeapSize": 44824721,
  "jsHeapSizeLimit": 2160066560
}
Username = Temicruise007
Chat ID = 666899697306
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Deeper integration with GitHub is an area of ongoing development as is being tracked [here](https://github.com/stackblitz/bolt.new/issues/2367).
