### ISSUE TITLE
My project just disapeared! (from both stackBlitz and Bolt.new)

### ISSUE THREAD

**Issue by TomV** [stackblitz/bolt.new#2503]
### Describe the bug

I was trying to get vite test working, and it was , but as we iterated things blew up (after 3 or 4 hours of iterating) and it's gone.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bbp9pb

### Steps to reproduce

Nothing special, just browser reload after Bolt and Terminal froze for the nth time.

### Expected behavior

project should exist and i should be able to edit it.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 42830636,
  "usedJSHeapSize": 39779480,
  "jsHeapSizeLimit": 4294705152
}
Username = TomV
Chat ID = 52680d63a4e8
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by TomV** [comment]
I seem to have a zip from about an hour before it went "boom" , which is nice!

**Comment by TomV** [comment]
I was able to figure it out - perhaps there were two tabs open, one with the random name ([sb1-bbp9pb](https://bolt.new/~/sb1-bbp9pb)   and one with my renamed version?  I found the other tab, and things are better.  But leaving this as a bug to encourage you to detect this condition and redirect folks on the bad tab to the live tab, or just throw up a big WARNING box, this project was renamed, please check your other tab or open it here (link to the updated project url.)

**Comment by nrgyapp** [comment]
nope , the reason is Bolt / stackblitz is either pushing updates without ever notifying users or they are struggling with capacity

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback! The team is hard at work improving integration with GitHub and version control overall. For now, I would look for your project in the Bolt Collection on StackBlitz by logging into [stackblitz.com](https://stackblitz.com) (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection. From there, you can open the project of interest, develop in StackBlitz, and save your changes. When you return to Bolt, these changes should be reflected when you open the project there. Hope this helps!
