### ISSUE TITLE
The message will be displayed immediately after starting bolt.new

### ISSUE THREAD

**Issue by mitunami** [stackblitz/bolt.new#2506]
### Describe the bug

Immediately after starting bolt.new, the following message will be displayed.

Chat history may be incomplete. This project was last upload outside of Bolt on 11-16-2024 16:28
Failed to save project. You can download your project by clicking this notification

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-z1sday

### Steps to reproduce

Nothing in particular

### Expected behavior

I want you to concentrate on your work

### Screen Recording / Screenshot

![msg](https://github.com/user-attachments/assets/bfa0ea79-7654-4af8-b96c-63371258ef7d)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61362409,
  "usedJSHeapSize": 55523989,
  "jsHeapSizeLimit": 4294705152
}
Username = mitunami
Chat ID = 0690ffdcc944
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2762.
