### ISSUE TITLE
Unable to deploy application

### ISSUE THREAD

**Issue by fanyaji** [stackblitz/bolt.new#2507]
### Describe the bug

Unable to deploy application

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-abench?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

Unable to deploy application

### Expected behavior

Unable to deploy application

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120870330,
  "usedJSHeapSize": 114084386,
  "jsHeapSizeLimit": 2160066560
}
Username = fanyaji@massivue.com
Chat ID = dc384650cfd3
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019.
