### ISSUE TITLE
Error cant get a link

### ISSUE THREAD

**Issue by sashasmeet** [stackblitz/bolt.new#2509]
### Describe the bug

hello. exuse me how can i get a link to my project? i cant do it. i want to open my website on my phone but i dont have a link. can u send me it please?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-89t5dy

### Steps to reproduce

open the link and thats all

### Expected behavior

i want you to share a link please

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 48537804,
  "usedJSHeapSize": 45710084,
  "jsHeapSizeLimit": 2160066560
}
Username = w1wang
Chat ID = 897c58490c24
```

**Comment by endocytosis** [comment]
On your computer, click "Deploy" at the top-right of the page. Bolt will give you a Netlify link and a URL to claim the website in your Netlify account. You can then access this link on your phone. 

Note: Developing in Bolt works best in Chrome and Chromium browsers. Developing on mobile is not supported at this time. 

Hope this helps!

**Comment by sashasmeet** [comment]
but botton deply doesnt work

**Comment by endocytosis** [comment]
Got it! The issue then appears to be with a missing Netlify claim URL. We are aware of this issue and are tracking it here: #2020. Appreciate your patience as improvements continue to be made!
