### ISSUE TITLE
Failed to save project. You can download your project by clicking this notification

### ISSUE THREAD

**Issue by surenganne** [stackblitz/bolt.new#2511]
### Describe the bug

Failed to save project. You can download your project by clicking this notification

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6mts2s

### Steps to reproduce

Whenever we request a new feature development. Just assume that if we ask to update the readme.md file, it's unable to save the changes and getting **"Failed to save project. You can download your project by clicking this notification"** and it's asking us to download the code as a .zip file.

### Expected behavior

It usually saves the code whenever we make any changes

### Screen Recording / Screenshot

<img width="374" alt="Screenshot 2024-11-16 at 3 03 07 PM" src="https://github.com/user-attachments/assets/00ef3c95-ec95-4544-9ff9-39526ea634b9">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking is here: https://github.com/stackblitz/bolt.new/issues/2762.
