### ISSUE TITLE
Page d'aperçu blanc 

### ISSUE THREAD

**Issue by Mamad-hub** [stackblitz/bolt.new#2513]
### Describe the bug

L'écran de Prévisualisation reste blanc malgré les nombreuses tentatives de réparation et de réactualisation. L'IA croit que le problème est reglé, mais ce n'est pas le cas.
<img width="1280" alt="Capture d’écran 2024-11-16 à 10 05 32" src="https://github.com/user-attachments/assets/820df200-f2ba-4e3f-b87d-712594a0dc12">
 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-g7w9vr?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

Allez dans aperçu 

### Expected behavior

J'aimerais simplement pouvoir visualisé correctement et être remboursé des tokkens utiliser pour avoir essayé de réparer ça sans succès. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46984270,
  "usedJSHeapSize": 44681474,
  "jsHeapSizeLimit": 2160066560
}
Username = Mamad-Panda
Chat ID = 0de7e9831942
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
