### ISSUE TITLE
Cannot save project...

### ISSUE THREAD

**Issue by Ndeavr** [stackblitz/bolt.new#2514]
### Describe the bug

failed to save project...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bzvhkd

### Steps to reproduce

modifying code, but not saving!

### Expected behavior

Save project!

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 95355908,
  "usedJSHeapSize": 83236088,
  "jsHeapSizeLimit": 2160066560
}
Username = Ndeavr
Chat ID = e0a134070635
```

**Comment by endocytosis** [comment]
Hi @Ndeavr, 

Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection?

**Comment by Ndeavr** [comment]
yes it works. But I need Bolt.new to work as I am not a programmer.
But something's not right, I spent millions of tokens trying to reconnect,
to debug... I guess you can see that!

**Comment by endocytosis** [comment]
This page [here](https://github.com/stackblitz/bolt.new/issues/678) contains a number of insights on using Bolt most effectively while maximizing token efficiency. At times, if Bolt is unable to auto-fix the issue manual intervention is required to prevent excessive token usage. Hope this helps!
