### ISSUE TITLE
Feature Request: Top Nav & Notification System

### ISSUE THREAD

**Issue by codewithtyler** [stackblitz/bolt.new#2515]
**Is your feature request related to a problem? Please describe:**

Not necessarily a problem with the app per say but more so it's a way to solve the issue of complaints and reports about the app being down. 

**Describe the solution you'd like:**

I'd like an update to the Bolt.new app to add a more formal top nav similar to what's in StackBlitz. The main feature I'm wanting out of this new top nav is a notification system so that we can know when a planned update is coming and know how long the app will be down for. Can even use this system to notify users of things like when a new feature is available or when a preview link to test stuff out is available. This feature could help consolidate your efforts to inform your users on what's going on.

**Describe alternatives you've considered:**

A post in the Discord or post on Twitter when an update is planned to go out and how long it will be down for. I would say a notification on the home page but if the app is down then people won't be able to see that.

**Comment by endocytosis** [comment]
@codewithtyler, agreed. The team is exploring better ways to notify users of planned downtime and upcoming updates - I'll pass this along. Thanks!
