### ISSUE TITLE
 prompt is too long: 208544 tokens > 200000 maximum

### ISSUE THREAD

**Issue by NobleYve** [stackblitz/bolt.new#2520]
### Describe the bug

prompt is too long: 208544 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sxlrzp

### Steps to reproduce

prompt is too long: 208544 tokens > 200000 maximum

### Expected behavior

Allowing the prompt to go through

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105498359,
  "usedJSHeapSize": 88177283,
  "jsHeapSizeLimit": 4294705152
}
Username = Kagoyire Yvette
Chat ID = 5fdbadfe0cbc
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.

**Comment by NobleYve** [comment]
I am still experiencing the same issue. can you solve it or refund?

**Comment by NobleYve** [comment]
Hello Brain,

I am still facing the same problem. Is it going to be fixed and if yes, do
you have a timeline you share with me?

Regards,

Yvette Kagoyire
