### ISSUE TITLE
Bolt is very inconsistent: prompt is too long: 210108 tokens > 200000 maximum

### ISSUE THREAD

**Issue by everspader** [stackblitz/bolt.new#2524]
### Describe the bug

Tokens have been refreshed but I can't use Bolt on a project because the prompt is always too long. This is very inconsistent.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-vnr8vs

### Steps to reproduce

Ask bolt anything

### Expected behavior

I expect bolt to give back any response

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/0f941ef1-3543-4429-aef7-48b2b93173d1)
![image](https://github.com/user-attachments/assets/e060c37e-0fa4-4453-b07e-6b3085744645)

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
