### ISSUE TITLE
Not able to deploy site to Netlify. 

### ISSUE THREAD

**Issue by fatty423** [stackblitz/bolt.new#2526]
### Describe the bug

I am able to make changes to create a prototype and make changes to it.  but I'm not able to delopy it.  The only error i get is the one attached.   Every other site i have built works fine.  this is the only one giving me issues.  
![image](https://github.com/user-attachments/assets/54b1adc8-9d8b-4099-b9bb-1f676d89800b)
![image](https://github.com/user-attachments/assets/03500221-bb5d-4d54-b95b-c2e1b3f074dd)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-c3q6cz

### Steps to reproduce

Click Deploy

### Expected behavior

To receive a netlify link

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 256696272,
  "usedJSHeapSize": 237752480,
  "jsHeapSizeLimit": 4294705152
}
Username = fatty423
Chat ID = 114bef09fa4e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019
