### ISSUE TITLE
The Website Is Not Previewing (Showing a Complete White Screen)

### ISSUE THREAD

**Issue by FilippGofman** [stackblitz/bolt.new#2527]
### Describe the bug

Hi!

I'm experiencing an issue of not loading the websites generated by the AI. All projects where I requested to create websites, ended up with a completely white screen. 

+

There is this error which cannot be fixed by AI:
SyntaxError: The requested module '/node_modules/lucide-react/dist/esm/lucide-react.js?v=b72e983a' does not provide an export named 'Cube

Could you please help me to understand what is the problem because I don't see the visual representation of the websites.

Thank you.

Sincerely,
Filipp

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2jb7mc

### Steps to reproduce

Just type this text into the AI's bar:
"Build a website for my 3D visual agency. It should be creative, modern, unique, having rich colour palette. I want to options of demonstrating my services: where my people (freelancers) will work on client 3D tasks for money. There will be a few subscriptions choices. The website should also have ‘Projects’ page where I’m demonstrating our latest successful works."

After that when everything is ready, press on "Start application" -> you will end up with a white screen for the preview. 
After that, the AI will recognise that there is 1 issue, which I have listed above, and will try to fix it. But, unfortunately, the error will keep appearing.

### Expected behavior

I expected to see the preview for the website at least.

### Screen Recording / Screenshot

![Screenshot (252)](https://github.com/user-attachments/assets/51532d46-fd72-47d9-968b-4b6cb88fb751)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 47683180,
  "usedJSHeapSize": 44163280,
  "jsHeapSizeLimit": 4294705152
}
Username = Filipp004
Chat ID = 44472b7cf666
```

**Comment by benshawuk** [comment]
Same experience here: https://github.com/stackblitz/bolt.new/issues/2486
Not a very good first impression as I literally can't get anything out of bolt other than a blank white screen!

**Comment by leon4u** [comment]
I encountered the same issue yesterday. I described the issue in the dialog box, and it tried its best to solve it, but nothing changed. Around ten minutes later, I asked, "How can I see my web app from my Explorer?" The agent fixed something and showed the web. I think the reason may be: 1. the environment is not set up, and it took longer than you think. 2. it didn't realize what was wrong...

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback! Going to mere this with #1791 where we are tracking this issue.

**Comment by FilippGofman** [comment]
> Hi @FilippGofman,
> 
> If you are willing, could you set your project settings to "Secret (Accessible by URL)" by clicking the lock next to the project title at the top of the screen? This will allow us to investigate further. Thanks!

Sure, I made it.

**Comment by benshawuk** [comment]
FWIW the problem for me is that it doesn't work in Safari on MacOS - I always get the white screen.
Npm cannot start.
But on Google Chrome, it works.
