### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by CemAkcakaya** [stackblitz/bolt.new#2528]
### Describe the bug

Spend more than  100.000 credit however, he couldn't solve very simple problem. If he will goes like this. This might be useless.

I need you to solve this problem maybe give more credits that s/he spend.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6ok1xi

### Steps to reproduce

Spend more than  100.000 credit however, he couldn't solve very simple problem. If he will goes like this. This might be useless.

I need you to solve this problem maybe give more credits that s/he spend.

### Expected behavior

Spend more than  100.000 credit however, he couldn't solve very simple problem. If he will goes like this. This might be useless.

I need you to solve this problem maybe give more credits that s/he spend.

### Screen Recording / Screenshot

Spend more than  100.000 credit however, he couldn't solve very simple problem. If he will goes like this. This might be useless.

I need you to solve this problem maybe give more credits that s/he spend.

### Platform

Spend more than  100.000 credit however, he couldn't solve very simple problem. If he will goes like this. This might be useless.

I need you to solve this problem maybe give more credits that s/he spend.

### Additional context

Spend more than  100.000 credit however, he couldn't solve very simple problem. If he will goes like this. This might be useless.

I need you to solve this problem maybe give more credits that s/he spend.

**Comment by endocytosis** [comment]
Appreciate the feedback! At times, there are problems that are too complex for the LLM to solve and manual intervention is required. Sometimes pasting the error message into the chat can help. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has additional insights on using Bolt most effectively while maximizing token efficiency.
