### ISSUE TITLE
I asked him to add me a matrix animation. He doesn't understand it what I'm saying.

### ISSUE THREAD

**Issue by Rober2092** [stackblitz/bolt.new#2531]
### Describe the bug

Every time I ask for a prompt, he doesn't understand it. There's a lot of issues with the application.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-b26fqd

### Steps to reproduce

hh

### Expected behavior

He's supposed to understand when I ask him to auto matrix animation

### Screen Recording / Screenshot

jhjh

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 131272257,
  "usedJSHeapSize": 105475949,
  "jsHeapSizeLimit": 4294705152
}
Username = Rober2092
Chat ID = d7feead6de3e
```

### Additional context

Did you guys need to order more on this model? It's gray I've been using a lot.

**Comment by endocytosis** [comment]
At times, there are programming challenges that are too complex for the AI to solve and manual intervention is required. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has more insights on using Bolt most effectively while maximizing token usage. Hope this helps!
