### ISSUE TITLE
Claim URL

### ISSUE THREAD

**Issue by FUCKiro** [stackblitz/bolt.new#2533]
### Describe the bug

When I do Deploy, it generates me the project link, but not the for the claim

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-hphadz

### Steps to reproduce

![Screenshot 2024-11-16 alle 18 03 33](https://github.com/user-attachments/assets/d3421b2f-bf40-432e-8819-a556b319444a)

### Expected behavior

When I do Deploy, it generates me the project link, but not the for the claim

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 122783799,
  "usedJSHeapSize": 115112911,
  "jsHeapSizeLimit": 2160066560
}
Username = FUCKiro
Chat ID = 548c355f7d9c
```

**Comment by FUCKiro** [comment]
UPDATE
Solved re asking claim url

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020
