### ISSUE TITLE
Same recurring error and preview not working

### ISSUE THREAD

**Issue by spyderknw** [stackblitz/bolt.new#2535]
### Describe the bug

I have rendered this application no less than three times and continue to get major errors. The preview does not work on my phone and I have uploaded screenshots of the errors. the install command kept coming back as a problem

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1khlpz

### Steps to reproduce

Fix the error

### Expected behavior

For the application to work and be available in preview

### Screen Recording / Screenshot

![Screenshot_20241116_125848_NativeScript Preview](https://github.com/user-attachments/assets/f4b4e9ba-eb98-4d56-8add-556d76878620)
![Screenshot_20241116_125945_NativeScript Preview](https://github.com/user-attachments/assets/34dbb56a-c87d-4022-bb5f-1b8da61e9053)
![Screenshot_20241116_130040_NativeScript Preview](https://github.com/user-attachments/assets/449d06ca-ac8d-4b77-80e6-3b7843c4b3b2)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 147566315,
  "usedJSHeapSize": 128170495,
  "jsHeapSizeLimit": 4294705152
}
Username = spyderknw
Chat ID = 21ddaedd8bf1
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Currently, developing in Bolt is supported in desktop browsers and works best in Chrome and Chromium browsers. At the top-right of the page in Bolt, click Deploy. You will be given a Netlify link that you can then use to view your site on other devices, including mobile. Hope this helps!
