### ISSUE TITLE
Need the ability to go back versions

### ISSUE THREAD

**Issue by rconr007** [stackblitz/bolt.new#254]
### Describe the bug

BOLT changed everything after it was completed and it messed the entire application look and feel as well as other features that were already fixed. meaning I had to start all over again. 
If you had versions then I could of gone back but no you don't have any.
Also the app keeps crashing and asking to resubmit

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nj4nnl

### Steps to reproduce

Asked to replace the original list of items and changes that were already done previously

### Expected behavior

to bring back the list and not change anything else

### Screen Recording / Screenshot

N/A

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88412870,
  "usedJSHeapSize": 79135614,
  "jsHeapSizeLimit": 2172649472
}
Username = rconr007
Chat ID = 5ad657d26dd7
```

**Comment by YaminMECHQI** [comment]
Actually only the Fork works for me !

**Comment by dragsbruh** [comment]
#35 is a similar issue

**Comment by kc0tlh** [comment]
@rconr007  Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
