### ISSUE TITLE
An image from pi

### ISSUE THREAD

**Issue by elzbieta8** [stackblitz/bolt.new#2541]
### Describe the bug

i have built a step where library from pixabay is displaying pictures. Then when i click on a chosen by me picture it opens a graphic editor that is supposed  to load the photo. It doesn't load at all, just all I get is a loading screen. I have tried many commends to get it fixed, and everytime it says that it should work, while in reality it doesnt load a picture into the editor. so i cannot see any pictures. How can I fix it?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kmt5tu

### Steps to reproduce

go to Brand Identity
Company Logo, then Select Logo Icon, and you will be in the editor

### Expected behavior

after i pick an image from pixabay library it should load it into the simple editor for further editing and saving,

### Screen Recording / Screenshot

![github](https://github.com/user-attachments/assets/07d3b118-09e7-4d83-b80e-2a877ea9f6db)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68406978,
  "usedJSHeapSize": 65621126,
  "jsHeapSizeLimit": 4294705152
}
Username = elzbieta8
Chat ID = 9c4ab3edce8e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately we don't have the resources to give programming support to individual projects. Reading the official documentation associated with external services you are using can be beneficial. Additionally, this page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on using Bolt most effectively. Hope this helps!
