### ISSUE TITLE
preview not showing

### ISSUE THREAD

**Issue by Gdataly** [stackblitz/bolt.new#2548]
### Describe the bug

try to view the preview and nothing is not coming up, pls help me

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8xes3m

### Steps to reproduce

just preview it and you will see it

### Expected behavior

show preview

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109307858,
  "usedJSHeapSize": 77809978,
  "jsHeapSizeLimit": 2160066560
}
Username = Gdataly
Chat ID = 3a41c0f57203
```

**Comment by endocytosis** [comment]
Sorry to hear this! This is a known issue and is being tracked here: #1791.

Make sure you don't have any browser extensions running that might interfere with Bolt such as an add blocker.

Hope this helps!

**Comment by Gdataly** [comment]
Dear Team

**Comment by Gdataly** [comment]
Hi

i am unable to access my site for long time now i have tried no no
avail, https://lambent-trifle-9f04a4.netlify.app/, i have developed
this site for a long time i need to access it

regards
treat as urgent
