### ISSUE TITLE
I am quite disappointed

### ISSUE THREAD

**Issue by amsartawi3** [stackblitz/bolt.new#255]
Hi, i have been using bolt for a couple days only and i came to a conclusion that there is something fishy with your tool, here are my thoughts so far:
- The tool has issues, keeps changing code from scratch rather than continuing the code with latest enhancements, resulting in wasting so much time and losing tokens fast, not for sure this is a bug or done on purpose. I was lucky that i saved. the code after losing the latest code of the app at the beginning and had to start from scratch.
- After we reached a proper semi functional app the tool refreshed by itself and now nothing is showing, also causing me to lose more and more tokens.
- Any enhancements i tried to do the tool fixes one issue and messes up loads of other sections/functions. Again, losing so many tokens for no reason.
- I had to provide code and screenshots so many times as the tool kept messing things up again and again.
- The tool doesn't show any history of chats, quite a basic feature 
- Even when i managed to get back to the chat it was not showing the history of the chat, unbelievable.

I feel so scammed, honestly not so good of an experience, V0 is way more stable and worth the investment.

**Comment by superresistant** [comment]
> * The tool has issues, keeps changing code from scratch rather than continuing the code with latest enhancements, resulting in wasting so much time and losing tokens fast, not for sure this is a bug or done on purpose. I was lucky that i saved. the code after losing the latest code of the app at the beginning and had to start from scratch.

I don't see how could a LLM work on a code without sending the code as tokens. 
Don't you separate your work into many files so that you don't have to send the whole project as token every time ?

**Comment by 6huGt** [comment]
i know right

**Comment by kc0tlh** [comment]
@amsartawi3 apologies for the frustrating experience during the beta!

- Ability to lock finished files is coming soon: tracked in #377
- Ability to rollback to prior versions if the AI breaks something has landed: [info here](https://x.com/stackblitz/status/1844839379270836266)
- Chat persistence is coming soon: tracked in #39

**Comment by StartWithWonder** [comment]
I spent hours having to consistently restart the code; it was frust

> Hi, i have been using bolt for a couple days only and i came to a conclusion that there is something fishy with your tool, here are my thoughts so far:
> 
> * The tool has issues, keeps changing code from scratch rather than continuing the code with latest enhancements, resulting in wasting so much time and losing tokens fast, not for sure this is a bug or done on purpose. I was lucky that i saved. the code after losing the latest code of the app at the beginning and had to start from scratch.
> * After we reached a proper semi functional app the tool refreshed by itself and now nothing is showing, also causing me to lose more and more tokens.
> * Any enhancements i tried to do the tool fixes one issue and messes up loads of other sections/functions. Again, losing so many tokens for no reason.
> * I had to provide code and screenshots so many times as the tool kept messing things up again and again.
> * The tool doesn't show any history of chats, quite a basic feature
> * Even when i managed to get back to the chat it was not showing the history of the chat, unbelievable.
> 
> I feel so scammed, honestly not so good of an experience, V0 is way more stable and worth the investment.

same experience..

**Comment by StartWithWonder** [comment]
<img width="1011" alt="Screenshot 2024-11-14 at 12 30 04 PM" src="https://github.com/user-attachments/assets/aef021fe-8882-4130-9532-96d6aef66ece">
This is the instructions to move the names off the white space and onto the radar.. 

I spent nearly 10 hours on this one simple fix that it just couldn't undersand and it kept deleting all my work I almost just cancelled everything not becaue it couldn't fix the bug necdcerlly but becuae it kept changing so many other things I spent hours to fix and then it couldn't rememebr my original foundaitonal work and I kept having to start from scratch . I don't mind the bugs I mind it delete and resruciogng hours of work that is funciong to try to fix somethign that not. 

All the benefits of bolt is not worth keeping a paid memebrship of any kind if I know that hours of work can be lost and unretrivable in seconds. It's just toooooooo risky it's not the lost part it's the waisting my time part.

**Comment by zamizo** [comment]
Brand new user and I wasted most $20 of tokens trying to fix one error that was working fine then all of a sudden not working and no matter how many times I asked it to fix it never fixes, lost my working version too as did not realise it would not save earlier versions, I downloaded a backup zip but there is no way to re-upload the backup

**Comment by Billsu55** [comment]
Very frustrated with bolt.new, same issues here. Every minor change small layout in code it modifies everything and every fix for one thing it keeps breaking another. Something fishy is definettly going on.  If it's really did it on purpose, it could be very large issues fellas. You better be careful bolt team

**Comment by chachew** [comment]
Same, i burned up $20 in a couple hours just trying to get a simple app to work AFTER it suggested that it connect itself to supabase. It obviously integrates with supabase but then cant even add the correct .env variable names after it creates them from the integration. I have to constantly rename .env variable names because it likes to either rename them or just ignore them all together and just hardcode the values in the nuxt.config.ts file. At first glance bolt.new looked awesome and Theo keeps touting it(im sure he has money at stake in the company). But after getting nowhere, losing $20 and losing a few hours, i canceled the subscription...Looks good at first but its no where near production ready, especially for the price.

**Comment by StartWithWonder** [comment]
Hi,

Based on my last post, I owe the Bolt team an apology. I was wrong. My previous comment had merit, but so does Bolt's use case. After spending a significant amount of time working with Bolt, I realized that I just didn’t understand how to “talk to Bolt.”

Basically, you really have to learn how to work with Bolt. I’m pleased to say that I’ve increased my membership and have built applications on Bolt worth over $50K. If anyone is interested in learning about some of the techniques and things I’ve used, I’d be happy to share them in this post.

That said, I do feel that I owe the Bolt team a sincere apology.

#boltisincredible
