### ISSUE TITLE
not giving claimable netlify link

### ISSUE THREAD

**Issue by iggypcnfsky** [stackblitz/bolt.new#2550]
### Describe the bug

after multiple deployment attempts, bolt is not providing link to claimable netlify, making it impossible to get it up and running quickly

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rjcngq

### Steps to reproduce

deploy 
see that it's not providing claimable link

### Expected behavior

provide claimable link to netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 97976600,
  "usedJSHeapSize": 78901660,
  "jsHeapSizeLimit": 4294705152
}
Username = iggypcnfsky
Chat ID = efdeabc2314d
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue and we are tracking it here: #2020.
