### ISSUE TITLE
 prompt is too long: 201012 tokens > 200000 maximum

### ISSUE THREAD

**Issue by TriAlliance** [stackblitz/bolt.new#2551]
### Describe the bug

I am constantly getting this error for small prompts to resolve fixes in the app.  Is it because the size of the app is now exceeding the limits of the system? 
<img width="1443" alt="Screenshot 2024-11-17 094553" src="https://github.com/user-attachments/assets/bcd1c295-9ee1-4afa-b5d7-a902f4f604ed">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-p4vw3k

### Steps to reproduce

1. I copy an error into the as a prompt. 
2. Hit enter,
3. It comes back with the "prompt is too long: 201012 tokens > 200000 maximum"

### Expected behavior

Bolt would normally easily fix this issue in this scenario.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 97781753,
  "usedJSHeapSize": 94812073,
  "jsHeapSizeLimit": 4294705152
}
Username = TriAlliance
Chat ID = 27b16d83e807
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Yes, this is likely due to the size of the application. This issue, along with potential workarounds, is being tracked here: #1322.
