### ISSUE TITLE
Community Manager

### ISSUE THREAD

**Issue by Mimix-13** [stackblitz/bolt.new#2552]
### Describe the bug

a plusieurs reprise, il s'affiche le message ci joint en photo. je suis dans l'obligation de sortir et recommencer. cela consomme aussi des jetons.
![Capture bolt bug](https://github.com/user-attachments/assets/5376daac-1ca0-49aa-92a8-30c208d2b9fd)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-twhj9h

### Steps to reproduce

j'ai demandé une modification pour que je puisse transformer les devis en factures. l'onglet factures est vide et l'onglet paramêtre aussi.

### Expected behavior

j'attendais qu'il réalise les modifications demandées

### Screen Recording / Screenshot

![Capture bolt bug](https://github.com/user-attachments/assets/67f9764b-5a6d-48cc-958c-0824a03621bb)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52463738,
  "usedJSHeapSize": 49662134,
  "jsHeapSizeLimit": 2172649472
}
Username = MimixIA
Chat ID = 007475c6f888
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this issue here: #2556.
