### ISSUE TITLE
Preview isnt working

### ISSUE THREAD

**Issue by cmstarks** [stackblitz/bolt.new#2565]
### Describe the bug

The preview isn't working and I bought your service and i haven't been able to preview anything. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qca7da

### Steps to reproduce

I added the prompt about 7-8 times in different ways.. i tried adding a file, I tried pasting it all in, some of it, just a paragraph and the proeview will not generate 

### Expected behavior

It should show the preview 

### Platform

```
Browser name = Safari
Full version = 16.6
Major version = 16
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
performance.memory = undefined
Username = crystalstarks@me.com
Chat ID = 7b5ffa4cb693
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
