### ISSUE TITLE
Installing Dependencies is still not working.

### ISSUE THREAD

**Issue by RongWroom** [stackblitz/bolt.new#2570]
### Describe the bug

I thought I would sign up to premium to see if I could get anymore out of this tool but alas, I was thwarted.
Is it worth me just getting a refund for now and coming back when it's all working again? I see others using it for free and it's working for them but I'm stuck at this same spot everyday bleeding tokens.

I'll definitely come back to it because I'm really enjoying it when it works and it's serving as a great distraction right now. But it's just frustrating like this.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ijhwvv

### Steps to reproduce

Starting any project.

### Expected behavior

Show me something, code, make me rich

### Screen Recording / Screenshot

<img width="526" alt="Screenshot 2024-11-17 at 08 09 07" src="https://github.com/user-attachments/assets/e1d6ad42-ba2f-442b-9932-d6f21bd55fe6">

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = WrongRoom
Chat ID = 227f58997ef7
```

**Comment by nfactorialco** [comment]
Same boat here. I use up all tokens just debugging. I'm going to be trying out Cursor and Windsurf now.

**Comment by RongWroom** [comment]
Been playing with Windsurf today. LOVE IT!I actually wouldn’t mind not having the preview window and just opening it in a browser, but I can’t even seem to get things to load at the moment. There must be something going on. Hopefully just a couple of bugs to iron out.On 17 Nov 2024, at 15:25, nfactorial labs ***@***.***> wrote:﻿
Same boat here. I use up all tokens just debugging. I'm going to be trying out Cursor and Windsurf now.

**Comment by nfactorialco** [comment]
Windsurf is pretty good at debugging build or compile errors, literally copy the entire error string into the into the Cascade AI prompt and it will reason about and resolve each generate error. I had similar challenge earlier and it resolve it pretty well. No tokens eaten up troubleshoot unlike Bolt :)

**Comment by RongWroom** [comment]
Aye! Give it time. The day is still young in tech. I’m sure Bolt will come out on top in no time.What I loved about Windsail is you can see the “agent like” conversation it has with myself when it found and correct its own errors.The way it improved the look of my site too is immense! (P.s. no idea what I’m doing coding and I’m halfway through a website front end build in a week) On 17 Nov 2024, at 17:23, nfactorial labs ***@***.***> wrote:﻿
Windsurf is pretty good at debugging build or compile errors, literally copy the entire error string into the into the Cascade AI prompt and it will reason about and resolve each generate error. I had similar challenge earlier and it resolve it pretty well. No tokens eaten up troubleshoot unlike Bolt :)

**Comment by kc0tlh** [comment]
@RongWroom @nfactorialco Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!
