### ISSUE TITLE
prompt is too long: 207319 tokens > 200000 maximum

### ISSUE THREAD

**Issue by karoliang** [stackblitz/bolt.new#2571]
### Describe the bug

Your prompt is too long. How can I help you reduce its length while maintaining its core functionality?

prompt is too long: 207319 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4dhc8q

### Steps to reproduce

trying to deploy but hitting the issues

### Expected behavior

deploy

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59381919,
  "usedJSHeapSize": 57505319,
  "jsHeapSizeLimit": 4294705152
}
Username = karoliang
Chat ID = d464bc596d55
```

**Comment by ragsntatters** [comment]
annoying ay, been the case for like a week now

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1322.
