### ISSUE TITLE
Regularly receiving error "This message didn't complete its response." 

### ISSUE THREAD

**Issue by newoldrelic** [stackblitz/bolt.new#2574]
### Describe the bug

When Bolt is building code for me today, I've been regularly getting the error "This message didn't complete its response." and it hangs mid-way through building or creating the code. 

And I think my tokens are still being used each time I try, so I've stopped trying for now. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-h9wt4v

### Steps to reproduce

intermittent, but regular enough right now. after entering any prompt I receive the error and the code stops building. 

### Expected behavior

Build hangs, with the error "This message didn't complete its response." 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92863492,
  "usedJSHeapSize": 72547788,
  "jsHeapSizeLimit": 4294705152
}
Username = newoldrelic
Chat ID = 354677dbcc46
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1073.
