### ISSUE TITLE
Too many incomplete messages in last 24h...

### ISSUE THREAD

**Issue by AncientRow2816** [stackblitz/bolt.new#2575]
### Describe the bug

Too many incomplete messages in last 24h...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u9yjp8

### Steps to reproduce

Adding Firebase

### Expected behavior

To complete message/coding
<img width="1501" alt="Screenshot 2024-11-17 at 10 57 58 AM" src="https://github.com/user-attachments/assets/1206b70a-6865-4bb3-8f6c-9f6ebab3425c">

### Platform

```
Browser name = Chrome
Full version = 127.0.0.0
Major version = 127
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 121353836,
  "usedJSHeapSize": 113451624,
  "jsHeapSizeLimit": 4294705152
}
Username = AncientRow2816
Chat ID = 3ee88471c1a9
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1073.
