### ISSUE TITLE
i do upload photo to my site. but it doesnt work. so there is no pictures in my site

### ISSUE THREAD

**Issue by sashasmeet** [stackblitz/bolt.new#2578]
### Describe the bug

i cant see pictures. bot add them but they are not mine.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qqbnvf

### Steps to reproduce

please check. this but works incorrectly

### Expected behavior

i wish it ll work better

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65165196,
  "usedJSHeapSize": 57389200,
  "jsHeapSizeLimit": 2160066560
}
Username = w1wang
Chat ID = 0fdbd634b916
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Bolt currently does not support image uploads to the file system. We are aware of this issue and are tracking it here: #1809. At this time, open your project in StackBlitz (click the "Open in StackBlitz" button at the top-right of the page) to upload images to the StackBlitz file system and continue development of your project.
