### ISSUE TITLE
ne link sent

### ISSUE THREAD

**Issue by arthurplatkutnowska** [stackblitz/bolt.new#2581]
### Describe the bug

it says "this is the link to claim" but there is no link and now more than 1M credit use because it keep not sending it

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bt1mgh

### Steps to reproduce

bug

### Expected behavior

bug

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 131650700,
  "usedJSHeapSize": 115039220,
  "jsHeapSizeLimit": 2160066560
}
Username = arthurpp
Chat ID = 8d14efed034e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020.

**Comment by arthurplatkutnowska** [comment]
There is also a lot of time it keep saying same things but it just using
credit for nothing. Do you offer new credit for those bug ?

**Comment by arthurplatkutnowska** [comment]
??

Once we pay we don’t receive 150k credit anymore.

This is not a good way to treat your client to not answer. It is normal to
have bug but to make it pay to customers this is not good

**Comment by endocytosis** [comment]
Refund requests are handled through hello@stackblitz.com.
