### ISSUE TITLE
cant delete chat history

### ISSUE THREAD

**Issue by ragsntatters** [stackblitz/bolt.new#2583]
### Describe the bug

ive tried deleting all chats because it is causing a max token error. The chats don't get deleted and reappear. I've tried in a brand new browsers with no cache but to no avail. bolt is unusable and better not be stealing tokens, this is getting ridiculous.

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-vvcafh

### Steps to reproduce

fix the app

### Expected behavior

a usable platform

### Platform

```
Browser name = Chrome
Full version = 132.0.0.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59907044,
  "usedJSHeapSize": 57888716,
  "jsHeapSizeLimit": 4294705152
}
Username = ragsntatters
Chat ID = fb67c753ba2e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this feature request here: #2698.
