### ISSUE TITLE
Claim Urls

### ISSUE THREAD

**Issue by hellobubles1233** [stackblitz/bolt.new#2584]
### Describe the bug

Keep asking to provide a claim url but loops to the same answer even if asked for aurl direclty

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rhewed

### Steps to reproduce

Mutliple rewrites and deployments

### Expected behavior

Provide claim url

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100554312,
  "usedJSHeapSize": 82826032,
  "jsHeapSizeLimit": 4294705152
}
Username = hellobubles1233
Chat ID = ad7f6077c04e
```

**Comment by endocytosis** [comment]
Hi @hellobubles1233 

Just curious, did you click the Deploy button at the top right of the page before requesting the claim URL?

**Comment by hellobubles1233** [comment]
Yes, no longer provided the url even after specifically asking for a url and alerting that there then was no url in the message at all it keeps building but pointing to the url of a previous deployment which was not updated..

**Comment by endocytosis** [comment]
Got it, appreciate the additional information! We are aware of this issue and are tracking it here: #2020.
