### ISSUE TITLE
keep telling : This message didn't complete its response.

### ISSUE THREAD

**Issue by jiangyan** [stackblitz/bolt.new#2588]
### Describe the bug

let's build a web app to generate images by prompts, like the screenshot does, user can input prompts to generate images by AI, all generated images will be listed below the input box, make it modern and professional

when it builds, it keeps telling the same error: This message didn't complete its response.

![image](https://github.com/user-attachments/assets/a98d7665-2a54-4fe4-a53b-62e04e373af1)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kpgmsc

### Steps to reproduce

![image](https://github.com/user-attachments/assets/a98d7665-2a54-4fe4-a53b-62e04e373af1)

### Expected behavior

when it builds, it keeps telling the same error: This message didn't complete its response.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/a98d7665-2a54-4fe4-a53b-62e04e373af1)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 98667071,
  "usedJSHeapSize": 76559035,
  "jsHeapSizeLimit": 4294705152
}
Username = jiangyan
Chat ID = 034e88171ee4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.
