### ISSUE TITLE
Something went wrong whilst creating your site on Netlify

### ISSUE THREAD

**Issue by BigDataEd** [stackblitz/bolt.new#259]
### Describe the bug

I apologize for the confusion. Let me check the deployment status to see what went wrong.

Something went wrong whilst creating your site on Netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wvjnpw

### Steps to reproduce

Deploy Florida Tag Agency App to Netlify

npx vite build
Deploy to netlify

### Expected behavior

wait for the deployment to complete. Once it's done, provide you with the deployment status and the URL where your application is hosted.

### Screen Recording / Screenshot

![Screenshot (337)](https://github.com/user-attachments/assets/815c3362-e1bd-4b0b-a2aa-bc7481fc600c)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100132311,
  "usedJSHeapSize": 94331919,
  "jsHeapSizeLimit": 2172649472
}
Username = Dektall
Chat ID = 2d1b50401a0d
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
