### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by jim7207** [stackblitz/bolt.new#2590]
### Describe the bug

I'm spending lots of tokens and time asking bolt to fix a white/blank preview screen. seems like vite config isn't properly configured. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qdb2xm

### Steps to reproduce

My first prompt yielded this. Then I made a small change to the order of the fields in the UI and it's back to white. 

### Expected behavior

I expect preview to render the UI.

### Screen Recording / Screenshot

<img width="2052" alt="Screenshot 2024-11-17 at 8 47 16 AM" src="https://github.com/user-attachments/assets/289bd6f4-8f11-403d-b766-fc0c2dde243c">

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = jim7207
Chat ID = 874721792d5a
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
