### ISSUE TITLE
Mistaken switching from code generation into conversation

### ISSUE THREAD

**Issue by wforbes** [stackblitz/bolt.new#26]
### Describe the bug

On my first prompt to the system I requested that it generates a todo app (like your vite conf presentation), but my prompt included more specific details about what deps/db to use. At a certain point near the end of the generation process it suddenly switched into generating the code as a conversation response to me, rather than into the editor.

![Screenshot 2024-10-03 231610](https://github.com/user-attachments/assets/76ff6096-c530-484e-be5c-cd03f9d29e9f)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jwuwic

### Steps to reproduce

1. Prompt the AI with the following text:
"Please create a todo list web app that uses nextjs framework, tailwindcss and daisy ui for styling and ui, and next-auth for a credential based authentication system. please add mongodb calls with mongoose for data persistence ( these data calls can be mocked if you dont have access to a running mongodb instance). Please include a landing page with mock pricing model, and an option to sign up and login on an auth page. we will leave payment integration out for now and assume an unlimited free tier of features. Successful signup or login should bring the user to a dashboard that includes the todo app functionality"
2. Observe generation of code begin, and at some point switch over to inputting the code into a conversation response. Code ends and it includes the npm commands to run the app. After that, it's intended response follows in the chat.
3. Describing the issue to it and asking it to fix the problem results in a message "There was an error processing your request" at the bottom of the chat thread.

### Expected behavior

Bolt is able to use a specific prompt to fully generate the initial project described in it, without switching code output over to the conversation message. Conversation message response should only begin after the code has been generated and any terminal commands have been run by the LLM.

### Screen Recording / Screenshot

Multiple screenshots used to display the chat conversation as it is scrolled down:

![image](https://github.com/user-attachments/assets/196fbf7e-8c98-4a2a-ad4e-f22145ccc1b8)

... then it begins code generation:

![image](https://github.com/user-attachments/assets/e44d6dc2-10f8-4ec2-a632-13150ee0f17e)

![image](https://github.com/user-attachments/assets/cd9c327b-ba43-4516-beef-940c94899adc)

![image](https://github.com/user-attachments/assets/28137577-b1e0-4ff1-a6e2-15680a2415b9)

![image](https://github.com/user-attachments/assets/b2be5a21-dd74-46d6-84c8-d2fbcedafd67)

![image](https://github.com/user-attachments/assets/df0154ab-28e0-4cea-8328-837cb2b38c82)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63235043,
  "usedJSHeapSize": 58545751,
  "jsHeapSizeLimit": 4294705152
}
Username = wforbes
Chat ID = fbb60d50fe0f
```

### Additional context

Message:
```
: null };
}

export async function connectToDatabase() {
  if (cached.conn) {
    return cached.conn;
  }

  if (!cached.promise) {
    const opts = {
      bufferCommands: false,
    };

    cached.promise = mongoose.connect(MONGODB_URI!, opts).then((mongoose) => {
      return mongoose;
    });
  }

  try {
    cached.conn = await cached.promise;
  } catch (e) {
    cached.promise = null;
    throw e;
  }

  return cached.conn;
}
</boltAction>

<boltAction type="file" filePath="models/User.ts">
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Please provide a name'],
    maxlength: [60, 'Name cannot be more than 60 characters'],
  },
  email: {
    type: String,
    required: [true, 'Please provide an email'],
    unique: true,
    lowercase: true,
    trim: true,
  },
  password: {
    type: String,
    required: [true, 'Please provide a password'],
    minlength: [6, 'Password should be at least 6 characters long'],
  },
}, { timestamps: true });

export default mongoose.models.User || mongoose.model('User', UserSchema);
</boltAction>

<boltAction type="file" filePath="models/Todo.ts">
import mongoose from 'mongoose';

const TodoSchema = new mongoose.Schema({
  text: {
    type: String,
    required: [true, 'Please provide a todo text'],
    maxlength: [300, 'Todo text cannot be more than 300 characters'],
  },
  completed: {
    type: Boolean,
    default: false,
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
}, { timestamps: true });

export default mongoose.models.Todo || mongoose.model('Todo', TodoSchema);
</boltAction>

<boltAction type="file" filePath="components/auth-provider.tsx">
'use client';

import { SessionProvider } from 'next-auth/react';

export default function AuthProvider({ children }: { children: React.ReactNode }) {
  return <SessionProvider>{children}</SessionProvider>;
}
</boltAction>

<boltAction type="shell">
<command>npm install && npm run dev</command>
</boltAction>
</boltArtifact>

I've created a todo list web app using Next.js, Tailwind CSS, DaisyUI, and NextAuth for authentication. The app includes a landing page with a mock pricing model, sign-up and login functionality, and a dashboard with todo list management.

Here's a summary of the changes and additions:

1. Updated `package.json` with necessary dependencies.
2. Modified `tailwind.config.ts` to include DaisyUI and custom theme settings.
3. Created authentication pages (`signin` and `signup`) and API routes.
4. Implemented a dashboard page with todo list functionality.
5. Added API routes for todo CRUD operations.
6. Created MongoDB models for User and Todo.
7. Set up database connection utility.
8. Added an AuthProvider component for Next-Auth integration.

The app now has the following features:

- Landing page with mock pricing model
- User authentication (sign up and login)
- Todo list management (add, toggle, delete todos)
- Responsive design using Tailwind CSS and DaisyUI components

To run the application, make sure to set up the `MONGODB_URI` environment variable in a `.env.local` file. You'll also need to add `NEXTAUTH_SECRET` for NextAuth to work properly.

The development server is now running. You can start testing the application by opening the provided local server URL in your browser.
```

**Comment by wforbes** [comment]
Follow up: I attempted 3 times to ask it to regenerate the ./lib/db.ts file once the "There was an error processing your request" message disappeared. The result was it appeared to correctly regenerate that ./lib/db.ts file.. however as soon as it was done the code file instantly reverted back to the original incomplete state.


https://github.com/user-attachments/assets/af1626a3-c37b-4003-8d33-3e0f5bcacfa0

**Comment by wforbes** [comment]
> Follow up: I attempted 3 times to ask it to regenerate the ./lib/db.ts file once the "There was an error processing your request" message disappeared. The result was it appeared to correctly regenerate that ./lib/db.ts file.. however as soon as it was done the code file instantly reverted back to the original incomplete state.
> 
>  2024-10-03_23-29-09.mp4

This instance of the issue was solved by prompting it to instead create a new database connection file that would serve the same purpose as ./lib/db.ts and leave the original file alone for now. Exact prompt:
"The problem is still persisting. Instead, could you please generate a new database file that will serve the same purpose as ./lib/db.ts and generate that code in the new file while leaving ./lib/db.ts alone for now?"

I hope that this report can help give insight into the issue of Bolt.new switching between code generation and chat response output, then the lock-up on the incomplete file it stopped generating in. I will stop commenting here now. Thanks for reading, I understand all tools are imperfect and I very much appreciate all your efforts on the project so far. Cheers!

**Comment by dragsbruh** [comment]
Similar issue here:

![Screenshot 2024-10-04 211414](https://github.com/user-attachments/assets/fae81201-ccfa-42a7-8dab-c92939da9ad8)
![Screenshot 2024-10-04 211400](https://github.com/user-attachments/assets/ace0fc3f-bcc7-4a2b-84ac-355afeffc677)
![Screenshot 2024-10-04 211349](https://github.com/user-attachments/assets/43f5f3f9-45be-4ad7-9aaf-e6867ae1a703)

**Comment by fasakinhenry** [comment]
I had same issue too. I hope it is solved

**Comment by fasakinhenry** [comment]
@wforbes How did you add video to that comment though?

**Comment by wforbes** [comment]
> @wforbes How did you add video to that comment though?

The 'Paste, drop, or click to add files' button below comment text input box allows for adding video files. I recorded it with OBS Studio app with small resolution setting. Another option you can consider is ScreenToGif which creates animated gifs from your screen.

**Comment by Nemikolh** [comment]
Hey everyone! Thanks a lot for the report! :smiley: 

We're tracking this issue internally and will let you know when we have a fix in place.

**Comment by fasakinhenry** [comment]
> > @wforbes How did you add video to that comment though?
> 
> The 'Paste, drop, or click to add files' button below comment text input box allows for adding video files. I recorded it with OBS Studio app with small resolution setting. Another option you can consider is ScreenToGif which creates animated gifs from your screen.

Thanks a lot man 🙌❤️👌🚀

**Comment by Nemikolh** [comment]
We have deployed a fix for this issue! It should work as expected now. :tada: 

If you run into more issues, feel free to open a new one! :raised_hands: 

For users still seeing AI messages into files, we're tracking this issue under #24
