### ISSUE TITLE
erro t

### ISSUE THREAD

**Issue by msant7708** [stackblitz/bolt.new#2601]
### Describe the bug

![image](https://github.com/user-attachments/assets/39cb4402-40fb-4724-83c7-3ae7f343c4cf)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pwtaxv

### Steps to reproduce

![image](https://github.com/user-attachments/assets/1c89436b-75bb-4cdd-9238-146452e8bb29)

### Expected behavior

![image](https://github.com/user-attachments/assets/22d2d669-e85e-466c-845d-e5f487d50aad)

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c38bbd19-6d04-446d-941e-ecbc7185a0c5)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78323110,
  "usedJSHeapSize": 74738870,
  "jsHeapSizeLimit": 2160066560
}
Username = msant7708
Chat ID = a8c041f705e3
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue with the AI model’s context window size and is being tracked here: #1322.
