### ISSUE TITLE
preview stays blank/white

### ISSUE THREAD

**Issue by luke8800gts** [stackblitz/bolt.new#2603]
### Describe the bug

preview stays blank/white

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-slnfzq

### Steps to reproduce

Go to preview tab, AI says it start the sever already

### Expected behavior

show the programmed page

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = luke8800gts
Chat ID = 14f288f9025d
```

**Comment by ragsntatters** [comment]
i find that if i then go into the terminal and put in the run command like npm run dev it works. usually it'll show the command with a > in the chat window if it hasnt run it itself

**Comment by endocytosis** [comment]
Hi all, 

Yes, manually running "npm run dev" at times can resolve the issue. We are aware of this issue and are tracking it here: #1791. Appreciate your patience as improvements continue to be made!
