### ISSUE TITLE
deployment site issues

### ISSUE THREAD

**Issue by axewood-kat** [stackblitz/bolt.new#2609]
### Describe the bug

i can't seem to make bolt deploy to an existing site, it keeps deploying to new sites and is inconsistent in generating retrieval urls to those newly generated sites.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dkedxh

### Steps to reproduce

deploy to existing site with site name and site id provided

### Expected behavior

deployment to site consistent with the details provided

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64513786,
  "usedJSHeapSize": 57817482,
  "jsHeapSizeLimit": 4294705152
}
Username = axewood-kat
Chat ID = 85eabf40dcab
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Continually deployment to a claimed Netlify domain is a known feature request and is being tracked here: #49. In the meantime, you can download your project (Download button at the top-right) and manage deployment manually. 

Tighter [GitHub integration](https://github.com/stackblitz/bolt.new/issues/2367) is also underway which should resolve many of these issues. We appreciate your patience as improvements continue to be made!

**Comment by Labhk** [comment]
For now, I've build this web tool for just this issue, previously using script on local now its a website much easy, enjoy
https://boltsync.mystify.tech/
https://www.youtube.com/watch?v=IneFM6ViV8s
