### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by manyyventures** [stackblitz/bolt.new#2610]
### Describe the bug

I deployed the build to Netlify and claimed the project. Then proceeded to update the site name (Netlify URL) and connect a custom domain but now when I deploy in Bolt it creates a new Netlify site meaning there's no way for me to update the thing I just built with the tool that built it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aobpqg

### Steps to reproduce

1. Deploy build
2. Update details of site in Netlify
3. Connect a custom domain
4. Proceed to continue building
5. Deployment creates new Netlify site rather than pushing updates to the original site

### Expected behavior

Bolt should be connected to a Netlify site based on an ID not a site name and that way you can continue to make changes and push updates to the same site regardless of whether the site name (and Netlify URL) has changed or if a custom domain has been connected. A new Netlify site should only be created when that has been explicitly requested.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93603101,
  "usedJSHeapSize": 90085981,
  "jsHeapSizeLimit": 4294705152
}
Username = manyyventures
Chat ID = cdadca68a10a
```

### Additional context

So many tokens are wasted on Bolt saying it's doing something but the result not actually matching what it believes it has done. You get stuck in circles requesting the same thing over and over with no change. If something can't be done it should tell you rather than spending tokens.

**Comment by endocytosis** [comment]
Appreciate the feedback and apologies for the frustration here! We are aware of this issue regarding a custom Netlify domain and are tracking it here: #49. 

In the meantime, you can download your project using the download button in the top-right and manage deploys manually. Better integration with custom domains and GitHub overall is an area the team is hard at working improving. We appreciate your patience!

**Comment by manyyventures** [comment]
Hi Brian,

Thanks for your reply. Is there a rough ETA? I’m not confident and a little
overwhelmed with the work arounds being suggested to solve my current
difficulties so I’m very desperate to be able to update my live app with
Bolt.

Cheers,
Dillon.

**Comment by etheuer** [comment]
hello, why was the issue closed? I am experiencing the same issue. What is the solution?
