### ISSUE TITLE
the preview appears white

### ISSUE THREAD

**Issue by Chochipols** [stackblitz/bolt.new#2614]
### Describe the bug

![bolt new foto error](https://github.com/user-attachments/assets/7059ea1a-0c4e-45c9-a15b-79dd29416b28)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ouapsq

### Steps to reproduce

when I ask for any application

### Expected behavior

do what I ask

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!
