### ISSUE TITLE
Probelem with the app 

### ISSUE THREAD

**Issue by brahim141** [stackblitz/bolt.new#2618]
### Describe the bug

a chaque fois que je lui demande quelque chose elle fonctionne pas Erreur d'application
NotFoundError : échec de l'exécution de « insertBefore » sur « Node » : le nœud avant lequel le nouveau nœud doit être inséré n'est pas un enfant de ce nœud.
    chez ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    chez moi (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401) cest ca qui maffiche

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qbdrtp

### Steps to reproduce

Erreur d'application
NotFoundError : échec de l'exécution de « insertBefore » sur « Node » : le nœud avant lequel le nouveau nœud doit être inséré n'est pas un enfant de ce nœud.
    chez ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    chez moi (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    à kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    chez Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Expected behavior

jai perdu 1m500000 tokens je veux un remboursement

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/b43ddd05-5f3d-4990-9685-b9f688b5d489)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 41706052,
  "usedJSHeapSize": 39629584,
  "jsHeapSizeLimit": 2160066560
}
Username = brahim141
Chat ID = effad5c7c1ba
```

**Comment by AriPerkkio** [comment]
Hey @brahim141, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
