### ISSUE TITLE
NOT ABLE TO INSTALL NPM DEPENDENCIES

### ISSUE THREAD

**Issue by ZIZOU066** [stackblitz/bolt.new#2620]
### Describe the bug

I don't know what is the problem 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1pmnva

### Steps to reproduce

I don't know

### Expected behavior

I want to see a preview 

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = Zizou066
Chat ID = e1e0ff8d8e3c
```

**Comment by endocytosis** [comment]
Bolt is not compatible with Safari as described here: #2796. Continue developing in Chrome for best performance.
