### ISSUE TITLE
Failing to estimate registration cost

### ISSUE THREAD

**Issue by geeAGI** [stackblitz/bolt.new#2623]
### Describe the bug

We are now test registering ens subnames but stock in spite of trial fixes. The issue is the correct code to estimate the registration cost before the transaction completes. If not estimated correctly, the transaction cant complete.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zm57wh

### Steps to reproduce

1. to search box
2. search a name johnny
3. trigger registration
4. nototification of failure pops up

### Expected behavior

Successful registration of subname onchain.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88380556,
  "usedJSHeapSize": 82110996,
  "jsHeapSizeLimit": 4294705152
}
Username = w3w
Chat ID = a946cfdfb521
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times, there are programming challenges that are too complex for the AI to solve. In these cases, consulting the official documentation and manual intervention is required. This page has a number of insights on continuing to developed your project: #2310. Hope this helps!

**Comment by geeAGI** [comment]
Brian/Guys...this response is dangerous for a new project but let me
worry about things I can control.
*adrian.w3w.eth*
