### ISSUE TITLE
Install dependencies hangs

### ISSUE THREAD

**Issue by techwardbound** [stackblitz/bolt.new#2628]
### Describe the bug

I created an application and had two instructions "npm install" and "npm run dev". However, on issuing "npm install" the "Install dependencies" appears, no errors, but the application does not progress beyond the "install dependencies"

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dydays

### Steps to reproduce

1. npm install
2. npm run dev

### Expected behavior

This is my first execution of the code so I'm not quite sure what is expected. I'm expecting the app to request and image to scan so that it can breakdown and identify individual objects in the the image.

### Screen Recording / Screenshot

![Screenshot 2024-11-18 at 1 02 24 PM](https://github.com/user-attachments/assets/1b50776d-5585-48f5-a093-6a5e44db895b)

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = techwardbound
Chat ID = b17ce8709490
```

**Comment by techwardbound** [comment]
Found out more. I've done some additional attempts but the system continues to have problems. Install is not hanging anymore, though it does take a while to terminate. I've looked into the logs and it is failing at an attempt to connect to my environment.... I think:
   @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-1k8l17eo.w-corp-staticblitz.com/blitz.d3acb9e1.js:40:22706
I've attached the log file.
    The error appears at time 50 to 56:

> 50 verbose stack captureLargerStackTrace2@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-1k8l17eo.w-corp-staticblitz.com/builtins.ddb8d84d.js:101:5336
> 50 verbose stack NodeError@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-1k8l17eo.w-corp-staticblitz.com/builtins.ddb8d84d.js:101:4151
> 50 verbose stack ClientRequest@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-1k8l17eo.w-corp-staticblitz.com/builtins.ddb8d84d.js:3:2594
> 50 verbose stack construct@[native code]
> 50 verbose stack @
> 50 verbose stack Promise@[native code]
> 50 verbose stack _0x168309@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-1k8l17eo.w-corp-staticblitz.com/blitz.d3acb9e1.js:40:21354
> 50 verbose stack @
> 50 verbose stack h@
> 50 verbose stack @
> 50 verbose stack @
> 50 verbose stack @https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-1k8l17eo.w-corp-staticblitz.com/blitz.d3acb9e1.js:40:22706
> 51 verbose cwd /home/project
> 52 verbose Linux 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
> 53 verbose node v18.20.3
> 54 verbose npm  v10.2.3
> 55 error code ERR_INVALID_PROTOCOL
> 56 error Protocol "https:" not supported. Expected "http:"

[2024-11-18T23_37_57_151Z-debug-0.log](https://github.com/user-attachments/files/17807822/2024-11-18T23_37_57_151Z-debug-0.log)

Have I failed to install or configure something?

**Comment by kc0tlh** [comment]
@techwardbound Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

Tagging #176

**Comment by techwardbound** [comment]
Good to know,
     I’ve wasted a whole bunch of tokens trying to get this to build under safari. Any chance of getting some back? Since I didn’t know this was the problem, I can’t really tell how many I’ve used. I only have 7 left now after upgrading to 20 two days ago.

George.

**Comment by techwardbound** [comment]
As an update, switching to Chrome on my Mac has resolved the failure to install due to http/https protocol error. 
Thank you. Now just need to resolve my other issues.
