### ISSUE TITLE
Service down !

### ISSUE THREAD

**Issue by SecteurA** [stackblitz/bolt.new#2632]
### Describe the bug

hello, how are you today ?

prompt is too long: 204129 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

hello, how are you today ?

prompt is too long: 204129 tokens > 200000 maximum

### Expected behavior

show fine thanks !

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SecteurA** [comment]
<img width="494" alt="Capture d’écran 2024-11-18 à 05 54 30" src="https://github.com/user-attachments/assets/bd5d716c-be26-45bf-82cb-114fd9cf11f3">

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1322.
