### ISSUE TITLE
python codes

### ISSUE THREAD

**Issue by LunaxGamer** [stackblitz/bolt.new#2634]
### Describe the bug

the AI have problems on executing a python code and when i say not to change the type of code and that I could run it on my device it changed the language to html

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ebl2dg

### Steps to reproduce

4

### Expected behavior

I run in my device then I say what was needed to be fixed

### Screen Recording / Screenshot

![Screenshot_20241118_070938_com android chrome](https://github.com/user-attachments/assets/7107a389-0171-4da6-ab2c-cb8a10e45c79)
![Screenshot_20241118_070942_com android chrome](https://github.com/user-attachments/assets/b542bf21-50b3-4319-a705-f39db280e92c)

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 44952428,
  "usedJSHeapSize": 38772280,
  "jsHeapSizeLimit": 969932800
}
Username = LunaxGamer
Chat ID = a71ac6656d5a
```

### Additional context

It actually says that it cant run it because it uses web, but still try to fix

**Comment by endocytosis** [comment]
Appreciate the feedback! Currently, Bolt supports common web-based languages. Python support in WebContainers, a core technology powering Bolt, is experimental. I'd try prompting Bolt to develop the game in JavaScript for best results. Hope this helps!
