### ISSUE TITLE
new model ai

### ISSUE THREAD

**Issue by spacexelonmusk9** [stackblitz/bolt.new#2639]
why not make another bolt language model which could be called bolt lite this model will be faster but more economical and also it does less code and it will consume less tokens and this is a good idea give me an opinion

**Comment by endocytosis** [comment]
Appreciate the feedback! The team is hard at work continuing to make improvements to token efficiency while utilizing the most effect AI inference available. Bolt is [open-source](https://github.com/stackblitz/bolt.new/blob/main/CONTRIBUTING.md), so feel free to experiment with different inference models.
