### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by daraHK88** [stackblitz/bolt.new#2643]
### Describe the bug

in the middle of the writing the code this error shows and I have to retry again. I tested with new project, it's the same also refresh and fork didn't help. and sometimes uses some comment just like this //rest of the code. it doesn't update the file with full code and I have to do it again. these 2 problems bothers me so much. If there is something that i do it wrong please let me know

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-blkmr1

### Steps to reproduce

1. doesn't have any specific step. randomly happens

### Expected behavior

write the code without throwing this error in side panel
This message didn't complete its response.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76604227,
  "usedJSHeapSize": 57652539,
  "jsHeapSizeLimit": 4294705152
}
Username = daraHK88
Chat ID = 7b2e400db509
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.
