### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by Krilleren** [stackblitz/bolt.new#2649]
### Describe the bug

When trying to generate a website it stops mid through and doesnt finish it

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-np3sbw

### Steps to reproduce

1. Ask for a websote
2. Wait for it to stop midway

### Expected behavior

I expected it to make a beutiful website

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55067483,
  "usedJSHeapSize": 50722039,
  "jsHeapSizeLimit": 2160066560
}
Username = Krilleren
Chat ID = 7e2a8caa8f16
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue that is being tracked here: #1073.
