### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by kyle-matthies** [stackblitz/bolt.new#265]
### Describe the bug

I apologize for not providing a clear explanation earlier. Let me summarize the error concisely:

The build process is failing due to an import error in the main application file. Specifically:

Error location: src/main.tsx, line 3
Error message: "default" is not exported by "src/App.jsx", imported by "src/main.tsx"
This error indicates that the App component in src/App.jsx doesn't have a default export, but src/main.tsx is trying to import it as if it does.

To fix this, we need to ensure that App.jsx exports its component as a default. Let's make that change:

Fix App.jsx export

src/App.jsx
Now that we've added the default export to App.jsx, let's try deploying the application again:

Retry Deployment to Netlify

npx vite build
netlify
Let's wait for the deployment process to complete and see if this resolves the issue.

There was an error processing your request

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ofupjk

### Steps to reproduce

Click deploy

### Expected behavior

Deploy

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 334336595,
  "usedJSHeapSize": 307648963,
  "jsHeapSizeLimit": 4294705152
}
Username = LittleNuggets
Chat ID = 8ef38fd22ab4
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
