### ISSUE TITLE
impossibilité de déploiement de mon application                    SURTOUT QUE J'AI DEJA REGLER LE MOIS EN COURS MERCI DE VOTRE AIDES 

### ISSUE THREAD

**Issue by ChristopheDordogne** [stackblitz/bolt.new#2652]
### Describe the bug

Voilla le souci https://bolt.new/~/sb1-suzyhk 
je suis en colere j'ai payer et maintenant ca M................. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-suzyhk

### Steps to reproduce

![Capture erreur](https://github.com/user-attachments/assets/0d8fbd24-f5c2-4565-9164-45afd0d175e0)

### Expected behavior

![Capture erreur](https://github.com/user-attachments/assets/c0653596-912c-45f6-af8b-6706b4e7ba99)

### Screen Recording / Screenshot

![Capture erreur](https://github.com/user-attachments/assets/8a961a35-a12a-4da9-a0d1-702762b19991)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47498161,
  "usedJSHeapSize": 45138309,
  "jsHeapSizeLimit": 2160066560
}
Username = Mattsulivan
Chat ID = 881ff6ea7049
```

### Additional context

![Capture erreur](https://github.com/user-attachments/assets/cdad2be4-9184-4b2e-acc0-d0a8f1c74a39)

**Comment by AriPerkkio** [comment]
Hey @ChristopheDordogne, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
