### ISSUE TITLE
Can't see my work 

### ISSUE THREAD

**Issue by STANISLAS-CORP** [stackblitz/bolt.new#2659]
### Describe the bug

Hi, even if bolt is telling me that every thing is ok, I can't see he work and know if what I'm doing is good. I'm using all me credits don do the same thing again and again. 

Can you please help? 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-udn3wy

### Steps to reproduce

see error 

### Expected behavior

I would like to see a preview of my work 

### Screen Recording / Screenshot

<img width="499" alt="Capture d’écran 2024-11-18 à 13 23 27" src="https://github.com/user-attachments/assets/35370fdd-57fc-4532-9589-f76730423f06">
<img width="500" alt="Capture d’écran 2024-11-18 à 13 23 50" src="https://github.com/user-attachments/assets/ee58b795-8aff-461e-9409-95371bc3aebc">
<img width="475" alt="Capture d’écran 2024-11-18 à 13 24 47" src="https://github.com/user-attachments/assets/e9c31ff9-5c93-4e90-b59e-aa805efcb793">
<img width="521" alt="Capture d’écran 2024-11-18 à 13 25 21" src="https://github.com/user-attachments/assets/fd79aba4-ac96-44df-ae40-fb25ddcdbbc3">

### Platform

```
Browser name = Safari
Full version = 17.5
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
performance.memory = undefined
Username = Zico
Chat ID = b8eb118ea177
```

**Comment by STANISLAS-CORP** [comment]
I'm a new, so sorry for bordering you.

**Comment by endocytosis** [comment]
Hi, can you try opening or running a project in Chrome or Firefox? Bolt works best in these browsers. Thanks!

**Comment by STANISLAS-CORP** [comment]
Hi thanks for answering. Just trying on chrome and it has more errors.

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Brian ***@***.***>
Envoyé : Monday, November 18, 2024 7:33:16 PM
À : stackblitz/bolt.new ***@***.***>
Cc : STANISLAS-CORP ***@***.***>; Author ***@***.***>
Objet : Re: [stackblitz/bolt.new] Can't see my work (Issue #2659)


Hi, can you try opening or running a project in Chrome or Firefox? Bolt works best in these browsers. Thanks!

**Comment by kc0tlh** [comment]
@STANISLAS-CORP  Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

Since this did not resolve your issue, please subscribe to #2021 for additional troubleshooting steps and updates as we are investigating additional causes of this error there!
