### ISSUE TITLE
Don't know why it's not working

### ISSUE THREAD

**Issue by STANISLAS-CORP** [stackblitz/bolt.new#2669]
### Describe the bug

<img width="1481" alt="Capture d’écran 2024-11-18 à 16 11 28" src="https://github.com/user-attachments/assets/47ce7647-06c5-4389-8f6c-94aae1832d61">

I can't see my work 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jzw7ca

### Steps to reproduce

See error

### Expected behavior

I would like to see a preview of my work or be able to get a QR code but nothing. 

### Screen Recording / Screenshot

<img width="1503" alt="Capture d’écran 2024-11-18 à 16 13 51" src="https://github.com/user-attachments/assets/8dbe2d51-ee11-4177-9d71-14128de193a1">

### Platform

```
Browser name = Safari
Full version = 17.5
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
performance.memory = undefined
Username = Zico
Chat ID = 1063f60db9af
```

**Comment by STANISLAS-CORP** [comment]
I have to pay each time I ask something to bolt, that's ok. Do I have to pay for each time it doesn't work?

**Comment by STANISLAS-CORP** [comment]
Hi i just did what you said on all my projet. I’m on Mac, i don’t have any extensions such as ad blocker.

Thanks

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Brian ***@***.***>
Envoyé : Monday, November 18, 2024 4:28:30 PM
À : stackblitz/bolt.new ***@***.***>
Cc : STANISLAS-CORP ***@***.***>; Mention ***@***.***>
Objet : Re: [stackblitz/bolt.new] Don't know why it's not working (Issue #2669)


Hi @STANISLAS-CORP<https://github.com/STANISLAS-CORP>,

Are you able to set your project permissions to "Private (accessible by URL)" by clicking the lock icon next to the project title so we can take a closer look?

Also, do you have any browser extensions, such as an ad-blocker, running that may interfere with Bolt?

Thanks!

**Comment by endocytosis** [comment]
Hi, 

Appreciate the additional feedback. It looks like this is related to this issue which we are tracking here: #1791. Also, make sure you are using Bolt in Chrome or Firefox as those browsers work best at this time. In the interim, you could try prompting Bolt that you don't see any output and see if that resolves the issue. We appreciate your patience as improvements continue to be made!
