### ISSUE TITLE
app not loading 

### ISSUE THREAD

**Issue by jubarammm** [stackblitz/bolt.new#267]
### Describe the bug

even if token finished should conyue in to a stabel version .. and the usage should be part of the main page real time not suddenly finished .. and confusion for me to jump from bolt biltz and the history of chat or projects disapeared 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7cbrpj

### Steps to reproduce

final stage 

### Expected behavior

app should load 

### Screen Recording / Screenshot

v

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46044564,
  "usedJSHeapSize": 44002648,
  "jsHeapSizeLimit": 4294705152
}
Username = jubaramm
Chat ID = 0c171b8bbb74
```

### Additional context

v

**Comment by samdenty** [comment]
Sorry for the inconvenience, projects are persisted at the moment but not chats.

We're tracking this in #39, you can subscribe to it to be notified when they are.

we recently shipped token reduction and the ability to see tokens in the settings page in sidebar
