### ISSUE TITLE
White Screen loop, no fix seems to work, and no way to get back to previous working checkpoint

### ISSUE THREAD

**Issue by romainboyer** [stackblitz/bolt.new#2672]
### Describe the bug

Hello,

I have white screens, I ask each time to fix it, Bolt seems to find the solution but nothing works, even after asking 10 times.

So I tried to get back to previous working checkpoints, but none worked, I still have a white screen.

I have lost my app and don't know how to fix this.

Thanks for your help

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tekwn9

### Steps to reproduce

Display the app => white screen

### Expected behavior

not a white screen

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64919620,
  "usedJSHeapSize": 62122684,
  "jsHeapSizeLimit": 4294705152
}
Username = romainboyer
Chat ID = ee015a6b301d
```

**Comment by endocytosis** [comment]
Hi @romainboyer, 

Sorry to hear about this! Are you able to find your past project by going to stackblitz.com, logging in (same credentials as Bolt), opening Collections on the left-hand side of the page, then opening Bolt Collection?

Regarding the white preview screen, this is a known issue and is being tracked here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. We appreciate your patience as improvements continue to be made!

**Comment by romainboyer** [comment]
This seems to have been fixed after a while. I don't know why but when I came back to my app, it was working. Thanks for the fast support!

**Comment by endocytosis** [comment]
You're welcome!

**Comment by samdenty** [comment]
hi there when you get the white screen could you send a screenshot of your browser devtools?

make sure this setting is enabled so we can see everything

![CleanShot 2024-11-22 at 08 54 57@2x](https://github.com/user-attachments/assets/0e0c1074-fdf0-4236-8f07-7716e394f8cb)

Specifically do you see `Minified React error #418` that'd be helpful to know
