### ISSUE TITLE
Unable to Add Icons for Progressive Web Apps

### ISSUE THREAD

**Issue by rickm1972** [stackblitz/bolt.new#2674]
### Describe the bug

Hi there, I want to add icon for my PWA but it is unable to do it no matter what promptI give.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jtvsso

### Steps to reproduce

Ask it to implement icons for my PWA, I uploaded 3 different sizes of the icons, it says it will but it never works

### Expected behavior

Adding to home screen gives my custom icon

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109416617,
  "usedJSHeapSize": 105441445,
  "jsHeapSizeLimit": 4294705152
}
Username = rm2024!
Chat ID = bf8f97977443
```

### Additional context

Also it would be awesome to see all of your previous projects and be able to edit and redeploy them, is that coming?

Overall this is an awesome tool, kudos and cant wait to see what you add

**Comment by endocytosis** [comment]
Appreciate the feedback and glad to hear you are liking Bolt! Regarding image uploads, this isn't currently supported and we are tracking it here: #1809. In the interim, if you open the Bolt project in StackBlitz (click the Open in StackBlitz button at the top-right of the page) you should be able to add the images to the StackBlitz file system and continue development there (you may need to adjust the image file path in the code).

Regarding chat persistence and management of past projects, the team is hard at work continuing to make these improvements. See here: #49 for continuing to update to a custom Netlify domain and here: #2367 regarding improved GitHub integration. Thanks for your support!

**Comment by rickm1972** [comment]
Awesome and thanks for the quick response!
