### ISSUE TITLE
Hit Token Limit after buying Premium in 3 min.

### ISSUE THREAD

**Issue by Toolbox-AI** [stackblitz/bolt.new#268]
### Describe the bug

Hello,

i hit my Pro Plan (10 Mio) token limit within 3 min after buying it. I did not even get any results. Clearly i must be in a bug, as i did more testing on the free plan.

> You have hit the rate limit. You can continue to code for free in the editor.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Not possible

### Expected behavior

See how many Tokens left

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by derSchotte** [comment]
Hello, I have the same problem. After a few attempts with Bolt.new and a Pro subscription. I get the message that I have used up all my tokens.

**Comment by Alohacop** [comment]
Same problem. Paid member. Out of tokens in a couple hours.

**Comment by WhaleFromMars** [comment]
Same issue here, rate limit message doesn't reflect updated token limits
```{"code":"rate-limited","message":"You have hit the rate limit. You can continue to code for free in the editor.","providerLimitHit":false,"isRetryable":true,"tokenStats":{"totalToday":0,"totalThisMonth":830022,"maxPerDay":10000,"maxPerMonth":10000,"nextTier":null,"overflow":{"available":0,"used":0}}}```

**Comment by sulco** [comment]
Hey all, thank you for reporting the issue! We are working on a solution and making a lot of changes to support the token reloading and a more clear in-app status of the tokens. Thank you for your patience, we will deploy the first updates as soon as possible.

**Comment by violacase** [comment]
> Same issue here, rate limit message doesn't reflect updated token limits `{"code":"rate-limited","message":"You have hit the rate limit. You can continue to code for free in the editor.","providerLimitHit":false,"isRetryable":true,"tokenStats":{"totalToday":0,"totalThisMonth":830022,"maxPerDay":10000,"maxPerMonth":10000,"nextTier":null,"overflow":{"available":0,"used":0}}}`

How did you get the info displayed above?

**Comment by sulco** [comment]
Hey, @Toolbox-AI, I back with a more specific update: just found that while we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue to help with the triage, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
