### ISSUE TITLE
Real-Time Subscription Usage Tracking Feature Request

### ISSUE THREAD

**Issue by amilkarferra** [stackblitz/bolt.new#269]
**Is your feature request related to a problem? Please describe:**

Currently, I don't have a clear way to see what I've consumed in real time or how much I have left according to my subscription. This makes it difficult to manage my usage and optimize consumption.

**Describe the solution you'd like:**

I would like to have a feature that shows me in real time what I've consumed and what I have left of my subscription. This should be available in a clear and accessible way within the system, with visual indicators that allow me to easily track my usage.

**Describe alternatives you've considered:**

I have considered keeping a manual record of consumption, but it is neither practical nor accurate. I also thought about using alerts to notify me when I am close to reaching my limit, but I prefer real-time monitoring for better control.

**Additional context:**

A dashboard with a progress bar or a chart showing consumption would be ideal. It would also be helpful to have automatic notifications when consumption is nearing the limit.

**Comment by sulco** [comment]
Hey @amilkarferra thank you for reporting the issue! We are working on a solution and making a lot of changes to support a more clear in-app status of the tokens. Thank you for your patience, we will deploy the first updates as soon as possible!

**Comment by samdenty** [comment]
This is shipped now in settings page in sidebar
