### ISSUE TITLE
New Error for Me: messages.0.content.11.text.cache_control: Extra inputs are not permitted 

### ISSUE THREAD

**Issue by SeniorThrive** [stackblitz/bolt.new#2690]
### Describe the bug

messages.0.content.11.text.cache_control: Extra inputs are not permitted 

### Link to the Bolt URL that caused the error

https://d5520b31.bolt-cnr.pages.dev/~/sb1-xttypz

### Steps to reproduce

Any new prompt gives me this show stopping error: messages.0.content.11.text.cache_control: Extra inputs are not permitted 

### Expected behavior

I can start / continue with my project

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! Would you be able to set your project to "Private (accessible by URL)" by clicking the lock icon next to the project title so we can take a closer look? Could you take a screenshot of this error and paste it here? Thanks!

**Comment by SeniorThrive** [comment]
![image](https://github.com/user-attachments/assets/cb197642-518f-4ca9-8d46-3dc558f2803b)

![image](https://github.com/user-attachments/assets/94b0ae87-6935-4b42-b6e9-fc500099efc4)


Here you go - and I think you mean Secret (accessible by URL). Please advise if different

**Comment by SeniorThrive** [comment]
Any updates on this? I am at a complete standstill on moving this project and my business forward. Is there a workaround you can suggest?

**Comment by endocytosis** [comment]
Hi! Are you able to resolve this issue by:

1) Opening your project.
2) Clicking the Bolt icon in the console.
3) Type "control + c".
4) Enter "npm run dev" and hit enter.

**Comment by endocytosis** [comment]
Glad to hear it! I would encourage you to download frequent backups of your project (right-click the Download button at the top-right of the page). The team is hard at work at enabling bettering GitHub integration which will make version control much simpler. In the meantime, making sure you have frequent backups is key.

Also, if you have your project at a desired state, I would click the Open in StackBlitz button at the top-right, then click the fork button at the top-left in StackBlitz to fork the project. You can then rename the title of this project in StackBlitz to have a forked version present as a backup there as well.

Hope this helps!
