### ISSUE TITLE
Please give money back

### ISSUE THREAD

**Issue by abda11ah** [stackblitz/bolt.new#2695]
### Describe the bug

It worked well yesterday for generating a tiny php application, today it is very locked even if I tell it I don't need to preview the php code.

please money back

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xovjvu

### Steps to reproduce

give me an example P H P blog

### Expected behavior

a tiny app

### Screen Recording / Screenshot

![Capture d’écran du 2024-11-18 21-38-02](https://github.com/user-attachments/assets/bc4531ed-b3b1-470e-92b8-8abd0ad6d248)

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = abda11ah
Chat ID = b361f54c0f15
```

**Comment by endocytosis** [comment]
Hi @abda11ah, 

Appreciate the feedback! Bolt currently does not support PHP as mentioned in the above message you received. You can download your PHP project by clicking the download button at the top-right of the page (or look for it on StackBlitz by going to [stackblitz.com ](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection, and then continue development there. Hope this helps!

**Comment by endocytosis** [comment]
All good, glad to hear it is working!

**Comment by abda11ah** [comment]
To make it work, i had to tell it : give me a basic [framework name] skeleton app. Then add other pages
