### ISSUE TITLE
Stopped updating codes.

### ISSUE THREAD

**Issue by head77x** [stackblitz/bolt.new#27]
### Describe the bug

<img width="471" alt="image" src="https://github.com/user-attachments/assets/1440f4ef-663d-4a4f-9862-ab97f1f26d03">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hcagvn

### Steps to reproduce

I just input new prompt but it was stopped.

### Expected behavior

<img width="471" alt="image" src="https://github.com/user-attachments/assets/6b1a9902-75c7-4021-bc30-8b40b34cb5bd">

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77773084,
  "usedJSHeapSize": 73707324,
  "jsHeapSizeLimit": 4294705152
}
Username = head77x
Chat ID = ba7d2e8b2f12
```

### Additional context

Message:
```
Certainly! I'll create a mobile-friendly layout for the ordering system, with categories on the left and the corresponding food items on the right. We'll update the OrderingSystem component to implement this design. Let's make these changes:

<div class="__boltArtifact__" data-artifact-id="6:update-ordering-system" data-running-actions="true"></div>

Now, let's update the App.vue file to ensure it passes the shopId and tableId correctly:

<div class="__boltArtifact__" data-artifact-id="7:update-app" data-running-actions="true"></div>
```

**Comment by samdenty** [comment]
This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back
