### ISSUE TITLE
It fails to regenerate the entire file

### ISSUE THREAD

**Issue by TheBlueHouse75** [stackblitz/bolt.new#2701]
### Describe the bug

When asking to work on a certain page (500+ lines long), it truncates most of the page in the new version (laziness)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-9hna9w

### Steps to reproduce

here is the result :

import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../config/firebase';
import { Shield, Lock, CreditCard, Building2, Mail, Phone, AlertCircle, X, Globe, FileText, ChevronDown } from 'lucide-react';
import { CardElement } from '@stripe/react-stripe-js';
import { StripeProvider } from '../components/StripeProvider';
import { motion, AnimatePresence } from 'framer-motion';
import { useTranslation } from 'react-i18next';

// ... (previous imports and interfaces remain the same)

export function DepositPage() {
  // ... (previous state and hooks remain the same)

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        {/* ... (previous code remains the same until the form section) */}

        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          {/* ... (previous sections remain the same) */}

          {/* User Information Form - Updated Layout */}
          <div className="px-8 py-10 border-b border-gray-200">
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-6">
              {t('payment.userInfo')}
            </h3>
            
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* First Name */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    {t('payment.firstName')} <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={firstName}
                    onChange={(e) => setFirstName(e.target.value)}
                    className="block w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    required
                    placeholder={t('payment.firstName')}
                  />
                  {fieldErrors.firstName && (
                    <p className="mt-2 text-sm text-red-600 dark:text-red-400">{fieldErrors.firstName}</p>
                  )}
                </div>

                {/* Last Name */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    {t('payment.lastName')} <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={lastName}
                    onChange={(e) => setLastName(e.target.value)}
                    className="block w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    required
                    placeholder={t('payment.lastName')}
                  />
                  {fieldErrors.lastName && (
                    <p className="mt-2 text-sm text-red-600 dark:text-red-400">{fieldErrors.lastName}</p>
                  )}
                </div>
              </div>

              {/* Email */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  {t('payment.email')} <span className="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="block w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  required
                  placeholder="example@email.com"
                />
                {fieldErrors.email && (
                  <p className="mt-2 text-sm text-red-600 dark:text-red-400">{fieldErrors.email}</p>
                )}
              </div>

              {/* Reservation Number */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  {t('payment.reservationNumber')}
                </label>
                <input
                  type="text"
                  value={reservationNumber}
                  onChange={(e) => setReservationNumber(e.target.value)}
                  className="block w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  placeholder={t('payment.reservationNumber')}
                />
              </div>
            </div>
          </div>

          {/* ... (rest of the code remains the same) */}
        </div>
      </div>
    </div>
  );
}

### Expected behavior

full file output (not truncated)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69741814,
  "usedJSHeapSize": 62356958,
  "jsHeapSizeLimit": 4294705152
}
Username = TheBlueHouse75
Chat ID = 0a75631cefdb
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2862.
