### ISSUE TITLE
command failed: npm run dev

### ISSUE THREAD

**Issue by ahmetarslan** [stackblitz/bolt.new#2702]
### Describe the bug

i have a serious issue. always getting same error with different logs. "npm run dev".

> parcel-viewer@0.0.0 dev
> vite

  VITE v4.5.5  ready in 1619 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.1.104:5173/
01:32:28 [vite] hmr update /src/components/Map.tsx, 
01:33:08 [vite] hmr update /src/components/PropertyDetails.tsx, /src/index.css

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a4prfd

### Steps to reproduce

i am trying to deploy my app without any errors. but i keep seeing same error with diff. logs.

### Expected behavior

bolt should solve the problem.

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 120942751,
  "usedJSHeapSize": 116094235,
  "jsHeapSizeLimit": 2172649472
}
Username = ahmetarslan
Chat ID = c0cdf6050c92
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2021).
