### ISSUE TITLE
Preview is just white screen

### ISSUE THREAD

**Issue by wtdavenport** [stackblitz/bolt.new#2709]
### Describe the bug

This may be a user issue and not a bug.  I created a project but when I click the Preview screen it's just white.  Nothing is there.  But this is my first day using Bolt so I may just be doing something wrong.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tuk3ne

### Steps to reproduce

I click on preview but nothing is there

### Expected behavior

The dialog says I should see something, see screenshot

### Screen Recording / Screenshot

![Screenshot 2024-11-18 at 7 55 52 PM](https://github.com/user-attachments/assets/b85c8e5c-1cf6-4a08-b423-ffa9d82ee582)

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = wtdavenport
Chat ID = abb40a70a235
```

### Additional context

there were errors during previous builds with Vite, not sure if that could be related.

**Comment by endocytosis** [comment]
Hi @wtdavenport, 

Sorry to hear this! Can you try opening your project in Chrome and see if the problem persists? Thanks.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. Make sure you are working in Chrome or Firefox as Bolt works best in those browsers. We appreciate your patience as improvements continue to be made!

**Comment by wtdavenport** [comment]
Running in Chome today worked!

Thank you very much.

**Comment by endocytosis** [comment]
Glad to hear it! Appreciate the additional feedback.
