### ISSUE TITLE
Run out of tokens

### ISSUE THREAD

**Issue by yazoosa** [stackblitz/bolt.new#271]
Help, I'm addicted. I need more tokens but I cant see how to buy more. I'm desperate man.

**Comment by Abraham12611** [comment]
Did you subscribe for the pro version?

**Comment by yazoosa** [comment]
Hi Abraham,

Yes, indeed. See the attached invoice.

Had the same experience as others as discussed in the link below

https://github.com/stackblitz/bolt.new/issues/218

Kind Regards,

**Comment by sulco** [comment]
Hey @yazoosa , thank you for reporting the issue! We are actively working on a solution and implementing several changes to support token reloading, provide a clearer in-app status for the tokens and more subscription tiers for token. We appreciate your patience and will deploy the first updates as soon as possible so today and over the next couple of days, you can expect a continually improving experience.

**Comment by sulco** [comment]
Hey, @yazoosa! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! And we are working on more subscription tiers and ways to purchase additional tokens, too! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!

**Comment by kc0tlh** [comment]
Here's the info on purchasing additional tokens:
https://x.com/stackblitz/status/1844138865508134999
