### ISSUE TITLE
NPM run dev error

### ISSUE THREAD

**Issue by lifehiker** [stackblitz/bolt.new#2715]
### Describe the bug

From the beginning of this project I have been getting the "No Preview Available" screen. I try to get the AI to find and fix the error, which is has on occasion, but lately it's gone downhill. I'm constantly getting the same NPM error over and over again. It can't find the error, or maybe it's hallucinating that it's finding the error, when it's really not. I'm not sure what the issue is. I've spent millions of credits trying to get it to identify and fix it. When it does detect a problem, and I click "fix problem" it just recreates a package.json file and then says "All good!" but then I get the same "No Preview Available" screen again. Additionally, often it'll also show me what I call _"the gray screen of death"_ where the browser is just a blank gray/blackish screen (see screenshot).  Would deploying it to Netlify provide a different outcome? Maybe I'll try it just to see. 

<img width="1470" alt="Screenshot 2024-11-18 at 9 14 50 PM" src="https://github.com/user-attachments/assets/02665cf1-f065-4954-a802-94ea697f5b0c">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-myw6qv

### Steps to reproduce

1. Go to: YourSiteGuru Client Portal (forked)
2. It will try to load the preview, it will fail. 
3. Click "fix problem" ... it will say it did. 
4. It will say "No Preview Available" 

<img width="503" alt="Screenshot 2024-11-18 at 9 22 10 PM" src="https://github.com/user-attachments/assets/39cb961c-4d67-4cb7-bb66-968d55b10822">

### Expected behavior

When I see the actual preview, I get so excited! But most of the time - it's just "No Preview Available" and I pull more hair out of my head.

### Screen Recording / Screenshot

I've included 2 above. If you need more just let me know. 

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = lifehiker
Chat ID = 40d02ac50ba9
```

### Additional context

I've spent millions of credits now just trying to solve these issues, I think it's kind of crazy that just telling it "run the code" costs 100,000 credits - or so it seems to cost that much - and feels wildly expensive. I'm not sure how it's structured but it seems like every command to the ai is at least 100,000 credits, but not all commands are equal, so the cost shouldn't be either. With Cursor.ai I have not run out of credits and have provided it with way more commands and I haven't exceeded the cost of $20/mo, whereas I blew through Bolts allocation of $20 worth of credits and now am on the verge of running out at the $50/mo level, all without what seems to be an app that won't work (at least doesn't show any preview of it working).

**Comment by lifehiker** [comment]
Oh my gosh, I just tried "deploying" it to Netlify - AND IT'S WORKING!!!! I can't believe it's working! So my next question would be - why would it work on Netlify and not on internally, on the preview?

**Comment by lifehiker** [comment]
yeah, I really wish the preview would work - I hope it can be solved. But in the meantime, I'm so excited and thrilled it's working on the "live" deployment. I will be up early in the morning to keep working on it!!! Woohoo!!!

**Comment by lifehiker** [comment]
and of course, with my last try and update of the night, the preview shows up. Unreal. haha

**Comment by lifehiker** [comment]
But, back to the gray screen of death and "no preview available" is constantly happening. Sometimes, the preview will show up, but then it'll go to the gray screen of death and I'll have to refresh the page.

**Comment by lifehiker** [comment]
and the conversation that I was having will be gone, losing whatever progress I had been making with the ai

**Comment by endocytosis** [comment]
Appreciate the feedback and glad you are liking Bolt! For best compatibility use Chrome or Firefox as described [here](https://github.com/stackblitz/bolt.new/issues/2796). It is likely that some of your issues may have stemmed from using Safari. Hope this helps!
