### ISSUE TITLE
Hit rate limit even after subscribing for pro.

### ISSUE THREAD

**Issue by Abraham12611** [stackblitz/bolt.new#272]
### Describe the bug

I received a 'Hit limit' message while using Bolt. Please note that I subscribed to the Pro version just yesterday evening, and I've barely used it since then. However, I unexpectedly encountered a 'Rate limit reached' message.

Is there possibly a daily limit, even after subscribing to the Pro version?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s4zamy

### Steps to reproduce

There are no steps to reproduce

### Expected behavior

Tokens not get exhausted that quickly.

### Screen Recording / Screenshot

![Screenshot 2024-10-09 082615](https://github.com/user-attachments/assets/84763951-b481-4346-af69-b4aad09c31a1)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89737628,
  "usedJSHeapSize": 86755636,
  "jsHeapSizeLimit": 2172649472
}
Username = Abdahunsi
Chat ID = 5a9fc14ac41b
```

**Comment by sulco** [comment]
Hey @Abraham12611 , thank you for reporting the issue! We are actively working on a solution and implementing several changes to support token reloading and provide a clearer in-app status for the tokens. We appreciate your patience and will deploy the first updates as soon as possible so today and over the next couple of days, you can expect a continually improving experience.

**Comment by sulco** [comment]
Hey, @Abraham12611! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
