### ISSUE TITLE
Request for Assistance with Unimplemented Changes and Token Restoration

### ISSUE THREAD

**Issue by NobleYve** [stackblitz/bolt.new#2720]
### Describe the bug

The issue occurs when attempting to make changes using the prompt. Despite entering valid input and following the usual process, the expected modifications are not being applied. The system processes the prompt without error messages but fails to reflect the requested updates.

This behavior persists even after resolving the token limit issue, suggesting that the problem lies specifically in the prompt's functionality or implementation. As a result, tokens are consumed without achieving the desired outcome.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sxlrzp

### Steps to reproduce

1. Logged in on the platform.
2. Navigated to the prompt section where modifications are typically made.
3. Entered a valid prompt detailing the changes I  wanted to implement.
4. Clicked to apply the changes.
5. Observed that the system processes the input without displaying any error messages, but the requested modifications are not reflected in the output or system state.
6. Verified that tokens are consumed for each attempt despite the changes not being implemented.

### Expected behavior

When a valid prompt is entered:

1. The system should process the input and apply the requested modifications correctly.
2. The changes should be reflected immediately in the output or system state, as specified in the prompt.
3. Tokens should only be consumed if the modifications are successfully implemented.
4. If the input is invalid or an error occurs, the system should provide a clear error message or feedback indicating the issue, without consuming tokens unnecessarily

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112013426,
  "usedJSHeapSize": 93045954,
  "jsHeapSizeLimit": 4294705152
}
Username = Kagoyire Yvette
Chat ID = 2e65e49fbccb
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times, there are programming challenges that are too complex for the AI to solve and manual intervention is required. Advice on prompting effectively can be found [here](https://support.bolt.new/Prompting-Effectively-13fd971055d6801b9af4e965b9ed26e2). This [prompt engineering documentation ](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview) from Anthropic is helpful as well. The [Bolt Help Center](https://support.bolt.new/welcome?pvs=74) in general has information on using Bolt most effectively. Advice on continuing the development of your project can be found [here](https://github.com/stackblitz/bolt.new/issues/2310). Refund requests are handled through hello@stackblitz.com. Hope this helps!
