### ISSUE TITLE
fix the damn WHITE SCREEN!

### ISSUE THREAD

**Issue by 0xCarnival** [stackblitz/bolt.new#2723]
### Describe the bug

white screen on preview page, it happens ALL THE TIMES, not just sometimes, it is white all the time.

### Link to the Bolt URL that caused the error

n/a

### Steps to reproduce

1 prompt bolt 
2 get a white screen

### Expected behavior

n/a

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by DeeCexplorer** [comment]
Exactly, this is frustrating and the worst is there is no response from bolt team, though some of us are using paid service and would definitely expect a much better service than this.

**Comment by LeGeRyChEeSe** [comment]
Hello, I noticed that with Opera GX I always have a white screen but with Microsoft Edge I never had a white screen.

**Comment by endocytosis** [comment]
Appreciate the additional feedback regarding Edge vs Opera! We are continuing to track this issue here: #1791. Appreciate your patience as improvements continue to be made!

**Comment by samdenty** [comment]
hi there when you get the white screen could you send a screenshot of your browser devtools?

make sure this setting is enabled so we can see everything

![CleanShot 2024-11-22 at 08 54 57@2x](https://github.com/user-attachments/assets/0e0c1074-fdf0-4236-8f07-7716e394f8cb)

Specifically do you see `Minified React error #418` that'd be helpful to know
