### ISSUE TITLE
Use diff instead of generating the whole content

### ISSUE THREAD

**Issue by balachandarsv** [stackblitz/bolt.new#2724]
**Is your feature request related to a problem? Please describe:**

When trying to generate a new item, it generates the whole document which already has most parts, instead generating only the needed portion and applying it as patch would be a great option and also it saves a lot of tokens.

**Describe the solution you'd like:**

Generate diff with the current content/ Generate a patch and apply it.

**Comment by endocytosis** [comment]
Appreciate the feedback! The team actively working on integrating a diff based approach which should further improve token efficiency.

**Comment by balachandarsv** [comment]
@endocytosis can you please help me with terms and conditions of bolt.new, we can see only stackblitz terms and conditions. 

Also please share any information on the terms as it is not clear as to what it is commercial purpose. Also, what if a single employee wants to use the services for internal purpose. 

Also what about the licence for the content that is generated by the service?

**Comment by osheenchavhan** [comment]
Hey @endocytosis , 
I guess this feature (diffs) was launched on twitter yesterday, I enabled it in my profile, it doesnt seems to be working well imo. It says it took 4500 tokens only but went straight from 715k to 547k tokens. 

<img width="518" alt="Screenshot 2024-11-28 at 2 09 13 PM" src="https://github.com/user-attachments/assets/2092d0d4-d5f6-4439-9970-ac525e68e0c3">
