### ISSUE TITLE
Subscription plan, my first project has not yet been completed, and I have run out of tokens

### ISSUE THREAD

**Issue by JKing-8** [stackblitz/bolt.new#273]
I subscribed to the pro plan. But my first project from scratch has not yet started, and I have been fixing bugs. I ran out of tokens and still haven't fixed it. I only used it for less than two hours, which is very confusing. And I can't use my own api key. I found that every time I fix a problem, the entire file is replaced, and I think it consumes a lot of tokens. Overall, I am very dissatisfied with this.

**Comment by reech1** [comment]
Same issue here. you can use your API key in the .env.local file

**Comment by KingLeoJr** [comment]
I agree. There is absolutely no need to recreate the whole project for every request. Just add enhancements and do not delete or replace already implemented code. 4.5M for free user and 10M for pro user. 10M gets over very quickly. It's just not very cost-effective at the moment.
How did you come up with 10M tokens limit? What was the rationale? It doesn't seems to be increased even in the higher pricing tiers as well.

**Comment by sulco** [comment]
Hey, @JKing-8! We are been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
