### ISSUE TITLE
Project lost

### ISSUE THREAD

**Issue by Trkrkrl** [stackblitz/bolt.new#2731]
### Describe the bug

Yesterday created a project. worked on it about 3 hours, now its lost. It said "npm error want me to fix it?" , I said yes and deleted all project codes, started from scratch. Time is lost and lots of credits lost. Will that happen again? Is there a way to save our projects like github or something, prevent data loss

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jykkeb

### Steps to reproduce

I left project , today its gone, this morning opened project and show e this error:
![image](https://github.com/user-attachments/assets/f94715cf-a388-4a38-b550-d86779b10927)
 refreshed page nothing fixed it. SO I said yes, and there is no code, it started from scratch. And gave this error again.

### Expected behavior

When I open the project I want to see the project. If every time it gets deleted why would I pay 

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120981779,
  "usedJSHeapSize": 99152023,
  "jsHeapSizeLimit": 4294705152
}
Username = lazer
Chat ID = 43dbe8c9ef38
```

**Comment by endocytosis** [comment]
Hi @Trkrkrl, 

Sorry to hear this! Are you able to find you project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and the opening Bolt Collection?

**Comment by Trkrkrl** [comment]
Yes, I can.

**Comment by endocytosis** [comment]
Glad to hear it! We appreciate your patience as the team continues to make improvements!
