### ISSUE TITLE
npm ERR! code ERR_INVALID_PROTOCOL on Safari browser only

### ISSUE THREAD

**Issue by everspader** [stackblitz/bolt.new#2733]
### Describe the bug

When running `npm run dev`, there is an error with the dev server that is only observer on Safari browser:
```
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-19T07_40_58_889Z-debug-0.log
```

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

Using Safari:
1. Start a NextJS project
2. Try to start the dev server with `nom run dev`

### Expected behavior

The development server should start after installing the package dependencies.

### Platform

- OS: macOS
- Browser: Safari
- Version: 18.2

### Additional context

This issue has only been observer with the Safari browser.

**Comment by kc0tlh** [comment]
@everspader Bolt.new does not currently support Safari. We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

Tagging #176

**Comment by everspader** [comment]
@kc0tlh thank you, I appreciate the explanation!
