### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ciapog** [stackblitz/bolt.new#2739]
### Describe the bug

Sometimes, when the prompt is to long, the ai struggles...

I'll fix the dependency issues and update the project structure. The main issue is with the SQLite package name and missing NativeScript CLI.
Fix Dependencies and Project Setup

package.json

npm install

src/services/DatabaseService.ts

    setup-nativescript-stackblitz && ns preview

I've made the following changes:

    Replaced @nativescript/sqlite with @triniwiz/nativescript-sqlite
    Added a DatabaseService to handle SQLite operations
    Updated the HomeScreen to use the DatabaseService
    Fixed the preview script to include the setup command
    Added proper error handling for database operations

The app should now work with proper database functionality for storing and retrieving beers. Would you like to add more features or screens to the application?
Bolt has resolved the problems.

I'll fix the SQLite dependency issue and update the project structure to use the correct NativeScript SQLite package.
Fix SQLite Dependency and Project Structure

    package.json

This message didn't complete its response.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mnegqn

### Steps to reproduce

npm install bug...

### Expected behavior

Prompt Optimisé pour Bolt.new
Pour créer une application web et mobile responsive qui répond aux consignes du brief et prend en compte les tables que vous avez créées (MLD et MPD), vous pouvez utiliser le prompt suivant pour Bolt.new. Ce prompt inclut toutes les spécifications nécessaires pour garantir que l'application soit bien structurée et fonctionnelle.

Prompt pour Bolt.new
Titre du Projet :
Zythologue - Base de Données pour Amateurs de Bière

Contexte du Projet :
Tu as une passion dévorante pour la bière artisanale et souhaites découvrir et partager ce monde au-delà de la dégustation : explorer l'histoire derrière chaque brasserie, les ingrédients spécifiques, et les techniques de brassage. En tant que développeur, tu envisages de créer une application web/mobile pour organiser et partager cette passion. Avant de te lancer dans le développement, une base de données bien structurée est cruciale.

Objectif :
Créer une application web et mobile responsive pour les amateurs de bière, permettant de gérer et d'explorer les informations sur les bières, les brasseries, les ingrédients, les avis, et les favoris.

Fonctionnalités Requises :

Gestion des Utilisateurs :

Inscription et connexion des utilisateurs.
Gestion des profils utilisateurs.
Gestion des Bières :

Ajout, mise à jour et suppression des bières.
Affichage des détails des bières, y compris les ingrédients, les avis, et les photos.
Gestion des Brasseries :

Ajout, mise à jour et suppression des brasseries.
Affichage des détails des brasseries et des bières associées.
Gestion des Avis :

Les utilisateurs peuvent laisser des notes et commentaires sur les bières.
Affichage des avis par bière.
Gestion des Favoris :

Les utilisateurs peuvent ajouter des bières à leurs favoris.
Affichage des bières favorites par utilisateur.
Gestion des Photos :

Les utilisateurs peuvent télécharger des photos des bières.
Affichage des photos par bière.
Gestion des Ingredients :

Ajout, mise à jour et suppression des ingrédients.
Affichage des ingrédients par bière.
Gestion des Catégories :

Ajout, mise à jour et suppression des catégories.
Affichage des bières par catégorie.
Structure de la Base de Données :
Utiliser les tables suivantes pour la base de données PostgreSQL :

-- Table Users
CREATE TABLE Users (
    id_user SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Beers
CREATE TABLE Beers (
    id_beer SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    abv DECIMAL(3,1) CHECK (abv BETWEEN 0 AND 20),
    type VARCHAR(50),
    color VARCHAR(50),
    release_date DATE,
    id_brewery INT REFERENCES Breweries(id_brewery) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Breweries
CREATE TABLE Breweries (
    id_brewery SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    country VARCHAR(100),
    region VARCHAR(100),
    address VARCHAR(255),
    facebook_link VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Reviews
CREATE TABLE Reviews (
    id_review SERIAL PRIMARY KEY,
    id_user INT REFERENCES Users(id_user) ON DELETE CASCADE,
    id_beer INT REFERENCES Beers(id_beer) ON DELETE CASCADE,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Favorites
CREATE TABLE Favorites (
    id_favorite SERIAL PRIMARY KEY,
    id_user INT REFERENCES Users(id_user) ON DELETE CASCADE,
    id_beer INT REFERENCES Beers(id_beer) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Photos
CREATE TABLE Photos (
    id_photo SERIAL PRIMARY KEY,
    id_beer INT REFERENCES Beers(id_beer) ON DELETE CASCADE,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Ingredients
CREATE TABLE Ingredients (
    id_ingredient SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table BeerIngredients (Relation N:M entre Beers et Ingredients)
CREATE TABLE BeerIngredients (
    id_beer INT REFERENCES Beers(id_beer) ON DELETE CASCADE,
    id_ingredient INT REFERENCES Ingredients(id_ingredient) ON DELETE CASCADE,
    PRIMARY KEY (id_beer, id_ingredient)
);

-- Table Categories
CREATE TABLE Categories (
    id_category SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table BeerCategories (Relation 1:N entre Beers et Categories)
CREATE TABLE BeerCategories (
    id_beer INT REFERENCES Beers(id_beer) ON DELETE CASCADE,
    id_category INT REFERENCES Categories(id_category) ON DELETE CASCADE,
    PRIMARY KEY (id_beer, id_category)
);
Requêtes SQL :

Lister les bières par taux d'alcool, de la plus légère à la plus forte.
Afficher le nombre de bières par catégorie.
Trouver toutes les bières d'une brasserie donnée.
Lister les utilisateurs et le nombre de bières qu'ils ont ajoutées à leurs favoris.
Ajouter une nouvelle bière à la base de données.
Afficher les bières et leurs brasseries, ordonnées par pays de la brasserie.
Lister les bières avec leurs ingrédients.
Afficher les brasseries et le nombre de bières qu'elles produisent, pour celles ayant plus de 5 bières.
Lister les bières qui n'ont pas encore été ajoutées aux favoris par aucun utilisateur.
Trouver les bières favorites communes entre deux utilisateurs.
Afficher les brasseries dont les bières ont une moyenne de notes supérieure à une certaine valeur.
Mettre à jour les informations d'une brasserie.
Supprimer les photos d'une bière en particulier.
Manipulations Avancées :

Écrire une procédure stockée permettant à un utilisateur de noter une bière. Si l'utilisateur a déjà noté cette bière, la note est mise à jour ; sinon, une nouvelle note est ajoutée.
Écrire un déclencheur (trigger) pour vérifier que l'ABV (taux d'alcool) est compris entre 0 et 20 avant l'ajout de chaque bière.
Contraintes :

Utiliser PostgreSQL comme SGBD relationnel.
Créer un environnement Docker avec docker-compose pour lancer PostgreSQL.
Utiliser un compte SQL dédié pour gérer la base de données (root interdit).
Chaque entrée de la base de données doit inclure une date de création et de modification pour le suivi.
Deadline :
3 jours.

Modalités d'Évaluation :

Correction entre pairs.
Les requêtes seront testées en local après importation de l’environnement Docker.
Livrables :

Un dépôt GitHub contenant :
L'environnement Docker configuré avec docker-compose pour la base de données.
Le dictionnaire des données.
Les règles de gestion.
MCD, MPD, et MLD détaillés.
Un script SQL pour initialiser la base de données avec des données de test.
Une documentation des requêtes dans le README.md.
Critères de Performance :

Facilité de mise en place de l’environnement.
Exactitude des relations entre les tables.
Fonctionnalité du trigger.
Clarté et pertinence des requêtes documentées dans le README.md.
Exécution sans erreur des requêtes.
Ressources :

DBeaver pour une interface de gestion de base de données.
Comprendre les bases de données.
Modèle Conceptuel des Données.
Langage SQL.

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = ciapog
Chat ID = 6e56e40fe462
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2021).
