### ISSUE TITLE
preview blank page

### ISSUE THREAD

**Issue by ademedio** [stackblitz/bolt.new#2745]
### Describe the bug

when i try to make any webapp bolt gives me a white screen... always last different requests e projects... i've spent much token!!!!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ya7igt

### Steps to reproduce

i've aks a template for a garden tool shop's apple style

### Expected behavior

a simple html template

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = ademedio
Chat ID = 1c4701848e9a
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with the white screen and are tracking it here: #1791, along with some potential workarounds. We appreciate your patience as the team continues to make improvements!

**Comment by endocytosis** [comment]
Got it, thanks for the additional feedback and glad it is working!

**Comment by samdenty** [comment]
hi there when you get the white screen could you send a screenshot of your browser devtools?

make sure this setting is enabled so we can see everything

![CleanShot 2024-11-22 at 08 54 57@2x](https://github.com/user-attachments/assets/0e0c1074-fdf0-4236-8f07-7716e394f8cb)

Specifically do you see `Minified React error #418` that'd be helpful to know
