### ISSUE TITLE
NPM Install always hangs on my account

### ISSUE THREAD

**Issue by David2BV** [stackblitz/bolt.new#2748]
### Describe the bug

NPM Install always hangs on my account

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-egyxfd

### Steps to reproduce

Anytime I ask it to compile code it gets no further than NPM Install and the wheel keeps spinning

### Expected behavior

Should compile and run - doesnt

### Screen Recording / Screenshot

<img width="1156" alt="Screenshot 2024-11-19 at 12 36 09" src="https://github.com/user-attachments/assets/09883d01-0593-4b6a-8d79-1d4f15775d6b">

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = David2BV
Chat ID = 3b35996a79c2
```

**Comment by endocytosis** [comment]
Hi @David2BV, 

Sorry to hear this! Are you able to try opening the project in Chrome or Firefox and seeing if the problem persists? Bolt works best with those browsers.

**Comment by endocytosis** [comment]
npm issues, along with potential workarounds, are being tracked here: #2021. Hope this helps!
