### ISSUE TITLE
always dont complete the task, a disaster

### ISSUE THREAD

**Issue by martinsantos** [stackblitz/bolt.new#2749]
### Describe the bug

disaster, i want my money back, never work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nokhmu

### Steps to reproduce

disaster, i want my money back

### Expected behavior

disaster, i want my money back

### Screen Recording / Screenshot

disaster, i want my money back

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82764567,
  "usedJSHeapSize": 79988843,
  "jsHeapSizeLimit": 4294705152
}
Username = martinsantos
Chat ID = baf2c9ac2664
```

### Additional context

disaster, i want my money back

**Comment by endocytosis** [comment]
Sorry to hear this! Refund requests are handled through hello@stackblitz.com.
