### ISSUE TITLE
Complaint Regarding Excessive Token Consumption

### ISSUE THREAD

**Issue by maxoldnr** [stackblitz/bolt.new#2752]
Hello,

I am writing to report a significant issue regarding the excessive consumption of tokens while using your AI service. I believe I have wasted a considerable amount of tokens due to repetitive malfunctions of the AI.

Specifically, the AI frequently loops, asking the same questions or repeating the same answers without providing any meaningful solutions to my requests. This has resulted in the rapid depletion of over half of my tokens with little to no value in return.

Here is a summary of my situation:

I initially subscribed to a €20 plan, which was entirely consumed in less than 24 hours due to the issues mentioned.
I then upgraded to a €50 plan, but the same problems persisted, leading to a swift loss of tokens.
Hoping for an improvement, I subscribed to a €100 monthly plan. Unfortunately, the issues continued, with the AI repeating the same responses or looping endlessly.
Currently, I have almost no tokens left, and I am being asked to upgrade to a higher plan costing €200, which I categorically refuse. I believe I have already invested a substantial amount for a service that has not met my expectations.

I kindly request that my account be credited with the tokens I have unjustly lost, totaling over 60 million tokens. I also urge you to address the AI's functionality issues.

I am counting on your collaboration to resolve this matter promptly and effectively.

Best regards,

Max

**Comment by endocytosis** [comment]
Appreciate the feedback and sorry to hear about this! Refund requests are handled through hello@stackblitz.com. At times, there are programming challenges that are too complex for the AI to solve, and manual intervention is required to prevent excessive token consumption. This page [here](https://github.com/stackblitz/bolt.new/issues/678) contains information on maximizing token efficiency. More generally, the [Bolt Help Center](https://support.bolt.new) contains information on using Bolt most effectively. Hope this helps!
