### ISSUE TITLE
I keep asking for the site url and claim url and it takes 10 times to get it

### ISSUE THREAD

**Issue by rickm1972** [stackblitz/bolt.new#2753]
### Describe the bug

I keep asking for the site url and claim url and it takes 10 times to get it

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ujw8mn

### Steps to reproduce

Ask it to give you the site url and claim url 

### Expected behavior

The urls

### Screen Recording / Screenshot

Let me wait for the deployment to complete and I'll provide you with both the live site URL and claim URL.

I keep getting this message even though the deploy is done...i am burning through tokens for nothing

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 148224871,
  "usedJSHeapSize": 113472795,
  "jsHeapSizeLimit": 4294705152
}
Username = rm2024!
Chat ID = bf8f97977443
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020

**Comment by rickm1972** [comment]
perfect thanks guys!
