### ISSUE TITLE
Blank page always a blank page ....

### ISSUE THREAD

**Issue by MichelCardinal** [stackblitz/bolt.new#2756]
### Describe the bug

Everything I ask your system to create always results in a blank page, even the simplest thing.
I asked it for a basic application to input a list of names, and every time it gives me files that don’t work.

I paid $500 for a subscription, and for the past three days, I haven’t been able to create anything at all.

Although it works in the preview on your website, once the project is compressed into a .zip file and downloaded to my computer, nothing works.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u1qgvw

### Steps to reproduce

I am sending you herewith what it created for me.

### Expected behavior

I just wanted to create a list of names.

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = MichelCardinal
Chat ID = fdf858e5edbc
```

### Additional context

[project-bolt-sb1-u1qgvw.zip](https://github.com/user-attachments/files/17817031/project-bolt-sb1-u1qgvw.zip)

**Comment by kc0tlh** [comment]
@MichelCardinal FYI we recommend Using a Chromium-based browser (see #2796).

What you're describing sounds like an issue with your local environment if it is working properly inside of Bolt.new but not on your local machine, and that is beyond the scope of what I'm able to provide support for. 

Have you tried deploying directly to Netlify from within the Bolt application? Please give that a try from a Chromium-based browser, and let us know if you're still experiencing any issues!
