### ISSUE TITLE
You have reach your rate limit

### ISSUE THREAD

**Issue by thornzz** [stackblitz/bolt.new#276]
I purchased a Pro subscription for Bolt.new 3-4 days ago to test it out. I've only created 3-4 simple dashboard designs and requested code refactoring for my C# code 2-3 times. And this morning, just when I really needed it, I hit a Rate Limit and was asked to continue through the code editor. You must be joking. 10 million tokens are promised, and it's being claimed that I've used up that many tokens with just a few queries. I'm requesting support to resolve this issue

**Comment by sulco** [comment]
Hey, @thornzz! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're improving the bolt experience!

**Comment by znuttyone** [comment]
Has anyone found a way to even view the tokens available vs used , or rate actual against usage ?  I see no place in the platform to check this , for all you know it’s made up 🤣🤷‍♂️
