### ISSUE TITLE
Bolt cannot Fix the problem in "npm install" iteratively

### ISSUE THREAD

**Issue by mlatif2000** [stackblitz/bolt.new#2764]
### Describe the bug

I face iteratively the same error in "npm install" and Bolt cannot resolve it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tngjtq

### Steps to reproduce

![image](https://github.com/user-attachments/assets/fa8faee5-ec8d-48da-9bed-c46020a54f86)

### Expected behavior

Same error is repeated

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/b9495c14-869a-4312-b64e-3431a5cd9136)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59041643,
  "usedJSHeapSize": 50281591,
  "jsHeapSizeLimit": 4294705152
}
Username = mlatif2000
Chat ID = 7c936a0adda7
```

### Additional context

Nil

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2021).
