### ISSUE TITLE
Last Session Missing

### ISSUE THREAD

**Issue by cmullins70** [stackblitz/bolt.new#2765]
### Describe the bug

I ran out of tokens, upgraded to the Pro plan, and when I returned, the last session was missing from the chat history. (!!) Lost time and lost tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rpz6qy

### Steps to reproduce

I can't reproduce as the deleted code is gone.

### Expected behavior

I expected my chat history to be up to date after upgrading.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 136197730,
  "usedJSHeapSize": 129432818,
  "jsHeapSizeLimit": 4294705152
}
Username = cmullins70
Chat ID = 410590c66edb
```

**Comment by endocytosis** [comment]
Sorry to hear this! Are you able to find your past project by going to [stackblitz.com](stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection?

**Comment by cmullins70** [comment]
No - only able to see the one project for this
