### ISSUE TITLE
PREVIEW WHITE

### ISSUE THREAD

**Issue by frederickauffmann** [stackblitz/bolt.new#2766]
### Describe the bug

Hello! Need help please! I cant se anything on preview mode. How can I move forward? (I’m using Chrome and safari).

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6cvrff

### Steps to reproduce

Just add my prompt for an app repository like a YouTube tutorial. The code is well done, the preview window opens automatically but stay in white.

### Expected behavior

I cant visualize the code preview.. I tried few time but always in white. The system open the preview but only white.

### Platform

```
Browser name = Safari
Full version = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPad; CPU OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/131.0.6778.73 Mobile/15E148 Safari/604.1
performance.memory = undefined
Username = frederickauffmann
Chat ID = 7f6da4d2f1f2
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. Make sure you are working in Chrome or Firefox as Bolt works best in those browsers. We appreciate your patience as improvements continue to be made!
