### ISSUE TITLE
I'm paying my bills, but I'm immediately subject to restrictions.

### ISSUE THREAD

**Issue by leeogi** [stackblitz/bolt.new#277]
### Describe the bug

Today, I joined the $9 per month plan. However, it was supposed to support up to 10m tokens, but after a few conversations I was hit by the limit.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

nothing

### Expected behavior

nothing

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sulco** [comment]
Hey, @leeogi and @ningyanhui! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. _So yes, this was a bug_.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being our early adopters and for your patience as we're improving the bolt experience!
