### ISSUE TITLE
after adding new features, the site stopped working and now there is only a white screen

### ISSUE THREAD

**Issue by sashasmeet** [stackblitz/bolt.new#2770]
### Describe the bug

after adding new features, the site stopped working and now there is only a white screen. please help me. my site doesnt work correctly and shows only white screen
![Скриншот 19-11-2024 213756](https://github.com/user-attachments/assets/75449dc7-d5a9-4215-b62d-5b73fd7c94a5)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qqbnvf

### Steps to reproduce

there are no errors in the code, but all the data that was there before has disappeared and now I see only a white screen. help me

### Expected behavior

I hope that my site will start working again and not show a white screen.

### Screen Recording / Screenshot

![Скриншот 19-11-2024 213756](https://github.com/user-attachments/assets/4cfcba19-80e5-463b-bc6e-e9ce2633c478)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59004504,
  "usedJSHeapSize": 56585708,
  "jsHeapSizeLimit": 2160066560
}
Username = w1wang
Chat ID = 96f6e6678922
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. Make sure you are working in Chrome or Firefox as Bolt works best in those browsers. We appreciate your patience as improvements continue to be made!
