### ISSUE TITLE
boltsync only shows 30 projects in dropdown

### ISSUE THREAD

**Issue by BeastCode** [stackblitz/bolt.new#2771]
### Describe the bug

I went to https://boltsync.mystify.tech/ to sync my bolt project with github. My bolt project is public so I expected to see it. But is seems like the drop down for repository only shows a certain number of projects, there is no way for me to scroll further down (yes I have quite a few projects) The dropdown only shows 30 projects.

### Link to the Bolt URL that caused the error

boltsync.mystify.tech

### Steps to reproduce

Set up a project in bolt
open stackblitz and upload it it to github
Go back to bolt and make more changes
Open boltsync.mystify.tech to upload latest changes.

Only 30 projects are visible in dropdown

### Expected behavior

I expected all public projects to be visible in the dropdown and not just 30

And as future enhancements it would be nice to have access to private projects too

### Platform

Chrome

**Comment by endocytosis** [comment]
Appreciate the feedback! It looks like that application was developed by a member of the community, which is awesome! I would reach out the them for feedback regarding their project. The team is hard at work improving GitHub integration, which is being tracked here: #2367.

**Comment by BeastCode** [comment]
Okay thanks, I had no clue., then just please close this one, looking forward to a more official integration one day!

**Comment by BeastCode** [comment]
FYI: I found the person that created him and sent him an email with the issue

**Comment by endocytosis** [comment]
Sounds great!

**Comment by BeastCode** [comment]
Update 2: He responded and fixed the issue, the api limited the response to 30... He fixed the issue and I've verified it with my repo :)

**Comment by endocytosis** [comment]
Awesome, glad to hear it!
