### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by Lightbaby** [stackblitz/bolt.new#278]
### Describe the bug

I subscribe but still  rate limit

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7a3bte

### Steps to reproduce

start Chat
“”You have hit the rate limit. You can continue to code for free in the editor.“”

### Expected behavior

Not limit

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sulco** [comment]
Hey, @Lightbaby! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're improving the bolt․new experience!
