### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by smarderny** [stackblitz/bolt.new#2783]
### Describe the bug

see history in movie calendar app

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fxgkui

### Steps to reproduce

anything I do doesnt actually work

### Expected behavior

working

### Screen Recording / Screenshot

<img width="1512" alt="Screenshot 2024-11-19 at 4 40 03 PM" src="https://github.com/user-attachments/assets/966b1a23-ddfa-40d6-af30-0326158c430f">

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116356500,
  "usedJSHeapSize": 111895704,
  "jsHeapSizeLimit": 4294705152
}
Username = smarder
Chat ID = a1c9509717ff
```

### Additional context

please refund me

**Comment by endocytosis** [comment]
Sorry to hear this! This issue with a white screen, along with potential workarounds, is being tracked here: #1791. Refund requests are handled through hello@stackblitz.com.
