### ISSUE TITLE
Can't deal with supabase?

### ISSUE THREAD

**Issue by romainboyer** [stackblitz/bolt.new#2784]
### Describe the bug

At first, the app has stored data locally in the browser. Then I noticed that and asked to use a database, the AI suggested Supabase, which I validated. Then the AI seems to be unable to change that and to fix the issues around that. I have this kind of errors for most of my entities.
Now, I am stuck, have used most of my credits, and I'm not sure the solution can be a good fit for my project if we can have dead ends like that.
I think that from start, it should ask what kind of data storage we want because I thought I finished my app and then noticed that with another browser it didn't work and now I'm stuck. So much time lost.
Let me know if you think there is a solution to get rid of that error without spending millions of tokens again?
For the rest, you app is very very promising, congrats.
Thanks

"❌ Error:"{message: "invalid input syntax for type uuid: "1"", code: "22P02", details: Object, hint: Object}
   at debugSupabase (/src/lib/supabase.ts?t=1732048904159:15:15)
   at async fetchUserActivities (/src/store/activitiesStore.ts?t=1732048924122:14:22)
2
"Erreur lors de la récupération des activités:"{code: "22P02", details: Object, hint: Object, message: "invalid input syntax for type uuid: "1""}
   at fetchUserActivities (/src/store/activitiesStore.ts?t=173204892

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tekwn9

### Steps to reproduce

just run the app

### Expected behavior

Identify the error

### Screen Recording / Screenshot

-

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 104287552,
  "usedJSHeapSize": 100376116,
  "jsHeapSizeLimit": 4294705152
}
Username = romainboyer
Chat ID = 0f8998782709
```

### Additional context

-

**Comment by endocytosis** [comment]
Sorry to hear this but glad you are liking Bolt overall! You could initially try pasting the error message into the Bolt chat to see if it is able to resolve the issue. However, if Bolt is repeatedly unable to resolve this error, manual intervention is required to prevent excessive token usage. 

Unfortunately we don't have the resources to deal with individual programming problems. Next steps for developing your project are further described here: #2310. In this case, you may need to consult the official [Supabase](https://supabase.com/docs) documentation. The [Bolt Help Center ](https://support.bolt.new) contains a number of resources on using Bolt most effectively, including tutorials on setting up Supabase. Hope this helps!
