### ISSUE TITLE
Rate Limit all tokens already used

### ISSUE THREAD

**Issue by GoThundercats** [stackblitz/bolt.new#279]
### Describe the bug

I upgraded to pro yesterday only used it for half a day, not sure how i could have used all the tokens already, is there a daily limit and does it go by a certain time-zone? because its the next day for me.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jbyboy

### Steps to reproduce

just signed in saw the message

### Expected behavior

no rate limit would be  the best or a display

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sunlin-xiaonai** [comment]
me too

**Comment by violacase** [comment]
me too

**Comment by ningyanhui** [comment]
me too

**Comment by margorpaami** [comment]
me too

**Comment by sulco** [comment]
Hey, @GoThundercats, @sunlin-xiaonai, @violacase, @ningyanhui and @margorpaami! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being our early adopters and for your patience as we're improving the bolt․new experience!

**Comment by znuttyone** [comment]
Where can you even see the limit and the actual usage in the platform, I hit it in 5 mins of work .. useless compared to Replit.com

**Comment by kc0tlh** [comment]
@znuttyone Settings > Tokens, in lower left corner of the app

@yasinkocak our plans are monthly. Go to https://bolt.new/?showPricing=true to see when your tokens will refresh/upgrade to a higher tier plan with more tokens.
