### ISSUE TITLE
Love bolt.new but hate it when it loses all my work

### ISSUE THREAD

**Issue by sriniatyoubuyweship** [stackblitz/bolt.new#2793]
### Describe the bug

github : sriniatyoubuyweship

I have been conversing with bolt and built the whole project front end. bolt.new was getting stuck, so had to refresh the page and it lost all the files i have built over hours and spent tons of tokens .. you can check logs. 

its unacceptable to lose work.. it has to save my work to point built.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vite-react-oj9jkm

### Steps to reproduce

there are no steps.. it just lost all my work.. it had a landing page , login flow etc

### Expected behavior

it cant lose my work if page is refreshed

### Screen Recording / Screenshot

N/A

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71902998,
  "usedJSHeapSize": 49578598,
  "jsHeapSizeLimit": 4294705152
}
Username = sriniatyoubuyweship
Chat ID = 2970e8a2b5a5
```

**Comment by endocytosis** [comment]
Sorry to hear this! Are you able to find your past projects by going to [stackblitz.com](https://stackblitz.com), clicking Collections on the left-hand side of the page, and then opening Bolt collection? 

Alternatively, in Bolt, you can go to Settings > Backups to revert your chat to a prior state.

**Comment by sriniatyoubuyweship** [comment]
There are no chats either and nothing in collections as well. This is such
an amazing product  but just persistence of project is super flaky.. please
fix it.

**Comment by endocytosis** [comment]
Apologies for the frustration! We appreciate your patience as the team continues to make improvements.
