### ISSUE TITLE
Complicated app, persistent errors, lots of tokens

### ISSUE THREAD

**Issue by dmajkut** [stackblitz/bolt.new#2794]
Hi - I just wanted to provide some feedback. I love the tool, and it has been amazing to try and build custom CRM software for my role that doesn't exist on the market. 

I am not a developer, so much of this is being done through trial and error. I am currently trying to connect Supabase (using the helpful prompts from your youtube channel!) and the changes are not working correctly. Because what I have been building is complicated, every single prompt and response is costing me 100k tokens, which is really painful and relatively expensive (for something I am just playing with). 

I don't know a way around this yet, but wanted to flag that this is an area where someone can quickly become frustrated and drop out.

**Comment by endocytosis** [comment]
Appreciate the feedback! The team is hard at work continuing to make integration with databases, such as Supabase, more seamless.
