### ISSUE TITLE
Cant show simple world map on screen

### ISSUE THREAD

**Issue by hjpjanssen** [stackblitz/bolt.new#2795]
### Describe the bug

I asked bolt to show a world map on the screen with every continent a different color. It shows just a blank screen. Tried it 10 times. Asked Bolt to solve but never was able to show a map. Simple stuff. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2w4r5z

### Steps to reproduce

just run the app

### Expected behavior

show a map.

### Screen Recording / Screenshot

just a blank screen

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100657017,
  "usedJSHeapSize": 84721025,
  "jsHeapSizeLimit": 4294705152
}
Username = ericjanssen
Chat ID = 1d154a31a928
```

**Comment by endocytosis** [comment]
Appreciate the feedback! At times, there are programming challenges that are too complex for AI to solve, and interacting with more complicated libraries (such as displaying a map with functionality) may require manual intervention and consulting the official documentation, as described here: #2310. If there are specific error messages you are receiving, you can try pasting those into the chat to see if that resolves the issue, however, if the AI is repeatedly unable to solve the problem then manual intervention is required. Hope this helps!

**Comment by hjpjanssen** [comment]
Thanks. I understand, but i am a programming novice, so cant solve myself. 

I agree that its quite a complex request, but I tried the same with Loveable. It succeeded in making a map visible and selectable (even hovering a country worked), but in the end it didnt get it fully to work.
