### ISSUE TITLE
Constantly recurring problem

### ISSUE THREAD

**Issue by samsunga31967** [stackblitz/bolt.new#2798]
### Describe the bug

There always seems to be a problem and you're going around in circles trying to solve it. First comes:

Let's fix the missing getCurrentUser export in the supabase service. Here's the corrected version:

Fix Supabase Service

src/services/supabase.ts
This update:

Adds the missing getCurrentUser function
Properly exports all necessary functions
Includes proper error handling
Maintains type safety with TypeScript interfaces
The application should now work without the "getCurrentUser" error.

and then, after you fix that one, comes:

email rate limit exceeded

Then you do it again:

Let's fix the email rate limit issue by modifying the Supabase authentication settings and updating our registration flow. Here's what we'll do:

Fix Email Authentication

src/services/supabase.ts
This update:

Removes email verification requirement
Checks for existing email before registration
Auto signs in the user after successful registration
Maintains all other functionality
You should now be able to register without email verification issues. The same email can be used for multiple children since we're not requiring email verification.

And then we come back to:

Let's fix the missing getCurrentUser export in the supabase service. Here's the updated version:

Fix Supabase Service

src/services/supabase.ts
This update adds the missing getCurrentUser function and ensures all necessary exports are available. The application should now work without the error.

The whole thing goes on like this and we don't make any progress while my tokens keep getting fewer and fewer.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wwkmwe

### Steps to reproduce

Navigate to the registration page of the application.
Enter the following details:
Name: Damon Michen-Gruber
Email: samsunga31967@gmail.com
Password: 12345678
Grade: 6th Grade
Click on Register.
Multiple issues occur:
Error 1: "Password is known to be weak and easy to guess, please choose a different one."
Error 2: "Error sending confirmation email."
Error 3: "SyntaxError: The requested module '/src/services/supabase.ts?t=1732064979639' does not provide an export named 'resetPassword'."
Error 4: "over_email_send_rate_limit."

### Expected behavior

Users should be able to successfully register.
Email verification should be disabled, allowing children or parents to reuse the same email address for multiple accounts.
Passwords should only require a minimum of 6 characters without additional complexity checks.
Users should be automatically logged in after registration.

### Screen Recording / Screenshot

![Screenshot 2024-11-20 023312](https://github.com/user-attachments/assets/9745125c-d30b-425a-ae71-11d7aeeb98da)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112774793,
  "usedJSHeapSize": 107401417,
  "jsHeapSizeLimit": 4294705152
}
Username = samsunga31967
Chat ID = 5fa46868c7c9
```

### Additional context

Additional Context
Problem Summary:

Fixes applied to the authentication system repeatedly cause a loop of issues.
Resolving one issue (e.g., missing exports) causes others (e.g., email confirmation errors) to resurface.
Changes like adding resetPassword or getCurrentUser exports do not persist or conflict with other fixes.
Priorities:

Disable email verification to simplify the registration process and support families registering multiple children under the same email.
Simplify password requirements to ensure children can easily create accounts (minimum 6 characters).
Resolve API export issues for functions like resetPassword and getCurrentUser so they work consistently.
Avoid email rate limits by allowing multiple accounts with the same email and either increasing the rate limit or bypassing verification entirely.
Ethical Considerations:

The platform targets children and families.
Children should not face technical barriers during registration.
Parents should be able to register multiple children using a single email address.

**Comment by samsunga31967** [comment]
I would be very happy about a quick processing, solution and refund of tokens (also because of the many hours I lost) in order to solve the recurring problem - which I was unfortunately unable to solve.

Best regards,

Claudia Michen-Gruber

**Comment by endocytosis** [comment]
Hi @samsunga31967, 

Sorry to hear about this! At times, there are programming challenges that are too complex for the AI to solve and manual intervention is required. Unfortunately, we don't have the resources to troubleshoot individual project code. You can read more about next steps here: #2310. 

Refund requests are handled through hello@stackblitz.com.

**Comment by samsunga31967** [comment]
The whole thing goes on like this and we don't make any progress while my tokens keep getting fewer and fewer.
