### ISSUE TITLE
failed deployment repeatedly

### ISSUE THREAD

**Issue by deessee** [stackblitz/bolt.new#280]
### Describe the bug

failed deployment repeatedly

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sguudw

### Steps to reproduce

ask to deploy for testing

### Expected behavior

deployment

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57516635,
  "usedJSHeapSize": 50995019,
  "jsHeapSizeLimit": 4294705152
}
Username = deessee
Chat ID = 8666bfac2e39
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
