### ISSUE TITLE
Not fetch earlier project

### ISSUE THREAD

**Issue by saurav389** [stackblitz/bolt.new#281]
### Describe the bug

I have made a project management app yesterday. But today not showing any project there in bolt.new. And also showing i have used all my token. But how i can use i millioun token in one day in a small project.

### Link to the Bolt URL that caused the error

https://bolt.new

### Steps to reproduce

nothing

### Expected behavior

should show my all previous project made through prompt in bolt.new

### Screen Recording / Screenshot

No recording

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

nothing

**Comment by sulco** [comment]
Hey, @saurav389! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're improving the bolt․new experience!
