### ISSUE TITLE
Preview doesn't show anything 

### ISSUE THREAD

**Issue by Pandemoniumhk** [stackblitz/bolt.new#2812]
### Describe the bug

Preview doesn't show anything. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1lymtg?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

Click on Preview

### Expected behavior

Having a preview.

### Screen Recording / Screenshot

<img width="1368" alt="Screenshot 2024-11-20 at 1 16 43 PM" src="https://github.com/user-attachments/assets/bf7f2f8a-b58b-457f-ba20-b69a00fca913">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103915058,
  "usedJSHeapSize": 97124934,
  "jsHeapSizeLimit": 2160066560
}
Username = HugoMeyer12
Chat ID = 95b4be9f4baf
```

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it here: #1791. You can also try typing “npm run dev” in the Bolt console to see if that resolves the issue. Also, selectively disable browser extensions, especially ad blockers, to see if that resolves the issue. Make sure you are working in Chrome as Bolt works best in that browser. We appreciate your patience as improvements continue to be made!

**Comment by samdenty** [comment]
hi there when you get the white screen could you send a screenshot of your browser devtools?

make sure this setting is enabled so we can see everything

![CleanShot 2024-11-22 at 08 54 57@2x](https://github.com/user-attachments/assets/0e0c1074-fdf0-4236-8f07-7716e394f8cb)

Specifically do you see `Minified React error #418` that'd be helpful to know
