### ISSUE TITLE
Pro Tokenz haven't received.

### ISSUE THREAD

**Issue by suradreamz** [stackblitz/bolt.new#282]
### Describe the bug

I just upgraded & pro tokenz haven't received. & for a simple output it's spending 1000s tokens, there's must be an issue, please check & solve this.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gbjbdw

### Steps to reproduce

I just upgraded & pro tokenz haven't received. & for a simple output it's spending 1000s tokens, there's must be an issue, please check & solve this.

### Expected behavior

I just upgraded & pro tokenz haven't received. & for a simple output it's spending 1000s tokens, there's must be an issue, please check & solve this.

### Screen Recording / Screenshot

I just upgraded & pro tokenz haven't received. & for a simple output it's spending 1000s tokens, there's must be an issue, please check & solve this.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 118341902,
  "usedJSHeapSize": 104374154,
  "jsHeapSizeLimit": 2172649472
}
Username = suradreamz
Chat ID = 0a74ccf7eefb
```

**Comment by sulco** [comment]
Hey, @suradreamz! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!

**Comment by suradreamz** [comment]
Thanks mate,
& Please let me know how do you count tokens?
