### ISSUE TITLE
why install npm can never be solved? are you trying to scam my tokens out by repetitively failing to solve the same problem?

### ISSUE THREAD

**Issue by BruceChanceBeatverse** [stackblitz/bolt.new#2820]
### Describe the bug

why install npm can never be solved? are you trying to scam my tokens out by repetitively failing to solve the same problem?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jhsrqp

### Steps to reproduce

why install npm can never be solved? are you trying to scam my tokens out by repetitively failing to solve the same problem?

### Expected behavior

why install npm can never be solved? are you trying to scam my tokens out by repetitively failing to solve the same problem?

### Screen Recording / Screenshot

why install npm can never be solved? are you trying to scam my tokens out by repetitively failing to solve the same problem?

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 232566269,
  "usedJSHeapSize": 207091441,
  "jsHeapSizeLimit": 4294705152
}
Username = BruceChanceBeatverse
Chat ID = 70de5747b477
```

### Additional context

why install npm can never be solved? are you trying to scam my tokens out by repetitively failing to solve the same problem?

**Comment by endocytosis** [comment]
This is a known issues that is being track here: #2021.
