### ISSUE TITLE
Wong language code returning asked for flutter/dart and returns javascript code

### ISSUE THREAD

**Issue by mayurd2019** [stackblitz/bolt.new#2823]
### Describe the bug

I have asked for flutter-dart code it is returning javascript code which is not really acceptable

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s2bvqc

### Steps to reproduce

1. give prompt for create flutter-dart app
2. you will found it is returning javascript app

### Expected behavior

It should return dart structure

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 51123551,
  "usedJSHeapSize": 49876879,
  "jsHeapSizeLimit": 4294705152
}
Username = mayurd2019
Chat ID = 4d40d8a2e638
```

### Additional context

Error:
```
You cancelled this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Bolt currently does not support Dart and Flutter.
