### ISSUE TITLE
i got this error: Something went wrong whilst creating your site on Netlify.

### ISSUE THREAD

**Issue by helmik514** [stackblitz/bolt.new#283]
### Describe the bug

i keep gettings this error which is completely preventing me from deploying: Something went wrong whilst creating your site on Netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vite-react-izwjcd

### Steps to reproduce

deploy the site either with the button or into the chat. it works once in so many tries

### Expected behavior

to give error

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86456554,
  "usedJSHeapSize": 82410622,
  "jsHeapSizeLimit": 2172649472
}
Username = helmik514
Chat ID = 08464042ea36
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
