### ISSUE TITLE
Device

### ISSUE THREAD

**Issue by victorlfb** [stackblitz/bolt.new#2831]
### Describe the bug

Once connected, the device do not show up.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dkjqa5

### Steps to reproduce

Scan the QR code
Click on my phone "Tap to open"

### Expected behavior

Once connected, the device do not show up.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52642673,
  "usedJSHeapSize": 50898085,
  "jsHeapSizeLimit": 2160066560
}
Username = victorlfb
Chat ID = 6498add06d5e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately, we don't have the resources to assist with the code for individual projects. You can read more about continuing to develop your project here: #2310.
