### ISSUE TITLE
Error on completing code with a simple prompt request

### ISSUE THREAD

**Issue by Donubu** [stackblitz/bolt.new#2837]
### Describe the bug

After a single prompt, the returned code is abbreviated (in a comment) and omitted causing fatal error:

`// Previous code remains the same until the imageSequence array

// Image sequence array
const imageSequence = Array.from({ length: 65 }, (_, i) => 
  `https://${i+2}.png`
);

// Rest of the code remains the same`

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-5qe5jg

### Steps to reproduce

1. Make a single prompt in a extense project (more than 10 pages)

### Expected behavior

Complete all the code without omite part of it.

### Platform

```
Browser name = Chrome
Full version = 133.0.0.0
Major version = 133
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87267756,
  "usedJSHeapSize": 80975048,
  "jsHeapSizeLimit": 4294705152
}
Username = Donubu
Chat ID = 30b4f58c342b
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2862.
