### ISSUE TITLE
limit reached???

### ISSUE THREAD

**Issue by violacase** [stackblitz/bolt.new#284]
I have a paid account (9$ pm) I just started to work today and the system says i reached the limit. I've done NOTHING! What is the matter?

**Comment by jdriesen** [comment]
Exactly the same situation here...

**Comment by jwhaz** [comment]
same here..

**Comment by superresistant** [comment]
> I've done NOTHING

You didn't use the app at all? 
If you used it, what did you do ?

**Comment by Exodo0** [comment]
Same here. I only used it for 5 to 10 minutes and reached the limit.

**Comment by jdriesen** [comment]
I used it for about 1 or 2 hrs... and all of a sudden... "limit reached"

**Comment by ningyanhui** [comment]
I used it for about 1 or 2 hrs... and all of a sudden... "limit reached"

**Comment by reech1** [comment]
Same here..its either a bug or is happening because the code reloads entirely for every modification

**Comment by Exodo0** [comment]
They should add a Token's Counter. You only realize that you reached the limit with the message.

**Comment by 1WorldCapture** [comment]
+1

**Comment by mrsunshine** [comment]
+1

**Comment by swcrazyfan** [comment]
I'm thinking this is a bug. We have no idea how to check if we've used our limit, but it seems many of us are having this problem.

**Comment by mrsunshine** [comment]
`{"code":"rate-limited","message":"You have hit the rate limit. You can continue to code for free in the editor.","providerLimitHit":false,"isRetryable":true,"tokenStats":{"totalToday":0,"totalThisMonth":793331,"maxPerDay":10000,"maxPerMonth":10000,"nextTier":null,"overflow":{"available":0,"used":0}}}`

Seems to be a Bug!

**Comment by reech1** [comment]
Everyone sees to be having the same issue .. even with $9/month and 10MM tokens... they have to fix this

**Comment by Tzar38** [comment]
please fix this problem. just paid 9/month for nothing.

**Comment by gameloft333** [comment]
why it happen? we're premium developers who had 10m tokens, I don't think we reached the max tokens indeed, please fix this issue since it will affect the work we're doing now.

And one more thing, @Team,

PLEASE BE MORE CAREFUL TO RELEASE ANY NEW FEATURES THAT YOU WANNA IMPROVE WHICH ARE APPROVED IN SANDBOX MODE BEFORE INDEED, TO AVOID AFFECTING THE USERS EXACTLY. THK YOU.

**Comment by nikolapalibrk** [comment]
Same issue here, this is just unacceptable. I don't see any way to contact them, anyone know support mail?

**Comment by sulco** [comment]
Hey, everyone! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. So yes, this was a bug.

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being our early adopters and for your patience as we're ironing out the experience on bolt!
