### ISSUE TITLE
Switching audio to active/main interface

### ISSUE THREAD

**Issue by geeAGI** [stackblitz/bolt.new#2840]
### Describe the bug

We have set up main player to stream music...the user can then browse and select another song which should now switch the new the audio to active/main interface. We keep getting errors for the switch in spite of a number of fixes. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xvtpu9

### Steps to reproduce

Click any secondary song from main page. switch does not happen neither does it play from existing position.

### Expected behavior

User clicks secondary. The song swaps to the main interface and autoplays.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 129096064,
  "usedJSHeapSize": 123437324,
  "jsHeapSizeLimit": 4294705152
}
Username = geeAGI
Chat ID = c6fb3bb3b31c
```

**Comment by endocytosis** [comment]
Sorry to hear this! While we would love to individually help our users resolve programming challenges, unfortunately, the resources required don't make that a possibility. This page [here](https://github.com/stackblitz/bolt.new/issues/2310) contains some information on continuing to develop your project. Hope this helps!
