### ISSUE TITLE
logo and other error

### ISSUE THREAD

**Issue by schechtereddie** [stackblitz/bolt.new#2846]
### Describe the bug

when given a logo to use it builds out every thing but cant put the logo file in so it makes a place holder of my logo in text 
then when asked to fix it and you give it the logo file again it does the same thing 
![Untitled design](https://github.com/user-attachments/assets/c2a42124-7717-4f50-bd06-6c67dd9312d3)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-42n3q2

### Steps to reproduce

will you put the logo im giving you in the spots the say schechter customs logo 

### Expected behavior

to have the logo that was in the png file i ghave it  ot be put in the spots that said schechter customs logo 

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = schechtereddie
Chat ID = e91bd95b1e05
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Currently, Bolt does not support image uploads to its file directory. We are aware of this issue and are tracking it here: #1809. In the meantime, you can open this project in StackBlitz and drag and drop image files into the StackBlitz file system to continue development there. Hope this helps!
