### ISSUE TITLE
Could not find project

### ISSUE THREAD

**Issue by pat3dx** [stackblitz/bolt.new#285]
### Describe the bug

There are many bugs in your application.
The most annoying bug is that every day when I reopen Bolt, it is unable to find the project and it opens the page:
Could not find project
While the day before, everything was working perfectly.
So, I have to use all my free credits for it to fix the problem...
You must fix this bug immediately.

For your subscriptions, there is also a problem.
I use Claude dev, Cursor, etc... to develop my AI Apps.
You only give 10M tokens in all your paid subscriptions.
10M tokens is what is used almost every day to develop a complete App.
For my part, with Claude dev and with GPT-4o, I use on average 5-7M tokens per day to develop my current SaaS AI Ebook generator project.
Basically, taking a subscription to your tool would mean no longer having tokens and therefore no longer being able to use your app, after 2-3 days.
No point.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yrm5vy

### Steps to reproduce

Go to my project url on your app: https://bolt.new/~/sb1-yrm5vy
and the app start the server and the page: Could not find project open.
It happens every day when I want to start working on my app again.

### Expected behavior

Every day when I want to start working on my project on your site again, your tool is unable to find my project, while the day before, everything was working perfectly.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@pat3dx thanks for the feedback!

Chat persistence is being tracked in #39 

New plans are available with more tokens in "My Subscription" in the lower left corner of the app!
