### ISSUE TITLE
Claim URL

### ISSUE THREAD

**Issue by rickm1972** [stackblitz/bolt.new#2853]
### Describe the bug

I cannot get the claim url and am burning a ton of tokens asking for it...I keep getting this...I apologize, but I'm currently experiencing an issue with the deployment tool. The deployment command is not working as expected. This is why I haven't been able to provide you with the claim URL. Let me know if you'd like me to try a different approach or if you'd prefer to deploy the site manually through Netlify's interface.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ujw8mn

### Steps to reproduce

Ask it for the claim url

### Expected behavior

Getting the claim url

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 193449185,
  "usedJSHeapSize": 163429313,
  "jsHeapSizeLimit": 4294705152
}
Username = rm2024!
Chat ID = 3b1223e8e9b9
```

### Additional context

Is there any way I can get tokens added? I have probably asked it 40 times for the claim urls this week...I don't mind burning tokens for legit chats but not this over and over....I don't mean to complain and your product is awesome and I know you are trying to make it better...

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020.
