### ISSUE TITLE
Dont install npm and setup-nativescript-stackblitz && ns preview

### ISSUE THREAD

**Issue by lizdejesus711** [stackblitz/bolt.new#2856]
### Describe the bug

Dont install npm and setup-nativescript-stackblitz && ns preview

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nativescript-js-fzc9tn

### Steps to reproduce

Dont install npm and setup-nativescript-stackblitz && ns preview

### Expected behavior

Dont install npm and setup-nativescript-stackblitz && ns preview

### Screen Recording / Screenshot

Dont install npm and setup-nativescript-stackblitz && ns preview

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64676567,
  "usedJSHeapSize": 54782039,
  "jsHeapSizeLimit": 4294705152
}
Username = lizdejesus711
Chat ID = 3ad0e669ed8e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2021.
