### ISSUE TITLE
Rate limit reached

### ISSUE THREAD

**Issue by Exodo0** [stackblitz/bolt.new#286]
I paid the 9 USD subscription. I didn't use it for long (about 10 minutes) and it already says You've used all your remaining tokens.

**Comment by 1WorldCapture** [comment]
+1, just the system tells me my 10M tokens are used up... Crazy!

**Comment by jdwd40** [comment]
paid the $9 sub also ... I hit it after a couple of hours ... I was creating a small frontend for a rest based api ... at first I was impressed and all went well but as I started adding to the app, the app stopped deploying to netlifiy last night .... today it says I've hit the rate limit but there were no warnings last night ...

**Comment by sulco** [comment]
Hey, @Exodo0, @1WorldCapture and @jdwd40! As we have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. 

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
