### ISSUE TITLE
npm run dev issue multiple times and vite issue.

### ISSUE THREAD

**Issue by nbn-fnu** [stackblitz/bolt.new#2860]
### Describe the bug

I have a code and it doesnt display multipage as it shoudl and also keeps giveing the npm dev issue and the vite issue and keeps circuling. I have wasted a lot of toakens becuase its doing this and it doesnt fix.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-92xzvg

### Steps to reproduce

Just the preview or even teh deploy dont work.

### Expected behavior

It will error

### Screen Recording / Screenshot

<img width="523" alt="Screenshot 2024-11-20 at 3 05 04 PM" src="https://github.com/user-attachments/assets/e3f30494-7ce1-47f6-9b69-4de8f5375a58">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55534273,
  "usedJSHeapSize": 52432829,
  "jsHeapSizeLimit": 4294705152
}
Username = nbn-fnu
Chat ID = 58f658a76cb7
```

**Comment by keithdoyle9** [comment]
I've wasted quite a few tokens trying to get this to work as well. I can't even get an initial preview to load. 

I get the following error: 
```
> vite
jsh: command not found: vite
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2021.
