### ISSUE TITLE
bolt.new is not working with my MacBook :(

### ISSUE THREAD

**Issue by Vicorusu** [stackblitz/bolt.new#2863]
### Describe the bug

idk if its just me but I was playing around a bit with bolt.new on my windows computer and wanted to continue on my MacBook but the preview is not working even if im tryna prompt a new website and the bot also cant fix the problem ! 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jam6nu

### Steps to reproduce

1.write a prompt on macOS device 
2. does not. Work :(

### Expected behavior

thought the website would be shown like on windows 

### Screen Recording / Screenshot

<img width="897" alt="Screenshot 2024-11-20 at 23 23 25" src="https://github.com/user-attachments/assets/15320ff8-9e38-4d4d-aac3-08f27830ecfd">

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = vicorusu
Chat ID = 8f023f820506
```

**Comment by endocytosis** [comment]
Bolt is most compatible with Chrome. You can read more about this here: #2796.
