### ISSUE TITLE
logo hell

### ISSUE THREAD

**Issue by schechtereddie** [stackblitz/bolt.new#2864]
### Describe the bug

cant put image in 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rydqrk

### Steps to reproduce

![logo](https://github.com/user-attachments/assets/c9c079de-df21-49f7-bd0f-2b52335105d2)

### Expected behavior

to add the image igave it

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = schechtereddie
Chat ID = 271997744349
```

**Comment by endocytosis** [comment]
Sorry to hear this! The Bolt file system currently doesn't support image uploads. This issue, along with potential workarounds, is being tracked [here](https://github.com/stackblitz/bolt.new/issues/1809).
