### ISSUE TITLE
token use

### ISSUE THREAD

**Issue by DoughBoy01** [stackblitz/bolt.new#288]
there is no indication of tokens remaining or why you have hit a rate limit.   How did i burn through over 10m in just a few hours?

**Comment by mrsunshine** [comment]
If you press "Prompt enhanced" after the token error you get some infos
![Screenshot 2024-10-09 at 11 04 28](https://github.com/user-attachments/assets/cc2caa02-040b-4aec-baaa-3f55d8f30317)
Seems something is wrong with the numbers /settings

**Comment by sulco** [comment]
Hey, @DoughBoy01! We are actively working on providing a clearer in-app status for the tokens. 
Additionally, as we have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. 

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!

**Comment by DoughBoy01** [comment]
Awesome, thanks for the update!
