### ISSUE TITLE
Erreur d'application

### ISSUE THREAD

**Issue by Holivarius** [stackblitz/bolt.new#2898]
### Describe the bug

Blocage de l'application à chaque ouverture
![Capture d’écran 2024-11-21 132241](https://github.com/user-attachments/assets/6a56a7b5-9f1e-49ed-9cb2-a21fd4c63160)

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Ouverture de la page Bolt.new

### Expected behavior

Accès à l'application

### Screen Recording / Screenshot

![Capture d’écran 2024-11-21 132241](https://github.com/user-attachments/assets/0e07bbdc-7305-4e03-b5c9-5f6996dffde6)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows 11
Chrome ou Edge

**Comment by AriPerkkio** [comment]
Hey @Holivarius, this bug was fixed today.
