### ISSUE TITLE
Preview not working when reopening a project

### ISSUE THREAD

**Issue by Pietervlamings** [stackblitz/bolt.new#2905]
### Describe the bug

Every time I reopen a project I worked on previously it starts up, tells me it's ready but the preview isn't working. When I ask Bolt to fix it, it tells me it's good now but still no preview. This can happen 5 or 6 times in a row. I usually close the app and rethink my subscription when that happens. Please fix this bug before I quit.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sugw9h

### Steps to reproduce

See description

### Expected behavior

Show a preview

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 74372138,
  "usedJSHeapSize": 67586238,
  "jsHeapSizeLimit": 4294705152
}
Username = Pietervlamings
Chat ID = 1092cd1a0d0f
```

**Comment by keithdoyle9** [comment]
Looks like the same as my issue. What errors do you see in the console? Does this happen right at startup?

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
