### ISSUE TITLE
If $9 is only for an hour or less, I think it's a scam

### ISSUE THREAD

**Issue by JKing-8** [stackblitz/bolt.new#291]
It didn't even let me build a complete project before all my tokens were used up. Why didn't I subscribe to the Claude plan?

**Comment by liunice** [comment]
check this [https://github.com/stackblitz/bolt.new/issues/218#issuecomment-2400464667](url)

**Comment by sulco** [comment]
Hey, @JKing-8! As we have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
