### ISSUE TITLE
I always receive a blank page 

### ISSUE THREAD

**Issue by lirone** [stackblitz/bolt.new#2914]
### Describe the bug

The preview always show a blank page

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-78sgpj

### Steps to reproduce

you can look at the history it's never work

### Expected behavior

I don't know it's never work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 230466958,
  "usedJSHeapSize": 200946034,
  "jsHeapSizeLimit": 4294705152
}
Username = lirone_kkwt
Chat ID = 3ceaaad28c25
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
