### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by rjsmegmpdc** [stackblitz/bolt.new#2922]
### Describe the bug

npm run dev

Bolt Doesnt fix the issue that causes the npm run dev to fail.
This has occured on multiple occasions on the same project and previous conversations.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ww6hfv

### Steps to reproduce

"Fix Problem"

### Expected behavior

Problem is fixed.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/6f414e5b-6d69-4a37-a389-23abcbf04b03)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 56164974,
  "usedJSHeapSize": 43560390,
  "jsHeapSizeLimit": 4294705152
}
Username = rjsmegmpdc
Chat ID = ff01c72febd4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2021.
