### ISSUE TITLE
stuck on loading preview

### ISSUE THREAD

**Issue by rayahofficial** [stackblitz/bolt.new#2923]
### Describe the bug

after website is made it gets stuck on loading preview

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v2oglg

### Steps to reproduce

click on generate 
stuck on loading prevoew

### Expected behavior

for the preview to load

### Screen Recording / Screenshot

![image_2024-11-22_003055602](https://github.com/user-attachments/assets/d1da2df3-5cd2-401d-a220-ca27439faa90)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
