### ISSUE TITLE
token issue

### ISSUE THREAD

**Issue by YDX64** [stackblitz/bolt.new#293]
### Describe the bug

I am currently dealing with an interesting problem that I’ve never encountered before. All I wanted was to import a GitHub project, add a few features, and run it, but unfortunately, I ended up only clicking the ‘fix errors’ button over and over without ever being able to run the program, and now my tokens are gone! Please refund or fix this issue, as I have wasted $10 for nothing. And now you’re suggesting I purchase more tokens! We do not want to buy more tokens, we just want to finish at least one project!

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-bbwbye

### Steps to reproduce

fix errors

### Expected behavior

for fix errors could not use token and tokens needed too much more not 10m maybe 100m we need

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 115968509,
  "usedJSHeapSize": 113721433,
  "jsHeapSizeLimit": 4294705152
}
Username = YDX64
Chat ID = 49005d8dc7c5
```

**Comment by sulco** [comment]
Hey, @YDX64! We have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!

**Comment by YDX64** [comment]
Guys, you've made an amazing product with Stackblitz, far better than Replit and several others. However, it really needs to move away from token-based usage and be more like V0 or Cursor messages. The current token system causes too many issues. For example, you told me I used over 1.5 million tokens in one day, but if you check, it was only about 30 minutes of usage. The AI gets stuck, and refreshing consumes tokens. Clicking the 'fix errors' button eats up tokens, and sometimes the AI fails to start simple tasks like running a dev command or gives errors for no reason. At times, the AI does things that weren't even asked for. It seems that output tokens are being calculated even when the AI is simply writing code or reading from GitHub. This results in a frustrating experience overall.

Despite these issues, the product itself is fantastic, and we love it. The main problem is the token system. I suggest switching the monthly subscription model to message-based usage instead.
