### ISSUE TITLE
Broken Links/URL

### ISSUE THREAD

**Issue by tmazad** [stackblitz/bolt.new#2930]
### Describe the bug

When I ask bolt.new to deploy the website and give me a claim URL it gives me broken links and no claim URL. As a complete beginner this is frustrating as the only reason I'm using bolt is to avoid any technical stuff, including this sort of thing where I need to manually connect different softwares/platforms. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rawzr1

### Steps to reproduce

Go to deploy and then click the link the it provides

### Expected behavior

for the chat bot to give me a link to website and separate link for claim URL 

### Screen Recording / Screenshot

<img width="556" alt="Screenshot 2024-11-21 at 21 11 13" src="https://github.com/user-attachments/assets/528e4d39-0dd1-427e-b4f0-0dcb6e5772b2">
<img width="552" alt="Screenshot 2024-11-21 at 21 11 53" src="https://github.com/user-attachments/assets/63191cea-f048-4d96-a7d0-713c8d614b11">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 99302002,
  "usedJSHeapSize": 96065334,
  "jsHeapSizeLimit": 2160066560
}
Username = tmazad
Chat ID = 59c1eda6ebac
```

**Comment by endocytosis** [comment]
Hi, 

Apologies for the frustration! Can you try the following and see if that works? 

- Redeploy and see if it now properly gives you back the claim URL.
- Link your Netlify account via Settings > Application and refresh the page. We will detect that you have setup your personal Netlify account but your site is deployed to our Bolt Netlify account. In that case we generate a claim URL and show it to you when the import of the project is complete.

Thanks!
