### ISSUE TITLE
bolt not capable to make preview or display .

### ISSUE THREAD

**Issue by marinruizf** [stackblitz/bolt.new#2931]
### Describe the bug

bolt not capable to make preview or display and repeated same error more than 20 times always saying that next time error was going to be corrected which was a big lie.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sen5z8

### Steps to reproduce

Got to preview to see a blank page

### Expected behavior

say i cant do it or we need this other software or service but not overpromise and underdeliver

### Screen Recording / Screenshot

none

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 185820468,
  "usedJSHeapSize": 175563536,
  "jsHeapSizeLimit": 2160066560
}
Username = marinruizf
Chat ID = 8a6eb00667c5
```

### Additional context

none

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
