### ISSUE TITLE
HAving issues getting anything to run or render on my macs

### ISSUE THREAD

**Issue by uelsimon** [stackblitz/bolt.new#2935]
### Describe the bug

Apps don't launch, usually an error with installign initial files or dependencies

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kabdbg

### Steps to reproduce

load and try to launch.

### Expected behavior

app would launch and render in preview

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c97e7efd-be91-46b8-bf7b-74c39e9f2e8b)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 77495827,
  "usedJSHeapSize": 76042967,
  "jsHeapSizeLimit": 4294705152
}
Username = uelsimon
Chat ID = 1b567cfc6ac3
```

### Additional context

ive tried on multiuple browsers..and on multiple machines.  

i havent had it work properly in weeks.  is it something going on with the browser or somehting?

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
