### ISSUE TITLE
Can't preview & error with npm install / run

### ISSUE THREAD

**Issue by DigitumLabsAI** [stackblitz/bolt.new#2943]
### Describe the bug

I can't preview the app and found that npm install  & run dev failing couple of times. Even after dependencies are installed.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fcznvb

### Steps to reproduce

Go to https://bolt.new/~/sb1-fcznvb and try to preview

### Expected behavior

You can install and preview the web app

### Screen Recording / Screenshot

N/A

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85196410,
  "usedJSHeapSize": 83300426,
  "jsHeapSizeLimit": 2197815296
}
Username = Gopi24
Chat ID = f937f57fb079
```

### Additional context

N/A

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2021.
