### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by SYasJ** [stackblitz/bolt.new#2945]
### Describe the bug

Try to start a new project since previously never able to get anything launched or work. Getting an error . npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-22T08_16_15_922Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rft4kd

### Steps to reproduce

Just it tried to run npm install and dependencies and did try to fix it but still same issue. 

### Expected behavior

Should be showing me the project preview.

### Screen Recording / Screenshot

![Screen Shot 2024-11-22 at 1 15 54 AM](https://github.com/user-attachments/assets/41e71757-d73a-4830-b6b9-0647f61a717b)
![Screen Shot 2024-11-22 at 1 20 02 AM](https://github.com/user-attachments/assets/ed77c418-5fa5-4336-8474-4e6aae1ad02e)
![Screen Shot 2024-11-22 at 1 20 11 AM](https://github.com/user-attachments/assets/9ee88700-0cc3-4d37-87d7-78b4a99a4efa)

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = SeithJi
Chat ID = 37e681616437
```

### Additional context

This was reported before and as per the logs said it is fixed but never did.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021.
