### ISSUE TITLE
Tokens 

### ISSUE THREAD

**Issue by MartinPotoniec** [stackblitz/bolt.new#295]
### Describe the bug

Hey , i bought pro version to have more tokens but it says taht i have no more tokens available , which is not true

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vue-dveoat

### Steps to reproduce

No steps to reproduce

### Expected behavior

Tokens not available

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sulco** [comment]
Hey, @MartinPotoniec! We have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
