### ISSUE TITLE
comment that says "rest of the code"

### ISSUE THREAD

**Issue by daraHK88** [stackblitz/bolt.new#2958]
### Describe the bug

sometimes when it updates a component AI doesn't write the full code, instead in a comment it mentions that you must place the rest of the code from previous code. This way of updating a component is good when it doesn't rewrite the whole file like chatgpt that helps you to fix a section of the code. Since Bolt updates the whole code it makes me to tell it to fix that component again. also sometimes adds </content> tag with no reason to the end or beginning of the file. If my bug report is duplicate please remove it

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vwg4sw

### Steps to reproduce

1. random behaviour. doesn't have any pattern

### Expected behavior

to update a file with full code instead of partially and not to add any extra tag "</content>"

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87101431,
  "usedJSHeapSize": 76171911,
  "jsHeapSizeLimit": 4294705152
}
Username = daraHK88
Chat ID = fc80133f758e
```

### Additional context

Error:
```
You cancelled this message.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2862.
