### ISSUE TITLE
You've used all your remaining tokens???

### ISSUE THREAD

**Issue by ennevolte** [stackblitz/bolt.new#296]
I subscribed to a team plan and I believe it's impossible that I've already used up all the tokens after 30 minutes of work.

This is the message and there's no place where I can see how much I've consumed or how much is left until the end.
You've used all your remaining tokens.

It's not right that there isn't a contact email address.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cfe3yl

### Steps to reproduce

.

### Expected behavior

I expected to be able to use this software

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by violacase** [comment]
Agreed on lack of contact email address.
