### ISSUE TITLE
npm install for dependencies not working

### ISSUE THREAD

**Issue by cryptulien** [stackblitz/bolt.new#2964]
### Describe the bug

Unable to install dependencies and stop terminal to restart command
![image](https://github.com/user-attachments/assets/9423a5b0-2499-4e7d-83df-b1908dc99520)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-83wjav

### Steps to reproduce

1. Go to project
2. Wait for npm install

### Expected behavior

Install dependencies and build project

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/61a9ff4a-9f7f-485b-b89b-f43e8de67d3f)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109478241,
  "usedJSHeapSize": 57574505,
  "jsHeapSizeLimit": 4294705152
}
Username = cryptulien
Chat ID = 86c87e7207f4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021.
