### ISSUE TITLE
preview issue

### ISSUE THREAD

**Issue by marinruizf** [stackblitz/bolt.new#2968]
### Describe the bug

since wednesday i´ve been having issues with preview on bolt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ztg6tl

### Steps to reproduce

Anythibg i request is not being displayed on preview

### Expected behavior

once bolt states that issue is fixed it should verify previously through a QA process.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 81241836,
  "usedJSHeapSize": 78589836,
  "jsHeapSizeLimit": 2160066560
}
Username = marinruizf
Chat ID = 44c92aabcdf4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
