### ISSUE TITLE
I need claim URL for netlify project

### ISSUE THREAD

**Issue by aproli90** [stackblitz/bolt.new#2972]
### Describe the bug

https://bolt.new/~/sb1-5pxldd
Need claim URL for this project

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5pxldd

### Steps to reproduce

No steps. I couldn't any other way to contact the team

### Expected behavior

I should have got the claim URL when the code was deployed on netlify

### Platform

```
Browser name = Firefox
Full version = 133.0
Major version = 133
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
performance.memory = undefined
Username = aproli90
Chat ID = 6ab5d9617a2f
```

**Comment by aproli90** [comment]
I redeployed after connecting my netlify account. So, it directly got
deployed there.
But I still need to claim/delete previous deployment

**Comment by SamVerschueren** [comment]
@aproli90 Ok got it! Send me an email/DM with the site URL of the site you want to get removed from Netlify and I'll remove it.

**Comment by aproli90** [comment]
Thanks, Sam

Can you share your email address? Will share the link there

Thanks,
Ashhar

**Comment by SamVerschueren** [comment]
Received your e-mail and removed your website from our Netlify account. I'll close this issue for now.

**Comment by SamVerschueren** [comment]
@Ishant-93 Are you not able to claim the website? If you claim the website you can remove it yourself.

**Comment by Ishant-93** [comment]
I am not able to claim it...... I lost that chat actually where the link was present

**Comment by SamVerschueren** [comment]
I removed it 👍 . Thanks for reaching out!

**Comment by Ishant-93** [comment]
@SamVerschueren thanks sir

**Comment by rory73** [comment]
@SamVerschueren Hi, I do have the same issue since a couple of days. While I prompted bolt.new NOT to publish it created an url with my content that does not appear in my sites lists so I can't claim it to delete it (already made it with other willed deployments). Can you please help me delete it I will send the URL to the mailbox you shared here ?
