### ISSUE TITLE
why pictures are not working

### ISSUE THREAD

**Issue by sashasmeet** [stackblitz/bolt.new#2973]
### Describe the bug

![Скриншот 22-11-2024 182034](https://github.com/user-attachments/assets/1bd494ba-5104-4496-81b7-6f7a975e4b82)
i downloaded pictures but they dont work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sgz9wz

### Steps to reproduce

what do i have to do now

### Expected behavior

i want pictures to work

### Screen Recording / Screenshot

![Скриншот 22-11-2024 182034](https://github.com/user-attachments/assets/0987ae54-933d-4ea9-95e2-89ed41e4aa69)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56349267,
  "usedJSHeapSize": 54105327,
  "jsHeapSizeLimit": 2197815296
}
Username = w1wang
Chat ID = ca794099a077
```

### Additional context

![Скриншот 22-11-2024 182034](https://github.com/user-attachments/assets/91a2128b-ac8c-4bb6-ba66-aeebb1346254)

**Comment by endocytosis** [comment]
Appreciate the feedback! Currently, the Bolt file system does not support image uploads. We are aware of this feature request and are tracking it here: #1809.
