### ISSUE TITLE
I can't see the preview

### ISSUE THREAD

**Issue by Akshay-9416** [stackblitz/bolt.new#2974]
### Describe the bug

I can't see the preview

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-b4g5vv

### Steps to reproduce

just gave my description

### Expected behavior

something to be visible on the preview

### Platform

```
Browser name = Chrome
Full version = 118.0.0.0
Major version = 118
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 40634665,
  "usedJSHeapSize": 38848213,
  "jsHeapSizeLimit": 1967652864
}
Username = Akshay-9416
Chat ID = 376e81928924
```

**Comment by endocytosis** [comment]
Hi @Akshay-9416, 

Appreciate the feedback! Could you send a screenshot of your browser devtools and post it here?

![image](https://github.com/user-attachments/assets/e82b4436-80b9-4c3d-807f-9e4b8d8644a1)

Make sure this setting is enabled so we can see everything.

Specifically, have any of you encountered `Minified React error #418` with the white screen? We appreciate any additional feedback!

**Comment by Akshay-9416** [comment]
Resolved, Thank you
