### ISSUE TITLE
Always changes openai model to an old deprecated one

### ISSUE THREAD

**Issue by timtim-hub** [stackblitz/bolt.new#2976]
### Describe the bug

Always changes openai model to an old deprecated one. When adding gpt-4o it always overwrites it.

### Link to the Bolt URL that caused the error

all

### Steps to reproduce

As said

### Expected behavior

Using the gpt-4o api.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi, 

Appreciate the feedback! Unfortunately, we don't have the resources to offer support for individual projects. You can read more about continuing development here: #2310. 

You likely need to consult the official[ OpenAI documentation](https://platform.openai.com/docs/api-reference/introduction) to correctly configure the use of this model in your project.
