### ISSUE TITLE
cannot fix himself the problem

### ISSUE THREAD

**Issue by agencepantera** [stackblitz/bolt.new#2977]
### Describe the bug

Potential problem detected.

1
Hide problem

Command failed
npx astro build and it's cost a lot of token ...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hb5sjm

### Steps to reproduce

Npm build failed

### Expected behavior

I just try to build to deploy ..

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84428497,
  "usedJSHeapSize": 80702381,
  "jsHeapSizeLimit": 2160066560
}
Username = agencepantera
Chat ID = f8c644e90dae
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/2021.
