### ISSUE TITLE
any credit history can see? 

### ISSUE THREAD

**Issue by peter0025hk** [stackblitz/bolt.new#298]
it just show used all creadit.

**Comment by violacase** [comment]
Indeed. No history or calculation to find.

**Comment by sulco** [comment]
Hey, all! We are actively working on providing a clearer in-app status for the tokens. We appreciate your patience and will deploy the first updates as soon as possible so today and over the next couple of days, you can expect a continually improving experience.

Additionally, as we have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
