### ISSUE TITLE
Project doesn't run

### ISSUE THREAD

**Issue by thisisdice** [stackblitz/bolt.new#2986]
### Describe the bug

~/project 2m 16s
❯ yarn dev
yarn run v1.22.19
$ next dev
jsh: command not found: next
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/project 2s
❯ 

same for npm

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-9ulhhy

### Steps to reproduce

create prompt and wait

### Expected behavior

site launches in browser

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = thisisdice
Chat ID = 8cab960567e3
```

**Comment by endocytosis** [comment]
Hi, Bolt works best in Chrome and Chromium browsers as described [here] https://github.com/stackblitz/bolt.new/issues/2796).
