### ISSUE TITLE
Network errors by the truckloads

### ISSUE THREAD

**Issue by NoHitCrit** [stackblitz/bolt.new#2987]
### Describe the bug

As I make changes to the project, Bolt continuously had network errors and I keep getting charged tokens each time it does.  Eventually as i made more changes the page began erring and not even letting me make updates to it anymore.  I currently have an open ssh pipeline which has not lost connection once this entire time so it's not an issue with my network.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-buhro5

### Steps to reproduce

Use the tool for multiple steps beyond the first

### Expected behavior

I expected the tool to be able to fix issues with the project and to not charge me when it has network issues.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88182258,
  "usedJSHeapSize": 66313866,
  "jsHeapSizeLimit": 4294705152
}
Username = NoHitCrit
Chat ID = d4d04fca0324
```

### Additional context

Error:
```
network error
```

**Comment by endocytosis** [comment]
Apologies for the frustration! Are you able to share a screenshot of any of the specific error messages you are receiving?

**Comment by NoHitCrit** [comment]
This is one of the errors that cropped up that was not an network
connection error:
[image: image.png]
The ai was unable to resolve the issue and I ended up creating a new
project to resolve it as I didn't know what the issue was.

Is the user expected to change the code manually to fix issues like this?
Just want to know what the expectation is.
Also, if I do change it manually to fix the issue, will it crop up again or
will the ai respect the manual change?

**Comment by NoHitCrit** [comment]
An example of the network errors:
[image: image.png]

Is there any way to have it recover what it was doing without having to use
up loads of tokens?
I don't really feel like this tool is feasible to use if I'm constantly
needing to click retry until all my tokens are used without getting results.

**Comment by NoHitCrit** [comment]
Today, I have been completely unable to even get the project to load.
[image: image.png]
It's seeming like I'm going to have to add a new project again and start
from scratch like I have done the past few times this happens.

**Comment by NoHitCrit** [comment]
After getting the project to load, my first request resulted in what
appears to be a 500 error while stating that the site is fully functional.

[image: image.png]

**Comment by NoHitCrit** [comment]
Turns out the network errors were being caused by a docker instance that
kept restarting periodically.
I ran docker-compose down to close the instance and the majority of errors
have stopped.

Figured it out thanks to this guy:
https://askubuntu.com/questions/958902/err-network-changed-on-chrome-with-ubuntu-17-04
