### ISSUE TITLE
NativeScript does not seem to work

### ISSUE THREAD

**Issue by anthonyyoussef01** [stackblitz/bolt.new#2988]
### Describe the bug

I am trying to view the app on the nativescript preview app and all I see is a blank screen

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u2kynq

### Steps to reproduce

1. create a nativescript app on bolt
2. Scan the qr code on your device

### Expected behavior

App should pop up instead of a blank screen

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94684653,
  "usedJSHeapSize": 84239373,
  "jsHeapSizeLimit": 4294705152
}
Username = anthonyyoussef01
Chat ID = 2ae9e7048980
```

**Comment by endocytosis** [comment]
Hi, Bolt is currently unable to build and deploy NativeScript applications. However, you could click Open in StackBlitz at the top-right to continue development of this application.
