### ISSUE TITLE
An unexpected status code 520 response was received from the server.

### ISSUE THREAD

**Issue by Domoramo** [stackblitz/bolt.new#2989]
### Describe the bug

As a test of the capabilities, I requested it to make a browser based game and it did but the "preview" was just a white screen so I tried to deploy it, it spend 30k tokens and produced an error...
![image](https://github.com/user-attachments/assets/9e540e31-3a74-4fd2-9fd9-96928d024db4)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qaq8b3

### Steps to reproduce

1) Prompt: "Create a browser based RTS game in the spirit of command and conquer"
2) Prompt: "Deploy this application."

### Expected behavior

Launch the game

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/9e540e31-3a74-4fd2-9fd9-96928d024db4)

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = Domoramo
Chat ID = 84dc9c0b2e7c
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
