### ISSUE TITLE
Tokens are finished

### ISSUE THREAD

**Issue by Munashe-Chikazunga** [stackblitz/bolt.new#299]
### Describe the bug

Good day, I can't seem to find my old chats and I am not able to send messages because my tokens have run out since I have a pro subscription.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u5q2qm

### Steps to reproduce

1. Write prompt 2. Submit

### Expected behavior

For my prompt to work

### Platform

-Windows
-Chrome

**Comment by sulco** [comment]
Hey, @Munashe-Chikazunga! We have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopter and for your patience as we're ironing out the experience on bolt!
