### ISSUE TITLE
Connecting to stripe

### ISSUE THREAD

**Issue by barryw85** [stackblitz/bolt.new#2994]
### Describe the bug

I keep getting a Unexpected end of JSON input error code. 

"Error fetching payment intent:"{}
   at fetchPaymentIntent (/src/components/dashboard/modals/SubscriptionModal.tsx?t=1732312671959:178:17)

    setError('');

        const response = await fetch('/.netlify/functions/create-subscription', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            plan: selectedPlan,
            customerId: currentUser.uid
          }),
        });

        const data = await response.json();

        if (!response.ok || data.error) {
          throw new Error(data.error || data.message || 'Failed to initialize subscription');
        }

        if (!data.clientSecret) {
          throw new Error('Invalid response from server');
        }

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-agsg2f

### Steps to reproduce

click on profile
click upgrade

### Expected behavior

I expected to be able to link to the stripe card processor to sign up for subscription

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 200463378,
  "usedJSHeapSize": 144308118,
  "jsHeapSizeLimit": 4294705152
}
Username = barryw85
Chat ID = 898f28da94d5
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately, we don't have the resources to offer coding advice for individual projects. The [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively.
