### ISSUE TITLE
Possibility to open current projects in bolt

### ISSUE THREAD

**Issue by ctwhome** [stackblitz/bolt.new#30]
Is it possible right now, or are you planning to do that?

**Comment by yilmazdurmaz** [comment]
I can't say if the AI understands your project well before trying to change it, you can open your project in "bolt.new" for sure because they are backed by the same greatness ❤️ 

your "stackblitz" project has this style of link you can see while editing: ``https://stackblitz.com/edit/_the_name_of_your_project_?file=package.json``

change it so that it reads ``https://bolt.new/~/_the_name_of_your_project_``

**Comment by ctwhome** [comment]
Thanks, that is great! A button to switch to the Bolt interface could be also convenient.

**Comment by ctwhome** [comment]
have noticed is that changes made in Bolt aren't reflected in StackBlitz

**Comment by kdy1** [comment]
I can't open team projects. It says `You don't have access to the repository` even though I installed the GItHub app and am using Team plan

**Comment by ctwhome** [comment]
> I can't open team projects. It says `You don't have access to the repository` even though I installed the GItHub app and am using Team plan

i had the same with a private repo, but not with public.

**Comment by divparty** [comment]
The ability to switch easily back and forth between Bolt and the StackBlitz code editor is a must, allowing changes that were made in either Bolt or StackBlitz to be committed to the same connected repo would make this excellent.

**Comment by Nemikolh** [comment]
Hey everyone! Thanks for the comments!

I agree, this would be a really nice feature! We're tracking this internally. We'll keep you posted :sparkles:

**Comment by hdpinto** [comment]
I added my bolt.new project to github using the stackblitz editor, and now it can no longer be opened in bolt. At least, the bolt project and the github repo seem to be entirely different projects, so I would also love to see the ability to have github-synced projects also be available in bolt.new, with the ability to commit changes up or to revert back to the last commit (reset all pending changes). Loving the tool so far! Lots of fun to use.

**Comment by samdenty** [comment]
The button in editor has been shipped 🎊

**Comment by ChrisRoboMacro** [comment]
Can someone please clarify this? I have opened my project in Stackblitz, but I want to open it back up in bolt, is there a way to import a github project into Bolt to continue editing it? Thank you

**Comment by yilmazdurmaz** [comment]
@ChrisRoboMacro open your Stackblitz project and you will see this button on top-left above project file structure.
![image](https://github.com/user-attachments/assets/58aa8903-7ffe-4abd-86dd-0caa90c4444d)

But, if you want to "import" a project from Github, that is another story. Here is a trick you can use to at least open your Github project: if you put the following string (replace with your username/repo) in the URL, it will open your project but with a different project name.

``https://bolt.new/~/github.com/{user_name}/{repo_name}``

I cannot say if the AI will understand your project well, but at least it is a way to try :)

Note: you may need to activate "CodeflowApp" and "CodeflowApp Bot" on Stackblitz and Github first. if you havent done so before, try opening a Github project from within Stackblitz; it will ask you to install these to be able to connect your Github.

**Comment by larhou** [comment]
@yilmazdurmaz Thanks ! It works well for me opening github repos with: https://bolt.new/~/github.com/{user_name}/{repo_name}

It is a pretty cool and I use it for example to quickly get an overview of Github repos I am investigating. I can ask question about how the code works and relative quickly also install and run the app.
