### ISSUE TITLE
getting this msg no matter how I edit the latest prompt: prompt is too long: 205272 tokens > 199999 maximum

### ISSUE THREAD

**Issue by moses5407** [stackblitz/bolt.new#306]
### Describe the bug

I wonder if it relates to the length of the chat vs the length of the latest prompt?

Also, I don't seem to have gotten the additional tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hdgrt4

### Steps to reproduce

enter even a single word prompt

### Expected behavior

I was expecting to continue with refining this project

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/228dc83f-62d1-4a22-9310-cd8d5e56238a)

### Platform

-Chromebook running Chrome browser Version 126.0.6478.253 (Official Build) (64-bit)

**Comment by superresistant** [comment]
wtf are those backups? just download your code for versioning. if you put 10 versions of your app in the app code, that probably explain why it run out of tokens

**Comment by kc0tlh** [comment]
The issue here is that your project is to large for the AI. You need to keep the total project size smaller, or it will overwhelm the AI, and throw this error.

More general usage tips are available in #678

**Comment by lcgarza10** [comment]
Im still having this error, but I doubt the project is too large being the issue since even when i said "Hi" it gives me this prompt
also how can i make it smaller without AI and without removing a page that may brake

**Comment by kc0tlh** [comment]
It is likely because the file system of the project is too large. More to come on this soon, but as a start, try to reduce the project size or break down the app into smaller components. This may be the best approach.

If you're able to replicate this on a small project with very few files in the file system, please take a video with Loom and share it here so that we can troubleshoot.

**Comment by kc0tlh** [comment]
More info now available in #1322 where we are tracking this issue
