### ISSUE TITLE
npm install not responding

### ISSUE THREAD

**Issue by dikaio** [stackblitz/bolt.new#3067]
### Describe the bug

while setting up a new project and issuing the first prompt the npm install never completes.No error is given it just has the spinning indicator that never finishes.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xghun4

### Steps to reproduce

1. provide prompt 2. wait for npm to complete

### Expected behavior

expect npm to install dependencies to complete project setup.

### Platform

```
Browser name = Safari
Full version = 18.1.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15
performance.memory = undefined
Username = dikaio
Chat ID = 0639d44f9768
```

**Comment by vijayindalkar** [comment]
![image](https://github.com/user-attachments/assets/de1506c9-61ac-4722-9b4f-cc34aa4be7c9)


try using terminal

**Comment by endocytosis** [comment]
Hi all, 

Bolt works best in Chrome and Chromium browsers. Additional npm install issues are being tracked here: #2021.
