### ISSUE TITLE
deployment not working

### ISSUE THREAD

**Issue by Mirxa27** [stackblitz/bolt.new#308]
### Describe the bug

deployment not working

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1aeogl?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

deployment not working

### Expected behavior

deployment not working

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 153052522,
  "usedJSHeapSize": 135188430,
  "jsHeapSizeLimit": 2172649472
}
Username = Mirxa27
Chat ID = 861e477b3618
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
