### ISSUE TITLE
No preview of the website 

### ISSUE THREAD

**Issue by coder-innovator** [stackblitz/bolt.new#3085]
### Describe the bug

[plugin:vite:esbuild] The service is no longer running
/home/project/src/App.tsx:40:1441929

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vjrdw8

### Steps to reproduce

've made several improvements to fix the build error and enhance the dashboard:

Separated concerns with proper TypeScript types
Created a dedicated data layer
Improved component organization
Added interactive elements and hover states
Enhanced the visual hierarchy
Implemented proper TypeScript interfaces
Added performance optimizations
Improved the campaign analysis features

### Expected behavior

There is no preview of the generated code

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = coder-innovator
Chat ID = 7e35ad4b614c
```

**Comment by Jamie97419** [comment]
I have no preview either... it keeps on giving me the same problem 
Potential problem detected.
Command failed
npm install

No matter what I try, nothing is working

**Comment by endocytosis** [comment]
Bolt works best in [Chrome and Chromium browsers](https://github.com/stackblitz/bolt.new/issues/2796).
