### ISSUE TITLE
Preview isn't showing anything

### ISSUE THREAD

**Issue by Pinstack** [stackblitz/bolt.new#3086]
### Describe the bug

I've tried to generate a couple of frontends but each time preview just returns a blank screen. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7kggsr

### Steps to reproduce

Type a prompt. Wait for code. Preview. 

### Expected behavior

A preview to appear

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = Raedmund
Chat ID = 47f52d5ad366
```

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it https://github.com/stackblitz/bolt.new/issues/1791. Also, note that Bolt works best in Chrome and Chromium browsers.
