### ISSUE TITLE
https://stackblitz.com/~/github.com/krisgnyc/sb1-4sh1di

### ISSUE THREAD

**Issue by krisgnyc** [stackblitz/bolt.new#3094]
### Describe the bug

https://stackblitz.com/~/github.com/krisgnyc/sb1-4sh1di

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4sh1di

### Steps to reproduce

https://stackblitz.com/~/github.com/krisgnyc/sb1-4sh1di

### Expected behavior

https://stackblitz.com/~/github.com/krisgnyc/sb1-4sh1di

### Screen Recording / Screenshot

https://stackblitz.com/~/github.com/krisgnyc/sb1-4sh1di

### Platform

```
Browser name = Safari
Full version = 18.1.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15
performance.memory = undefined
Username = krisgnyc
Chat ID = ee71fa8fe700
```

### Additional context

https://stackblitz.com/~/github.com/krisgnyc/sb1-4sh1di

**Comment by endocytosis** [comment]
Bolt works best in Chrome and Chromium browsers.
