### ISSUE TITLE
Install dependencies fail

### ISSUE THREAD

**Issue by bgoldb21** [stackblitz/bolt.new#3099]
### Describe the bug

nom install command fails repeatedly

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6unfqx

### Steps to reproduce

Try to fix problem is selected and bolt then retries and sometimes succeeds but fails to generate a QR code for testing. I then write "QR code fails to load" in the text input box and bolt tries to fix the problem and then stalls on the dependencies install step.

### Expected behavior

I expect it to install and preview properly.

### Platform

```
Browser name = Safari
Full version = 18.2
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15
performance.memory = undefined
Username = bgoldb21
Chat ID = a1df3cda468d
```

**Comment by endocytosis** [comment]
Hi, 

Bolt is most compatible with Chrome and Chromium browsers. Additional build errors are being tracked here: #2021.
