### ISSUE TITLE
Monthly Subscription not worth it.

### ISSUE THREAD

**Issue by dhurrelbrink** [stackblitz/bolt.new#3100]
### Describe the bug

I feel like Bolt.new is getting worse.  I paid $20 to have the monthly subscription because I won't need to use it as much as a developer.  However, the system is working worse and worse on my builds.  It takes me sometimes 30 prompts to fix simple issues.  Some issues I've just given up on.  Now, I've burned through most of my tokens just because I tell the system to fix its own mistakes or that the screen is blank.  If this isn't fixed, I won't be renewing my subscription and will use one of the newer programs that builds apps out.

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-rb6d2l

### Steps to reproduce

Here's an easy one that Bolt.new can't fix:  "the lettering for the cities on the locations page is white and the window background is white.  Please fix.  

It'll then say that it's fixed and then it's not fixed.  After I tell it multiple times, I lose 500K tokens.  Ridiculous.  

### Expected behavior

I expect the system to quickly build out an app based on basic prompts I provide.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 70379795,
  "usedJSHeapSize": 61739567,
  "jsHeapSizeLimit": 2160066560
}
Username = dhurrelbrink@fuse.net
Chat ID = c3bc7f00876c
```

**Comment by meapps** [comment]
![Terminal 1](https://github.com/user-attachments/assets/0febc94d-bb3c-4adb-adf5-cd32a9625086)
Try to run the build through the terminal and then copy the errors in the chat. 

You have to give the AI sometimes errors or test examples.

**Comment by endocytosis** [comment]
Yes, at times there are programming challenges that are too complex for the AI to solve. Pasting errors from the Console into the chat is at time effective. At times, manual intervention is required. You can read more about continuing to develop your project here: #2310.

**Comment by dhurrelbrink** [comment]
Brian, 

I appreciate your help. However, I'm done with Bolt. I purchased my subscription in good faith and watched Bolt use up tokens on its own mistakes and at a faster rate than previous projects that were able to limit its use to 60K tickets. It's unimaginable how I could go through millions of tokens without something being severely wrong with your system. I haven't used Bolt in a week and don't plan to use it again. I was previously happy with the $20/month subscription I had, but want to now cancel. Please advise. 

Thank you.

**Comment by endocytosis** [comment]
Hi, if you email hello@stackblitz.com we can assist you with a refund.
