### ISSUE TITLE
Corrupted all the project

### ISSUE THREAD

**Issue by marcelolavor** [stackblitz/bolt.new#3105]
### Describe the bug

According with my prompt to change a combo behaviour, the whole page disaperied.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-msncjb

### Steps to reproduce

O combo de MA deverá apresentar as opções abaixo. Ao selecionar a escala para Média Aritmética e clicar no botão a direita, as respetivas linhas de MA (7, 25 e 99) deverão ser adicionadas a respetiva timeScale escolhida, entretando mantendo a timeScale escolhida do gráfico. A cada escolha de outra timeScale e acionamento do botão, mas 3 linhas (MA para 7, 25 e 99) respetivas a nova timeScale deverão ser adicionadas. Ao clicar novamente no botão para uma MA de um derminado timescale já incluído, as respetivas linhas MA deverão ser removidas.
1m
5m
15m
1H
4H
1D
3D
1W
1M

### Expected behavior

Do not change the page layout, only combo and button behaviour

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74102299,
  "usedJSHeapSize": 65955731,
  "jsHeapSizeLimit": 4294705152
}
Username = MarceloLavor
Chat ID = f3a60ef80d8a
```

**Comment by meapps** [comment]
There is a main file that it changed that shouldn't have. Fork it and then rollback to the checkpoint before.

**Comment by marcelolavor** [comment]
Thanks for the prompt response. Fixed

**Comment by endocytosis** [comment]
Glad to hear it worked!
