### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by joelGuerraArias** [stackblitz/bolt.new#3111]
### Describe the bug

Blank screen

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-remotion-eflbmh

### Steps to reproduce

Preview code

### Expected behavior

![Screenshot_114](https://github.com/user-attachments/assets/867273dc-e012-4577-bebe-4a7fbc88e1d2)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 211240030,
  "usedJSHeapSize": 140867750,
  "jsHeapSizeLimit": 4294705152
}
Username = joelGuerraArias
Chat ID = 3a2f650cdb5a
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
