### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mirmirmomo** [stackblitz/bolt.new#3114]
### Describe the bug

im trying to creat An app that a team can have on their phones and the admin can send notifications and alerts to them 
but it gives error and nothing is working
<img width="1440" alt="Screenshot 2024-11-24 at 8 22 43 PM" src="https://github.com/user-attachments/assets/c8079386-ec30-4927-b5c0-13f7f72b57f2">
![Untitled](https://github.com/user-attachments/assets/eebeebfb-dda5-4f7b-bbcc-071ac80c37c7)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-okuyun

### Steps to reproduce

<img width="1440" alt="Screenshot 2024-11-24 at 8 22 43 PM" src="https://github.com/user-attachments/assets/8e3096f6-3dff-4c65-a5e8-b2ab135c6d52">
![Untitled](https://github.com/user-attachments/assets/a5e74e93-c7f2-45e3-ab41-ddae39b1ecab)
<img width="817" alt="Screenshot 2024-11-24 at 6 16 32 PM" src="https://github.com/user-attachments/assets/0b857310-b9cb-470d-9d21-ad69c29c693f">

### Expected behavior

i need the error to be fixed

### Screen Recording / Screenshot

<img width="1440" alt="Screenshot 2024-11-24 at 8 22 43 PM" src="https://github.com/user-attachments/assets/4826524d-924b-4db9-a527-189c84caa5b1">
![Untitled](https://github.com/user-attachments/assets/ceb84839-0570-4f35-9309-9d371ee69e77)

### Platform

```
Browser name = Chrome
Full version = 127.0.0.0
Major version = 127
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105330042,
  "usedJSHeapSize": 101627750,
  "jsHeapSizeLimit": 2172649472
}
Username = None2211@gmail.com
Chat ID = 12f0cae058b5
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately, we don't have the resources to offer programming advice for individual projects. You can read more about continuing to develop your project here: #2310. Also, the [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively.
