### ISSUE TITLE
 white screen ( repeatedly) + massive token reduction ( for waht?) 

### ISSUE THREAD

**Issue by LiebUr** [stackblitz/bolt.new#3138]
### Describe the bug

when upgrading to NextJS 14 ( from usual 13.5.1 ) the "i cant see anything issue" happens all the time and "fixing" it reduced massivle the no of tokens but doenst change anything. :-( 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jbaze2

### Steps to reproduce

just open the file / current status

### Expected behavior

well , my Ux which worked nicely with nextJS13.51. ?! ( if thats even the cause)

### Screen Recording / Screenshot

white screen

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106003250,
  "usedJSHeapSize": 71260998,
  "jsHeapSizeLimit": 4294705152
}
Username = LiebUr
Chat ID = 34ab0c2d9b22
```

**Comment by AriPerkkio** [comment]
Hey @LiebUr, thanks for the report!

This seems to be an issue in NextJS. Their `14.0.4` version is trying to download peer dependency that doesn't exist in NPM. To me this looks like failed release as parts of packages are missing from registry. Looking at their Github issues, there are others who are running into same issue on other platforms too.

To fix this in your Bolt project, you can update your NextJS to `14.1.0`. This version is not broken like `14.0.4`. 

- https://www.npmjs.com/package/@next/swc-wasm-nodejs/v/14.0.4
- https://www.npmjs.com/package/@next/swc-wasm-nodejs/v/14.1.0

```diff
  "dependencies": {
-   "next": "14.0.4",
+   "next": "14.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "lucide-react": "0.294.0",
    "tailwind-merge": "2.1.0",
    "clsx": "2.0.0"
  },
```

<img src="https://github.com/user-attachments/assets/c82685ab-5bf4-433f-b13d-7bb46d522437" width="400" />
