### ISSUE TITLE
Page refresh consumes daily token limit.

### ISSUE THREAD

**Issue by theemilk** [stackblitz/bolt.new#314]
My page refreshed and somehow "ate" my days token allotment...NOT AMUSED... Namaste bless you and may you evolve consciousness consciously for the best and highest good of ALL OM.

**Comment by kc0tlh** [comment]
This bug has been resolved. I have reset your tokens to the full amount. We appreciate the report!

**Comment by YDX64** [comment]
Guys, you've made an amazing product with Stackblitz, far better than Replit and several others. However, it really needs to move away from token-based usage and be more like V0 or Cursor messages. The current token system causes too many issues. For example, you told me I used over 1.5 million tokens in one day, but if you check, it was only about 30 minutes of usage. The AI gets stuck, and refreshing consumes tokens. Clicking the 'fix errors' button eats up tokens, and sometimes the AI fails to start simple tasks like running a dev command or gives errors for no reason. At times, the AI does things that weren't even asked for. It seems that output tokens are being calculated even when the AI is simply writing code or reading from GitHub. This results in a frustrating experience overall.

Despite these issues, the product itself is fantastic, and we love it. The main problem is the token system. I suggest switching the monthly subscription model to message-based usage instead.
