### ISSUE TITLE
netlify not working anymore

### ISSUE THREAD

**Issue by mathishalimi** [stackblitz/bolt.new#3146]
### Describe the bug

can't deploy
4:37:57 PM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue. message from netlify. also i tried to add heroku for the backhend, connect github and stripe nd netlify but it dosenn't wwork ... 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wq5rd8

### Steps to reproduce

try to deploy

### Expected behavior

updates

### Platform

```
Browser name = Chrome
Full version = 130.0.6723.86
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; Quest 3) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/36.0.0.63.54.660846222 Chrome/130.0.6723.86 VR Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86780391,
  "usedJSHeapSize": 81971859,
  "jsHeapSizeLimit": 1098907648
}
Username = mathishalimi
Chat ID = 747a345b4fc8
```

**Comment by endocytosis** [comment]
Hi, can you try to deploy again by clicking the Deploy button at the top-right of the page? Thanks!

**Comment by mathishalimi** [comment]
Hey there I’m trying to connect netlify to heroku and GitHub to heroku from
boot but it didn’t work … can you help me with that ? Can we make a video
call so you can help me in live ?

**Comment by endocytosis** [comment]
Hi, unfortunately we don't have the resources to offer individual programming support. The [Bolt Help Center](https://support.bolt.new/welcome) has a number of resources and tutorials, including database integration. For more detailed integration, you may need to consult the official documentation as there are some programming challenges that are too complex for the AI to solve. Hope this helps!
