### ISSUE TITLE
test

### ISSUE THREAD

**Issue by lyhaifeng** [stackblitz/bolt.new#315]
### Describe the bug

测试

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-98beff

### Steps to reproduce

测试

### Expected behavior

测试案例  答题

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = lyhaifeng
Chat ID = ec4069e253a9
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
