### ISSUE TITLE
Why is install dependencies in Bolt.New so bad?

### ISSUE THREAD

**Issue by tbmosweu** [stackblitz/bolt.new#3163]
### Describe the bug

 it's taking forever to intel and error after error with no hope of fixing the problem soon. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s4fgkl

### Steps to reproduce

n/a

### Expected behavior

Not installing dependencies quick enough and preview not showing been waiting for hours, keep coming with errors.

### Screen Recording / Screenshot

n/a

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = tbmosweu
Chat ID = 09b707436915
```

### Additional context

n/a

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2021).
