### ISSUE TITLE
bolt doesnot open a repo

### ISSUE THREAD

**Issue by am1rbi** [stackblitz/bolt.new#3166]
### Describe the bug

I get "You don't have access to the repository"

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/am1rbi/v14-jul-be?file=index.html

### Steps to reproduce

changed url to bolt.new

### Expected behavior

load repo

### Screen Recording / Screenshot

<img width="676" alt="Screenshot 2024-11-26 at 0 30 30" src="https://github.com/user-attachments/assets/91f65dff-ab04-4209-be01-11955879e954">

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68492668,
  "usedJSHeapSize": 58321196,
  "jsHeapSizeLimit": 4294705152
}
Username = am1rbi
Chat ID = 1735e4107874
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Bolt currently supports public GitHub repositories. The [Bolt Help Center](https://suppport.bolt.new) has additional information on using Bolt most effectively.
