### ISSUE TITLE
No preview

### ISSUE THREAD

**Issue by PaulRANKNFC** [stackblitz/bolt.new#3169]
### Describe the bug

I have tried everything but bolt don't show anymore the preview of the project on which i have worked during multiple hours, i have tried many differents browser but it don't works

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hhvqqe

### Steps to reproduce

a

### Expected behavior

I wan't to see preview

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61880628,
  "usedJSHeapSize": 56095980,
  "jsHeapSizeLimit": 2197815296
}
Username = Paulbrtl
Chat ID = a196cb19292b
```

**Comment by PaulRANKNFC** [comment]
i have no extension and no VPN and when i type npm run dev, this appear : 

error when starting dev server:
Error: Port 4000 is already in use
    at Server.onError (file:///home/project/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:45644:18)
    at Server.emit (node:events:30:10899)
    at emitErrorNT (node:net:285:11727)
    at processTicksAndRejections (node:internal/process/task_queues:192:1067)
    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.88b6dd69.js:40:198652)

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791)
