### ISSUE TITLE
All chats are gone

### ISSUE THREAD

**Issue by steveninge** [stackblitz/bolt.new#317]
### Describe the bug

I've been working on two different apps for a few days now, but now when I log in to my account is says I have no previous conversations. I know for 100% certain I did not delete them. I tried logging out and logging back in, and I have the paid account so I made sure i'm in the right account. I do think I recently got very low on monthly tokens. 

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

1. Log in
2. Click the menu in the bottom left corner

### Expected behavior

Earlier today I saw at least 5 previous conversation chats that I had worked on. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows, chrome.

**Comment by davidmoshal** [comment]
yep same problem, the system doesn't remember chat history

**Comment by kc0tlh** [comment]
Thanks for the feedback @davidmoshal & @steveninge! We are aware of this and working save chats. There was some technical details around why we did not implement this fully at launch, but are excited to have this landed next week!

Closing this, as we will be tracking this issue in issue #17 !

**Comment by kc0tlh** [comment]
_Linking to #35_

**Comment by kc0tlh** [comment]
_Linking to #39_
