### ISSUE TITLE
app not working on StackBlitz

### ISSUE THREAD

**Issue by andujarmusic1** [stackblitz/bolt.new#3175]
### Describe the bug

i get a sign in page for the app that was built and also.. when i click on the button lets say for example CREATE AN EVENT or NEW BOOKING nothing happens.  I need a fully working app which is what i requested and even purchased tokens for.   please assist.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-k2vqax

### Steps to reproduce

i get a sign in page for the app that was built and also.. when i click on the button lets say for example CREATE AN EVENT or NEW BOOKING nothing happens.  I need a fully working app which is what i requested and even purchased tokens for.   please assist.

### Expected behavior

i need the app to work completely and to also be able to edit fields etc... 

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/3b1334f2-67b7-4118-96f1-f6a212ba264c

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47210571,
  "usedJSHeapSize": 45345815,
  "jsHeapSizeLimit": 2160066560
}
Username = andujarmusic1
Chat ID = a12c3289cfff
```

**Comment by endocytosis** [comment]
Unfortunately, we are unable to offer programming assistance for individual projects. The [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively, including database integration. You can read more about continuing to develop your project here: #2310.
