### ISSUE TITLE
Website completely broke after an edit

### ISSUE THREAD

**Issue by PublikoFR** [stackblitz/bolt.new#3188]
### Describe the bug

The website is broke after an edit because I ask Bolt to NOT EDIT the rest of the file.
And it insert lot of mention like that : 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vanilla-vite-rr3bsw

### Steps to reproduce

Ask Bolt to not edit the rest of the website

### Expected behavior

I expect Bolt to not redo the entire projet on every prompt because every time it break everything and this is a pain

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 81180106,
  "usedJSHeapSize": 75257666,
  "jsHeapSizeLimit": 4294705152
}
Username = RiderFx3
Chat ID = 42113d6fc387
```

**Comment by endocytosis** [comment]
If you right-click a file in the Bolt code editor and select "Lock file" this will prevent the AI from making further changes to that file. The [Bolt Help Center](https://support.bolt.new) contains a number of resources on using Bolt most effectively.
