### ISSUE TITLE
Npm error

### ISSUE THREAD

**Issue by bekzada1** [stackblitz/bolt.new#3189]
### Describe the bug

Doesn't do npm commands 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fsqfp3

### Steps to reproduce

Npm install

### Expected behavior

![IMG_3710](https://github.com/user-attachments/assets/3480bdb5-e094-473c-a66c-2abd5ae338fe)

### Platform

```
Browser name = Safari
Full version = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/131.0.6778.73 Mobile/15E148 Safari/604.1
performance.memory = undefined
Username = Bekzada
Chat ID = 198be217a19d
```

**Comment by endocytosis** [comment]
Hi, we recommend desktop Chrome and Chromium based browsers for Bolt usage. You can read more [here](https://github.com/stackblitz/bolt.new/issues/2796).
