### ISSUE TITLE
Many Issues and Bugs with Bold

### ISSUE THREAD

**Issue by Jagger757** [stackblitz/bolt.new#319]
### Describe the bug

There are many bugs. I had to basically start the website over multiple times. I would get everything where I wanted it and then it would completely change the landing page. This happened too many times to count. I created the code for the pages and submitted them so you would think it would be faster, but not. It changed the posts page, it changed many things on the site even though we were working on something completely unrelated. I think this is a great start for a product but it certainly is not there. I used almost all of my monthly tokens in one full day of correcting errors. Finally when it deployed the site it completely changed the admin panel to the point I had no control over anything. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5in4ve

### Steps to reproduce

It's everything

### Expected behavior

I expected it to not have too many issues until we started building the backend. But the code changes were a big surprise. I didn't expect it to completely change what was already completed. I know it's new and I accept that. The problem is I used a full month of Tokens trying to create one project. I think an advanced programmer would have solved the issues without much trouble, but I am a beginner and I couldn't.

### Screen Recording / Screenshot

I did not record what was happening.

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = Jag757
Chat ID = 1476fb30211e
```

### Additional context

I think it's going to be a great product but I am not sure it's better than Replit Agent at this point although I thought it was in the beginning. But I don't know how it could completely change the landing page for example after we had been working for hours and then couldn't restore it. I would like to have some additional tokens if possible so maybe I could try it differently.

**Comment by kc0tlh** [comment]
@Jagger757 apologies for any frustration during the beta period! Tips on getting good results from Bolt and increasing token usage efficiency can be found in issue #678
