### ISSUE TITLE
application preview not loading

### ISSUE THREAD

**Issue by arunk16** [stackblitz/bolt.new#3194]
### Describe the bug

expected to continue on developing the website from yesterday, but preview is not working

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pj6vpy

### Steps to reproduce

open the project

### Expected behavior

preview to work

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = arunk16
Chat ID = 986eb5dbc9c4
```

### Additional context

show preview

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it https://github.com/stackblitz/bolt.new/issues/1791. Also, note that Bolt works best in Chrome and Chromium browsers.
