### ISSUE TITLE
Unreachable

### ISSUE THREAD

**Issue by tabalizer** [stackblitz/bolt.new#3196]
### Describe the bug

The app gives a lot of unreachable warning/errors and the app will not show up in preview. It is also impossible to deploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-putq5u

### Steps to reproduce

Try to deploy and the error will replicate. Important, this is not only relevant for the ref. prosject, but for all my repos.

### Expected behavior

That the code and preview renders with install dependencies

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57287446,
  "usedJSHeapSize": 53645754,
  "jsHeapSizeLimit": 1174405120
}
Username = tabalizer
Chat ID = 8c6202f63d16
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with the preview window and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
