### ISSUE TITLE
Blank Preview screen

### ISSUE THREAD

**Issue by Explorer-64** [stackblitz/bolt.new#3199]
### Describe the bug

I've had bolt try to fix this several times but nothing comes up on the preview screen. It's blank.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-82vpcl

### Steps to reproduce

I don't know

### Expected behavior

A form to add expenses
A document scanner button to use your phone's camera
A summary section showing total expenses
A list of all expenses

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 167689876,
  "usedJSHeapSize": 160155516,
  "jsHeapSizeLimit": 4294705152
}
Username = explorer64
Chat ID = 2e4ba9555ca9
```

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
