### ISSUE TITLE
Ability to determine account token usage

### ISSUE THREAD

**Issue by prichter** [stackblitz/bolt.new#32]
**Is your feature request related to a problem? Please describe:**
Using the bolt.new chat interface, I am submitting numerous requests but am unaware of how many tokens this is consuming from my account.  My subscription (pro) says I have 10M tokens / month - how do I monitor this or find my balance?  I noted in the free account a pop-up showed when I was nearing my limit, but this isn't helpful if I am trying to gauge how fast I am consuming tokens.

**Describe the solution you'd like:**
I would like an easy way to monitor account token usage so I can determine how my usage impacts my allocated tokens.  If this is already available, some instructions on how to access this would be helpful.

**Describe alternatives you've considered:**
I looked in the bolt.new settings and accounts areas, and the StackBlitz settings / account areas, but was unable to find anything showing the balance.

**Additional context:**

**Comment by Nemikolh** [comment]
Hey @prichter ! 

We agree with you! We're going to add that information in the UI. 

Note that the pop-up you saw for free accounts also appears when you are getting close to your limit.

**Comment by saurav389** [comment]
I also recently purchased the pro membership of bolt.new and created a small project management app. I didn't  got any warning yesterday that i am close to exhaust my token limit. But when try to access today It giving message i used all my token limit. How is this possible to use 10 million token in just a small project.

**Comment by kc0tlh** [comment]
@saurav389 on my end it appears you have ~4m tokens remaining, and you used about 1.5m today. Please let me know if that is not the case and I will help you out!

**Comment by kc0tlh** [comment]
@prichter this has shipped! More info here: https://x.com/stackblitz/status/1844144363384996169

Thanks for your feedback and support!

**Comment by prichter** [comment]
> @prichter this has shipped! More info here: https://x.com/stackblitz/status/1844144363384996169
> 
> Thanks for your feedback and support!

Thanks so much, this is a great response in a short turnaround.  Brilliant job!
