### ISSUE TITLE
Practically Unuseable

### ISSUE THREAD

**Issue by bkowalski21** [stackblitz/bolt.new#3206]
### Describe the bug

Errors stack up continuously, the platform just wastes tokens almost intentionally so you will buy more. Initial results seem promising so you buy more tokens and then you will encounter a wave of consistent issues and expend all resources trying to get the app stable

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pwhbeh

### Steps to reproduce

Errors stack up continuously, the platform just wastes tokens almost intentionally so you will buy more. Initial results seem promising so you buy more tokens and then you will encounter a wave of consistent issues and expend all resources trying to get the app stable

### Expected behavior

I expect it to perform how it does when you are running out of tokens and the platform wants you to buy more...

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 256766688,
  "usedJSHeapSize": 194679016,
  "jsHeapSizeLimit": 4294705152
}
Username = bkowalski21
Chat ID = 488e617bbf83
```

### Additional context

Errors stack up continuously, the platform just wastes tokens almost intentionally so you will buy more. Initial results seem promising so you buy more tokens and then you will encounter a wave of consistent issues and expend all resources trying to get the app stable

**Comment by endocytosis** [comment]
Appreciate the feedback! The [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively.
