### ISSUE TITLE
Please help… Deployment issue

### ISSUE THREAD

**Issue by frederickauffmann** [stackblitz/bolt.new#3207]
### Describe the bug

I deploy and it stays installing without advancing
![image](https://github.com/user-attachments/assets/d9ba9be0-2149-4f37-98bd-6325e174eca5)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ysvtur

### Steps to reproduce

I deploy and it stays installing without advancing

### Expected behavior

I deploy and it stays installing without advancing

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Apologies for the frustration! 1) What browser are you using? We suggest using Bolt with Chrome and Chromium based browsers. 2) Can you set your project to "Private (accessible by URL)" by clicking the lock icon next to the project title so we can take a closer look? Thanks.

**Comment by frederickauffmann** [comment]
Hi, thanks for your reply. I’ve been using Safari but now I change to Mozilla so now better. I expend a lot of tokens with no success in safari. If there’s any chance to have any credits, I will be happy. Many thanks and I’m enjoying your platform.Someone with no idea of coding.Enviado desde mi iPhoneEl 26 nov 2024, a las 19:18, Brian ***@***.***> escribió:﻿
Apologies for the frustration! 1) What browser are you using? We suggest using Bolt with Chrome and Chromium based browsers. 2) Can you set your project to "Secret (accessible by URL)" by clicking the lock icon next to the project title so we can take a closer look? Thanks.

**Comment by endocytosis** [comment]
Hi, refund requests are handled through hello@stackblitz.com!
