### ISSUE TITLE
can't download the project on local/personal machine

### ISSUE THREAD

**Issue by DarthBeyg** [stackblitz/bolt.new#321]
### Describe the bug

once done with nextJs project. bolt is unable to create a zip file or deploy to netlify and make on deployed app a download link for anyone to download on personal machine

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tavquh

### Steps to reproduce

write in prompt box: I am done with the project, how can i download the project to my local machine

### Expected behavior

1.can't create zip file
2.can't deploy to netlify

### Screen Recording / Screenshot

![Screenshot 2024-10-09 230150](https://github.com/user-attachments/assets/d4540d0f-c158-46a5-950a-ea9c0b1f3800)
![Screenshot 2024-10-09 230227](https://github.com/user-attachments/assets/b7d20816-b57c-424e-85ff-feb7976ac28f)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 48879949,
  "usedJSHeapSize": 41402841,
  "jsHeapSizeLimit": 4294705152
}
Username = DarthBeyg
Chat ID = 5154ef908659
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by techydad05** [comment]
Im trying to figure this out as well, if you figure it out please post here. I will too.

**Comment by paladyne-io** [comment]
This 2 step process worked for me. Click the '**Open in Stackblitz**' button next to "Deploy". Next (in StackBlitz), click the Download Project icon (cloud with an arrow) to the right of PROJECT.

**Comment by DarthBeyg** [comment]
> This 2 step process worked for me. Click the '**Open in Stackblitz**' button next to "Deploy". Next (in StackBlitz), click the Download Project icon (cloud with an arrow) to the right of PROJECT.

yep. works like that. thanks

**Comment by DarthBeyg** [comment]
> Im trying to figure this out as well, if you figure it out please post here. I will too.

check above comment. you can download project through stackblitz
