### ISSUE TITLE
REFUND!

### ISSUE THREAD

**Issue by tabalizer** [stackblitz/bolt.new#3210]
### Describe the bug

The code does not update, but I am spending shitload of tokens without anything happens, iteration after iteration. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-njl2gq

### Steps to reproduce

try to update the ux with ny specs, but it only shows the same white blanc canvas without any changes. 

### Expected behavior

It should update the code, but now it is only repeating and going in circles without ANY updates

### Screen Recording / Screenshot

<img width="1392" alt="Screenshot 2024-11-26 at 19 07 16" src="https://github.com/user-attachments/assets/207129d5-8e73-488b-8011-814b8297beca">

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64968619,
  "usedJSHeapSize": 59965731,
  "jsHeapSizeLimit": 4294705152
}
Username = tabalizer
Chat ID = d130150473b4
```

### Additional context

I have thrown out millions of tokens on nothing today! Please REFUND!

**Comment by endocytosis** [comment]
Apologies for the frustration! Refund requests are handled through hello@stackblitz.com.
