### ISSUE TITLE
Not updating the hero image with the image I am providing

### ISSUE THREAD

**Issue by fmcgee1984** [stackblitz/bolt.new#3211]
### Describe the bug

Hi- I have attached an image from Pexels to replace my hero image and Bolt is not updating the image with this image. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pbsrdv

### Steps to reproduce

Please update the hero image with the attached image. 
![pexels-sanaa-ali-338721094-13995877](https://github.com/user-attachments/assets/55dc5a4d-2b50-4c4e-a7e7-da7a67719c53)

### Expected behavior

Image updated when I attach to prompt and prompt it to replace the image. 
![pexels-sanaa-ali-338721094-13995877](https://github.com/user-attachments/assets/a067738e-b11b-42af-afe9-8b12fa1f2cd9)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75975215,
  "usedJSHeapSize": 56103155,
  "jsHeapSizeLimit": 4294705152
}
Username = fmcgee1984
Chat ID = 7d76b332474d
```

**Comment by endocytosis** [comment]
Hi, 

Currently, Bolt does not support the ability to upload images to the file system. This is a known feature request that is being tracked [here](https://github.com/stackblitz/bolt.new/issues/1809). In the interim, you can:

1. Open your Bolt project in StackBlitz (click "Open in StackBlitz" at the top right of the page)
2. Upload the image to the StackBlitz file system
3. Specify the correct image path
