### ISSUE TITLE
Bolt says GPT-4 doesn't exist

### ISSUE THREAD

**Issue by coerdelion** [stackblitz/bolt.new#3212]
### Describe the bug

Bolt doesn't recognise my gpt-4o api.  

Error is: "The model `gpt-4` does not exist or you do not have access to it."

https://bolt.new/~/sb1-sc4kjb?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sc4kjb?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

1. Go to preview
2.  Choose ai model
3. Insert keyword
4. Add details if you like
5. Click "generate SEO article"
6. Stare into the abyss of disappointment

### Expected behavior

I expect bolt to accept the api and write an article calling on that api

### Platform

```
Browser name = Firefox
Full version = 132.0
Major version = 132
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
performance.memory = undefined
Username = FinMcC
Chat ID = 50a0a68bc73d
```

**Comment by endocytosis** [comment]
At times, there are programming challenges that are too complex for the AI to solve. As such, manual intervention is required. You can read more about continuing to develop your project here: #2310.
