### ISSUE TITLE
I asked bolt to build a login page

### ISSUE THREAD

**Issue by mrbizi1** [stackblitz/bolt.new#3226]
### Describe the bug

It seemed to write code but the preview was completely blank.   I was in Chrome. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hv1rw6

### Steps to reproduce

Asked Bolt to build a login page and it seemed to write the code but no preview.  It was all blank. 

### Expected behavior

I expected to see something in the preview. 

### Platform

```
Browser name = Safari
Full version = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPad; CPU OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/131.0.6778.73 Mobile/15E148 Safari/604.1
performance.memory = undefined
Username = mrbizi1
Chat ID = 7ec745bc5ddf
```

**Comment by endocytosis** [comment]
Appreciate the feedback! The issue with the preview not showing is a known issue and is being tracked [here](https://github.com/stackblitz/bolt.new/issues/1791).

**Comment by mrbizi1** [comment]
Thanks!Thanks,Josh “I can do all things through him who strengthens me.” – Philippians 4:13On Nov 26, 2024, at 6:22 PM, Brian ***@***.***> wrote:﻿
Appreciate the feedback! The is a known issue and is being tracked here.
