### ISSUE TITLE
I can't access my project

### ISSUE THREAD

**Issue by programmer22** [stackblitz/bolt.new#323]
### Describe the bug

I need to be able to access my project.

If I can't access this I will be pressing a lawsuit against you guys. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-7dgegv

### Steps to reproduce

It isn't loading from my history

### Expected behavior

It isn't loading from my history 

### Screen Recording / Screenshot

<img width="2056" alt="Screenshot 2024-10-09 at 2 26 00 PM" src="https://github.com/user-attachments/assets/1915931a-1b41-4d6d-ae8b-071d5c936662">

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 372235681,
  "usedJSHeapSize": 353541493,
  "jsHeapSizeLimit": 4294705152
}
Username = programmer22
Chat ID = c76bdf9ede3c
```

**Comment by gvasilakiss** [comment]
Threatening with a lawsuit makes me laugh so much

**Comment by davidmoshal** [comment]
@gvasilakiss not sure what's so hilarious, I also lost a project today.
Luckily it was only one day of work.
@programmer22 if it's any consolation, I cancelled my subscription when it happened to me!

**Comment by programmer22** [comment]
Appreciate the support @davidmoshal  I did some background checking on @gvasilakiss and he goes to a college rated a 2.1 out of 5 stars, calls himself a computer expert which is language only a rookie uses, and dosen't have any good  experience in programming. I laughed when I read his profile

**Comment by gvasilakiss** [comment]
I lost about 5 different projects from yesterday too so I know what it is like but I don't go posting online for lawsuits lol.
Also its called University not college and I don't call myself Blockchain Maestro at least:)

**Comment by programmer22** [comment]
Love that I ruffled your feathers ;)

**Comment by programmer22** [comment]
@gvasilakiss Last one because i've been laughing so hard reading your profile and watching this video https://www.youtube.com/watch?v=Bs9hC-olVlE&t=47s

**Comment by gvasilakiss** [comment]
Enjoy it, at least I'm someone here and achieved a lot:)

**Comment by programmer22** [comment]
You have achieved nothing lol just from reading your profile, watching your youtube video, and doing more research, I know you don't do much you don't have to buff up your resume for your own self conscious to make yourself feel better :D

I also have more contributions than you on github their just private because why would I want to share any of my work with someone like you? 

After all some of the most uneducated people are people who go to college. Look at all the money you wasted according to a student who attended your school :)

Samson Jacob
Rated 1 out of 5 stars
Sep 18, 2024
[The University of Sunderland](https://www.trustpilot.com/reviews/66eb6202290f5438524d1117)
The University of Sunderland: where dreams come to die. Student complaints: useless. Course: waste of money.
But then again, this reflects the state of the UK's education system as a whole.

Hahaha you lost this convo @gvasilakiss but if you want to keep exposing yourself as a fool go right ahead, i love being a troll on here :)

**Comment by programmer22** [comment]
This reflects the kind of developer you will be @gvasilakiss:

Rated 1 out of 5 stars
Jun 7, 2024

Just when you think that this foul and fetid institution can’t possibly sink any lower - they always sink lower than rock bottom.

Absolutely despicable practices going on here.

AVOID AT ALL COSTS.

**Comment by programmer22** [comment]
I won, admit your loss move on (pat on the back)

**Comment by EricSimons** [comment]
FYI I've blocked OP from all @stackblitz repos, this guy is toxic af and has no place here

**Comment by gvasilakiss** [comment]
Thanks @EricSimons congrats on the webinar today too!
