### ISSUE TITLE
OMG I'm going nuts with you my friend!!!!  

### ISSUE THREAD

**Issue by 1on1imim** [stackblitz/bolt.new#3233]
### Describe the bug

Look at the history this thing kept deleting everything. blew through lot of tokens and think it is only fair to give me some back please. Again this has not worked as you can see .

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3bfrzv

### Steps to reproduce

Look at the error logs please i am not a geek software guru

### Expected behavior

shouldn't delete everything when I do file upload. won't upload to netlify any more

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114130120,
  "usedJSHeapSize": 109895112,
  "jsHeapSizeLimit": 4294705152
}
Username = 1on1imim
Chat ID = 53459a1d719c
```

**Comment by endocytosis** [comment]
Appreciate the feedback! You can right-click a file in the Bolt code editor and select "Lock file" to prevent the AI from making further changes. Refund requests are handled through hello@stackblitz.com.
