### ISSUE TITLE
Chats not showing on another device while logged in on the same account

### ISSUE THREAD

**Issue by gvasilakiss** [stackblitz/bolt.new#324]
### Describe the bug

When trying to view my previous chat on another device, they are not loading

MacBook
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e65cf3a9-b5ad-41c1-b6a8-72fe86288345">

Windows 
<img width="960" alt="NVIDIA_Share_ckrU3OmW2r" src="https://github.com/user-attachments/assets/7285fd95-7099-48fa-abe9-44237eeac1f7">

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Go to https://bolt.new/ on 2 different devices
2. Hover on the left to see your past chats

### Expected behavior

Past chats should sync across devices

### Screen Recording / Screenshot

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cae37c15-e34c-49c5-83f8-01bc9bfbcd06">
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/b9b40d78-eaa3-40d1-bef6-e3278bbd9340">

### Platform

- OS: macOS and Windows
- Browser: Chrome on both
- Version: 129.0.6668.90 (Official Build) (arm64)

**Comment by programmer22** [comment]
Take screenshots of all the issues and paste them on x, and let the public know they are not taking care of their customers and fixing the issues needed to be fixed. If they fix the issues, I will stop. But I will not let down and will post this comment on every github issue to make sure everyone is on board. Don't just let this go out the window, its your work. Its your data. Spread the word and save other developers.

**Comment by kc0tlh** [comment]
@gvasilakiss thanks for the detailed feedback! We are aware of this issue now, and are tracking the resolution in #17
