### ISSUE TITLE
image display issue, 

### ISSUE THREAD

**Issue by brawlaphant** [stackblitz/bolt.new#325]
### Describe the bug

uploading image using attachment paperclip, i have tried using imgur, and another to use url links to no success in displaying in preview it shows this consistently see attachments
![oscillate](https://github.com/user-attachments/assets/37cce780-c917-47c7-b094-d36bca30a346)
<img width="85" alt="photo midj" src="https://github.com/user-attachments/assets/79b7504e-e94c-4005-83d6-5bacb0ec3ae0">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nxt46v

### Steps to reproduce

click paper clip, 
add image
ask to use image in webpage/site
it does not show

### Expected behavior

i expected it to display the image i uploaded

### Platform

```
Browser name = Brave
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67738169,
  "usedJSHeapSize": 45389945,
  "jsHeapSizeLimit": 4294705152
}
Username = brawlaphant
Chat ID = 2696913de052
```

### Additional context

i'm using brave browser
very novice in this industry,
bolt is my learning engine
i believe
best ux/ui for learning programming

**Comment by brawlaphant** [comment]
asked bolt to construct a feedback report from its understanding

# Image Display Issue in Next.js Static Export

## Problem Description
- Uploaded images are not displaying in the preview when using Next.js static export.
- The issue persists despite using standard HTML `img` tags and configuring `next.config.js` for unoptimized images.

## Steps to Reproduce
1. Upload an image (e.g., 'oscillate-logo.png') to the 'public' folder.
2. Reference the image in components using either Next.js `Image` component or standard HTML `img` tag.
3. Configure `next.config.js` with `images: { unoptimized: true }` for static export.
4. Run `npm run dev` to start the development server.
5. Observe that the image is not visible in the preview.

## Expected Behavior
The uploaded image should be visible in the preview when referenced in components.

## Actual Behavior
The image is not displayed, and the image placeholder or broken image icon is shown instead.

## Environment
- Next.js version: [Your Next.js version]
- Node.js version: [Your Node.js version]
- Operating System: [Your OS]
- Browser: [Browser used for testing]

## Additional Notes
- The issue occurs in a static export environment (using `output: 'export'` in `next.config.js`).
- Standard troubleshooting steps (clearing cache, using incognito mode) have been attempted without success.

**Comment by msagliocco** [comment]
Images are exported as reference to a blob, this happens almost randomly for me

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1809. A workaround described there would be to open the Bolt project in StackBlitz and upload the image to the file system there to continue development.
