### ISSUE TITLE
Upgraded and lost my project

### ISSUE THREAD

**Issue by mmonty23** [stackblitz/bolt.new#3279]
### Describe the bug

I was working on a postcard project on the free plan and when I upgraded to a paid plan, I can't find it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kvrisw

### Steps to reproduce

No project found

### Expected behavior

When I upgraded my plan, my expectation was that I would be brought back to my project I was in the middle of.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 40112201,
  "usedJSHeapSize": 37109837,
  "jsHeapSizeLimit": 4294705152
}
Username = mmonty23
Chat ID = 60f7752aa42f
```

**Comment by endocytosis** [comment]
Sorry to hear this! Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking collections at the left-hand side of the page and the opening Bolt Collection? 

If the issue remains, we are aware of this and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2209).
