### ISSUE TITLE
cant display image  and logo

### ISSUE THREAD

**Issue by holidays25** [stackblitz/bolt.new#3281]
### Describe the bug

not one bugs 1000 bugs. its not able to find a easy bug why it not the the hero image

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-q2p6ll

### Steps to reproduce

when you start it you will allready when you start it

### Expected behavior

very easy. It must show the logo and the hero image. i upload to my hosting and its not working

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 176014175,
  "usedJSHeapSize": 164290263,
  "jsHeapSizeLimit": 4294705152
}
Username = holiday25
Chat ID = 863c1083f6fd
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1809). If the issue is in your deployed project, make sure the image file paths are correct.
