### ISSUE TITLE
Component updates and changes aren't rendering on the bolt project after implementation

### ISSUE THREAD

**Issue by JonKhours** [stackblitz/bolt.new#3282]
### Describe the bug

1. we're prompting changes to a component and page for our bolt project, but the changes aren't rendering at all on UI/UX. 
2. we've asked numerous times to fix issues, troubleshoot, etc. and it implements code review and 'fixes' but the implementations do not show on the UI/UX. 

### Steps to reproduce

1. Ask bolt to make a slight change or improvement to the ProductSidePanel component. 
2. Wait for implementation. 
3. Go to 'Original Catalog' scroll right of row and click pen icon to open up ProductSidePanel. 
4. Changes aren't to be found. 

### Expected behavior

Support in fixing this issue so that we can carry on with our bolt project. We've lost several tokens stuck on this issue. 

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 350379997,
  "usedJSHeapSize": 341055469,
  "jsHeapSizeLimit": 4294705152
}
Username = Sprout Dev
Chat ID = ed6dbd631f6b
```

**Comment by bwhit99** [comment]
Does this happen only when you do updates via a targeted file? That's when it happens to me. I have to refresh the browser window to see the updates. It is consistent, a bit of a pain but refreshing browser works.

**Comment by Receptionally** [comment]
Just happened to me too!
