### ISSUE TITLE
I just lost a tonne of work and tokens

### ISSUE THREAD

**Issue by deanmfankhauser** [stackblitz/bolt.new#3283]
### Describe the bug

I was working on this https://stackblitz.com/edit/bolt-nextjs-shadcn-98igpt?file=.gitignore

I refreshed the page and noticed that a bunch of my latest prompts and work completed was missing. In addition, nothing was being displayed on the screen. I refreshed again, and nothing. I then clicked the rollback button and then realised about 2 hours of work was gone.

Is there any way to get this back? If not, can I atleast get those credits back?

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-98igpt

### Steps to reproduce

I described above

### Expected behavior

Not to lose all my work

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 156970630,
  "usedJSHeapSize": 144690150,
  "jsHeapSizeLimit": 4294705152
}
Username = deanf
Chat ID = 6f2a579e74de
```

**Comment by endocytosis** [comment]
Sorry to hear this! Are you able to find your past project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), opening Collections on the left-hand side of the page, and then opening Bolt Collection? 

Alternatively, if you mouseover the left-hand side of the page in Bolt and open Settings > Backups you may find a prior version of your chat there that you can revert to. 

Please let me know if either of these methods works.

**Comment by deanmfankhauser** [comment]
Can you revert forwards?

**Comment by endocytosis** [comment]
If you revert to a Backup that will create a fork of your project at that point. You can not revert forwards from that point.

**Comment by deanmfankhauser** [comment]
Ok, please read my bug report again and you’ll understand the problem.

**Comment by deanmfankhauser** [comment]
Hello? I lost about 2 hours of work and tonnes of credits due to a bug in your system.

**Comment by endocytosis** [comment]
Refund requests are handled through hello@stackblitz.com.
