### ISSUE TITLE
IVEOM DJ

### ISSUE THREAD

**Issue by IVEOMDJ** [stackblitz/bolt.new#3290]
### Describe the bug

UNE APPLICATION ME PERNETANT DE CREE UNE BIBLIOTHEQUE POUR MES MIXAGE 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-k6eqvr

### Steps to reproduce

VIDMATE

### Expected behavior

Une application sur qui poster et  classer les mixage par catégorie pour le monde

### Screen Recording / Screenshot

![photo_2024-11-27 17 44 25](https://github.com/user-attachments/assets/063c2aa7-f680-4491-af60-690a44139f15)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65001776,
  "usedJSHeapSize": 50621828,
  "jsHeapSizeLimit": 2172649472
}
Username = IVEOMDJ
Chat ID = 3a59b33924c9
```

### Additional context

RIEN

**Comment by IVEOMDJ** [comment]
UNE APPLICATION POUR POUVOIR POSTER ET CLASSER CES MIXAGE

**Comment by IVEOMDJ** [comment]
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65001776,
  "usedJSHeapSize": 50621828,
  "jsHeapSizeLimit": 2172649472
}
Username = IVEOMDJ
Chat ID = 3a59b33924c9

**Comment by endocytosis** [comment]
The [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively.
