### ISSUE TITLE
Failure to save

### ISSUE THREAD

**Issue by wundergunder** [stackblitz/bolt.new#3294]
### Describe the bug

When I do a new command, I get an error saying it isn't saving.

![image](https://github.com/user-attachments/assets/701867b6-014a-4331-9b16-823c908e1ed5)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jw26lk

### Steps to reproduce

Any command gives the error.

### Expected behavior

It saves progress

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 247605219,
  "usedJSHeapSize": 172999039,
  "jsHeapSizeLimit": 4294705152
}
Username = wundergunder
Chat ID = 103def322066
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Do you know around what time specifically this error occurred? We are trying to collect more details as we investigate the cause of this error. Also, could you share your Bolt/StackBlitz username (if you login to [stackblitz.com](https://stackblitz.com/) with the same credentials as Bolt, you will see your username at the top left-hand side of the page). 

We are tracking this issue [here](https://github.com/stackblitz/bolt.new/issues/2762). Thanks!

**Comment by wundergunder** [comment]
Username is wundergunder.  I believe it was when I added an add test data function when it first appeared.

**Comment by endocytosis** [comment]
Great, thanks for the additional feedback!
