### ISSUE TITLE
can't build and deploy

### ISSUE THREAD

**Issue by claydouglass** [stackblitz/bolt.new#330]
### Describe the bug

Seems unable to build and deploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hcvc6o

### Steps to reproduce

i tried to build and deploy multiple times. 

### Expected behavior

that it builds and deploys 

### Screen Recording / Screenshot

Now that we've updated the package.json file, let's deploy the application to Netlify:

Deploy application to Netlify

npx vite build
netlify
Now we'll wait until the site is live. Let me check the deployment status for you.

Failed building the project. Make sure the build command is correct and try again.

Report Issue

Retry
it seems you have issues deploying. what are they?

I apologize for the confusion. It seems that the deployment didn't start due to some issues with the package versions. Let's address these issues and try to deploy again.

The main problem appears to be with the anthropic package version. The version ^0.6.1 specified in the package.json file is not compatible with the current code. Let's update the AIAssistant.tsx file to use the correct version of the Anthropic SDK.

First, let's update the package.json file:

Update package.json with correct anthropic version

package.json
Now, let's update the AIAssistant.tsx file to use the correct import for the Anthropic SDK:

Update AIAssistant.tsx with correct Anthropic import

src/components/AIAssistant.tsx
Now that we've made these changes, let's try to deploy the application again:

Deploy application to Netlify

npx vite build
netlify
Let's wait for the deployment to complete and then I'll check the status for you.

There was an error processing your request

Report Issue

Retry
this looks liek the latest version of Anthropic 2023-06-01

I apologize for the confusion. You're right, and thank you for providing the correct information. Let's update the code to use the latest version of the Anthropic SDK.

Update Anthropic SDK usage

src/components/AIAssistant.tsx
Now that we've updated the Anthropic SDK usage, let's try to deploy the application again:

Deploy application to Netlify

npx vite build
netlify
Let's wait for the deployment to complete, and then I'll check the status for you.

There was an error processing your request

Report Issue

Retry
this has happened 5 times now. why can't yo deploy?

There was an error processing your request

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54191678,
  "usedJSHeapSize": 49806982,
  "jsHeapSizeLimit": 2172649472
}
Username = claydouglass
Chat ID = 3f0f1f8ff307
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
i've just opened a pr to add auto-fixes for build errors encountered inside deployment build commands

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/46

**Comment by claydouglass** [comment]
didn't work. i have to deploy to github then it works. please keep going.

**Comment by claydouglass** [comment]
what does this mean? i try to click on the offer but there is no chance to
buy.

i wasted like half my tokens just trying to get deployment to work. can you
add 10m to my account?

big fan of the product and evangelizing.
