### ISSUE TITLE
Connection Problem Constantly

### ISSUE THREAD

**Issue by mustavanov** [stackblitz/bolt.new#331]
### Describe the bug

every now and then i get this error when i am trying to add new message , i don't know why ??

It looks like we're having trouble connecting due to the location of the server you're connected to. If this is in error, can you try switching your VPN location?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fwae95

### Steps to reproduce

1. try to send a message 
2. sometimes it send normally sometimes i receive the motioned error

### Expected behavior

send message and interacting with ai seamlessly

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49954032,
  "usedJSHeapSize": 43992120,
  "jsHeapSizeLimit": 2172649472
}
Username = mustavanov
Chat ID = ba20fdb5b031
```

**Comment by programmer22** [comment]
Take screenshots of all the issues and paste them on x, and let the public know they are not taking care of their customers and fixing the issues needed to be fixed. If they fix the issues, I will stop. But I will not let down and will post this comment on every github issue to make sure everyone is on board. Don't just let this go out the window, its your work. Its your data. Spread the word and save other developers.

They should not be charging people money unless their project is working smoothly and perfectly

**Comment by samdenty** [comment]
we've recently fixed this issue

**Comment by samdenty** [comment]
you can track in https://github.com/stackblitz/bolt.new/issues/77

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
