### ISSUE TITLE
Unable to Revert Changes

### ISSUE THREAD

**Issue by pkeller3** [stackblitz/bolt.new#332]
### Describe the bug

I had made a few changes to my test project, then asked for something to be added and the entire app was rewritten which threw away all of the prior changes that I had made. I would like to revert changes back to the version that I was happy with and work to add more features to that version of the code.

### Link to the Bolt URL that caused the error

https://bolt.new/~/tanstack-table-heazey

### Steps to reproduce

Make several iterations working through things and adding features. Ask for the code to be updated to simulate a scenario that is described.

### Expected behavior

The code is updated instead of rewritten. There is a revert option to go back to a prior working version.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72069249,
  "usedJSHeapSize": 70120817,
  "jsHeapSizeLimit": 4294705152
}
Username = pkeller3
Chat ID = 4412f92d37ea
```

**Comment by kc0tlh** [comment]
Thanks for the report! We are tracking the resolution in #82

**Comment by kc0tlh** [comment]
@pkeller3 Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!

**Comment by pkeller3** [comment]
Thank you for the quick response. Nice work on Bolt so far!
