### ISSUE TITLE
Logo images not loading

### ISSUE THREAD

**Issue by EmmanuelDA12** [stackblitz/bolt.new#3320]
### Describe the bug

Logo images not loading when added as an attachment for the site

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m34szd

### Steps to reproduce

attach image 
Command is - add logo to header in front of text on the left

### Expected behavior

for lofo to appear in site header

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66147348,
  "usedJSHeapSize": 60714872,
  "jsHeapSizeLimit": 2197815296
}
Username = EmmanuelDA12
Chat ID = 8d6b2ebe1ce2
```

**Comment by endocytosis** [comment]
Appreciate the feedback! I'd give this another try as the Bolt file system now supports image uploads.

**Comment by jiacheng-coder** [comment]
> Appreciate the feedback! I'd give this another try as the Bolt file system now supports image uploads.

i clone the repo, but not see the upload icon, please tell me the reason~
