### ISSUE TITLE
PLEASE READ

### ISSUE THREAD

**Issue by programmer22** [stackblitz/bolt.new#336]
### Describe the bug

Everyone should read this and restrain from further use of bolt.ai or stackblitz until they fix the issue. The only way to get them to resolve the issue is to stop using the service and not pay the $20 until they have everything perfect. If so, you giving your data away for free. 

### Link to the Bolt URL that caused the error

Everyone should read this and restrain from further use of bolt.ai or stackblitz until they fix the issue. The only way to get them to resolve the issue is to stop using the service and not pay the $20 until they have everything perfect. If so, you giving your data away for free. 

### Steps to reproduce

Everyone should read this and restrain from further use of bolt.ai or stackblitz until they fix the issue. The only way to get them to resolve the issue is to stop using the service and not pay the $20 until they have everything perfect. If so, you giving your data away for free. 

### Expected behavior

Everyone should read this and restrain from further use of bolt.ai or stackblitz until they fix the issue. The only way to get them to resolve the issue is to stop using the service and not pay the $20 until they have everything perfect. If so, you giving your data away for free. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by EricSimons** [comment]
Sorry, I don't see an issue actually listed here? Also, this is (as advertised) beta software- stuff will break and we are scrambling jets to fix them asap! If you are not okay with that then pls do not buy a subscription, for sure

Closing for now
