### ISSUE TITLE
The whole page crash with react errors when importing a github repo.

### ISSUE THREAD

**Issue by c0rtexR** [stackblitz/bolt.new#337]
### Describe the bug

Visit https://bolt.new/github.com/softflow24/data-river

Idk what the error is because you don't handle your errors.

![image](https://github.com/user-attachments/assets/740d340e-0b66-49b6-a254-47f210e375b2)

### Link to the Bolt URL that caused the error

https://bolt.new/github.com/softflow24/data-river

### Steps to reproduce

Enter url boom

### Expected behavior

Tell me what the error is, also would be cool if it didn't explode.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c745c72e-f922-438d-85c8-b45ef23e8fd7)

### Platform

- OS: MacOS
- Browser: Edge
- Version: 128.0.2739.67

**Comment by thxare** [comment]
Same happens to me

**Comment by samdenty** [comment]
this seems to be fixed now, could you confirm and if not re-open
