### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by dbavey22** [stackblitz/bolt.new#338]
### Describe the bug

clicked deploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ux8ha9

### Steps to reproduce

click deploy or tell it to deploy

### Expected behavior

deployment
![image](https://github.com/user-attachments/assets/8c440a91-f931-46a6-9f1a-3508b8b45d71)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 42990675,
  "usedJSHeapSize": 39623167,
  "jsHeapSizeLimit": 4294705152
}
Username = dbavey22
Chat ID = 2cac623f9221
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
i've just opened a pr to add auto-fixes for build errors encountered inside deployment build commands

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/46
