### ISSUE TITLE
white page

### ISSUE THREAD

**Issue by andreifsolomon** [stackblitz/bolt.new#340]
### Describe the bug

the entire page is white

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-msuuuu

### Steps to reproduce

the page is white....
wasting my tokens trying to fix this....probably more than half went to waste due to white screens or behavior that was lost  and had to re-do

### Expected behavior

no white screen should be seen

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c63aea87-bb4c-457f-b807-b9f8732824d2)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93202347,
  "usedJSHeapSize": 88696935,
  "jsHeapSizeLimit": 4294705152
}
Username = dre
Chat ID = f53a95301dff
```

**Comment by endocytosis** [comment]
Hi @andreifsolomon, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
