### ISSUE TITLE
has been blocked by CORS policy

### ISSUE THREAD

**Issue by kernel1999** [stackblitz/bolt.new#3401]
### Describe the bug

CORS blocking when trying to authenticate with external api 15M, tokens burned

![Screenshot_5](https://github.com/user-attachments/assets/f30c6a3d-27ee-401b-9093-506d04d522ae)
![Screenshot_4](https://github.com/user-attachments/assets/a2330119-d197-4da9-94dc-7dfb0f434053)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sghsdx

### Steps to reproduce

Go to Credit Inquiry, enter a CPF, fill in the name, click to query, open the browser inspector, go to console and check the error.

![Screenshot_15](https://github.com/user-attachments/assets/4bef5930-7c51-4d13-aa53-825bf1c5bf71)

### Expected behavior

I spent over 15M tokens trying to resolve this issue, I would like to get them back as this is a systemic issue. I have proof of recharge for the tokens I made.

![WhatsApp Image 2024-11-29 at 09 39 12](https://github.com/user-attachments/assets/782f5155-30af-4b6d-9c7b-35b404ee5eac)
![WhatsApp Image 2024-11-29 at 09 39 11](https://github.com/user-attachments/assets/ae277ced-d6fe-4857-b8a0-8f9ea57622f5)

### Screen Recording / Screenshot

![WhatsApp Image 2024-11-29 at 09 39 12](https://github.com/user-attachments/assets/cf25dbbd-ee26-425b-a7c3-e54b962dd0bf)
![WhatsApp Image 2024-11-29 at 09 39 11](https://github.com/user-attachments/assets/9cff97ea-817e-4619-b359-fe7c6315b138)
![Screenshot_15](https://github.com/user-attachments/assets/2a378763-0275-46bd-ad38-1827f11823c3)
![Screenshot_5](https://github.com/user-attachments/assets/9db0ba05-56a4-4963-8c6a-73bb96aa8f36)
![Screenshot_4](https://github.com/user-attachments/assets/c6fb0505-d685-4dd1-a98b-915bb3d58cbb)

### Platform

- OS: [ Windows]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

### Additional context

thank's

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #3164.
