### ISSUE TITLE
I bought the pro plan... and now nothing but errors and I cannot preview my site and its eating my tokens...

### ISSUE THREAD

**Issue by mawiskored** [stackblitz/bolt.new#342]
I keep having the same error. I used over 300k tokens to try and fix it but bolt is stuck in a loop. I cant preview, I cant deploy. It was working ok but the I lost preview. bolt did some changes, then same error, then changes, then same error.... over and over again. I asked it to analyze and fix all code. it did then same error. this is messed up for me to waste tokens when it keeps doing the same thing over and over again......

**Comment by kc0tlh** [comment]
@mawiskored apologies for any frustration during the beta period! Tips on getting good results from Bolt and increasing token usage efficiency can be found in issue #678
