### ISSUE TITLE
failed to deploy react project to netlify

### ISSUE THREAD

**Issue by jasonpython50** [stackblitz/bolt.new#344]
### Describe the bug

failed to deploy to netlify

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4e5giq

### Steps to reproduce

project runs successfully but cannot deploy to netlify

### Expected behavior

Project should deploy successfully

### Screen Recording / Screenshot

Failed to deploy my react code to netlify after several tries

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56081899,
  "usedJSHeapSize": 52769967,
  "jsHeapSizeLimit": 2172649472
}
Username = jasonpython50
Chat ID = 50a35f5041a8
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
