### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by Paul-BWS** [stackblitz/bolt.new#3446]
### Describe the bug

i keep getting white screen. im using lots of credits all the time just going over the same thing. Im trying to connect the app to firebase yet all i keep getting is auth errors and white screens. ive deleted tha app in firbase and created a new one. then added this new api data to boltai and go around again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tumcjd

### Steps to reproduce

just try to authenticate, it throws up an error. then when i ask it to fix the error it throws up a white screen. m just going around in circles. Thanks

### Expected behavior

white screen of death :-)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 129964536,
  "usedJSHeapSize": 66941924,
  "jsHeapSizeLimit": 4294705152
}
Username = Paul-BWS
Chat ID = fec8950cf4bd
```

**Comment by Paul-BWS** [comment]
its ok i managed to sort it. i need to enable email authentificification in Firebase.

**Comment by endocytosis** [comment]
Glad to hear you resolved the white screen issue (just FYI we are tracking this issue [here](https://github.com/stackblitz/bolt.new/issues/1791). The [Bolt Help Center](https://support.bolt.new) has a number of resources including working with Firebase. Hope this helps!
