### ISSUE TITLE
Unable to load into github

### ISSUE THREAD

**Issue by derricktyh** [stackblitz/bolt.new#345]
### Describe the bug

I was unable to load my public github into boltz. The github was made public from private, but i am unable to load it into github. The error is "You don't have access to the repository"
![Unable to load into github](https://github.com/user-attachments/assets/ae35c7a4-4bf2-4fda-9de6-2dcdc8b7e40d)

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/derricktyh/ToolCRMVersion1.0

### Steps to reproduce

![Github public](https://github.com/user-attachments/assets/fa83ca60-6bca-406c-a177-a8d192195664)

### Expected behavior

Public Github should be able to load into Bolt.new

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 40247247,
  "usedJSHeapSize": 36551787,
  "jsHeapSizeLimit": 4294705152
}
Username = derricktyh
Chat ID = 686fa899e758
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
We're tracking this internally. You can follow https://github.com/stackblitz/bolt.new/issues/95 to get notified when we've resolved this issue.
