### ISSUE TITLE
Question: Why the XML format for prompts?

### ISSUE THREAD

**Issue by Aschen** [stackblitz/bolt.new#3456]
Hello guys and first thanks you for making this Open Source, it's a great deal of useful information on LLM Engineering 😄 

I was looking into your [system prompt](https://github.com/stackblitz/bolt.new/blob/main/app/lib/.server/llm/prompts.ts#L6) and wondering why did you choose to use XML for the structured output format ?

I did [some benchmark](https://github.com/Aschen/llm-experiments/tree/master/prompt-action-benchmark) one year ago and XML had better generation performances but since then we decided to switch to JSON because the industry seems to have made a lot of effort for this format (e.g. OpenAI structured output with JSON).

That's why I'm curious, I'm trying to understand if there is a generation performance reason to use XML and if you guys have any insights it would be much appreciated ;-)

Thanks!

**Comment by adamdbradley** [comment]
It's a recommendation from Anthropic, which powers the LLM used by bolt: https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/use-xml-tags
