### ISSUE TITLE
preview not working?

### ISSUE THREAD

**Issue by iambutler** [stackblitz/bolt.new#3467]
### Describe the bug

The preview is not displaying anything. Is there an issue with some versions of chrome? I'm using a chrome book.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sqef8q

### Steps to reproduce

click the preview tab

### Expected behavior

no preview, just a white page

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61077026,
  "usedJSHeapSize": 54992150,
  "jsHeapSizeLimit": 2084569088
}
Username = iambutler
Chat ID = f0a66a985f3f
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
