### ISSUE TITLE
Potential Leak of Sensitive Prompt Logic 

### ISSUE THREAD

**Issue by Anest2009** [stackblitz/bolt.new#3494]
### Describe the bug

I wanted to bring to your attention a potential issue in this repository. The file located at:

https://github.com/stackblitz/bolt.new/blob/main/app/lib/.server/llm/prompts.ts

appears to expose a critical prompt that governs the foundational behavior of your AI, including how user-generated prompts are handled. This could lead to unintended use or replication of proprietary logic.

If this exposure was unintentional, I’d recommend reviewing and removing the file from the public repository to mitigate potential risks.

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

Navigate to the repository: https://github.com/stackblitz/bolt.new.
Browse to the file path: app/lib/.server/llm/prompts.ts.
Open the file to view its contents.
Observe that the file contains a sensitive prompt that governs AI behavior, exposing foundational logic and potential rules.

### Expected behavior

Sensitive files or configurations, such as the prompts.ts file containing AI foundational rules and logic, should not be exposed in a public repository.

Instead, such files should:

Be stored in a secure location (e.g., environment variables, private repositories, or encrypted storage).
Be excluded from version control using .gitignore or similar mechanisms.
Only be accessible to authorized team members or systems in a secure and controlled manner.
By securing this file, the integrity of the AI’s foundational rules and proprietary logic would remain protected.

### Screen Recording / Screenshot

![Screenshot 2024-12-01 115620](https://github.com/user-attachments/assets/9f328611-428c-4ab7-8015-d0ec451f6775)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by AriPerkkio** [comment]
Hey @Anest2009, thanks for the report!

The prompt instructions are intentionally public.
