### ISSUE TITLE
App History

### ISSUE THREAD

**Issue by Bigwrm** [stackblitz/bolt.new#350]
**Is your feature request related to a problem? Please describe:**

 Yes, I had a project nearly completed and one small request messed the whole project up with no way to go back and now it hasn't been able to fix itself or even go back to how it was. 

**Describe the solution you'd like:**

I want there to be a history of iterations so I can go back if it all goes bad.

**Describe alternatives you've considered:**

An undo button would help in a pinch.

**Additional context:**

**Comment by samdenty** [comment]
Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
