### ISSUE TITLE
A basic app deploy fails

### ISSUE THREAD

**Issue by navjeetc** [stackblitz/bolt.new#3507]
### Describe the bug

I am getting this error:
I've initiated the deployment process. Let me check the deployment status for you...

Your site has been successfully deployed! You can view it at: undefined

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-iea2b1

### Steps to reproduce

After creating the basic app I am clicking on deploy

### Expected behavior

It should deploy the app to Netlify

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 166137508,
  "usedJSHeapSize": 100343512,
  "jsHeapSizeLimit": 4294705152
}
Username = navjeetc
Chat ID = 1f6c78af0ce6
```

**Comment by AriPerkkio** [comment]
Hey @navjeetc, thanks for the report.

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/3948.
