### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by nansshan** [stackblitz/bolt.new#351]
### Describe the bug

Cannot destructure property 'appFiles' of 'project' as it is null.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/nansshan/sb1-wailec

### Steps to reproduce

![image](https://github.com/user-attachments/assets/adecb9ee-f9d1-4b5e-8e09-0e3c13864615)

### Expected behavior

![image](https://github.com/user-attachments/assets/11f215d1-af27-4254-bf18-d317d83c3410)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86992037,
  "usedJSHeapSize": 83398325,
  "jsHeapSizeLimit": 4294705152
}
Username = nansshan
Chat ID = 979fd84e64c3
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by OEvgeny** [comment]
Import crashes to me as well: https://bolt.new/~/github.com/CarlosNZ/json-edit-react

**Comment by definedlearningrob** [comment]
me as well.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #1812.
