### ISSUE TITLE
Lost majority of my project when I bought more tokens.  

### ISSUE THREAD

**Issue by jaywakeford** [stackblitz/bolt.new#352]
### Describe the bug

I ran low on tokens and purchased the new credits and then refreshed the browser to apply them I found that my project was backed up to several days ago.    

Now I am going to have to rebuild the project , and its a fullstack application build.    And I am going to have to pay credits to rebuld only because I purchased more credits.   Frustrating.  Highly disruptive. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wlgkaw

### Steps to reproduce

No steps required.  I would have to rebuild, buy more credits and have it revert the project again in order to reproduce.

### Expected behavior

I expect to have access to the latest build.  

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 118654965,
  "usedJSHeapSize": 102601813,
  "jsHeapSizeLimit": 4294705152
}
Username = jaywakeford
Chat ID = e67c31e444d3
```

**Comment by jaywakeford** [comment]
I should have been more patient.  This is NOT an error in the platform.    It just took time to reload the necessary files.  

The full scripts are visible now. 

Apologies for the panic.

**Comment by EricSimons** [comment]
Honestly just glad to hear everything is working well for you! No apologies needed :)

Closing for now but let us know if you run into any issues!
