### ISSUE TITLE
Frozen while installing dependencies

### ISSUE THREAD

**Issue by zerealthib** [stackblitz/bolt.new#3547]
### Describe the bug

i asked for the addition of an open street map section on the "cours" pages and it froze i think during the installation of the dependencies.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tdh7g9

### Steps to reproduce

i asked the following : 

"for the Nos Clubs page, please add an open street map with the multiple club locations, try to add about 6 clubs to fill the page nicely"

### Expected behavior

it should have been done installing the dependencies and update the page.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e8c1b001-717b-4236-92e7-ab6d4a065e79)

### Platform

```
Browser name = Firefox
Full version = 133.0
Major version = 133
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
performance.memory = undefined
Username = zethib
Chat ID = 03e534d3e612
```

### Additional context

I reverted to a previous step.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue regarding dependencies and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2021).
