### ISSUE TITLE
preview only white screen

### ISSUE THREAD

**Issue by 5cientist** [stackblitz/bolt.new#3548]
### Describe the bug

preview only white screen

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hxfen9

### Steps to reproduce

preview only white screen

### Expected behavior

preview only white screen

### Screen Recording / Screenshot

preview only white screen

### Platform

```
Browser name = Firefox
Full version = 133.0
Major version = 133
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
performance.memory = undefined
Username = hanshir
Chat ID = 1333cf890c19
```

### Additional context

preview only white screen

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791). Something to initially try is to make sure you are using Chrome or a Chromium browser as those are most compatible with Bolt.
