### ISSUE TITLE
this is nonsense

### ISSUE THREAD

**Issue by quintinappi** [stackblitz/bolt.new#356]
### Describe the bug

with every 2nd deployment or bug fix the response doesnt complete !!!!!!!!!!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-x4jhci

### Steps to reproduce

1. type a request
2. bolt starts fixing
3. bolt says couldnt comlete

### Expected behavior

as above

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75261743,
  "usedJSHeapSize": 69569243,
  "jsHeapSizeLimit": 2172649472
}
Username = quintinappi
Chat ID = 0186ba88082d
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by kc0tlh** [comment]
@quintinappi we are working on improving reliability. In the meantime, there are many tips on how to get better results in #678
