### ISSUE TITLE
Chats are not saved, only the "project" is saved.

### ISSUE THREAD

**Issue by Freffles** [stackblitz/bolt.new#357]
The UI implies that I can access previous chats. When I do, the project is effectively reloaded and I lose all the back and forth that I had with bolt.new. The project is correct and up to date but I was looking to continue the chat where I left off. Its helpful to be able to walk back through the chat history

**Comment by kc0tlh** [comment]
@Freffles Thanks for the feedback! We are working on the resolution to this issue and tracking in #17
