### ISSUE TITLE
1 simple question about styles on a mouse pointer burnt 1 million tokens and made no changes. sort your selves out.

### ISSUE THREAD

**Issue by Imrickjamesbitch88** [stackblitz/bolt.new#360]
### Describe the bug

absolute missmanagement of tokens. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-j2ik54

### Steps to reproduce

any prompt. has degraded in quality since release

### Expected behavior

cacheing and efficient use of claude 3.5 or add gpt4omini for minor prompts and finetuning.

### Screen Recording / Screenshot

go to the link and check runtime

### Platform

```
Browser name = Chrome
Full version = 127.0.0.0
Major version = 127
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 OPR/113.0.0.0
performance.memory = {
  "totalJSHeapSize": 96914184,
  "usedJSHeapSize": 94741288,
  "jsHeapSizeLimit": 4294705152
}
Username = Imrickjamesbitch88
Chat ID = b29750d0b1e8
```

### Additional context

unuseable service at that pricepoint. and i should be able to import existing repos into bolt whats the go?

**Comment by kc0tlh** [comment]
@Imrickjamesbitch88 apologies for any frustration during this beta period!

Tips for token usage efficiency and error handling (and our efforts to automate some of this) are tracked in #678.
