### ISSUE TITLE
Part of code missing when receiving "keep the rest of the component unchanged" from LLM

### ISSUE THREAD

**Issue by Zihann73** [stackblitz/bolt.new#361]
### Describe the bug

After interacting with LLM for the second time, some code returned an omitted version of the result, but bolt.new did not add these codes back.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a3acxf

### Steps to reproduce

There is no definite path to reproduce. 
It is often encountered that after doing A first and then doing B, the code changed by A is restored.

### Expected behavior

The previous code still exists.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/5892f9d3-bbde-4356-8516-54c1c6f0f0ea)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 129.0.6668.90 (Official Build) (arm64)

**Comment by armandojaleo** [comment]
I have the same problem, only you need to detail better that you need all next time and don't forget anything.

**Comment by samdenty** [comment]
This is pretty frustrating indeed!

We're tracking this internally. You can follow https://github.com/stackblitz/bolt.new/issues/124 to get notified when we've resolved this issue.

**Comment by Zihann73** [comment]
> I have the same problem, only you need to detail better that you need all next time and don't forget anything.

It helps a lot for now. Big thx!

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
