### ISSUE TITLE
did not work

### ISSUE THREAD

**Issue by FromByond** [stackblitz/bolt.new#362]
### Describe the bug

I'm not sure but it did not work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kedpvd

### Steps to reproduce

just typed in the prompt .. thats it

### Expected behavior

it didn't work

### Screen Recording / Screenshot

not sure why
![Screenshot 2024-10-10 at 12 03 49 PM](https://github.com/user-attachments/assets/e8495e2c-dba9-4cda-9203-2c26734206f7)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61776531,
  "usedJSHeapSize": 43482567,
  "jsHeapSizeLimit": 4294705152
}
Username = FromByond
Chat ID = 60848bb571a3
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
