### ISSUE TITLE
Project not found

### ISSUE THREAD

**Issue by jfabraxas** [stackblitz/bolt.new#363]
### Describe the bug

My project is away - can't find it neather on stackblitz nor on bolt.new

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-chzpzz

### Steps to reproduce

1. Created a project
2. work on it
3. switch to stackblitz and back to bolt

### Expected behavior

project should persist

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 44598403,
  "usedJSHeapSize": 36716175,
  "jsHeapSizeLimit": 4294705152
}
Username = jfabraxas
Chat ID = 986befba0bec
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/50
