### ISSUE TITLE
Impossible to deploy

### ISSUE THREAD

**Issue by Githli24** [stackblitz/bolt.new#3659]
### Describe the bug

I cannot deploy my application
Error : ReferenceError: process is not defined

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qkx3mr

### Steps to reproduce

click on "Deploy"

### Expected behavior

No preview available

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126678345,
  "usedJSHeapSize": 107830013,
  "jsHeapSizeLimit": 4294705152
}
Username = Githli24
Chat ID = 7d46746b4a61
```

**Comment by Legend-parth** [comment]
**HI! I CAN'T UNDERSTAND THE ISSUE AND IF I OPEN YOUR LINK THEN IT SHOWS ME THAT I DON'T HAVE ACCESS TO IT , IF YOU CONVERT IT TO SECRETED BY URLFROM PRIVATE THEN I MIGHT HELP**

**Comment by Githli24** [comment]
<img width="953" alt="Bolt Issue" src="https://github.com/user-attachments/assets/ddbafa49-3e6a-49a5-9c6e-60030cf52dd2">

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with the preview not displaying and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
