### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by VidyaMandava** [stackblitz/bolt.new#3669]
### Describe the bug

Developing game, presssing an alphabet should play its phonetic sound. But its not playing. Same is te case with images, apple & other images are not displayed.
"Sound loading error:""/sounds/success.mp3"4
   at Howl2.onloaderror (/src/utils/audio.ts?t=1733319181458:11:41)
   at Howl2.<anonymous> (/node_modules/.vite/deps/howler.js?v=0cfeff4c:1348:20)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-r92nmi

### Steps to reproduce

public/sounds/a.mp3
src/utils/audio.ts
src/App.tsx

### Expected behavior

Screen will have alphabet & its corresponding images like apple, ball . PRessing alphabet should play sound.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/524ef1b0-f9ad-456b-a3f5-ebb167d9c5a9)
![game](https://github.com/user-attachments/assets/a04b6ea0-67f6-4b6c-85e9-b660801f772a)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62529522,
  "usedJSHeapSize": 51304962,
  "jsHeapSizeLimit": 2197815296
}
Username = VidyaMandava
Chat ID = 5a7915e3df55
```

**Comment by endocytosis** [comment]
Unfortunately we don't have the resources to offer programming support for individual projects. You can read more about continuing to develop your project [here](https://github.com/stackblitz/bolt.new/issues/2310). The [Bolt Help Center](https://support.bolt.new) also has a number of resources on using Bolt most effectively.
