### ISSUE TITLE
Can't see the preview of the generated code

### ISSUE THREAD

**Issue by Sash-Up** [stackblitz/bolt.new#3678]
### Describe the bug

When bolt generates code in my browser (OperaGX) it does not display no matter how many times I ask it to display it or trying to do a different project.
![image_2024-12-04_165519729](https://github.com/user-attachments/assets/ee18b58e-851e-4ee0-94ed-2b3e5ecd96c7)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n5ni7z

### Steps to reproduce

1. Go to bolt.new on OperaGX
2. ask it to code a project
3. Try to preview the project

### Expected behavior

I expected it to preview the code that I asked for

### Screen Recording / Screenshot

![image_2024-12-04_165704002](https://github.com/user-attachments/assets/b122bcb3-b7a1-4ff4-ad82-fd460b6449db)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 68211325,
  "usedJSHeapSize": 63259881,
  "jsHeapSizeLimit": 2172649472
}
Username = Sash
Chat ID = f87c2c5b265d
```

**Comment by AriPerkkio** [comment]
Hey @Sash-Up, you can see the error in the chat:

![image](https://github.com/user-attachments/assets/2224b294-c9ff-4185-9021-118f466cd513)
