### ISSUE TITLE
Preview show blank screen on Safari

### ISSUE THREAD

**Issue by vision360deg** [stackblitz/bolt.new#3685]
### Describe the bug

After inputting the first prompt and enhancing it, Bolt goes off and builds the website. However the preview shows nothing but a blank screen 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hzym3h

### Steps to reproduce

1. Input prompt to build a website
2. Enhance the promo
3. After it's done building the preview shows nothing but a blank screen

### Expected behavior

the preview should at least show something

### Platform

```
Browser name = Safari
Full version = 18.1.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15
performance.memory = undefined
Username = usian
Chat ID = 300cfa7e5a93
```

**Comment by endocytosis** [comment]
Bolt is most compatible with Chrome and Chromium browsers as described [here](https://github.com/stackblitz/bolt.new/issues/2796).
