### ISSUE TITLE
bolt keeps redeploying as a new site URL

### ISSUE THREAD

**Issue by baiken315** [stackblitz/bolt.new#3697]
### Describe the bug

After deployment, when fixing bugs and updating code, when redeploying, bolt continues to deploy to an entirely different location. It has updated the .env and netlify.toml for NETLIFY_SITE_ID, and I have also manually updated and saved those as the correct ID in the code, but deployment still creates a new site each time. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v4tgh3

### Steps to reproduce

deploying from prompt or hitting "deploy" button 

### Expected behavior

deploy to the existing site

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
performance.memory = {
  "totalJSHeapSize": 168484105,
  "usedJSHeapSize": 164152905,
  "jsHeapSizeLimit": 4294705152
}
Username = baiken315
Chat ID = 620736e6931b
```

**Comment by codewithtyler** [comment]
Try going to your account settings in Bolt and under Applications link your Netlify account to your Bolt account. Once you claim your link it should deploy to the same URL every time after that.

**Comment by baiken315** [comment]
omg. of course. thank you. my mind is absolutely blown by this software. you guys are changing my world here. thank you.
