### ISSUE TITLE
Displaying a bottomsheet and correcting a bug

### ISSUE THREAD

**Issue by lagapollo** [stackblitz/bolt.new#3708]
### Describe the bug

I'm creating a mood app, and want to show a bottomsheet when clicking on sad. 

The app created displayed a popup, then a new page, but never a bottomsheet, now the button does not work at all

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nativescript-js-zbxvmj

### Steps to reproduce

click on sad, a bottomsheet should appear

### Expected behavior

the bottomsheet should appear

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52542482,
  "usedJSHeapSize": 49445526,
  "jsHeapSizeLimit": 4294705152
}
Username = lagapollo
Chat ID = 83cebd116344
```

**Comment by endocytosis** [comment]
Unfortunately we don't have the resources to offer programming assistance for individual projects. You can read more about continuing to develop your project [here](https://github.com/stackblitz/bolt.new/issues/2310).
