### ISSUE TITLE
 Bolt crashes on TypeError: t.toSorted is not a function 

### ISSUE THREAD

**Issue by endocytosis** [stackblitz/bolt.new#3711]
**Issue:** User receives the following application breaking error. Collecting similar cases to investigate further. 

![image](https://github.com/user-attachments/assets/0511ebc3-eefb-407c-a1b4-0aa395c91abb)

**Comment by AriPerkkio** [comment]
- https://github.com/stackblitz/bolt.new/issues/2425#issuecomment-2478225369
- https://github.com/stackblitz/bolt.new/issues/519#issuecomment-2495411950

**Comment by AriPerkkio** [comment]
This is now fixed.
