### ISSUE TITLE
stock and crypto price display bug

### ISSUE THREAD

**Issue by zakiii33** [stackblitz/bolt.new#3731]
### Describe the bug

I've managed to enter the names of the crytpo and stocks I want the course to change but it's not the right course nor the right marketcap. How can I solve this problem?
![Capture d'écran 2024-12-05 130146](https://github.com/user-attachments/assets/5ba77bd3-10f7-47b0-ad46-8547f3d804e0)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lqaz3y

### Steps to reproduce

go to the chat and scroll to the 2 last messages

### Expected behavior

I wanted to know the real price of shares and cryptos

### Screen Recording / Screenshot

![Capture d'écran 2024-12-05 130146](https://github.com/user-attachments/assets/b55003b6-dd8a-4f42-9e34-22821876552b)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 105467131,
  "usedJSHeapSize": 101856639,
  "jsHeapSizeLimit": 4294705152
}
Username = ozaii33
Chat ID = b303622841af
```

**Comment by endocytosis** [comment]
Unfortunately we don't have the resources to offer programming assistance for individual projects. You can read more about continuing to develop your project [here](#2310).
