### ISSUE TITLE
Bolt is becoming "lazy", it deliver part of the code with placeholders

### ISSUE THREAD

**Issue by AlexandreCalvet** [stackblitz/bolt.new#3732]
### Describe the bug

When I ask bolt to modify an existing file it erase the whole file and rewrite only a part of it put place holder everywhere to identify where to put the previous code resulting on a file full of comment and that is not working 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ed4lyf

### Steps to reproduce

create a file with code
Ask change 
see the result

### Expected behavior

it should deliver the full functionning file with the changes included and the previous code to keep

### Screen Recording / Screenshot

<img width="879" alt="Monosnap bolt new~sb1-ed4lyf 2024-12-05 13-13-36" src="https://github.com/user-attachments/assets/cf51ce32-e47d-45d9-bebf-f2bf06aaaea7">

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 167072529,
  "usedJSHeapSize": 157926421,
  "jsHeapSizeLimit": 4294705152
}
Username = AlexandreCalvet
Chat ID = ef0c8929c2d2
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2862).
