### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by Chousman** [stackblitz/bolt.new#3744]
### Describe the bug

The Preview is blank and not visiable

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5x7byl

### Steps to reproduce

view webiste preview

### Expected behavior

I expected to see a preview 

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56370804,
  "usedJSHeapSize": 46889116,
  "jsHeapSizeLimit": 4294705152
}
Username = Chousman
Chat ID = 624d20fa8721
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with the preview not displaying and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
