### ISSUE TITLE
[Error]Import public repo into bolt

### ISSUE THREAD

**Issue by mickitty0511** [stackblitz/bolt.new#375]
### Describe the bug

When trying importing vscode repo into bolt, got the following error, which is not unfamiliar to me.

import microsoft/vscode/tree/main
Cannot destructure property 'appFiles' of 'project' as it is null.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/microsoft/vscode/tree/main

### Steps to reproduce

Just add bolt.new/ before github.com domain in the URL and wait until this error happened.

### Expected behavior

Safely importing the public repo into bolt.new without errors.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/2e6f25ea-e9db-4ffc-9393-f9f50b3763c9)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 39685473,
  "usedJSHeapSize": 36696173,
  "jsHeapSizeLimit": 4294705152
}
Username = Nerv
Chat ID = 9a041e88ad6d
```

### Additional context

I do ~~not~~ suppose this feature is good, but for now it is challenging and tricky to handle these kinds of errors for me.
Hope we will get a smaller number of them near future.

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1812.
