### ISSUE TITLE
It's on the project. I can't even get the preview to work and I've tried multiple different command pros. I even went and tried to create a light version with a simple command and nothing. It's really hard for me to take my harder and cash to invest in this and there's no turnaround. I'm very disappointed.

### ISSUE THREAD

**Issue by ArchiCAD1** [stackblitz/bolt.new#3751]

**Comment by endocytosis** [comment]
Apologies for the frustration! The preview not displaying is a known issue that we are tracking [here](https://github.com/stackblitz/bolt.new/issues/1791). For further assistance, please reach out to hello@stackbiltz.com with your account information. Thanks!
