### ISSUE TITLE
not showing preview after website genration

### ISSUE THREAD

**Issue by Cyansiiii** [stackblitz/bolt.new#3752]
### Describe the bug

not showing preview after website genration

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qcojk1

### Steps to reproduce

preview

### Expected behavior

not showing of my website genration 

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46261399,
  "usedJSHeapSize": 41920435,
  "jsHeapSizeLimit": 2197815296
}
Username = anandam
Chat ID = 7aa85922a7f1
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue of the preview not displaying and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
