### ISSUE TITLE
This is a joke - Bolt Customer Service Does Not Answer - Wasting Money

### ISSUE THREAD

**Issue by bkowalski21** [stackblitz/bolt.new#3754]
### Describe the bug

Is the ai programmed to get people to waste money?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jlzkx2

### Steps to reproduce

why is this so bad?

### Expected behavior

I expect it to work

### Screen Recording / Screenshot

why is this so bad? why does no one from customer service answer?

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 308813201,
  "usedJSHeapSize": 225968909,
  "jsHeapSizeLimit": 4294705152
}
Username = bkowalski21
Chat ID = 3b829865bc7b
```

### Additional context

why is this so bad?

**Comment by endocytosis** [comment]
Hi, please reach out to hello@stackblitz.com so we can assist you further. Thank you.
