### ISSUE TITLE
Cannot destructure property 'appFiles' of 'project' as it is null. There was an error processing your request

### ISSUE THREAD

**Issue by mz0in** [stackblitz/bolt.new#378]
### Describe the bug

<img width="889" alt="image" src="https://github.com/user-attachments/assets/51359504-80f1-474f-b0d6-2514b3916c64">
 Cannot destructure property 'appFiles' of 'project' as it is null.
There was an error processing your request

### Link to the Bolt URL that caused the error

nul

### Steps to reproduce

import a public repo 

### Expected behavior

import 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1812.
