### ISSUE TITLE
My preview for bolt is not showing despite installing dependencies 

### ISSUE THREAD

**Issue by Vern14** [stackblitz/bolt.new#379]
### Describe the bug

My preview for bolt is not showing despite installing dependencies . It's just showing a white blank screen 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aeg6ku

### Steps to reproduce

I prompted it and asked it to install dependencies once it was done generating but didn't show output 

### Expected behavior

I expected to see the output. Nothing is showing. The code is generating fine

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45062426,
  "usedJSHeapSize": 42523934,
  "jsHeapSizeLimit": 522452992
}
Username = Vern14
Chat ID = 584bc09d867e
```

### Additional context

My email address is vzidana@gmail.com   contact me there

**Comment by endocytosis** [comment]
Appreciate the feedback here. We are tracking this issue: [#1791](https://github.com/stackblitz/bolt.new/issues/1791). You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
