### ISSUE TITLE
bug: the code spills to the left hand side

### ISSUE THREAD

**Issue by fasakinhenry** [stackblitz/bolt.new#38]
### Describe the bug

the code does not complete due to the fact that it creates the code in the left hand side instead of the actual editor itself

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zxv3av

### Steps to reproduce

This is my prompt: Build a fully blown app using react, javascript and tailwindcss with appwrite as the backend that helps people to find new jobs. Use anthropic AI and ChatGPT for analysis of jobs. Sign in with github and google should be present. Let it have a lot of features including resume ai and building, ability to get profile info by updating LinkedIn bio profile pdf, job copilot, interview prep with questions, learning roadmap, dashboard, social connections and explore pages and all

See what it does

### Expected behavior

it should write the code in the files and editor

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 300111586,
  "usedJSHeapSize": 127525114,
  "jsHeapSizeLimit": 2172649472
}
Username = fasakinhenry
Chat ID = 306341a599fb
```

**Comment by Nemikolh** [comment]
Hey @fasakinhenry! I think you're running into the same issue as #26. I'll close this issue, feel free to reopen if you think your issue is actually different.
