### ISSUE TITLE
A waste of a lot of tokens

### ISSUE THREAD

**Issue by Doryaa13** [stackblitz/bolt.new#380]
### Describe the bug

I've been trying for a whole day to deploy to a simple application I built with BOLT without success.
Every time he writes that he does and fails to do it through Netlify

### Link to the Bolt URL that caused the error

https://unrivaled-lebkuchen-d096ae.netlify.app/

### Steps to reproduce

go to https://unrivaled-lebkuchen-d096ae.netlify.app/
its not working.
i delete the site from the netlify.
now i want to make a new deploy with a new link/ 

### Expected behavior

I wanted him to open a new link for me to claim on netlify
And I will get a new link that I can send to friends

### Platform

- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@Doryaa13 @Kumala3 apologies for any frustration during this beta period!

Tips for token usage efficiency and error handling (and our efforts to automate some of this) are tracked in #678.
