### ISSUE TITLE
Saving project to Stackblitz wipes out Bolt session

### ISSUE THREAD

**Issue by mattsterp** [stackblitz/bolt.new#381]
### Describe the bug

After saving to Stackblitz my Bolt instance was cleared out to a blank project.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zyqlik

### Steps to reproduce

Save a large Bolt session to Stackblitz 
Bolt session is cleared out 

### Expected behavior

The Bolt session remains 

### Platform

- OS: macOS
- Browser: Chrome

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
