### ISSUE TITLE
Bolt wastes tokens 

### ISSUE THREAD

**Issue by mattsterp** [stackblitz/bolt.new#382]
### Describe the bug

Ive lost so many large sections of projects, so much back and forth with the same errors, so much opening a project t find its gone.  I feel like most of my token for the month were wasted.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zyqlik

### Steps to reproduce

Work with Bolt 

### Expected behavior

Bolt should detect when its in a loop with bugs.  

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Kumala3** [comment]
I understand your frustration because I had the same, especially when it comes to a loop of errors, you can loop 100k tokens easily.

**Comment by kc0tlh** [comment]
@mattsterp @Kumala3 apologies for any frustration during this beta period!

Tips for token usage efficiency and error handling (and our efforts to automate some of this) are tracked in #678.
