### ISSUE TITLE
broken netlify link 

### ISSUE THREAD

**Issue by cryptonyte9** [stackblitz/bolt.new#3829]
### Describe the bug

Site deployed on netlify has a broken link  and can't be found. Please help
https://gleeful-parfait-4dd4b5.netlify.app/

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vu3https://gleeful-parfait-4dd4b5.netlify.app/nnf

### Steps to reproduce

click link for website

### Expected behavior

this is what i need.
I've successfully imported your project. I'm ready to assist you with analyzing and improving your code.

Your project has been previously deployed to https://gleeful-parfait-4dd4b5.netlify.app/ and is owned by the StackBlitz Netlify account.

If you want to deploy this project to your personal account, claim ownership by visiting undefined and connect with Netlify.

### Screen Recording / Screenshot

I can't do any of this message from bolt.

I've successfully imported your project. I'm ready to assist you with analyzing and improving your code.

Your project has been previously deployed to https://gleeful-parfait-4dd4b5.netlify.app/ and is owned by the StackBlitz Netlify account.

If you want to deploy this project to your personal account, claim ownership by visiting undefined and connect with Netlify.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49087103,
  "usedJSHeapSize": 46736523,
  "jsHeapSizeLimit": 2197815296
}
Username = alhasan999
Chat ID = e9c2fe19143a
```

### Additional context

none

**Comment by AriPerkkio** [comment]
This issue is now fixed. 
- https://github.com/stackblitz/bolt.new/issues/3948
