### ISSUE TITLE
Version Rollback Capability

### ISSUE THREAD

**Issue by Wangxs404** [stackblitz/bolt.new#385]
I recently encountered a situation where I was dissatisfied with the results of a particular update or change. Unfortunately, there was no option to revert to a previous version, which left me feeling somewhat stranded. This experience highlighted the importance of having a version rollback feature, especially in scenarios where unintended consequences arise from updates or changes.

**Comment by samdenty** [comment]
@pkeller3 Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
