### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by sheacurran311** [stackblitz/bolt.new#388]
### Describe the bug

Application Error
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fe (https://bolt.new/assets/components-g8_Fbz61.js:24:33638)
    at np (https://bolt.new/assets/components-g8_Fbz61.js:22:22233)
    at gB (https://bolt.new/assets/_index-B5w_AeNx.js:3:631)
    at https://bolt.new/assets/_index-B5w_AeNx.js:3:700
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-B5w_AeNx.js:3:689
    at gB (https://bolt.new/assets/_index-B5w_AeNx.js:3:631)
    at https://bolt.new/assets/_index-B5w_AeNx.js:3:700
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-B5w_AeNx.js:3:689

### Link to the Bolt URL that caused the error

https://bolt.new/~

### Steps to reproduce

Go to project.

### Expected behavior

The project won't load - I keep getting this application error.

### Platform

Windows
Chrome

**Comment by samdenty** [comment]
Hey everyone! Sorry for the inconvenience, we're going to track this in https://github.com/stackblitz/bolt.new/issues/260
