### ISSUE TITLE
Where did the 11M tokens go?

### ISSUE THREAD

**Issue by andaydvice** [stackblitz/bolt.new#3883]
### Describe the bug

I had 11M tokens before the subscription was updated and now they have all gone?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dc952t

### Steps to reproduce

I expected the 11M tokens to be added to the 26M I just paid for

### Expected behavior

I expected the 11M tokens to be added to the 26M I just paid for

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67337135,
  "usedJSHeapSize": 66176451,
  "jsHeapSizeLimit": 4294705152
}
Username = andaydvice
Chat ID = cb6f183c6e3c
```

### Additional context

Why don't the unused tokens roll over to the next month as I paid for them?

**Comment by endocytosis** [comment]
Tokens are described further [here](https://support.bolt.new/Tokens-13fd971055d6804ea762d2fafdc3ad98). Tokens as part of a paid subscription do not roll over from month to month. When you upgrade from a lower tier to higher tier plan, tokens already used in the billing cycle remain used upon upgrade.

**Comment by andaydvice** [comment]
Hi Brian

so multiple millions of tokens are wasted through errors and you lose the
11M token that you pay for instead of rolling over. Why?

Kind Regards

Andrew Edwards
