### ISSUE TITLE
AI overwrites files with partial code.

### ISSUE THREAD

**Issue by ignBiometrical** [stackblitz/bolt.new#389]
### Describe the bug

When making changes, bolt.new will sometimes overwrite all the code and only provide a portion, which will then break all the code and replaces it with nothing.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vtzhos

### Steps to reproduce

Use bolt.new, no exact way to reproduce, just using it causes it.

### Expected behavior

It will update the code with new changes, and not overwrite the entire thing.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samdenty** [comment]
This is pretty frustrating indeed!

We're tracking this internally. You can follow https://github.com/stackblitz/bolt.new/issues/124 to get notified when we've resolved this issue.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
