### ISSUE TITLE
Feature Request: Add Chat Persistence Across Devices & Sessions

### ISSUE THREAD

**Issue by adenkaplan** [stackblitz/bolt.new#39]
### Describe the bug
When I refresh the page, all my old conversations are removed, and I couldn't find on the conversation list on the left panel.

## Temporary Workaround / How To Open Chats On a New Session or Device
1. Login to StackBlitz.com (same account as Bolt.new)
2. Open the Collections Tab
3. Open the Bolt collection
4. Open the project you want to edit in Bolt
5. Press the "Open in Bolt" button and continue coding!

## How to Use Backups to Rollback Code to Prior Project Versions
1) Hover over the left-hand side of the page to bring up the options menu.
2) Click Settings.
3) Click Backups.
4) Select the relevant backup to rollback code to prior project version.

**Comment by patiljignesh** [comment]
Same issue, using safari.

**Comment by Nemikolh** [comment]
Hey @adenkaplan and @patiljignesh!

The conversation is indeed not persisted between refresh, we've added this feature to our internal tracker.

We'll keep you posted when this is implemented.

**Comment by mauriciorubio2** [comment]
Same 🤦🏻‍♂️. Lost hours of work and multiple apps I had built 🤯. Major issue: https://github.com/stackblitz/bolt.new/issues/160

**Comment by swcrazyfan** [comment]
This is really truly horrible. There was no notification that chat will disappear, and now I've lost hours of progress. Really disappointed. I paid for the pro version, too.

**Comment by kc0tlh** [comment]
Keeping chat history is indeed an important feature that we are working rapidly to add! This is on our high priority roadmap and will be addressed very soon. 

Appreciate all of your feedback and patience!

**Comment by adenkaplan** [comment]
In fact, that's why I only have 2M tokens left from 10M tokens. Because I had to rewrite everything for the 3rd time. By the way, I think users will need instructions on how to edit their texts or instructions to the AI. Because it always forgets what I say over and over again. After a while, it becomes difficult for the AI ​​to remember the instructions

**Comment by kc0tlh** [comment]
**Update: How To Open Chats On a New Browser/Device** 
1. Login to StackBlitz.com (same account as Bolt.new) 
2. Open the Collections Tab
3. Open the Bolt collection
4. Open the project you want to edit in Bolt
5. Press the "Open in Bolt" button and continue coding!

**Comment by larhou** [comment]
Can someone clarify if this means that chat history is persisted now ? And that we don’t have to copy paste chat dialogues and store locally to avoid the risk of loosing the chat dialogue ?

**Comment by mauriciorubio2** [comment]
@larhou , as you can see this ticket is still open, which basically means chat history isn't saved yet. But they're working on a fix for this and I understand it will be landing soon. This is obviously a critical issue that still needs to be resolved (short term priority).
For the time being, keep saving history manually. That's what I'm doing too, since you don't want to lose the record, prompts, etc.

**Comment by larhou** [comment]
Thanks! Will make a big difference when this is implemented.

**Comment by Habartru** [comment]
> Привет @adenkaplan и @patiljignesh!
> 
> Разговор действительно не сохраняется между обновлениями, мы добавили эту функцию в наш внутренний трекер.
> 
> Мы будем держать вас в курсе, когда это будет реализовано.

Can I expect a refund of tokens, since my projects and the money spent on them are lost to me?

**Comment by alan313313** [comment]
Any progress on this?

**Comment by kc0tlh** [comment]
If you are looking for a project that is no longer in your Bolt sidebar, here's where you should find it:

**Find Missing Chats or Open Chats On a New Session/Browser/Device**
1. Login to StackBlitz.com (same account as Bolt.new)
2. Open the Collections Tab
3. Open the Bolt collection
4. Open the project you want to edit in Bolt
5. Press the "Open in Bolt" button and continue coding!

CC: @alan313313 @Habartru @larhou @mauriciorubio2 @adenkaplan @patiljignesh 

We will be shipping the final fix for this no later than end of next week, thanks for your patience 🙏🏻

**Comment by lewismcgui** [comment]
The collection thing didn't work for me as when i reloaded the url, it 'updated' the app code and rewrote it with nothing, as there is no revisions all the code is gone?

**Comment by kc0tlh** [comment]
@lewismcgui then I think [this update posted 1 minute ago](https://github.com/stackblitz/bolt.new/issues/1104#issuecomment-2445407033) may be what you need.

**Comment by alan313313** [comment]
I did send you an email requesting to restore my project at hello@stackblitz.com

Is anyone processing this?

**Comment by kc0tlh** [comment]
@alan313313 yes, but we have a backlog at the moment. Have you tried the [instructions here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2445044619) and the [instructions here](https://github.com/stackblitz/bolt.new/issues/1104#issuecomment-2445407033) yet?

**Comment by alan313313** [comment]
@kc0tlh yes sir, I did try that. Before I found this thread I absolutely screwed up my project and now the only saving grace is the restore. 
Anyway, I'll wait.

**Comment by plataformaconcreta** [comment]
Again.... error. Lots 14M credits!!!
<img width="789" alt="Screenshot at Nov 10 11-28-09" src="https://github.com/user-attachments/assets/ed799e65-6b25-4ed8-a2c5-fbf5ae7c324a">

**Comment by jackccrawford** [comment]
Suggest you add a bug discovery credit (tokens). Rewards can be small, because hard work should be appreciated. I know that I would be grateful and become an even more zealous fan.

**Comment by endocytosis** [comment]
**Update:** The engineering team recently released chat persistence! Please let us know if you encounter any issues accessing your chats across sessions and devices. We appreciate your patience as the team continues to make improvements!

**Comment by sirking1991** [comment]
> **Update:** The engineering team recently released chat persistence! Please let us know if you encounter any issues accessing your chats across sessions and devices. We appreciate your patience as the team continues to make improvements!

Great! Workin on my end. Thank you!

**Comment by endocytosis** [comment]
Excellent, glad to hear it!

**Comment by elogicuk** [comment]
> **Update:** The engineering team recently released chat persistence! Please let us know if you encounter any issues accessing your chats across sessions and devices. We appreciate your patience as the team continues to make improvements!

im a new user signed up today, loaded $50 tokens started to work. 
refreshed the page and hours of my chat had vanished.
so angry money and time wasted.

**Comment by kc0tlh** [comment]
@elogicuk please reach out to hello@stackblitz.com so I can help you directly!

**Comment by elogicuk** [comment]
another day more problems i am getting very angry this is not ok to take customers money and provide a buggy app like this.

i refreshed my page today and it lost hours of my work, and restoring the backup from 5mins ago does not fix it.

how can a simple refresh lose hours of chat and files??????

**Comment by vieuxgrizou** [comment]
and for all the lost credits you will make a gesture because I had to pay again to continue and relaunch the whole project from a new bolt + github I lost half a day there

 ???

**Comment by endocytosis** [comment]
Hi all, 

Refund requests can be handled through hello@stackblitz.com.

**Comment by raphael-pietrzak** [comment]
I encountered an issue after linking my GitHub account to my Bolt profile. Here’s what happened:
	1.	I logged in to Bolt using my email address.
	2.	I linked my GitHub account to my Bolt profile.
	3.	After Bolt updated my profile to reflect my GitHub information, the chats stopped loading.

Now, every time I try to access the chats, I see a toast error message:
“Failed to load chats.”

**Comment by pksorensen** [comment]
@endocytosis - is it possible to extract/export full chat sessions from my projects? I want publish some videos from 40hours of bolt recordings i have done and would like to try add a narrator ontop of the videos based on the prompts/chat messages, but seems that i only can get the last 10 or so messages in the api?
