### ISSUE TITLE
The AI didn't fix what it said that fixed!

### ISSUE THREAD

**Issue by yohanbrc** [stackblitz/bolt.new#3900]
### Describe the bug

I has been happining very often.

I ask the AI to fix a few issues, and the AI understand my request and it returns a message the issue is fixed, but it hasn't been fixed and it took a good amount of my tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-d2h55q

### Steps to reproduce

1 - ask
2 - press enter
3 - verify
4 - not fixed

### Expected behavior

To fix the issues that AI said that was fixed

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72978578,
  "usedJSHeapSize": 67398182,
  "jsHeapSizeLimit": 4294705152
}
Username = yohanbrc
Chat ID = 8427544f3b2a
```

**Comment by mbhvl** [comment]
Yes seen this a lot of times.  The AI doesn't do what it says it did.  To be fair, we see this in foundation model LLMs directly.

**Comment by endocytosis** [comment]
Hi all, 

Yes, at times, the AI is unable to resolve the problem and manual intervention is required. The team is hard at work continuing to add hard coded logic as able to fix common errors. Appreciate the feedback!
