### ISSUE TITLE
You have hit the rate limit. Please Upgrade to keep chatting, or you can continue coding for free in the editor

### ISSUE THREAD

**Issue by nipperuk** [stackblitz/bolt.new#3919]
### Describe the bug

I am receiving the message below even though I have purchased more tokens and have 10.0M monthly tokens remaining

{"code":"rate-limited","message":"You have hit the rate limit. Please <a class=\"__boltUpgradePlan__\">Upgrade</a> to keep chatting, or you can continue coding for free in the editor.","providerLimitHit":false,"isRetryable":true}

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qcgkbunr

### Steps to reproduce

Try and enter another prompt

### Expected behavior

Should be able to enter more prompts with 10.0M tokens remaining

### Screen Recording / Screenshot

![Capture](https://github.com/user-attachments/assets/869451a8-72d5-4a29-9806-d5163ba8845e)

### Platform

Windows 10, Chrome Version 131.0.6778.109

**Comment by endocytosis** [comment]
Please reach out to hello@stackblitz.com so we can assist you further.
