### ISSUE TITLE
Can't deploy application

### ISSUE THREAD

**Issue by MrHafez06** [stackblitz/bolt.new#392]
### Describe the bug

I tried to deploy the website and it just wouldn't work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fbxrcq

### Steps to reproduce

Go to the code. 

Press deploy. 

### Expected behavior

It should deploy the app on netlify

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = MrHafez06
Chat ID = 1f4b4bc07cda
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
