### ISSUE TITLE
Incomplete Code

### ISSUE THREAD

**Issue by oakunion** [stackblitz/bolt.new#393]
### Describe the bug

The code is written to the file and then right before it completes, it's erased to about 1/2 of its desired length.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mmnszj

### Steps to reproduce

Edit the inventory.tsx file.
Claude/Bolt outputs code.
Claude/Bold deletes half of the code.

### Expected behavior

I've already described what's happening and what's expected. Full code output is being erased to half-code output with AI-side deletion.

### Platform

```
Browser name = Firefox
Full version = 129.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
performance.memory = undefined
Username = oakunion
Chat ID = 2beb59ba405d
```

**Comment by mikes-bowden** [comment]
I'm having the same issue today. I refreshed, thinking that might help, and half of the files are missing, along with previous chats in the past. I'm not too pleased with all the lost progress.

**Comment by samdenty** [comment]
This is pretty frustrating indeed!

We're tracking this internally. You can follow https://github.com/stackblitz/bolt.new/issues/124 to get notified when we've resolved this issue.
