### ISSUE TITLE
DEPLOY NOT WORKING

### ISSUE THREAD

**Issue by Joinclicki** [stackblitz/bolt.new#394]
### Describe the bug

DEPLOY NOT WORKING

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rgyz9c

### Steps to reproduce

DEPLOY NOT WORKING

### Expected behavior

DEPLOY NOT WORKING

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79070066,
  "usedJSHeapSize": 73887734,
  "jsHeapSizeLimit": 4294705152
}
Username = Joinclicki
Chat ID = 6667a04259f7
```

### Additional context

DEPLOY NOT WORKING

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/46
