### ISSUE TITLE
Rip off service

### ISSUE THREAD

**Issue by mbpfws** [stackblitz/bolt.new#396]
### Describe the bug

Many times the bot say it has done it has not, the thing is token runs and you want to break my wallet

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vziljz

### Steps to reproduce

mplement the actual functionality for generating topics, outlines, and vocabulary
Add more detailed analysis results and visualizations
Implement the chat functionality for discussing topics and essays
Add user profile and progress tracking features
Implement the leaderboard and community features
These additional features would require backend support and more complex state management, which is beyond the scope of a single component. However, this updated version should provide a solid foundation for the IELTS Writing Toolbox.

2 menu not collapsable, should you have header menu too, where is the dashboard tab. Please make sense of your design, you waste my token doing nothing. Such a rip off. You made a side bar which the third level can not clickable at all

### Expected behavior

have things done as it says it has

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 69610067,
  "usedJSHeapSize": 51524815,
  "jsHeapSizeLimit": 4294705152
}
Username = elecosys
Chat ID = 3a154815ea40
```

**Comment by carloslfu** [comment]
@mbpfws, please contact me via any channel—maybe email. I couldn't find you, and your code has a critical issue.

**Comment by mbpfws** [comment]
ok the bot before the recovery feature got me nowhere I have created pretty
much of UIs and some backend APIs then they got swept away instantaneously
couple of times that to a point I used up my 10 mil on first account I
registered for second one at ***@***.*** which I spent another
top-up I burned my 20M account in just few hours resulting in nothing but
15 .tsx files deleted with no return.

[image: image.png]

**Comment by carloslfu** [comment]
Hey @mbpfws! I meant to reach out via DM, but I couldn't, and I might not have been clear in the last message. So here is the issue: **You accidentally leaked your OpenAI API key** here: https://bolt.new/~/sb1-vziljz. I checked and it is valid. I suggest you invalidate it asap! ⚠️

**Comment by kc0tlh** [comment]
@mbpfws Apologies that you have not found value with the service. Please reach out to hello@stacklets.com, and we'll be happy to issue a refund if we have not already done so!
