### ISSUE TITLE
I am not able to see any preview no matter what i tell it to do

### ISSUE THREAD

**Issue by 2010kaggarwal** [stackblitz/bolt.new#3963]
### Describe the bug

I am not able to see a preview

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2qab4s9h

### Steps to reproduce

I did some random testing and cannot see any prewiew

### Expected behavior

To show a prewiew

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 130389041,
  "usedJSHeapSize": 99923297,
  "jsHeapSizeLimit": 2197815296
}
Username = 2010kaggarwal
Chat ID = 2cb529ddc544
```

**Comment by endocytosis** [comment]
We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
