### ISSUE TITLE
Won't deploy to Netlify 

### ISSUE THREAD

**Issue by dheselton** [stackblitz/bolt.new#400]
### Describe the bug

error is "Something went wrong whilst creating your site on Netlify." unknown what the issue is

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sakrdn

### Steps to reproduce

However, since this is the first time we're deploying this project, there are a few things to note:

The deployment will create a new site on Netlify.
You'll receive a unique claim URL that allows you to take ownership of the deployed site.
The site will be given a random subdomain on netlify.app initially.

### Expected behavior

However, since this is the first time we're deploying this project, there are a few things to note:

The deployment will create a new site on Netlify.
You'll receive a unique claim URL that allows you to take ownership of the deployed site.
The site will be given a random subdomain on netlify.app initially.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116786459,
  "usedJSHeapSize": 108104087,
  "jsHeapSizeLimit": 4294705152
}
Username = dheselton
Chat ID = 545457fc6299
```

### Additional context

Error:
```
Something went wrong whilst creating your site on Netlify.
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
