### ISSUE TITLE
Deploy to netlify is not working

### ISSUE THREAD

**Issue by bhctest123** [stackblitz/bolt.new#402]
### Describe the bug

Let's start the deployment process.

Deploy Quiz

netlify
I've initiated the deployment process for your Assessment Quiz application to Netlify. The build command npm run build will create a production-ready version of your app, and the output will be in the dist directory.

Now, we'll wait until the site is live. I'll retrieve the deployment status and provide you with the necessary information.

### Steps to reproduce

try and click the deploy button and deploy it

### Expected behavior

I expected it to work and deploy

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62348808,
  "usedJSHeapSize": 51026208,
  "jsHeapSizeLimit": 4294705152
}
Username = bhctest123
Chat ID = 52ffd9dddbec
```

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
