### ISSUE TITLE
Messages failing - Already used a million tokens somehow

### ISSUE THREAD

**Issue by jacobnorgord** [stackblitz/bolt.new#403]
### Describe the bug

My first few projects went very smoothly, but I just purchased more tokens and am having message requests fail multiple times, nearly everytime I send a message which is appearing to use lots of my tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vf1trt

### Steps to reproduce

Send a message. It could be because there are multiple images attached possibly? Not sure why this wasn't happening before but is now.

### Expected behavior

I expect messages to be sent successfully at least almost every time.

### Screen Recording / Screenshot

<img width="472" alt="Screenshot 2024-10-10 at 3 52 31 PM" src="https://github.com/user-attachments/assets/69a6a25d-fb53-40ee-a19f-eb823fea7b67">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103655156,
  "usedJSHeapSize": 96074720,
  "jsHeapSizeLimit": 2172649472
}
Username = jacobnorgord
Chat ID = 847708b497b1
```

**Comment by kc0tlh** [comment]
@jacobnorgord this issue should be resolved. Please let me know if you are still experiencing it!
