### ISSUE TITLE
no deploy

### ISSUE THREAD

**Issue by ardakaano** [stackblitz/bolt.new#406]
### Describe the bug

no deploy also says ;There was an error processing your request

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3u1rs7

### Steps to reproduce

you can already see

### Expected behavior

-

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78780669,
  "usedJSHeapSize": 72167425,
  "jsHeapSizeLimit": 2172649472
}
Username = ardakaano
Chat ID = 055169cbfd31
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by samdenty** [comment]
we'll track this in https://github.com/stackblitz/bolt.new/issues/46
