### ISSUE TITLE
REVERT Function

### ISSUE THREAD

**Issue by btray77** [stackblitz/bolt.new#409]
**Is your feature request related to a problem? Please describe:**
Needs a revert function.  It sometimes deletes features out of nowhere.  

**Describe the solution you'd like:**
Go back before the last prompt was run.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by samdenty** [comment]
Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!
