### ISSUE TITLE
app never deploys to netlify

### ISSUE THREAD

**Issue by jvermilllion** [stackblitz/bolt.new#41]
### Describe the bug

after three attempts, bolt never deploys to netlify. Just sits and spins. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qisdgq

### Steps to reproduce

set your app, then click deploy

### Expected behavior

to deploy and then ask for netlify creds

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 124337838,
  "usedJSHeapSize": 109787690,
  "jsHeapSizeLimit": 4294705152
}
Username = jvermilllion
Chat ID = 7e880d33c4a5
```

### Additional context

help

**Comment by Nemikolh** [comment]
Hey @jvermilllion! Sorry you ran into this issue!

We have pushed a couple of fixes regarding deployment, is it still an issue you're running into?

**Comment by samdenty** [comment]
we're aware of this issue it's due to netlify rate limiting us we're trying to resolve the issue. Closing this issue in favour of tracking at https://github.com/stackblitz/bolt.new/issues/365 instead.
