### ISSUE TITLE
Error when connecting 

### ISSUE THREAD

**Issue by adoin** [stackblitz/bolt.new#410]
### Describe the bug

It looks like we're having trouble connecting due to the location of the server you're connected to. If this is in error, can you try switching your VPN location?

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nuxt-afylxb

### Steps to reproduce

First Prompt

### Expected behavior

Can get something

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86433307,
  "usedJSHeapSize": 83758675,
  "jsHeapSizeLimit": 4294705152
}
Username = adoin
Chat ID = c6544700b23d
```

**Comment by samdenty** [comment]
we'll track it in https://github.com/stackblitz/bolt.new/issues/77

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
