### ISSUE TITLE
Lost my projects

### ISSUE THREAD

**Issue by jbratton45** [stackblitz/bolt.new#411]
### Describe the bug

I was working on a project and used 10 million tokens and during the development I started getting error message then i logged out and logged back in and my projects are gone. PLEASE Advise money and time wasted 

### Link to the Bolt URL that caused the error

URL missing

### Steps to reproduce

Log into my account no projects are available

### Expected behavior

My Projects are now missing from my profile

### Screen Recording / Screenshot

No screenshot

### Platform

macos
Chrome

**Comment by wu0407** [comment]
The chat history is lost after the token exhausts.

**Comment by jbratton45** [comment]
I have 10 millions tokens left. tokens not exhausted

**Comment by kc0tlh** [comment]
@jbratton45 info on how to open old chats can be [found here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671 ) along with our progress on implementing chat persistence in #39
