### ISSUE TITLE
TOKEN PROBLEM

### ISSUE THREAD

**Issue by captisia** [stackblitz/bolt.new#412]
### Describe the bug

I purchased tokens, but they are not showing in my account to use them. Support doesn't respond to fix the issue.

### Link to the Bolt URL that caused the error

https://checkout.stripe.com/c/pay/cs_live_a1wpGBGsAaoAfkONfyP7XEkxM0oCsvNVBdXuLpg5lBtznTbO84ovURyGBc#fidkdWxOYHwnPyd1blppbHNgWnR%2FXV1zUUI1UVBKU25RX0lSdkB0Mkp0aDU1N3xkV3VJQk0nKSdjd2poVmB3c2B3Jz9xd3BgKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSdga2RnaWBVaWRmYG1qaWFgd3YnP3F3cGB4JSUl

### Steps to reproduce

i don't know

### Expected behavior

i want just to use tokens to complete my project.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@captisia please reach out to hello@stackblitz.com and we will get this sorted out for you (if we haven't already). Please send a screenshot of your Settings > Tokens pane.
