### ISSUE TITLE
problemas con correcion de errores 

### ISSUE THREAD

**Issue by daniel17gg** [stackblitz/bolt.new#413]
### Describe the bug

le pedi que me creara un dashboard y al crearlo no mostraba nada la pantalla se quedaba en blanco le dije que corregira el error si existia uno ya que no visualizaba la pagina y me sale un error tras otro error y ya gaste muchos tokens y no ha podido solucionar el problema reinicie la pagina le di al boton open with stackbliz esperando que se solucionara por si era un bug , regrese a la pagina de bolt y no se soluciona

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sphhjq

### Steps to reproduce

https://github.com/user-attachments/assets/525228f4-821d-45cf-9603-36bc0ad2e08e

### Expected behavior

poder visualizar un dashboard creado con angular 

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/b0a075fb-c1fd-461c-b45a-740fe37fc9f9

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45286191,
  "usedJSHeapSize": 42947531,
  "jsHeapSizeLimit": 4294705152
}
Username = Sancarlos
Chat ID = e90ca976a648
```

**Comment by kc0tlh** [comment]
@daniel17gg apologies for any frustration during this beta period!

Tips for token usage efficiency (and our efforts to automate some of this) are tracked in #678.
