### ISSUE TITLE
Cannot get deployed url

### ISSUE THREAD

**Issue by mangollc** [stackblitz/bolt.new#4179]
### Describe the bug

I've initiated the deployment process. Let me check the deployment status for you...

**Your site has been successfully deployed! You can view it at: undefined.**

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-dqnongkj

### Steps to reproduce

just deployed

### Expected behavior

to provide netlify url for deployed project

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/79cf5954-a098-4b99-b6cb-58e52148f266)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 104912827,
  "usedJSHeapSize": 88520999,
  "jsHeapSizeLimit": 4294705152
}
Username = mangollc
Chat ID = 5c5ec35b8369
```

### Additional context

.

**Comment by AriPerkkio** [comment]
This issue is now fixed. 
- https://github.com/stackblitz/bolt.new/issues/3948
