### ISSUE TITLE
Facing the forbidden error again and historical chat is lost together with it

### ISSUE THREAD

**Issue by nheelam** [stackblitz/bolt.new#418]
### Describe the bug

Facing the forbidden error again and historical chat is lost together with it. Even if I change my VPN, I cannot access my historical chat

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Go to bolt.new
2. Sign in

### Expected behavior

To work

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
#39 has tips on loading past chats
