### ISSUE TITLE
Code is left out on revisions

### ISSUE THREAD

**Issue by davidmoshal** [stackblitz/bolt.new#419]
<img width="480" alt="Screenshot 2024-10-11 at 1 25 59 AM" src="https://github.com/user-attachments/assets/05afa22e-d048-48ee-b1cd-28573fca0048">
<img width="540" alt="Screenshot 2024-10-11 at 1 26 11 AM" src="https://github.com/user-attachments/assets/aef01471-59cb-459f-9deb-53b46fa8d6f6">

### Describe the bug

Bolt seems to like omitting code when it revises it, putting instead placeholders where there used to be code.

Curiously, even if you ask it to repeat this phrase at the start of every response it still deletes code, despite responding with this phrase:

> The most important rule of this project is: "Be cautious when modifying existing code to avoid accidentally removing important functionality.

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-aqjopq

### Steps to reproduce

Happens all the time, no specific steps required.

### Expected behavior

Bolt should not replace code with placeholder comments

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
Appreciate your patience during this beta period as we work to improve the platform! This issue, some powerful temporary workarounds, and it's resolution is being tracked in issue #24
