### ISSUE TITLE
Idiot IA

### ISSUE THREAD

**Issue by PedroMarqzol** [stackblitz/bolt.new#424]
### Describe the bug

The AI ​​is just stupid. When I ask for changes as simple as changing the color of some texts, it doesn't do it and starts eliminating things that were already done previously and that have nothing to do with what I'm asking.

For example: I have some categories in a top menu and I want the text to be white. Well, instead, it keeps the color it had and eliminates the translations of those texts.

The Bolt tool is fine, but the AI ​​is just stupid, I waste more time correcting the mistakes the AI ​​makes than trying new ideas.

At the moment totally useless. I had paid a month to test it properly, but it is not worth it at the moment, it has to improve much more to be useful for developers.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1a3a8w

### Steps to reproduce

The AI ​​is just stupid. When I ask for changes as simple as changing the color of some texts, it doesn't do it and starts eliminating things that were already done previously and that have nothing to do with what I'm asking.

For example: I have some categories in a top menu and I want the text to be white. Well, instead, it keeps the color it had and eliminates the translations of those texts.

The Bolt tool is fine, but the AI ​​is just stupid, I waste more time correcting the mistakes the AI ​​makes than trying new ideas.

At the moment totally useless. I had paid a month to test it properly, but it is not worth it at the moment, it has to improve much more to be useful for developers.

### Expected behavior

The AI ​​is just stupid. When I ask for changes as simple as changing the color of some texts, it doesn't do it and starts eliminating things that were already done previously and that have nothing to do with what I'm asking.

For example: I have some categories in a top menu and I want the text to be white. Well, instead, it keeps the color it had and eliminates the translations of those texts.

The Bolt tool is fine, but the AI ​​is just stupid, I waste more time correcting the mistakes the AI ​​makes than trying new ideas.

At the moment totally useless. I had paid a month to test it properly, but it is not worth it at the moment, it has to improve much more to be useful for developers.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78876063,
  "usedJSHeapSize": 71203515,
  "jsHeapSizeLimit": 4294705152
}
Username = PedroMarqzol
Chat ID = f1b482d69450
```

**Comment by mbpfws** [comment]
true! it has been told to do advanced stuff but stupid enough not to change simple things. He enjoys delete components and expend ridiculous number of tokens to bring the project of few days to the very beginning. Cost me 3 times of top up without creating an app. What's more, he likes to create hierarchical of same folders and get lost on them.

**Comment by mbpfws** [comment]
At least the V0 created multiple versions that we can always come back. This one is a no return point once it decides to trash your whole project

**Comment by kc0tlh** [comment]
@mbpfws @PedroMarqzol tips for token usage efficiency (and our efforts to automate some of this) are tracked in #678. One that seems particularly relevant for both of you is the [Rollback feature](https://x.com/stackblitz/status/1844839379270836266)

If you are unhappy with the product, feel free to request a refund via hello@stackblitz.com
