### ISSUE TITLE
replacing code with "  // ... existing code ..."

### ISSUE THREAD

**Issue by romainboyer** [stackblitz/bolt.new#4252]
### Describe the bug

The solution is great, but I lose so much time each time there is some updates replacing content and adding lines like "  // ... existing code ..."
or
"// ... rest of the code"

It should be able to do the difference between writing code and giving feedback.

Best wishes to get that fixed and best wished of success for your solution

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-a5fbnthh

### Steps to reproduce

random error. Sometimes it just cut a part of the code.
maybe because at a time, I told it not to give me the code but to write it in the code.

### Expected behavior

obvious

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60584675,
  "usedJSHeapSize": 55519523,
  "jsHeapSizeLimit": 4294705152
}
Username = romainboyer
Chat ID = dbd728b95c9e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/2862).
