### ISSUE TITLE
How to use bolt locallay with the code form the local folder

### ISSUE THREAD

**Issue by itsparser** [stackblitz/bolt.new#426]
### Describe the bug

How to use bolt locallay with the code form the local folder

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/astro-simple-blog

### Steps to reproduce

How to use bolt locallay with the code form the local folder

### Expected behavior

need to pass the project folder in env 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
We are a browser based tool, and not currently exploring this feature
