### ISSUE TITLE
Nothing is rendering in the preview. 

### ISSUE THREAD

**Issue by brendengreenwood** [stackblitz/bolt.new#4261]
### Describe the bug

consistently having an issue where nothing is rendered in the preview. when i deploy to netlify the app does render as expected. i keep having this issue with new projects. im wasting my tokens telling it to fix it but nothing changes. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7kub5g6y

### Steps to reproduce

just open the project. 

### Expected behavior

expect the preview to render the app. it doesnt. 

### Platform

```
Browser name = Firefox
Full version = 133.0
Major version = 133
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
performance.memory = undefined
Username = brendengreenwood
Chat ID = 704df5e5d063
```

**Comment by endocytosis** [comment]
Hi, 

Bolt has limited support for Safari and Firefox, as described here: #2796. Using Chrome or a Chromium browsers should resolve this issue.
