### ISSUE TITLE
I get one part of the app how I want it and move to the next part and everything changes

### ISSUE THREAD

**Issue by snookyred66** [stackblitz/bolt.new#4262]
### Describe the bug

I get one part of the app how I want it and move to the next part and everything changes. I try to undo and go back to restore the point and try again and I can't get it back and just burns my tokens up trying to fix error after error. What can I do to fix this isuue and can I get my tokens back that were mainly spent on fixing errors?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dpnnapzx

### Steps to reproduce

if you look at my chat you can see the struggle

### Expected behavior

expected to continue building other parts of my application without unwanted changes happening to the part that was already complete and how I wanted it.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 121211268,
  "usedJSHeapSize": 114745624,
  "jsHeapSizeLimit": 4294705152
}
Username = snookyred66
Chat ID = 45701c1edc97
```

### Additional context

This is my first time trying to build an app and also with no code. however I have built websites since 2009 and I'm familiar with html code but not the newer languages. Please let me know what I should do. I've watched many tutorials, yt videos, etc... and I dont see any of these things happening when they use the program. Thank you and looking forward to resolving my issue and continue to learn and build

**Comment by endocytosis** [comment]
Hi, 

The [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively. If you right-click a file(s) in the code editor and select "Lock file", this will prevent the AI from make further changes to that file(s). Additionally, enabling diff base file editing (currently available as a feature preview, go to Settings > Feature Previews > toggle Diffs to on) can significantly reduce token consumption.
