### ISSUE TITLE
Duplicative work, doubling token usage

### ISSUE THREAD

**Issue by Drenchkat** [stackblitz/bolt.new#4269]
### Describe the bug

Good evening team,

I spent most of the day working in bolt developing my unique project and for some reason it reverted back to an instance that I used last night. There was a lot of work done today and its burning all my tokens that I paid for. Can you please investigate this and possible revert the history back to approximately 2030EST? We finally were making some serious progress :( Thanks in advance!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bgupfkeo

### Steps to reproduce

When using the opened bolt window to develop it forgot all the work we had accomplished and reverts back to an earlier instance. 

### Expected behavior

Pick up where I left off. I simply went to my settings tab to see how many tokens I had left. 

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108799784,
  "usedJSHeapSize": 106182680,
  "jsHeapSizeLimit": 4294705152
}
Username = Drenchkat
Chat ID = ff16ef5e5b14
```

**Comment by Drenchkat** [comment]
Hey Brian,

Sorry for the delay and thank you for the help. Unfortunately I was unable
to find my previous instance. I am going to start all over again because
there was a good bit of work that I put into it and a lot of tokens. I will
try this again and hopefully it will stay. Thanks again.

-Mike

**Comment by endocytosis** [comment]
Sorry to hear this! We expect these persistence issues to decrease as database improvements are made - don't hesitate to reach out with any other questions.
