### ISSUE TITLE
Fixing problems uses tokens

### ISSUE THREAD

**Issue by jacwilmar** [stackblitz/bolt.new#4286]
### Describe the bug

The resulting code contained non-logic errors, meaning they were introduced by the generator and not caused by the instructions. Fixing these problems consumed my credits for the day, but this is incorrect. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cf2zbb6c

### Steps to reproduce

1. Enter instructions
2. Wait for code generation
3. Code generator identified a problem
4. Opt to fix the problem

### Expected behavior

I should only use my credits for bugs I cause.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72151699,
  "usedJSHeapSize": 64347495,
  "jsHeapSizeLimit": 4294705152
}
Username = jacwilmar
Chat ID = c98fd96bde6b
```

**Comment by endocytosis** [comment]
Hi all, 

Please reach out to hello@stackblitz.com so we can assist you further. In instances where the AI model is repeatedly unable to solve a problem, manual intervention is required. We recommend researching the issue outside of Bolt to preserve tokens. I am happy to look into the issues you are experiencing further over email. Thank you.

**Comment by jacwilmar** [comment]
I recommend that you alter the UI / UX to make it clear that when a
problem is found that opting to automatically attempt to correct it may not
work, will result in token consumption, and that there is an option to
manually fix it. As it stands today, the UI leads the user to believe that
the problem can be atomically fixed, it does not make it clear that it will
consume tokens, or that there are options to manually fix the problem.
