### ISSUE TITLE
Bug fixing infinite loop - feedback

### ISSUE THREAD

**Issue by paulgosnell** [stackblitz/bolt.new#429]
### Describe the bug

We are repeating fixes. Each time we fix one bug, we undo it from a previously fixed bug, so it's taking twice as long and sometimes not fixing at all, just unfixing and fixing the same bugs. 

Is there a way to not revert and undo or overwrite code that's working and fixed?

### Link to the Bolt URL that caused the error

https://bolt.new/~/chilledcrm

### Steps to reproduce

general back and forth bug fixing 

### Expected behavior

Not to unfix previously fixed bugs

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 151891577,
  "usedJSHeapSize": 132372253,
  "jsHeapSizeLimit": 2172649472
}
Username = paulgosnell
Chat ID = ed6ce9e3ed83
```

**Comment by kc0tlh** [comment]
Checkout the best practices for token efficiency and bug resolution on #678
