### ISSUE TITLE
npm run dev npm ERR! Missing script: "dev"

### ISSUE THREAD

**Issue by YDX64** [stackblitz/bolt.new#432]
### Describe the bug

❯ npm run dev
npm ERR! Missing script: "dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-11T12_28_53_367Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-jdu7s7

### Steps to reproduce

❯ npm run dev
npm ERR! Missing script: "dev"

### Expected behavior

worked

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = YDX64
Chat ID = 4b4e05212aff
```

**Comment by kc0tlh** [comment]
@YDX64 this is because there is no dev script in your package.json. Please switch to Chrome as Safari is not completely supported (see #2796).
