### ISSUE TITLE
Can you add a version control that it will be easy to revert the code its corruption the code and i cant go back

### ISSUE THREAD

**Issue by Matan693** [stackblitz/bolt.new#433]
### Describe the bug

I am asking for a simple change for the dialog popup and it change everything and remove almost all the data in another modal that now i cant bring it to how it was before

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-phwrca

### Steps to reproduce

just ask for simple thing from component that attached to each other and see how it change all the files regardless if its needed

### Expected behavior

to change only the things needed and maybe ask before if i approve the change, kind of PR once i finish with the Code review ill merge the two

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 98904307,
  "usedJSHeapSize": 92190163,
  "jsHeapSizeLimit": 4294705152
}
Username = Matan693
Chat ID = 26f70581260f
```

**Comment by patiljignesh** [comment]
Second this feature.

**Comment by kc0tlh** [comment]
@Matan693 done: https://x.com/stackblitz/status/1844839379270836266
