### ISSUE TITLE
Prompts ain't working but tokens still decrease

### ISSUE THREAD

**Issue by rory73** [stackblitz/bolt.new#4341]
### Describe the bug

Hi, I am building a website with bolt. I makes great job but at one point prompts has no effect like bold made it so complicated and dependant in the code that what I ask for is not possible for it to make. It's ok with step 1 creating pages but at one point when I wand to add some new element bold modify the code and the result is nothing or it's ok for what I asked but the whole display style is lost. It is the same in header, footer, anywhere. I asked it for a simple html/css with less dependencies but it's bug over bug and the tokens still decrease but it should not when the operation is unsuccessful. Like my last 50 or 80 prompts were about 5-6 tries for the same operation, then didn't wokrked, then rollback, then etc etc.. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yalxvfwo

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Made so many rollbacks but see the description tx

### Expected behavior

simple add of a logo, an icon in footer, a stock info in product page

### Screen Recording / Screenshot

![Capture d'écran 2024-12-17 171730](https://github.com/user-attachments/assets/a76ba02c-a9d3-4e25-8363-64d5acf07f3a)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86251430,
  "usedJSHeapSize": 82959398,
  "jsHeapSizeLimit": 2080636928
}
Username = ceopdc
Chat ID = 00d39cba8606
```

**Comment by glasiore** [comment]
I have a simillar problem at the moment. I can't update the things I added yesterday but I can add new stuff.

**Comment by salzstar** [comment]
It's a massive bug right now and it seems loads of people including myself are experiencing this issue!

**Comment by glasiore** [comment]
It keeps spending my tokens and I've already spent most of it but still couldn't even get anything I wanted... I dk if they will return my tokens or at least fix this issue so we can move on our projects.

**Comment by glasiore** [comment]
It seems that Bolt needs help recognizing your code. To address this, you can take a portion of the code and request a small change, such as modifying a color. If Bolt initially struggles to implement the change, retry the process until it succeeds. Once the change is made, you can proceed to add other modifications as needed. This may not be a definitive solution, but it worked for me.

**Comment by rory73** [comment]
Ok well tx. My side I learned and want to share that : at the beginning of a blank project you better feed bolt with a maximum elaborate specification sheet and dev rules like this (foud it from a youtuber) : 

IMPORTANT: Development Rules
1. Start with configuration files
2. Then develop components
3. Create ALL necessary folders in src/
4. Create an empty file for EACH component mentioned
5. Do NOT start coding components before creating all files
6. Never import a component that has not been created yet
7. Always use the .tsx extension for React files
8. Create routes only after having all components working.

Restarted by zero and till now is it way more stable.
Good luck
