### ISSUE TITLE
Refund after 

### ISSUE THREAD

**Issue by roytmanpiccoli** [stackblitz/bolt.new#4349]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by codewithtyler** [comment]
Hi @roytmanpiccoli in order to request a refund I suggest you send an email to support@stackblitz.com using the same email address that' associated with your Bolt account.

**Comment by AriPerkkio** [comment]
Billing related issues should be done via email, as @codewithtyler mentioned. See https://github.com/stackblitz/bolt.new/issues/new/choose for instructions.
