### ISSUE TITLE
Code deletion when LLM not return the full code for the file

### ISSUE THREAD

**Issue by merlinvn** [stackblitz/bolt.new#436]
### Describe the bug

When the file become large, LLM tend to simplify and return the part that need to be edit in the file. But Bolt simply replace the whole file instead of edit part by part, which lead to code deletion.

This could be improve by breaking down the file into multiple small files or let the llm know that it have to return full text for the file.

### Link to the Bolt URL that caused the error

I deleted it. Sorrrry.

### Steps to reproduce

When the file have large number of lines

### Expected behavior

Edit part by part instead of replace the whole file

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
Appreciate your patience during this beta period as we work to improve the platform! This issue, some powerful temporary workarounds, and it's resolution is being tracked in issue #24
