### ISSUE TITLE
"Anthropic rate limit exceeded, please wait a bit and try again."

### ISSUE THREAD

**Issue by mmkontis** [stackblitz/bolt.new#440]
### Describe the bug

Anthropic rate limit exceeded, please wait a bit and try again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gytzcf

### Steps to reproduce

Anthropic rate limit exceeded, please wait a bit and try again.

### Expected behavior

Anthropic rate limit exceeded, please wait a bit and try again.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 177553520,
  "usedJSHeapSize": 156885336,
  "jsHeapSizeLimit": 2172649472
}
Username = mmkontis
Chat ID = 7078dd3e50bc
```

**Comment by samdenty** [comment]
sorry you ran into this, we've asked antrohpic to increase our tokens per minute so hopefully you won't see it again.

Thanks for reporting this as others on the team were noticing slowdowns but were unsure why 🙏

**Comment by uerzer** [comment]
Sir do you have a Giant pile of cash to burn, how?

**Comment by mattches** [comment]
Hey Bolt team this has happened again! Please update your limits with Anthropic!
Anthropic rate limit exceeded, please wait a bit and try again.

**Comment by reverard** [comment]
it just happened to me

**Comment by helpisdev** [comment]
it just happened to me also

**Comment by jmestrallet** [comment]
Me pasa lo mismo lol

**Comment by gumizolex** [comment]
also here

**Comment by paramveersinghxd** [comment]
same here lol

**Comment by skyni1** [comment]
me too

**Comment by devJ1776** [comment]
same. in the middle of development...

**Comment by posh-ampa** [comment]
how long it takes to reset? so tha twe can restart work ?

**Comment by cebrailk1** [comment]
same here getting this alot atm

**Comment by devJ1776** [comment]
Reloading my Bolt.new page seamed to help

**Comment by therazaimran** [comment]
Same here, when to expect this issue to be fixed?

**Comment by Redmail1122** [comment]
same I can't get anything done

**Comment by Budatron** [comment]
Well, seen all the messages I guess is overloaded. Trafic time.

**Comment by mahyarh** [comment]
I cannot do anything since last night.

**Comment by thrivehub22** [comment]
Same here fml

![Image](https://github.com/user-attachments/assets/7adece12-b72e-455a-85d7-df9989cff655)

**Comment by anandkanishkZ** [comment]
Anthropic rate limit exceeded, please wait a bit and try again. I am facing this problem too, why ???

**Comment by akcankadir** [comment]
We've hit a rate limit with Anthropic. Please switch to the 'default' model, another model, or try again in a few moments.

**Comment by Gotoogle** [comment]
me too - very frustrating plus Bolt tries to design my apps rather than follow my instructions just hate when AI thinks it knows it all, an insult to those of us who do :-)

**Comment by linazdexter** [comment]
Me too same issue is causing extreme trouble now. My [project](https://sngplonlinebill.com.pk) Got down as well.

**Comment by jesuscurreri** [comment]
same error "Failed after 3 attempts. Last error: This request would exceed the rate limit for your organization (xxxxx) of 1,000,000 input tokens per minute. For details, refer to: https://docs.anthropic.com/en/api/rate-limits. You can see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.

**Comment by voyanceleadership** [comment]
I'm having this issue as well - I wasn't sure if it was because my project has gotten quite large, or if it's due to overall usage of Bolt (i.e. too many people using it) overwhelming the rate limit.

Failed after 3 attempts. Last error: This request would exceed the rate limit for your organization (a22cf6e6-a940-4fff-8c4c-1580816ac7be) of 1,000,000 input tokens per minute. For details, refer to: https://docs.anthropic.com/en/api/rate-limits. You can see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.

**Comment by NFTim-og** [comment]
It might be because many people are using the service from Bolt, I'm having exactly the same issue and the organization id is exactly the same.
