### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Shirokani1** [stackblitz/bolt.new#4402]
### Describe the bug

Description of the problem
When I try to fix an issue on Bolt (related to image sizes), the tool generates hundreds of lines of unnecessary edits that quickly eat up my credits. I went back to restore the previous state, but now I have a blocking error message (see screenshot).

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dfwedhjq

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Steps to reproduce the issue
I tried to resize images via Bolt.
Since it wasn't working properly, I used the rollback option.
Since then, with each new repair attempt, the following error appears:

[plugin:vite:css] [postcss] ENOENT: no such file or directory, open 
'/home/project/src/components/accessories/installed/InstalledAccessories.ts'

### Expected behavior

Expected result
I just wanted Bolt to resize my images correctly or allow me to return to a steady state.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/5ab77de5-8a2a-4c81-b7f8-52d89bdb731d)

![Capture d’écran 2024-12-18 214135](https://github.com/user-attachments/assets/9432f57d-306d-4336-a65e-f18585cf1877)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106088927,
  "usedJSHeapSize": 67710631,
  "jsHeapSizeLimit": 4294705152
}
Username = Shirokani1
Chat ID = 2558cd09e7d6
```

### Additional context

**Current result**
The error blocks my project (see screenshot).
Any further attempts to fix this bug generate hundreds of lines and use up my credits unnecessarily.
Additional information
Browser: Chrome 131.0.0.0
System: Windows 10
Project link: bolt.new
Please correct this issue quickly, as I can no longer work in this state and my credits are running out with no useful results.

**Comment by ClientricDev** [comment]
@Shirokani1 Did you get this fixed? I'm still facing this issue with no support helping. I'm not sure what the issue is and it's incredibly frustrating!
