### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by neo-frame** [stackblitz/bolt.new#4438]
### Describe the bug

i tried to log into my bolt and it doesnt let me. 
When trying to sign in there comes a pop up on the bottom right saying "Unable to log in".
Did i get banned or something?

### Link to the Bolt URL that caused the error

https://bolt.new/

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

try to sign in with my user.

### Expected behavior

Unable to log in.

### Screen Recording / Screenshot

![screen_bolt_error](https://github.com/user-attachments/assets/0be74fed-443b-4b3d-aa9c-ab79ca6ff6f2)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

windows edge browser.

**Comment by arorapunu4** [comment]
Same issue

**Comment by Walatgavat** [comment]
same here

**Comment by Walatgavat** [comment]
i can log into sackblitz and netfly but bolt not working

**Comment by AriPerkkio** [comment]
This is now fixed.
