### ISSUE TITLE
when fixing an error 

### ISSUE THREAD

**Issue by cmBorak** [stackblitz/bolt.new#445]
### Describe the bug

when fixing an error the system reverts features further back before issue creating a repeat process, such as error with a button completely rewrites form to a previous non-working state 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-brebsr

### Steps to reproduce

have bolt change action in taskform, they taskform will be rewritten without definitions that were previously present and working

### Expected behavior

would keep definitions in taskform during rewrite

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows 11 pro chrome 

### Additional context

I'm new to no coding apps and I have wasted millions of tokens re-doing step after step, not sure how to proceed, I am not knowledgeable with coding

**Comment by kc0tlh** [comment]
@cmBorak tips for token usage efficiency (and our efforts to automate some of this) are tracked in #678
