### ISSUE TITLE
chat history missing 

### ISSUE THREAD

**Issue by jubarammm** [stackblitz/bolt.new#446]
### Describe the bug

i built a 12 hours project and in the middle of building my first laptop battery dead ..and i was  still in bolt.new , i hurry up to th eother laptop to continue building .. i logged in and i dont see my project part of the histiorty 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ftxrmw

### Steps to reproduce

check history betwen 2 laptops or 2 broswerws 

### Expected behavior

to keep saving the project in my profile chat history 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54550337,
  "usedJSHeapSize": 45404097,
  "jsHeapSizeLimit": 4294705152
}
Username = jubaramm
Chat ID = a53a109e3f4b
```

**Comment by kc0tlh** [comment]
@jubarammm info on how to open old chats can be [found here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671 ) along with our progress on implementing chat persistence in #39
