### ISSUE TITLE
I can't sign in now

### ISSUE THREAD

**Issue by XianWang-Lu** [stackblitz/bolt.new#4467]
### Describe the bug

see
![image](https://github.com/user-attachments/assets/6ff34044-d1e3-4d2e-8217-0d326c14fb4c)

### Link to the Bolt URL that caused the error

none

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

I can't sign in today.

### Expected behavior

Signed in successfully

### Screen Recording / Screenshot

none

### Platform

- OS: windows
- Browser: edge
- Version: 131.0.2903.99

### Additional context

none

**Comment by endocytosis** [comment]
A fix was just implemented for this. Are you able to login now?

**Comment by XianWang-Lu** [comment]
Yes, I am able to login now.
