### ISSUE TITLE
Upgraded to Teams but unable to use Tokens

### ISSUE THREAD

**Issue by PropertyVue** [stackblitz/bolt.new#448]
### Describe the bug

I decided to upgrade to teams from the basic plan as we are going to use Bolt moving forward. I can see that the tokens renewed, but then I am prompted to upgrade to teams for more tokens.
![image](https://github.com/user-attachments/assets/3da3ecf0-0a01-401c-ad21-0b8bdf321117)
![image](https://github.com/user-attachments/assets/b8b67fe0-b763-4bda-ba68-ddb1feea281a)

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-eq3p3h

### Steps to reproduce

1. Pay for individual plan
2. Use all tokens for the month
3. Upgrade to teams
4. See tokens reloaded
5. Unable to use tokens 

### Expected behavior

I expected to upgrade to teams and get more tokens. I thought I read it was 30M/day

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by PropertyVue** [comment]
Just to expand further, I have experienced similar issues as what I see in the laundry list. Spent tons of tokens on repeat changes or minimal revisions. Hopefully I get some more tokens since upgrading. We intend to use this product like crazy, but our hands are tied for the moment

**Comment by EricSimons** [comment]
Hi! We actually had to roll back team plans due to bugs we found ([more here](https://x.com/ericsimons40/status/1844551248265216238)) - can you email me eric@stackblitz.com? I can get you fully refunded, and for time being if you sign up on a pro plan everything will work as expected 🙇

**Comment by PropertyVue** [comment]
Hey Eric, my email is chris@propertyvue.io. 

We have emailed prior.

**Comment by nireadaddy** [comment]
I use tons of tokens to fix small bugs, please include the revision or freeze correct code not use waste token for regenerate a lot of code.

**Comment by kc0tlh** [comment]
This is being resolved directly via email support. Closing this issue.
