### ISSUE TITLE
No history of Chat for Reopened projects

### ISSUE THREAD

**Issue by verioussmith** [stackblitz/bolt.new#45]
### Describe the bug

I just upgraded to your basic plan but the browser made me refresh to continue on my project and when I refreshed there is not history of the chat I had with the assistant prior to the upgrade.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qe94au

### Steps to reproduce

1. Begin project Build
2. Interact until you run into token limit
3. Click to upgrade and add Payment
4. Refresh Project Page after Upgrade to Continue interaction
5. Observe that there is no history of interactions prior to upgrade

### Expected behavior

I would expect there to be a history of interactions prior to upgrade

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52201919,
  "usedJSHeapSize": 44298787,
  "jsHeapSizeLimit": 4294705152
}
Username = verioussmith
Chat ID = 276279447956
```

**Comment by Nemikolh** [comment]
Hey @verioussmith! So sorry you had this issue! :pray: 

We do not persist the chat history for now, but we will add support for this. You can track this in #39. I'll close this issue for now but feel free to create a new one if you ever run into any other issues :smiley:
