### ISSUE TITLE
Major waste of time and tokens

### ISSUE THREAD

**Issue by Carson1391** [stackblitz/bolt.new#455]
### Describe the bug

I spent a few hours modifying and updating and describing how I wanted my project to be and II accidentally clicked the back button and the chat didn't save and there's no knowledge of all the updates I did, and I'm sure I spent a lot of tokens doing it. I'm just hoping that either. I can get that chat back or the tokens I spent

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nkpgj8

### Steps to reproduce

Hit back button on phone by accident and couldn't get back and no chat nor project was saved or updated. Spent hours fine tuning

### Expected behavior

If you can't find my chat log then please give back the tokens I spent today. But the chat log is way more important to me then the tokens. Tia

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 37811966,
  "usedJSHeapSize": 36963766,
  "jsHeapSizeLimit": 1098907648
}
Username = Carson1391
Chat ID = 4f1c0dd17f08
```

**Comment by kc0tlh** [comment]
@Carson1391 apologies for the frustrating experience. Please feel free to reach out to hello@stackblitz.com for a refund while we continue to work thru the beta period and improve the app.
