### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by benspak** [stackblitz/bolt.new#456]
### Describe the bug

Keep running into this error. 

### Link to the Bolt URL that caused the error

asdfasdf

### Steps to reproduce

Enter prompt. 

### Expected behavior

Fully completion of project.

### Screen Recording / Screenshot

https://www.youtube.com/watch?v=vjIxBcWGu4k

### Platform

```
Browser name = Chrome
```

**Comment by candidreloaded** [comment]
This issue seems to be happening a lot lately.

**Comment by kc0tlh** [comment]
Tracking this in #1073
