### ISSUE TITLE
Disappear previous chat 

### ISSUE THREAD

**Issue by nathaliely** [stackblitz/bolt.new#457]
### Describe the bug

Hi i spend almost all my Token you build 2 projects and it's disappeared from the chat, I'm a paid user from the previous price when i try to import a new project cause i would have to rebuilt it, it told me that 
<img width="523" alt="Capture d’écran 2024-10-12 à 00 05 09" src="https://github.com/user-attachments/assets/bf040c74-ae51-403a-9af2-09d80ac64768">
Ok to paid but in bolt when i click "my subscription "i got this without any price 
<img width="1319" alt="Capture d’écran 2024-10-12 à 06 38 36" src="https://github.com/user-attachments/assets/8faad6c6-93d8-44a4-991d-91ece5faebcb">
I'm very frustrating i took a lot of time to build my previous project , i hope you can help

### Link to the Bolt URL that caused the error

https://bolt.new/?showPricing=true

### Steps to reproduce

<img width="342" alt="Capture d’écran 2024-10-12 à 06 42 15" src="https://github.com/user-attachments/assets/fc0925c5-0688-4b6f-8787-312f335c3f8e">

### Expected behavior

Hi i spend almost all my Token you build 2 projects and it's disappeared from the chat, I'm a paid user from the previous price when i try to import a new project cause i would have to rebuilt it, it told me that 
<img width="523" alt="Capture d’écran 2024-10-12 à 00 05 09" src="https://github.com/user-attachments/assets/bf040c74-ae51-403a-9af2-09d80ac64768">
Ok to paid but in bolt when i click "my subscription "i got this without any price 
<img width="1319" alt="Capture d’écran 2024-10-12 à 06 38 36" src="https://github.com/user-attachments/assets/8faad6c6-93d8-44a4-991d-91ece5faebcb">
I'm very frustrating i took a lot of time to build my previous project , i hope you can help

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by DIegolitoMatador1984** [comment]
Im facing the same issue !!!!!!

**Comment by DIegolitoMatador1984** [comment]
I worked like a full day and today I open it and nothing in the chats!!

**Comment by dumieu** [comment]
WHat a scam. I've spent days working on projects and they were deleted. What a complete waste of time and money this is.

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
