### ISSUE TITLE
Build doesn't complete

### ISSUE THREAD

**Issue by samora254** [stackblitz/bolt.new#46]
### Describe the bug

UNABLE TO BUILD THE APP READY FOR DEPLOYMENT
![image](https://github.com/user-attachments/assets/bf19c99b-f2d7-457a-b967-926842e6b063)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-x74kxp

### Steps to reproduce

I ran a prompt but cant preview the output because it cannot build the app after multiple attempts

### Expected behavior

I ran a prompt but cant preview the output because it cannot build the app after multiple attempts

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/03dede76-d1b4-4c36-ab61-e9fb1accc79d)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83101248,
  "usedJSHeapSize": 73136808,
  "jsHeapSizeLimit": 4294705152
}
Username = samora254
Chat ID = f185339153fa
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by Nemikolh** [comment]
Hey @samora254! Looks like `vite` is missing from your dependency list. You can edit your `package.json` to add it and then run `npm install` to install it.

**Comment by samdenty** [comment]
i've just opened a pr to add auto-fixes for build errors encountered inside deployment build commands
