### ISSUE TITLE
deletes code

### ISSUE THREAD

**Issue by ethosperformance** [stackblitz/bolt.new#460]
### Describe the bug

instead of saving versions of the code that are totally fine, it completely overwrites code and sometimes it even comments saying "insert rest of XYZ code here" as if its not the one that just deleted it from there lol. i think if you allowed the user to select which ai model to program with like cursor allows for, this may not happen. i'm not sure which model you're running under the hood though.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ysv4jz

### Steps to reproduce

1. write so much code that you have a relatively large file of 500-700 lines
2. start programming something else
3. watch it delete the code in that large file and then because no past versions of it are saved upon each iteration, you won't be able to retrieve the code

### Expected behavior

for the ai to not touch stuff it is not asked to change

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116790468,
  "usedJSHeapSize": 111488488,
  "jsHeapSizeLimit": 4294705152
}
Username = ethosperformance
Chat ID = 7b3974c9e5f6
```

**Comment by kc0tlh** [comment]
Appreciate your patience during this beta period as we work to improve the platform! This issue, some powerful temporary workarounds, and it's resolution is being tracked in issue #24

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
