### ISSUE TITLE
get something bad

### ISSUE THREAD

**Issue by TouAllCra** [stackblitz/bolt.new#463]
### Describe the bug

![B_QM5T4L%NJDTNQHKUNZ1SP](https://github.com/user-attachments/assets/6243062e-fb09-4fc8-a8dc-23bac3f8dffc)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8azndk

### Steps to reproduce

1、copy github project url
2、built finis
3、try to built something new
4、get something bad

### Expected behavior

1、copy github project url
2、built finis
3、try to built something new
4、get something bad

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55343546,
  "usedJSHeapSize": 51879442,
  "jsHeapSizeLimit": 2172649472
}
Username = TouAllCra
Chat ID = 4368ba2398ee
```

**Comment by AriPerkkio** [comment]
Hey @TouAllCra, thanks for the report!

This issue is tracked on #2556.
