### ISSUE TITLE
Have you considered allowing users to use their own Sonnet 3.5 tokens? 

### ISSUE THREAD

**Issue by JKing-8** [stackblitz/bolt.new#468]
Have you considered allowing users to use their own Sonnet 3.5 tokens? 
Since I am a non-technical developer, I will ask more questions. I am worried that the tokens will be used up and cannot be replenished.

**Comment by samdenty** [comment]
You can do this with the self hosted version on this repo

**Comment by JKing-8** [comment]
thanks
