### ISSUE TITLE
“Create a login system with Next.js and prisma.” is not working.

### ISSUE THREAD

**Issue by matsumoto-aqua** [stackblitz/bolt.new#476]
### Describe the bug

❯ npx prisma generate && npx prisma db push && npm run dev
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/06fc58a368dc7be9fbbbe894adf8d445d208c284/debian-openssl-1.1.x/libquery_engine.so.node.sha256 failed, reason: socket hang up

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gmxqer

### Steps to reproduce

[Make a system to login with Next.js and prisma.] and play button

### Expected behavior

Create a login system with Next.js and prisma.

### Screen Recording / Screenshot

![error](https://github.com/user-attachments/assets/00caead8-5d45-421c-b7ac-ae79f25da66a)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53576985,
  "usedJSHeapSize": 50809433,
  "jsHeapSizeLimit": 4294705152
}
Username = matsumoto-aqua
Chat ID = fae120ac2a07
```

**Comment by Adele583** [comment]
yeah i am facing the same problem too

**Comment by olexdij** [comment]
me to

**Comment by ZainCheung** [comment]
me too

**Comment by yasinkocak** [comment]
Same issue here, we need openSSL on WebContainers

**Comment by arpandeep-singh** [comment]
Having same issue. Did anyone find a fix for this?

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback! A potential issue is that [Prisma does not currently compile to Wasm](https://github.com/prisma/prisma/discussions/18428), which would be necessary for compatibility with Bolt. If you are open to using another database we have instructions on using Firebase [here](https://www.youtube.com/watch?v=1GfqnOAKr9M).

**Comment by edproton** [comment]
Wasting a lot of tokens with this.
