### ISSUE TITLE
Admin creation error

### ISSUE THREAD

**Issue by akmauri** [stackblitz/bolt.new#4764]
### Describe the bug

I am attempting to add a admin user so that i can create an admin dashboard. I had bolt create an admin user, but the provided login credentials don't work. the login intially also allowed for social login with google, facebook, and apple, but when I asked for the admin the social login options disappeared.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2xjdfehj

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

1. click sign in
2. input the provided creditals
3. see error

### Expected behavior

I keep getting this error after entering the provided credentials.

1
"Sign in error:"{__isAuthError: true, name: "AuthApiError", status: 400, code: "invalid_credentials"}
1
"Login error:"{}
1
"Supabase request failed"{url: "https://xesaejpjbtbttpyqgmpo.supabase.co/auth/v1/token?grant_type=password", status: 400, body: "{"code":"invalid_credentials","message":"Invalid login credentials"}"}

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 312960036,
  "usedJSHeapSize": 294417096,
  "jsHeapSizeLimit": 4294705152
}
Username = akmauri
Chat ID = b473a3f71dfe
```

### Additional context

I have much of the project and features outlined. My first step was to upload the entire outline and work my way through it, but the chat history deleted.

**Comment by endocytosis** [comment]
Apologies for the frustration! Unfortunately, we aren't able to offer engineering support for individual projects. You can read more about continuing to develop your project here: #2310.
