### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by NEOFORME** [stackblitz/bolt.new#4772]
### Describe the bug

its showing white screen after the command was put in like the screenshot provied 
![image](https://github.com/user-attachments/assets/ea57fb7f-b081-4cbb-8306-5b15541f6882)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-div4fkaf

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

create a landing page for my gym  with the instruction give :Hero Section
Tagline:
"Transform Your Life, One Workout at a Time."

Subtext:
"At Test Subject, we provide everything you need to become the best version of yourself—fitness, focus, and a healthier future."

Call-to-Action (CTA):

"Start Your Journey Today" button (leads to a signup form or free trial).
Secondary button: "Join Now" for direct membership signup.
About Us Section
Title:
"Why Choose Test Subject?"

Text:
"Test Subject is more than just a gym—it's a community. With state-of-the-art facilities, expert trainers, and a commitment to your goals, we’re here to support you every step of the way. Whether you're looking to build strength, improve endurance, or find balance, our programs are tailored to help you succeed."

Programs Section
Title:
"Programs Designed for Every Goal"

Categories (displayed in interactive cards or icons):

Strength Training: Build muscle and power with personalized weightlifting programs.
Cardio Workouts: Boost endurance with our treadmills, bikes, and HIIT classes.
Group Classes: Yoga, Zumba, and spin sessions to keep you motivated.
Personal Training: One-on-one coaching to fast-track your fitness journey.
Recovery Zone: Access to saunas, massage therapy, and stretching zones for post-workout care.
Facilities Section
Title:
"World-Class Facilities"

Text:
"Our gym is equipped with everything you need for a superior workout experience: modern machines, free weights, spacious group training areas, and a sleek recovery lounge. At Test Subject, every detail is designed to elevate your fitness journey."

Interactive Features:

Virtual tour of the gym with a 360° view.
Images of key facilities: weight room, cardio area, group fitness studio, and recovery zone.
Testimonials Section
Title:
"What Our Members Say"

Text:
"Don’t take our word for it. Here’s what our members have to say about their transformations at Test Subject."

Interactive Carousel:

Show quotes from satisfied members, before-and-after images, and success stories.
Pricing Section
Title:
"Flexible Membership Plans"

Text:
"Choose a plan that fits your lifestyle. No long-term commitments, just results."

Examples of Pricing Plans:

Basic Plan: Access to gym facilities during standard hours.
Starting at $29/month
Premium Plan: Includes all-access facilities, group classes, and recovery zone.
Starting at $49/month
VIP Plan: Unlimited access, personal training, and exclusive perks.
Starting at $79/month
CTA Button:
"See Full Pricing"

Call-to-Action Section (CTA):
Text:
"Ready to Make a Change?"

Button Options:

"Start Your Free Trial" (leads to a 7-day free trial signup form).
"Join Now" (direct membership purchase).
Footer Section
Contact Information:
"Have questions? Contact us anytime!"

Phone: xxxxxxx
Email: testsubject@gmail.com
Location: 123 Fitness St., Wellness City
Social Links:
Add links to Instagram, Facebook, and Twitter.

Operating Hours:
"Open 24/7 for our members."

### Expected behavior

white screen after reset and allowing pop ups and everything included

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/85c38f60-1237-46d8-93ca-98758aada9b3)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 OPR/115.0.0.0
performance.memory = {
  "totalJSHeapSize": 59278810,
  "usedJSHeapSize": 56768530,
  "jsHeapSizeLimit": 4294705152
}
Username = neowakeuptryout
Chat ID = efdb9f5f0523
```

**Comment by endocytosis** [comment]
Apologies for the frustration! We are aware of this issue and are tracking it [here](https://github.com/stackblitz/bolt.new/issues/1791).
