### ISSUE TITLE
Me dice que no tengo tokens disponibles y no es así.

### ISSUE THREAD

**Issue by Jotaa-AI** [stackblitz/bolt.new#4783]
### Describe the bug

Hola, tengo la suscripción mensual del nivel PRO, y después de terminar con los 2M tokens que habéis puesto a disposición nuestra en Bolt.new ya me dice que no tengo acceso a poder escribir prompts, cuando me quedan 41.614/10.000.000 tokens disponibles. Necesito solventar este problema rápido porque tengo un proyecto que presentar a un cliente y tengo que cumplir con la fecha. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u6nkr9bh

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Comprobar los tokens usados, tienen que salir: 41.614 de 10.000.000 disponibles

### Expected behavior

Necesito que pueda acceder al editor de código con prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Apologies for the frustration! Please reach out to hello@stackblitz.com so we can assist your further.
