### ISSUE TITLE
Keeps breaking generating code

### ISSUE THREAD

**Issue by vidyuth** [stackblitz/bolt.new#479]
The code generation keeps breaking in between creation process so often, this is not good since this is only going to eat my tokens/credit available and the ones that are created are all wasted and goes against the total count of tokens available. This is so ridiculous

**Comment by kc0tlh** [comment]
@vidyuth tips for token usage efficiency (and our efforts to automate some of this) are tracked in #678

**Comment by VinayRangra** [comment]
Bolt.new occasionally deletes generated code automatically, either I think it is  due to session timeouts or bugs in the system. This issue may be related to its integration with tokenbased usage models, where interruptions or errors during generation lead to loss of progres
