### ISSUE TITLE
project is not deploying at all

### ISSUE THREAD

**Issue by SamWebDe** [stackblitz/bolt.new#480]
### Describe the bug

I can't get deploy anymore when creating this project 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v3vzww

### Steps to reproduce

I get errors now when I try to deploy my code. it has not worked for days

### Expected behavior

I always get errors now trying to deploy a project. This project

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86015221,
  "usedJSHeapSize": 70303165,
  "jsHeapSizeLimit": 4294705152
}
Username = sam610
Chat ID = 6c238405cb19
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
