### ISSUE TITLE
Ten Question 1.000.000 Token!

### ISSUE THREAD

**Issue by Akintkaya** [stackblitz/bolt.new#483]
### Describe the bug

I am repeatedly doing the same task, it says it's done, but the result doesn't change, and it takes 1,000,000 tokens for just 10 questions—this is unbelievable!! Someone please help!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dgmxjp

### Steps to reproduce

I am repeatedly doing the same task, it says it's done, but the result doesn't change, and it takes 1,000,000 tokens for just 10 questions—this is unbelievable!! Someone please help!

### Expected behavior

I am repeatedly doing the same task, it says it's done, but the result doesn't change, and it takes 1,000,000 tokens for just 10 questions—this is unbelievable!! Someone please help!

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83012978,
  "usedJSHeapSize": 75934234,
  "jsHeapSizeLimit": 4294705152
}
Username = kaya
Chat ID = cb8c6d8ce1aa
```

**Comment by kc0tlh** [comment]
@Akintkaya tips for token usage efficiency (and our efforts to automate some of this) are tracked in #678
