### ISSUE TITLE
 This message didn't complete its response.

### ISSUE THREAD

**Issue by benspak** [stackblitz/bolt.new#487]
### Describe the bug

I tell Bolt.new to "Create the backend and frontend in separate git repos for easy deployability." which might be causing it to provide too long of a response.

### Link to the Bolt URL that caused the error

asdfasdf

### Expected behavior

Expect it to be able to complete the whole task.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/05d301ae-48fa-4500-8ec7-8a13999e67a6)

### Platform

```
Browser name = Chrome
```

**Comment by kc0tlh** [comment]
Tracking in #1073
