### ISSUE TITLE
Feature Request: Ability to Update Netlify Deploys, Even After Claiming

### ISSUE THREAD

**Issue by notorioushanz** [stackblitz/bolt.new#49]
**Is your feature request related to a problem? Please describe:**

Every time the app is deployed, it generates a new netlify URL.
My app use supabase which require redirect URLs.
So at every deployment, supabase settings have to be updated for the app to work.

**Describe the solution you'd like:**

i'd like an integartion with an existing Netlify account so you can add your own custom domain.

**Describe alternatives you've considered:**

the possibility to directly add a custom domain for deployment

**Additional context:**

**Comment by Nemikolh** [comment]
Hey @notorioushanz! Thanks for creating this issue!

I've created an issue in our internal tracker. We'll keep you posted on this feature! We agree it would be amazing to be able to keep updating your deployment from bolt.new :star2:

**Comment by mauriciorubio2** [comment]
100%, I agree. Being able to easily push updates into production is super important and expected functionality. I don't think anyone builds anything and expects it to remain there static, without any on-going updates. You should be able to update the app > preview > if ok > push to production > if something breaks or isn't working as expected > rollback to state before additional changes were introduced or even an older version if proper versioning is implemented (auto saves, every time changes are introduced to the app)

**Comment by fixfounder** [comment]
I've had a similar experience where continuous deployments start off correctly but then go off track, generating random URLs and creating excess deployments. To manage this, I’ve asked Bolt to stop making automatic deployments and reduce the frequency. I’ve also tried different custom configurations to make Netlify deploy to a specific URL that Bolt believes should work, but it hasn’t worked as expected.

**Comment by poolsidefm** [comment]
+1 with this issue. Every time I deploy a new site lands in my Netlify account, it's becoming a mess fast

**Comment by ayalpani** [comment]
That's a big issue for me too

**Comment by QaunainM** [comment]
Hi all,  what is the process to get Bolt to deploy to a different source first, i.e. GitHub and then we could get GitHub to keep overwriting a Netflify deployment, as it seems that Bolt keeps creating new Netlify deployment instances / URLs every time?

**Comment by kc0tlh** [comment]
@notorioushanz, @ayalpani, @poolsidefm and @QaunainM Thanks for the feature request!

In order to make this happen, we will need to add Netlify authentication to the Bolt app so that you can update Deploys even after they are claimed into your user profile in Netlify. This is in progress and will be shipped in the next few weeks!

**Comment by QaunainM** [comment]
Hi all, in the meantime here is a way to push a Bolt project into GitHub which then continuously deploys to Netlify, its a bit of a messy process which has a bit of manual tweaking everytime you make a change https://www.youtube.com/watch?app=desktop&v=vB6JUrqnUTo

**Comment by kc0tlh** [comment]
@QaunainM agreed! For now, [that video](https://www.youtube.com/watch?app=desktop&v=vB6JUrqnUTo) shows a pretty good workaround process. 

One Improvement: Each Bolt chat is also a StackBlitz project that lives in StackBlitz.com > Collections > Bolt. Instead of manually copying changes from Bolt to StackBlitz for future Github pushes, you could download the StackBlitz project as a zip file (grey cloud icon in upper left of StackBlitz editor), and drag-n-drop the new files into the existing Github repo!

**Comment by manyyventures** [comment]
Desperate for this. The current work around is just a little overwhelming for me as a non-developer at the moment.

**Comment by QaunainM** [comment]
@manyyventures , I was on the office hours that @EricSimons and the team mentioned this will be out very soon! Even those familiar with development and servers need this :-)

**Comment by manyyventures** [comment]
For anyone looking for a manual workaround I wrote some instructions on how I am currently doing it in r/boltnewbuilders which only requires Bolt & Netlify to deploy my updates to my live app. Probably common knowledge for the folks in the know but might be helpful for the noobs like myself. Can be found here: https://www.reddit.com/r/boltnewbuilders/comments/1gu597n/live_site_deployment_workaround_bolt_netlify_only/

**Comment by endocytosis** [comment]
**Update:** You can now connect your Netlify account with Bolt and always deploy to the same URL, including your own custom domain names. To set this up, open Settings > Applications and then connect your Netlify account.

![image](https://github.com/user-attachments/assets/7e2a81b5-3fc9-47bf-aeef-219d299f81f2)

**Comment by stueynet** [comment]
> **Update:** You can now connect your Netlify account with Bolt and always deploy to the same URL, including your own custom domain names. To set this up, open Settings > Applications and then connect your Netlify account.
> 
> ![image](https://private-user-images.githubusercontent.com/47831340/389084699-7e2a81b5-3fc9-47bf-aeef-219d299f81f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTEzMDMsIm5iZiI6MTczMzE5MTAwMywicGF0aCI6Ii80NzgzMTM0MC8zODkwODQ2OTktN2UyYTgxYjUtM2ZjOS00N2JmLWFlZWYtMjE5ZDI5OWY4MWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAxNTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxM2IxNzUyOWVkMWNjNzIwNjk0Mzk5ZTA5M2U2ODgxMTAwYzFjYTc5ZWQwZTZkNjlkNzNmNjNkMDYzNzg0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-EnyxSYueO1rNtpyJyS3JCawymtkN4Tat71x0Tg7qGk)

Awesome!! Thanks for this its super helpful.

**Comment by manyyventures** [comment]
If I've already set up a custom domain on a Netlify project, is there a way
to have Bolt deploy to that project instead? Saves me having to play around
with the domain settings etc.

**Comment by QaunainM** [comment]
@aliharis thanks and what happens when you fork the app, does it decide to deploy to a new Netlify URL / instance or the same one that has your domain linked to it?

**Comment by Mohammedcvc** [comment]
![Image](https://github.com/user-attachments/assets/b162df7d-9ee7-45f7-aea0-c3dc2525dba4)     التحديثات لا تضهر على التطبيق   يضهر   هذه الرساله  

لا يمكن ارسال الدردشه ارجو المساعده
