### ISSUE TITLE
Cache Cleared

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#493]
### Describe the bug

It told me to clear the cache but when I did I lost everything.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xrrikm

### Steps to reproduce

I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Stackblitz Project

sb1-xrrikm
Unexpected end of JSON input
An unknown error occured while running an action.

Report Issue

Retry

You've used all your remaining tokens.Buy more

### Expected behavior

It was supposed to revert and work.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49236114,
  "usedJSHeapSize": 36006466,
  "jsHeapSizeLimit": 4294705152
}
Chat ID = 30bff3f53c0c
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
You can reload all of your projects into Bolt using the instructions in #39
