### ISSUE TITLE
Cache Clear pt. 2

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#496]
### Describe the bug

It's mighty convenient that all of my previous messages and hard work were deleted but my usage wasn't. If it cleared all of my hard work, I should be reimbursed for my tokens as well.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

View my account internally

### Expected behavior

This should be full again:
Usage
Billing period
8 November 2024
Per day
3.908.936
/
26.000.000
Per month
13.953.235
/
26.000.000
Purchased tokens remaining
0

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
This issue and its resolution are being tracked in #124. There are instructions there on how to load your existing Bolt projects from StackBlitz back into bolt as well!

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
