### ISSUE TITLE
no build configuration was found.

### ISSUE THREAD

**Issue by samccone** [stackblitz/bolt.new#5]
### Describe the bug

pressed deploy:

I've initiated the deployment process for your weather application to Netlify. The build and deployment process is now being handled automatically. Let's wait for the deployment to complete and retrieve the status.

Could not build the project because no build configuration was found.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qmuuus

### Steps to reproduce

build the app press deploy

### Expected behavior

it is deployed

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51843481,
  "usedJSHeapSize": 43774621,
  "jsHeapSizeLimit": 4294705152
}
Username = samccone
Chat ID = 941aa20f0ce0
```

**Comment by SamVerschueren** [comment]
Hey @samccone 👋 ! Thanks for reaching out.

We had some issues with the deploys in the beginning, but most of them are fixed. I tested it out with your project and it works now.

https://shiny-sprinkles-b1aa14.netlify.app/

I will be working on deploy to make them more reliable.

**Comment by samccone** [comment]
Thanks Sam!
