### ISSUE TITLE
Lost All my time and progress

### ISSUE THREAD

**Issue by Calvido** [stackblitz/bolt.new#501]
### Describe the bug

You have made me lose all the time and progress I had in the project, I had been working on it for days and yesterday when I asked for an improvement several project files were incomplete with commented segments indicating the legend "same previous code" and the project los everything and can´t run then. Do not handle a history of corrections or all the chat that allows me to return to a previous correct state. At the moment of asking to restore to a previous point, the project was simply invented, rules and implemented logics were lost, a total mess they made to me.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-f57jtt

### Steps to reproduce

Simple, i asking to restore to a previous point, the result is a simply invented, rules and implemented logics were lost, a total mess. The back Checkpoint the same thing. And all this cost me lost tokens, now i can´t explain to the IA all things to-do do again

### Expected behavior

I was hoping at the time of asking to go back to a previous step to get the integrity of the code before the last change request.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 180819290,
  "usedJSHeapSize": 174093526,
  "jsHeapSizeLimit": 4294705152
}
Username = Calvido
Chat ID = da0f58c3f73f
```

**Comment by Calvido** [comment]
The same report from other user: "Once the project is a bit detailed and requires changes in few pages. Bolt writes the updated code snippet but does not write the old code instead writes "//-- Existing code goes here" which pretty much breaks the website." And when i prompt please restore all code, simply invent, lost all logical and advances, lost tokens, lost days off work.

**Comment by Riakon1** [comment]
About 3 million of my 9 million used tokens so far this month were on creative endeavors, and the other 6 million were spent on trying to figure out how to fix the broken project that bolt overwrote with truncation or changed entirely directly against my instruction. I haven't bothered with the last 1 million because I know I wont be able to make any progress on anything before I hit a wall of fixing and breaking loops. Until they can fix the problem of context and memory none of these advanced tools will be more than a novelty.

**Comment by kc0tlh** [comment]
This issue, the current workaround, and the final resolution are breing tracked in #24

**Comment by samir-walji** [comment]
This happened to me also. I reloaded the page, and lost tons of chats and it went back to an older version of the project
