### ISSUE TITLE
Versioning not working properly. Unable to rollback to previous versions

### ISSUE THREAD

**Issue by mauriciorubio2** [stackblitz/bolt.new#51]
### Describe the bug

It completely failed at versioning. When I asked it to rollback to the initial prototype it just couldn't do it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ggjdqx

### Steps to reproduce

Take a look at the chat history. Also, ask it to rollback to the original version and it can't. The original version looked like this: https://bolt.new/~/sb1-suwz7g , which I was able to re-generate by starting from scratch using the same initial prompt. But needless to say you should never start from scratch

### Expected behavior

Versioning works properly. Bolt keeps a record as it makes changes to the app, so you can rollback to the previous state as needed. Versioning should happen automatically

### Platform

- OS: macOS
- Browser: Brave

### Additional context

You can read more about it here: https://x.com/_mauriciorubio/status/1842529786767499475

**Comment by ataldev** [comment]
+1
There must be a versioning system in place. It recreates everything from scratch if you tell it to return to a previous version.

**Comment by Nemikolh** [comment]
Hey! Thanks for raising this issue!

We're tracking this internally, and #35 is a similar feature request. I'm going to close this issue, feel free to subscribe for updates in the other issue! We'll keep you posted :raised_hands:
