### ISSUE TITLE
Missing Tokens

### ISSUE THREAD

**Issue by gitboikills** [stackblitz/bolt.new#513]
### Describe the bug

When I subscribed I subscribed for pro version but it said i had 30 M tokens, but now it just says I have 1 M left and have used around 8M+ tokens out of 10M token, theres a major discrepancy and please resolve this

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Go to Settings> Tokens

### Expected behavior

It should have had 30 M tokens but it only has 1M + tokens left. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ginuineca** [comment]
Everytime I try to update one component it removes something else. I have wasted $90 so far an have not completed one thing. Please resolve the issues. It keeps happening over and over again. I am also sure I have not gone through all the tokens. Also the price keeps changing. First it was $9.00 then jumped to $20 per 10M tokens. This is frustrating.

**Comment by kc0tlh** [comment]
@gitboikills the pro plan includes 10m tokens so everything seems in order here.

@ginuineca please reference issue #678 for tips around increasing token usage efficiency
