### ISSUE TITLE
Bolt is useless and absolutly not working

### ISSUE THREAD

**Issue by alexf1395** [stackblitz/bolt.new#516]
### Describe the bug

the updates take an infinite amount of time and ultimately produce nothing. Bolt absolutely doesn't work. The number of tokens is too limited, even for the free version. I will obviously never pay for something that doesn't seem to work at all. All I see is written code but it doesn't lead anywhere.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4gq7oh?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=sidebar

### Steps to reproduce

1. Just launch a simple prompt
2. Bug
3. Nothing happens

### Expected behavior

Something that works

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 42460166,
  "usedJSHeapSize": 41222698,
  "jsHeapSizeLimit": 2172649472
}
Username = alexfrs
Chat ID = 2924332b5e29
```

**Comment by Kumala3** [comment]
Hi Alex, I'm sorry to hear your frustration. Can you please share a prompt you used to reproduce the problem you're facing with Bolt? Have you tried to build a web app, or something different? As for me, a well-structured prompt with a clear goal leads to a foundational version of the app that I can use as a foundation to build upon. It's absolutely not perfect but an extremely good for non-tech people who want to build prototypes or even pretty good websites from scratch.

**Comment by alexf1395** [comment]
Thanks for your answer. Here is the prompt : 

_Develop a cross-platform application (Android, iOS, and web) that allows artisans and subcontractors to receive near real-time payments based on the progress of their work. Artisans can request payments with a simple button click by submitting photo evidence of completed tasks. The app should streamline payment processes, making task submission and work verification easy. Clients and artisans must be able to register, log in, create projects, list tasks, and upload progress photos. Key features should include automatic validation of completed work, simple approval of project amendments, and secure real-time payment transfers from the client’s account to the artisan's account upon task approval. Additional features include automated milestone tracking, digital signatures for task approvals, integration with bank APIs and digital wallets, customizable project timelines, push notifications for approvals and payments, an integrated messaging system, a dashboard summarizing project status and payments, dispute resolution tools, offline functionality for work submission, historical records of payments and projects, PDF export of project documentation, tax compliance tools, multi-currency support, data encryption for security, user reviews and ratings, support for project amendments and extra work requests, and multi-language functionality for international users._

Maybe he is too long...

**Comment by alexf1395** [comment]
I have to wait for the tokens to come back every day even with a paid plan?

**Comment by Kumala3** [comment]
> I used a simple prompt to try to create someting. I tried to built a web app + android/iOS app.
> 
> I have to wait for the tokens to come back every day even with a paid plan?
> 
> The preview only remains blank, impossible to see the result of the code created. the application is unusable... and the tokens are gone much too quickly.

The issue you're experiencing is clear but with no solution now. **Bolt.new** is designed to build full-stack web apps, and it's best at creating apps from scratch step-by-step. In the "**Tips and Tricks**" you can view best practices and tips on how to get the desirable results, the most important thing from there is: "**Scaffold the basics first, then add features**". It essentially means that you need to breakdown your complex prompt into logical parts that AI can handle, and then add features to it. You also mentioned you asked it to build android/iOS app but the thing is that it can't run the code for mobile apps AT ALL. Therefore, it can hallucinate trying to convince you that it's creating app, fixes bugs, adds new features but just got into the rabbit loop, and became useless until you start a new conversation. Depending on your paid plan, you are getting a certain amount of tokens, for example, as of today, pro plan offers you 10M tokens which resets monthly.

**Comment by kc0tlh** [comment]
Apologies for the frustrating experience. Please feel free to reach out to [hello@stackblitz.com](mailto:hello@stackblitz.com) for a refund while we continue to work thru the beta period and improve the app.

**Comment by IMTanuki** [comment]
Except for the simplest apps, Bolt is NOT ready for prime time. I'm trying to develop a simple chatbot in vuejs and nuxt and it just keeps digging itself into a deeper hole. Before adding vercel, I asked it if it had version history and it insisted it could roll back to a stable version - nyet.

**Comment by drpintotorres** [comment]
Wow, I ma speechless, the promos state otherwise, this saved myself a subscription.

**Comment by IMTanuki** [comment]
I think all of these tools are about the same - great concept, but they need 4-6 months. I tried Windsurf, same results - both Bolt and Windsurf can generate Nuxt apps, but the code is non-standard and at a certain point, each additional modification creates more bugs than it solves. If they got this far, I'm confident they'll have sth solid before the end of 2025.

**Comment by drpintotorres** [comment]
> I think all of these tools are about the same - great concept, but they need 4-6 months. I tried Windsurf, same results - both Bolt and Windsurf can generate Nuxt apps, but the code is non-standard and at a certain point, each additional modification creates more bugs than it solves. If they got this far, I'm confident they'll have sth solid before the end of 2025.

I understand your point, but I have some doubts and concerns. Every product or service goes through stages of development, introduction, growth, maturity, and decline. Rushing for quick profits can often lead to premature failure. It's essential to ensure that each stage is carefully managed to achieve long-term success. Hastening the process for immediate financial gain can undermine the product's potential and sustainability.

**Comment by IMTanuki** [comment]
Just my 2 cents - the name of the game these days is time to market, quality be damned
