### ISSUE TITLE
Bolt decided to delete all the previous changes to fix a bug. 

### ISSUE THREAD

**Issue by nans64** [stackblitz/bolt.new#517]
### Describe the bug

Bold decided to delete all the previous changes to fix a bug and delete the latest work and take it as an instruction when I clicked on fix bugs.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-z633vj

### Steps to reproduce

1. Create a feature
2. Get an error
3. Fix the error
4. Bolt deleted the previous work

### Expected behavior

Take in consideration the previous work and make sure to not get back

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 154569432,
  "usedJSHeapSize": 150534136,
  "jsHeapSizeLimit": 2172649472
}
Username = nans64
Chat ID = b4302a48f4b3
```

**Comment by hijuliancode** [comment]
You're right; this happens to me quite often. Trying to fix those bugs consumes a lot of tokens, which makes them run out quickly. Even when it's specified not to delete something that has already been done, it insists on removing it, which is really frustrating

**Comment by kc0tlh** [comment]
Appreciate your patience during this beta period as we work to improve the platform! This issue, some powerful temporary workarounds, and it's resolution is being tracked in issue #24
