### ISSUE TITLE
URGENT!  NEED MORE TOKENS! PLEASE READ

### ISSUE THREAD

**Issue by Terman7a** [stackblitz/bolt.new#520]
OK LOVE Bolt...BUT this whole how to buy new tokens process is a mess. I NEED TO BUY MORE TOKENS TO COMPLETE MY PORJECT.
I have upgraded many times to teams, and then something lese and then something else.  i just re-upgraded to the $20 for 10M tokens and it only charged me $8...prorating I guess..then I did the $50 and it only charged me $23...Ive paid $35 a couple of times this last week and it eventually adds tokens.....sort of.....bottom line  HELP! I simply want to buy 20M tokens or whatever amount you will let me buy. 
I have a deadline
its REALLY important
Just trying to do business with you but your purchase system makes no sense to an average person.
I JUST UPGRADED AGAIN IN AN ATTEMPT TO SIMPLY BUY MORE TOKENS to the 20, the $50 and NOW the $100
it prorates in all situations so who knows what that means. PLEASE JUST ADD TOKENS FOR ME. It is critical I get tihs done.
Oct 13, 2024  $37.21    Paid  Pro 100 Oct 13, 2024  $22.34     Paid Pro 50  Oct 13, 2024  $8.32  Paid Pro

Terence McMahon

mynsbm@gmail.com

**Comment by kc0tlh** [comment]
@Terman7a you can buy more in the "My Subscription" area, located lower left corner of the app

**Comment by Terman7a** [comment]
Hi Alexander,

I don't know if you were able to read my support ticket all the way the
problem was is that 6.8 million tokens were wiped out of my account.

What I was talking about was all the sudden the platform froze and I had to
hard clothes out of the browser
I relogged in and all 6.8 million were gone
I had bought around 20 million or something like that before

I did eventually have to go by another 20 million

But there was a problem with the platform of some sort and I'm looking to
recoup those 6.8 million

Any help you could give me I would be grateful

Terry McMahon
