### ISSUE TITLE
Chat history went missing, after/or something like crashes.

### ISSUE THREAD

**Issue by LeonixZx** [stackblitz/bolt.new#521]
### Describe the bug

My chat history went missing. Plus it happened after my application cant load images i inserted on my app, it didnt reflect.

There is no error shown on the terminal. So i couldnt find what is the issue.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

I cant say nothing, since there is no chat history. 

### Expected behavior

My app loaded the images.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@LeonixZx info on how to open old chats can be [found here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671 ) along with our progress on implementing chat persistence in #39
