### ISSUE TITLE
Bolt is just flat out not doing what I ask it to

### ISSUE THREAD

**Issue by PropertyVue** [stackblitz/bolt.new#523]
### Describe the bug

I am trying to get it to do really simple stuff and it is saying that it has accomplished it but nothing changes. I am throwing so many tokens away which is not ideal. I am trying to build a document template builder and I cannot get it to add functionality to save the template. Everytime I try to fix it, it says it has accomplished the task but then it does not actually work.

![image](https://github.com/user-attachments/assets/d249b707-9ca8-4b96-a9e9-d2beff8a78b7)
![image](https://github.com/user-attachments/assets/cd0626af-60d4-4250-8179-32561200a9e7)

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

1. request functionality 
2. bolt says it has added
3. bolt has not added it
4. tokens spent

### Expected behavior

I should not be spending all of my tokens for bolt to not actually work. Getting a little frustrated with this.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
This is being addressed in #678. Stay tuned!
