### ISSUE TITLE
Concerns Regarding Unwanted Changes and Token Usage

### ISSUE THREAD

**Issue by al-teamaot-com** [stackblitz/bolt.new#524]
I am reaching out to express concerns about recurring issues while using Bolt.new for development:

The platform frequently alters my push-to-GitHub scripts, consuming tokens and time unnecessarily.
When asked yes/no questions, it unpredictably changes code without instruction.
It forgets previous discussions on the same project, requiring token-heavy fixes.
It makes unwanted changes like removing formatting or reverting files to old versions.
It treats the code as if it were on my computer, despite it being in the Bolt environment.
I appreciate the platform's potential but these issues are making it risky to use. I hope these can be addressed.
There is, currently, no apparent way to add tokens if you consume your monthly quota even though lots of tokens are wasted on the above issues.
I purchased a year subscrition before the price increase and with these issues, I would not renew or increase my subscription. It only took a few days to chew through 20M tokens and by the time I get more, I will have probably moved on to another tool.

Hope these issues are resolved as the tool is very helpful.

**Comment by kc0tlh** [comment]
@al-teamaot-com thanks for the feedback, we are working on all of these issues! 

The best thread for you to follow is issue #678 as most all of your issues will be resolved by various updates that we will be posting there in the coming weeks.
