### ISSUE TITLE
Truncation Hell

### ISSUE THREAD

**Issue by coletcyre** [stackblitz/bolt.new#525]
### Describe the bug

No matter how many times I request to the agent to stop truncating code, it will continue to do so. This seems to happen if a conversation goes on long enough, but to be honest it doesn't take much time at all before the program isn't working because it removed entire classes/functions. 
![Screenshot 2024-10-13 124426](https://github.com/user-attachments/assets/1db8a438-9b0b-41ca-9e13-547db8d375b3)

While it wasn't this specific project, I did have one where this issue added about 5 hours to my project just to fix it's issues. And pushed me to upgrading a tier earlier than I wanted to. (I am still paying and using the tier of course)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m8q7zy

### Steps to reproduce

Idk what steps to reproduce, it always occurs when I am providing feedback or asking for changes, after about 4 or 5 prompts (sometimes as low as 2) it will begin truncating and nuking old features. 

### Expected behavior

Stop truncating. If I ask it to make any changes, it should (ON ITS OWN) update and track changes/ bad code choices into a document while assisting. I have to ask it this every time and even still it fails to update the documentation or just nukes it making it useless. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 144979331,
  "usedJSHeapSize": 112626187,
  "jsHeapSizeLimit": 4294705152
}
Username = coletcyre
Chat ID = dc504cf83bf3
```

### Additional context

I really really like this tool, but these bugs are going to cost me more time and money than it's worth.

**Comment by eliaspizarro** [comment]
// ... (el resto del código permanece igual)

**Comment by kc0tlh** [comment]
Appreciate your patience during this beta period as we work to improve the platform! This issue, some powerful temporary workarounds, and it's resolution is being tracked in issue #24
