### ISSUE TITLE
chats not saved

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#526]
### Describe the bug

it would be nice if all of the previous messages in the chats were saved so i could remember where i left off. right now, all i see is this message: I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.
But without all of the previous chat information, I can't remember what I've accomplished and/or if anything needed to be elaborated on or implemented further. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-djg3o8

### Steps to reproduce

Go to bolt.new and select a chat or go to the collections tab and open the repository in bolt.new.

### Expected behavior

All previous chats from the project were there, not just this note: I'm importing your StackBlitz project into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84643666,
  "usedJSHeapSize": 71813958,
  "jsHeapSizeLimit": 4294705152
}
Username = nonistack
Chat ID = 505728353b78
```

**Comment by kc0tlh** [comment]
This issue is being tracked in #39
