### ISSUE TITLE
Claiming URL goes to a broken link

### ISSUE THREAD

**Issue by mitchellbernstein** [stackblitz/bolt.new#527]
### Describe the bug

Clicking the URL the ai produced to claim the url sends me to this page.

![CleanShot 2024-10-13 at 14 51 53@2x](https://github.com/user-attachments/assets/86b37d9c-50dd-457f-a2ba-b8a74b80fb8b)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5pphjf

### Steps to reproduce

1. Click the "deploy" button in the top right of bolt.new
2. Click on the URL to claim it in netlify after "Additionally, you have the option to claim this project within the next week using the following claim URL:"
3. URL shows as the image above. Page not found.

### Expected behavior

Open the URL in netlify and let me retain it and add a domain to it.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 153762099,
  "usedJSHeapSize": 148716979,
  "jsHeapSizeLimit": 4294705152
}
Username = mitchellbernstein
Chat ID = 8dc56ce7f2cb
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
