### ISSUE TITLE
You should keep track of the previous versions and be able to restore them

### ISSUE THREAD

**Issue by felix-butzbach** [stackblitz/bolt.new#528]
**Is your feature request related to a problem? Please describe:**

Sometimes bolt messes up the app and it wont work anymore.
Asking it to revert to the previous version did not work, but would be pretty useful.
Especially, if this would not consume tokens, or at least not the same amount it took to create the version in the first place.

**Describe the solution you'd like:**

Some kind of history of all changes bolt has done with the option to revert to the previous one or maybe even arbitrary previous versions.

**Describe alternatives you've considered:**

The alternative in my case was to repeat the previous prompts while fixing new bugs bolt introduced along the way

**Additional context:**

Note: I am pretty sure this feature request was already placed before, but I did search for it.
Note2: This is also a kind of bug report, as it would be nice, if bolt could just undo what it did in the last response, but it somehow cant.
Note3: Apart from this, I see great potential in bolt, keep up the great work!

**Comment by kc0tlh** [comment]
This has landed: https://x.com/stackblitz/status/1844839379270836266
