### ISSUE TITLE
Cant see anything on the preview option 

### ISSUE THREAD

**Issue by MAYANK12-WQ** [stackblitz/bolt.new#530]
### Describe the bug

i run the codes and i can just see a white screen and i am trying to fix it for an hour now nothing really changes 
![image](https://github.com/user-attachments/assets/09438c0f-ef63-4c15-afcc-42475e792769)

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-szunzv

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4b5f3033-65d1-4775-9fca-70babce37f5d)

### Expected behavior

it suppose to run my program which is ai tecajhing assistant 

### Screen Recording / Screenshot

https://bolt.new/~/stackblitz-starters-szunz
![image](https://github.com/user-attachments/assets/c78a4907-7b7a-4dd8-b12d-f5cd3ec24cde)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
