### ISSUE TITLE
cannot connect to port I think? preview is blank.

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#532]
### Describe the bug

The software can't correct itself. My preview page remains blank.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-djg3o8

### Steps to reproduce

Ask it to fix the bug. It will go in circles but not provide an actual solution.

### Expected behavior

Fix the error. As a matter of fact, warn me of potential errors so I can handle them as they arise. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77464783,
  "usedJSHeapSize": 72469971,
  "jsHeapSizeLimit": 4294705152
}
Username = nonistack
Chat ID = bc9655001391
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it https://github.com/stackblitz/bolt.new/issues/1791.

Bolt is most compatible with Chrome and Chromium browsers.

Try selectively disabling browser extensions such as ad blockers and refresh the page to see if this resolves the problem. Additionally, you can try typing "npm run dev" in the Bolt console.
