### ISSUE TITLE
Multiple Files being written into

### ISSUE THREAD

**Issue by DistinctlyMktgLLC** [stackblitz/bolt.new#534]
### Describe the bug

I was provided with an architecture for a streamlit build and I was provided two directories that contained the same file, those file did not match the directory structure I provided via screenshot of my streamlit buiid. when I make requests, it writes to both files although ive pointed out several times and included screenshots on what the front end response looks like.  to the app's credit it apologizes for the oversight however continues to do the same thing.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n6u8xa

### Steps to reproduce

Simply enter any change, issue, etc with the `map_visualization.py` file as a reference
it will write into both map_visualization files,. only writing 72 lines into one and the full code to another
it also bounces you from the first file it wrote into STOPS and writes the full code into the other file

### Expected behavior

I expect the file directory NOT being used to be removed leaving on one file so there isnt duplication

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60218922,
  "usedJSHeapSize": 53872046,
  "jsHeapSizeLimit": 2172649472
}
Username = DistinctlyMktgLLC
Chat ID = da08987498a0
```

**Comment by kc0tlh** [comment]
@DistinctlyMktgLLC thanks for the feedback! We are currently building a feature that allows you to lock files that are done, so the AI cannot make additional changes. This will be shipping in the next 1-2 weeks!

**Comment by kc0tlh** [comment]
This feature will be announced this week in #678
