### ISSUE TITLE
Dissapointment.

### ISSUE THREAD

**Issue by Riakon1** [stackblitz/bolt.new#535]
I'm not quite sure I understand what the intended use case for this site is. It presents it's self as an AI coding all in one,  prompt to deployment of a full stack app, but instead its just another tool that showcases how quickly LLM's spiral into recursive logic failure . IF you want to create something super simple that does one task that you probably didn't need Bolt.new to make anyway, this is the tool for you. If you want to make something sophisticated and useful and complete, this is not the tool for you, unless you have unlimited funds to burn on tokens to endlessly fix recurring loops of the same exact bug appearing or figuring out where your 500 lines of truncated code went. If you ask for a single thing to be changed such as "change the title from "Super Cool App" to "Cool App""  then expect to see 14 other things changed and many, many lines of code suddenly vanished. This could be promising if it actually did what it purports to do but that is not the case, and if you take just a moment to look at the issues page you will see hundreds of the same exact post being made regarding all of their code being truncated into oblivion or bolt just flat out ignoring instructing and not following the users direction. I have cancelled my 20 dollar subscription and have deleted my account and removed all of my massive pile of broken, uncompleted projects (some of which worked great for 1 or 2 iterations and then quickly descended into unrecoverable truncation hell) Hopefully things follow the same trend as of late and an opensource free local version that does the same thing comes along.

**Comment by Riakon1** [comment]
https://github.com/stackblitz/bolt.new/issues/517
https://github.com/stackblitz/bolt.new/issues/516
https://github.com/stackblitz/bolt.new/issues/503
https://github.com/stackblitz/bolt.new/issues/534
https://github.com/stackblitz/bolt.new/issues/525
https://github.com/stackblitz/bolt.new/issues/524
https://github.com/stackblitz/bolt.new/issues/523
https://github.com/stackblitz/bolt.new/issues/501
https://github.com/stackblitz/bolt.new/issues/479
https://github.com/stackblitz/bolt.new/issues/481
https://github.com/stackblitz/bolt.new/issues/473
https://github.com/stackblitz/bolt.new/issues/471
https://github.com/stackblitz/bolt.new/issues/460
https://github.com/stackblitz/bolt.new/issues/445
https://github.com/stackblitz/bolt.new/issues/455
https://github.com/stackblitz/bolt.new/issues/439
https://github.com/stackblitz/bolt.new/issues/436
https://github.com/stackblitz/bolt.new/issues/429
https://github.com/stackblitz/bolt.new/issues/421
https://github.com/stackblitz/bolt.new/issues/419
https://github.com/stackblitz/bolt.new/issues/405
https://github.com/stackblitz/bolt.new/issues/396
https://github.com/stackblitz/bolt.new/issues/382
https://github.com/stackblitz/bolt.new/issues/380
https://github.com/stackblitz/bolt.new/issues/369
https://github.com/stackblitz/bolt.new/issues/360

Just as a sort of reference to my point. 

I could go on and on and on..

**Comment by curiousguyinhis30s** [comment]
True.  I have been using this website and i have been fix it's issues all the time.

**Comment by mobm93** [comment]
IDK if it is just me. Every AI tool performs so bad when I actually buy a subscription and try to use it with no limits. They all loose their shit. xD

**Comment by Riakon1** [comment]
https://github.com/coleam00/bolt.new-any-llm

https://www.youtube.com/watch?v=3PFcAu_oU80

i found someone who made a fork of this and added local free models to it but you need a little bit of hardware. 

im having a little bit of success with not too much hardware though but its free!

3060ti 64gb ddr4 i7 11700

**Comment by kc0tlh** [comment]
Apologies for the frustrating experience. We working as fast as we can to improve the user experience and find creative ways to improve the AI / LLM performance.

One of the core issues you experienced is being tracked in #24 (as well as some workarounds and tips)

**Comment by curiousguyinhis30s** [comment]
I guess the token usage is not so transparent.  i'm able to do more in 20$
V0 subscription then the 50$ Bolt .new.  I only spend 3 days and 26M tokens
are completed. I ws ony able to make one project 95%.  Can you guys work on
this please.  I learnt how to use it and it has beengood so far.


https://splendid-semifreddo-0bd468.netlify.app
this is the website i build.  how to download the project files so that i
can run it locally and do the modification in local.

**Comment by kc0tlh** [comment]
@curiousguyinhis30s project files can be found for download in StackBlitz.com > Collections > Bolt
