### ISSUE TITLE
1-click-deployment of fullstack web app

### ISSUE THREAD

**Issue by ayalpani** [stackblitz/bolt.new#537]
**Is your feature request related to a problem? Please describe:**

It seems as if there is no real / documented solution for deploying both frontend and backend.

**Describe the solution you'd like:**

The deploy-button on the top-right allows me to deploy everything with one click, also the server. I can choose from a provider you really know can deal with the deployment triggered by bolt. 

**Describe alternatives you've considered:**

**Additional context:**

For me it is one of THE most important issues, that I can not just deploy everything at once. This makes your service - as cool as it is - almost unusable for any serious work for me. I can not develop a fullstack app in between 2 different environments and sync between them easily. I love bolt BTW

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499. We do have plans to add additional deployment providers in the future. In the meantime, you can also use StackBlitz.com to push your code into Github or download it, and deploy manually!
