### ISSUE TITLE
Previous chats / conversations not visible in left navigation

### ISSUE THREAD

**Issue by TimPietrusky** [stackblitz/bolt.new#54]
### Describe the bug

After I log in, I don’t see my previous chats / conversations in the left sidebar. 

### Link to the Bolt URL that caused the error

n/a

### Steps to reproduce

1. Login to bolt on a device like your computer 
2. Create a bolt
3. Login on another device like your phone 
4. Open the left sidebar to continue your bolt
5. See that there is nothing

### Expected behavior

I can always see all my bolts regardless of the device. 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/670dd7c3-f871-4bfa-bfd4-9334fac6857a)

### Platform

- OS: iOS
- Browser: Chrome
- Version: n/a

**Comment by Nemikolh** [comment]
Hey @TimPietrusky! We currently persist your conversations in your local browser. If you clear your cache, they will be gone.

**Comment by mauriciorubio2** [comment]
I find this nuts @Nemikolh. My browser clears cache, history, etc. by default every time I close my browser as a safety/privacy measure. Please fix this, it is a major issue: https://github.com/stackblitz/bolt.new/issues/160

**Comment by kc0tlh** [comment]
@TimPietrusky Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #17!
