### ISSUE TITLE
143 problems is insane 

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#540]
### Describe the bug

The entire app must not have been formulated properly from the beginning because there are 143 potential problems detected.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-djg3o8

### Steps to reproduce

npm run dev

### Expected behavior

For the development to run and for my web app to function

### Screen Recording / Screenshot

![Screenshot 2024-10-13 202931](https://github.com/user-attachments/assets/2b8dae9f-2bc0-4169-a6aa-a500bffe63ac)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46981955,
  "usedJSHeapSize": 44273735,
  "jsHeapSizeLimit": 4294705152
}
Username = nonistack
Chat ID = 9827e4fb41c8
```

**Comment by kc0tlh** [comment]
Thanks for your patience during this beta period.
