### ISSUE TITLE
my project disappeared for no reason

### ISSUE THREAD

**Issue by manyone** [stackblitz/bolt.new#541]
### Describe the bug

i tried a couple of time to do more work but  i wasnt successful.  - i ran out of tokens.  so i left it.  maybe going back to it after overninght it would work but it didnt.  now it has disappeared.

### Link to the Bolt URL that caused the error

cannot find project

### Steps to reproduce

cannot find project

### Expected behavior

should be able to see project on top of project list

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/6b897fa9-b616-4a01-abfa-c737cceb6dab)

### Platform

windows 10

### Additional context

i do have  link to the (90% working) project:
https://adorable-basbousa-dd9371.netlify.app/

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50

**Comment by manyone** [comment]
You marked it completed.  Were you able to restore my project in bolt?Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone
-------- Original message --------From: Sam Denty ***@***.***> Date: 10/16/24  2:00 PM  (GMT-08:00) To: "stackblitz/bolt.new" ***@***.***> Cc: manyone ***@***.***>, Author ***@***.***> Subject: Re: [stackblitz/bolt.new] my project disappeared for no reason (Issue
  #541) 
Closed #541 as completed.

**Comment by samdenty** [comment]
So sorry that you experienced this extremely frustrating bug! There are 2 possible scenarios here:

**Scenario A:** Chat history is currently not persisted across browsers/devices, and chats will disappear from the Bolt.new UI if your cache is cleared, so it is possible that your project was actually saved to StackBlitz behind the scenes. If that is the case, you can find your project on [StackBlitz.com](http://stackblitz.com/) (same account as Bolt.new) > Collections Tab > Bolt collection.

**Scenario B:** if Scenario A does not apply, unfortunately your work has been permanently lost due to a very serious bug. We just identified the root cause moments ago. We are tracking the resolution in #50 and working as I type this to resolve it ASAP!


While bugs can happen during beta periods, this one is very serious and frustrating, and we are very sorry that you were affected.

**Comment by manyone** [comment]
Sam,thanks for this info, i was able to recover my project and work it to completion.

BTW, i submitted another issue (how do i go see all the issues i submitted?  i didnt see an easy way) - it was something like this:

i could not deply because i caught 'unknown error at application build' and it always results in hanging my pc that i always have to reboot.

i found out what caused it - i made sure to note what was in the terminal window at that time and here it is:  

vite:terser not found...need dependency... need to install
trace at leadtercerFath, at renderChunk...

i mentioned this back to bolt.new and it fixed it.  my deploy worked.

FYI - in case it comes up again
thanks,manny
   On Wednesday, October 16, 2024 at 03:19:09 PM PDT, Sam Denty ***@***.***> wrote:  
 
 


So sorry that you experienced this extremely frustrating bug! There are 2 possible scenarios here:

Scenario A: Chat history is currently not persisted across browsers/devices, and chats will disappear from the Bolt.new UI if your cache is cleared, so it is possible that your project was actually saved to StackBlitz behind the scenes. If that is the case, you can find your project on StackBlitz.com (same account as Bolt.new) > Collections Tab > Bolt collection.

Scenario B: if Scenario A does not apply, unfortunately your work has been permanently lost due to a very serious bug. We just identified the root cause moments ago. We are tracking the resolution in #50 and working as I type this to resolve it ASAP!

While bugs can happen during beta periods, this one is very serious and frustrating, and we are very sorry that you were affected.

**Comment by samdenty** [comment]
@manyone could you open a separate issue, that really helps thanks

**Comment by manyone** [comment]
I did open a new issue. I just don't know how to get to Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone
-------- Original message --------From: Sam Denty ***@***.***> Date: 10/16/24  8:16 PM  (GMT-08:00) To: "stackblitz/bolt.new" ***@***.***> Cc: manyone ***@***.***>, Mention ***@***.***> Subject: Re: [stackblitz/bolt.new] my project disappeared for no reason (Issue
  #541) 
@manyone could you open a separate issue, that really helps thanks

**Comment by manyone** [comment]
i closed it: (bolt.new fixed it after i supplied thh error info

 during build_application of deploy, unknown error occured #590 
during build_application of deploy, unknown error occured · Issue #590 · stackblitz/bolt.new




| 
| 
| 
|  |  |

 |

 |
| 
|  | 
during build_application of deploy, unknown error occured · Issue #590 ·...

Describe the bug deploy fails at build application step (unknown reason) Link to the Bolt URL that caused the er...
 |

 |

 |




    On Wednesday, October 16, 2024 at 09:45:07 PM PDT, manyone ***@***.***> wrote:  
 
 I did open a new issue. I just don't know how to get to 


Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone

-------- Original message --------From: Sam Denty ***@***.***> Date: 10/16/24 8:16 PM (GMT-08:00) To: "stackblitz/bolt.new" ***@***.***> Cc: manyone ***@***.***>, Mention ***@***.***> Subject: Re: [stackblitz/bolt.new] my project disappeared for no reason (Issue #541) 



@manyone could you open a separate issue, that really helps thanks
