### ISSUE TITLE
confusing language for non-devs; conflicting information

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#542]
### Describe the bug

maybe not a bug but this could still be good feedback. please understand I'm not a web developer so messages like this are confusing. First it said: Also, make sure that your .env file contains a proper JWT_SECRET for production use, as the current fallback ('your_jwt_secret') is not secure for a production environment.

Then it said:
It's crucial to keep the .env file secure and not expose its contents publicly, as it often contains sensitive information like API keys and secrets. In a real-world scenario, you would typically not include actual secret values in version control, but rather use placeholder values and provide the real values securely to your deployment environment.

How am I supposed to use "a proper JWT secret code" but not include actual secret values? Are "proper" and "actual" different in this scenario? Perhaps dumb this down for non web-devs?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-djg3o8

### Steps to reproduce

edit the .env file

### Expected behavior

it goes, "awesome! that was fully implemented."

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54915482,
  "usedJSHeapSize": 47820326,
  "jsHeapSizeLimit": 4294705152
}
Username = nonistack
Chat ID = 9827e4fb41c8
```

**Comment by kc0tlh** [comment]
Thanks for the feedback during the beta!
