### ISSUE TITLE
Code Deletion & Incomplete File Generation Causing Excessive Credit Usage

### ISSUE THREAD

**Issue by gmb9000** [stackblitz/bolt.new#543]
### Describe the bug

While creating an application and adding features, Bolt is repeatedly deleting sections of code and failing to complete files correctly. This issue has caused significant disruption, leading to wasted credits and effort due to needing to redo code generation multiple times.

Key problems observed:

	1.	Code Deletion: Bolt deletes previously generated code. Even if I manually add corrections or my own code to fix issues, Bolt deletes those additions during the next code generation cycle.
	2.	Incomplete Files: Bolt often rewrites an entire file, but large portions (including several functions) disappear unexpectedly. At times, Bolt saves only half the file or stops generating code altogether, even when prompted to continue.
	3.	Repeated Iterations: Due to the deletion and incomplete files, I must iterate over the same task multiple times just to restore deleted functions and complete the code. This causes excessive credit consumption with no progress made.

This issue makes it nearly impossible to complete tasks effectively, significantly impacting the workflow and resource consumption on the platform.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-belyyy

### Steps to reproduce

1.	Correct a bug or create a new feature using AI coding assistant.
	2.	Observe as Bolt rewrites and deletes sections of the generated file.
	3. Doesn't run get error
	4. Request to fix the error
	5. Bolt says completed but only half the file is written. 
	3.	If you Attempt to manually add missing functions or correct code.
	4.	Bolt will often delete or revert those additions, or fail to complete the file correctly without even running the assistant. If you add code, save, refresh the browser prview. Bolt will delete the additions.

### Expected behavior

Not deleting the code or completing the requested file.

### Platform

- Mac OS: [e.g. macOS, Windows, Linux]
- Browser: Arc
- Version: [e.g. 91.1]

**Comment by dineshchandakshubhchintak** [comment]
+1

**Comment by kc0tlh** [comment]
@gmb9000 + @dineshchandakshubhchintak appreciate your patience and feedback during this beta launch! 

We are aware of the limitations described above and are working on some backend improvements to make Bolt even more effective. We are sharing progress on that front as well as some great tips on how to best utilize Bolt efficiently today in issue #678!
