### ISSUE TITLE
Excessive errors, not able to automatically bug fix, not able to fix so preview works, Code Deletion & Incomplete File Generation Causing Excessive Credit Usage

### ISSUE THREAD

**Issue by Jimmy-Jim-J** [stackblitz/bolt.new#546]
### Describe the bug

While creating an application and adding features, Bolt is repeatedly amending and bug fixing sections of code and failing to complete files correctly. Aften many more errors are outputted than is fixed, causing a cascade of errors building up. 
Bolt is not able to solve the Preview issue, so the application can't be viewed. 
This issue has caused significant disruption, leading to wasted credits and effort due to needing to redo code generation multiple times.

Key problems observed:

1.	Code Deletion: Bolt deletes previously generated code. Even if I manually add corrections or my own code to fix issues, Bolt deletes those additions during the next code generation cycle.
2.	Incomplete Files: Bolt often rewrites an entire file, but large portions (including several functions) disappear unexpectedly. At times, Bolt saves only half the file or stops generating code altogether, even when prompted to continue.
3.	Repeated Iterations: Due to the deletion and incomplete files, I must iterate over the same task multiple times just to restore deleted functions and complete the code. This causes excessive credit consumption with no progress made.

### Link to the Bolt URL that caused the error

https://bolt.new/ (Removing direct link due to the bolt.new project being open to anyone, no account security!)

### Steps to reproduce

Correct a bug or create a new feature using AI coding assistant.
2. Observe as Bolt rewrites and deletes sections of the generated file.
3. Doesn't run and build - get error
4. Request to fix the error
5. Bolt says completed
6. Bolt will often delete or revert those additions, or fail to complete the file correctly.

### Expected behavior

Bolt's benefit is to build, review, fix and run code. 
At present, it's incapable of this core offering.  

### Screen Recording / Screenshot

![Errors 141024](https://github.com/user-attachments/assets/43084436-9136-4fda-9b6f-9ccb61a0762d)

![image](https://github.com/user-attachments/assets/4a2adaf9-b9d3-4e1f-bc48-41ba5a96574d)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 122107895,
  "usedJSHeapSize": 116409063,
  "jsHeapSizeLimit": 4294705152
}
Username = Jimmy_Jim_J
Chat ID = b7d082aaf8b0
```

### Additional context

I'm a paying subscriber. I have spent numerous hours on  Saturday and Today Monday trying to solve the issue.

**Comment by Jpubli** [comment]
Have you had any responses from @stackblitz-gitops ?

**Comment by tbatirov** [comment]
Bolt tried to fix problems 5 times but failed. To prevent spending more tokens, you might want to try to fix them manually or rollback to a previous checkpoint instead.

**Comment by tbatirov** [comment]
so frustrating

**Comment by kc0tlh** [comment]
@Jimmy-Jim-J, @tbatirov, and @Jpubli appreciate your patience and feedback during this beta launch! 

We are aware of the limitations described above and are working on some backend improvements to make Bolt even more effective. We are sharing progress on that front as well as some great tips on how to best utilize Bolt efficiently today in issue #678!
