### ISSUE TITLE
I keep loosing all my work. I wish there was a big red save button.

### ISSUE THREAD

**Issue by MarcinCebula** [stackblitz/bolt.new#55]
### Describe the bug

Let me just start by saying that I love what you're doing here. This is the first product I used where I can see myself prompting a full (for now landing page) website build. BUT I lost my work 3 times now and ran through 200k credits/tokens which I feel could be resolved with a save button. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-f7txgx

### Steps to reproduce

1. Prompt changes
 a. loose connection
 b. leave page
 c. refresh
2. it revert to a step from few minutes to all the way to prompt 1

### Expected behavior

Ideally it would auto save on every prompt but if there was a save button that would also work perfectly well.

### Platform

chrome
macOS

### Additional context

Awesome work on this project!

**Comment by konradre** [comment]
Needs git integration like Cursor has.

**Comment by u007** [comment]
u can use bookmark for now
