### ISSUE TITLE
Cant deploy this app

### ISSUE THREAD

**Issue by leestarr** [stackblitz/bolt.new#551]
### Describe the bug

Cannot deploy keep getting this error 

<img width="405" alt="image" src="https://github.com/user-attachments/assets/a6542a0d-5d4c-45e4-a4a3-33f45a93daa8">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vp1ewb

### Steps to reproduce

Press deploy

### Expected behavior

doesnt deploy app and keeps giving me the errror on build application 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141887724,
  "usedJSHeapSize": 136109180,
  "jsHeapSizeLimit": 4294705152
}
Username = leestarr
Chat ID = 1d2cb50263c1
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@leestarr we do not support deploy to Vercel, just Netlify. This particular project will not open at all for me, so I would recommend trying again with a different project and Netlify deploy (you can also just use the deploy button in upper right corner of the app).

**Comment by matts1213** [comment]
@kc0tlh is there any way to keep the same Netlify deployment URL constant? It's hard to wire up a real domain if the deployment URL is constantly changing. 

Definitely could be a user error, however. I'd love some guidance on how to keep deploying to the same URL, since we can't do continuous development with the repo, I believe. 

Amazing product and have had so much fun building!

**Comment by kc0tlh** [comment]
@matts1213 interesting that it's more reliable from chat...

Either way, we are going to make major changes to how this works to guarantee you can always update the existing deploy. That effort is being tracked in #49
