### ISSUE TITLE
error occured when import project from github

### ISSUE THREAD

**Issue by liujinbang8** [stackblitz/bolt.new#553]
### Describe the bug

error infomation: Cannot destructure property 'appFiles' of 'project' as it is null.
github project infomation: langgenius/dify  https://github.com/langgenius/dify

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/langgenius/dify

### Steps to reproduce

visit github: https://github.com/langgenius/dify
modify website address from  https://github.com/langgenius/dify  to  https://bolt.new/github.com/langgenius/dify
waitting 
error occured

### Expected behavior

visit github: https://github.com/langgenius/dify
modify website address from  https://github.com/langgenius/dify  to  https://bolt.new/github.com/langgenius/dify
waitting 
error occured

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 57054694,
  "usedJSHeapSize": 54626438,
  "jsHeapSizeLimit": 4294705152
}
Username = liujinbang8
Chat ID = d848d38be867
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1812.
