### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by naqu12** [stackblitz/bolt.new#557]
### Describe the bug

错误：无法在“节点”上执行“insertBefore”：要插入新节点的节点不是该节点的子节点。
    至（https://bolt.new/assets/components-g8_Fbz61.js:24:25478）
    在 je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    在 gc（https://bolt.new/assets/components-g8_Fbz61.js:24:27717）
    在 Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    在 gc（https://bolt.new/assets/components-g8_Fbz61.js:24:27709）
    在 Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    在 gc（https://bolt.new/assets/components-g8_Fbz61.js:24:27709）
    在 Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    在 gc（https://bolt.new/assets/components-g8_Fbz61.js:24:27709）
    在 Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-oshgxe

### Steps to reproduce

每次提交都会出现报错

### Expected behavior

不管我怎样生成代码都会出现这些报错信息

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46969370,
  "usedJSHeapSize": 42678770,
  "jsHeapSizeLimit": 4294705152
}
Username = naqu12
Chat ID = 48f20cce82d6
```

**Comment by AriPerkkio** [comment]
Hey @naqu12, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
