### ISSUE TITLE
Half way through it stopped writing in the script and started writing the code in the message

### ISSUE THREAD

**Issue by krazor94** [stackblitz/bolt.new#56]
### Describe the bug

Half way through it stopped writing in the script and started writing the code in the message

![image](https://github.com/user-attachments/assets/d9784a3d-230b-4890-adca-1acb25456576)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-g1hbyc

### Steps to reproduce

i asked it to build a bit of a complex app. 

this was my prompt 

### Expected behavior

create a game developer portfolio with nextjs, typescript shadcn and mongodb, quill.

it should hae featured projects and products on the home page.
their should be a home page, projects, products, contact,  login/register account with mongo db

the projects and products should be stored on the database.

the admin account should have a dashboard to create and edit projects and products

it should have a light and dark theme. and be a modern sleek design

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90835990,
  "usedJSHeapSize": 71795346,
  "jsHeapSizeLimit": 4294705152
}
Username = krazor94
Chat ID = 6a577340c6ab
```

**Comment by Nemikolh** [comment]
Hey @krazor94 ! Thanks for the report!

I think this is the same issue as #26. I'm going to close this one but feel free to follow on the other one to track progress on this front! :raised_hands:
