### ISSUE TITLE
Trying to authenticate and get a token from a REST API on internet does not work

### ISSUE THREAD

**Issue by Kafalk01** [stackblitz/bolt.new#563]
### Describe the bug

I am trying to post to a publically available REST API, to retrieve a login-token. It works when I try it on the web-based version of POSTMAN, but not when I ask BOLT.NEW to develop the code to do it. It seems to get a CORS error and when I asked it to fix the issue it tried to use a CORS proxy server, but that does not work at all.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-i8sfdf

### Steps to reproduce

This is what I asked it to do:
Create a loginpage where I can enter a REST API base url, an Id and a Password. Use the users/login endpoint to retrieve a token. The header key required are:
default-bundle-scope—myit-sb
Content-Type—application/json
X-Requested-By—XMLHttpRequest

The body format is:
{
"id": "<your_user>",
"password": "<your_password>"
}

Provide very detailed debug log information

### Expected behavior

I expect I can login to the REST-API and retrieve a login Token. The code fro posting to the endpoint seems correct and same as I use in POSTMAN

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63533656,
  "usedJSHeapSize": 58883852,
  "jsHeapSizeLimit": 4294705152
}
Username = Kafalk01
Chat ID = 470b176c8904
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking CORS issues [here](https://github.com/stackblitz/bolt.new/issues/3164).
