### ISSUE TITLE
One-click or one-prompt deployment to Android

### ISSUE THREAD

**Issue by mauriciorubio2** [stackblitz/bolt.new#565]
I'd like to have the option to deploy my app to Android in Bolt with a one-click or one-prompt solution that makes my app available in the Google store (Android). The app should be the same as the web build but optimized for mobile, and of course it should use the same backend and database so that users can have a consistent experience and access their data from their mobile device or the web.

**Comment by kc0tlh** [comment]
@mauriciorubio2 this is not currently possible due to Android & Apple store publishing policies AND because bolt only support web languages (not android or ios native languages). 

If you're interested in using Bolt to develop for mobile with Bolt, I recommend looking into NativeScript or one of it's competitors.

**Comment by mauriciorubio2** [comment]
Well Replit has an option for this, so why wouldn't Bolt be able to do this too if it's already a superior product? I opened this as a feature request, so I wasn't expecting this to be done right away, but I would like to think this is in the Roadmap. Being able to deploy from Bolt to iOS and Android. Kind of like you can deploy from Spotify for Podcasters (previously Anchor) to all sorts of distribution channels. If there's something I've learnt in the world of technology is that there is usually a way. You just need to find it. Be great if you re-opened this ticket. I'm pretty sure I'm not the only one interest in getting their web app to  iOS and Android.

**Comment by Klanik58** [comment]
Clicker oyunu
