### ISSUE TITLE
LLMs removing code with comment placeholders......

### ISSUE THREAD

**Issue by devinschumacher** [stackblitz/bolt.new#566]
### Describe the bug

Hilarious (not really) that this is happening but please train your AI to NOT DO THIS. 

it's bad enough to have to deal with this with claude/chatGPT while copy and pasting in but this.... too much 

otherwise im lovin bolt!

cheers

### Link to the Bolt URL that caused the error

https://all-of-them.com

### Steps to reproduce

Have the editor work on a file long enough and it'll do it

### Expected behavior

to not replace the code with comment placeholders.

### Screen Recording / Screenshot

![Screenshot 2024-10-14 at 05 48 01](https://github.com/user-attachments/assets/5343b2a0-6014-4141-9dae-6ba2debae29b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by eliaspizarro** [comment]
// ... (otras funciones permanecen igual)

**Comment by kc0tlh** [comment]
This issue has been resolved! #124

**Comment by duckorangeduck** [comment]
It definitely hasn't!

**Comment by kc0tlh** [comment]
@duckorangeduck please share any recent project URL examples in #124 so we can investigate!
