### ISSUE TITLE
All Chats are gone!

### ISSUE THREAD

**Issue by karimhyahia** [stackblitz/bolt.new#567]
### Describe the bug

This happened the second time, that all my chats are gone and everything that I have built!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-semrok

### Steps to reproduce

Everything gone!

### Expected behavior

All chats are their

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@karimhyahia your projects should be stored in StackBlitz.com > Collections > Bolt

As for chat persistence, this is being tracked in #39
