### ISSUE TITLE
MONEY BACK

### ISSUE THREAD

**Issue by PepeMuniz** [stackblitz/bolt.new#568]
### Describe the bug

THE IA ASSISTAN CRASHED MY WORK SEVERAL TIMES. MAKING TO START FROM SCRATCH EVERY TIME. NEED MY MONEY BACK

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vfolas

### Steps to reproduce

THE BOLT ASSISTANT CRASHED MY WORK EVERY TIME.

### Expected behavior

DO WHAT I SAY IT TO DO.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@PepeMuniz refund requests can be processed with an email request to hello@stackblitz.com, thanks!
