### ISSUE TITLE
Unable to execute a prompt

### ISSUE THREAD

**Issue by N8N-Kitli** [stackblitz/bolt.new#57]
### Describe the bug

I'm unable to execute a prompt and getting this error  "forbiden"

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-e2ktkc

### Steps to reproduce

1. Go to "https://bolt.new/~/sb1-pecard"
2.  Write prompt
3.  Error message:  "forbiden"

### Expected behavior

I tried to execute a prompt, but to no avail. I always got the error message "forbiden"

### Screen Recording / Screenshot

[error.docx](https://github.com/user-attachments/files/17266629/error.docx)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 115813461,
  "usedJSHeapSize": 100646337,
  "jsHeapSizeLimit": 4294705152
}
Username = N8N-Kitli
Chat ID = 0d57e9ee878d
```

**Comment by Nemikolh** [comment]
Hey @N8N-Kitli! There are restrictions on certain countries where Anthropic AI can be used: https://docs.anthropic.com/en/api/supported-regions.

Could you confirm whether or not this is the case for you? If yes, I'm afraid we cannot do anything at this time.

**Comment by N8N-Kitli** [comment]
Hi, I rerun the application, and it worked.  Thanks for the assistance.

Thanks🥰
________________________________

**Comment by samdenty** [comment]
you can track in https://github.com/stackblitz/bolt.new/issues/77

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!

**Comment by thanhnhattran** [comment]
HI team, I also see this error today. I'm from Vietnam! https://prnt.sc/SlBbQOYLis6q
