### ISSUE TITLE
Bolt is not worth money

### ISSUE THREAD

**Issue by mattsterp** [stackblitz/bolt.new#575]
### Describe the bug

Bolt is not worth money buyer beware 

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

Eats up tokens and leaves you with nothing 

### Expected behavior

bolt needs to be taken private and fixed this is not worth paying for yet. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tbatirov** [comment]
Completely agree, it almost feels like they are doing it on purpose by not fixing the occurence of the same error 5-6 times

**Comment by kc0tlh** [comment]
@mattsterp & @tbatirov AI models are certainly limited in their abilities to code and debug errors. Some good usage tips and tricks to workaround that, as well as our efforts to improve token usage efficiency can be found in issue #678. If you're in need of a refund, please reach out to hello@stackblitz.com, and we'll be happy to help!

**Comment by tbatirov** [comment]
[hello@stackblitz.com](mailto:hello@stackblitz.com) is responding with email not found. Responsible customer care would take car of the issue and escalate appropriately. Giving me a general response does not show intention of helping.
