### ISSUE TITLE
Price increase without disclosure?

### ISSUE THREAD

**Issue by mattsterp** [stackblitz/bolt.new#576]
### Describe the bug

when I signed up it was 9 dollars now it says 20 a month.  where in the marketing was this disclosed?

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

my invoice says 9 monthly now its 20 

### Expected behavior

that you notified me if it was a trial period.   

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by mrsunshine** [comment]
I wonder about this drastic change as well

**Comment by mattsterp** [comment]
> I wonder about this drastic change as well

I'm glad to know I'm not the only one to notice.  This product is so half-baked.

**Comment by kc0tlh** [comment]
@mattsterp As a thank you to our earliest adopters, this change does not affect folks who had already signed up when the plan was $9.

Here is where we announced the change: https://x.com/ericsimons40/status/1844551246658798079

For users who are signing up after the price change, it was reflected on the pricing page as well of course.

**Comment by mattsterp** [comment]
It would have been much better if someone explained this to us.
