### ISSUE TITLE
Keep getting An error occured while streaming this message.

### ISSUE THREAD

**Issue by jimbiamp** [stackblitz/bolt.new#577]
### Describe the bug

When using the prompt I get the message "An error occured while streaming this message." and it stops mid-update.  This then breaks the code and makes it unusuable.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tikfnz

### Steps to reproduce

1.  Use the prompt to add any new functionality.  
2.  See it break with an error "An error occured while streaming this message."

### Expected behavior

It to complete updating the file.

### Screen Recording / Screenshot

![Screenshot 2024-10-14 at 10 00 01 AM](https://github.com/user-attachments/assets/e789dfa3-41cb-4ed9-b04f-0b6db54a43fe)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50784906,
  "usedJSHeapSize": 48624362,
  "jsHeapSizeLimit": 4294705152
}
Username = jimbiamp
Chat ID = 37959c88becd
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@jimbiamp thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
