### ISSUE TITLE
DB Connection string working elsewhere but not on StackBlitz

### ISSUE THREAD

**Issue by benspak** [stackblitz/bolt.new#580]
### Describe the bug

Able to connect with MongoDB Compass using the connection string; but not with Bolt / StackBlitz. The connection is whitelisted on the DB server.

### Link to the Bolt URL that caused the error

Bolt's Security Sucks!

### Steps to reproduce

See chat log

### Expected behavior

Connection string for the database to work

### Platform

```
Bolt is also dumping browser versions. Anyone out of date could be targeted. 
```

**Comment by kc0tlh** [comment]
Closing as duplicate of #589
