### ISSUE TITLE
I WANT MY MONEY BACK

### ISSUE THREAD

**Issue by znzmzrijz** [stackblitz/bolt.new#581]
### Describe the bug

It’s not working, having problems all the time, ultra slow, since I paid I haven’t been able to do any progress because of constant problems. 

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

Do basically anything. 

### Expected behavior

Functionality, you are paying to generate blank white board with problems. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by benspak** [comment]
Contact eric@stackblitz.com

**Comment by Jpubli** [comment]
Another here!!

**Comment by ccharade** [comment]
It works wonderfully.

**Comment by kc0tlh** [comment]
@Jpubli @znzmzrijz refund requests are handled through hello@stackblitz.com
