### ISSUE TITLE
Loss of history in chat after refreshing or opening the project from Stackblitz

### ISSUE THREAD

**Issue by dipereira0123** [stackblitz/bolt.new#586]
### Describe the bug

Im not sure if its a bug or the product is not meant to have this functionality, but since its an inconvenience, id like to ask to check:

After closing the chat, the history is lost,  this behavior also happens also if open via StackBliz. 

![image](https://github.com/user-attachments/assets/55461bdf-fc08-4064-bf1f-7009de8afae4)

Is possible to save the chat history?

thanks in Advance!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nfdq5o

### Steps to reproduce

1 - Go to Bolt.new;
2 - Open a previous Chat 

Alternative:

1 - go to StackBlitz;
2 - Go to Collections -> Bolt Collections
3 - Open a Project
4 - Click in the button "Open in Bolt.new | AI"

### Expected behavior

The Bolt.new will open and will import the project, without any history of the conversation

![image](https://github.com/user-attachments/assets/06d7292b-e66a-4df4-9a16-2fd06227ba96)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112384108,
  "usedJSHeapSize": 107628620,
  "jsHeapSizeLimit": 4294705152
}
Username = dipereira0123
Chat ID = b21880f85f77
```

**Comment by JeyZG** [comment]
Buenas tardes, tmb quiero saber como recuperar el historial del chat con el prompt ingresado.

**Comment by kc0tlh** [comment]
This issue and workarounds are being tracked and discussed in #39
