### ISSUE TITLE
Mutliple time of it trying to make the code better, but couldn't

### ISSUE THREAD

**Issue by code-pumpkin** [stackblitz/bolt.new#587]
### Describe the bug

Hey there,

I am kind of annoyed, at the same time its in beta, so this is something which should have been accepted.
But first I had asked it to get me the ham burger menu for all the things, and also recommended to make a navbar.tsx file so that you could have three to four different navfile for different pages which i had on the webapp. Seem to give me a apology and acknowledges that this a better method and nice idea, but tries to do it. But the same thing again and again and I have lost close to 200k tokens just trying to go it. Finally I thought maybe it would understand better if i showcase a photo of the same thing which i wanted in my project, again it acknowledge and does the things, but the same result the hamburger menu isn't showing up

I am not sure what did it do with the code, as I was a bit distracted and didn't see what was the changes made, but seem to be like this is just waste of money, if it is going to act this way, and also the main point of selling was that it would be deployment and have install all the nodemodules and other things in the background. This is so annoying.

I have too much personal data on the chat, so i don't want to share the link, but rather if your team is interested in investing their time in trying to find out, please do let me know i would share the image or maybe the link, only if I know to whom it is shared.

Regards,

Ugandafornigeria@outlook.com

### Link to the Bolt URL that caused the error

https://cantgivethelinkastoomuchpersonaldata.com

### Steps to reproduce

Email me for the link regards

### Expected behavior

I guess i wrote the whole story in the description, as mentioned i was trying to get the hamburger menu working that it, but seem to me that it was kind of going in the wrong track.

### Platform

```
Browser name = Firefox
Full version = 131.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
performance.memory = undefined
Username = uganda
Chat ID = 790675229ae1
```

**Comment by kc0tlh** [comment]
Apologies for the frustrating experience during the beta.

With that in mind, I have collected a ton of awesome tips on how to be more efficient with token usage and get what you need from the AI. Check those out in issue #678.
