### ISSUE TITLE
Comments destroy my app, i need a token refund solution

### ISSUE THREAD

**Issue by eliaspizarro** [stackblitz/bolt.new#588]
### Describe the bug

change your starter proyect, suddenly your code get empty with comments

`
  // ... (el resto del código permanece igual)

  return (
    <App>
      <div className="usuarios-container">
        <Card title={t('users.title')} className="usuarios-card">
          {/* ... (el resto del JSX permanece igual) */}
          <Table 
            columns={columns} 
            dataSource={data} 
            rowKey="id" 
            scroll={{ x: true }} 
            loading={loading}
            pagination={{ 
              responsive: true,
              showSizeChanger: true, 
              showQuickJumper: true,
              showTotal: (total, range) => `${range[0]}-${range[1]} of ${total} items`,
            }}
          />
        </Card>

        {/* ... (el resto del JSX permanece igual) */}
      </div>
    </App>
  );
};`

### Link to the Bolt URL that caused the error

https://bolt.new/~/app-watitas

### Steps to reproduce

start project, chat, and get the bug

### Expected behavior

fill with only changed code

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 182105830,
  "usedJSHeapSize": 163149166,
  "jsHeapSizeLimit": 4294705152
}
Username = eliaspizarro
Chat ID = e71bf68e9c38
```

**Comment by kc0tlh** [comment]
@eliaspizarro We are working on a permanent fix for this issue. In the meantime, follow issue #124 for tips and tricks on how to work around this issue and avoid wasting tokens when it does occur.

If you have billing questions please reach out to hello@stackblitz.com
