### ISSUE TITLE
i want to open existing stackblitz repository or github repository

### ISSUE THREAD

**Issue by u007** [stackblitz/bolt.new#59]
### Describe the bug

i tried to open my existing project, but it states its not possible

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xvslgh

### Steps to reproduce

1. ask : import project from github.com/u007/vue-cms
or 
import from https://stackblitz.com/~/github.com/...

### Expected behavior

open existing project 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 43482859,
  "usedJSHeapSize": 42343187,
  "jsHeapSizeLimit": 4294705152
}
Username = u007
Chat ID = d8cb098b651d
```

**Comment by Nemikolh** [comment]
Hey @u007! 

Just to double-check, you want to open a private repository?

We have planned to add support for github repositories in the near future. We'll keep you posted! :raised_hands:

**Comment by u007** [comment]
oh right, due to license?

**Comment by samdenty** [comment]
you can open stackblitz projects at https://bolt.new/~/PROJECT_SLUG and repositories at https://bolt.new/~/github.com/owner/repo

**Comment by lipecss** [comment]
> Você pode abrir projetos StackBlitz em https://bolt.new/~/PROJECT_SLUG e repositórios em https://bolt.new/~/github.com/owner/repo

I'm trying to open the repository, but it says I can't access it 
![image](https://github.com/user-attachments/assets/59e0a8cf-9223-475b-ab46-297fffd9deba)
