### ISSUE TITLE
Lost the app I build yesterday

### ISSUE THREAD

**Issue by EHC1972** [stackblitz/bolt.new#592]
### Describe the bug

For some reason when I logged in today the app I build yesterday is now gone.
My previous conversations are gone!

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Log in
Go to my previous chats ...

### Expected behavior

I should be able to see all my projects/ chats in there...

### Platform

- OS: [e.g. macOS
- Browser: Chrome
- Version: Version 129.0.6668.101 (Official Build) (arm64)

**Comment by kc0tlh** [comment]
@EHC1972 instructions in loading existing chats can be found in #39
