### ISSUE TITLE
wasting tokens with massive errors

### ISSUE THREAD

**Issue by flaturtha** [stackblitz/bolt.new#595]
I'm trying to test this out and see how it works; however, it keeps making fundamental errors and forcing me to run and rerun prompts to error check so i run out of tokens. I'm certainly not going to pay for this kind of a waste of my time so I can't legitimately test it because I never get past the most basic set up and errors. Nice idea. Seems cool. Bring it back when it works.

**Comment by mawiskored** [comment]
same issue. but no help from support.

**Comment by flaturtha** [comment]
@mawiskored I'm trying a local version. Found a YT vid of a guy who forked it to use any LLM. Check it out: https://github.com/coleam00/bolt.new-any-llm

I'm just getting it set up to use Ollama and deepseek-coder-v2. We'll see if that works better!

**Comment by GUSGUS33** [comment]
same problem. 

Also after errors I had to remind him what we were doing, giving intermittent errors, as I make requests.

**Comment by mawiskored** [comment]
> @mawiskored I'm trying a local version. Found a YT vid of a guy who forked it to use any LLM. Check it out: https://github.com/coleam00/bolt.new-any-llm
> 
> I'm just getting it set up to use Ollama and deepseek-coder-v2. We'll see if that works better!

Thank you for the information. Anything should be better than what we currently have.

**Comment by kc0tlh** [comment]
@mawiskored @flaturtha @GUSGUS33 This is being addressed in #678 along with lots of tips and tricks for better results today. Stay tuned!

**Comment by flaturtha** [comment]
👍 Awesome!Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Alexander Berger ***@***.***> Date: 10/22/24  4:08 PM  (GMT-06:00) To: "stackblitz/bolt.new" ***@***.***> Cc: Rich Cook ***@***.***>, Mention ***@***.***> Subject: Re: [stackblitz/bolt.new] wasting tokens with massive errors (Issue
  #595) 
@mawiskored @flaturtha @GUSGUS33 This is being addressed in #678 along with lots of tips and tricks for better results today. Stay tuned!
