### ISSUE TITLE
files are emptied after creation of the project

### ISSUE THREAD

**Issue by yilmazdurmaz** [stackblitz/bolt.new#6]
### Describe the bug

when creating multiple files, contents of the files other than the last one created are emptied.

I thought the content was permanently removed, but fortunately "Ctrl+Z" undo this removal.

It is, however, very annoying and most people will assume it is a permanent deletion.

### Link to the Bolt URL that caused the error

do not matter

### Steps to reproduce

1- go to "bolt.new"
2- try a long prompt so it will create a multi-file project.
3- watch every file being created one by one
4- after the last file is written, open al other files to see them being empty.
and 
5- press undo to undo deleted file contents.

### Expected behavior

file contents are not deleted 

### Platform

- Windows 10 22H2 64bit up-to-date
- Edge 129.0.2792.65 (Official build) (64-bit) up-to-date

**Comment by samdenty** [comment]
This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back
