### ISSUE TITLE
Chat history is gone

### ISSUE THREAD

**Issue by joe-shenouda** [stackblitz/bolt.new#60]
### Describe the bug

After making a project, I went back later to check my prompts, they were gone it seems

### Link to the Bolt URL that caused the error

general

### Steps to reproduce

make a project - leave - go back to it - look for your prompts

### Expected behavior

I expected to scroll back and find my chat history and iterations

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Nemikolh** [comment]
Hey @joe-shenouda ! Chat is not persisted at the moment.

We're tracking this issue in #39. Feel free to subscribe to that issue if you want to be informed when this will be added!
