### ISSUE TITLE
How to buy tokens for users who are on $9 plan

### ISSUE THREAD

**Issue by mohammeddyousuf** [stackblitz/bolt.new#600]
### Describe the bug

How to buy tokens for users who are on $9 plan

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

How to buy tokens for users who are on $9 plan

### Expected behavior

How to buy tokens for users who are on $9 plan

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59853644,
  "usedJSHeapSize": 57701092,
  "jsHeapSizeLimit": 4294705152
}
Username = mohammeddyousuf
Chat ID = d008a54c1358
```

**Comment by kc0tlh** [comment]
This feature has been shipped! You will find it in the settings> token pane, in the lower left-hand corner of the app.
