### ISSUE TITLE
Token consumption. 

### ISSUE THREAD

**Issue by Jpubli** [stackblitz/bolt.new#603]
### Describe the bug

This is a serious claim on the failures of Bolt.new. When building an app the AI could make mistakes (totally understandable). They way the app is running causes that any simple change rewrite the full code and eventually cause malfunctions and/or UI changes that force the user to reprompt. 
The case is that buiding a simple app consumes millions of tokens because bolt needs to recode the full app over and over. I´ve spent over 7.000.000 tokens just because of the senseless prcedures and trying to fix errors for made changes on things that were functioning ok before. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zjwbxm

### Steps to reproduce

Add a filter to the page were created documents are listed

### Expected behavior

I expected to simply add it 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by mawiskored** [comment]
I have the same issue and they don't respond or help. I asked for help 1 week ago.

**Comment by kc0tlh** [comment]
@Jpubli @mawiskored I appreciate your patience during this very busy beta period! 

We have compiled a ton of tips on how to increase token consumption efficiency through prompting strategies and other user-driven means. You can check all of those out in #678, as well as follow along on progress updates we will be posting as we make application changes to increase token usage efficiency on our end as well.

Best of luck with your projects!
