### ISSUE TITLE
CUSTOM PRODUCT

### ISSUE THREAD

**Issue by GUSGUS33** [stackblitz/bolt.new#609]
### Describe the bug

Error: No se pudo ejecutar 'insertBefore' en 'Nodo': El nodo antes del cual se insertará el nuevo nodo no es un hijo de este nodo.
    en a (https://bolt.new/assets/components-g8_Fbz61.js:24:25478)
    en je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    en gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27717)
    en Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    en gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    en Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    en gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    en Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    en gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    en Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cesfpw

### Steps to reproduce

The error occurs intermittently, as I make requests.

### Expected behavior

AS I ADVANCE IT THROWS ME NODE ERRORS AND I HAVE TO START AGAIN, WHEN IT COMES BACK IT HAS LOST MANY FUNCTIONALITIES.

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 46771873,
  "usedJSHeapSize": 41101361,
  "jsHeapSizeLimit": 2172649472
}
Username = gusgus33
Chat ID = 2fc429a9275e
```

### Additional context

I want to inform that during all Sunday I have created an app where step by step it was growing, but today it has begun to become distorted and forget what it was doing, losing many functionalities.

I had to remind him that we were doing a project for woocommerce because he had forgotten and was creating for another platform.

In addition to giving me the NODO errors.

IS THERE A POSSIBILITY TO GO BACK? HISTORY?

**Comment by AriPerkkio** [comment]
Hey @GUSGUS33, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
