### ISSUE TITLE
Auto AI improve creates [object Object][object Object]

### ISSUE THREAD

**Issue by joe-shenouda** [stackblitz/bolt.new#61]
### Describe the bug

When I used auto optimize prompt, it created the enhanced prompt and added: [object Object][object Object]

### Link to the Bolt URL that caused the error

general

### Steps to reproduce

Write a prompt, auto enhance it and see it it adds [object Object][object Object] to the newly created prompt

### Expected behavior

Auto optimize does not add [object Object][object Object] in the end of the newly optimized prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Nemikolh** [comment]
Hey! Thanks for the report! This issue has now been fixed.
