### ISSUE TITLE
Generated a crap ton, but failed to load it into StackBlitz 

### ISSUE THREAD

**Issue by benspak** [stackblitz/bolt.new#612]
### Describe the bug

Also.. This message didn't complete its response..

### Link to the Bolt URL that caused the error

Look it up. 

### Steps to reproduce

Run the prompt

### Expected behavior

To load into Stackblitz and complete the request

### Platform

```
Browser name = Chrome
```

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue and is being tracked here: #1073.
