### ISSUE TITLE
npx netlify deploy --build

### ISSUE THREAD

**Issue by ccharade** [stackblitz/bolt.new#619]
### Describe the bug

npx netlify deploy --build built site, but it won't deploy to netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-astro-blog-jkemq2

### Steps to reproduce

![image](https://github.com/user-attachments/assets/798c9b39-ec00-4929-8340-c8a3d66b4608)

### Expected behavior

deploy site to netlify

### Screen Recording / Screenshot

![Screenshot 2024-10-15 152738](https://github.com/user-attachments/assets/e0b51ee7-71b6-4ae1-8b33-33f760ff0811)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 264023717,
  "usedJSHeapSize": 254695961,
  "jsHeapSizeLimit": 4294705152
}
Username = groundworkd
Chat ID = 9ea84cb3651c
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by ccharade** [comment]
no reply to emails. refund me. service doesn't work!!

**Comment by kc0tlh** [comment]
@ccharade Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499 

Refund requests can be directed to hello@stackblitz.com.

**Comment by ccharade** [comment]
5th time requesting refund because Bolt is not ready for prime time.

**Comment by kc0tlh** [comment]
@ccharade as you can see below, this was the first refund request email we have received from you:
![image](https://github.com/user-attachments/assets/322d3f87-912d-4a00-9aa4-81efd05b30e0)

✅ Refund issued successfully
