### ISSUE TITLE
All my code from free (before upgrading) just disappeared

### ISSUE THREAD

**Issue by mark1inla** [stackblitz/bolt.new#623]
### Describe the bug

All code disappeared upon paying you money and returning to project. Is my project gone?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-s2vu2l

### Steps to reproduce

1) Work on an idea; 2) run out of free tokens; 3) click to pay you money; 4) lose everything

### Expected behavior

I expected to return to my work in progress!!!!

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116733781,
  "usedJSHeapSize": 101102165,
  "jsHeapSizeLimit": 4294705152
}
Username = mark1inla
Chat ID = c163ffc70971
```

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
