### ISSUE TITLE
Deploy this application.

### ISSUE THREAD

**Issue by actus7** [stackblitz/bolt.new#630]
### Describe the bug

~/project 6s
❯ npx next build
 ✓ Creating an optimized production build   
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types .Failed to compile.

./app/api/cases/route.ts:2:10
Type error: Module '"@prisma/client"' has no exported member 'PrismaClient'.

  1 | import { NextResponse } from 'next/server'
> 2 | import { PrismaClient } from '@prisma/client'
    |          ^
  3 | 
  4 | const prisma = new PrismaClient()
  5 | 

~/project 36s
❯ npx prisma generate

prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/08713a93b99d58f31485621c634b04983ae01d95/debian-openssl-1.1.x/libquery_engine.so.node.sha256 failed, reason: socket hang up

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-b4kmcj

### Steps to reproduce

1. Click to Deploy

### Expected behavior

~/project 6s
❯ npx next build
 ✓ Creating an optimized production build   
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types .Failed to compile.

./app/api/cases/route.ts:2:10
Type error: Module '"@prisma/client"' has no exported member 'PrismaClient'.

  1 | import { NextResponse } from 'next/server'
> 2 | import { PrismaClient } from '@prisma/client'
    |          ^
  3 | 
  4 | const prisma = new PrismaClient()
  5 | 

~/project 36s
❯ npx prisma generate

prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/08713a93b99d58f31485621c634b04983ae01d95/debian-openssl-1.1.x/libquery_engine.so.node.sha256 failed, reason: socket hang up

### Platform

```
Browser name = Chrome
Full version = 127.0.0.0
Major version = 127
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 OPR/113.0.0.0
performance.memory = {
  "totalJSHeapSize": 64672710,
  "usedJSHeapSize": 57221418,
  "jsHeapSizeLimit": 4294705152
}
Username = actus7
Chat ID = 52d371b913a0
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
Tracking all deployment related bug fixes in issue #499
