### ISSUE TITLE
My project is lost

### ISSUE THREAD

**Issue by rebusweb** [stackblitz/bolt.new#633]
### Describe the bug

I cannot restore my project - seems like no files were stored.
Deployed project for reference: https://benevolent-beijinho-6aa23d.netlify.app/

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5tg95q

### Steps to reproduce

1. Go to project url
2. Try to import files
3. No files are being imported

### Expected behavior

Project files should be imported.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 34853470,
  "usedJSHeapSize": 34159114,
  "jsHeapSizeLimit": 4294705152
}
Username = rebusweb
Chat ID = 7c7bf29066a1
```

**Comment by fil146** [comment]
I have the same issue here.
