### ISSUE TITLE
I deployed my project and my codes had been deleted.

### ISSUE THREAD

**Issue by mondbarde** [stackblitz/bolt.new#635]
### Describe the bug

I deployed my project and my codes had been deleted.
The preview screen was empty and I commanded that 'the preview is blank. show my web app in preview'
Then bolt made up some stupid web app Immediately that I've never seen.
What a stupid bug.
I lost the whole works for 2 days.

deployed Original work : https://beautiful-llama-bde7b4.netlify.app/
stupid work bolt made up : https://bolt.new/~/bolt-nextjs-shadcn-cvgxmz

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-cvgxmz

### Steps to reproduce

I deployed my project and my codes had been deleted.
The preview screen was empty and I commanded that 'the preview is blank. show my web app in preview'
Then bolt made up some stupid web app Immediately that I've never seen.
What a stupid bug.
I lost the whole works for 2 days.

### Expected behavior

Just deploying my web app without deleting it!

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
