### ISSUE TITLE
With new update, just your information

### ISSUE THREAD

**Issue by cerarslan** [stackblitz/bolt.new#637]
### Describe the bug

I'm importing your repository into Bolt. This may take a moment as I set everything up. Once it's ready, you'll be able to explore and interact with your code.

Importing Github Repository

cerarslan/MyOutFood-main
Cannot destructure property 'appFiles' of 'project' as it is null.
An unknown error occured while running an action.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/cerarslan/MyOutFood-main

### Steps to reproduce

While try to create new chat

### Expected behavior

Compile the project.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 212137038,
  "usedJSHeapSize": 200191922,
  "jsHeapSizeLimit": 4294705152
}
Username = cerarslan
Chat ID = c36c50283c3a
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1812.
