### ISSUE TITLE
Make sure the AI isn't summarizing/cutting corners like "keep the previous code"

### ISSUE THREAD

**Issue by jlcd** [stackblitz/bolt.new#64]
### Describe the bug

After a long chat, the AI made changes to the code and added the well known "/* (... keep the previous code ...) */" comments.

This happens often with ChatGPT/Claude etc.

It then saved the file with these comments and with actual functionality removed.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ozmeae

### Steps to reproduce

Talk long enough with the AI that will eventually summarize/cut code.

### Expected behavior

Always have the full code output, without comments stating we should "keep the previous code" or similar.

### Platform

- OS: Windows 11
- Browser: Brave
- Version: [Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by Nemikolh** [comment]
Hey @jlcd ! This is pretty frustrating indeed!

We're tracking this internally. You can follow #124 to get notified when we've resolved this issue.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
