### ISSUE TITLE
Project has been destroyed after 5 prompts

### ISSUE THREAD

**Issue by gabrielstuff** [stackblitz/bolt.new#642]
### Describe the bug

First : you made an incredible work. 👏

Was prompting for a VueJS project and after few adjustment, it throw an error which I did not capture but made the whole Bolt.new crash with a Typescript error.

After reloading the error was : 

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/c854b60a-f13f-477a-bd56-ff7b4694a269">

And now, I simply can't open the bolt.

Thanks !

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fnth7j

### Steps to reproduce

1. Create a vue project
2. Ask for UI modification
3. Keep asking for UI modification
4. It will eventually break

### Expected behavior

1. Should not break

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109457977,
  "usedJSHeapSize": 106810105,
  "jsHeapSizeLimit": 4294705152
}
Username = gabrielstuff
Chat ID = 95abea2611f4
```

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50

**Comment by gabrielstuff** [comment]
Thanks @samdenty for the clear reply ! Bolt is awesome.
