### ISSUE TITLE
Cant open in StackBlitz

### ISSUE THREAD

**Issue by vemas23** [stackblitz/bolt.new#644]
### Describe the bug

Every time i press the Open in Stackblitz button StackBlitz opens but none of the items art there

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jxum8n

### Steps to reproduce

1. Go to my link 2. Press the Open in Stackblitz button

### Expected behavior

It opening in stackblitz and i can acces the items

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/3f0217cf-0ce2-459b-bd28-79b61c91708f)

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63547555,
  "usedJSHeapSize": 59853743,
  "jsHeapSizeLimit": 4294705152
}
Username = vemas23
Chat ID = 215ad03a7639
```

**Comment by vemas23** [comment]
The bolt link dosent work anymore so it cant be reporduce (dosent show files in bolt like it does in stackblitz)

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
