### ISSUE TITLE
URGENT: Bolt erased 6.5M of my tokens! Please help

### ISSUE THREAD

**Issue by Terman7a** [stackblitz/bolt.new#648]
### Describe the bug

Last night Bolt froze on me and I had to dump my browser. Logged in this am and 6.5 million of my tokens are gone and it says Ive run out. I assure you I did not. I've bought alot of tokens from you guys (which is a very confusing process by the way) Can someone check my account or look at some logs to verify what I am saying and restore the 6.5M i had had left please?  mynsbma@gmail.com is the account. The project loaded at the time of the freeze was "ULTRA LINK Powered By Growth park"

### Link to the Bolt URL that caused the error

my account

### Steps to reproduce

Logged in this am and 6.5 million of my tokens are gone and it says Ive run out. I assure you I did not.

### Expected behavior

Last night Bolt froze on me and I had to dump my browser. Logged in this am and 6.5 million of my tokens are gone and it says Ive run out. I assure you I did not. I've bought alot of tokens from you guys (which is a very confusing process by the way) Can someone check my account or look at some logs to verify what I am saying and restore the 6.5M i had had left please?  mynsbma@gmail.com is the account. The project loaded at the time of the freeze was "ULTRA LINK Powered By Growth park"

### Screen Recording / Screenshot

Last night Bolt froze on me and I had to dump my browser. Logged in this am and 6.5 million of my tokens are gone and it says Ive run out. I assure you I did not. I've bought alot of tokens from you guys (which is a very confusing process by the way) Can someone check my account or look at some logs to verify what I am saying and restore the 6.5M i had had left please?  mynsbma@gmail.com is the account. The project loaded at the time of the freeze was "ULTRA LINK Powered By Growth park"

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Last night Bolt froze on me and I had to dump my browser. Logged in this am and 6.5 million of my tokens are gone and it says Ive run out. I assure you I did not. I've bought alot of tokens from you guys (which is a very confusing process by the way) Can someone check my account or look at some logs to verify what I am saying and restore the 6.5M i had had left please?  mynsbma@gmail.com is the account. The project loaded at the time of the freeze was "ULTRA LINK Powered By Growth park"

**Comment by chefbc2k** [comment]
If they don't get back to you and you need something right away, just let me know. I might have enough to help you out.

**Comment by Terman7a** [comment]
Hi, Terence Mcmahon here.  Thank you for responding to me Well no they
haven't responded at all. So if you're able to help me I would be grateful.
I was just finishing my software project after a 10 day build sand then the
whole platform froze on me so I hard to hard reboot essentially and when I
logged back in the 6.5M tokens I had left out of the 30 or 40 M I had
bought were just wiped. Now are you with the company or work with them?
adn yes, if you were able to help me out I would be extremely grateful as
their support ticket system just isn't clear.

Thank Much!
Terence mcmahon
***@***.***

**Comment by chefbc2k** [comment]
No, I'm just a guy who saw your post and wanted to help. Do you still need assistance with tokens? I could add you to my organization, and then you could complete your project.

**Comment by valleteclab** [comment]
> Não, sou apenas um cara que viu sua postagem e queria ajudar. Você ainda precisa de ajuda com tokens? Eu poderia adicioná-lo à minha organização e, em seguida, você poderia concluir seu projeto.

If you could include me in your company group, I would appreciate it;

**Comment by valleteclab** [comment]
loamesilva@valleteclab.com.br

**Comment by kc0tlh** [comment]
@Terman7a please reach out to hello@stackblitz.com for support on user specific billing issues. We can get this sorted for you there, thanks!
