### ISSUE TITLE
Writing the code in the chat not in the ide

### ISSUE THREAD

**Issue by younann** [stackblitz/bolt.new#65]
### Describe the bug

I give the app a long prompt that include a lot of pages , it started to create the pages in the ide but then its crop it and continue to write the code in the chat 
![Screenshot 2024-10-05 at 21 50 31](https://github.com/user-attachments/assets/7161fa5a-e5d5-4697-b238-f5fa92f528a0)
![Screenshot 2024-10-05 at 21 50 45](https://github.com/user-attachments/assets/e9de760a-9f31-4d03-b199-f17fa8d929ea)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kjesqc

### Steps to reproduce

1. add long prompt that created more than 4 pages 
2. the code started in. the ide 
3. the code started to write in the chat

### Expected behavior

to continue in the ide 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 167459790,
  "usedJSHeapSize": 151555178,
  "jsHeapSizeLimit": 4294705152
}
Username = younann
Chat ID = 6470b4c8f6a9
```

**Comment by Nemikolh** [comment]
Hey @younann! Thanks for creating this issue!

We're tracking this internally. You can follow #26 to be notified of progress on this issue.
