### ISSUE TITLE
<!-- Rest of the slides content remains the same --> should be ELIMINATED

### ISSUE THREAD

**Issue by joe-shenouda** [stackblitz/bolt.new#66]
### Describe the bug

WHen AI responds with code, it should never respond with "" because this kills the code and the new result.

### Link to the Bolt URL that caused the error

general

### Steps to reproduce

create an initial app for example - see the result - ask for changes - if you're lucky, it will do "" and cut the code, resulting in losing alot of detail of course. The System Prompt should include: "NEVER respond with , but always write out the full code" something like this.

### Expected behavior

When asking for changes, AI should write out the full code, the new AND the old code, so it does not "dissapear".  is unnacceptable and should be amended through the system prompt of Bolt.new

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Nemikolh** [comment]
Hey @joe-shenouda!

We're tracking this internally. You can follow #124 to be notified of when we're going to have a fix for this.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
