### ISSUE TITLE
Unable to deploy my website

### ISSUE THREAD

**Issue by j-q-khan** [stackblitz/bolt.new#660]
### Describe the bug

An unknown error occured while running an action. :\

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qsmj6q

### Steps to reproduce

Just try to deploy

### Expected behavior

Successful Deployment

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/d75409da-81a3-4296-accf-329d86248587)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74673762,
  "usedJSHeapSize": 68371054,
  "jsHeapSizeLimit": 4294705152
}
Username = j-q-khan
Chat ID = 58b7f6591b1a
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
