### ISSUE TITLE
A question to PRO PLAN users

### ISSUE THREAD

**Issue by Filippo295** [stackblitz/bolt.new#661]
Guys there was this problem where people buying the pro plan finished theyr tokens in a matter of 1 or 2 hours.

is it still the case or they fixed the token consuption? i mean now that it is 20$ it is even more important that this issue is solved, i am not going to upgrade to pro until i know for sure.

**Comment by kc0tlh** [comment]
@Filippo295 there was a bug that was affecting some users, where their tokens would indicate that they were exhausted when they actually had more to use. This bug has been resolved.

You can now track token usage in Settings > Tokens.

We also launched higher tier plans that include more tokens for heavy usage.

Finally, issue #678 has tons of tips on how to be more efficient with your token usage.

Hope that helps!
