### ISSUE TITLE
you lost my website

### ISSUE THREAD

**Issue by Showmeyourland** [stackblitz/bolt.new#663]
### Describe the bug

had a website and you lost it. 

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Leave the site and come back

### Expected behavior

No idea i don't code

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

i would like a refund on the credits at least.

**Comment by kc0tlh** [comment]
@Showmeyourland you should be able to load your project using the instructions in #39
