### ISSUE TITLE
Add an option to delete recently made changes. AI often gets confused and it's hard to revert back to a previous state

### ISSUE THREAD

**Issue by staszek-arbuz** [stackblitz/bolt.new#664]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kc0tlh** [comment]
@staszek-arbuz thanks for the feedback. This has shipped:
https://x.com/stackblitz/status/1844839379270836266
