### ISSUE TITLE
The claim URL is not working for me after deploying to Netlify

### ISSUE THREAD

**Issue by marcfest** [stackblitz/bolt.new#665]
### Describe the bug

The claim URL is not working for me after deploying to Netlify

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ynpgyx

### Steps to reproduce

Click the claim URL

### Expected behavior

On Netflify, the imported app should show up. It's not. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 48689243,
  "usedJSHeapSize": 46927971,
  "jsHeapSizeLimit": 4294705152
}
Username = marcfest
Chat ID = a64340da3ac6
```

**Comment by madson** [comment]
I'm not getting the claim URL after a deployment. I'm guessing that's related to this issue. Thanks, marcfest, for opening up this issue.

**Comment by fizex** [comment]
Same here. I tried to guess the URL structure and even asked asked Bolt for it but it gave me an incorrect structure by the looks of things https://app.netlify.com/sites/[site-name]/claim didn't work for me :(

**Comment by vstoms** [comment]
Same issue here!

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2020
