### ISSUE TITLE
Previous work has diapered Pro 50 sub scriber 

### ISSUE THREAD

**Issue by johnthreedie** [stackblitz/bolt.new#666]
### Describe the bug

All of my previous work in the chat history has dissapeared, this has taken considerable time and tokens to build.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6bsqif

### Steps to reproduce

Go to your chat.
There is no previous chat from my latest project

### Expected behavior

chat history with my project is available to click

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50534078,
  "usedJSHeapSize": 49094438,
  "jsHeapSizeLimit": 4294705152
}
Username = johnthreedie
Chat ID = 26a77fc93162
```

**Comment by kc0tlh** [comment]
@johnthreedie your work should be stored here: StackBlitz.com > Collections tab > Bolt Collection. If not, please email hello@stackblitz.com as this would be a serious bug that we would work with you to look into ASAP!

If your projects ARE there, then you can reference #39 for more info on Chat Persistence in general, and coming improvements.

**Comment by johnthreedie** [comment]
Thank you, This resolved the issue.
