### ISSUE TITLE
Npm start does not work 

### ISSUE THREAD

**Issue by Frankystan** [stackblitz/bolt.new#667]
### Describe the bug

Npm start does not work . As son as I open my project with Bolt...it does not run, so I cannot use the IA in my project

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-mw5kih

### Steps to reproduce

From my Stackblitz project a press "Open in Bolt.new" button.
In bolt.new , on the left side, the log info indicates that install dependencies and start application FAILS.
And that's it

### Expected behavior

Run the application for using the  new AI .

### Screen Recording / Screenshot

![bolt new issue](https://github.com/user-attachments/assets/2d5fb178-0ca9-462a-847c-00c8105d328d)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45160230,
  "usedJSHeapSize": 42886166,
  "jsHeapSizeLimit": 4294705152
}
Username = Frankystan
Chat ID = f7a9b01dc9ed
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
