### ISSUE TITLE
Auto fix bug feature doesn't work if using something like vue router

### ISSUE THREAD

**Issue by TheWebTech** [stackblitz/bolt.new#671]
### Describe the bug

Vue router causes the auto fix suggestion to be useless because it thinks the issues are in the router itself not the components.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kmklpa

### Steps to reproduce

create an app that uses vue router. 
A vue component within the router component has an issue. 
The bot says hey there's a bug do you want me to fix it? 
Hit the button, it will misdiagnose the issue, do something then you'll get an error still since it didn't address the issue.

### Expected behavior

It should ideally be able to tell that the error was in the contained file as that's what shows in the UI, that way it can actually resolve the relevant issue.

### Platform

- OS: Windows
- Browser: Arc

**Comment by kc0tlh** [comment]
@TheWebTech This may just be a limitation of the AI model at the moment. I recommend a more direct manual prompting strategy to address these types of issues.

**Comment by TheWebTech** [comment]
Adding some clarity. I actually dont think the issue is the LLM. It seemed like the actual stack trace error message wasn't provided to the LLM only a surface level vue error. So it just kept rewriting unrelated code.

**Comment by kc0tlh** [comment]
Mmm interesting.

@samdenty @SamVerschueren @d3lm tagging ya'll for awareness and to factor this into the work we're doing on error handling
