### ISSUE TITLE
Looking for refund

### ISSUE THREAD

**Issue by yrkh** [stackblitz/bolt.new#673]
Hello,

Please cancel my subscription and provide a refund—the Bolt. New app is not prod-ready, and the generated Next.js app is full of errors.

Thank you.

**Comment by ccharade** [comment]
Same here.

**Comment by ccharade** [comment]
They still haven't replied to me about anything.

**Comment by kc0tlh** [comment]
@ccharade has been refunded.
@yrkh please email hello@stackblitz.com for refund requests, thanks!

**Comment by utibe-ettebong** [comment]
I sent an email for a refund too, haven't heard from them.
I've successfully repeated the same task and prompt for about 15 to 20 times with the same result, after getting a message about successfully implementing the changes, which isn't true. Ended up wasting millions of tokens

**Comment by ccharade** [comment]
Hi Utibe, what a waste of time!  I have been told I am being refunded. When it shows up on my bank statement, I'll post an update.

**Comment by vklonis** [comment]
Same here. asked for a refund in the above email. The tool is no near close production level tool. It's absolute garbage in terms of code it produces. lost 3 days trying to make it work. keeps giving me crap. i followed every best practice out there

**Comment by kc0tlh** [comment]
@utibe-ettebong 
<img width="672" alt="image" src="https://github.com/user-attachments/assets/9b96fdf2-338c-4aaf-8808-a9eb18a5a18a">

**Comment by kmlacr** [comment]
Refund please too. İ get maximum tokens limit error i bought 200 dollar package. I cant develop waste of time

**Comment by ecat8888** [comment]
I want tooo..
200$ packages...but bolt..is not ready...

**Comment by moleqnap** [comment]
The below mail was sent to you on 30.11.2024


I would like to inform you that I did not intend to continue using your subscription service for the new term. However, as I did not cancel the subscription in time, an amount of [20 usd ] has been deducted from my account.

I kindly request your consideration in this matter and ask for a refund of the charged amount. Please let me know if any further information is required to process my request.

Thank you in advance for your understanding and support.

**Comment by roytmanpiccoli** [comment]
Hello, I hope this message finds you well. I am writing to request a refund for a subscription charge that was applied to my account in error. But no one return information.

**Comment by novianbiz** [comment]
> I sent an email for a refund too, haven't heard from them. I've successfully repeated the same task and prompt for about 15 to 20 times with the same result, after getting a message about successfully implementing the changes, which isn't true. Ended up wasting millions of tokens

same here, very wasting.

**Comment by roytmanpiccoli** [comment]
I am writing to express my concern regarding the lack of response to my refund request sent over a month ago. Despite my detailed request on December 16, 2024, including all relevant payment details, I have not received any reply or confirmation.

Here is a summary of the refund request:

Receipt Number: 2161-3949
Invoice Number: ABDC7009-0002
Amount: US$50.00
Payment Date: December 16, 2024
Payment Method: Card ending in 3331
I kindly request an update on the status of my refund. Your prompt response would be greatly appreciated, as this delay has been frustrating.

Best regards,

**Comment by soareiaq** [comment]
Hello @kc0tlh @,

I am requesting a full refund for my StackBlitz Pro subscription (invoice # 253E71CE0002) that was automatically renewed on February 1, 2025.

Details:
Receipt Number: 22126483
Payment Date: February 1, 2025
Amount Charged: $20.00
Service Period: February 1, 2025 to March 1, 2025
Billing Email: isaquevieirasoares@gmail.com

Reason for Refund:
The subscription was automatically renewed, but I did not use the Pro service during the billing period. I would like to cancel the subscription immediately to avoid future charges.

Please let me know how to proceed or if additional information is needed.

Thank you!

**Comment by zivatts** [comment]
Same here as above complaints! 

Truly frustrating the lack of transparency and communication.

Please respond to my emails from "zachary@scaleandgrow.io" about a refund (I never upgraded my account from free plan and was some how placed on the pro 50 plan!). 

Thanks kindly, 
Zachary

**Comment by amamdouheg90** [comment]
Same here, they didn't mention its not ready to deploy Python / fastapi and alerts for that, so wasting all tokens and finally discovering that, please refund

**Comment by Liberty-Chris** [comment]
It's a shame that people are having to resort to GitHub comments for customer service. I have emailed at least twice from  cyphrpool@gmail.com and no response. My next step is dispute with credit card company @kc0tlh

**Comment by saudinccam** [comment]
Kindly refund my money. saudinccam@gmail.com
