### ISSUE TITLE
Missing Chat

### ISSUE THREAD

**Issue by ashrafmunim** [stackblitz/bolt.new#679]
### Describe the bug

why the chat was not save?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3qkb8s

### Steps to reproduce

https://[bolt.new/~/sb1-3qkb8s](https://bolt.new/~/sb1-3qkb8s) is gone

### Expected behavior

it should be listed on the left menu

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c4b7864a-aa94-4d66-aaa6-3e76554a440d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Sa-ar** [comment]
I had the same issue. had a project, tried to open it in StackBlitz and than nothing was saved and it opened an empty project on StackBlitz and now I have no chat or a project

**Comment by munivinayk** [comment]
I had the same issue. However thanks to github sync, i still have the project in stackblitz. But i dont know how to pull this project back to the chat and modify and optimise this project.

**Comment by EHC1972** [comment]
Same issue

**Comment by ranrahav** [comment]
Sane issue

**Comment by kc0tlh** [comment]
@ashrafmunim, @Sa-ar, @munivinayk, @EHC1972 info on how to open old chats can be [found here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671 ) along with our progress on implementing chat persistence in #39
