### ISSUE TITLE
Saving Chat history

### ISSUE THREAD

**Issue by siamcomm** [stackblitz/bolt.new#683]
**Is your feature request related to a problem? Please describe:**

After saving my code and going back into Bolt, I am frustrated that I cannot see what I have asked the AI to do so far. This would provide me some context on where I was when I stopped last session.

**Describe the solution you'd like:**

It would be nice to have a "History" or "Chat Session" menu to view what was asked relating to a specific repository or code base.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by imUNIKKK** [comment]
ask bolt to make a page with all information you send to him in a private route

**Comment by kc0tlh** [comment]
This issue and workarounds are being tracked and discussed in #39
