### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by PiotrStyla** [stackblitz/bolt.new#684]
### Describe the bug

Deploy application to Netlify

npx vite build
netlify
I've initiated the deployment process to Netlify. The build command npm run build will be executed, and the contents of the dist directory will be deployed. Now, let's wait until the site is live and retrieve the deployment status.

An error occured while streaming this message.
![image](https://github.com/user-attachments/assets/e854869c-c81d-4906-a1c5-973b7dc7e13b)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rnsaon

### Steps to reproduce

1. Clicked Deploy

### Expected behavior

Clicked Deploy

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/7abd3b70-8d98-446d-9a38-043ee0c315b3)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61182837,
  "usedJSHeapSize": 56429189,
  "jsHeapSizeLimit": 4294705152
}
Username = PiotrStyla
Chat ID = dd34062d8c4b
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
This issue is being tracked in Issue #1022.
