### ISSUE TITLE
It will always change so much

### ISSUE THREAD

**Issue by obey24com** [stackblitz/bolt.new#691]
### Describe the bug

What often occurs is that it will change much more than I have asked for than it will just miss a lot of features or delete them. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qfdhrh

### Steps to reproduce

ask it to: 

Please position the question field back to the middle of the page and only stick it to the tope ONCE the response-field reached the height of the screen size, you know what I mean?

Please don't change anything else!!!!

### Expected behavior

I just wanted it to change the position of a field, but instead it did just delete and change complete different parts of the whole web app

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 133558689,
  "usedJSHeapSize": 113185517,
  "jsHeapSizeLimit": 4294705152
}
Username = obey24com
Chat ID = d3505d23a62a
```

**Comment by kc0tlh** [comment]
@obey24com Check out issue #678 for tips on prompting to avoid this, as well as updates on this issue
