### ISSUE TITLE
Preview disappeared and not showing anything

### ISSUE THREAD

**Issue by Seva-pm** [stackblitz/bolt.new#692]
### Describe the bug

Preview disappeared and not showing anything

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wdv5xy

### Steps to reproduce

click on preview

### Expected behavior

showing preview 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64924909,
  "usedJSHeapSize": 60086689,
  "jsHeapSizeLimit": 4294705152
}
Username = Seva-pm
Chat ID = 4b02b91cf3f8
```

**Comment by endocytosis** [comment]
Appreciate the feedback here. We are tracking this issue: [#1791](https://github.com/stackblitz/bolt.new/issues/1791). You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!

**Comment by pistonsfan2004** [comment]
Same issue for me now @endocytosis . No preview in UI but does seem to be working when I download and run. Hopefully can get some comp tokens for all of the "hmm, it doesn't seem to be rendering in the frontend" back and forth's 😅🙈

**Comment by lcharleslaing** [comment]
Yes, I am having the same issue

**Comment by nocluetoday** [comment]
same issue here.  built a bunch of stuff, didn't see preview.  Reverted.  Wasted tokens.  Bummer.

**Comment by Jamie97419** [comment]
Same issue here... it is very annoying!

**Comment by salemalem** [comment]
same issue
![image](https://github.com/user-attachments/assets/d3d54e89-2475-4190-a607-4928304c618c)

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it, along with potential solutions, [here](https://github.com/stackblitz/bolt.new/issues/1791).

**Comment by ycdaskin** [comment]
after 3 weeks there is still no solution and we are paying for this service.

**Comment by cre8torwork** [comment]
<img width="1436" alt="Screenshot 2024-12-28 at 13 53 10" src="https://github.com/user-attachments/assets/334304ab-718a-4d44-9924-06775a9fc7a3" />

**Comment by duarterocha0** [comment]
I had this problem, and it was caused by my ad blocker. I just disabled it, and that fixed the issue for me.

**Comment by mellouze77** [comment]
same issue
