### ISSUE TITLE
THIS SUCKS SOOOOO HARD 

### ISSUE THREAD

**Issue by LeonardSEO** [stackblitz/bolt.new#700]
### Describe the bug

# IM JUST SO FRUSTRATED ON BOLT, LIKE FIX THE PROMPTING BRO. FIX YOUR SYSTEM
IT FUCKING KEEPS DELETING MY STUFF, ADD PLACEHOLDERS ETC.! ITS NOT THAT HARD TO FIX IT, CHATGPT CAN DO IT WITH CANVAS, FUCKING CURSOR CAN DO IT. WHY NOT BOLT? ITS A GREAT CONCEPT, BUT NOT READY TO BE LAUNCHES AND ADVERTISED AS ''THIS GREAT TOOL' ITS ASS ATM. MAYBE IN THE FUTURE! CANCELLED MY SUBSCRIPTION AFTER 2 HOURS.
I

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6qkwza

### Steps to reproduce

X

### Expected behavior

Z

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58023017,
  "usedJSHeapSize": 54765217,
  "jsHeapSizeLimit": 4294705152
}
Username = LeonardSEO
Chat ID = 4e85cc1c08aa
```

**Comment by valter-silva-au** [comment]
@LeonardSEO I understand that you are frustrated and I can understand that, as I've been learning on how to use these tools like Bolt effectively. However, I believe you could choose better words to express yourself as a sign of respect to the bolt developers and the overall community. I hope you find the solution to your technical problem though. Cheers.

**Comment by kc0tlh** [comment]
Apologies for the frustration during the beta! Tips for a better usage experience can be found in #678

**Comment by FuckBolt** [comment]
> [@LeonardSEO](https://github.com/LeonardSEO) I understand that you are frustrated and I can understand that, as I've been learning on how to use these tools like Bolt effectively. However, I believe you could choose better words to express yourself as a sign of respect to the bolt developers and the overall community. I hope you find the solution to your technical problem though. Cheers.

FUck you

**Comment by sugoigroup** [comment]
FUCK FUCK BOLT ASS HOLE
