### ISSUE TITLE
I cannot find my previous chats

### ISSUE THREAD

**Issue by EHC1972** [stackblitz/bolt.new#701]
### Describe the bug

Lost all my previous chats. 
Login page opens another window and does not go trough the initial page
Does not retain my previous chats

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Go to menu check chats, its all gone...

### Expected behavior

I want to see all my previous builds.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by duan78** [comment]
Same here

**Comment by chevgo** [comment]
same issue

**Comment by sergosv** [comment]
same!! I lost my previous chat :(  really sad!

**Comment by kc0tlh** [comment]
@EHC1972 @duan78 @sergosv @chevgo you can reload your old chats using the instructions in #39
