### ISSUE TITLE
AI appears to write comments that intend to be doing certain action, but wiping out existing code

### ISSUE THREAD

**Issue by clipson** [stackblitz/bolt.new#702]
### Describe the bug

AI is wiping out existing code and has comments for what it is trying to do, but has removed the code that existed before. Example of what this looked like:

import React, { useState, useRef, useEffect } from 'react';
import { startOfWeek, endOfWeek, eachDayOfInterval, format, addWeeks, subWeeks, isSameDay } from 'date-fns';
import { ChevronLeft, ChevronRight, Plus, X, Calendar, CheckSquare, RefreshCw } from 'lucide-react';

// ... (keep all the interfaces and other imports)

const WeeklyView: React.FC<WeeklyViewProps> = ({
  // ... (keep all the props)
}) => {
  // ... (keep all the existing state)
  const [dialogPosition, setDialogPosition] = useState({ top: 0, left: 0 });

  // ... (keep other functions)

  const handlePlusClick = (day: Date, event: React.MouseEvent) => {
    event.stopPropagation();

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yqrbex

### Steps to reproduce

This appears to happen randomly on certain requests. I'm not sure the exact way to reproduce

### Expected behavior

Do not add these comments, instead do the listed action.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56996047,
  "usedJSHeapSize": 50496195,
  "jsHeapSizeLimit": 4294705152
}
Username = clipson
Chat ID = 51ac236a8515
```

**Comment by kc0tlh** [comment]
@clipson this has been resolved in #124
