### ISSUE TITLE
the tool frequently truncates the generated code when writing to files

### ISSUE THREAD

**Issue by jps1990** [stackblitz/bolt.new#707]
### Describe the bug

When using the code generation feature on [www.bolt.new](https://www.bolt.new/), the tool frequently truncates the generated code when writing to files. This results in incomplete code files that cause application crashes. Additionally, even after manually removing the truncated sections, the remaining code remains incomplete or broken. This issue disrupts the development workflow and incurs additional costs due to token-based billing for each incomplete generation attempt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lyz8ng

### Steps to reproduce

normal use 

### Expected behavior

normal use 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 98341207,
  "usedJSHeapSize": 94052591,
  "jsHeapSizeLimit": 4294705152
}
Username = jps1990
Chat ID = 9faaf4ac0607
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by jps1990** [comment]
Need Better Pre PROMPT !!!!

**Comment by motiejunas** [comment]
Yes, this is the most annoying part for now. It is impossible to code any app when the code grows a bit. This issue should be prioritized ASAP.

**Comment by kc0tlh** [comment]
@jps1990 & @motiejunas This is a top priority for us. You can track progress and see the tips and tricks for working around it in issue #124 ([rollbacks](https://x.com/stackblitz/status/1844839379270836266) are very helpful working around this until it is fully fixed)
