### ISSUE TITLE
uyguluma sürekli kesiliyor yeniden başlamak zorunda kalıyorum ve yeniden jeton harcıyorum çok saçma ! 

### ISSUE THREAD

**Issue by eraycaylak** [stackblitz/bolt.new#711]
### Describe the bug

.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fph9ut

### Steps to reproduce

.

### Expected behavior

.

### Screen Recording / Screenshot

.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76084726,
  "usedJSHeapSize": 57032090,
  "jsHeapSizeLimit": 4294705152
}
Username = eraycaylak
Chat ID = 84251bca2df5
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@eraycaylak thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
