### ISSUE TITLE
Code Commenting Huge Sections of Code out, which wastes tokens...This would be a 10 second fix

### ISSUE THREAD

**Issue by bensdb01** [stackblitz/bolt.new#714]
### Describe the bug

At the moment, about 30%-40% of the time, bolt.new outputs commented code, breaking the app. This result in wasted tokens and time, and annoyance.

I imagine it would be the quickest/easiest fix in the world.

If bolt.new simply appended "Always output full uncommented, unnabreviated code." to the end of every user message, before passing to the model, it would basically solve that problem...

In practice when I do that manually it usually stops bolt.new making this mistake, but it is laborious and annoying to have to append that to the end of every single message.

### Link to the Bolt URL that caused the error

www.bolt.new

### Steps to reproduce

Just use bolt.new for more than half an hour.

### Expected behavior

Not to comment out huge sections of my code base every time bolt.new works on it, essentially breaking the application over and over.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by neillh** [comment]
Hey @bensdb01 this is driving me crazy too. no matter how many times I tell it to give me a full file.
Following to see any responses.

**Comment by jim80** [comment]
Have a look at .bolt/prompt, would adding your "Always output full uncommented, unnabreviated code." to that work?
you can read/edit it using cat in a terminal, but those edits will not persist on reloading.
I'd be interested to see if that works for you.

**Comment by kc0tlh** [comment]
@bensdb01, @neillh, @jim80 we have found this issue to be tougher than expected to resolve but are working on it. You can track progress and see the tips and tricks for working around it in issue #124

**Comment by rasec809** [comment]
here with the same issue
