### ISSUE TITLE
Can't import public repo

### ISSUE THREAD

**Issue by Knickend** [stackblitz/bolt.new#715]
### Describe the bug

Cannot destructure property 'appFiles' of 'project' as it is null.

### Link to the Bolt URL that caused the error

https://bolt.new/~/github.com/liquity/bold

### Steps to reproduce

Go to https://bolt.new/~/github.com/liquity/bold

### Expected behavior

Expected to see the front-end of this decentralised application

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89572564,
  "usedJSHeapSize": 88467488,
  "jsHeapSizeLimit": 4294705152
}
Username = Knickend
Chat ID = 85a934f0fda6
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by joaoviana** [comment]
Also facing this issue, any pointers?
