### ISSUE TITLE
URL / Hyperlinks are not working in chat

### ISSUE THREAD

**Issue by MrNickGeiger** [stackblitz/bolt.new#719]
### Describe the bug

When you suggest I upgrade my account - I click upgrade and there is not link to actually upgrading. Also it seems that my previous projects do not have anywhere near the features that I built out yesterday before running out of credits.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mtqcg6

### Steps to reproduce

1. Utilize all your free credits
2. Click Upgrade button when prompted to upgrade to keep utilizing service
3. Nothing happens - no new page or link to your billing page options or whatever come up.

### Expected behavior

I expect it to take me to a page that lets me look at the upgrade options available

I expect it to keep my projects / save my projects so that I can pickup the next day where I left off.

I would gladly pay for this service if I knew I could trust it with building out my projects and not losing anything day over day etc

### Screen Recording / Screenshot

![boltissues](https://github.com/user-attachments/assets/84181e28-1326-4e0c-a55c-46f727fd76c3)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows, Chrome 

### Additional context

Is there anyway I can save system state or something?

**Comment by endocytosis** [comment]
Appreciate the feedback! This issue should now be resolved.
