### ISSUE TITLE
Saving / Versions

### ISSUE THREAD

**Issue by guapjackson** [stackblitz/bolt.new#722]
You guys need to fix this - why is there no clear way to push git or save versions? Was making good progress and then one prompt destroyed everything and it couldn't rebuild what was already done or revert to a previous version. Was quite annoying.

**Comment by kc0tlh** [comment]
🎉Rollback/undo to previous chat messages has [landed on production](https://x.com/stackblitz/status/1844839379270836266)!

Thanks for the report and patience during this beta period!
