### ISSUE TITLE
1 step forward, 2 steps back

### ISSUE THREAD

**Issue by PARAD111GM** [stackblitz/bolt.new#729]
### Describe the bug

constantly making random changes and undoing all previous work. Impossible to make progress. No version control. It just burned through 8 million credits running me in circles for hours and at the end it pretty much erased half the app on a whim. Terrible experience once the novelty wears off.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qwfmmz

### Steps to reproduce

1. step one: start a project
2. step two: try to actually make anything
3. step three: approach wall
4. step four: proceed to bang head against wall
5. step five: repeat

### Expected behavior

a functional development experience

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 373400968,
  "usedJSHeapSize": 331200024,
  "jsHeapSizeLimit": 4294705152
}
Username = PARAD111GM
Chat ID = ab4c632122bc
```

### Additional context

too exhausting

**Comment by kc0tlh** [comment]
Apologies for the frustrating beta experience. Checkout the tips in #678 to avoid many of the issues you described!
