### ISSUE TITLE
Bolt looping when attempt to fix error. Used .2 to .3 M tokens

### ISSUE THREAD

**Issue by kman62** [stackblitz/bolt.new#731]
### Describe the bug

App keeps looping to fix this error 
"Error analyzing idea:""An error occurred while analyzing the idea."
   at analyzeIdea (/src/components/idea-analyzer.tsx:53:15)
   
   and 
   Error: Failed to execute 'postMessage' on 'MessagePort': Symbol() could not be cloned.
   at /.localservice@runtime.34c588ed.js:1:12699
   at new Promise (<anonymous>)
   at _0x24ed21 (/.localservice@runtime.34c588ed.js:1:11784)
   at Object.apply (/.localservice@runtime.34c588ed.js:1:9811)
   at _0x24da8c (/.localservice@runtime.34c588ed.js:26:34628)
   at _0x5bf0cc (/.localservice@runtime.34c588ed.js:26:35369)
   at console.error (/.localservice@runtime.34c588ed.js:26:34080)
   at analyzeIdea (/src/components/idea-analyzer.tsx:53:15)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nss8ts

### Steps to reproduce

Clciking on fix problem button

### Expected behavior

Fix error

### Screen Recording / Screenshot

https://www.loom.com/share/84017c83beb14b49878183b5d5b960b0?sid=2eb1ac6e-2b64-4d77-ab63-52ff27d851fe

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91027506,
  "usedJSHeapSize": 83020118,
  "jsHeapSizeLimit": 4294705152
}
Username = kman62
Chat ID = bbad7094d808
```

**Comment by kc0tlh** [comment]
@kman62 the "Fix error" button cannot magically fix all errors, due to AI limitations. You will need to do research on the issue and try to help fix it, or take another approach to the project. 

A bunch of tips can be found in issue #678

**Comment by Billsu55** [comment]
i have some error.@kc0tlh how to fix this error. Cannot find in google as well

**Comment by tethlorhen** [comment]
I personally think its a rip off. Things like error loops and recurring errors should be discounted . If your assistant keeps writing faulty code what should we do , keep paying money for the faulty code?
