### ISSUE TITLE
"Deployment stopped with unknown error". 

### ISSUE THREAD

**Issue by LiebUr** [stackblitz/bolt.new#732]
### Describe the bug

"Deployment stopped with unknown error". 
Tried the usual suspects. pretty consistent ( repeatable) 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jbaze2

### Steps to reproduce

click "deployment" button

### Expected behavior

deployment :-)

### Screen Recording / Screenshot

<img width="556" alt="image" src="https://github.com/user-attachments/assets/2920bc7f-6af5-451e-8377-b4c55cb88106">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 48636711,
  "usedJSHeapSize": 42581175,
  "jsHeapSizeLimit": 4294705152
}
Username = LiebUr
Chat ID = d142297ba235
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
