### ISSUE TITLE
not deploying

### ISSUE THREAD

**Issue by abhiM200** [stackblitz/bolt.new#734]
### Describe the bug

unable to deploy the application

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7nnyrx?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=sidebar

### Steps to reproduce

na

### Expected behavior

mna

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47586413,
  "usedJSHeapSize": 43246701,
  "jsHeapSizeLimit": 4294705152
}
Username = abhiM200
Chat ID = db1a9188e11c
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
