### ISSUE TITLE
Can you make it so that a user's full chat history, not just the code, is saved.

### ISSUE THREAD

**Issue by vicmusara** [stackblitz/bolt.new#738]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by neillh** [comment]
I agree, reloading the page or opening another chat, all chat history is gone, this relates to steps to set up projects or features we have worked on. Its hard to pickup where we left off.

**Comment by kc0tlh** [comment]
This issue and it's resolution is being tracked in issue #124
