### ISSUE TITLE
Integration with Github

### ISSUE THREAD

**Issue by rhfiguer** [stackblitz/bolt.new#741]
**Is your feature request related to a problem? Please describe:**
In many ocassions Bolt make too many changes in the project that were not requested that I get a huge mess. It would be great to have a version control to avoid losing progress in the project. The current way to work is very unreliable since there are changes that come from nowhere.

**Comment by Labhk** [comment]
Hey, I have build this web tool for just this, previously using script on local now its a website much easy, enjoy
https://boltsync.mystify.tech/
https://www.youtube.com/watch?v=IneFM6ViV8s
