### ISSUE TITLE
dependencies not install. get same error every time.

### ISSUE THREAD

**Issue by KAXUN01** [stackblitz/bolt.new#744]
### Describe the bug

npm ERR! Unterminated string in JSON at position 1832600 (line 1 column 1832601)

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-19T15_52_14_340Z-debug-0.log

~/project 3m 12s

above error massage coming in every time i use the application 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-yyj3qa

### Steps to reproduce

"i need github markdown file generator app. user give input and this application output the markdown text."

give above text for the input of bolt ai. then it produce this error

### Expected behavior

i think this is a programming  problem. this AI use the programming languages without knowing proper idea. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 43188350,
  "usedJSHeapSize": 40553802,
  "jsHeapSizeLimit": 2172649472
}
Username = KAXUN01
Chat ID = 9070d40cb174
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
