### ISSUE TITLE
Whole my project i was working on is gone.. 

### ISSUE THREAD

**Issue by SheikhCash** [stackblitz/bolt.new#746]
### Describe the bug

Whole my project i was working on is gone..  do you have a copy or what.. i cant find it bolt..
it have something.. but all time and effort i have done is gone... along with all the token...
i need you guys to look into it and find a back of the code and design.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-93g1qk

### Steps to reproduce

Whole my project i was working on is gone..  do you have a copy or what.. i cant find it bolt..
it have something.. but all time and effort i have done is gone... along with all the token...
i need you guys to look into it and find a back of the code and design.

### Expected behavior

Whole my project i was working on is gone..  do you have a copy or what.. i cant find it bolt..
it have something.. but all time and effort i have done is gone... along with all the token...
i need you guys to look into it and find a back of the code and design.

### Screen Recording / Screenshot

Whole my project i was working on is gone..  do you have a copy or what.. i cant find it bolt..
it have something.. but all time and effort i have done is gone... along with all the token...
i need you guys to look into it and find a back of the code and design.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 49375160,
  "usedJSHeapSize": 47818680,
  "jsHeapSizeLimit": 4294705152
}
Username = sheikhk
Chat ID = cfbca331548b
```

### Additional context

Whole my project i was working on is gone..  do you have a copy or what.. i cant find it bolt..
it have something.. but all time and effort i have done is gone... along with all the token...
i need you guys to look into it and find a back of the code and design.

**Comment by kc0tlh** [comment]
@SheikhCash info on how to open old chats can be [found here](https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671 ) along with our progress on implementing chat persistence in #39
