### ISSUE TITLE
Problems with deployment

### ISSUE THREAD

**Issue by andresroi** [stackblitz/bolt.new#748]
### Describe the bug

When I press deploy Bolt starts but then suddendly gets an error: I've initiated the deployment process for your Recipe Generator application to Netlify. The build command npm run build will be used to create a production-ready version of your Next.js application, and the output directory .next will be deployed.

Now, let's wait for the deployment to complete and retrieve the deployment status.

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xruqqm

### Steps to reproduce

just deploy any app, it doesnt work

### Expected behavior

to deploy the app

### Screen Recording / Screenshot

no

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 117291273,
  "usedJSHeapSize": 109579845,
  "jsHeapSizeLimit": 4294705152
}
Username = andresroi
Chat ID = b970b34eda8d
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
