### ISSUE TITLE
My chats are gone

### ISSUE THREAD

**Issue by prattydaddy** [stackblitz/bolt.new#749]
### Describe the bug

Hello, im missing my chats from awhile ago. so sad

### Link to the Bolt URL that caused the error

unfortunately its just missing

### Steps to reproduce

its just entirely missing

### Expected behavior

its missing, not sure why

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@prattydaddy here is how to open old chats:
https://github.com/stackblitz/bolt.new/issues/39#issuecomment-2418148671
