### ISSUE TITLE
Did not deploy

### ISSUE THREAD

**Issue by masgpt** [stackblitz/bolt.new#756]
### Describe the bug

it did not deploy to netfly

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uwwaie

### Steps to reproduce

Not sure. First time build. 

### Expected behavior

A clickable preview of a deployed product. Maybe not fully to the web online, but just a local preview to do testing. 

### Screen Recording / Screenshot

did not install dependencies. 
did not build application. 

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = masgpt
Chat ID = 6696263b2b5c
```

### Additional context

Update package.json with build script

package.json
npm install

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
