### ISSUE TITLE
All changes have not been saved after refreshing the page

### ISSUE THREAD

**Issue by RZX00** [stackblitz/bolt.new#76]
### Describe the bug

It's really sad that all the work I did with bolt has disappeared. Also after it fixed a wrong version, I can't go back, I can't go back to what was my favorite version ever

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-56erxm

### Steps to reproduce

Step 1 Refresh the page 

### Expected behavior

nothing be change

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 91325345,
  "usedJSHeapSize": 87994881,
  "jsHeapSizeLimit": 4294705152
}
Username = RZX00
Chat ID = 41a70e1a3d70
```

**Comment by Nemikolh** [comment]
Hey @RZX00! 

Really sorry about this, we're aware and we're going to fix those two issues: saving your chat history and having multiple versions that you can navigate to.

We're already tracking those issues in #35 and #39 so I'm going to close this issue. Feel free to subscribe to those to track our progress on this!
