### ISSUE TITLE
Pricing & Tokens Concern

### ISSUE THREAD

**Issue by DeepakKuPatro** [stackblitz/bolt.new#762]
Hi,

I am enjoying your platform. It's wonderful. Great job in building this!

However pricing is an issue. I paid $9 for Pro version that offered 10M tokens for a month. It took me just 4-5 days to exhaust that. I am not able to continue my work because the next 10M tokens will be available next month. I can't wait so I look for a one time reload and it charges me $30 for 10M tokens. It's insane. Why did I have to pay 3 times to get the same amount of access. And what's with this 10M tokens. It doesn't seem to be good enough for anything substantial. Plus the moment my tokens are renewed, I see only 8.8M tokens. Where did the 1.2M tokens go?

Please write back at deepakpatrohr@gmail.com

**Comment by kc0tlh** [comment]
@DeepakKuPatro apologies for the frustrating experience during the beta.

 if you are building out a large project, I recommend upgrading to a higher tier plan that includes more tokens.

For info on our efforts to increase token efficiency follow issue #678. There are also a bunch of tips on how to work with Bolt more efficiently!

**Comment by massanulaga** [comment]
Same for me, I bought the pro plan 20$ and depleted the 10M token in literally 4-5 hours of interaction
This is absolutely insanely not optimized, the AI keep making mistakes for a fairly basic app
How is the world is this even a realistic pricing ? So now I am stuck and have to wait a month to continue ?
Or buy 10M more tokns for 30$ that will be consumed tomorrow ?

I am mind blown that bolt is considered a production ready project
