### ISSUE TITLE
Unfair token calculation for system errors

### ISSUE THREAD

**Issue by TakaIdea** [stackblitz/bolt.new#766]
I consider it unfair that bolt makes many mistakes mainly by removing sections that then need to be restored and reported for changes again. I am sure that I have lost 75% of my tokens due to this endless cycle.

**Comment by neillh** [comment]
ditto.
every command is followed by, "can you give me the full file"
followed by "And with all the previous features we just added"

**Comment by kc0tlh** [comment]
@TakaIdea apologies for the frustrating experience during the beta. 

Please follow issue #678 for our efforts on increasing token efficiency AND a bunch of tips on how to work with Bolt more efficiently!
