### ISSUE TITLE
deploying to netlify error

### ISSUE THREAD

**Issue by logicshaper19** [stackblitz/bolt.new#767]
### Describe the bug

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-pmcrs8

### Steps to reproduce

with no clear error message, i tried to deploy severally.

### Expected behavior

deploy to netlify

### Screen Recording / Screenshot

<img width="1440" alt="Screenshot 2024-10-21 at 02 28 07" src="https://github.com/user-attachments/assets/7a8e576e-350f-48e5-ac19-2cea7fa12e33">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108762585,
  "usedJSHeapSize": 106315245,
  "jsHeapSizeLimit": 2172649472
}
Username = logicshaper19
Chat ID = 54bdcab08569
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
