### ISSUE TITLE
generate new file and hang

### ISSUE THREAD

**Issue by u007** [stackblitz/bolt.new#771]
### Describe the bug

ask to generate a script file.
can see the file being generated, and it become blank and the process hang

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-t45rad

### Steps to reproduce

1. add a script alike prisma db push

### Expected behavior

file generated

### Screen Recording / Screenshot

<img width="1230" alt="Screenshot 2024-10-21 at 1 56 48 PM" src="https://github.com/user-attachments/assets/d8ea50c3-d85d-4c7c-a179-a4dca3dc0e7b">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47360721,
  "usedJSHeapSize": 45507481,
  "jsHeapSizeLimit": 4294705152
}
Username = u007
Chat ID = c19bd714f4e4
```

**Comment by endocytosis** [comment]
Appreciate the feedback! The team is hard at working continuing to make improvements to model performance and efficiency. Sometimes the LLM has to be re-prompted if it fails to generate code correctly, and there are cases where manual intervention is required if the LLM fails repeatedly. More information and techniques to optimize performance can be found here: #678.
