### ISSUE TITLE
will not deploy

### ISSUE THREAD

**Issue by harryhamlinjr** [stackblitz/bolt.new#772]
### Describe the bug

will not deploy gives me this error every time...
<img width="487" alt="Screenshot 2024-10-21 at 2 10 25 AM" src="https://github.com/user-attachments/assets/3f251009-1860-4e1e-bbeb-f1faa6348f79">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nhpyrr

### Steps to reproduce

cant deploy

### Expected behavior

can't deploy

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 145224122,
  "usedJSHeapSize": 125423454,
  "jsHeapSizeLimit": 4294705152
}
Username = harryhamlinjr
Chat ID = 8a66f350353d
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
