### ISSUE TITLE
Chat disappearing both of chat got disappeared

### ISSUE THREAD

**Issue by nadimnakade** [stackblitz/bolt.new#774]
### Describe the bug

Chat disappearing both of my chat got disappeared and i lost all the progress i made please help

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gcfnn4

### Steps to reproduce

Chat disappearing both of my chat got disappeared and i lost all the progress i made please help

### Expected behavior

Chat disappearing both of my chat got disappeared and i lost all the progress i made please help

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 104128966,
  "usedJSHeapSize": 82391682,
  "jsHeapSizeLimit": 4294705152
}
Username = nadimnakade
Chat ID = e5f8e94f7d4c
```

**Comment by kc0tlh** [comment]
@nadimnakade you can find your projects using the instructions in #39
