### ISSUE TITLE
The images are not displayed in the editors.

### ISSUE THREAD

**Issue by yahyamohmuedpro99** [stackblitz/bolt.new#776]
### The images are not displayed in the editors. and it looks like it paralyzed  

also the name of images is changed ,

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-waujbv

### Steps to reproduce

- upload any image to the editor
- try to open the image editor

### Expected behavior

to be shown as a normal image and the name not changed of the image 

### Platform

- Browser:  Chrome

**Comment by endocytosis** [comment]
Appreciate the feedback. We are aware of this issue and are tracking it here: https://github.com/stackblitz/bolt.new/issues/1809.
