### ISSUE TITLE
add the history of the code 

### ISSUE THREAD

**Issue by yahyamohmuedpro99** [stackblitz/bolt.new#778]
**Describe the solution you'd like:**

Similar to version control systems like Git, any changes made to the project will automatically update in the tree structure. This allows for easy tracking of modifications and enables you to revert to specific parts of the project on demand. You can also update or roll back changes based on any specific section of the project, providing flexibility and control over the development process.

**Comment by kc0tlh** [comment]
@yahyamohmuedpro99 thanks for the feedback!

This has landed on prod: https://x.com/stackblitz/status/1844839379270836266
