### ISSUE TITLE
DEPLOYMENT ERROR

### ISSUE THREAD

**Issue by KELVIN25509** [stackblitz/bolt.new#779]
### Describe the bug

While the application was being deployed ,  it just said that they was an error ,  i cant understand what the error was for 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n4wfhy

### Steps to reproduce

there was an error during the deployment process

### Expected behavior

the deployment process didnt go succesful

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 132862397,
  "usedJSHeapSize": 120202661,
  "jsHeapSizeLimit": 4294705152
}
Username = Kelvinnj
Chat ID = 4014b5648343
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
