### ISSUE TITLE
Installing Dependencies

### ISSUE THREAD

**Issue by kaiteddy** [stackblitz/bolt.new#786]
### Describe the bug

Most of the time when installing dependencies on my project it fails at NPM install or NPN run dev and this is a continuation throughout my projects. Possibly due to the fact that I am utilising API's 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-z2lhrv

### Steps to reproduce

1. Run the project is initiated through the text and then it tries to install dependencies 

### Expected behavior

Expect the project to run

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = kaiteddy
Chat ID = 8a2814ff8131
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
