### ISSUE TITLE
 SyntaxError: Identifier 'nextPromptResult' has already been declared

### ISSUE THREAD

**Issue by DataD-AI** [stackblitz/bolt.new#79]
### Describe the bug

i keep getting this error ultimately anytime i try to build an app after a few mins of code i always get this error 

SyntaxError: Identifier 'nextPromptResult' has already been declared

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mdfjql

### Steps to reproduce

ask the bolt.new to make a pdf merger app with a certain colour code

### Expected behavior

get a problem saying 
SyntaxError: Identifier 'nextPromptResult' has already been declared

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85702874,
  "usedJSHeapSize": 80505274,
  "jsHeapSizeLimit": 4294705152
}
Username = Datad
Chat ID = 0d2c51e56b74
```

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

I think this issue may have been resolved now, could you try again? 

If there are any further problems let us know so we can reopen the issue!
