### ISSUE TITLE
 An error occured while streaming this message.

### ISSUE THREAD

**Issue by epiqueone** [stackblitz/bolt.new#790]
### Describe the bug

hej ther. i very often get this error after put in my prompt

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8nha1k

### Steps to reproduce

please check the link

### Expected behavior

...

### Screen Recording / Screenshot

...
<img width="1717" alt="Bildschirmfoto 2024-10-21 um 16 56 10" src="https://github.com/user-attachments/assets/02456982-4a7d-45da-90ad-da5db67a2f5a">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45199322,
  "usedJSHeapSize": 42548142,
  "jsHeapSizeLimit": 4294705152
}
Username = epiqueone
Chat ID = da3318623264
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Tracked in #1022
