### ISSUE TITLE
Upload current project into Bolt/StackBlitz

### ISSUE THREAD

**Issue by ethosperformance** [stackblitz/bolt.new#791]
**Is your feature request related to a problem? Please describe:**

I initially started my project on bolt (when it first came out), but because of certain reasons, i downloaded the project and started working on it in Cursor. Now, the project has become much more sophisticated with many more files. Unfortunately, the only way to create a new file in a Bolt project is to go into Stackblitz to create the file and then open the project in bolt. the thing is, i added around 100 files in the project after downloading it from Bolt. While i could copy and paste the code into a new corresponding file in Stackblitz, that just seems silly. It'd be amazing to be able to upload a project to bolt or stackblitz that way i don't need to copy and paste each file. maybe even to allow bringing in a project from a github repo and then being able to push your updates to the git repo, so now you can collab with people on a project not using bolt. For me, i do enjoy programming on Cursor for it's variety of use cases, and I enjoy the great design skills of Bolt and its interconnectivity with the backend. So, if I could work off the same files instead of copying and pasting code over to each other, that'd be great.

**Comment by kc0tlh** [comment]
@ethosperformance you can drag and drop the entire filesystem from your local machine into a blank StackBlitz project filetree, and then open in Bolt. This will accomplish your workflow for now!
