### ISSUE TITLE
The code will immediately break and unusable after being generated

### ISSUE THREAD

**Issue by cobeo2004** [stackblitz/bolt.new#798]
### Describe the bug

For this bug, the code will immediately got broken when the generating process is finished, causing the code completely unusable.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fagjvj

### Steps to reproduce

1. Go to https://bolt.new/~/sb1-fagjvj
2. Type in this prompt "design a webpage that looks like skyscanner, which has field to input the from and to destination, from date and to date, amount of person (infant, children and adult) and one-way or round trip"
3. Hit enter and wait for the response stream to complete

### Expected behavior

Expected behavior: The code after generated will be lose, making the code unusable

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45272039,
  "usedJSHeapSize": 41886779,
  "jsHeapSizeLimit": 4294705152
}
Username = cobeo2004
Chat ID = 7861c36d0cb7
```

**Comment by kc0tlh** [comment]
@cobeo2004 looks like this issue has been resolved: https://bolt.new/~/sb1-zyr1w6
