### ISSUE TITLE
Can't understand pricing

### ISSUE THREAD

**Issue by codenomnom** [stackblitz/bolt.new#8]
**Is your feature request related to a problem? Please describe:**

I got to a point where I see the message `24K of 150K daily tokens remaining.` Which makes me think I got 150k free daily tokens. 

I'm also invited to `Subscribe to Pro for 66x more usage.`. That would've been awesome, but the pricing tier says `Up to 500K output tokens per month`.

So I cannot clearly understand what get for free, and what do I get in the Pro tier. If it's 66 times more tokens, that would been around 10m tokens _per day_. But it says 500k _per month_ (which is like ~3 times the free daily quote, if I got the free daily idea correctly).

**Describe the solution you'd like:**

An easy to understand tokens quota - per day/month, or whatever the limitations are.

---

Despite that - it looks amazing! I am eager to test it a bit further (gimme those tokens 😈). Good job!

**Comment by KwintenP** [comment]
That is a mistake. The Pro plan gives you 10mio tokens per month.

I will get the page updated asap.

🙏 for letting us know.

**Comment by KwintenP** [comment]
Pricing has been updated to match the correct number of tokens. Let me know if you need more info.

**Comment by RobertZander** [comment]
i am assuming the stackblitz subscription covers bolt ?

**Comment by yachal-upson** [comment]
> i am assuming the stackblitz subscription covers bolt ?

Also here with this question
