### ISSUE TITLE
Prompts are being ignored

### ISSUE THREAD

**Issue by TakeOrdersai** [stackblitz/bolt.new#801]
### Describe the bug

Not sure if its a bug but after prompting not to use deprecated modules I'm still getting the same installs:
 npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-8hhyez

### Steps to reproduce

See Errors

### Expected behavior

It should not use any deprecated install I would hope after prompting not too but I could be wrong  and I will still need to address each one after the install to correct them.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84748656,
  "usedJSHeapSize": 59961332,
  "jsHeapSizeLimit": 4294705152
}
Username = Dwaynep
Chat ID = de2a19520344
```

**Comment by kc0tlh** [comment]
@TakeOrdersai we upgraded to a newer AI model, so hopefully this is resolved. Unfortunately we cannot control whether the AI knows the latest status of every NPM dependency. We will be introducing the ability to lock specific files tho, so you could lock your package.json after you are satisfied with all package versions using that feature soon!
