### ISSUE TITLE
Preview not showing correclty

### ISSUE THREAD

**Issue by Passne-hub** [stackblitz/bolt.new#803]
### Describe the bug

<img width="688" alt="スクリーンショット 2024-10-22 15 18 59" src="https://github.com/user-attachments/assets/f185682e-59f1-45a7-b37f-b6f0fc5d6050">
It seems there is an error in the code and preview is not working.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-me72zz

### Steps to reproduce

Go Preview.
See the error. 
Reload and Reopen cannot work.

### Expected behavior

Showing preview properly

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62185093,
  "usedJSHeapSize": 59793417,
  "jsHeapSizeLimit": 4294705152
}
Username = Passne-hub
Chat ID = ccf4b8506962
```

**Comment by endocytosis** [comment]
Appreciate the feedback here. We are tracking this issue: [#1791](https://github.com/stackblitz/bolt.new/issues/1791). You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
