### ISSUE TITLE
Unknown error unable to deploy

### ISSUE THREAD

**Issue by ericmqu** [stackblitz/bolt.new#804]
### Describe the bug

Cant deploy website after making new env variable to store API key and trying to redeploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6c2j3d

### Steps to reproduce

1. redeploy

### Expected behavior

Deployment to work

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e419fbd0-2822-4a83-8091-7a0a2e0608b2)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73823670,
  "usedJSHeapSize": 58340098,
  "jsHeapSizeLimit": 4294705152
}
Username = ericmqu
Chat ID = 2f5024de2a0a
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
