### ISSUE TITLE
Unable to deploy program after updating the application

### ISSUE THREAD

**Issue by ERLocums** [stackblitz/bolt.new#805]
### Describe the bug

Unable to deploy the program after updating application. Problems occur during the npx vite build stage of building an application.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3fqqhs

### Steps to reproduce

Deploy a program
Open program on nelify , realise there is a problem you need to fix
Go back to bolt.new add the changes desired
Try to redeploy
Error recieved

### Expected behavior

I expected the application to redeploy with the expected changes. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68624514,
  "usedJSHeapSize": 63970950,
  "jsHeapSizeLimit": 4294705152
}
Username = ERLOCUMS
Chat ID = 669b7f948446
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Thanks for the report and patience during this beta period! Tracking all deployment related bug fixes in issue #499
