### ISSUE TITLE
Looping error

### ISSUE THREAD

**Issue by Passne-hub** [stackblitz/bolt.new#806]
### Describe the bug

<img width="1426" alt="スクリーンショット 2024-10-22 15 34 39" src="https://github.com/user-attachments/assets/0458703d-5782-437f-a0be-f44b9ec0f680">
It detects problems after sending prompt and looping it. Clicking"Fix problems" doesn't work and showing it again.
Also it costs token.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-me72zz

### Steps to reproduce

See error message left bottom side. Click "Fix problems". Same error pop up again. Click "Fix problems" again. Looping the error.

### Expected behavior

Fix the problem and show preview correctly.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 45308230,
  "usedJSHeapSize": 43531458,
  "jsHeapSizeLimit": 4294705152
}
Username = Passne-hub
Chat ID = dd06f49cc438
```

**Comment by kc0tlh** [comment]
@Passne-hub tips on token usage efficiency and error debugging can be found in issue #678

**Comment by Passne-hub** [comment]
Can you check the issue?
