### ISSUE TITLE
Error al crear aplicacion

### ISSUE THREAD

**Issue by Talamuque77** [stackblitz/bolt.new#808]
### Describe the bug

NotFoundError: No se pudo ejecutar 'insertBefore' en 'Nodo': el nodo antes del cual se insertará el nuevo nodo no es un hijo de este nodo.
    en ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    en je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    en kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    en Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vwxzsd

### Steps to reproduce

crear aplicacion con este aspecto

### Expected behavior

crear la app sin errores

### Screen Recording / Screenshot

![PXL_20241017_155054247](https://github.com/user-attachments/assets/5e6772b3-e195-42c5-9936-e70ab3093e7f)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50640572,
  "usedJSHeapSize": 41867108,
  "jsHeapSizeLimit": 2160066560
}
Username = Talamuque77
Chat ID = 63d1be330f98
```

**Comment by kc0tlh** [comment]
For assistance with programming help on specific projects, please check out the discord: discord.gg/stackblitz
