### ISSUE TITLE
Can't upload existing project.

### ISSUE THREAD

**Issue by DharmickM** [stackblitz/bolt.new#810]
### Describe the bug

I worked on a new front end for my start up using bolt.new which was great. However, I downloaded the code locally, made some change and wanted to upload it again and I can't. I paid 100 USD for this feature and it is set me back. I am meant to be presenting my MVP in a few weeks and this is critical! Is there anyway around this???

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

Try adding in a local repo or a private repo from github.

### Expected behavior

Being able to add in a local repo.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
Yes! Drag-n-drop the code into a **blank** StackBlitz project (you can create one by going to [node.new](node.new)) and then use the Open In Bolt button to open it in Bolt!
