### ISSUE TITLE
Wasted almost 5million credit 

### ISSUE THREAD

**Issue by putitonline** [stackblitz/bolt.new#817]
### Describe the bug

Design an app. But it kept not completed and using up my credits as if it was going back on itself. Which as not helpful as its wasted almost 5million of my credit which i would like back 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cjxt2w

### Steps to reproduce

produce the code was an issue and it kept producing a different design

### Expected behavior

Same code should have be used just with the updates. instead of reusing my credit 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 170914632,
  "usedJSHeapSize": 147355928,
  "jsHeapSizeLimit": 4294705152
}
Username = putitonline
Chat ID = a0d8f2b52bb0
```

**Comment by kc0tlh** [comment]
Please review the token usage tips in #678 to avoid wasting tokens
