### ISSUE TITLE
Trying Bolt

### ISSUE THREAD

**Issue by localseo365** [stackblitz/bolt.new#818]
### Describe the bug

Hi, I'm trying Bolt to create websites and it makes some mistakes like: it deletes part of the code without being asked, you ask it to modify one thing and it deletes another, etc. The tool is promising, but if we are paying to use it, there should NOT be these kinds of errors. Thanks

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-udh7iy

### Steps to reproduce

Hi, I'm trying Bolt to create websites and it makes some mistakes like: it deletes part of the code without being asked, you ask it to modify one thing and it deletes another, etc. The tool is promising, but if we are paying to use it, there should NOT be these kinds of errors. Thanks

### Expected behavior

Hi, I'm trying Bolt to create websites and it makes some mistakes like: it deletes part of the code without being asked, you ask it to modify one thing and it deletes another, etc. The tool is promising, but if we are paying to use it, there should NOT be these kinds of errors. Thanks

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76730134,
  "usedJSHeapSize": 71382894,
  "jsHeapSizeLimit": 4294705152
}
Username = localseo365
Chat ID = c8400ba8de0c
```

**Comment by kc0tlh** [comment]
Checkout the suage tips in #678 to improve your results!
