### ISSUE TITLE
ADD A BACK BUTTON, PLEASE!

### ISSUE THREAD

**Issue by Kenty2k** [stackblitz/bolt.new#82]
### Describe the bug

I am forever fixing the issues that it's "Hallucinating" thinking it needs to fix without me requesting it. I request to change a button and it removes features from the website on different pages. I fix one issue and it "Hallucinates" casing 3 more to fix. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kssyba

### Steps to reproduce

Use the AI long enough to see how it just breaks stuff you didnt ask it to touch....

### Expected behavior

Give me a back button for the project. I would expect the AI to make mistakes but I CAN'T UNDO THEM!!! Why??? Please add this feature. 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114990531,
  "usedJSHeapSize": 111833619,
  "jsHeapSizeLimit": 4294705152
}
Username = Kenty2k
Chat ID = f5856a436c2d
```

**Comment by shobhit99** [comment]
same boat. much needed. one wrong output and your progress is ruined. only to fix is keep asking it to get back to working version.
i made perfect app in 4-5 revisions but couldn't get it work again after 1 bad prompt

**Comment by brovio** [comment]
any suggestions to avoid this @shobhit99 @Kenty2k , I've used similar programs and know what you're talking about.

trying this out and so far so good, but would like to start making save points, forks or something...

**Comment by shobhit99** [comment]
@brovio i guess just fork the repo at every save point, see if it can be added as a commit

**Comment by brovio** [comment]
So I've got em forked in stackblist. But I can't get them back into bolt.. No access to bolt collection. No idea how many tokens I've left. Have to go local. No control. Instead of reverting a whole slack like interface that I was fine tuning - because it bugged out - it recreated everything from the before end after screenshots I provided. That's gotta be a lot of tokens....

Feel there should be some extra love for the first time subscribers who are here early adopters helping out with bug reporting and feature requests to improve the tool.

**Comment by shobhit99** [comment]
@brovio clone it locally and use some ai editor to polish it further

**Comment by brovio** [comment]
yeah that path I ended up taking, tying out AIder (openai) and Claude Dev (anthropic) combo.

hate the BUILD anything claims, when if you try to build anything past a calculator, it invariably ends up messing shit up.

**Comment by mauriciorubio2** [comment]
Yes, Bolt needs versioning and a one click-rollback, undo solution, that allows you to go back to the state before you made additional changes.

**Comment by Kumala3** [comment]
> Yes, Bolt needs versioning and a one click-rollback, undo solution, that allows you to go back to the state before you made additional changes.

Absolutely! Rollback functionality is vital and needs to be implemented ASAP.

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

I agree, it would be great to have this feature! We're tracking this internally. We'll keep you posted ✨

**Comment by brovio** [comment]
Can't there be a commit added on user chat entries, that way you could more easily role back?

Or something that you can instruct us to instruct the chat, that we can make into a nearly Custom Instructions at the beginning of our sentence would provide so much help

**Comment by kc0tlh** [comment]
Short term workaround while we implement checkpoints (which we are doing as fast as we can): you can CTRL + Z to undo changes manually on each individual code file that the AI changed if you do not like the results.

**Comment by kc0tlh** [comment]
@Kenty2k @shobhit99 @brovio + @Kumala3 Thank you for the great feedback! We completely agree and are working rapidly to implement this feature. The resolution will be tracked under #35!

**Comment by fakeneuron** [comment]
I lost most of my tokens  trying to get this app to show preview again and again and unbreaking after requesting minor formatting changes. The last one was asked to add more padding to the margin of a website and everything broke.

I found a pretty clunky workaround by pushing functional versions to git via stackblitz. Bolt -> Open in Stackblitz -> Create a (git) Repository. Then you can import from git from bolt by addiing the git url to bolt like this: bolt.new/giturl... 

Just haven't found a way to commit updates to the same git without just creating an entire new repository after further progress. Stackblitz seems to just allow a whole new repository.
