### ISSUE TITLE
Use the new upgraded version of Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by Kumala3** [stackblitz/bolt.new#822]
**Is your feature request related to a problem? Please describe:**

Today, Anthropic announced [a new upgraded version of Claude 3.5 Sonnet](https://www.anthropic.com/news/3-5-models-and-computer-use) which according to Anthropic outperforms all publicly available models, including the OpenAI's o1 series of models. The great thing is that Anthropic hasn't increased the price of the new version, so since it's using Claude 3.5 Sonnet, it makes perfect sense to test the new model out and then use the new one, which should generate even higher quality code. As of my understanding, it needs to be tested extensively to ensure that the results are actually better, and if so, use this instead of its predecessor.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

Will appreciate your time and thoughts on this.

**Comment by kc0tlh** [comment]
✅ Shipped
