### ISSUE TITLE
I spent almost 5,000 tokens trying to fix an error

### ISSUE THREAD

**Issue by duhlink** [stackblitz/bolt.new#825]
I spent almost 5,000 tokens trying to fix an error, Port 3000 was stuck and it couldn't be closed, the npm logs were inaccessible because they were outside of the directory I have access to.... 

I exited the UI, reopened the project and no more issues with port 3,000 fkkkk hours wasted

**Comment by YDX64** [comment]
same here useless scam project this Bolt.new

**Comment by kc0tlh** [comment]
@duhlink this and other usage tips can be found in #678. Apologies for the frustration during the beta!
