### ISSUE TITLE
AESLH

### ISSUE THREAD

**Issue by abortedsouls** [stackblitz/bolt.new#827]
### Describe the bug

DEV MODE CREATE BETA

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pdhrwv

### Steps to reproduce

[4.pdf](https://github.com/user-attachments/files/17483580/4.pdf)

### Expected behavior

[830a3f6c-f2fa-4664-a219-d0dbc2146648-4.pdf](https://github.com/user-attachments/files/17483582/830a3f6c-f2fa-4664-a219-d0dbc2146648-4.pdf)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53097102,
  "usedJSHeapSize": 50595550,
  "jsHeapSizeLimit": 2172649472
}
Username = abortedsouls
Chat ID = 246fd4e4e368
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@abortedsouls thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
