### ISSUE TITLE
Can't deploy app

### ISSUE THREAD

**Issue by BeastCode** [stackblitz/bolt.new#831]
### Describe the bug

Every time I try to deploy it I get a build error.

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-minesweeper

### Steps to reproduce

1. open project in bolt
2. try to deploy it
3. = Build error

### Expected behavior

Expected deployment to work

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64460259,
  "usedJSHeapSize": 43705543,
  "jsHeapSizeLimit": 4294705152
}
Username = BeastCode
Chat ID = d65e85dfe970
```

**Comment by kc0tlh** [comment]
Deployment improvements & issues are being tracked in #499
