### ISSUE TITLE
Memory between conversations

### ISSUE THREAD

**Issue by markitusss** [stackblitz/bolt.new#835]
### Describe the bug

I've spent a good amount of time trying to make an application in Bolt. I've been improving the way I launch the prompts so that I can get further and further in the development of the application without it starting to give problems.

But one thing that I think needs to be corrected, is that Bolt has memory between conversations which makes it pick up previous bad habits when you start the same project in a different chat. So it's very frustrating to see that something that seems to start off on the right foot than the previous project, ends up giving errors and programming parameters that you didn't ask for in the new chat, and that come from the old ones. Also with the consequent loss of non-productive tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-1vg5ac

### Steps to reproduce

Create new chat with

### Expected behavior

.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@markitusss great feedback. We are tracking progress on this feature in #39 (it is coming soon)

**Comment by markitusss** [comment]
It's not the same problem. I'm talking about isolating conversations. When I start a new chat, the AI ​​takes data and design aspects from other open conversations. This shouldn't be correct.
