### ISSUE TITLE
Stuck on Installing Dependencies

### ISSUE THREAD

**Issue by preetsinghvi** [stackblitz/bolt.new#837]
### Describe the bug

The app is stuck in a loop. I dont see a preview, when I ask Bolt to fix errors, it tries to fix but gets stuck on 'Installing Dependencies'. I have been unable to run any apps yet due to this. I see no previews. It gets stuck on npm install.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mnxeen

### Steps to reproduce

1. Enter details to create any app
2. Model gets stuck on 'installing dependencies'

### Expected behavior

An app should be made, with a preview generated. No preview is generated as of now.

### Platform

- OS: macOS 15.0
- Browser: Safari
- Version:

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021

**Comment by thrugz** [comment]
Same issue, spending way to many tokens on this
