### ISSUE TITLE
gets to 126 lines of code then freezes after working fine for maybe an hour

### ISSUE THREAD

**Issue by 1Fix** [stackblitz/bolt.new#839]
### Describe the bug

although its written the code several times easily upto 500+ characters, it has done this consistently and if i try and fix or restart the bolt.new.. it forgets all the conversations and i have try and instruct it all again. it is very frustrating, but i know its in beta. just to remember the chats would be great... i spend alot of time telling it to print out all of the code, so it makes it easy for me (a non programer) to just copy and paste to my files rather than trying to see what code has changed and remove/paste into my code.

[I'll continue with the rest of the file in the next message due to length limits...]

Would you like me to continue with the rest of the ai-blog-genera

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jl6ije

### Steps to reproduce

no idea it seems if its maybe been running for an hour.. if it crashes or restarts it works again

### Expected behavior

i just want it to display the full code after alterations are made

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/08177d8e-ca22-4ee7-805c-5cb3a9076b6c)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 70630262,
  "usedJSHeapSize": 58314558,
  "jsHeapSizeLimit": 4294705152
}
Username = Onefix
Chat ID = 6cc8605a5750
```

**Comment by kc0tlh** [comment]
@1Fix this intermittent stability issue should be resolved with the new AI model update from last week.

Tracking chat persistence in #39
