### ISSUE TITLE
write all the code up to line 300ish then when come back to "commenting" deletes everything and show only 20 lines of code...

### ISSUE THREAD

**Issue by marcoastriders** [stackblitz/bolt.new#846]
### Describe the bug

write all the code up to line 300ish then when come back to "commenting" deletes everything and show only 20 lines of code...

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-unmhrb

### Steps to reproduce

error generating code (disappearing after finished and shows only 20 rows )

### Expected behavior

expected that the code stick there, but just disappearing after it finishes generating! 

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/fdb4afbc-be0f-4110-873b-b00f00ecb4f3)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111966104,
  "usedJSHeapSize": 92698960,
  "jsHeapSizeLimit": 4294705152
}
Username = marcoastriders
Chat ID = 0b2e2dd8dcdd
```

**Comment by kc0tlh** [comment]
This should be resolved, let me know if not!
