### ISSUE TITLE
Cannot deploy app. And Bolt cannot answer why.

### ISSUE THREAD

**Issue by Qpidox** [stackblitz/bolt.new#847]
### Describe the bug

Trying to deploy, wont explain why it doesnt work.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-njtwdp

### Steps to reproduce

Build, ask to deploy. Just doesnt work.

### Expected behavior

To deploy the app and see what was made.

### Platform

```
Browser name = Safari
Full version = 17.3.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
performance.memory = undefined
Username = Qpidox
Chat ID = 81a9baff1a5f
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Deployment improvements & issues are being tracked in #499
