### ISSUE TITLE
I"m unable to see past propmpt and answer.

### ISSUE THREAD

**Issue by cyrillesaxo** [stackblitz/bolt.new#849]
### Describe the bug

I"m unable to see past propmpt and answer.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fgcphy

### Steps to reproduce

I"m unable to see past propmpt and answer.

### Expected behavior

I"m unable to see past propmpt and answer.

### Screen Recording / Screenshot

I"m unable to see past propmpt and answer.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116765165,
  "usedJSHeapSize": 109620421,
  "jsHeapSizeLimit": 4294705152
}
Username = cyrillesaxo
Chat ID = 5cae11771c31
```

### Additional context

I"m unable to see past propmpt and answer.

**Comment by kc0tlh** [comment]
This improvement is being tracked in #39
