### ISSUE TITLE
1 Million Tokens for Paid Account

### ISSUE THREAD

**Issue by brovio** [stackblitz/bolt.new#85]
**Token Consumption + Buy More Tokens + Add own API Key to continue**

**Please add profile page that shows token consumption**

**ChatGPTEngineer.app / Cursor / Claude Dev / Aider:**

**Additional Thoughts/Feature Requeusts**

**Comment by ericwelshdev** [comment]
Totally agree!!
I signed up for the Pro subscription this afternoon and have already creeped up on the max for the 10 million month!!  LOL I'm curious how i can add more tokens to my account ? ( I've spent 3/4 of them in the last 5 hours debugging the gen ai process overwriting files and breaking stuff - don't get me wrong i love the tool , but with how verbose it is i can imagine that you can burn through tokens really quick. We will most certainly need a way to add more tokens and control how verbose the prompts are.

Thoughts ?

**Comment by brovio** [comment]
How did you know where they are?

I'm downloading local going back to Claude dev, Continke and Aider, it's
got to point where adding one change breaks existing functionality.

I feel like I've no control now. Even with forking I can't add them to the
bolt collection. So it's kinda pointless.

Unless I'm (and I probably am) missing something

There is no memory. Even with Claude's cache.

I'm using GPT4o to rewrite my basic ass prompts. Then the bolt one does
it's thing and drips functionality out of it. Think I'll stop using that!

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

We're working on ways to buy more tokens and see your usage. We'll keep you posted ✨

**Comment by brovio** [comment]
Legesnss6

**Comment by brovio** [comment]
@cosmicwork, I agree, @kirjavascript I think with cursor, fragments, chatgptengineer.app, claude dev, aider, etc... you guys need to be seen as generous to your early adopting paid users...

I'm having issue/frustrations, but because you're in your early stages, I'm holding back to an extent, giving you the benefit of the doubt, that you'll look after the problems and you new customers... Instead of being rug pulled!!

you got this!

**Comment by kc0tlh** [comment]
Hey @brovio & @ericwelshdev appreciate your feedback and understanding as we navigate this busy initial launch and work rapidly towards addressing all the great feedback! We are very excited to have you both as new users.

Updates:
1) We have shipped updates that we believe will make token usage much more efficient going forward (less tokens per prompt)
2) You can now see your Token usage in your settings pane (lower left hand corner of Bolt.new)
3) You can now buy more tokens ([instructions here](https://x.com/stackblitz/status/1844138865508134999))
4) I have reset both of your Token usage back to zero so you can keep cooking and providing more great feedback!

Closing this issue as resolved, but please open more if additional issues occur/more feature requests come to mind!
