### ISSUE TITLE
not able to build and deploy

### ISSUE THREAD

**Issue by royskiegames** [stackblitz/bolt.new#850]
### Describe the bug

> Build failed because of webpack errors
   Creating an optimized production build .
~/project 7s
❯ npx next build
Failed to compile.

./lib/email.ts
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

The error was caused by importing 'resend/dist/index.mjs' in './lib/email.ts'.

Maybe one of these should be marked as a client entry "use client":
  ./lib/email.ts
  ./app/api/verify/route.ts

> Build failed because of webpack errors
   Creating an optimized production build .
~/project 6s
❯ npx next build
Failed to compile.

./lib/email.ts
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

The error was caused by importing 'resend/dist/index.mjs' in './lib/email.ts'.

Maybe one of these should be marked as a client entry "use client":
  ./lib/email.ts
  ./app/api/verify/route.ts

> Build failed because of webpack errors
   Creating an optimized production build .
~/project 7s
❯ npx next build
Failed to compile.

./lib/email.ts
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

The error was caused by importing 'resend/dist/index.mjs' in './lib/email.ts'.

Maybe one of these should be marked as a client entry "use client":
  ./lib/email.ts
  ./app/api/verify/route.ts

> Build failed because of webpack errors
   Creating an optimized production build .
~/project 6s
❯ 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pwhm52

### Steps to reproduce

i do know how to do this

### Expected behavior

should deplloy to netify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 120898804,
  "usedJSHeapSize": 118791268,
  "jsHeapSizeLimit": 2160066560
}
Username = royskiegames
Chat ID = e31a59d15a39
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@royskiegames thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
