### ISSUE TITLE
Will not deploy

### ISSUE THREAD

**Issue by realwhytry** [stackblitz/bolt.new#852]
### Describe the bug

I try to deploy and I get "An error occured while streaming this message."

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-k4dmjg

### Steps to reproduce

click deploy

### Expected behavior

Should deploy and update netlify site

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64077780,
  "usedJSHeapSize": 58653920,
  "jsHeapSizeLimit": 4294705152
}
Username = realwhytry
Chat ID = b0de290a8998
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by rrupsing-layla** [comment]
Also encountering the same issue today

**Comment by kc0tlh** [comment]
Tracking in #1022
