### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by Pickkess** [stackblitz/bolt.new#856]
### Describe the bug

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-9a7zgb

### Steps to reproduce

An error occured while streaming this message.

### Expected behavior

An error occured while streaming this message.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89142757,
  "usedJSHeapSize": 85463177,
  "jsHeapSizeLimit": 2248146944
}
Username = kess122
Chat ID = 2ebba068c233
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
Tracking this in #1022
