### ISSUE TITLE
preview not showing

### ISSUE THREAD

**Issue by akatergi** [stackblitz/bolt.new#859]
### Describe the bug

It coded me a whole webpage but when I click on "Preview", nothing is showing up. And yes I was patient I know it can take a second, it definitely bugged out because other previews in my chat history are showing its just this one. An error I get which might help you is: 
GET https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--34c588ed.local-credentialless.webcontainer-api.io/ 404 (Not Found)
This shows while im waiting for the preview to show

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sjp4ye

### Steps to reproduce

1. Start a new chat
2. Paste in an image of a ui and ask the ai to reproduce it in an app
3. Wait for a preview to show when coding is done (it doesnt)

### Expected behavior

i expect it to show the preview

### Screen Recording / Screenshot

<img width="1728" alt="Screenshot 2024-10-23 at 1 49 08 PM" src="https://github.com/user-attachments/assets/c844bf5c-efa7-40d2-87da-e080d41db5dc">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58435443,
  "usedJSHeapSize": 56587811,
  "jsHeapSizeLimit": 4294705152
}
Username = r123123123
Chat ID = a8356ab77e1e
```

**Comment by endocytosis** [comment]
Appreciate the feedback here. We are tracking this issue: [#1791](https://github.com/stackblitz/bolt.new/issues/1791). You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
