### ISSUE TITLE
Dependencies don't load

### ISSUE THREAD

**Issue by mjnyland** [stackblitz/bolt.new#860]
### Describe the bug

dependencies won't install at all, or take a very long time

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-3wbv4y

### Steps to reproduce

1 Try to create any app

2 Get stuck on installing dependencies

### Expected behavior

dependencies to load, and the app to display

### Platform

```
Browser name = Safari
Full version = 17.2.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
performance.memory = undefined
Username = mjnyland
Chat ID = 208854e52f87
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
