### ISSUE TITLE
Issue with deployment

### ISSUE THREAD

**Issue by EliaStein** [stackblitz/bolt.new#864]
### Describe the bug

There was an issue with a connection between my site I built and EmailJS. When the builder fixes it and tries to deploy the fix, it gives me the message of "An error occured while streaming this message." as it tries to complete the step to "build application"

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vkgzgj

### Steps to reproduce

In the chatbox ask if the connection between my site and EmailJS has been fixed
When it goes to deploy the change, the "build application" step fails

### Expected behavior

I would expect that it could resolve the bug and deploy to production.

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 163192736,
  "usedJSHeapSize": 144884876,
  "jsHeapSizeLimit": 4294705152
}
Username = eliastein
Chat ID = 3db3c7ef3d71
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by EliaStein** [comment]
Update: it now looks like the whole site has come down and all my chats with the bolt ai chat box give me the same error message

**Comment by jim80** [comment]
Have you by any chance run out of tokens?

**Comment by EliaStein** [comment]
Where would I find that out? I just subscribed to the pro plan yesterday On Oct 23, 2024, at 4:08 PM, jim80 ***@***.***> wrote:﻿
Have you by any chance run out of tokens?

**Comment by rrupsing-layla** [comment]
Same issue, subscribed today and it's having giving this issue on deployment

**Comment by jim80** [comment]
in bolt.new go to settings and then tokens (via the little button on bottom left corner)
But if it's working otherwise and only fails on deployment it may well be another issue.

**Comment by rrupsing-layla** [comment]
This is what I see:

<img width="506" alt="Screenshot 2024-10-23 at 6 09 54 PM" src="https://github.com/user-attachments/assets/69ffe204-c9b0-413c-a4ba-cb504b2bf7c8">

**Comment by jim80** [comment]
on the per month it looks like you've got about 25 million left to me. However, 0 purchased tokens remaining looks a bit suspect ?
Honestly, I don't know I'm afraid, sorry about that! I've not paid for any tokens as yet, I'm waiting to see how it all develops first...

**Comment by kc0tlh** [comment]
@EliaStein this is a known issue with deployments affecting some users. We are tracking and investigating in #1022
