### ISSUE TITLE
white page 

### ISSUE THREAD

**Issue by jps1990** [stackblitz/bolt.new#867]
### Describe the bug

server not work it's just a white page i don't know why ! 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-txu6fr

### Steps to reproduce

123

### Expected behavior

123

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 131617487,
  "usedJSHeapSize": 123698779,
  "jsHeapSizeLimit": 4294705152
}
Username = jps1990
Chat ID = 1e0f083de6b1
```

**Comment by stevejford** [comment]
Same issue

**Comment by endocytosis** [comment]
Hi all, 

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
