### ISSUE TITLE
TOKEN ISSUE STILL NOT SOLVED

### ISSUE THREAD

**Issue by Filippo295** [stackblitz/bolt.new#868]
> ME: how many lines of code is this program and are they all necessary? dont change it, i just want to know
> 
>BOLT: Let me count the lines of code (excluding empty lines and closing tags):
> 
> App.tsx: ~120 lines
> Chat.tsx: ~85 lines
> CreateGroupModal.tsx: ~80 lines
> EditGroupModal.tsx: ~95 lines
> Events.tsx: ~65 lines
> GroupList.tsx: ~140 lines
> Header.tsx: ~35 lines
> Home.tsx: ~40 lines
> Interests.tsx: ~65 lines
> Profile.tsx: ~40 lines
> Study.tsx: ~65 lines
> Total: Approximately 830 lines of TypeScript/React code
> 
> Are they necessary? Yes, this is actually a well-structured, production-ready application with:
> 
> Clean component separation
> Proper type definitions
> Full CRUD operations
> Real-time chat functionality
> Modal systems for editing/creating
> Responsive design
> Error handling
> User feedback
> Navigation system
> While it could be made more concise by combining similar components (Events/Study/Interests share similar logic), the current structure makes it more maintainable and easier to extend with specific features for each section.
> 
> The code follows best practices and doesn't contain unnecessary bloat. Each component has a single responsibility and the complexity is appropriate for the functionality provided.

This spent 20k tokens, how?! 
As i wrote in the title, the token issue is not fixed (that exchange alone spent 20k, coding obviously consumes even more) meaning that this AI is unusable! I mean, spending 20$ to run out of tokens in a few days is ridiculus, i have not experienced that but according to token consumption and to stories of people to whom that happened, it is a big issue.
And the problem is not prompt optimization btw

**Comment by kc0tlh** [comment]
@Filippo295 please review the explanation of how tokens work in #678 if you're interested in understanding how this all works. A big update to increase efficiency will be announced there tomorrow as well!
