### ISSUE TITLE
Constant fix for the same error 

### ISSUE THREAD

**Issue by KWirePain** [stackblitz/bolt.new#869]
### Describe the bug

It tried to fix the same issue three time essentialy doing the same thing and failing chewing through all the available tokens.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jbxivb

### Steps to reproduce

click the fix error button when it appears

### Expected behavior

it should report that it cannot fix the error or that it is trying to fix the same error.  If it fails to fix the error it should refund the tokens it has used.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 69580519,
  "usedJSHeapSize": 50096735,
  "jsHeapSizeLimit": 4294705152
}
Username = KWirePain
Chat ID = 1e95dd1c8437
```

**Comment by kc0tlh** [comment]
#678 has a collection of best practices to avoid this
