### ISSUE TITLE
Lost chat history

### ISSUE THREAD

**Issue by jlph79** [stackblitz/bolt.new#87]
### Describe the bug

I created a new project, and bolt was following the instructions.
Until at some point bolt looked not making any progress, so I refreshed the page. Then the complete chat history disappeared.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nltpun

### Steps to reproduce

1. Chat to generate app
2. ChatBot looked not making any progress while updating the code
3. I refreshed the page
4. Chat history is lost. 

### Expected behavior

After refreshing the page, I would like to continue with the chat or cancel the 'update' if it seems not making any progress.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 114281981,
  "usedJSHeapSize": 104259201,
  "jsHeapSizeLimit": 4294705152
}
Username = jlph79
Chat ID = 9bfc21243767
```

**Comment by vedantkarandikar** [comment]
Hey, Your API keys are visible when we click this link. Please revoke the Anthropic and Replicate keys.

bolt.new should have some visiblity settings as well
