### ISSUE TITLE
Bolt lost my conversation!! HELP!! How can i get all my work back?

### ISSUE THREAD

**Issue by krischulz** [stackblitz/bolt.new#874]
### Describe the bug

Bolt lost my conversation... I just signed up spent hours working on a project, the servers froze during my build, I logged out logged back in and my conversation was there. This happened several times. When I tried to deploy it got hung up for a few minutes then said server was busy or cannot connect to server so I logged out and tried getting back in... now my conversation doesn't show up. I've used 3MM tokens of my 10MM. How can I get my work back?

### Link to the Bolt URL that caused the error

DIdn't deploy to a url, I used Bolt.new to build

### Steps to reproduce

1) Search my activity and history... for my project

### Expected behavior

Who can check my history and find my conversation? I had only one project, would it really just get deleted spontaneously?

### Screen Recording / Screenshot

none, disappeared before I could

### Platform

Using mac safari v17.1

### Additional context

Who can help me find my project? Does it save anything to Github?

**Comment by kc0tlh** [comment]
#39 has instructions on restoring your chats. A full UI update to solve this is coming very very soon!
