### ISSUE TITLE
Bolt Looping over Errors

### ISSUE THREAD

**Issue by Midas-Coin** [stackblitz/bolt.new#875]
### Describe the bug

Bolt gets stuck in Loops when attempting to Fix an AppWrite Network Auth Issue.

"Auth check error:"{name: "AppwriteException", code: 0, type: "", response: ""}
   at checkAuth (/src/store/authStore.ts?t=1729745759211:66:15)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-kdarhn?autoAuth=true

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4b089002-a383-4457-824d-d1942b95458c)

### Expected behavior

Error should be fixed, and user should be able to be created via AppWrite.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126436583,
  "usedJSHeapSize": 123506935,
  "jsHeapSizeLimit": 2160066560
}
Username = Midas-Coin
Chat ID = 9de1149e518a
```

**Comment by Midas-Coin** [comment]
This is burning my credits, whilst it is just looping over and not fixing the issue. Please refund my credits/ tokens to the original amount.

**Comment by kc0tlh** [comment]
@Midas-Coin tips on error resolution and token usage efficiency have been collected in #678 

Please reach out to hello@stackblitz.com with a specific request around tokens/credits and we will address there, thanks!
