### ISSUE TITLE
App won't deploy

### ISSUE THREAD

**Issue by krischulz** [stackblitz/bolt.new#876]
### Describe the bug

Deploy feature doesn't work, failed to deploy.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-akpgka

### Steps to reproduce

Won't deploy app after hitting deploy button

### Expected behavior

Deploys app

### Screen Recording / Screenshot

![Bolt error](https://github.com/user-attachments/assets/07402fae-b1a4-4848-a5a7-f321db18489a)

### Platform

```
Browser name = Safari
Full version = 17.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
performance.memory = undefined
Username = krischulz
Chat ID = 39111b957cc1
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
Tracking this in #499
