### ISSUE TITLE
See chat history

### ISSUE THREAD

**Issue by Aby0203** [stackblitz/bolt.new#879]
**Is your feature request related to a problem? Please describe:** See chat history

**Describe the solution you'd like:** See chat history

**Describe alternatives you've considered:** See chat history

**Additional context:** See chat history

**Comment by artisleilands** [comment]
Same here, chat history does not exist.

**Comment by chidinweke** [comment]
This issue will be addressed very soon.

https://github.com/stackblitz/bolt.new/issues/39

**Comment by kc0tlh** [comment]
@chidinweke is correct! Workarounds are posted in #39, and the full UI update is coming very soon
