### ISSUE TITLE
Nothing work for me, i have tested 3 website creation. Give me blank page every times

### ISSUE THREAD

**Issue by Thomaseustache** [stackblitz/bolt.new#881]
### Describe the bug

Nothing work

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-r8ft7n

### Steps to reproduce

Try on website creation

### Expected behavior

Show me something.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by nucks** [comment]
Same here

**Comment by kc0tlh** [comment]
Lots of tips on how to use Bolt in #678 that should be helpful
