### ISSUE TITLE
If you refresh the page you loose the ability to undo something, which is critical

### ISSUE THREAD

**Issue by titusfx** [stackblitz/bolt.new#882]
### Describe the bug

If you refresh the page you loose the ability to undo something, which is critical

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gngrxc

### Steps to reproduce

If you refresh the page you loose the ability to undo something, which is critical

### Expected behavior

If you refresh the page you loose the ability to undo something, which is critical

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66427127,
  "usedJSHeapSize": 58763787,
  "jsHeapSizeLimit": 4294705152
}
Username = titusfx
Chat ID = e88354ef4242
```

**Comment by kc0tlh** [comment]
This will be fixed very soon in issue #39
