### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by JamalMohammed143** [stackblitz/bolt.new#883]
### Describe the bug

When am asking deploy my app, it throwing error 

![image](https://github.com/user-attachments/assets/c5ca1783-b78f-4c12-af51-255a1f424fa4)

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-nisx8h

### Steps to reproduce

1. Created nextjs project
2. asked to create one game for me 
3. asked to deploy that app

### Expected behavior

it should deploy my app

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/fdf80474-7dc3-4ded-8f9c-67df57e14324)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47560469,
  "usedJSHeapSize": 44033413,
  "jsHeapSizeLimit": 2160066560
}
Username = JamalMohammed143
Chat ID = 4bed19824d2b
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@JamalMohammed143 tracking this in #1022
