### ISSUE TITLE
npm install doesn't complete

### ISSUE THREAD

**Issue by daveloe** [stackblitz/bolt.new#886]
### Describe the bug

I wanted to "load" a project I started previously. Then when it installs dependencies, npm install would never complete and I see only:

~/project
❯ npm install
[..................] \ idealTree:project: sill idealTree buildDeps

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ry2xky

### Steps to reproduce

1. select previous chat
2. wait (forever)

### Expected behavior

It should install all dependencies and I should be able to continue building the app.

### Platform

```
Browser name = Safari
Full version = 17.3.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
performance.memory = undefined
Username = daveloe
Chat ID = 88055d9bfa27
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2021
