### ISSUE TITLE
STUCK IN isssues

### ISSUE THREAD

**Issue by rizvinewed** [stackblitz/bolt.new#887]
### Describe the bug

stuck in a loop, once it generate the wrong code, it will stuck up there, not able to figure out new way of deling the issue, it's like if it is done the work then done in first time or just leave it otherwise it will not make it better or fix the issue in nxt shot

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qp5sfw

### Steps to reproduce

i want to build a youtube banner downloader

### Expected behavior

i am exepecting to resovle the issue and give me correct output but it goes in process of errror handling not, solving the issuese

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 99439230,
  "usedJSHeapSize": 95791898,
  "jsHeapSizeLimit": 2160066560
}
Username = rizvinewed
Chat ID = 29d3f276e2db
```

**Comment by kc0tlh** [comment]
#678 has many tips related to resolving issues more efficiently
