### ISSUE TITLE
Give us a history to switch between versions

### ISSUE THREAD

**Issue by NoahWiedemer** [stackblitz/bolt.new#89]
**Is your feature request related to a problem? Please describe:**
When a change is bufggy, i have no way of going back and have to fix it manually or try to reverse via prompting. Biiig nono :(

**Describe the solution you'd like:**
Each change could be a commit and i can chosse between all commits by selecting a version

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hey! Thanks for raising this issue!

We're tracking this internally, and https://github.com/stackblitz/bolt.new/issues/35 is a similar feature request. I'm going to close this issue, feel free to subscribe for updates in the other issue! We'll keep you posted 🙌
