### ISSUE TITLE
Fix the issue manually or rollback to a previous checkpoint

### ISSUE THREAD

**Issue by karalar2017** [stackblitz/bolt.new#891]
### Describe the bug

Bolt.new is telling me "Bolt tried to fix problems 6 times but failed. To prevent spending more tokens, you might want to try to fix them manually or rollback to a previous checkpoint instead."

If I had enough coding knowledge to fix the issues manually, why would I pay the fee for Bolt.new?

Do you suggest me to proceed with Replit or another platform? I guess it will not be a good impression for your platform on Youtube and the other social media channels that Bolt.new is suggesting  to code manually

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jkcwbc

### Steps to reproduce

??

### Expected behavior

I expect Bolt.new could do the simple Supabase connection and show the values on the website properly

### Screen Recording / Screenshot

![Bolt screenshot](https://github.com/user-attachments/assets/7159cf1d-ba28-4c48-8d04-7a52fb7921ad)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@karalar2017 AI is not all powerful yet unfortunately so human intervention is sometimes required for success on all AI powered platforms.

#678 has lots of tips on how to improve your prompts for better results (including when debugging)
Here is a tutorial on using Firebase as a backend: https://x.com/sulco/status/1850937685512478850

If you do end up wanting to switch platforms, I can get you a refund via hello@stackblitz.com
