### ISSUE TITLE
 prompt is too long: 200099 tokens > 199999 maximum

### ISSUE THREAD

**Issue by orkhanart** [stackblitz/bolt.new#893]
### Describe the bug

I created a lot of code in last few days, built an amazing product, but now i can't continue it says 
prompt is too long: 200099 tokens > 199999 maximum. whats your advise?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pwqxrd

### Steps to reproduce

Ask for any new code implementation

### Expected behavior

to code next feature

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lcgarza10** [comment]
Do you still have the issue? Im in the same situation started last night but it appeared jsut once, now again I thought it was becasue i had less then 10k tokens and I made a recharge now I have 10M but cant use, still getting the same msg

**Comment by orkhanart** [comment]
Yes, I have over 50 million tokens, which I believe is tied to the scale of the project. It seems that beyond a certain volume of work, the ai struggles to manage and retain information effectively for reasoning. In my case, after a while, it began to exhibit hallucinations and even deleted elements it had previously generated.

**Comment by lcgarza10** [comment]
I don't see any answer from them, some update that says that they are working on, we can't just leave our projects as this, I was almost finishing mine. What other competitors we can use instead of this one?

**Comment by lcgarza10** [comment]
what is indeed working flawlessly is the token usage... that guy is still reducing my tokens every time he gave me an incomplete answer

**Comment by lcgarza10** [comment]
Fix xxxx Type Conversion

src/app/services/xxx.service.ts
This message didn't complete its response.

**Comment by kc0tlh** [comment]
@orkhanart thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!

**Comment by lcgarza10** [comment]
I still dont get the credit that you guys said will credit?

**Comment by lcgarza10** [comment]
Please apply the credit on my account, please see below

Begin forwarded message:

**Comment by kc0tlh** [comment]
@lcgarza10 please do not hijack other users issues. I will respond in your issue #911
