### ISSUE TITLE
 An error occured while streaming this message.

### ISSUE THREAD

**Issue by jaimedevelop** [stackblitz/bolt.new#894]
### Describe the bug

~/project 9s
❯ npx vite build
vite v5.4.10 building for production...
✓ 17 modules transformed.
x Build failed in 3.03s
error during build:
Could not resolve "./pages/ResortSearch" from "src/App.tsx"
file: /home/project/src/App.tsx

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-evaagb

### Steps to reproduce

check video

### Expected behavior

I am not a programmer so I do not know what is happening

### Screen Recording / Screenshot

https://screenrec.com/share/KYNCfEkeRU

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103472835,
  "usedJSHeapSize": 94779451,
  "jsHeapSizeLimit": 2172649472
}
Username = jaimedevelop
Chat ID = f0a5d736c6dc
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@jaimedevelop tracking this in #1022. Thanks for the video and feedback!
