### ISSUE TITLE
Preview fails to load

### ISSUE THREAD

**Issue by chatwellai** [stackblitz/bolt.new#896]
### Describe the bug

After most new updates (I enter a chatt into prompt box and bolt modifies code), the preview box shows only a blank white canvas. I refresh, log out, log in, etc. but no change

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-6f2b4l

### Steps to reproduce

1. type instruction into prompt field
2. hit blue arrow to send command.
3. wait for bolt to implement changes
4. Now error occurs

### Expected behavior

show visual preview of code output

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 44653185,
  "usedJSHeapSize": 43603609,
  "jsHeapSizeLimit": 4294705152
}
Username = matthewbrunken
Chat ID = 657d3a539448
```

**Comment by endocytosis** [comment]
Hi @chatwellai,

Appreciate the feedback here. We are tracking this issue: #1791. You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
