### ISSUE TITLE
 prompt is too long: 211833 tokens > 199999 maximum

### ISSUE THREAD

**Issue by lcgarza10** [stackblitz/bolt.new#897]
### Describe the bug

prompt is too long: 211833 tokens > 199999 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-dpmtx9

### Steps to reproduce

with any prompt even a Hi, it tells me this... I thought it was because I had less than 10k tokens so I made a recharge now i have 10Million tokens and I can not use bolt, please help

### Expected behavior

prompt is too long: 211833 tokens > 199999 maximum

### Screen Recording / Screenshot

with any prompt even a Hi, it tells me this... I thought it was because I had less than 10k tokens so I made a recharge now i have 10Million tokens and I can not use bolt, please help

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55600357,
  "usedJSHeapSize": 50477813,
  "jsHeapSizeLimit": 4294705152
}
Username = lcgarza10
Chat ID = 95d6f0cf0326
```

**Comment by kc0tlh** [comment]
@lcgarza10 @ashiabbott thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!
