### ISSUE TITLE
"creating initial files" step does not complete, so the project is stuck

### ISSUE THREAD

**Issue by yilmazdurmaz** [stackblitz/bolt.new#9]
### Describe the bug

![image](https://github.com/user-attachments/assets/8eac6748-3573-4aea-a443-a15bf851c0c3)

Developer console shows these messages:

````
bolt.new/:1  Unchecked runtime.lastError: The message port closed before a response was received.
hook.js:591  Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vi (components-BaTg7EkE.js:22:4788)
    at Oc (components-BaTg7EkE.js:24:45269)
    at Rc (components-BaTg7EkE.js:24:39500)
    at Ep (components-BaTg7EkE.js:24:39473)
    at _c (components-BaTg7EkE.js:24:34528)
    at C (components-BaTg7EkE.js:9:1561)
    at MessagePort.ne (components-BaTg7EkE.js:9:1928)
overrideMethod @ hook.js:591
Show 1 more frame
Show less
26components-BaTg7EkE.js:22  Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vi (components-BaTg7EkE.js:22:4788)
    at Oc (components-BaTg7EkE.js:24:45269)
    at Rc (components-BaTg7EkE.js:24:39500)
    at Ep (components-BaTg7EkE.js:24:39473)
    at _c (components-BaTg7EkE.js:24:34528)
    at C (components-BaTg7EkE.js:9:1561)
    at MessagePort.ne (components-BaTg7EkE.js:9:1928)
components-BaTg7EkE.js:24  Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vi (components-BaTg7EkE.js:22:4788)
    at Oc (components-BaTg7EkE.js:24:45269)
    at Rc (components-BaTg7EkE.js:24:39500)
    at Ep (components-BaTg7EkE.js:24:39473)
    at _c (components-BaTg7EkE.js:24:34528)
    at C (components-BaTg7EkE.js:9:1561)
    at MessagePort.ne (components-BaTg7EkE.js:9:1928)
components-BaTg7EkE.js:22  Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vi (components-BaTg7EkE.js:22:4788)
    at Oc (components-BaTg7EkE.js:24:45269)
    at Rc (components-BaTg7EkE.js:24:39500)
    at Ep (components-BaTg7EkE.js:24:39473)
    at _c (components-BaTg7EkE.js:24:34528)
    at C (components-BaTg7EkE.js:9:1561)
    at MessagePort.ne (components-BaTg7EkE.js:9:1928)
components-BaTg7EkE.js:24  Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Oc (components-BaTg7EkE.js:24:44929)
    at Rc (components-BaTg7EkE.js:24:39500)
    at Sp (components-BaTg7EkE.js:24:39431)
    at ml (components-BaTg7EkE.js:24:39289)
    at io (components-BaTg7EkE.js:24:35706)
    at _c (components-BaTg7EkE.js:24:34662)
    at C (components-BaTg7EkE.js:9:1561)
    at MessagePort.ne (components-BaTg7EkE.js:9:1928)
content.js:9  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertRule')
    at sh (content.js:9:48777)
    at d (content.js:9:51119)
    at Object.start (content.js:9:51394)
    at content.js:9:557721
    at kh (content.js:9:50257)
93[Deprecation] -ms-high-constrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
5[Deprecation] -ms-high-contrast-adjust is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
content.js:2  Error: <svg> attribute viewBox: Expected number, "0 0 100% 3".
y @ content.js:2
Show 1 more frame
Show less
4content.js:9  Uncaught TypeError: Cannot read properties of undefined (reading 'target')
    at content.js:9:528113
455Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again
````

### Link to the Bolt URL that caused the error

do not matter

### Steps to reproduce

1- any prompt should do
2- watch project file creation
3- watch the initial files step does not complete

### Expected behavior

all files created fine along with initial templates

### Platform

- Windows 10 22H2 64 bit up-to-date
- Edge 129.0.2792.65 (Official build) (64-bit) up-to-date

**Comment by yilmazdurmaz** [comment]
@codenomnom  Those steps did not show up for me. did you use MS Edge, or other browsers?

**Comment by codenomnom** [comment]
Chrome 🤷

**Comment by yilmazdurmaz** [comment]
I also tried with Vue to no avail.

I think it depends on the browser. Another issue has mentioned Brave browser saw similar problems (but also got successful tries).

**Comment by chrismahoney** [comment]
@yilmazdurmaz I dug up Chrome and went through the steps that were leading me to this issue, and it seems there is no problem at least with:
- macOS Sequoia 15.0
- Chrome Version 129.0.6668.89 (Official Build) (arm64)

Prompt that failed with described errors in Brave Browser: "Simple express API based on the OpenAPI Pet Store example."

# Brave UI Result (Failure):
<img width="1489" alt="Brave-Failures-ExpressPetStore" src="https://github.com/user-attachments/assets/76aa3f5c-7d04-451c-a4bd-60a5ceb4962c">

# Chrome UI Result (All good):
![Chrome-Success-ExpressPetStore](https://github.com/user-attachments/assets/7d453548-b686-4377-b647-726ffc6fe87a)

Hope this helps!

**Comment by tsimms** [comment]
I also experienced this issue. I'm on a Mac 14.4.1, Chrome 129.0.6668.90. I posted a screenshot here:
https://discord.com/channels/364486390102097930/1291554476746084363/1291554476746084363

**Comment by mrmachine** [comment]
Same problem here. On Chrome and Edge on macOS 14.

**Comment by chrismahoney** [comment]
Good news, at least on my end. Had the sudden realization that a bunch of us are probably running some wacky Chrome extensions related to web dev after reading [the actual React minification error](https://react.dev/errors/418?invariant=418):

```
Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch
```

> **It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.**

Definitely have a few of that sort of extension. I went into Private Browsing and attempted Vite & Remotion again, the UI fires up immediately and works fine:

<img width="1608" alt="Brave-Private-Vite_OK" src="https://github.com/user-attachments/assets/217e2226-3959-4ef1-a3dc-7eb1a9ad01fd">

<img width="1608" alt="Brave-Private-Remotion_OK" src="https://github.com/user-attachments/assets/f13b780d-a259-4d0e-8c6d-93433bdf7fb5">

Prompt worked exactly as expected:

<img width="1608" alt="Brave-Private-Remotion_PurplePrompt" src="https://github.com/user-attachments/assets/e53a442a-b917-4693-9cd3-02e89d1655a7">

**Comment by mrmachine** [comment]
Still does not work for me in Edge private window with all extensions disallowed in private 😭

**Comment by samdenty** [comment]
This issue was caused by a Remix React SSR Hydration mismatch, because a browser extension (or this browser itself) modified the dom. We've just shipped a fix, feel free to test and report back

**Comment by yilmazdurmaz** [comment]
@samdenty, It works fine for me now.

I haven't changed anything with my extensions, so my bet is on SSR.

**Comment by tsimms** [comment]
Working for me now as well. Thank you @samdenty!
