### ISSUE TITLE
I always get Forbidden Response even after subscribing to pro.

### ISSUE THREAD

**Issue by johnattanarcilla** [stackblitz/bolt.new#90]
### Describe the bug

I always get Forbidden Response even after subscribing to pro.

### Steps to reproduce

normal prompt

### Expected behavior

Return what has been prompted. Currently it always returns Forbidden.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 341239601,
  "usedJSHeapSize": 335341341,
  "jsHeapSizeLimit": 4294705152
}

```

**Comment by burryxie** [comment]
The same. Always forbidden. But I have no sucscription for now

**Comment by SamVerschueren** [comment]
Closing this in favour of #77.

**Comment by samdenty** [comment]
we've just shipped a fix for the forbidden / trouble connecting to server in from certain location errors, please confirm it now works!
