### ISSUE TITLE
Application Stuck on repeat.  

### ISSUE THREAD

**Issue by jaywakeford** [stackblitz/bolt.new#900]
### Describe the bug

Significant repeat of the the same error.     

- tried many potential solutions.  Refreshed page, burning tokens on retries, signout , signin, left overnight, retried ,...  . presented the partially completed script and requested bolt to complete it, still failed.    That sends me into a loops burning many tokens.  Odd considering the script is 95 lines of sql , pretty simple.      After somewhere in the area of 15 times repeating this and millions of wasted tokens I am trying to remain patient but falling short.     

This is one series of repeating incidents.  This is an intermittent disruptive and costly error.     

All that said, the performance is overall excellent , especially with the new updates.        I am also building a significantly large application.    Trying my best to be patient on that basis.  

But for simple tasks this seems more like a deficiency in the set up.   Should not have this many failed repeats.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wlgkaw

### Steps to reproduce

It is intermittent but stuck solid when it fails. 

### Expected behavior

Simply write a script into the directory and complete the script.  

### Screen Recording / Screenshot

<img width="358" alt="Screenshot 2024-10-24 145231" src="https://github.com/user-attachments/assets/554ec406-60cb-4491-8787-8dc425475646">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92712765,
  "usedJSHeapSize": 85942773,
  "jsHeapSizeLimit": 4294705152
}
Username = jaywakeford
Chat ID = 1da46d2950cd
```

### Additional context

I have suffered with this for the last week but frustrated enough now to report it and hope for a resolution.

**Comment by kc0tlh** [comment]
@jaywakeford this serious issue is being tracked and investigated in #1073
