### ISSUE TITLE
Preview screen blank - tokens being chewed up!

### ISSUE THREAD

**Issue by OliLegitGit** [stackblitz/bolt.new#901]
### Describe the bug

I am a new user to bolt and keen to test its capabilities. I have attempted some requests, and code has been generated, but in each instance the Preview screen is blank.

![image](https://github.com/user-attachments/assets/006e1784-a1c1-44d8-9904-2f69c07d1c56)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-76smdv

### Steps to reproduce

Prompt what I wanted to build
Observe files being created and code generated
Once completed, click on the Preview tab
Observe blank preview screen

Tested in new chat - same behavior  

### Expected behavior

Preview the front-end that has been generated based on the prompt

### Platform

- Windows
- Chrome
- Version 130.0.6723.70

**Comment by endocytosis** [comment]
Appreciate the feedback! This is a known issue and is being tracked here: #1791.
