### ISSUE TITLE
wasting credits while giving non working code

### ISSUE THREAD

**Issue by dbiznis69** [stackblitz/bolt.new#904]
### Describe the bug

it keeps giving me errors every time it does npx vite build while trying to deploy. ive wasted 90% of my credits trying to fix issues and it keeps giving me the same stuff over and over again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dv2kyg

### Steps to reproduce

npx vite build

### Expected behavior

deploy to netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 156521285,
  "usedJSHeapSize": 147287077,
  "jsHeapSizeLimit": 2160066560
}
Username = dbiznis69
Chat ID = a7a40bad1dd0
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@dbiznis69 apologies for the frustrating experience during the beta.

#678 has some general tips for using tokens efficiently and debugging errors, and we are tracking some deploy issues in #499
