### ISSUE TITLE
Bug Report: 10m tokens used after a single console error & page reload

### ISSUE THREAD

**Issue by AdrianBM96** [stackblitz/bolt.new#908]
### Describe the bug

I was developing an application when suddenly a loop error started appearing all the time, and when I reloaded the page +10M tokens had been subtracted, I had just bought 20M a few hours ago.

The error is: Of "Error fetching jobs:"{code: "failed-precondition", customData: undefined, name: "FirebaseError"}

Please help.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m2nysw

### Steps to reproduce

I was developing an application when suddenly a loop error started appearing all the time, and when I reloaded the page +10M tokens had been subtracted, I had just bought 20M a few hours ago.

The error is: Of "Error fetching jobs:"{code: "failed-precondition", customData: undefined, name: "FirebaseError"}

Please help.

### Expected behavior

I was developing an application when suddenly a loop error started appearing all the time, and when I reloaded the page +10M tokens had been subtracted, I had just bought 20M a few hours ago.

The error is: Of "Error fetching jobs:"{code: "failed-precondition", customData: undefined, name: "FirebaseError"}

Please help.

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 44376107,
  "usedJSHeapSize": 43331243,
  "jsHeapSizeLimit": 4294705152
}
Username = AdrianBM96
Chat ID = 6787e7307aa4
```

**Comment by kc0tlh** [comment]
@AdrianBM96 if you have not already, please reach out to hello@stackblitz.com so we can credit you $10 for the missing credits. I will also be adding this to the queue for eng to investigate!

**Comment by AdrianBM96** [comment]
@kc0tlh I sent it but I haven't had any response from a week.

**Comment by kc0tlh** [comment]
Just responded, sorry for the delay! Linking this to #1148 for further investigation by eng as well!
