### ISSUE TITLE
aplikachonen kraschar 

### ISSUE THREAD

**Issue by Viktor-berg5061** [stackblitz/bolt.new#91]
### Describe the bug

Applikationsfel
Fel: Det gick inte att köra 'insertBefore' på 'Node': Noden före vilken den nya noden ska infogas är inte en underordnad till denna nod.
    på till (https://bolt.new/assets/components-g8_Fbz61.js:24:25478)
    på je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    på gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27717)
    på Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    på gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    på Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    på gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    på Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    på gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    på Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-umvjz3

### Steps to reproduce

vet inte

### Expected behavior

att det ska funka 

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 357910117,
  "usedJSHeapSize": 341792705,
  "jsHeapSizeLimit": 2172649472
}
Username = Viktor-berg5061
Chat ID = 7db8c9431991
```

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

We're tracking this issue internally and will let you know when we have a resolution.

**Comment by AriPerkkio** [comment]
Hey @Viktor-berg5061, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
