### ISSUE TITLE
 This message didn't complete its response.

### ISSUE THREAD

**Issue by lcgarza10** [stackblitz/bolt.new#910]
### Describe the bug

getting many messages and it doesnt finish the task "This message didn't complete its response. "

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-2terty

### Steps to reproduce

getting many messages and it doesnt finish the task "This message didn't complete its response. "

### Expected behavior

getting many messages and it doesnt finish the task "This message didn't complete its response. "

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51077336,
  "usedJSHeapSize": 46444664,
  "jsHeapSizeLimit": 4294705152
}
Username = lcgarza10
Chat ID = 9bb6e80e2f6b
```

**Comment by kc0tlh** [comment]
Tracked in #1073
