### ISSUE TITLE
This message didn't complete its response. I spent complete refill of 20 usd today for nothing and lost entire day please fix this asap

### ISSUE THREAD

**Issue by lcgarza10** [stackblitz/bolt.new#911]
### Describe the bug

This message didn't complete its response. I spent complete refill of 20 usd today for nothing and lost entire day please fix this asap

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-2terty

### Steps to reproduce

This message didn't complete its response. I spent complete refill of 20 usd today for nothing and lost entire day please fix this asap

### Expected behavior

This message didn't complete its response. I spent complete refill of 20 usd today for nothing and lost entire day please fix this asap

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = lcgarza10
Chat ID = fcbb864adf62
```

**Comment by kc0tlh** [comment]
@lcgarza10 tracking this in #1022 

Please reach out to hello@stackblitz and we can credit you for the $20. 

Additionally, checkout the tips in #678 to increase your efficiency of token usage

**Comment by lcgarza10** [comment]
Hi Asking for an update on this pending credit  for the $20 on my account @lcgarza10

I’d like to  for $40 instead of $20, since this issue  happened for a complete week where I spent more than $60 you can check the history of the refills I had to do.

Issue is fixed now btw,

Please see below conversation

**Comment by lcgarza10** [comment]
HiAny update on my pending credit to be applied?Thanks ,CarlosOn Oct 30, 2024, at 9:43 AM, Carlos Garza ***@***.***> wrote:﻿Hi Asking for an update on this pending credit  for the $20 on my account @lcgarza10I’d like to  for $40 instead of $20, since this issue  happened for a complete week where I spent more than $60 you can check the history of the refills I had to do.Issue is fixed now btw,Please see below conversationOn Oct 29, 2024, at 2:25 PM, Alexander Berger ***@***.***> ***@***.*** tracking this in #1022Please reach out to ***@***.*** and we can credit you for the $20.Additionally, checkout the tips in #678 to increase your efficiency of token usage—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by lcgarza10** [comment]
Hi Alexander,
Stil I dont get the credit, I have sent the email twice but still no answer and Im just out of credits now and I would like to spend another 20 today, hopefully you can help me 
and If Im not asking much I would like you to re consider the credit amount since I spent more than 40 due to that issue last week

**Comment by kc0tlh** [comment]
@lcgarza10 I have no emails from you in hello@stackblitz.com. Please try again.

<img width="886" alt="image" src="https://github.com/user-attachments/assets/a4f06cae-54a8-474f-8e2b-181fa3e7cb46">

**Comment by lcgarza10** [comment]
Hi, Attached you will see the amount of emails I have sent to ***@***.***’m not sure what you mean by hijacking, but I just want to receive the credit you said I was going to receive due to this issue inconvenience to continue with my project. Username lcgarza10Thank youGracias,CarlosOn Nov 2, 2024, at 5:51 PM, Alexander Berger ***@***.***> wrote:﻿
@lcgarza10 I have no emails from you in ***@***.*** Please try again.
image.png (view on web)

**Comment by kc0tlh** [comment]
@lcgarza10 As a one-time courtesy, I have issued you a one time $40 credit. More details to follow to your email address: lcgarza10@gmail.com

**Comment by lcgarza10** [comment]
Thank You!
I still dont see it on my tokens balance, will it take few minutes to appear here?
￼

**Comment by kc0tlh** [comment]
Check your email now for all the details!
