### ISSUE TITLE
Chat disappeared

### ISSUE THREAD

**Issue by arblark** [stackblitz/bolt.new#914]
### Describe the bug

Yesterday I was doing a project, after the tokens ran out I decided to finish it the next day. Today I log in and there is no yesterday’s chat in the chat panel. After reloading the page, browser, etc., the chat does not appear.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

1. Go to the website bolt.new
2. Waiting for the full download
3. Open the side menu

### Expected behavior

We need to find out why the chat disappeared, although it exists via a link, and how to prevent this in the future

### Platform

- OS: win10
- Browser: Chrome
- Version: 130.0.6723.70

**Comment by kc0tlh** [comment]
@arblark this issue and workarounds are tracked in #39
