### ISSUE TITLE
Pushing it to netlify is not working

### ISSUE THREAD

**Issue by DomM16** [stackblitz/bolt.new#915]
### Describe the bug

My code is working on local but bolt can't push it to netlify.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dg3xee

### Steps to reproduce

just go to my bolt and ask it to push to netlify

### Expected behavior

It should push to netlify

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 176905357,
  "usedJSHeapSize": 155816081,
  "jsHeapSizeLimit": 4294705152
}
Username = dominkobambinko
Chat ID = e0bde2abb77e
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@DomM16 tracking this in #1022
