### ISSUE TITLE
can't deploy

### ISSUE THREAD

**Issue by DreamerLark** [stackblitz/bolt.new#918]
### Describe the bug

> ❯ npm run build
> 
> > timestamp-converter@0.0.0 build
> > tsc && vite build
> 
> Version 5.6.3
> tsc: The TypeScript Compiler - Version 5.6.3                                                         
>                                                                                                   TS 
> COMMON COMMANDS
> 
>   tsc
>   Compiles the current project (tsconfig.json in the working directory.)

it seems error with build params

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-m65vkw

### Steps to reproduce

click deploy buttong

### Expected behavior

deploy success

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72889964,
  "usedJSHeapSize": 70480072,
  "jsHeapSizeLimit": 4294705152
}
Username = DreamerLark
Chat ID = 225e33f34f1f
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by DreamerLark** [comment]
when i edit package.json ,rewrite ""build": "tsc & vite build"  to "build": "vite build", deploy success, so i think is tsc loss some params.

**Comment by kc0tlh** [comment]
@DreamerLark this is being tracked in #1022. Thanks for the helpful feedback, I reposted there!
