### ISSUE TITLE
An error occured while streaming this message.

### ISSUE THREAD

**Issue by gadget-guys** [stackblitz/bolt.new#922]
### Describe the bug

I'll start the deployment process to Netlify. The site will be built and deployed automatically. Once the deployment is complete, you'll receive a unique URL where your site is live.

Let me check the deployment status...

An error occured while streaming this message.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-knayg7

### Steps to reproduce

I'll help you deploy the application to Netlify. First, let's make sure everything is ready for deployment.

### Expected behavior

It would finish and provide me with the URL; plus, when I asked it to save the files for me, to upload to Bluehost, or help me get everything ready to host on BH, It couldn't do that as it only wanted to use Netlify.

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/49e5380a-250b-47a6-8ee7-1ecab1e5d7c7

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 128558240,
  "usedJSHeapSize": 120482240,
  "jsHeapSizeLimit": 4294705152
}
Username = gadget-guys
Chat ID = 7df76d434255
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@gadget-guys this is being tracked in #1022
