### ISSUE TITLE
Truncates new code Destroying all my work

### ISSUE THREAD

**Issue by Caderial15** [stackblitz/bolt.new#93]
### Describe the bug

The Ai when i make a request , starts writing out the code but truncates all the "Currently working" or "Unchanged" portions of the code deleting it and replacing it with /* ...  rest of code remains the same... */ or /* ...keep existing code ... */ things like that. making it ear impossible for me to work without constantly undoing its work.

I usually have to specify with each message i send  "DO NO TRUNCTAE MY CODE, Rewrite my full code when ever making changes." Sometimes that woks sometimes it doesn't. Usually when I Restart the conversation, it works for a while and then starts truncating after a few messages.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-9yluzj

### Steps to reproduce

ask the AI do changes something specific a certain part or block of a page, it will delete everything around it and only re-write the code for the portion requested for changes, everything else is replaced by a truncating message, or not at all, just deletes all the other code and 

### Expected behavior

I should ither ONLY dit the portions needed for the changes OR ALWAYS re-write all my code verbatim in full except for the changes being made.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows 11, Chrome Version 129.0.6668.90 (Official Build) (64-bit)

Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 11 Home
Version	23H2
Installed on	‎6/‎10/‎2024
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

We're tracking this issue internally and will let you know when we have a resolution.

**Comment by samdenty** [comment]
This is pretty frustrating indeed!

We're tracking this internally. You can follow #124 to get notified when we've resolved this issue.

**Comment by kc0tlh** [comment]
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.
