### ISSUE TITLE
I ran in to a minor issue and i dont know what is wrong

### ISSUE THREAD

**Issue by ChasBaer** [stackblitz/bolt.new#930]
### Describe the bug

Before it had been compiling ok, then I asked it to change the colours of the fonts and it had crashed 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rzk6wb

### Steps to reproduce

1 I was looking at the website, then I noticed a problem with words being difficult to read because of their dark background
2 I suggested to AI that it should fixed
3 It fixed everything then it refused to work

### Expected behavior

I expect it to work

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 692260904,
  "usedJSHeapSize": 659348296,
  "jsHeapSizeLimit": 4294705152
}
Username = ChasBaer
Chat ID = 2bc77c4a7c2c
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@ChasBaer thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
