### ISSUE TITLE
This message didn't complete its response.

### ISSUE THREAD

**Issue by paulgosnell** [stackblitz/bolt.new#932]
### Describe the bug

See this every 5 messages today - very frustrating as burning through tokens as have to resend the message each time so everything is taking 5 times as long and costing me 5 times the tokens

### Link to the Bolt URL that caused the error

https://bolt.new/~/chilledcrm-puskmq

### Steps to reproduce

send a message 

### Expected behavior

to not see this message

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103123171,
  "usedJSHeapSize": 83991743,
  "jsHeapSizeLimit": 2172649472
}
Username = paulgosnell
Chat ID = bda980dd2ab7
```

**Comment by kc0tlh** [comment]
@paulgosnell tracking this in #1073
