### ISSUE TITLE
can not restore repo after webcontainer crash

### ISSUE THREAD

**Issue by geminiyellow** [stackblitz/bolt.new#935]
### Describe the bug

can not restore repo after webcontainer crash.
it run npm install very very long time.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dzwasw

### Steps to reproduce

1. crash
2. refresh browser
3. wait 

### Expected behavior

i want my chat history and restore this project.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91449508,
  "usedJSHeapSize": 60140492,
  "jsHeapSizeLimit": 4294705152
}
Username = geminiyellow
Chat ID = 8536c2370f10
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [[stackblitz.com](http://stackblitz.com/)](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
