### ISSUE TITLE
I upgraded to the higher version, came back, and all (chat) memory was lost

### ISSUE THREAD

**Issue by gitlevo** [stackblitz/bolt.new#937]
### Describe the bug

I've build the framework for an amazing app with your tool, just within 2 days. 

Now I need to heavily restore it from a backup I made some hours ago, since bolt.new cant remember or restore checkpoints from 2 minutes (!!) ago, just because I upgraded the plan. Now fixing manually since 2 hours... 

I also tried to import my backup project from git, but thats not possible (bolt.new not available for my git project!?) - just wanted to give you that feedaback because I strongly believe your product rocks!!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7v7d6s

### Steps to reproduce

create a project, web app for 2 days, try to implement all supabase functionalities, leave the chat and come back -> tell bolt.new to recreate the last version -> no checkpoint memory for version before leaving the chat. also asking to restore the currently deployed version not possible

### Expected behavior

give me the full functional version before the crash 2 minutes ago (checkpoint feature, but working after leaving and coming back to chat)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67679763,
  "usedJSHeapSize": 63799743,
  "jsHeapSizeLimit": 4294705152
}
Username = gitlevo
Chat ID = 7399081abc2f
```

**Comment by kc0tlh** [comment]
@gitlevo check #39 for the current workaround and for updates on the complete solution, coming soon. TLDR: your work is not lost, just not showing properly in the UI. Appreciate your patience during this beta!
