### ISSUE TITLE
Bolt.new repeatedly fails when adding new content

### ISSUE THREAD

**Issue by joemurrayaz** [stackblitz/bolt.new#939]
### Describe the bug

Bolt.new is alpha software which has not been tested. I can't believe they are charging for the software. I have tried using it to create a real production website and my efforts are futile.  Sometimes when adding something as simple as a new page, the software reports an error "An error occured while streaming this message.".  Many times when adding new features to the home page, it would forget about different things that I had previously added and revert back to old content. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-azl8cn

### Steps to reproduce

Try to create a real production website.

### Expected behavior

The software should not generate random errors such as "An error occured while streaming this message."  The software should not forget things that I previously added to the page. 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106866577,
  "usedJSHeapSize": 86926841,
  "jsHeapSizeLimit": 4294705152
}
Username = joemurrayaz
Chat ID = f3bf9ecbb92e
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@joemurrayaz thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!

I also encourage you to check out #678 for bolt usage tips and tricks!
