### ISSUE TITLE
They don't install pm install and it's spending a lot of tokens with problems that I generate alone

### ISSUE THREAD

**Issue by vmsebas** [stackblitz/bolt.new#944]
### Describe the bug

~/project
❯ npm install

~/project 4m 27s
❯ npm install

added 271 packages in 5m

65 packages are looking for funding
  run `npm fund` for details

~/project 4m 49s
❯ npx prisma generate && npx prisma db push && npm run dev
[callSiteLocation@
depd@
@
@
@
@
@
@
@
_0x34b746@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:792686
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14247
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14863
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10277
executeUserEntryPoint@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:1646
internal/main/run_main_module@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:138:405
_0x5e2a11@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1427905
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:889971
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1458345]

Node.js v18.20.3

~/project 1s
❯ npx prisma generate && npx prisma db push && npm run dev
[callSiteLocation@
depd@
@
@
@
@
@
@
@
_0x34b746@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:792686
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14247
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14863
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10277
executeUserEntryPoint@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:1646
internal/main/run_main_module@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:138:405
_0x5e2a11@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1427905
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:889971
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1458345]

Node.js v18.20.3

~/project 1s
❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-25T17_52_03_259Z-debug-0.log

~/project 1m 10s
❯ npx prisma generate && npx prisma db push && npm run seed && npm run dev
[callSiteLocation@
depd@
@
@
@
@
@
@
@
_0x34b746@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:792686
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14247
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14863
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10277
executeUserEntryPoint@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:1646
internal/main/run_main_module@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:138:405
_0x5e2a11@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1427905
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:889971
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1458345]

Node.js v18.20.3

~/project 1s
❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-25T17_55_22_106Z-debug-0.log

~/project 1m 11s
❯ npm run setup && npm run dev

> apartment-dashboard@0.0.0 setup
> prisma generate && prisma db push && npm run seed

[callSiteLocation@
depd@
@
@
@
@
@
@
@
_0x34b746@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:792686
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14247
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14863
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10277
executeUserEntryPoint@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:1646
internal/main/run_main_module@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:138:405
_0x5e2a11@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1427905
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:889971
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1458345]

Node.js v18.20.3

~/project 1s
❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-25T17_59_09_010Z-debug-0.log

~/project 3m 31s
❯ npm run db:setup && npm run dev

> apartment-dashboard@0.0.0 db:setup
> prisma db push && prisma db seed

[callSiteLocation@
depd@
@
@
@
@
@
@
@
_0x34b746@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:792686
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14247
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:14863
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:12820
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:144:10277
executeUserEntryPoint@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:1646
internal/main/run_main_module@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/builtins.ddb8d84d.js:138:405
_0x5e2a11@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1427905
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:889971
@https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-corp-staticblitz.com/blitz.34c588ed.js:40:1458345]

Node.js v18.20.3

~/project 1s
❯ npm config delete proxy
npm config delete https-proxy

~/project 1s
❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-25T18_03_58_024Z-debug-0.log

~/project 3m 31s
❯ 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wjrwh8

### Steps to reproduce

Restart server with proper initialization

package.json
npm install
npm run setup && npm run dev

### Expected behavior

In the latest applications it takes a long time to install the dependencies and also does not install them correctly. It always gives an error and I can never get to create the application

### Platform

```
Browser name = Safari
Full version = 18.0
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
performance.memory = undefined
Username = vmsebas
Chat ID = ea7e1f5cd65a
```

### Additional context

When he is constantly giving mistakes, he should not assume so many, since this according to sustainable, I will give him a chance that is not sustainable in time

**Comment by endocytosis** [comment]
Appreciate the feedback! A potential issue is that [Prisma does not currently compile to Wasm](https://github.com/prisma/prisma/discussions/18428), which would be necessary for compatibility with Bolt. If you are open to using another database we have instructions on using Firebase [here](https://www.youtube.com/watch?v=1GfqnOAKr9M).
