### ISSUE TITLE
Cannot deploy the app I built

### ISSUE THREAD

**Issue by krischulz** [stackblitz/bolt.new#945]
### Describe the bug

Deploy function fails

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-akpgka

### Steps to reproduce

1. I hit the deploy button
2. It fails

### Expected behavior

I expected the deploy function to work. Can someone contact me about this?

### Screen Recording / Screenshot

![Bolt error](https://github.com/user-attachments/assets/16e08b0d-848a-4871-8097-59434ce055e6)

### Platform

```
Browser name = Safari
Full version = 17.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
performance.memory = undefined
Username = krischulz
Chat ID = 65ebf28f9318
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@krischulz this is being tracked in #1022
