### ISSUE TITLE
bolt repeatedly breaks things and costs me millions of tokens in fixing stuff that it did not do properly

### ISSUE THREAD

**Issue by horserankerco** [stackblitz/bolt.new#949]
### Describe the bug

It has burned through over one million tokens just today, fixing things which should not have needed fixing. When I complained that it had fixed the Preview screen when I did not ask it to do that, it totally redeployed my app. I cannot afford to use this product given that you charged me $30 for 10 mill and they are almost half gone and all on fixing mistakes Bolt created.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gz7tdz

### Steps to reproduce

I can't describe them because Bolt deleted all of our chats.

### Expected behavior

I expect Bolt to update things properly, instead of having to do things over and over and over again until it gets it right. Then things work great for a while, and I will ask it to make some TRIVIAL change, because we are basically DONE, but it then BREAKS something, and ends up using hundreds of thousands of tokens trying to fix each simple detail. 

### Screen Recording / Screenshot

https://somup.com/cZ6TYtHd8i

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93229128,
  "usedJSHeapSize": 89673912,
  "jsHeapSizeLimit": 4294705152
}
Username = horserankerco
Chat ID = a8221410e4ad
```

### Additional context

I have seen many other people utter similar complaints, that it does well for a while but then it starts deleting or breaking processes while it is supposedly performing simple updates.

**Comment by leosdad** [comment]
I wonder if they are reading this and the large pile of similar complaints here. Something is seriously wrong and must be addressed urgently. I know they are working on it, but meanwhile I believe they should at least explain what's happening. Shouldn't they also proactively refund the millions of tokens spent trying to fix errors that should't have occurred in the first place?

**Comment by jaywakeford** [comment]
I'm estimating a loss of around 30 million tokens due to these persistent errors. It's extremely concerning to encounter repeated >199k prompt limit messages for simple, one-line queries.

Quickly addressing and resolving these issues is an immediate and non-negotiable requirement. Many of us here are deeply concerned and need the team to fully understand the severity of this situation. We're not just unhappy—significant financial losses are at stake, compounded by lingering frustration from the recent unexpected and substantial token cost increase.

This situation feels like early supporters are bearing the brunt of these problems while the system is being fixed. Moments like this define reputations, and we are watching closely to see how the team responds. We want to succeed together, but right now, the system is not functioning as it should.

Every hour of downtime further devalues each token.

**Comment by kc0tlh** [comment]
@jaywakeford @leosdad @horserankerco, apologies for the frustrating experience during the beta!

We are working aggressively to address these issues (and sharing progress publicly in #678) but we are a small team and ensuring everyone sees the updates has been a challenge!

**Comment by jaywakeford** [comment]
Thank you,  I appreciate the response and continue cheering you on as a team!   It is a fantastic product.   That said I have lost upwards of 30m tokens without clear understanding or resolution during the iterations.   Great news is I just tried running a command and it seems to be live again.     Was a painful last 5 days but happy to be live again.  Have a great week!  Warm regards,  Jay WakefordOn 29 Oct 2024, at 2:11 PM, Alexander Berger ***@***.***> wrote:﻿
@jaywakeford @leosdad @horserankerco, apologies for the frustrating experience during the beta!
We are working aggressively to address these issues (and sharing progress publicly in #678) but we are a small team and ensuring everyone sees the updates has been a challenge!

**Comment by jaywakeford** [comment]
I spoke a little too soon.  Hit a brick wall again with relatively simple requests.   Hopefully the issues are resolved to satisfaction.  Warm regards, Jay WakefordOn 29 Oct 2024, at 3:13 PM, Jay Wakeford ***@***.***> wrote:﻿Thank you,  I appreciate the response and continue cheering you on as a team!   It is a fantastic product.   That said I have lost upwards of 30m tokens without clear understanding or resolution during the iterations.   Great news is I just tried running a command and it seems to be live again.     Was a painful last 5 days but happy to be live again.  Have a great week!  Warm regards,  Jay WakefordOn 29 Oct 2024, at 2:11 PM, Alexander Berger ***@***.***> wrote:﻿
@jaywakeford @leosdad @horserankerco, apologies for the frustrating experience during the beta!
We are working aggressively to address these issues (and sharing progress publicly in #678) but we are a small team and ensuring everyone sees the updates has been a challenge!

**Comment by jaywakeford** [comment]
Hi Alex,

To be absolutely clear, if there’s any perception that I haven’t exercised patience and accepting this being in beta, just review my 900 open issues. I’ve been trying to resolve these for over a week BEFORE escalating, potentially adding to the backlog. My costs are your margins—let that be understood. However, after upgrading to the $100 monthly tier, my patience has turned into a strong sense of being overcharged. When paying such fees, I expect a product that doesn’t fail on this scale.

In today’s chat, I was the one reluctantly asking for resolution steps for issues like these.

Issues #900 and #907 on GitHub.

Honestly, your team should consider addressing and resolving the existing issues before pushing forward with a product launch on platforms like Product Hunt. Development improvements may address future problems, but there should be a concerted effort to properly manage and resolve the current backlog, especially for your early supporters like myself. The team’s inexperience is becoming increasingly evident.

Kind regards,Jay WakefordOn 29 Oct 2024, at 3:13 PM, Jay Wakeford ***@***.***> wrote:﻿Thank you,  I appreciate the response and continue cheering you on as a team!   It is a fantastic product.   That said I have lost upwards of 30m tokens without clear understanding or resolution during the iterations.   Great news is I just tried running a command and it seems to be live again.     Was a painful last 5 days but happy to be live again.  Have a great week!  Warm regards,  Jay WakefordOn 29 Oct 2024, at 2:11 PM, Alexander Berger ***@***.***> wrote:﻿
@jaywakeford @leosdad @horserankerco, apologies for the frustrating experience during the beta!
We are working aggressively to address these issues (and sharing progress publicly in #678) but we are a small team and ensuring everyone sees the updates has been a challenge!

**Comment by leosdad** [comment]
> Hi Alex, To be absolutely clear,,,

Let me add that the team answered here and they are quite active in Discord. At least they seem to be listening. This is the beginning and they have lots pf constructive feedback already so they can steer towards the right direction very quickly. The overwhelming response should tell them that the dev community was eager to put their hands on a product like this, and at least in the surface it appears to deliver what is promises. Nevertheless, what must be stressed is that the product is obviously **not** ready for prime time! I didn't find the word "beta" anywhere in the UI, and I believe they should come clean about it. It's clearly a beta or even a pre-beta (does aanyone still call anything "pre-beta" these days?), it has lots of bugs, don't use it for production, use at your own risk. Also addressing the many refund requests and complaints about lost tokens would be very welcome.

**Comment by kc0tlh** [comment]
@leosdad @jaywakeford we absolutely are listening and moving as fast as we can to improve the product! We had no idea it would be this successful right at launch, and our very small team is hustling to try and keep up with the feedback, but obviously have fallen a bit behind given the torrent of feedback across Github, email, twitter, live chat, reddit and discord.

We are committed to addressing each issue, with a priority on refund requests which are handled via hello@stackblitz.com, and have begun onboarding people to help with support.

Thanks again for the patience and feedback.

P.S. @jaywakeford I responded to those other 2 tickets you mentioned just now as well.
