### ISSUE TITLE
Deploy issue after signing up

### ISSUE THREAD

**Issue by PaulAyre** [stackblitz/bolt.new#952]
### Describe the bug

Once the app was built, I had to subscribe to deploy - now that I've subscribed, there is an unknown error int he deploy

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-ug3px7

### Steps to reproduce

Hit 'deploy'

### Expected behavior

AI output: 
I'll help you deploy the application to Netlify.

Deploy to Netlify

npx vite build
netlify
I'll check the deployment status to get your site URL.

An error occured while streaming this message.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51562377,
  "usedJSHeapSize": 46008829,
  "jsHeapSizeLimit": 4294705152
}
Username = PaulAyre
Chat ID = 264567680bce
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@PaulAyre we're tracking this in #1022
