### ISSUE TITLE
Deploying does not update previous deploy

### ISSUE THREAD

**Issue by mrexodia** [stackblitz/bolt.new#953]
### Describe the bug

Deploying does not update site once claimed

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-appgew

### Steps to reproduce

1. Deploy
2. Claim the site
3. Update the subdomain
4. Deploy again

### Expected behavior

The claimed site should update at the new domain

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57966123,
  "usedJSHeapSize": 54772903,
  "jsHeapSizeLimit": 4294705152
}
Username = mrexodia
Chat ID = 827a038ea6c1
```

**Comment by kc0tlh** [comment]
@mrexodia Thanks for the feedback. We are tracking this in #984.
