### ISSUE TITLE
My project just decided to not load anymore

### ISSUE THREAD

**Issue by rryati20** [stackblitz/bolt.new#955]
### Describe the bug

Was working on it, adding and fixing things, and it wont install dependencies now and I can't do anything let alone preview it. Did not give me the option to undo the work either.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-sf3kew

### Steps to reproduce

Not sure, just not working.

### Expected behavior

Have the project working. I even tried telling it if something is wrong

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/24d76d31-5fb3-479b-8ec8-97a324f07133)

Stuck on this

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 36683121,
  "usedJSHeapSize": 34861429,
  "jsHeapSizeLimit": 4294705152
}
Username = rryati20
Chat ID = 72ba1734056d
```

**Comment by DBNKmedia** [comment]
How did you fix this? I have the same issue on 2 projects.
