### ISSUE TITLE
Deployment Failure in Bolt for Next.js Project

### ISSUE THREAD

**Issue by tomiguns** [stackblitz/bolt.new#956]
### Describe the bug

Deployment of my Next.js app in Bolt fails during npx next build with the error "An error occurred while streaming this message."

Steps Taken to Resolve:

Added environment variables (NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY) in .env.local.

Verified syntax of environment variables.

Attempted npx next build in Bolt, but it consistently fails.

Expected Behavior:
The build command should succeed without errors.

Additional Information:

Environment variables are correct and work locally.

Error message lacks details, making diagnosis difficult.

Error Message:
"An error occurred while streaming this message."

Request:
Please investigate this deployment issue in Bolt. Any help is appreciated.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-f5hyfg

### Steps to reproduce

Open the Bolt environment and load the Next.js project.

Add required environment variables (NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY) in .env.local.

Run the command npx next build in the Bolt environment.

### Expected behavior

he build command should execute successfully without errors, allowing the deployment process to proceed.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106888081,
  "usedJSHeapSize": 86431261,
  "jsHeapSizeLimit": 4294705152
}
Username = tomiguns
Chat ID = 265facf232b1
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by kc0tlh** [comment]
@tomiguns tracking this in #1022
