### ISSUE TITLE
Burning through millions of tokens 

### ISSUE THREAD

**Issue by Endermittens** [stackblitz/bolt.new#958]
### Describe the bug

[plugin:vite:import-analysis] Failed to resolve import "./components/auth/AuthCard" from "src/App.tsx". Does the file exist?

/home/project/src/App.tsx:7:25

21 |  import { LoginModal } from "./components/auth/LoginModal";
22 |  import { auth, logout } from "./lib/firebase";
23 |  import { AuthCard } from "./components/auth/AuthCard";
   |                            ^
24 |  import { Button } from "./components/ui/Button";
25 |  import Navbar from "./components/Navbar";

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-ai3nef

### Steps to reproduce

[testf.txt](https://github.com/user-attachments/files/17528986/testf.txt)
[test5.txt](https://github.com/user-attachments/files/17528987/test5.txt)
[test1.txt](https://github.com/user-attachments/files/17528988/test1.txt)

I believe these are the scripts?

### Expected behavior

For it to resolve the problem and I can keep working on my project

### Screen Recording / Screenshot

![48bc18bcddfe55c7a830188f05e78b8a](https://github.com/user-attachments/assets/7a1f7873-772d-4ad2-a0f2-74f735afebb7)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112432011,
  "usedJSHeapSize": 92101851,
  "jsHeapSizeLimit": 4294705152
}
Username = Gigglebox
Chat ID = f906b0ffe338
```

### Additional context

I don't code this tool is the only thing I have to make my dreams come true, I've spent prob 5-6million tokens trying to fix the issue, for it to redo the code but every character is 1 token and its repeating not fixing the code over and over.

The option to download scripts from bolt.new instead of stackblitz would be helpful, as bolt.new keeps crashing. Right now, I have to manually save each script before moving on to the next update.

**Comment by kc0tlh** [comment]
@Endermittens issue #678 will point you in the right direction!
