### ISSUE TITLE
simple database set up

### ISSUE THREAD

**Issue by Jonny-Carboodle** [stackblitz/bolt.new#963]
### Describe the bug

stuck inan endless loop try to get teh database initalised an dset up.   pretty simnple app. this should be simple.  Bolt seems to get itself stuck in an endless loop of changem, rechange.   tried to take it back step by step to test layer by layer.  but even that is not working.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-f36xmq

### Steps to reproduce

asking it for a database to store versions

### Expected behavior

for versions of the object to be stored,

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80931484,
  "usedJSHeapSize": 57275392,
  "jsHeapSizeLimit": 4294705152
}
Username = Jonny-Carboodle
Chat ID = 90d14d972fb0
```

### Additional context

just trying to build a simple versioning of prompts app.

**Comment by kc0tlh** [comment]
Here's a tutorial on this topic: https://x.com/sulco/status/1850937685512478850
