### ISSUE TITLE
always prompt 'An error occured while streaming this message.'

### ISSUE THREAD

**Issue by sydneyzhong** [stackblitz/bolt.new#974]
### Describe the bug

Let me check the deployment status to understand the specific error.

'An error occured while streaming this message.'

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-x19eul

### Steps to reproduce

Deploy to Netlify 

### Expected behavior

Deploy to Netlify  successfuly

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 43685106,
  "usedJSHeapSize": 40314782,
  "jsHeapSizeLimit": 4294705152
}
Username = sydneyzhong
Chat ID = eeb7a1bc2486
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by ayalpani** [comment]
same. can not deploy anything atm

**Comment by kc0tlh** [comment]
@sydneyzhong thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
