### ISSUE TITLE
Started Posting code in chat instead of IDE

### ISSUE THREAD

**Issue by sohil404** [stackblitz/bolt.new#98]
### Describe the bug

![Screenshot 2024-10-06 at 7 20 55 pm](https://github.com/user-attachments/assets/de8f590e-e9fe-406a-bb3c-94019ce146c7)
Started putting the code into chat, once I assume the context window got too large

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-joox1e

### Steps to reproduce

1. Start a project, 
2. get to second prompt and give a complex prompt with 2-3 actionables
3. Get code overflow in chat

### Expected behavior

To continue creating and adding flies and code in IDE

### Screen Recording / Screenshot

![Screenshot 2024-10-06 at 7 20 55 pm](https://github.com/user-attachments/assets/de8f590e-e9fe-406a-bb3c-94019ce146c7)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101835625,
  "usedJSHeapSize": 77480189,
  "jsHeapSizeLimit": 2172649472
}
Username = sohil404
Chat ID = d235d1af331e
```

**Comment by sohil404** [comment]
Prompted to continue in chat and it did

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

We're tracking this issue internally and will let you know when we have a fix in place.

**Comment by Nemikolh** [comment]
We have deployed a fix for this issue! It should work as expected now. :tada: 

If you run into more issues, feel free to open a new one! :raised_hands:
