### ISSUE TITLE
   Code gets updated with missing information potentially because LLM bias to omit unchanged code ("// ... other sections remain the same")

### ISSUE THREAD

**Issue by berniBZS** [stackblitz/bolt.new#980]
### Describe the bug

When you ask Bolt for a change that affects a local update, the reply of the LLM (Claude 3.1 I assume) tends to omit part of the existing code for the sake of token saving, introducing comments in the unfinished code like "    // ... other sections remain the same", hence deleting parts of the project code for next iterations.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-9z3uqt

### Steps to reproduce

Ask Bolt to generate a project like a directory with sample elements. A lot. Then start working in the project. When a change affects a potentially large file containing the examples, it truncates the examples as you are supposed to only replace the part of code that needs change. 

### Expected behavior

When rewriting a file, it should NEVER use placeholders or omit code.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/b4d31e99-9394-4a85-992e-0254bf38575c)

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79023057,
  "usedJSHeapSize": 74973261,
  "jsHeapSizeLimit": 4294705152
}
Username = berniBZS
Chat ID = eac30059b48e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2862.
