### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by davidtavcar** [stackblitz/bolt.new#983]
I am building an application where during the process I am adding new features.  it happens that new requests destroys already great working items. It is like cycling, you are almost on top and then suddenly the whole mountain is collapsed. I was impressed at the start, but now I am just thinking to cancel my subscription. Lost 2m tokens for nothing.

**Comment by kc0tlh** [comment]
@davidtavcar tips and tricks for better results have been gather from other users and stored in #678
