### ISSUE TITLE
Feature Request: Ability to Update Netlify Deploys, Even After Claiming

### ISSUE THREAD

**Issue by alnutile** [stackblitz/bolt.new#984]
**Is your feature request related to a problem? Please describe:**

Deploy goes to netify which is great but each deployment after should use the same site on netify

**Describe the solution you'd like:**

When I click deploy the first time it makes a site on netify
When I click it after some updates it should continue to deploy to that site.

**Comment by kc0tlh** [comment]
@alnutile this is being tracked in #1022

**Comment by kc0tlh** [comment]
@alnutile Thanks for the feature request! 

In order to make this happen, we will need to add Netlify authentication to the Bolt app so that you can update Deploys even after they are claimed into your user profile in Netlify. **This is in progress and will be shipped in the next few weeks!**

**Comment by kc0tlh** [comment]
Tracking the final resolution in #49
