### ISSUE TITLE
help me finish a union project

### ISSUE THREAD

**Issue by Rubling66** [stackblitz/bolt.new#987]
### Describe the bug

just look at what is going on and help me finish this application.. thanks

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-az28kj

### Steps to reproduce

get better

### Expected behavior

stop repeating and lossing page content

### Screen Recording / Screenshot

none

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 85624589,
  "usedJSHeapSize": 81308405,
  "jsHeapSizeLimit": 4294705152
}
Username = Rubling66
Chat ID = bfd362faa5a9
```

### Additional context

Error:
```
An error occured while streaming this message.
```chech the log

**Comment by kc0tlh** [comment]
@Rubling66 thanks for your patience during this beta period! This issue is being tracked and investigated in #1022 so please subscribe there for updates!
