### ISSUE TITLE
TOKENS

### ISSUE THREAD

**Issue by Filippo295** [stackblitz/bolt.new#99]
Hi, i would like to buy bolt.new pro since i find your product very interesting, but first i need a few clarifications:
- first of all i'd like to know how many tokens/month i have with the premium version. The issue is that the pro plan sais 1M but while chatting with the ai free plan i have 150K and it says "You've used all your remaining tokens.
 Subscribe to Pro for 66x more usage.", 150K*66 is almost 10M, so i would like to know which one is the right amount.
- then i'd like to know if, once i use all my pro monthly tokens, i can buy other tokens for that month
- finally i made a test: i had 5k tokens left of the daily free amount and i wanted to see  how many tokens the conversation below  would use and it used all 5k ending my daily usage. that is barely 30-40 tokens so i would like to know why that is a thing.

thank you very much.
please let me know as soon as possible, since i really want to buy your product
![image](https://github.com/user-attachments/assets/c0fffea0-b98f-40c7-99ea-c2c756a40f39)

**Comment by oalexdoda** [comment]
I'm wondering how to top up on credits too

**Comment by EduardoVieira10** [comment]
My problem is that I'm getting the message “prompt is too long: 204548 tokens > 199999 maximum”. I only signed up for PRO today and I no longer have any tokens? Until when?

**Comment by FastTrackAudio** [comment]
+1 for topping off on credits

**Comment by divparty** [comment]
Urgently need to be able to top up credits, we used ALL our Pro credits in one DAY! this limit is useless for a MONTH!

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks for the comments!

We're working on ways to buy more tokens and see your usage. We'll keep you posted ✨

**Comment by verioussmith** [comment]
+1 For adding more tokens

**Comment by kc0tlh** [comment]
@Filippo295 thanks for the great feedback thread! Everything you brought up has been resolved:

- Pro plan includes 10m tokens per month, and the pricing page now reflects that
- You can now buy more tokens if you run out. Details here: https://x.com/stackblitz/status/1844138865508134999
- You can view your tokens remaining in Settings now as well, details here: https://x.com/stackblitz/status/1844144363384996169

CC: @oalexdoda @FastTrackAudio @divparty @verioussmith 

@vieirex10 you are experiencing a different issue, where your PROJECT is too large for bolt I believe. Please open a new ticket if you are still experiencing that issue and link to your project. Thanks!

Going to go ahead and close this issue now as the token issues have been resolved! Thank you all for your early usage and feedback on our new product, feel free to reach out/create new issues if you have additional feedback as it is very valuable to us!

**Comment by Filippo295** [comment]
@kc0tlh great! thank you very much.

one last thing though: did you also fix the issue where people ran out of pro tokens almost immediately or quick conversations, like the one in my original message, cost 5k? I think that it was the biggest problem of all because, as i said, i love your product, but if token consumption is high to the point that a lot of people run out of pro tokens in the first day, then it is not worth 10$ a day. 

thanks in advance

**Comment by kc0tlh** [comment]
@Filippo295 we are tracking progress on that (and tips and tricks to be more efficient) in #678

**Comment by oalexdoda** [comment]
@kc0tlh I ended u buying 2 accounts before credits were available. Can I top up on one of them at the original pricing & cancel the other or am I better of keeping both accounts instead? I saw pricing went up post-launch.

**Comment by kc0tlh** [comment]
@oalexdoda if you have two accounts on the original pricing, that will be the best deal you can ever access for bolt, so I would hang onto those! Congrats for adopting early :)
