### ISSUE TITLE
Errors while deploying

### ISSUE THREAD

**Issue by anthonym2010** [stackblitz/bolt.new#990]
### Describe the bug

I am having an unsolvable error when deploying the app to Netlify. What could be the problem

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-l6rfzr

### Steps to reproduce

The error is occurring repeatedly .

### Expected behavior

n/a

### Screen Recording / Screenshot

![errors](https://github.com/user-attachments/assets/86c03b24-b97b-437b-85ad-469b804acf54)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84942254,
  "usedJSHeapSize": 79601138,
  "jsHeapSizeLimit": 4294705152
}
Username = anthonym2010
Chat ID = 2d901e9e3096
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
We are investigating this in #1022
