### ISSUE TITLE
token limit exceeded but have 10M tokens

### ISSUE THREAD

**Issue by Ego4sho** [stackblitz/bolt.new#991]
### Describe the bug

I keep running into an issue where the token limit exceeds 199999 but the project just started and only completed a few prompts. Also it persists even when writing a very short prompt. I purchased the $20/month subscription so I should have 10M tokens. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-bu9p8p

### Steps to reproduce

Write any prompt

### Expected behavior

To do something

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76204603,
  "usedJSHeapSize": 74962007,
  "jsHeapSizeLimit": 2160066560
}
Username = Ego4sho
Chat ID = b0de7e5ddb44
```

**Comment by kc0tlh** [comment]
@Ego4sho thanks for the report! We are tracking this (and the temp workarounds) in #1322
