### ISSUE TITLE
Preview Not Working

### ISSUE THREAD

**Issue by icjam** [stackblitz/bolt.new#994]
### Describe the bug

    node_modules/@libsql/client/lib-esm/wasm.js:6:16:
      6 │ const sqlite3 = await sqlite3InitModule();

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-n1agjy

### Steps to reproduce

The application is not showing up on the preview tab once you start the application despite the getting the prompt "The development server is running and you should now see the application working properly."

### Expected behavior

App preview is not showing

### Screen Recording / Screenshot

![tata](https://github.com/user-attachments/assets/79c13f34-8a9d-47fc-af47-a8480cec8a0f)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 139743955,
  "usedJSHeapSize": 128831635,
  "jsHeapSizeLimit": 4294705152
}
Username = deji381
Chat ID = e81f6a3dd7b4
```

**Comment by endocytosis** [comment]
Appreciate the feedback here. We are tracking this issue: [#1791](https://github.com/stackblitz/bolt.new/issues/1791). You can follow there for updates. If you continue to have this problem, posting the requested details on that issue page would be helpful. Thanks!
